### ISSUE TITLE
Question in Heterogeneous LR and Heteogenous NN

### ISSUE THREAD

**Issue by peiyangL** [FederatedAI/FATE#1001]
I noticed that the model training algorithm of Hetero LR is different with the algotithm used by  interactive layer of Hetero NN. Does it mean that the model training algorithm in Hetero LR can not extend to a multi-classfication task?
And can I regard the [Heterogeneous LR with Neural Network](https://github.com/FederatedAI/FATE/blob/master/federatedml/linear_model/logistic_regression/README.md#3-heterogeneous-lr-with-neural-network) as a special case of Hetero NN (in multi-classfication task)?
thanks~

**Comment by tanmc123** [comment]
@peiyangL Hetero-lr can perform one-vs-rest for multi-classfication task. 

As for Heterogeneous LR with Neural Network, it is a sample of combining lr with nn in transfer learning case, which is different from using hetero NN itself.

**Comment by peiyangL** [comment]
> @peiyangL Hetero-lr can perform one-vs-rest for multi-classfication task.
> 
> As for Heterogeneous LR with Neural Network, it is a sample of combining lr with nn in transfer learning case, which is different from using hetero NN itself.

Thanks for your response.
