### ISSUE TITLE
Errors when I tried to run hetero_ftl.

### ISSUE THREAD

**Issue by Qi-Pang** [FederatedAI/FATE#1011]
I got this error when I tried to run `sh run_ftl_dct_standalone.sh 131` in folder `/fate/examples/hetero_ftl`:
`'AttributeError: HeteroFTLTransferVariable' object has no attribute 'generate_transferid'`

And I got `ImportError: cannot import name 'AbsConverge'` when I tried to run `sh run_ftl_ct_standalone.sh 132`.

I used the stand-alone version and it was installed using docker (v1.2.0).

**Comment by vietkhoa86** [comment]
I met the same errors, is there any solution for this error?
