### ISSUE TITLE
what's the function of java code[Doc]

### ISSUE THREAD

**Issue by libratiger** [FederatedAI/FATE#1016]
The fate flow server accept the request, and deal it with the task_executor.py.

All this is done in Python, so what's the function about the java code under `arch` dir. there is no doc about this.

**Comment by zhihuiwan** [comment]
these are the source code for federation and proxy

**Comment by libratiger** [comment]
> these are the source code for federation and proxy

Can you give more Explanation about this?  this maybe helpful for others too. Thanks!
