### ISSUE TITLE
Does FATE support LabelEncoder when building a horizontal federated learning pipeline?

### ISSUE THREAD

**Issue by hibayesian** [FederatedAI/FATE#1026]
Does FATE support LabelEncoder when building a horizontal federated learning pipeline?
E.g.
The label column in PartyA has two values("+1", "-1") and I'd like to use a LabelEncoder to encode them like this: "+1" -> 1, "-1" -> 0;
Meanwhile, the label column in PartyB has two values("Yes", "No") and I'd like to use a LabelEncoder to encode them like this: "Yes" -> 1, "No" -> 0;

I can't find any op like above in FATE.

**Comment by mgqa34** [comment]
FATE<=1.3 version doesn't supply such a function api yet,   but it's a useful api especially training a multi-label task. Thanks for your good advisement, this api will be added in FATE-1.4 or 1.5.

**Comment by weiwee** [comment]
> FATE<=1.3 version doesn't supply such a function api yet, but it's a useful api especially training a multi-label task. Thanks for your good advisement, this api will be added in FATE-1.4 or 1.5.

It can be implemented in DataIO If necessary. But I don't think it‘s good idea for  FATE to works like these.
@mgqa34

**Comment by weiwee** [comment]
label encoded is introduced at version 1.5.0.
