### ISSUE TITLE
homo nn: Object of type 'MetricType' is not JSON serializable

### ISSUE THREAD

**Issue by wang-boyu** [FederatedAI/FATE#1060]
**Describe the bug**
Cannot see model output of homo nn in FATE Board

**To Reproduce**
1. Start a homo nn job and wait for its completion
2. In FATE Board, view the job id with arbiter role
3. Choose `homo_nn_0` and click on `view the outputs` 
4. Have an error dialog with message `Object of type 'MetricType' is not JSON serializable`

**Expected behavior**
Model output similar to that of homo lr

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [Chrome]

**Additional context**

In file `federatedml/linear_model/linear_model_base.py` it is `metric_type="LOSS"` ([link](https://github.com/FederatedAI/FATE/blob/master/federatedml/linear_model/linear_model_base.py#L103))
but
in file `federatedml/nn/homo_nn/enter_point.py` it is `metric_type=MetricType.LOSS` ([link](https://github.com/FederatedAI/FATE/blob/5a614edf7814f20a4a34151ac7b19d2b0eb39b12/federatedml/nn/homo_nn/enter_point.py#L85))

Looks like some refactoring work for `MetricType` is still in-progress...?

**Comment by weiwee** [comment]
> **Describe the bug**
> Cannot see model output of homo nn in FATE Board
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Start a homo nn job and wait for its completion
> 2. In FATE Board, view the job id with arbiter role
> 3. Choose `homo_nn_0` and click on `view the outputs`
> 4. Have an error dialog with message `Object of type 'MetricType' is not JSON serializable`
> 
> **Expected behavior**
> Model output similar to that of homo lr
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Ubuntu 18.04]
> * Browser [Chrome]
> 
> **Additional context**
> 
> In file `federatedml/linear_model/linear_model_base.py` it is `metric_type="LOSS"` ([link](https://github.com/FederatedAI/FATE/blob/master/federatedml/linear_model/linear_model_base.py#L103))
> but
> in file `federatedml/nn/homo_nn/enter_point.py` it is `metric_type=MetricType.LOSS` ([link](https://github.com/FederatedAI/FATE/blob/5a614edf7814f20a4a34151ac7b19d2b0eb39b12/federatedml/nn/homo_nn/enter_point.py#L85))
> 
> Looks like some refactoring work for `MetricType` is still in-progress...?


Thank you for your detailed description. This bug is related to another bug of fateflow. You can temporarily change `MetricType.LOSS` to "LOSS"  to make it workaround.

**Comment by wang-boyu** [comment]
> You can temporarily change `MetricType.LOSS` to "LOSS" to make it workaround.

Yes already did this from my side. Thanks for your reply and look forward to your future releases!

Closing the issue now.
