### ISSUE TITLE
modify fate_flow chinese doc 

### ISSUE THREAD

**Issue by wpdata** [FederatedAI/FATE#1078]
**Describe the bug**
The doc have a mistake 
**To Reproduce**
1. Go to 'https://github.com/FederatedAI/FATE/blob/master/fate_flow/doc/fate_flow_cli.md'
2.   Scroll down to  'component_output_data' section 
3. The sample 'python fate_flow_client.py -f component_output_model -j $job_id -r $role -p $party_id -cpn $component_name -o $output_path' have a mistake 
4. See error is  'component_output_model' it's should ' component_output_data' 

**Expected behavior**
modify 'component_output_model'  to  ' component_output_data' 

**Screenshots**
![image](https://user-images.githubusercontent.com/10710148/76164197-ecd3bc80-6187-11ea-885d-0a0fedf7573b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. linux]
 - Version [e.g. 1.2]

**Comment by zhihuiwan** [comment]
Thank you for your correction.
