### ISSUE TITLE
execute the fate_flow  -f download  have a Nonetype error 

### ISSUE THREAD

**Issue by wpdata** [FederatedAI/FATE#1080]
**Describe the bug**
According to documents the fate_flow -f download need four parameter . the doc example :

#### 7.How to download a table which has been uploaded before
 > python fate_flow_client.py -f download -n table_namespace -t table_name -w work_mode -o save_file  

but if execute this script ,will return a error :

![微信图片_20200308223633](https://user-images.githubusercontent.com/10710148/76164886-4d192d00-618d-11ea-9fb6-f730aae6953a.png)

**To Reproduce**
1. execute  'python fate_flow_client.py -f download -n table_namespace -t table_name -w work_mode -o save_file  '
2 See error

**Expected behavior**
Expected behavior is download data to outputdata .because the python scrip "FATE\fate_flow\utils\download.py" lines 49 :
  
fout.write(key + self.parameters.get("delimitor", ",") + value + "\n")

the  self.parameters.get("delimitor", ",")  there is no judgment that the variable delimitor is None 

**Desktop (please complete the following information):**
 - OS: [e.g. linux]
 - Browser [e.g. chrome]
 - Version [e.g. 1.2]

**Comment by zhihuiwan** [comment]
Please refer to the document:https://github.com/FederatedAI/FATE/blob/master/fate_flow/doc/fate_flow_cli.md#download
