### ISSUE TITLE
More sampling methods?

### ISSUE THREAD

**Issue by wang-boyu** [FederatedAI/FATE#1084]
**Is your feature request related to a problem? Please describe.**

Currently two sampling modes are supported: `RandomSampler` and `StratifiedSampler`, both of which are using [sklearn.utils.resample](https://scikit-learn.org/stable/modules/generated/sklearn.utils.resample.html), which is essentially based on bootstrapping.

In practice however, if the data is highly imbalanced (i.e., less than 1% of the data belongs to class A whereas rest 99% is class B), this might not be sufficient - thus more sophisticated methods such as [SMOTE](https://imbalanced-learn.readthedocs.io/en/stable/generated/imblearn.over_sampling.SMOTE.html) are used.

**Describe the solution you'd like**

More samplers please!

**Describe alternatives you've considered**

Probably we can add more samplers similarly to what we currently have: a wrapper on top of other sampling modules such as [imbalanced-learn](https://imbalanced-learn.readthedocs.io/en/stable/api.html).

**Additional context**

None.

**Comment by Simonsxin** [comment]
Hello！
I would like to know how FATE realizes the sampling methods. 
Is it necessary to make an alignment for sample's id (Private Set Intersection), before we perform the StratifiedSampler? 
And in the code of StratifiedSampler, I didn't find the part for sever to generate a ratio for each clients. It seems that we need to input the sample ratio for each clients.  Is that the case?
