### ISSUE TITLE
when I build docker meet a problem 部署docker的时候遇到一个问题

### ISSUE THREAD

**Issue by xineting** [FederatedAI/FATE#1120]
when I build the Docker images of FATE components, just use this command "bash build_cluster_docker.sh all", I meet this problem "Unable to find image 'maven:3.6-jdk-8' locally‘

我在单机部署docker时遇到一个问题“Unable to find image 'maven:3.6-jdk-8' locally‘

![8ECCB4536B1266A52860AD31BC41ADE9](https://user-images.githubusercontent.com/29162161/77231167-38e51f00-6bd4-11ea-855f-1cf42c34813c.jpg)

**Comment by weiwee** [comment]
Not issue related to FATE, Google Docker usage first please!
