### ISSUE TITLE
binning 不支持label为非二值的情况

### ISSUE THREAD

**Issue by miki-zmq** [FederatedAI/FATE#1121]
问题：binning 因为只支持二分类数据的IV值计算（raise ValueError("Iv calculation support binary-data only in this version.")），所以当我的场景是 label是连续或者多分，且我仅需要分箱，不需要知道其IV值时，就用不了binning组件。
方案：希望 binning中的分箱过程和IV值过程解耦，可通过配置参数来选择，如 二分时分箱+IV计算、多分时分箱+不计算IV、label连续值+不计算IV。

**Comment by tanmc123** [comment]
@miki-zmq You are asking if federated feature-binning can apply un-supervised binning of multi-class or regression data. Currently, this is not supported. But thanks for your suggestion very much. Hopefully, this function can be applied in FATE-v1.5 or later.

**Comment by tanmc123** [comment]
> @miki-zmq You are asking if federated feature-binning can apply un-supervised binning of multi-class or regression data. Currently, this is not supported. But thanks for your suggestion very much. Hopefully, this function can be applied in FATE-v1.5 or later.

Already implemented.
