### ISSUE TITLE
hetero secureboost: large disk usage by egg lmdb

### ISSUE THREAD

**Issue by wang-boyu** [FederatedAI/FATE#1124]
**Describe the bug**
The disk usage of hetero secureboost is around 500GB during training.

**To Reproduce**
1. Train a hetero secureboost model with the following parameters:
    - "num_trees": 200
    - "encrypt_param": {"method": "IterativeAffine"}
    - "validation_freqs": null
2. After training finishes, check the disk usage of egg service from both guest and host sides:
    - guest:
    ```bash
    $ cd /data/projects/fate/confs-10000/confs/egg/data-dir/lmdb
    $ du -hs 202003230126391918532_secureboost_0_guest_10000/
    507G    202003230126391918532_secureboost_0_guest_10000/
    ```
    - host:
    ```bash
    $ cd /data/projects/fate/confs-9999/confs/egg/data-dir/lmdb
    $ du -hs 202003230126391918532_secureboost_0_host_9999/
    474G    202003230126391918532_secureboost_0_host_9999/
    ```

**Expected behavior**
Is this expected?

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Smartphone (please complete the following information):**
 N.A.

**Additional context**
- FATE is deployed with `docker-compose` on one guest and one host
- Data size: guest: `454,902 x 17`; host: `454,902 x 16`
- FATE version: v1.3.0
- Related issue: #648 (which was closed and reopened)

**Comment by dylan-fan** [comment]
After the task, whether the space has been released？

**Comment by wang-boyu** [comment]
Unfortunately no. I had to remove the folders manually.

**Comment by wang-boyu** [comment]
@dylan-fan Looks like this has been fixed. Shall I go ahead and close this issue?

**Comment by weiwee** [comment]
fix already, close issue
