### ISSUE TITLE
standalone-deploy install FATE in host, error in init.sh script

### ISSUE THREAD

**Issue by Neah-Ko** [FederatedAI/FATE#1127]
- Went over the process described at https://github.com/FederatedAI/FATE/tree/master/standalone-deploy
Option 2) install FATE in host
Running the command `source init.sh init` caused errors looking like this :
`service.sh: 65: service.sh: [[: not found` and services not starting.

- It is because string conditions like `[[ cond ]]` are bash specific and the script init.sh calls the script service.sh like this `sh  service.sh restart`.
sh is not bash and it does not implements `[[. which causes errors like the one I mentioned above.

- Could complete the install by replacing ocurences of `sh` calls by `bash`

**Comment by paulbaogang** [comment]
Excute commonds:
yum -y install dos2unix
dos2unix  service.sh
