### ISSUE TITLE
横向联邦100w数据量在做predict的时候报错【ERROR: 'NoneType' object has no attribute 'unboxed'" 】

### ISSUE THREAD

**Issue by JackLi529** [FederatedAI/FATE#1157]
"2020-04-13 09:31:55,560 - homo_lr_arbiter.py[line:95] - INFO: Start predict task"
82"2020-04-13 09:31:55,901 - task_executor.py[line:132] - ERROR: 'NoneType' object has no attribute 'unboxed'"
83Traceback (most recent call last):
84File "/home/fate/fate/python/fate_flow/driver/task_executor.py", line 119, in run_task
85run_object.run(parameters, task_run_args)
86File "/home/fate/fate/python/federatedml/model_base.py", line 91, in run
87this_data_output = func(*params)
88File "/home/fate/fate/python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_arbiter.py", line 100, in predict
89LOGGER.debug("Loaded arbiter model: {}".format(self.model_weights.unboxed))
90AttributeError: 'NoneType' object has no attribute 'unboxed'
91"2020-04-13 09:31:55,951 - api_utils.py[line:69] - INFO: grpc api response: header {

**Comment by tanmc123** [comment]
@JackLi529 According to the parameters settings, max_iter has been set as 1 which may cause fail to aggregate model in arbiter. Therefore, arbiter cannot access the aggregated model yet before entering predict process.

**Comment by tanmc123** [comment]
However, this is still a problem for arbiter fail to aggregate. This will be fix in next version.
