### ISSUE TITLE
when I resubmitted  a job several times , why got the different results？

### ISSUE THREAD

**Issue by Teslaxhub** [FederatedAI/FATE#1158]
when I resubmitted  a secureboost  job several times , I hope to get the same KS & AUC values,  but the results were different for all the jobs。

So how can I find the reason?

**Comment by kaikaokao** [comment]
I got the same problem when I use homo-stb module. I think this is  caused by the error of floating point number calculation，so I close secure_aggregator by changing code , it looks like resolved。Is their some auther who can fix this problem,or tell us some about it。

**Comment by tanmc123** [comment]
@kaikaokao @Teslaxhub 

The uncertainty of result is caursed by binning module embeded in sbt/homo-sbt component which has nothing to do with secure-aggregator. 

In binning module, data is supposed to be sorted during which some data will be ignored for higher efficiency. This process is completed by mapPartitions & reduce function. And the uncertainty is caursed by uncertainty order of reduce. Different reduce order will abandon different data which caurse tiny difference of final result. 

A way to reduce this influence is setting a smaller error in binning parameters but it still cannot guarantee full consistency between results.  

Theoretically, this problem can be solved if the data is allocated in one partition only.

**Comment by kaikaokao** [comment]
@tanmc123 I have 2 questions。
1：U sad the uncertainty is caursed by uncertainty order of reduce. when do feature binning . Can you exlpian some detail to help dudestand why the same data and the same binning function has uncertainty order of reduce?  OR gave the mapPartitions & reduce function code in fate（I try to find them but failed）.
2：U sad the problem has nothing to do with secure-aggregator . But in my understand homo_sbt moudle use secure_aggregator  to protect data safe. Secure_aggregator is implemetd by add a random data to Histogram in every party , but the sum of all random data in party is equal 0, so arbiter can get the sum  Histogram ,but can not get Histogram in one party. In computing system，even we set a+b = 0 ,But  A+a+B+b is not equal A+B  when use float . There will be some residual , and it will deifferent when a and b is defferent. So I think this will lead-in  a smaller accumulative error，and with computing step going on ，it will become bigger and bigger . The  accumulative error could make the result different , and I confus about it all the time。Is there some misunderstand of my think,can you explain how do you resolve this problem。
