### ISSUE TITLE
跑横向逻辑回归训练模型时arbiter方出现错误

### ISSUE THREAD

**Issue by jennylove10** [FederatedAI/FATE#1159]
fate版本1.3，提交test_homolr_train_job.conf.json任务在homo_lr_0出错
在fateboard 界面host和guest方log显示无误，arbiter 端出现error，将算法配置中CV_param的shuffle由原来的true改成false后成功跑通。请教一下各位大神，这是什么原因？
log如下：
 ERROR: <_Rendezvous of RPC that terminated with:
2 status = StatusCode.INTERNAL
3 details = "192.168.22.141:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
4 at com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:69)
5 at com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:44)
6 at com.webank.ai.eggroll.framework.roll.manager.RollSessionManager.initializeEgg(RollSessionManager.java:112)
7 at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl$ProcessServiceTemplate.run(RollProcessServiceImpl.java:344)
8 at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
9 at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl.mapValues(RollProcessServiceImpl.java:117)
10 at com.webank.ai.eggroll.api.computing.processor.ProcessServiceGrpc$MethodHandlers.invoke(ProcessServiceGrpc.java:976)
11 at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
12 at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
13 at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
14 at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
15 at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
16 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18 at java.lang.Thread.run(Thread.java:748)
19 Caused by: java.lang.reflect.InvocationTargetException
20 at com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)
21 at com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:67)
22 ... 14 more
23 Caused by: io.grpc.StatusRuntimeException: INTERNAL: 192.168.22.141:7888: java.lang.IllegalStateException: The attempt resulted in a result. There is no exception
24 at com.webank.ai.eggroll.core.retry.impl.attempt.context.ResultAttemptContext.getExceptionCause(ResultAttemptContext.java:63)
25 at com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:29)
26 at com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:24)
27 at com.webank.ai.eggroll.core.retry.Retryer.call(Retryer.java:106)
28 at com.webank.ai.eggroll.framework.egg.manager.EggSessionManager.getOrCreateSession(EggSessionManager.java:126)
29 at com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.lambda$getOrCreateSession$0(EggSessionServiceImpl.java:38)
30 at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
31 at com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.getOrCreateSession(EggSessionServiceImpl.java:36)
32 at com.webank.ai.eggroll.api.framework.egg.SessionServiceGrpc$MethodHandlers.invoke(SessionServiceGrpc.java:349)
33 at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
34 at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
35 at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
36 at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
37 at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
38 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
39 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
40 at java.lang.Thread.run(Thread.java:748)
41  
42 at io.grpc.Status.asRuntimeException(Status.java:526)
43 at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
44 at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
45 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
46 at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
47 at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
48 at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
49 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
50 at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
51 at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
52 at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
53 at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
54 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
55 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
56 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
57 ... 5 more
58 "
59 debug_error_string = "{"created":"@1586767213.483875340","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"192.168.22.141:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:69)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:44)\n\tat com.webank.ai.eggroll.framework.roll.manager.RollSessionManager.initializeEgg(RollSessionManager.java:112)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl$ProcessServiceTemplate.run(RollProcessServiceImpl.java:344)\n\tat com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl.mapValues(RollProcessServiceImpl.java:117)\n\tat com.webank.ai.eggroll.api.computing.processor.ProcessServiceGrpc$MethodHandlers.invoke(ProcessServiceGrpc.java:976)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:67)\n\t... 14 more\nCaused by: io.grpc.StatusRuntimeException: INTERNAL: 192.168.22.141:7888: java.lang.IllegalStateException: The attempt resulted in a result. There is no exception\n\tat com.webank.ai.eggroll.core.retry.impl.attempt.context.ResultAttemptContext.getExceptionCause(ResultAttemptContext.java:63)\n\tat com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:29)\n\tat com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:24)\n\tat com.webank.ai.eggroll.core.retry.Retryer.call(Retryer.java:106)\n\tat com.webank.ai.eggroll.framework.egg.manager.EggSessionManager.getOrCreateSession(EggSessionManager.java:126)\n\tat com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.lambda$getOrCreateSession$0(EggSessionServiceImpl.java:38)\n\tat com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)\n\tat com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.getOrCreateSession(EggSessionServiceImpl.java:36)\n\tat com.webank.ai.eggroll.api.framework.egg.SessionServiceGrpc$MethodHandlers.invoke(SessionServiceGrpc.java:349)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\n\tat io.grpc.Status.asRuntimeException(Status.java:526)\n\tat io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)\n\tat io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)\n\tat io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)\n\t... 5 more\n","grpc_status":13}"
60 >"
61 Traceback (most recent call last):
62 File "/home/fate/projects/fate/python/fate_flow/driver/task_executor.py", line 119, in run_task
63 run_object.run(parameters, task_run_args)
64 File "/home/fate/projects/fate/python/federatedml/model_base.py", line 91, in run
65 this_data_output = func(*params)
66 File "/home/fate/projects/fate/python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_arbiter.py", line 116, in predict
67 predict_wx = cipher.distribute_decrypt(encrypted_predict_wx)
68 File "/home/fate/projects/fate/python/federatedml/secureprotol/encrypt.py", line 68, in distribute_decrypt
69 decrypt_table = X.mapValues(lambda x: self.decrypt(x))
70 File "/home/fate/projects/fate/python/arch/api/utils/profile_util.py", line 31, in _fn
71 rtn = func(*args, **kwargs)
72 File "/home/fate/projects/fate/python/arch/api/table/eggroll/table_impl.py", line 113, in mapValues
73 return DTable(self._dtable.mapValues(func), session_id=self._session_id)
74 File "/home/fate/projects/fate/eggroll/python/eggroll/api/cluster/eggroll.py", line 271, in mapValues
75 return _EggRoll.get_instance().map_values(self, func)
76 File "/home/fate/projects/fate/eggroll/python/eggroll/api/cluster/eggroll.py", line 600, in map_values
77 return self.__do_unary_process_and_create_table(table=_table, user_func=func, stub_func=self.proc_stub.mapValues)
78 File "/home/fate/projects/fate/eggroll/python/eggroll/api/cluster/eggroll.py", line 680, in __do_unary_process_and_create_table
79 resp = self.__do_unary_process(table=table, user_func=user_func, stub_func=stub_func)
80 File "/home/fate/projects/fate/eggroll/python/eggroll/api/cluster/eggroll.py", line 677, in __do_unary_process
81 return stub_func(process)
82 File "/home/fate/projects/fate/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
83 return _end_unary_response_blocking(state, call, False, None)
84 File "/home/fate/projects/fate/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
85 raise _Rendezvous(state, None, None, deadline)
86 grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
87 status = StatusCode.INTERNAL
88 details = "192.168.22.141:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
89 at com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:69)
90 at com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:44)
91 at com.webank.ai.eggroll.framework.roll.manager.RollSessionManager.initializeEgg(RollSessionManager.java:112)
92 at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl$ProcessServiceTemplate.run(RollProcessServiceImpl.java:344)
93 at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
94 at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl.mapValues(RollProcessServiceImpl.java:117)
95 at com.webank.ai.eggroll.api.computing.processor.ProcessServiceGrpc$MethodHandlers.invoke(ProcessServiceGrpc.java:976)
96 at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
97 at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
98 at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
99 at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
100 at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
101 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
102 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
103 at java.lang.Thread.run(Thread.java:748)
104 Caused by: java.lang.reflect.InvocationTargetException
105 at com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)
106 at com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:67)
107 ... 14 more
108 Caused by: io.grpc.StatusRuntimeException: INTERNAL: 192.168.22.141:7888: java.lang.IllegalStateException: The attempt resulted in a result. There is no exception
109 at com.webank.ai.eggroll.core.retry.impl.attempt.context.ResultAttemptContext.getExceptionCause(ResultAttemptContext.java:63)
110 at com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:29)
111 at com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:24)
112 at com.webank.ai.eggroll.core.retry.Retryer.call(Retryer.java:106)
113 at com.webank.ai.eggroll.framework.egg.manager.EggSessionManager.getOrCreateSession(EggSessionManager.java:126)
114 at com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.lambda$getOrCreateSession$0(EggSessionServiceImpl.java:38)
115 at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
116 at com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.getOrCreateSession(EggSessionServiceImpl.java:36)
117 at com.webank.ai.eggroll.api.framework.egg.SessionServiceGrpc$MethodHandlers.invoke(SessionServiceGrpc.java:349)
118 at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
119 at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
120 at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
121 at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
122 at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
123 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
124 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
125 at java.lang.Thread.run(Thread.java:748)
126  
127 at io.grpc.Status.asRuntimeException(Status.java:526)
128 at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
129 at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
130 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
131 at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
132 at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
133 at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
134 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
135 at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
136 at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
137 at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
138 at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
139 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
140 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
141 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
142 ... 5 more
143 "
144 debug_error_string = "{"created":"@1586767213.483875340","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"192.168.22.141:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:69)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:44)\n\tat com.webank.ai.eggroll.framework.roll.manager.RollSessionManager.initializeEgg(RollSessionManager.java:112)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl$ProcessServiceTemplate.run(RollProcessServiceImpl.java:344)\n\tat com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.server.RollProcessServiceImpl.mapValues(RollProcessServiceImpl.java:117)\n\tat com.webank.ai.eggroll.api.computing.processor.ProcessServiceGrpc$MethodHandlers.invoke(ProcessServiceGrpc.java:976)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.EggSessionServiceClient.getOrCreateSession(EggSessionServiceClient.java:67)\n\t... 14 more\nCaused by: io.grpc.StatusRuntimeException: INTERNAL: 192.168.22.141:7888: java.lang.IllegalStateException: The attempt resulted in a result. There is no exception\n\tat com.webank.ai.eggroll.core.retry.impl.attempt.context.ResultAttemptContext.getExceptionCause(ResultAttemptContext.java:63)\n\tat com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:29)\n\tat com.webank.ai.eggroll.core.retry.RetryException.<init>(RetryException.java:24)\n\tat com.webank.ai.eggroll.core.retry.Retryer.call(Retryer.java:106)\n\tat com.webank.ai.eggroll.framework.egg.manager.EggSessionManager.getOrCreateSession(EggSessionManager.java:126)\n\tat com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.lambda$getOrCreateSession$0(EggSessionServiceImpl.java:38)\n\tat com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)\n\tat com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.getOrCreateSession(EggSessionServiceImpl.java:36)\n\tat com.webank.ai.eggroll.api.framework.egg.SessionServiceGrpc$MethodHandlers.invoke(SessionServiceGrpc.java:349)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\n\tat io.grpc.Status.asRuntimeException(Status.java:526)\n\tat io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)\n\tat io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)\n\tat io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)\n\t... 5 more\n","grpc_status":13}"

**Comment by tanmc123** [comment]
I suspect it was because some server are down. Please have a check if roll service(whose port number is 8011) is still here or not. And restart all the services before another try.

**Comment by jennylove10** [comment]
> I suspect it was because some services are down. Please have a check if roll service(whose port number is 8011) is still here or not. And restart all the services before another try.

好的，谢谢

**Comment by gaolje** [comment]
> > I suspect it was because some services are down. Please have a check if roll service(whose port number is 8011) is still here or not. And restart all the services before another try.
> 
> 好的，谢谢

请问在跑横向逻辑回归时有遇到list index out of range这个错误吗？host guest 第一步dataio就报错了……

**Comment by SKYYKS-9998** [comment]
> > > I suspect it was because some services are down. Please have a check if roll service(whose port number is 8011) is still here or not. And restart all the services before another try.
> > 
> > 
> > 好的，谢谢
> 
> 请问在跑横向逻辑回归时有遇到list index out of range这个错误吗？host guest 第一步dataio就报错了……

您好，我也遇到了这个错误，请问您解决了吗
