### ISSUE TITLE
 hetero_nn model : the  error of Backward Propagation Part II in README.md 

### ISSUE THREAD

**Issue by ZhanqiLiu** [FederatedAI/FATE#1162]
According to the papers and code, the description should be modified as follows， @ is the modification location, the total error number is 16 :
1、Party B calculates the error delta_act of activation function's output by delta.
2、Party B propagates delta_bottomB = delta_act * W_B to bottom model, then updates W_B(W_B -= eta * delta_act * alpha_B).
3、Party B generates noise epsilon_B, calculates [delta_act* @alpha_A + epsilon_B] and sends it to party A.
4、Party A encrypts epsilon_acc, sends [epsilon_acc] to party B.
Then party @A decrypts the received value, generates noise epsilon_A, adds epsilon_A / eta to decrypted result(delta_act * @alpha_A  + epsilon_B + epsilon_A / eta) and epsilon_A to accumulate noise epsilon_acc(epsilon_acc += epsilon_A). Party A sends the addition result to party B. (delta_act * @alpha_A + epsilon_B + epsilon_A / eta)
5、Party B receives [epsilon_acc] and delta_act * @alpha_A  + epsilon_B + epsilon_A / eta. Firstly it sends party A's bottom model output' error [ @delta_act * @(W_A + epsilon_acc)] to host. Secondly updates W_A -= eta * (delta_act * alpha_A + epsilon_B + epsilon_A / eta - epsilon_B @) = eta * delta_act * @alpha_A  @+ @epsilon_A,  @ W_A =W_TRUE - epsilon_acc. Where W_TRUE represents the actually weights.
6、Party A decrypts [@delta_act * (W_A + @epsilon_acc)] and passes @delta_act * (W_A + @epsilon_acc) to its bottom model.

**Comment by mgqa34** [comment]
@ZhanqiLiu Thanks for your detailed modification comments，we will fix it soon. Sorry for misleading,  refer to the attached flow diagram will be much better.
