### ISSUE TITLE
why choose Paillier encryption to do this?

### ISSUE THREAD

**Issue by yeverwang** [FederatedAI/FATE#1167]
As I know , paillier encryption requires  expensive operations in order to encrypt and decrypt. Its ciphertexts also have relatively large plaintext and ciphertext spaces, which leads to a large communication expansion when the values being encrypted are small. For example, the short number summed are in the range of 10 bits, then using Paillier results in approximately 400× ciphertext expansion compared to the plaintext.
Of course, the Paillier is able to slotting ,just be divided by k, but  the slots need to be large enough to accomodate the associated values, with some extra bits to allow summing without overflowing into the next slot, and some further additional bits to allow random masking.only half the plaintext space can be used for slots, since otherwise there is no way to rotate the lowest slot into the highest slot’s position without overflowing the ciphertext space. 
If you must do this , use Damgard-Jurik optimizations to impove it .

**Comment by renzhenghang** [comment]
could you describe what is "slotting" and why it is not suitable for Paillier encryption?

**Comment by yeverwang** [comment]
Slotting just use k to segment the plaintext in Paillier ,  it means the plaintext = (2^(k-1))pk+...+(2^0)p1
it is not suitable for fateAI， one reason is the speed of calculation slow ， the second reason is that the price of traffic is much higher than the calculated price。maybe 20 times higher than it ,so it is very important to keep the ciphertext short.
