### ISSUE TITLE
单机fate1.3版用自己数据跑模型第一步dataio_0出错

### ISSUE THREAD

**Issue by jennylove10** [FederatedAI/FATE#1172]
在单机版上用自己数据跑横向纵向模型，都卡在的第一步dataio_0,同样的数据在集群版上可以成功跑通，请教一下各位是什么原因会出现这种情况？
![image](https://user-images.githubusercontent.com/62371712/79815839-4ac50800-83b4-11ea-88cf-b6fbfbf937c8.png)
LOG:
 "2020-04-20 22:32:09,381 - task_executor.py[line:132] - ERROR: Attempt to operate on closed/deleted/dropped object."
2 Traceback (most recent call last):
3 File "/home/fate/standalone-fate-master-1.3.0/fate_flow/driver/task_executor.py", line 121, in run_task
4 tracker.save_output_data_table(output_data, task_output_dsl.get('data')[0] if task_output_dsl.get('data') else 'component')
5 File "/home/fate/standalone-fate-master-1.3.0/fate_flow/manager/tracking.py", line 178, in save_output_data_table
6 name='{}_persistent'.format(data_table._name))
7 File "/home/fate/standalone-fate-master-1.3.0/arch/api/utils/profile_util.py", line 31, in _fn
8 rtn = func(*args, **kwargs)
9 File "/home/fate/standalone-fate-master-1.3.0/arch/api/table/eggroll/table_impl.py", line 56, in save_as
10 persistent_engine=persistent_engine)
11 File "/home/fate/standalone-fate-master-1.3.0/eggroll/api/standalone/eggroll.py", line 678, in save_as
12 dup.put_all(self.collect(use_serialize=use_serialize), use_serialize=use_serialize)
13 File "/home/fate/standalone-fate-master-1.3.0/eggroll/api/standalone/eggroll.py", line 633, in put_all
14 for k, v in kv_list:
15 File "/home/fate/standalone-fate-master-1.3.0/eggroll/api/standalone/eggroll.py", line 710, in _merge
16 if it.next():
17 lmdb.Error: Attempt to operate on closed/deleted/dropped object.

**Comment by XYT2000** [comment]
> 在单机版上用自己数据跑横向纵向模型，都卡在的第一步dataio_0,同样的数据在集群版上可以成功跑通，请教一下各位是什么原因会出现这种情况？
> ![image](https://user-images.githubusercontent.com/62371712/79815839-4ac50800-83b4-11ea-88cf-b6fbfbf937c8.png)
> LOG:
> "2020-04-20 22:32:09,381 - task_executor.py[line:132] - ERROR: Attempt to operate on closed/deleted/dropped object."
> 2 Traceback (most recent call last):
> 3 File "/home/fate/standalone-fate-master-1.3.0/fate_flow/driver/task_executor.py", line 121, in run_task
> 4 tracker.save_output_data_table(output_data, task_output_dsl.get('data')[0] if task_output_dsl.get('data') else 'component')
> 5 File "/home/fate/standalone-fate-master-1.3.0/fate_flow/manager/tracking.py", line 178, in save_output_data_table
> 6 name='{}_persistent'.format(data_table._name))
> 7 File "/home/fate/standalone-fate-master-1.3.0/arch/api/utils/profile_util.py", line 31, in _fn
> 8 rtn = func(*args, **kwargs)
> 9 File "/home/fate/standalone-fate-master-1.3.0/arch/api/table/eggroll/table_impl.py", line 56, in save_as
> 10 persistent_engine=persistent_engine)
> 11 File "/home/fate/standalone-fate-master-1.3.0/eggroll/api/standalone/eggroll.py", line 678, in save_as
> 12 dup.put_all(self.collect(use_serialize=use_serialize), use_serialize=use_serialize)
> 13 File "/home/fate/standalone-fate-master-1.3.0/eggroll/api/standalone/eggroll.py", line 633, in put_all
> 14 for k, v in kv_list:
> 15 File "/home/fate/standalone-fate-master-1.3.0/eggroll/api/standalone/eggroll.py", line 710, in _merge
> 16 if it.next():
> 17 lmdb.Error: Attempt to operate on closed/deleted/dropped object.

您好，调低partition个数即可
