### ISSUE TITLE
任务突然僵死，日志不再增加

### ISSUE THREAD

**Issue by Origin-Draven** [FederatedAI/FATE#1233]
环境配置：centos7，fate1.3，8万数据（训练/验证=6/2），150特征，20棵树，双机部署，外网ip访问，带宽200M
问题描述：训练任务在 secureboost 迭代时会突然僵死不动，主要表现为日志不再增加，cpu使用率较低，且不会自己失败，关闭需要人工干预。同样的参数配置，也有可能是第一轮也可能是最后一轮，甚至有可能再 predict 的时候，发生位置不确定的。重新提交又可以正常跑。由于日志没有报错，无法定位原因
截图示例：
![image](https://user-images.githubusercontent.com/20585352/80296991-d1f9ed80-87b1-11ea-89c2-adf3b50a5be3.png)

![image](https://user-images.githubusercontent.com/20585352/80296999-e342fa00-87b1-11ea-840b-6009d159418f.png)

**Comment by Origin-Draven** [comment]
![微信图片_20200426113459](https://user-images.githubusercontent.com/20585352/80297020-11c0d500-87b2-11ea-9c82-99407dbf783a.png)
![微信图片_20200426113531](https://user-images.githubusercontent.com/20585352/80297022-14bbc580-87b2-11ea-9913-ab1e116a5118.png)

**Comment by changjiangbailang** [comment]
我也碰到了僵死的问题，你可以把debug的日志也粘出来。

**Comment by Origin-Draven** [comment]
> 我也碰到了僵死的问题，你可以把debug的日志也粘出来。

上面两张图就是 两个任务的debug 的日志了，没有报错，贴了最后的情况的

**Comment by dulante00** [comment]
这种僵尸的情况，除了重启FATE服务，还有别的解决办法吗？

**Comment by Origin-Draven** [comment]
> 这种僵尸的情况，除了重启FATE服务，还有别的解决办法吗？

看情况，如果fate挂了，新提交任务卡在dataio，那只能重启了。不过有时候等好久可能又可以用了。如果是任务自己失去连接挂了就只能手动kill了，页面上处理不了只能处理数据库里面的了
