### ISSUE TITLE
Online prediction is reported {"code": "103", "message": "SYSTEM_ERROR"} 

### ISSUE THREAD

**Issue by WillJiang12** [FederatedAI/FATE#1269]
**Describe the bug**
Online prediction is reported {"code": "103", "message": "SYSTEM_ERROR"} 

**To Reproduce**
1.[root@cdc29a4a09ad fate_flow]# vi examples/test_hetero_lr_job_conf.json
{
    "initiator": {
        "role": "guest",
        "party_id": 9999
    },
    "job_parameters": {
        "work_mode": 1
    },
    "role": {
        "guest": [9999],
        "host": [10000],
        "arbiter": [10000]
    },
    "role_parameters": {
        "guest": {
            "args": {
                "data": {
                    "train_data": [{"name": "breast", "namespace": "fate_flow_test_breast"}]
                }
            },
            "dataio_0":{
                "with_label": [true],
                "label_name": ["y"],
                "label_type": ["int"],
                "output_format": ["dense"]
            }
        },
        "host": {
            "args": {
                "data": {
                    "train_data": [{"name": "breast", "namespace": "fate_flow_test_breast"}]
                }
            },
             "dataio_0":{
                "with_label": [false],
                "output_format": ["dense"]
            }
        }
    },

2.[root@cdc29a4a09ad fate_flow]# python fate_flow_client.py -f submit_job -d examples/test_hetero_lr_job_dsl.json -c examples/test_hetero_lr_job_conf.json
{
    "data": {
        "board_url": "http://fateboard:8080/index.html#/dashboard?job_id=202004290619158982332&role=guest&party_id=9999",
        "job_dsl_path": "/data/projects/fate/python/jobs/202004290619158982332/job_dsl.json",
        "job_runtime_conf_path": "/data/projects/fate/python/jobs/202004290619158982332/job_runtime_conf.json",
        "logs_directory": "/data/projects/fate/python/logs/202004290619158982332",
        "model_info": {
            "model_id": "arbiter-10000#guest-9999#host-10000#model",
            "model_version": "202004290619158982332"
        }
    },
    "jobId": "202004290619158982332",
    "retcode": 0,
    "retmsg": "success"
}

3. vi examples/publish_load_model.json
{
    "initiator": {
        "party_id": "9999",
        "role": "guest"
    },
    "role": {
        "guest": ["9999"],
        "host": ["10000"],
        "arbiter": ["10000"]
    },
    "job_parameters": {
        "work_mode": 1,
        "model_id": "arbiter-10000#guest-9999#host-10000#model",
        "model_version": "202004290619158982332"
    }
}
-----------Output--------------------
{
    "data": {
        "guest": {
            "9999": 0
        },
        "host": {
            "10000": 0
        }
    },
    "jobId": "202004290620510662733",
    "retcode": 0,
    "retmsg": "success"
}

4.vi examples/publish_load_model.json 
{
    "initiator": {
        "party_id": "9999",
        "role": "guest"
    },
    "role": {
        "guest": ["9999"],
        "host": ["10000"],
        "arbiter": ["10000"]
    },
    "job_parameters": {
        "work_mode": 1,
        "model_id": "arbiter-10000#guest-9999#host-10000#model",
        "model_version": "202004290619158982332"
    }
}

5. [root@cdc29a4a09ad fate_flow]# python fate_flow_client.py -f load -c examples/publish_load_model.json
{
    "data": {
        "guest": {
            "9999": 0
        },
        "host": {
            "10000": 0
        }
    },
    "jobId": "202004290620510662733",
    "retcode": 0,
    "retmsg": "success"
}

6.[root@cdc29a4a09ad fate_flow]# vi examples/bind_model_service.json
{
    "service_id": "test3",
    "initiator": {
        "party_id": "9999",
        "role": "guest"
    },
    "role": {
        "guest": ["9999"],
        "host": ["10000"],
        "arbiter": ["10000"]
    },
    "job_parameters": {
        "work_mode": 1,
        "model_id": "arbiter-10000#guest-9999#host-10000#model",
        "model_version": "202004290619158982332"
    },
    "servings": ["172.16.108.121:8000"]
}

7.(venv) [root@cdc29a4a09ad fate_flow]# python fate_flow_client.py -f bind -c examples/bind_model_service.json
{
    "retcode": 0,
    "retmsg": "service id is test3"
}

8. [root@cdc29a4a09ad fate_flow]# curl -X POST -H 'Content-Type: application/json' -d ' {"head":{"serviceId":"test3"},"body":{"featureData": {"x0": 0.254879,"x1": -1.046633,"x2": 0.2096560.377645,"x6": -0.485934,"x7": 0.347072,"x8": -0.287570,"x9": -0.733474}}' 'http://172.16.108.122:8059/federation/v1/inference'

9.This error occurred while post
{"code":"103","message":"SYSTEM_ERROR"}

<img width="1618" alt="WX20200429-145437@2x" src="https://user-images.githubusercontent.com/64405618/80568361-6cb03180-8a29-11ea-91b2-5c55e8b70232.png">

**Comment by Paul0M** [comment]
过程类似，FATE1.4.4, 同样遇到这个问题，不过是`{"code":"110","message":"SYSTEM_ERROR"}`

**Comment by JianhuanZeng** [comment]
过程类似，FATE1.5.0, 同样遇到这个问题，是{"code":"110","message":"SYSTEM_ERROR"}； 有答案吗？为什么是系统错误？
