### ISSUE TITLE
在线推理时返回retcode 104

### ISSUE THREAD

**Issue by learningwang** [FederatedAI/FATE#1325]
我用的kubefate安装,跟着教程到最后一步在线测试时,上传的数据是
data = {
  "head": {
    "serviceId": "test"
  },
  "body": {
    "featureData": {
      "x0": 0.254879,
      "x1": -1.046633,
      "x2": 0.209656,
      "x3": 0.074214,
      "x4": -0.441366,
      "x5": -0.377645,
      "x6": -0.485934,
      "x7": 0.347072,
      "x8": -0.287570,
      "x9": -0.733474,
    }
  }
}

返回的结果是
{"flag":0,"data":{"prob":0.06794082930000367,"retcode":104},"retmsg":"success","retcode":2104}

而教程中返回的结果是
{"flag":0,"data":{"prob":0.30684422824464636,"retmsg":"success","retcode":0}

虽然success了,请问retcode104和retcode2104是什么原因?另外在哪里查看retcode的字典表?谢谢

**Comment by deadlywing** [comment]
请问模型bind之后怎么进行在线推理呢？
我找了一圈没找到你说的那个教程诶，能麻烦给个链接么？
