### ISSUE TITLE
intersection 匹配率不为1且不固定

### ISSUE THREAD

**Issue by Origin-Draven** [FederatedAI/FATE#1328]
**Describe the bug**
intersection 会匹配率不为1且不固定
已检查id一致，匹配率也不是一个固定的值，在0-1之间的一个浮点数

**To Reproduce**
1.提交任务
2.检查intersection

**Expected behavior**
希望匹配率稳定为1，且增加丢包检查

**Screenshots**
![微信图片_20200507101212](https://user-images.githubusercontent.com/20585352/81247311-3cc9e500-904c-11ea-9158-d6e6699a809f.png)

![微信图片_20200507101137](https://user-images.githubusercontent.com/20585352/81246917-574f8e80-904b-11ea-9910-58c9e2cd5ce3.png)

**Desktop (please complete the following information):**
 - fate1.3

**Additional context**
看了 issue 里面好像没有相关问题，不知道我这种是不是个例

**Comment by Teslaxhub** [comment]
我这也有相同的问题

**Comment by dylan-fan** [comment]
FATE v1.4 已经解决，可以试用下

**Comment by Origin-Draven** [comment]
> FATE v1.4 已经解决，可以试用下

谢谢啦 最近试试

**Comment by Origin-Draven** [comment]
> FATE v1.4 已经解决，可以试用下

已尝试，数据量问题1.4 已解决
