### ISSUE TITLE
component_output_data api 导出的数据量问题

### ISSUE THREAD

**Issue by Origin-Draven** [FederatedAI/FATE#1374]
**Describe the bug**
参考文档 https://fate.readthedocs.io/en/latest/fate_flow/doc/fate_flow_cli.html
使用 component_output_data  api时
1. 数据量不一致的问题
总数据量（训练+验证）1万时，发现导出数据量
    output_data.csv 数据量 == train + eval
总数据量（训练+验证）10万时，发现导出数据量（有时）
    output_data.csv 数据量 == train
总数据量 （训练+验证）> 5万时，发现数据量有一定波动性，但是均为
    output_data.csv 数据量 < train + eval
 2. 重启fate后数据不见了的问题
    重启之后发现无法导出了

**To Reproduce**
1. 训练一个secureboost任务
2. 使用api：python fate_flow_client.py -f component_output_data -j $job_id -r $role -p $party_id -cpn $component_name -o $output_path
导出 out_data.csv
3. cat output_data.csv |wc -l
4. 数量不对劲

**Expected behavior**
希望导出数据量能与 训练+验证 一致
不排除是训练过程中丢包什么导致的数据量不一致，重复使用out_data.csv 导出数据量一致
使用 submit_job api 中 predict 的方法，多试 predict 的 out_data.csv 的数据量有一定随机性且很少与 输入的数据量一致
由于没有报错信息，不知道数据量不一致具体原因

**Screenshots**
1万数据量一致
![1万数据量一致](https://user-images.githubusercontent.com/20585352/82003959-4a0e5180-9694-11ea-8471-b05a27672c41.png)
10万数据量只有训练集
![10万数据量只有训练集](https://user-images.githubusercontent.com/20585352/82003967-51355f80-9694-11ea-98eb-3a2b0aae962b.png)
重启之后再无法导出
![重启之后再无法导出](https://user-images.githubusercontent.com/20585352/82003982-58f50400-9694-11ea-9c76-f484609c1aba.png)

**Desktop (please complete the following information):**
 - OS: centos7
 - Version fate1.3

**Comment by Origin-Draven** [comment]
经过排查大概率可能是 训练过程的丢包导致的，对于这种情况能否处理一下，重新打分也好，保证数据量一致的，否则线下很难评估

**Comment by dylan-fan** [comment]
FATE v1.4 已经fixed这个bug，也做了检测。可以试验下。

**Comment by Origin-Draven** [comment]
> FATE v1.4 已经fixed这个bug，也做了检测。可以试验下。

好的 这两天会试一下

**Comment by Origin-Draven** [comment]
> FATE v1.4 已经fixed这个bug，也做了检测。可以试验下。

v1.4 output_data.csv 数据量与训练+测试已一致
