### ISSUE TITLE
使用全连接神经网络横向联邦学习进行手写体识别任务，报错

### ISSUE THREAD

**Issue by Doodlera** [FederatedAI/FATE#1376]
**Describe the bug**

使用全连接神经网络横向联邦学习进行手写体识别任务。数据集使用mnist，按标签01234和56789划分为两个数据集，分别上传。每个角色没有其他类别标签的数据。分类任务设为5或者10均报错。
对于数据特征相同的分类任务，不同角色拥有的数据标签完全不同时，推断报错。

**To Reproduce**
1. guest、host分别上传数据
2. 运行相应的配置文件、dsl文件
3.fateboard查看运行状态

**Expected behavior**

算法正常运行。

**Comment by dreadNought-ai** [comment]
在横向任务中，每个本地节点，数据label必须一样，比如guest{0123456789}host{0123456789}

**Comment by weiwee** [comment]
It works in 1.5.0, close issue.

**Comment by weiwee** [comment]
It works in 1.5.0, close issue.

**Comment by Doodlera** [comment]
> It works in 1.5.0, close issue.

OK，looking forward to it.
