### ISSUE TITLE
单机版fate1.4在运行推荐模型时报错

### ISSUE THREAD

**Issue by youzp** [FederatedAI/FATE#1377]
版本：单机版1.4
运行用例shell脚本如下：
```
#!/bin/bash

MODEL_DIR="examples/federatedrec-examples/hetero_svd"
python fate_flow/fate_flow_client.py -f upload -c ${MODEL_DIR}/upload_data_guest.json
sleep 3s
python fate_flow/fate_flow_client.py -f upload -c ${MODEL_DIR}/upload_data_host.json
sleep 3s
python fate_flow/fate_flow_client.py -f submit_job -d ${MODEL_DIR}/test_hetero_svd_train_job_dsl.json -c ${MODEL_DIR}/test_hetero_svd_train_job_conf.json
```
报如下错误

> [ERROR] [2020-05-18 06:56:00,745] [6994:140016906028864] - task_executor.py[line:140]: Attempt to operate on closed/deleted/dropped object.
> Traceback (most recent call last):
> File "/fate/fate_flow/driver/task_executor.py", line 127, in run_task
> input_dsl=task_input_dsl)
> File "/fate/fate_flow/driver/task_executor.py", line 203, in get_task_run_args
> name=data_table.get_name(), options=save_as_options)
> File "/fate/arch/api/utils/profile_util.py", line 32, in _fn
> rtn = func(*args, **kwargs)
> File "/fate/arch/api/impl/based_1x/table.py", line 58, in save_as
> persistent_engine=persistent_engine)
> File "/fate/arch/standalone/standalone/eggroll.py", line 696, in save_as
> dup.put_all(self.collect(use_serialize=use_serialize), use_serialize=use_serialize)
> File "/fate/arch/standalone/standalone/eggroll.py", line 650, in put_all
> for k, v in kv_list:
> File "/fate/arch/standalone/standalone/eggroll.py", line 728, in _merge
> if it.next():
> lmdb.Error: Attempt to operate on closed/deleted/dropped object.

**Comment by AustinNeverPee** [comment]
请问这个问题解决了吗～

**Comment by XYT2000** [comment]
您好 

> 版本：单机版1.4
> 运行用例shell脚本如下：
> 
> ```
> #!/bin/bash
> 
> MODEL_DIR="examples/federatedrec-examples/hetero_svd"
> python fate_flow/fate_flow_client.py -f upload -c ${MODEL_DIR}/upload_data_guest.json
> sleep 3s
> python fate_flow/fate_flow_client.py -f upload -c ${MODEL_DIR}/upload_data_host.json
> sleep 3s
> python fate_flow/fate_flow_client.py -f submit_job -d ${MODEL_DIR}/test_hetero_svd_train_job_dsl.json -c ${MODEL_DIR}/test_hetero_svd_train_job_conf.json
> ```
> 
> 报如下错误
> 
> > [ERROR] [2020-05-18 06:56:00,745] [6994:140016906028864] - task_executor.py[line:140]: Attempt to operate on closed/deleted/dropped object.
> > Traceback (most recent call last):
> > File "/fate/fate_flow/driver/task_executor.py", line 127, in run_task
> > input_dsl=task_input_dsl)
> > File "/fate/fate_flow/driver/task_executor.py", line 203, in get_task_run_args
> > name=data_table.get_name(), options=save_as_options)
> > File "/fate/arch/api/utils/profile_util.py", line 32, in _fn
> > rtn = func(*args, **kwargs)
> > File "/fate/arch/api/impl/based_1x/table.py", line 58, in save_as
> > persistent_engine=persistent_engine)
> > File "/fate/arch/standalone/standalone/eggroll.py", line 696, in save_as
> > dup.put_all(self.collect(use_serialize=use_serialize), use_serialize=use_serialize)
> > File "/fate/arch/standalone/standalone/eggroll.py", line 650, in put_all
> > for k, v in kv_list:
> > File "/fate/arch/standalone/standalone/eggroll.py", line 728, in _merge
> > if it.next():
> > lmdb.Error: Attempt to operate on closed/deleted/dropped object.

您好，我遇到同样的问题，请问您解决了么？

**Comment by youzp** [comment]
没有解决，可以试试最新的1.6.0版本

**Comment by XYT2000** [comment]
> 没有解决，可以试试最新的1.6.0版本

您好，使用1.3.1版本就可以解决了，应该是1.4没注册那个算法
