### ISSUE TITLE
a little bug in hetero_decision_tree_guest.py file

### ISSUE THREAD

**Issue by ZhanqiLiu** [FederatedAI/FATE#1399]
In the 315 line, which is in the function of  find_best_split_guest_and_host(), the  value of 1 should be modified as 2.
![image](https://user-images.githubusercontent.com/13013299/82445526-8d732080-9ad7-11ea-8c7d-d1c8dba016e3.png)

**Comment by mgqa34** [comment]
It waste one time of comparision, but will not affect the result correctness

**Comment by ZhanqiLiu** [comment]
yes, it will not affects the  result correctness
