### ISSUE TITLE
The error after the command "docker-compose down and docker-compose up -d" for the KubeFATE 1.4

### ISSUE THREAD

**Issue by ZhanqiLiu** [FederatedAI/FATE#1409]
When the container is restarted, the table which is uploaded in the last container cann't be accessed  again in the new job, and the job which was run in the last container cann't be readed from the fateboard also.

![image](https://user-images.githubusercontent.com/13013299/83089937-1f77bc00-a0ca-11ea-93cc-c1dc226392c1.png)
![image](https://user-images.githubusercontent.com/13013299/83089959-269eca00-a0ca-11ea-8676-87db8fee6806.png)
![image](https://user-images.githubusercontent.com/13013299/83089976-2c94ab00-a0ca-11ea-9ad4-38756c46f326.png)

**Comment by jiahaoc1993** [comment]
@ZhanqiLiu hi thank you for your feedback, this issue has been addressed by this [PR](https://github.com/FederatedAI/KubeFATE/pull/146)
