### ISSUE TITLE
如何做FATE的安全性验证？

### ISSUE THREAD

**Issue by tuobameng** [FederatedAI/FATE#1414]
目前我们在用FATE做一个平台，现在需要对FATE做安全性的验证，证明数据传输过程中传递的不是原始数据。
目前我们采用的方法是通过抓包的方式来看传递的数据是什么。但是目前抓到的包，无法用python的pickle来loads，总是提示"pickle data was truncated"。

**Comment by dylan-fan** [comment]
传输的数据可能会对数据进行切分传输，所以你直接抓包就会出现这问题

**Comment by lixuejun725** [comment]
> 目前我们在用FATE做一个平台，现在需要对FATE做安全性的验证，证明数据传输过程中传递的不是原始数据。
> 目前我们采用的方法是通过抓包的方式来看传递的数据是什么。但是目前抓到的包，无法用python的pickle来loads，总是提示"pickle data was truncated"。

这个需求我们也是有的,我们的解决方案是自己进入代码，自己添加逻辑代码，打印加密数据，自己添加加密过程查看数据在各方每个过程密文明文信息。
