### ISSUE TITLE
docker commit is not saving my changes in container to new image in the kubefate 1.4

### ISSUE THREAD

**Issue by ZhanqiLiu** [FederatedAI/FATE#1445]
I have known that "The commit operation will not include any data contained in volumes mounted inside the container", so I annotates the volumes in the docker-compose.yml and remove all the volumes in the host machine through the "docker volume rm" command.
![image](https://user-images.githubusercontent.com/13013299/84219639-8ef69e00-ab03-11ea-9206-0e39d90c8fc4.png)
![image](https://user-images.githubusercontent.com/13013299/84219648-9453e880-ab03-11ea-824e-125ddc793a0e.png)

Then,I restart all the container through the "docker-compose up -d" command,  I  enter the python container and changes the code in the  hetero_feature_binning_transfer_variable.py file.
Afterwards, i save the python container to a new image  through the commit command.
![image](https://user-images.githubusercontent.com/13013299/84220722-16451100-ab06-11ea-9532-96a02b005761.png)
![image](https://user-images.githubusercontent.com/13013299/84220066-805cb680-ab04-11ea-8ab9-1634980f3532.png)

but,when i load the image on another machine,the hetero_feature_binning_transfer_variable.py file in python container is still the old text and not changed. the new machnie has annotated the federatedml volume in the docker-compose.yml
![image](https://user-images.githubusercontent.com/13013299/84220315-10026500-ab05-11ea-8544-c8a3d8813e37.png)
![image](https://user-images.githubusercontent.com/13013299/84220670-eb5abd00-ab05-11ea-8756-98fb53d2d9f9.png)

**Comment by jiahaoc1993** [comment]
@ZhanqiLiu HI, just verify that after running `docker commit` as your mentions above, the new image actually contains the new changes. However, the container's "federatedml" directory may be overwrote by hosts. Make sure you have cleaned up the contents under "federatedml" of host before starting the container.

**Comment by jiahaoc1993** [comment]
The recommended way to create new image upon changes is to define a "Dockerfile" like:
```
from federatedai/python:1.4.0-release
COPY federatedml /* /data/projects/fate/python/federatedml/
```
