### ISSUE TITLE
Cannot run toy_example

### ISSUE THREAD

**Issue by chaindreamjet** [FederatedAI/FATE#1457]
**What deployment mode you use? **
docker-compose

**What KubeFATE and FATE version you are using? **
1.4.0

**What OS you are using for docker-compose or Kubernetes? Please also clear the version of OS. **
Ubuntu 18.04

To Reproduce
When following the deployment manual step by step, there is nothing going wrong until I run the run_toy_example.py.
My two machines' private IPs are 172.31.66.120 & 172.31.67.208.
ssh login without key has no problem.
I have no idea what went wrong here.

What happens?
No matter how many times I try it, It failed with an unreadable exception, see below.

![image](https://user-images.githubusercontent.com/28439833/84371650-8fc72700-ac0c-11ea-9161-fd408a0e3bd5.png)

**Comment by chaindreamjet** [comment]
我按照docker-compose 部署文档做的
前面都很顺利，生成部署文件以及集群部署，看上去都没问题
docker ps 看到的各组件状态也都正常
但是运行不了toy_example
就会报截图上的错误

**Comment by xq92** [comment]
I met the same problem when I tried to deploy the FATE 1.4。How to solve it?

**Comment by SamuelGong** [comment]
Similar problem here
