### ISSUE TITLE
[SPDZ] Table-based implementation does not support multiple times’ operations

### ISSUE THREAD

**Issue by SamuelGong** [FederatedAI/FATE#1551]
If I multiply under the SPDZ environment two tensors of class `fixedpoint_table.FixedPointTensor`, say *A* and *B*, the resulting product *C = A.dot(B)* will be of class `fixedpoint_numpy.FixedPointTensor`. While there is no problem if I immediately extract the result and leave the environment, errors will occur if I want to use the result to do further computation with tensors of type `fixedpoint_table.FixedPointTensor` because they will have different types. For example, if I want to perform *C+D* where *D* is of type `fixedpoint_table.FixedPointTensor`, either doing *C+D* or *D+C* does not work (with different errors prompting, though).

**Comment by SamuelGong** [comment]
As a user, currently I may sidestep this issue by separating the computation in pieces. Of course it will induce remarkable performance overhead since unnecessary “get()” and “from_source()” have to be performed.

**Comment by weiwee** [comment]
track in #2312
