### ISSUE TITLE
No data in database

### ISSUE THREAD

**Issue by meijuanwang** [FederatedAI/FATE#1592]
**Describe the bug**
 I have uploaded data for host and guest,but when I start a new job,it shows "no data in database"

![image](https://user-images.githubusercontent.com/65224044/88160025-af586300-cc40-11ea-854a-2aff33cd84c6.png)

**Additional context**

**Comment by tanmc123** [comment]
Please have a check whether the table_name and namespace of your uploaded data and configuration in conf are matched. If it is matched, you can use fate_flow cli "table_info" to check the table info of your uploaded data.

**Comment by meijuanwang** [comment]
> Please have a check whether the table_name and namespace of your uploaded data and configuration in conf are matched. If it is matched, you can use fate_flow cli "table_info" to check the table info of your uploaded data.

**Comment by meijuanwang** [comment]
> Please have a check whether the table_name and namespace of your uploaded data and configuration in conf are matched. If it is matched, you can use fate_flow cli "table_info" to check the table info of your uploaded data.

Yes,  I have checked all the information. But I solved it . I put wrong data , the first column should be "id"
