### ISSUE TITLE
Problem when run quick_run.py in fate1.2.0

### ISSUE THREAD

**Issue by WenTaoDu** [FederatedAI/FATE#1594]
I'm using macOS Catalina10.15.5, python 3.7.7, and Pycharm 2019.2.

1 . When I run fate_flow_server.py, the result is as blows:
"***
/usr/local/bin/python3.7 /Users/duwentao/Downloads/standalone-fate-master-1.2.0/fate_flow/fate_flow_server.py
 * Running on http://0.0.0.0:9380/ (Press CTRL+C to quit) 
***"

2 . And then after I run quick_run.py, the problems occurred as blow:
"***
/usr/local/bin/python3.7 /Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py
Upload data config json: {'file': 'examples/data/default_credit_homo_guest.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'default_credit_homo_guest', 'namespace': ‘default_credit_homo_guest_guest'}
stdout:{
    "retcode": 100,
    "retmsg": "Expecting value: line 1 column 1 (char 0)",
    "traceback": [
        "Traceback (most recent call last):\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py\", line 239, in <module>\n    response = call_fun(args.function, config_data, dsl_path, config_path)\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py\", line 172, in call_fun\n    return response.json() if isinstance(response, requests.models.Response) else response\n",
        "  File \"/usr/local/lib/python3.7/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n",
        "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py\", line 348, in loads\n    return _default_decoder.decode(s)\n",
        "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
        "  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
        "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"
    ]
}
{  "retcode": 100,
    "retmsg": [
        "Traceback (most recent call last):\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py\", line 372, in <module>\n    upload_data()\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py\", line 352, in upload_data\n    upload(GUEST)\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py\", line 243, in upload\n    stdout = exec_upload_task(json_info, role)\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py\", line 124, in exec_upload_task\n    \"[Upload task]exec fail, status:{}, stdout:{}\".format(status, stdout))\n",
        "ValueError: [Upload task]exec fail, status:100, stdout:{'retcode': 100, 'retmsg': 'Expecting value: line 1 column 1 (char 0)', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py\", line 239, in <module>\\n    response = call_fun(args.function, config_data, dsl_path, config_path)\\n', '  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py\", line 172, in call_fun\\n    return response.json() if isinstance(response, requests.models.Response) else response\\n', '  File \"/usr/local/lib/python3.7/site-packages/requests/models.py\", line 897, in json\\n    return complexjson.loads(self.text, **kwargs)\\n', '  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py\", line 348, in loads\\n    return _default_decoder.decode(s)\\n', '  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py\", line 337, in decode\\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\\n', '  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py\", line 355, in raw_decode\\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\\n', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\\n']}\n"
    ]}
Process finished with exit code 0
***"

3 . Then the fate_flow_server.py outputs:
"***
127.0.0.1 - - [22/Jul/2020 21:27:47] "POST /v1/data/upload HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
TypeError: 'tuple' object is not callable
 ***"

These are all about my problem, if you know why, please help me. Best wishes to you!

**Comment by WenTaoDu** [comment]
I use the standalone version1.2.0. I try to discover the answer and I think the problem may caused by the following code:
''***
subp = subprocess.Popen(["python3",
                             FATE_FLOW_PATH,
                             "-f",
                             "upload",
                             "-c",
                             config_path],
                            shell=False,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT)
    # print(subp)
    stdout, stderr = subp.communicate()
***"
There is something wrong with my 'stdout', but I don't know why and how to solve it.
"***
stdout:{
    "retcode": 100,
    "retmsg": "Expecting value: line 1 column 1 (char 0)",
    "traceback": [
        "Traceback (most recent call last):\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py\", line 241, in <module>\n    response = call_fun(args.function, config_data, dsl_path, config_path)\n",
        "  File \"/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py\", line 174, in call_fun\n    return response.json() if isinstance(response, requests.models.Response) else response\n",
        "  File \"/usr/local/lib/python3.7/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n",
***"

If you know why, please tell me. Best wishes to you!

**Comment by tanmc123** [comment]
> I'm using macOS Catalina10.15.5, python 3.7.7, and Pycharm 2019.2.
> 
> 1 . When I run fate_flow_server.py, the result is as blows:
> "***
> /usr/local/bin/python3.7 /Users/duwentao/Downloads/standalone-fate-master-1.2.0/fate_flow/fate_flow_server.py
> 
> * Running on http://0.0.0.0:9380/ (Press CTRL+C to quit)
>   ***"
> 
> 2 . And then after I run quick_run.py, the problems occurred as blow:
> "***
> /usr/local/bin/python3.7 /Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py
> Upload data config json: {'file': 'examples/data/default_credit_homo_guest.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'default_credit_homo_guest', 'namespace': ‘default_credit_homo_guest_guest'}
> stdout:{
> "retcode": 100,
> "retmsg": "Expecting value: line 1 column 1 (char 0)",
> "traceback": [
> "Traceback (most recent call last):\n",
> " File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py", line 239, in \n response = call_fun(args.function, config_data, dsl_path, config_path)\n",
> " File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py", line 172, in call_fun\n return response.json() if isinstance(response, requests.models.Response) else response\n",
> " File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json\n return complexjson.loads(self.text, **kwargs)\n",
> " File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/**init**.py", line 348, in loads\n return _default_decoder.decode(s)\n",
> " File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
> " File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode\n raise JSONDecodeError("Expecting value", s, err.value) from None\n",
> "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"
> ]
> }
> { "retcode": 100,
> "retmsg": [
> "Traceback (most recent call last):\n",
> " File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py", line 372, in \n upload_data()\n",
> " File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py", line 352, in upload_data\n upload(GUEST)\n",
> " File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py", line 243, in upload\n stdout = exec_upload_task(json_info, role)\n",
> " File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py", line 124, in exec_upload_task\n "[Upload task]exec fail, status:{}, stdout:{}".format(status, stdout))\n",
> "ValueError: [Upload task]exec fail, status:100, stdout:{'retcode': 100, 'retmsg': 'Expecting value: line 1 column 1 (char 0)', 'traceback': ['Traceback (most recent call last):\n', ' File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py", line 239, in \n response = call_fun(args.function, config_data, dsl_path, config_path)\n', ' File "/Users/duwentao/Downloads/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py", line 172, in call_fun\n return response.json() if isinstance(response, requests.models.Response) else response\n', ' File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json\n return complexjson.loads(self.text, **kwargs)\n', ' File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/**init**.py", line 348, in loads\n return _default_decoder.decode(s)\n', ' File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n', ' File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode\n raise JSONDecodeError("Expecting value", s, err.value) from None\n', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n']}\n"
> ]}
> Process finished with exit code 0
> ***"
> 
> 3 . Then the fate_flow_server.py outputs:
> "***
> 127.0.0.1 - - [22/Jul/2020 21:27:47] "POST /v1/data/upload HTTP/1.1" 500 -
> Error on request:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
> execute(self.server.app)
> File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 291, in execute
> application_iter = app(environ, start_response)
> TypeError: 'tuple' object is not callable
> ***"
> 
> These are all about my problem, if you know why, please help me. Best wishes to you!

I suspect it was because you are using python3.7 while FATE support python 3.6.

**Comment by WenTaoDu** [comment]
I tried Python with Version of 3.6.5 today, but it failed with the same error. Do you have any other ideas?

**Comment by WenTaoDu** [comment]
I think the error is caused by the Server error. 
"***
500 Internal Server Error.Internal Server Error.The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
***"
when I click the link "Running on http://0.0.0.0:9380/ (Press CTRL+C to quit)"
"Internal Server Error" occurred !
