### ISSUE TITLE
V1.7  HeteroLR: hetero_lr_0  task output data [None]

### ISSUE THREAD

**Issue by JianhuanZeng** [FederatedAI/FATE#1596]
**Describe the bug**
sometimes no output data & no [ERROR]

**To Reproduce**

[INFO] [2022-05-18 10:11:59,457] [202205180957391574150] [18041:139769249228608] - [task_executor._run_] [line:199]: task output data [None]

**Screenshots**
![da28426bb5a35adc4e0c14c69039dd1](https://user-images.githubusercontent.com/37096176/168948909-09ca9689-6555-4633-b48b-daadabf4e009.png)

**Desktop (please complete the following information):**
 - CentOS 7.9
 - Docker version 20.10.1
 - docker-compose version  1.25.0

**Additional context**
TRY:
checked docker logs [all containers]
checked  nodemanager /data/projects/fate/eggroll/logs/xxxxxxx_hetero_lr_0_0_guest_xxx_clean

**Comment by JianhuanZeng** [comment]
Grpc的域名解析，它是先找了什么地方，然后失败了？

**Comment by FutaoJia97** [comment]
same issue here
