### ISSUE TITLE
please start fate flow server.......

### ISSUE THREAD

**Issue by gaojunjie03** [FederatedAI/FATE#1608]
when i execute fate_flow_client -f submit_job.....

i got an error :
{
    "retcode": 999,
    "retmsg": "please start fate flow server: 192.167.0.6:9381"
}

but the service already started : 
![image](https://user-images.githubusercontent.com/30582212/88609277-4b0d2780-d0b6-11ea-8253-bfba28a32cf9.png)

**Comment by Eighonet** [comment]
Hello. So, how did you solve it?

**Comment by gaojunjie03** [comment]
> Hello. So, how did you solve it?
I apologize. I can't remember why......
I don't use fate every day. Some problems have been solved but I forget
