### ISSUE TITLE
Standardize Feature Pseudonym Generation 

### ISSUE THREAD

**Issue by nemirorox** [FederatedAI/FATE#1617]
Currently FATE modules each maintain individual feature pseudonym generators. We will standardize pseudonym generation process to allow smoother developer experience and reduce potential incoherent behavior between modules.

We will add a utility function specific for feature pseudonym generation. All modules will call on this function when needed. Generated pseudonyms will include necessary information: party id and feature index. In addition, another utility function is provided for abstracting feature index information from a given pseudonym.

**Comment by weiwee** [comment]
released in version 1.6
