### ISSUE TITLE
特征分箱仅支持等频和等距分箱吗？跑最优分箱会报错

### ISSUE THREAD

**Issue by jennylove10** [FederatedAI/FATE#1624]
报错如下: - ERROR: hetero binning param's optimal is not supported, it should be in ['quantile', 'bucket']"
![image](https://user-images.githubusercontent.com/62371712/88898332-24e6b380-d27f-11ea-9295-4bd7f67d0145.png)

组件参数配置为：
{
"method": "optimal",
 "optimal_binning_param": {
 "metric_method": "iv",
 "min_bin_pct": 0.05,
 "max_bin_pct": 0.8,
 "init_bucket_method": "quantile",
 "init_bin_nums": 100,
 "mixture": true
 },
 "compress_thres": 10000,
 "head_size": 10000,
 "error": 0.001,
 "bin_num": 10,
 "bin_indexes": -1,
 "bin_names": null,
 "category_indexes": [0,1,2],
 "category_names": null,
 "adjustment_factor": 0.5,
 "local_only": false,
 "transform_param": {
 "transform_cols": -1,
 "transform_names": null,
 "transform_type": "bin_num"
 }
 }

**Comment by tanmc123** [comment]
从1.4版本开始，是支持最优分箱的。
