### ISSUE TITLE
container confs_9999_pyhon_1  always restarts 

### ISSUE THREAD

**Issue by meijuanwang** [FederatedAI/FATE#1649]
**Describe the bug**
 when I use docker compose to deploy the cluster , the container confs_9999_pyhon_1  always restarts .

**Comment by cometta** [comment]
I experienced this issue in 1.4.2 as well (master branch). i notice service in port 9380 is not running? any issue?

**Comment by cometta** [comment]
solution : edit confs-xx/confs/eggroll/conf/eggroll.properties change this line
```
eggroll.resourcemanager.bootstrap.roll_pair_master.javahome=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/jre
```

**Comment by meijuanwang** [comment]
I have solved this. The reason is that the mysql container exited. And I close the selinux.

**Comment by Song-xx** [comment]
i have the same problem with you,it is a headache.

**Comment by wood-j** [comment]
Same log but different cause

My cluster is run with:
- k3s
- self built image on arm64v8
- base on code release `1.8.0`

Log file from pod `nodemanager-0-xxx` container `nodemanager-0-eggrollpair`  path `logs//202209150646164580550_secure_add_example_0_0_guest_10001`:

```shell
/data/projects/fate/eggroll/logs/202209150646164580550_secure_add_example_0_0_guest_10001 $ ll
total 28
-rw-r--r--    1 root     root           115 Sep 15 06:49 bootstrap-egg_pair-51.err
-rw-r--r--    1 root     root         11150 Sep 15 06:49 bootstrap-egg_pair-51.out
-rw-r--r--    1 root     root           791 Sep 15 06:46 egg_pair-51.err
-rw-r--r--    1 root     root             0 Sep 15 06:46 egg_pair-51.out
-rw-r--r--    1 root     root            44 Sep 15 06:46 pid.txt
-rw-r--r--    1 root     root           425 Sep 15 06:46 strace-51.log
```

content of `egg_pair-51.err`:

```shell
bin/roll_pair/egg_pair_bootstrap.sh: line 196: None/bin/python: No such file or directory
```

content of `bootstrap-egg_pair-51.err`:

```shell
egg_pair_bootstrap.sh: unrecognized option '--python-venv'
bin/roll_pair/egg_pair_bootstrap.sh: line 166: None/bin/activate: No such file or directory
bin/roll_pair/egg_pair_bootstrap.sh: line 181: None/bin/python: No such file or directory
strace: attach: ptrace(PTRACE_SEIZE, 135): No such process
kill: not enough arguments
```

## Fix:

edit file `bin/roll_pair/egg_pair_bootstrap.sh` in running pod container:

- nodemanager-0-xxxx: nodemanager-0
- nodemanager-1-xxxx: nodemanager-1

```shell
PYTHON=`which python`
# if [[ -z ${venv} ]]; then
#   PYTHON=`which python`
# else
#   source ${venv}/bin/activate
#   PYTHON=${venv}/bin/python
# fi
```
