### ISSUE TITLE
获取安装包报错404

### ISSUE THREAD

**Issue by liuluyeah** [FederatedAI/FATE#1672]
wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/python-env-1.4.0-rc3.tar.gz
--2020-08-11 10:15:52--  https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/python-env-1.4.0-rc3.tar.gz
.0-rc3.tar.gz
wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/FATE_install_1.4.0-release.tar.gz
Resolving webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)... 211.159.130.21, 123.207.131.115, 119.29.47.254, ...
Connecting to webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)|211.159.130.21|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-11 10:15:53 ERROR 404: Not Found.

**Comment by SennriSyunnga** [comment]
same problem，any solution？

**Comment by oublie6** [comment]
wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone-fate-master-${version}.tar.gz
