### ISSUE TITLE
程序卡住，内存占满无法释放

### ISSUE THREAD

**Issue by luzhidong** [FederatedAI/FATE#1872]
FATE版本：1.4.2
AllinOne方式部署

重启设备后，进行第一次的任务提交是能够完成整个模型训练的任务的，但是模型训练结束后，guest端和host端的内存都被占用着无法释放，再次提交相同的任务时就会卡着无法运行，待机器reboot再重启所有服务，重新提交任务则可以顺利完成训练。

请问知道怎样释放内存呢？

**Comment by dylan-fan** [comment]
看下，任务是不是被杀掉了

**Comment by dylan-fan** [comment]
建议升级到FATE v1.5.2版本，稳定性会好很多
