### ISSUE TITLE
Failed to release resource after fate_flow server crashed

### ISSUE THREAD

**Issue by jiahaoc1993** [FederatedAI/FATE#2082]
**Describe the bug**
The `nodemanager` fails to release `roll_pair.py` process after fate_flow server crashed.

**To Reproduce**
1. Start FATE Cluster
2. Kill fate_flow server without `KeyboardInterrupt`
3. Check process in "nodemanager",  the resource occupied by the session will not be released.

**Expected behavior**
Once fate_flow server restart, it should reuse the previous session of delete it before create a new one.

**Comment by LaynePeng** [comment]
Close the issue cuz fixed in v1.5.1
