### ISSUE TITLE
socket.gethostbyname(socket.getfqdn()) get gaierror: [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by demeen68** [FederatedAI/FATE#2153]
I use Macos and standalone-fate-master-1.4.5.tar.gz

when I run fate_flow_server.py , In core_utils.py line 97 
```ip = socket.gethostbyname(socket.getfqdn())``` get error.
socket.getfqdn() get : "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa"

but my ```/etc/hosts``` is 
```
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
127.0.0.1       X-QdeMacBook-Pro.local
127.0.0.1       X-QdeMacBook-Pro
0.0.0.0         X-QdeMacBook-Pro
0.0.0.0         X-QdeMacBook-Pro.local
```

**Comment by weiwee** [comment]
try rename getfqdn to gethostname, which works for me in same situation.

by the way,  version 1.5.0 has better support for macos using standalone  deploy.

**Comment by weiwee** [comment]
This issue is closed due to not being active. Please feel free to open it again
