### ISSUE TITLE
windows系统下可以单机部署FATE吗？

### ISSUE THREAD

**Issue by ElsaQf** [FederatedAI/FATE#2156]
请教：FATE只能部署在linux和mac环境下吗？有没有win7安装FATE的方法，或者windows部署成功的小伙伴？只能通过虚拟机吗？

**Comment by weiwee** [comment]
> 请教：FATE只能部署在linux和mac环境下吗？有没有win7安装FATE的方法，或者windows部署成功的小伙伴？只能通过虚拟机吗？

Windows 支持不在我们的计划列表，所以即使通过某种手段安装成功我们也没法保证没有问题，因为我们的测试覆盖不到。实际上只有Linux系统才有完善的测试支持。如果感兴趣，可以自己尝试在window上部署，并在这里分享遇到的问题。

这个issue会保持开放一段时间
