### ISSUE TITLE
fatal: [xx.xxx.xxx.xx]: FAILED! => {"changed": false, "elapsed": 120, "msg": "Timeout when waiting for xx.xxx.xxx.xx:3306"}

### ISSUE THREAD

**Issue by SuZhaoJie** [FederatedAI/FATE#2184]
fatal: [xx.xxx.xxx.xx]: FAILED! => {"changed": false, "elapsed": 120, "msg": "Timeout when waiting for xx.xxx.xxx.xx:3306"}
部署失败，看不到其他错误信息了，怎么排查？

**Comment by tigflanker** [comment]
遇到了同样问题，请问楼主最后解决了么？
