### ISSUE TITLE
pipeline API不兼容：'Reader' object has no attribute 'algorithm_param'

### ISSUE THREAD

**Issue by graduter** [FederatedAI/FATE#2202]
**Describe the bug**
安装最新的FATE 镜像，按照指导文档：https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/README.rst操作。在执行：python demo/pipeline-mini-demo.py
报错：
Traceback (most recent call last):
  File "fate/examples/pipeline/demo/pipeline-mini-demo.py", line 129, in <module>
    main()
  File "fate/examples/pipeline/demo/pipeline-mini-demo.py", line 57, in main
    reader_0.get_party_instance(role="guest", party_id=guest).algorithm_param(table=guest_train_data)
AttributeError: 'Reader' object has no attribute 'algorithm_param'

**Comment by weiwee** [comment]
> **Describe the bug**
> 安装最新的FATE 镜像，按照指导文档：[https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/README.rst操作。在执行：python](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/README.rst%E6%93%8D%E4%BD%9C%E3%80%82%E5%9C%A8%E6%89%A7%E8%A1%8C%EF%BC%9Apython) demo/pipeline-mini-demo.py
> 报错：
> Traceback (most recent call last):
> File "fate/examples/pipeline/demo/pipeline-mini-demo.py", line 129, in 
> main()
> File "fate/examples/pipeline/demo/pipeline-mini-demo.py", line 57, in main
> reader_0.get_party_instance(role="guest", party_id=guest).algorithm_param(table=guest_train_data)
> AttributeError: 'Reader' object has no attribute 'algorithm_param'

There are some api modify in final release and we has publish rc2 to pypi for test

temporary, try 
install fate_client==0.1rc1
Or
install - e python/fate_client
