### ISSUE TITLE
Label Y can be a vector?

### ISSUE THREAD

**Issue by lynnprosper** [FederatedAI/FATE#2255]
Dear,
Thanks for your contribution on this project.

The label in all examples is just one scalar, 
I want to set label to be a vector, could you help me on what should I do?

Best wishes.
2020.11.02

**Comment by weiwee** [comment]
> Dear,
> Thanks for your contribution on this project.
> 
> The label in all examples is just one scalar,
> I want to set label to be a vector, could you help me on what should I do?
> 
> Best wishes.
> 2020.11.02

We only support scalar label right now and I don't think there are easy way to switch scalar label to vector like label. Is there some examples that vector like label could be much more useful?
