### ISSUE TITLE
What communication schemes are used in FATE?

### ISSUE THREAD

**Issue by tanjuntao** [FederatedAI/FATE#2326]
In vertical federated learning, there exists many intermediate information needed to be transmitted to another host during training process, so I want to know what communication schemes(or communication frameworks) are adopted in FATE? Is it python socket, or gRPC, or any other?

It seems a little bit hard for me to find the communication code snippets in `HeteroLinR` and `HeteroLR` model, so could you please provide a link for me, that would be greatly appreciated!

**Comment by whr819987540** [comment]
Did you find the answer?
