### ISSUE TITLE
grpc connection reset by peer

### ISSUE THREAD

**Issue by xkf4806** [FederatedAI/FATE#2327]
**Describe the bug**
docker方式部署的fate环境，在做联邦预测时，guest和host经过exchange通信，观察日志发现host端会偶发性的出现grpc connection reset by peer错误，这种错误有时会丢失数据包。
现象：预测任务卡死。

**To Reproduce**
1. docker版1.4.3FATE
2.在联邦训练和联邦预测场景
3.报错日志见附件

**Expected behavior**
希望能优化grpc通信异常处理逻辑

**Screenshots**
![image](https://user-images.githubusercontent.com/7620676/99224969-38179200-2822-11eb-9c1d-08ac660483c6.png)
![image](https://user-images.githubusercontent.com/7620676/99224975-3cdc4600-2822-11eb-858a-346b3f2eba53.png)

**Comment by Keepmoving001073** [comment]
我遇到了同样的错误，请问应该从哪里开始排查呢？

**Comment by Keepmoving001073** [comment]
最近我找到一个规律，一旦出现getStatus的结果中出现“JOB NOT finished”字段，并且put batch required的值小于put batch finished的值，基本训练就卡死了。一开始出现这种日志之后，我等了三天Fate没有进行再输出任何日志，所以我觉得出现这种日志应该是卡死了。
