### ISSUE TITLE
Find a typo: sparse_optmization should be sparse_optimization

### ISSUE THREAD

**Issue by lotress** [FederatedAI/FATE#2331]
**Describe the bug**
Typo in [python/federatedml/param/boosting_param.py](../blob/master/python/federatedml/param/boosting_param.py#L415) line 415, 471, 495.
Got exception "__init__() got an unexpected keyword argument 'sparse_optmization'"

**To Reproduce**
1. from pipeline.component.hetero_fast_secureboost import HeteroFastSecureBoost
2. Instantiate HeteroFastSecureBoost
3. Add this component to a pipeline and call .fit()

**Expected behavior**
sparse_optmization should be sparse_optimization.

**Comment by furuifr** [comment]
I had the same problem. Have you solved this problem?

**Comment by meldonization** [comment]
same problem here, any solutions?

**Comment by meldonization** [comment]
@furuifr hetero fast secure boost typo `sparse_optmization` problem is solved in FATE-1.6

# FATE-1.5
![fate_old_1 5](https://user-images.githubusercontent.com/1425792/133391832-f46ff3ae-5b57-4d4e-9ce1-0e90788f4bb3.png)

# FATE-1.6
![fate_new_1 6](https://user-images.githubusercontent.com/1425792/133392080-58132ef1-42d7-4f4a-99e8-62ff270242c1.png)
