### ISSUE TITLE
Fate 1.5 run /fate_flow/examples/test_predict_conf.json

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE#2332]
when run this command 
```
python /data/projects/fate/python/fate_flow/fate_flow_client.py -f submit_job -c /data/projects/fate/python/fate_flow/examples/test_predict_conf.json
```

i get below error
```
{
    "retcode": 100,
    "retmsg": "__init__() missing 1 required positional argument: 'msg'"
}

```

content of test_predict_conf.json
```
{
    "initiator": {
        "role": "guest",
        "party_id": 9999
    },
    "job_parameters": {
        "work_mode": 1,
        "job_type": "predict",
        "model_id": "arbiter-10000#guest-9999#host-9998#model",
        "model_version": "202011180908219381005",
        "dsl_version": "2"
    },
    "role": {
        "guest": [9999],
        "host": [9998],
        "arbiter": [10000]
    },
    "role_parameters": {
        "guest": {
            "0": {
                "reader_0": {
                    "table": {"name": "breast_hetero_guest", "namespace": "experiment"}
                },
                "dataio_0":{
                    "with_label": true,
                    "label_name": "y",
                    "label_type": "int",
                    "output_format": "dense"
                }
            }
        },
        "host": {
            "0": {
                "reader_0": {
                    "table": {"name": "breast_hetero_host", "namespace": "experiment"}
                },
                "dataio_0":{
                    "with_label": false,
                    "output_format": "dense"
                }
            }
        }
    }
}
```

for your info, i have no issue run on 1.4.3

**Comment by tanmc123** [comment]
@cometta There exists some errors in "job_parameter" part of your conf file. Please refer to this doc for more details:
https://github.com/FederatedAI/FATE/blob/master/examples/experiment_template/user_usage/dsl_v2_predict_tutorial.md

**Comment by cometta** [comment]
@tanmc123 the conf file is from https://github.com/FederatedAI/FATE/blob/master/python/fate_flow/examples/test_predict_conf.json , i only modified model_id, version and the role id. For your info, i did successfully ran similar codes for older version 1.4.3 and below successfully.  Can you elaborate more on what is possibility cause the issue? i am sure the model id, version and role id are correct.

**Comment by cometta** [comment]
@tanmc123 i successfully run https://github.com/FederatedAI/FATE/blob/master/examples/experiment_template/user_usage/dsl_v2_predict_tutorial.md  example, but what about  https://github.com/FederatedAI/FATE/blob/master/python/fate_flow/examples/test_predict_conf.json ? does it still work in 1.5 ?

**Comment by cometta** [comment]
issue resolved after done minor changes to test_predict_conf.json

```
{
    "dsl_version": 2,
    "initiator": {
        "role": "guest",
        "party_id": 9999
    },
    "job_parameters": {
      "common":{
        "work_mode": 1,
        "job_type": "predict",
        "model_id": "<id>",
        "model_version": "<id>",
        "dsl_version": "2"
     }
    },

```
