### ISSUE TITLE
Logistic逻辑回归bug

### ISSUE THREAD

**Issue by RookieCXL** [FederatedAI/FATE#2336]
**Describe the bug**
逻辑回归二分类早停功能正常，但是在多分类下无法启用早停，在多分类任务转二分类任务时，数据传输出错。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RookieCXL** [comment]
多分类下加入验证集出错，导致早停无法启用。
![图片](https://user-images.githubusercontent.com/33027651/99612411-7b574800-2a50-11eb-9557-7db78c3176cd.png)

**Comment by tanmc123** [comment]
感谢反馈，我们先排查一下的，确认问题后会尽快修复

**Comment by tanmc123** [comment]
目前，LR多分类暂时不支持early_stop，后续版本会再支持的
