### ISSUE TITLE
Failed to install fate_flow while running pip3 install fate-client

### ISSUE THREAD

**Issue by KleinXin** [FederatedAI/FATE#2355]
**Describe the bug**
Failed to install fate_flow while running pip3 install fate-client. Only fate_client is installed.

**To Reproduce**
1. Run pip3 install fate-client
2. Run pip3 list to check
3. Run /data/projects/fate/python/fate_flow/fate_flow_server.py
4. ModuleNotFoundError: No module named 'fate_flow'

**Expected behavior**
fate_flow is installed

**Screenshots**
![image](https://user-images.githubusercontent.com/13084622/100074504-cbcc0c80-2e79-11eb-8a40-deeb1a18e65e.png)

![image](https://user-images.githubusercontent.com/13084622/100074541-d686a180-2e79-11eb-8f25-62eba3e8dcc2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nemirorox** [comment]
FATE Flow is part of FATE package, and it is not included in FATE-Client. 
As for the described behavior, it appears to be an environment issue. Make sure to first set pythonpath to /data/projects/fate/python (or the directory where fate_flow and federatedml locate), and then execute service.sh or fate_flow_server.py inside the fate_flow directory.
