### ISSUE TITLE
When I install the FATE with docker-compose with the 1.5.0.0-relase,i find confs-10000_python_1 has error which is mysql error

### ISSUE THREAD

**Issue by liyinxin** [FederatedAI/FATE#2401]
peewee.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)")
E1215 03:22:16.512166133       9 server_chttp2.cc:40]        
{"created":"@1608002536.512091815","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1608002536.512083674","description":"Unable to configure socket","fd":13,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1608002536.512074367","description":"Cannot assign requested address","errno":99,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Cannot assign requested address","syscall":"bind"}]}]}
/bin/sh: line 1:     9 Killed                  python ./fate_flow/fate_flow_server.py

**Comment by jiahaoc1993** [comment]
@liyinxin you should update the this [IP](https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/training_template/docker-compose-eggroll.yml#L111) address

**Comment by liyinxin** [comment]
How to update IP address ? can you tell me, thanks.

**Comment by JackieeYin** [comment]
can you remember how did you solve this problem?  i have met the same error with you......
