### ISSUE TITLE
集群部署的情况下，跑quick测试，任务创建成功之后一直wait

### ISSUE THREAD

**Issue by HunDeMingMingBaiBai** [FederatedAI/FATE#2412]
**Describe the bug**
FATE集群部署的情况下，单边测试和双边测试都跑过了，但是quick测试，可以创建job，然后之后一直是wait，查看日志说是向eggroll申请资源失败，请赐教怎么解决谢谢

![image](https://user-images.githubusercontent.com/48507141/102451934-6d5b0e00-4074-11eb-9d7c-68578307051d.png)

**Comment by liyinxin** [comment]
我这边也是这个问题，请问您解决了吗：
"f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,

**Comment by HunDeMingMingBaiBai** [comment]
> 我这边也是这个问题，请问您解决了吗：
> "f_status": "success",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "success",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "success",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "success",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "success",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "success",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,
> "f_status": "success",
> "f_status_code": null,
> "f_status": "waiting",
> "f_status_code": null,

我当时是因为在虚拟机部署的集群，跳过了128G交换空间的分配，在配置足够的真实机器上部署，没出现这个问题

**Comment by liyinxin** [comment]
好的，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HunDeMingMingBaiBai"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 下午4:37
收件人: "FederatedAI/FATE"<FATE@noreply.github.com&gt;; 
抄送: "李因新"<1034113547@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [FederatedAI/FATE] 集群部署的情况下，跑quick测试，任务创建成功之后一直wait (#2412)





  
我这边也是这个问题，请问您解决了吗：
 "f_status": "success",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "success",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "success",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "success",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "success",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "success",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
 "f_status": "success",
 "f_status_code": null,
 "f_status": "waiting",
 "f_status_code": null,
  
我当时是因为在虚拟机部署的集群，跳过了128G交换空间的分配，在配置足够的真实机器上部署，没出现这个问题
