### ISSUE TITLE
host和guest必须实时通讯吗

### ISSUE THREAD

**Issue by awdrgyjilplij** [FederatedAI/FATE#2424]
有没有可能guest和host不实时通讯，而是一方训练的数据先储存在exchange上，另一方上线后从exchange上取数据再自己训练

**Comment by tanmc123** [comment]
@awdrgyjilplij 联邦学习的机制下，数据是不会直接传输的，根据不同算法会有不同的需要交互的中间结果，有些是加密，以及每轮迭代的。所以实时通信应该是效率更高的解决方案。
