### ISSUE TITLE
FATE 1.5 用Homo_LR 预测breast_homo 报错

### ISSUE THREAD

**Issue by sandyhxd** [FederatedAI/FATE#2428]
之前已经修改完预测配置文件 test_predict_conf.json 里面的 model _id 和model_version
可是在docker中运行
python python/fate_flow/fate_flow_client.py -f submit_job -c
examples/dsl/v1/homo_logistic_regression/test_predict_conf.json
后会报错
{
    "retcode": 100,
    "retmsg": "Component homo_lr_1, module HomoLR, does not pass component check, error msg is Paillier encryption mode supports 'sgd' optimizer method only."
}

fateboard 上 guest homo_lr_0 的data output里 type 仍然是train不是predict
不知道是哪里配置错了吗？有大佬解答吗？

**Comment by tanmc123** [comment]
看报错信息，是有个homo_lr_1的组件，这个组件的参数配置有问题，在加密状况下只能使用sgd
