### ISSUE TITLE
为什么按照案例跑不起来

### ISSUE THREAD

**Issue by anning666** [FederatedAI/FATE#2440]
做了个简单的LR 两份数据上传成功
# python /home/fate/standalone-fate-master-1.5.0/python/fate_flow/fate_flow_client.py -f table_info -n experiment -t breast_hetero_host
{
    "data": {
        "count": 570,
        "namespace": "experiment",
        "partition": 1,
        "schema": {
            "header": "x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19",
            "sid": "id"
        },
        "table_name": "breast_hetero_host"
    },
    "retcode": 0,
    "retmsg": "success"
}

# python /home/fate/standalone-fate-master-1.5.0/python/fate_flow/fate_flow_client.py -f table_info -n experiment -t breast_hetero_guest
{
    "data": {
        "count": 570,
        "namespace": "experiment",
        "partition": 1,
        "schema": {
            "header": "y,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9",
            "sid": "id"
        },
        "table_name": "breast_hetero_guest"
    },
    "retcode": 0,
    "retmsg": "success"
}

conf文件如下，没有改，直接从文件中拿的
{
    "initiator": {
        "role": "guest",
        "party_id": 10000
    },
    "job_parameters": {
        "work_mode": 0
    },
    "role": {
        "guest": [
            10000
        ],
        "host": [
            10000
        ],
        "arbiter": [
            10000
        ]
    },
    "role_parameters": {
        "guest": {
            "args": {
                "data": {
                    "train_data": [
                        {
                            "name": "breast_hetero_guest",
                            "namespace": "experiment"
                        }
                    ],
                    "eval_data": [
                        {
                            "name": "breast_hetero_guest",
                            "namespace": "experiment"
                        }
                    ]
                }
            },
            "dataio_0": {
                "with_label": [
                    true
                ],
                "label_name": [
                    "y"
                ],
                "label_type": [
                    "int"
                ],
                "output_format": [
                    "dense"
                ],
                "missing_fill": [
                    true
                ],
                "outlier_replace": [
                    true
                ]
            },
            "evaluation_0": {
                "eval_type": [
                    "binary"
                ],
                "pos_label": [
                    1
                ]
            }
        },
        "host": {
            "args": {
                "data": {
                    "train_data": [
                        {
                            "name": "breast_hetero_host",
                            "namespace": "experiment"
                        }
                    ],
                    "eval_data": [
                        {
                            "name": "breast_hetero_host",
                            "namespace": "experiment"
                        }
                    ]
                }
            },
            "dataio_0": {
                "with_label": [
                    false
                ],
                "output_format": [
                    "dense"
                ],
                "outlier_replace": [
                    true
                ]
            },
            "evaluation_0": {
                "need_run": [
                    false
                ]
            }
        }
    },
    "algorithm_parameters": {
        "hetero_lr_0": {
            "penalty": "L2",
            "optimizer": "rmsprop",
            "tol": 0.0001,
            "alpha": 0.01,
            "max_iter": 30,
            "early_stop": "diff",
            "batch_size": -1,
            "learning_rate": 0.15,
            "init_param": {
                "init_method": "zeros"
            },
            "sqn_param": {
                "update_interval_L": 3,
                "memory_M": 5,
                "sample_size": 5000,
                "random_seed": null
            },
            "cv_param": {
                "n_splits": 5,
                "shuffle": false,
                "random_seed": 103,
                "need_cv": false
            }
        },
        "intersect_0": {
            "intersect_method": "rsa",
            "sync_intersect_ids": true,
            "only_output_key": false
        }
    }
}

dsl文件也是
{
    "components" : {
        "dataio_0": {
            "module": "DataIO",
            "input": {
                "data": {
                    "data": [
                        "args.train_data"
                    ]
                }
            },
            "output": {
                "data": ["train"],
                "model": ["dataio"]
            }
         },
         "intersection_0": {
             "module": "Intersection",
             "input": {
                 "data": {
                     "data": [
                         "dataio_0.train"
                     ]
                 }
             },
             "output": {
                 "data": ["train"]
             }
         },
        "hetero_lr_0": {
            "module": "HeteroLR",
            "input": {
                "data": {
                    "train_data": ["intersection_0.train"]
                }
            },
            "output": {
                "data": ["train"],
                "model": ["hetero_lr"]
            }
        },
        "evaluation_0": {
            "module": "Evaluation",
            "input": {
                "data": {
                    "data": ["hetero_lr_0.train"]
                }
            }
        }
    }
}

运行后日志报错

[ERROR] [2021-01-04 16:58:58,271] [23915:139688257656640] - task_executor.py[line:196]: input data's value is empty, it does not contain a label
2
Traceback (most recent call last):
3
  File "./fate/python/fate_flow/operation/task_executor.py", line 174, in run_task
4
    run_object.run(component_parameters_on_party, task_run_args)
5
  File "./fate/python/federatedml/model_base.py", line 98, in run
6
    this_data_output = func(*real_param)
7
  File "./fate/python/federatedml/util/data_io.py", line 885, in fit
8
    data_inst = self.reader.read_data(data_inst, "fit")
9
  File "./fate/python/federatedml/util/data_io.py", line 133, in read_data
10
    raise ValueError("input data's value is empty, it does not contain a label")
11
ValueError: input data's value is empty, it does not contain a label

大神们帮帮我吧，菜鸟一个 ，只想先按照文档运行成功一次

**Comment by anning666** [comment]
已解决 ，是数据文件的问题，直接copy整个文件 就解决了

**Comment by milu5490** [comment]
你好，我和你同样的问题，都是： input data's value is empty, it does not contain a label
我之前都能运行成功，但不知道我动了哪里，现在每次提交任务后都显示这样的失败结果
我目前从新上传了数据还是这样
请问是配置文件的问题吗

**Comment by milu5490** [comment]
你好，我和你同样的问题，都是： input data's value is empty, it does not contain a label
我之前都能运行成功，但不知道我动了哪里，现在每次提交任务后都显示这样的失败结果
我目前从新上传了数据还是这样
请问是配置文件的问题吗

**Comment by anning666** [comment]
> 你好，我和你同样的问题，都是： input data's value is empty, it does not contain a label
> 我之前都能运行成功，但不知道我动了哪里，现在每次提交任务后都显示这样的失败结果
> 我目前从新上传了数据还是这样
> 请问是配置文件的问题吗

就是数据格式的原因，你用包里的案例中的数据 验证下
