### ISSUE TITLE
where can get the image of v1.5.0 哪裏可以搞到1.5版本的鏡像？

### ISSUE THREAD

**Issue by Song-xx** [FederatedAI/FATE#2442]
就像1.4那樣，1.4的鏡像是可以下載到的

**Comment by bdfa6c** [comment]
@Song-xx  What kind of image do you need? Native or kubefate?

**Comment by Song-xx** [comment]
> @Song-xx What kind of image do you need? Native or kubefate?

a kubefate one is better.
i have known use docker pull to pull all images,but a fate-1.5.0-images.tar.gz is more convenient.

**Comment by bdfa6c** [comment]
@Song-xx  I know an image, I am not sure if it's what you want.
`wget https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-docker-compose-v1.5.0.tar.gz`
There is an installation manual, [使用Docker Compose 部署FATE v1.5.0](https://mp.weixin.qq.com/s/eDbQ16_UJdwOmmQtD4xTKg)

**Comment by Song-xx** [comment]
> FederatedAI

thank you, but i am afraid it is not what i wand.  this file is kubefate,so far as i can see,one must make a image file by himself,the tutorial is in the link you give me ,but it may be a bit complex, i found use 'docker pull image' is more easier.

**Comment by Song-xx** [comment]
> @Song-xx I know an image, I am not sure if it's what you want.
> `wget https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-docker-compose-v1.5.0.tar.gz`
> There is an installation manual, [使用Docker Compose 部署FATE v1.5.0](https://mp.weixin.qq.com/s/eDbQ16_UJdwOmmQtD4xTKg)

thank you, but i am afraid it is not what i wand. this file is kubefate,so far as i can see,one must make a image file by himself,the tutorial is in the link you give me ,but it may be a bit complex, i found use 'docker pull image' is more easier.

**Comment by Song-xx** [comment]
> 就像1.4那樣，1.4的鏡像是可以下載到的

if any one do not have a image of fate-1.5.0，you can use below shell comand to get the images you need:

`bash
version=1.5.0
version_server=2.0.0
docker pull federatedai/eggroll:$version-release
docker pull federatedai/fateboard:$version-release
docker pull federatedai/python:$version-release
docker pull federatedai/client:$version-release
docker pull federatedai/serving-server:$version_server-release
docker pull federatedai/serving-proxy:$version_server-release
docker pull redis:5
docker pull mysql:8
`

**Comment by ChangxinBai** [comment]
@Song-xx 

Please check this tutorial 
https://www.mulhyac.com/details/285.html
