### ISSUE TITLE
when i check the task status, i find one f_status is success,and the other is waiting.can anyone help me?

### ISSUE THREAD

**Issue by liyinxin** [FederatedAI/FATE#2444]
(venv) [root@1ef48e13a0f5 fate_flow]#  python fate_flow_client.py -f query_task -j 202101050644283199303 | grep f_status
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,
            "f_status": "success",
            "f_status_code": null,
            "f_status": "waiting",
            "f_status_code": null,

this is the content which i get the query_task from the fate_flow_client.py

**Comment by soacker** [comment]
In Fate, one job consists of many tasks. It show that one task is finished.
