### ISSUE TITLE
Standalone FATE communicating with multiple parties

### ISSUE THREAD

**Issue by victorperezc** [FederatedAI/FATE#2445]
Hello Community and Fate Developers,

Is it possible to set up the fate system in standalone mode to work with 2 or more parties located in different physical servers ( different ips)? If so, how do I specify the parties ip's before start the training? I saw that in cluster mode you can specify the party ids so that the proxy module can resolve and communicate with the party, however, I haven't seen a way of doing this in standalone mode. 

Thanks,
Victor

**Comment by dylan-fan** [comment]
this feature will be supported in v1.7
