### ISSUE TITLE
quick_run.py中路径配置错误

### ISSUE THREAD

**Issue by fei-chang** [FederatedAI/FATE#2448]
**错误描述**
在测试脚本examples/dsl/v1/quick_run.py中，读取fate_flow.py的路径仍为1.2版本中的路径。由于1.5版本中安装包结构发生变化，目前代码会导致fate_flow.py脚本无法正常读取。

目前代码为：
```
FATE_FLOW_PATH = HOME_DIR + "/../../fate_flow/fate_flow_client.py"
```
应修改为：
```
FATE_FLOW_PATH = HOME_DIR + "/../../../pytthon/fate_flow/fate_flow_client.py"
```

**Comment by ChangxinBai** [comment]
应修改为下面的吧：
FATE_FLOW_PATH = "../../../python/fate_flow/fate_flow_client.py"
