### ISSUE TITLE
Pipeline Examples 'Connection refused, Please check if the fate flow service is started'

### ISSUE THREAD

**Issue by ChangxinBai** [FederatedAI/FATE#2449]
Hi there,

I am interested in using FATE to do some research problems. 

I used the Stand-alone Deployment Guide with docker  environment successfully. 

Unfortunately, when I try to execute the command in the demo folder below:
root@e7e3434e58b1:/fate/examples/pipeline/demo# python pipeline-upload.py -base /fate

I got these error informations below:
2021-01-06 08:47:03.424 | ERROR    | __main__:main:63 - An error has been caught in function 'main', process 'MainProcess' (369), thread 'MainThread' (139780264617792):
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 105, in upload_data
    raise ValueError

ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "pipeline-upload.py", line 73, in <module>
    main(args.base)
    │    │    └ '/fate'
    │    └ Namespace(base='/fate')
    └ <function main at 0x7f2120e02e18>

> File "pipeline-upload.py", line 63, in main
    pipeline_upload.upload(work_mode=work_mode, backend=backend, drop=1)
    │               │                │                  └ <Backend.EGGROLL: 0>
    │               │                └ <WorkMode.STANDALONE: 0>
    │               └ <function PipeLine.upload at 0x7f20e9652950>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7f20e9643b00>

  File "/usr/local/lib/python3.6/site-packages/pipeline/backend/pipeline.py", line 495, in upload
    self._train_job_id, detail_info = self._job_invoker.upload_data(upload_conf, int(drop))
    │    │                            │    │            │           │                └ 1
    │    │                            │    │            │           └ {'file': '/fate/examples/data/breast_hetero_guest.csv', 'table_name': 'breast_hetero_guest', 'namespace': 'experiment', 'head...
    │    │                            │    │            └ <function JobInvoker.upload_data at 0x7f20e96482f0>
    │    │                            │    └ <pipeline.utils.invoker.job_submitter.JobInvoker object at 0x7f20e9643ac8>
    │    │                            └ <pipeline.backend.pipeline.PipeLine object at 0x7f20e9643b00>
    │    └ None
    └ <pipeline.backend.pipeline.PipeLine object at 0x7f20e9643b00>
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 113, in upload_data
    raise ValueError("job submit failed, err msg: {}".format(result))
                                                             └ {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 105, in upload_data
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipeline-upload.py", line 73, in <module>
    main(args.base)
  File "pipeline-upload.py", line 63, in main
    pipeline_upload.upload(work_mode=work_mode, backend=backend, drop=1)
  File "/usr/local/lib/python3.6/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipeline/backend/pipeline.py", line 495, in upload
    self._train_job_id, detail_info = self._job_invoker.upload_data(upload_conf, int(drop))
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 113, in upload_data
    raise ValueError("job submit failed, err msg: {}".format(result))
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

Any suggestions are welcome.
Thanks

**Comment by gongyan200** [comment]
When initialize pipeline "pipeline init --ip 127.0.0.1 --port 9380",
change 127.0.0.1 to the contianer ip,  such as "192.167.1.100"
It works for me.

**Comment by gongyan200** [comment]
Find your contianer ip as follow
![image](https://user-images.githubusercontent.com/14838533/103766154-4d0de600-5059-11eb-82ba-1059aa453419.png)

**Comment by ChangxinBai** [comment]
> Find your contianer ip as follow
> ![image](https://user-images.githubusercontent.com/14838533/103766154-4d0de600-5059-11eb-82ba-1059aa453419.png)

Yes, it works! Thanks soooo much.

**Comment by Edwin-Xu** [comment]
> 

it works for me, too

**Comment by Edwin-Xu** [comment]
mark

**Comment by ForLynda** [comment]
Hi! I have same problem, but chanigng ip doensn't solely resolve the problem.
Should I change the number of port as well?

**Comment by Thxyg** [comment]
This works for me
but I can't query IP-related commands in my container class
execute "docker inspect < container id> : grep IPAddress" outside the container my be find you container IP
