### ISSUE TITLE
线性回归模型在线测试无预测结果

### ISSUE THREAD

**Issue by Laiyigui** [FederatedAI/FATE#2452]
host.csv数据
`id,x1
1,1
2,2
3,3
4,4
5,5
6,6
7,7
8,8`
guest.csv数据
`id,y,x0
1,1,0
2,2,1
3,3,0
4,4,1`
job_conf.json
```
{
    "initiator": {
        "role": "guest",
        "party_id": 9999
    },
    "job_parameters": {
        "work_mode": 1
    },
    "role": {
        "guest": [
            9999
        ],
        "host": [
            10000
        ],
        "arbiter": [
            10000
        ]
    },
    "role_parameters": {
        "guest": {
            "args": {
                "data": {
                    "train_data": [
                        {
                            "name": "test",
                            "namespace": "test"
                        }
                    ]
                }
            },
            "dataio_0": {
                "with_label": [
                    true
                ],
                "label_name": [
                    "y"
                ],
                "label_type": [
                    "float"
                ],
                "output_format": [
                    "dense"
                ],
                "missing_fill": [
                    true
                ],
                "outlier_replace": [
                    false
                ]
            },
            "evaluation_0": {
                "eval_type": [
                    "regression"
                ],
                "pos_label": [
                    1
                ]
            }
        },
        "host": {
            "args": {
                "data": {
                    "train_data": [
                        {
                            "name": "test",
                            "namespace": "test"
                        }
                    ]
                }
            },
            "dataio_0": {
                "with_label": [
                    false
                ],
                "output_format": [
                    "dense"
                ],
                "outlier_replace": [
                    false
                ]
            },
            "evaluation_0": {
                "need_run": [
                    false
                ]
            }
        }
    },
    "algorithm_parameters": {
        "hetero_linr_0": {
            "penalty": "L2",
            "optimizer": "sgd",
            "tol": 0.001,
            "alpha": 0.01,
            "max_iter": 20,
            "early_stop": "weight_diff",
            "batch_size": -1,
            "learning_rate": 0.15,
            "decay": 0.0,
            "decay_sqrt": false,
            "init_param": {
                "init_method": "zeros"
            },
            "encrypted_mode_calculator_param": {
                "mode": "fast"
            }
        }
    }
}
```
dsl_conf.json
`{
    "components" : {
        "dataio_0": {
            "module": "DataIO",
            "input": {
                "data": {
                    "data": [
                        "args.train_data"
                    ]
                }
            },
            "output": {
                "data": ["train"],
                "model": ["dataio"]
            }
         },
         "intersection_0": {
             "module": "Intersection",
             "input": {
                 "data": {
                     "data": [
                         "dataio_0.train"
                     ]
                 }
             },
             "output": {
                 "data": ["train"]
             }
         },
        "hetero_linr_0": {
            "module": "HeteroLinR",
            "input": {
                "data": {
                    "train_data": ["intersection_0.train"]
                }
            },
            "output": {
                "data": ["train"],
                "model": ["hetero_linr"]
            }
        },
        "evaluation_0": {
            "module": "Evaluation",
            "input": {
                "data": {
                    "data": ["hetero_linr_0.train"]
                }
            }
        }
    }
}`
调用在线推理接口
curl -X POST -H 'Content-Type: application/json' -i 'http://localhost:8059/federation/v1/inference' --data '{
  "head": {
    "serviceId": "test"
  },
  "body": {
    "featureData": {
      "x0": 1
    },
    "sendToRemoteFeatureData": {
      "id": "5"
    }
  }
}'
预测结果
{
    "retcode": 0,
    "retmsg": "",
    "data": {
        "modelId": "guest#9999#arbiter-10000#guest-9999#host-10000#model",
        "modelVersion": "2021010412180273130115",
        "timestamp": 1609809836490
    },
    "flag": 0
}
无预测结果值，是线性回归算法的bug吗

**Comment by nemirorox** [comment]
Serving目前不支持线性模型。所有支持的算法组件请参考：https://github.com/FederatedAI/FATE-Serving/tree/master/fate-serving-federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model 

Serving currently does not support online inference with HeteroLinR model. For supported modules, please refer here:  https://github.com/FederatedAI/FATE-Serving/tree/master/fate-serving-federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model
