### ISSUE TITLE
 HomoSecureBoost does not exist under the fold federatedml.setting_conf

### ISSUE THREAD

**Issue by bohea** [FederatedAI/FATE#2484]
**Describe the bug**

Component fed_train_0, module HomoSecureBoost does not exist under the fold federatedml.setting_conf

**To Reproduce**
1. submit a HomoSecureBoost train job

**Additional context**
rename  federatedml/conf/setting_conf/HomoSecureboost.json  to HomoSecureBoost.json

will fix it

**Comment by talkingwallace** [comment]
https://github.com/FederatedAI/FATE/blob/develop-1.6/python/federatedml/conf/setting_conf/HomoSecureboost.json 
Here is the setting conf of module 'HomoSecureBoost'.
The naming does not strictly follow the camel case. We will fix it.
Thanks for your advice :).
