### ISSUE TITLE
Question: Changing and Updating an algorithm component

### ISSUE THREAD

**Issue by fei-chang** [FederatedAI/FATE#2503]
If I want to change an algorithm component, (instead of creating a new one), what should I do to upload changed scripts and make the changes effective? 

For example, if I want to define a new parameter in component 'intersection', how should I update the changed 'intersection' component to replace the old version? 

Thanks for helping out.

**Comment by tanmc123** [comment]
@fei-chang 
You should be able to achieve it by directly replacing your new version codes. After replacement, restart fate-flow, and it should be able to be shown on fate-board too.
