### ISSUE TITLE
Why don't you use the tensorflow encryption methods rather than the Python Paillier?

### ISSUE THREAD

**Issue by liuyejia** [FederatedAI/FATE#2586]
Hi, 

We did some tests on integers and found out that tf-encryption seems 10x faster than the phe. The only disadvantages are the tensorflow encryption haven't implemented complete methods to deal with floats and we are currentlt manually developing them.

May I know why you team not implement an underlyting cryption package based on C++/C or others to expediate the computation for FATE? Is it because this kind of work won't contribute much to your system efficiency? But we found out in our system that encryption & decryption took most of the time in computation.

I am looking forward to your answers. Thank you!

**Comment by weiwee** [comment]
> Hi,
> 
> We did some tests on integers and found out that tf-encryption seems 10x faster than the phe. The only disadvantages are the tensorflow encryption haven't implemented complete methods to deal with floats and we are currentlt manually developing them.
> 
> May I know why you team not implement an underlyting cryption package based on C++/C or others to expediate the computation for FATE? Is it because this kind of work won't contribute much to your system efficiency? But we found out in our system that encryption & decryption took most of the time in computation.
> 
> I am looking forward to your answers. Thank you!

Well，FATE has long developing history compare to  tf-encrypted...
We have do some test about gmpy2, and the result shows that there is no much overhead in gmpy2's GMP wrapper. The phe implemention in tf-encrypted also based on a wrapper GMP program wapper, tf-big. We may test is later to found out an objective comparison.  Thanks for reporting.
