### ISSUE TITLE
Only deployed models could be used to execute process of loading. Please deploy model before loading

### ISSUE THREAD

**Issue by wenmengzhou** [FederatedAI/FATE#2605]
FATE version: 1.5.1 
according to doc https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md#加载模型. when I finished training and load model for online inference, error occurs:

{
    "data": {
        "detail": {
            "guest": {
                "9999": {
                    "retcode": 100,
                    "retmsg": "Only deployed models could be used to execute process of loading. Please deploy model before loading."
                }
            },
            "host": {
                "10000": {
                    "retcode": 100,
                    "retmsg": "Only deployed models could be used to execute process of loading. Please deploy model before loading."
                }
            }
        },
        "guest": {
            "9999": 100
        },
        "host": {
            "10000": 100
        }
    },
    "jobId": "2021022410084208673718",
    "retcode": 101,
    "retmsg": "failed"
}

**Comment by wenmengzhou** [comment]
use flow model deploy and use the model_version and model_id returned to load.

But I failed in load model with following error:
model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct.

**Comment by VincyChen96** [comment]
Have you solved it? I met the same problem.

**Comment by JackieeYin** [comment]
> 你解决了吗？我也遇到了同样的问题。

请问你解决了吗，我也遇到了这个问题

**Comment by caihy05** [comment]
你解决了，我也遇到了这个问题

**Comment by Edwin-Xu** [comment]
> > 你解决了吗？我也遇到了同样的问题。
> 
> 请问你解决了吗，我也遇到了这个问题

请问你解决了吗，我也遇到了这个问题

**Comment by Edwin-Xu** [comment]
[ERROR] c.w.a.f.s.c.p.ModelServiceProvider(AbstractServiceAdaptor.java:143) - do service fail, cause by: model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct.
