### ISSUE TITLE
运行dsl v2中的hetero fast secureboost报错"__init__() got an unexpected keyword argument 'sparse_optmization'"

### ISSUE THREAD

**Issue by furuifr** [FederatedAI/FATE#2619]
想跑下dsl_v2的hetero fast secureboost，运行代码：python fate_flow_client.py -f submit_job -d examples/test_fast_sbt_dsl.json -c examples/test_fast_sbt_mix_conf.json python，报错：
{
    "retcode": 100,
    "retmsg": "__init__() got an unexpected keyword argument 'sparse_optmization'"
}

**Comment by dylan-fan** [comment]
which fate version？

**Comment by peiji1981** [comment]
> "**init**() got an unexpected keyword argument 'sparse_optmization'"

hi, how to solve this issue?

**Comment by peiji1981** [comment]
> which fate version？

1.5

**Comment by meldonization** [comment]
Same problem here, any answers?

**Comment by meldonization** [comment]
@peiji1981 @furuifr  hetero fast secure boost typo `sparse_optmization` problem is solved in FATE-1.6

# FATE-1.5
![fate_old_1 5](https://user-images.githubusercontent.com/1425792/133391832-f46ff3ae-5b57-4d4e-9ce1-0e90788f4bb3.png)

# FATE-1.6
![fate_new_1 6](https://user-images.githubusercontent.com/1425792/133392080-58132ef1-42d7-4f4a-99e8-62ff270242c1.png)

**Comment by weiwee** [comment]
thanks report 
it's typo issue and fix in 1.5.1, close issue
