### ISSUE TITLE
提交job总是出错

### ISSUE THREAD

**Issue by ghost** [FederatedAI/FATE#2620]
job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

这个服务提示没有开，docker 单机的 请问怎么起

**Comment by thyxsl** [comment]
还有在执行
 ```
python demo/pipeline-upload.py --base /data/projects/fate
```
出现
The file is obtained from the fate flow client machine, but it does not exist, please check the path: /data/projects/fate/ex

**Comment by DiegoCao** [comment]
可以直接跑fate_flow/fate_flow_client.py的代码

**Comment by ybenxin** [comment]
我也存在你这样的问题，然后你这IP设置的不对，你如果装的是docker那就打开docker看一下里面设置的ip，文件名是docker_standalone.yml，里面有两个地址，你用第二个试试（我successful了）。root@0bd20afb2d1c:/fate/logs/FATE-master# 
    flow init --ip 192.167.1.100 --port 9380。直接代码设置一下ip就行。祝你成功！
