### ISSUE TITLE
上传数据出错

### ISSUE THREAD

**Issue by ghost** [FederatedAI/FATE#2621]
docker单独1.5.0版本使用flow 上传数据
```
flow data upload -c dsl_test/upload_data.json
```

出现 required parameters are missing: work_mode,namespace,table_name,head,partition 错误

upload_data.json如下
``` json
{
  "file": "examples/data/breast_hetero_guest.csv",
  "table_name": "hetero_breast_guest",
  "namespace": "experiment",
  "head": 1,
  "partition": 8,
  "work_mode": 0,
  "backend": 0
}
```

**Comment by BeatBoxerLrd** [comment]
python /data/projects/fate/python/fate_flow/fate_flow_client.py -f upload -drop 1 -c eggroll_guest_upload_conf.json
