### ISSUE TITLE
OnehotEncoder逻辑是否有Bug

### ISSUE THREAD

**Issue by zfen0913** [FederatedAI/FATE#2639]
sklearn的onehot分两个步骤：
1、将训练集与测试集的数据合并做fit
2、分别对训练集数据、测试集数据做tranform得到2份结果

但fate的onehot，却是训练集单独onehot_0，输入数据集只有训练集自身的数据，测试集单独onehot_1，输入数据集为测试数据集及onehot_0的model，并没有将2个数据集合并做fit的过程：
"one_hot_0": {
            "module": "OneHotEncoder",
            "input": {
                "data": {
                    "data": [
                        "intersection_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ],
                "model": [
                    "model"
                ]
            }
        },
        "one_hot_1": {
            "module": "OneHotEncoder",
            "input": {
                "data": {
                    "data": [
                        "intersection_1.data"
                    ]
                },
                "model": [
                    "one_hot_0.model"
                ]
            },
            "output": {
                "data": [
                    "data"
                ],
                "model": [
                    "model"
                ]
            }
        },

**Comment by xiaoqing928** [comment]
你好，我使用过横向onehot--‘’Homo_OneHot_Encoder‘’，跟你的处理一样，测试集单独onehot_1，输入数据集为测试数据集及onehot_0的model，特征可以保持一致。同时也会存在问题，测试集单独onehot_1的得到的特征同训练集onehot_0一致，但onehot_1之后out_put的数据全是0。很奇怪，希望有人能解答一下。

**Comment by zfen0913** [comment]
> 他的逻辑是没有问题的，fate会把训练集onehot之后的特征记录下来，测试集只需和训练集保持一致即可

如果测试集里有的特征值在训练集里是没有的呢，比如城市，训练集里有上海、北京、深圳，训练集onehot之后扩展出来的特征列是city_上海，city_北京，city_深圳，那测试集里出现城市是成都的呢？

难道必须要保证测试集里的特征值不要超出训练集里包含的取值吗？这样数据准备很麻烦啊

**Comment by tanmc123** [comment]
> > 他的逻辑是没有问题的，fate会把训练集onehot之后的特征记录下来，测试集只需和训练集保持一致即可
> 
> 如果测试集里有的特征值在训练集里是没有的呢，比如城市，训练集里有上海、北京、深圳，训练集onehot之后扩展出来的特征列是city_上海，city_北京，city_深圳，那测试集里出现城市是成都的呢？
> 
> 难道必须要保证测试集里的特征值不要超出训练集里包含的取值吗？这样数据准备很麻烦啊

你说的这个问题的话，即使加进了验证数据，未来遇到真实预测数据的时候，一样有可能遇到从未出现的值，这个无法避免的。现在的逻辑是，如果测试集出现训练集没有的值，则转化的所有值都为0.
