### ISSUE TITLE
evaluation评测结果是否又bug？！

### ISSUE THREAD

**Issue by xiaoqing928** [FederatedAI/FATE#2665]
前端显示是否存在bug？
如下图所示，通过混淆矩阵手动计算的精确率和召回率，和前端显示的完全不一致，是前端显示的bug吗？

![微信图片_20210319152059](https://user-images.githubusercontent.com/34981842/111744869-d5fd9500-88c6-11eb-9f32-e523535eb208.jpg)

**Comment by talkingwallace** [comment]
hi，
上面那个的threshold是50%分位点（Quantile），
下面那个的threshold是0.5（实值），二者是不一样的。

**Comment by mgqa34** [comment]
Problem solved, issue close
