### ISSUE TITLE
fate_flow_client命令无法进行predict任务

### ISSUE THREAD

**Issue by xiaoqing928** [FederatedAI/FATE#2667]
rt，使用fate_flow_client命令无法进行预测任务，运行编辑好的conf文件（预测），会返回retcode:100，retmsg:pipeline，而无法进行预测任务。

**Comment by jinjiel1994** [comment]
是1.5.1版本吗，看看模型deploy了没

**Comment by xiaoqing928** [comment]
请问1.5.1模型怎么实现deploy，fate_flow_client没有deploy的命令



---原始邮件---
发件人: "Jim ***@***.***&gt;
发送时间: 2021年3月22日(周一) 晚上6:54
收件人: ***@***.***&gt;;
抄送: "scientific ***@***.******@***.***&gt;;
主题: Re: [FederatedAI/FATE] fate_flow_client命令无法进行predict任务 (#2667)




 
是1.5.1版本吗，看看模型deploy了没
