### ISSUE TITLE
震惊！！fate_flow_client发起predict批量预测任务竟然无法使用

### ISSUE THREAD

**Issue by xiaoqing928** [FederatedAI/FATE#2677]
rt，使用fate_flow_client命令无法进行预测任务，运行编辑好的conf文件（预测），
会返回retcode:100，retmsg:pipeline，
无法进行预测任务。
DAGScheduler部分代码如下，发现传入了一个‘pipeline’的字符串，而不是模型相关的参数
![1](https://user-images.githubusercontent.com/34981842/112288985-d7fd9480-8cc8-11eb-8704-bf6e25597d06.png)
后面component_name, model_alias的信息读取不到
![2](https://user-images.githubusercontent.com/34981842/112290029-ccf73400-8cc9-11eb-9b65-6b1a006d0f93.png)
求官方答疑解惑！

**Comment by izhfeng00** [comment]
你好，请问是否方便提供一下你编辑的预测conf文件以及当前使用的FATE版本号？

**Comment by xiaoqing928** [comment]
conf文件如下图所示，FATE是官方1.5.0 release
![image](https://user-images.githubusercontent.com/34981842/112924397-9f374280-9142-11eb-962f-fecd52458553.png)
![image](https://user-images.githubusercontent.com/34981842/112924480-c726a600-9142-11eb-94b1-05964959aee6.png)
