### ISSUE TITLE
federatedrec 在哪

### ISSUE THREAD

**Issue by Donkequan** [FederatedAI/FATE#2682]
1.3版本由联邦推荐的federatedrec，现在1.5版本不见了，是取消了吗，还是更新到哪里了？

**Comment by mgqa34** [comment]
> 1.3版本由联邦推荐的federatedrec，现在1.5版本不见了，是取消了吗，还是更新到哪里了？

Please refor to this issue: https://github.com/FederatedAI/FATE/issues/2692
