### ISSUE TITLE
How to use pipeline to submit a DNN job which in ptorch backend?

### ISSUE THREAD

**Issue by kaikaokao** [FederatedAI/FATE#2685]
How to use pipeline to submit a DNN job which in ptorch backend?
Does it supoprt for use pipeline to submit a DNN job which in ptorch backend?

**Comment by mgqa34** [comment]
Pipeline does not support yet, you can submit it will dsl v2: https://github.com/FederatedAI/FATE/tree/master/examples/dsl/v2/homo_nn/mnist_demo
