### ISSUE TITLE
federatedrec相关

### ISSUE THREAD

**Issue by XYT2000** [FederatedAI/FATE#2692]
请问联邦推荐的算法即1.3的
federatedrec是被取消了么

**Comment by Donkequan** [comment]
同问

**Comment by mgqa34** [comment]
Federated Recommendation is a independent repo of FATE,  please refer to: https://github.com/FederatedAI/FedRec

**Comment by XYT2000** [comment]
> Federated Recommendation is a independent repo of FATE, please refer to: https://github.com/FederatedAI/FedRec

请问这一块有相应的文档支持么，因为我需要做一个联邦推荐系统，但是在您给的项目下没有找到相应的学习文档。

**Comment by mgqa34** [comment]
You may create some issue on FedRec repo instead of FATE

**Comment by mgqa34** [comment]
> > Federated Recommendation is a independent repo of FATE, please refer to: https://github.com/FederatedAI/FedRec
> 
> 请问这一块有相应的文档支持么，因为我需要做一个联邦推荐系统，但是在您给的项目下没有找到相应的学习文档。

https://github.com/FederatedAI/FedRec/tree/master/federatedrec

**Comment by XYT2000** [comment]
> You may create some issue on FedRec repo instead of FATE, this issue will be close in near days

我怀疑那个项目已经作废停止维护了
