### ISSUE TITLE
fate集群，使用mnist训练数据模型，按照彭路工程师发布的博客操作，为什么任务出错了？

### ISSUE THREAD

**Issue by GrandyJames** [FederatedAI/FATE#2739]
我按照这个彭路工程师的操作，https://my.oschina.net/u/4238514/blog/3279779
使用fate集群，mnist数据集来训练模型，
为什么任务训练出错了。。
看不懂报错信息55555
不知道怎么解决，求大神指教，，

任务提交成功，但是执行失败，报错信息如下：
![image](https://user-images.githubusercontent.com/50815935/114028361-f9ef3d80-98aa-11eb-82b6-00675187d554.png)

修改损失函数为categorical_crossentpoty时，报错如下：
![image](https://user-images.githubusercontent.com/50815935/114028241-d88e5180-98aa-11eb-98d3-a713e943f377.png)

[ERROR] [2021-04-08 12:07:35,634] [2600:140528646215488] - task_executor.py[line:191]: You are passing a target array of shape (30000, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:

```

from keras.utils import to_categorical

y_binary = to_categorical(y_int)

y_binary = to_categorical(y_int)

```

Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.

Traceback (most recent call last):

  File "./fate/python/fate_flow/operation/task_executor.py", line 168, in run_task

    run_object.run(component_parameters_on_party, task_run_args)

  File "./fate/python/federatedml/model_base.py", line 101, in run

    this_data_output = func(*params)

  File "./fate/python/federatedml/nn/homo_nn/enter_point.py", line 107, in fit

    _version_0.client_fit(self=self, data_inst=data)

  File "./fate/python/federatedml/nn/homo_nn/_version_0.py", line 161, in client_fit

    self.nn_model.train(data, aggregate_every_n_epoch=self.aggregate_every_n_epoch)

  File "./fate/python/federatedml/nn/backend/tf_keras/nn_model.py", line 250, in train

    self._model.fit(x=data, epochs=epochs, verbose=1, shuffle=True, **left_kwargs)

  File "/opt/app-root/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py", line 808, in fit

    use_multiprocessing=use_multiprocessing)

  File "/opt/app-root/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator_v1.py", line 593, in fit

    steps_name='steps_per_epoch')

  File "/opt/app-root/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator_v1.py", line 259, in model_iteration

    batch_outs = batch_function(*batch_data)

  File "/opt/app-root/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py", line 1063, in train_on_batch

    extract_tensors_from_dataset=True)

  File "/opt/app-root/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2336, in _standardize_user_data

**Comment by GrandyJames** [comment]
构建出的模型json：
{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 784], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "batch_input_shape": [null, 784], "dtype": "float32", "units": 512, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 256, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_2", "trainable": true, "dtype": "float32", "units": 10, "activation": "softmax", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}]}, "keras_version": "2.4.0", "backend": "tensorflow"}

**Comment by jplnasa5** [comment]
兄弟问题解决了吗
