### ISSUE TITLE
Where is the proto_generate.sh?

### ISSUE THREAD

**Issue by Milkve** [FederatedAI/FATE#2746]
**Describe the bug**
Where is the [proto_generate.sh](https://github.com/FederatedAI/FATE/blob/master/doc/python/federatedml/protobuf/proto_generate.sh)?
https://github.com/FederatedAI/FATE/blob/178f04d1a58181359d6550b4673d4b4dc72a778f/doc/develop_guide.rst#L266

By the way, how to recompile the whole FATE after generating files from `.proto` files.

**Comment by tanmc123** [comment]
It is located here: https://github.com/FederatedAI/FATE/blob/master/python/fate_arch/protobuf/generate_py.sh

We will fix the doc later. Thank you for pointing out.
