### ISSUE TITLE
车联网与联邦学习结合的话用standalone还是cluster

### ISSUE THREAD

**Issue by wgboy23** [FederatedAI/FATE#2748]

**Comment by Milkve** [comment]
Please briefly describe the scenario of your demands in Internet of Vehicles, how to combine your demands with federated learning. Generally, computers on vehicles have limited capability which can hardly cover training assignments locally. If you send some data collected from sensors to computing server, you must take latency among all vehicles and servers. Also, cost is always a big deal.

**Comment by wgboy23** [comment]
感谢您的回答，具体场景确实如您所说。我们的想法是在这样的场景下进行，车辆之间要想互相通信，需要借助每个路口的路边单元，可以把路边单元看做一个基站，通过基站决定走哪条信道，从而使整个网络中的信道负载达到最优，最主要的部分是路边单元收集车辆通信请求数据后，传到联邦学习的框架里，训练完成后返回方案。但是现在我们不知道该如何将路边单元的数据传到联邦学习框架里，以及是否有已有的合适的算法，感谢您的指导，非常期待您对以上问题的解答，万分感谢



> Please briefly describe the scenario of your demands in Internet of Vehicles, how to combine your demands with federated learning. Generally, computers on vehicles have limited capability which can hardly cover training assignments locally. If you send some data collected from sensors to computing server, you must take latency among all vehicles and servers. Also, cost is always a big deal.
