### ISSUE TITLE
请问下，现在serving支持dsl_v2了吗？（因模型部署上线后预测无结果而有的猜疑....）

### ISSUE THREAD

**Issue by ioracion** [FederatedAI/FATE#2752]
（dockers部署的）用最新版的fate跑pipeline训练出的模型在部署上线时，过程都是success，但是到推理测试就是啥结果也没，返回结果像下面这样：

- {"retcode":0,"retmsg":"","data":{"modelId":"guest#9999#guest-9999#host-10000#model","modelVersion":"2021041903133901753497","timestamp":1618802149453},"flag":0}

然后瞅了下serving-server容器，发现在运行加载模型命令（**_flow model load -c publish_load_model.json_**）的时候，这个容器logs里会报这个错：

- DSLParser init catch error:{}
 org.json.JSONException: JSONObject["input"] not found.

就怀疑是解析dsl时出错了，所以想问下现在的serving是不是还不支持dsl_v2？如果是的话，难道还要用dsl_v1来上线？或是其他什么方式？大佬们求解orz
@nemirorox @weiwee @jarviszeng-zjc @tanmc123

**Comment by jiahaoc1993** [comment]
@ioracion 2.0.4的fate serving是支持DSL 2.0的

**Comment by ioracion** [comment]
@jiahaoc1993 感谢回复！
希望能再帮忙解疑下：就是在加载模型时，serving-server容器后台会报这个错：
![log](https://user-images.githubusercontent.com/17641924/115361589-4dd71c00-a1f3-11eb-842d-2583db337716.png)
我部属的流程是这样的（按照pipeline预测例子弄的，是不是这样不对？）：
![微信截图_20210420161000](https://user-images.githubusercontent.com/17641924/115361710-69422700-a1f3-11eb-8699-856d5f45b145.png)

**Comment by jiahaoc1993** [comment]
@ioracion 容器版本的serving是2.0.0的，所以报错正常

**Comment by ioracion** [comment]
@jiahaoc1993 非常感谢！问题解决了
