### ISSUE TITLE
纵向联邦学习SecureBoost

### ISSUE THREAD

**Issue by miracle625** [FederatedAI/FATE#2753]
SecureBoost算法中计算分割点的算法Split Finding具体代码在哪里实现的？

**Comment by mgqa34** [comment]
You can refer to 
python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/splitter.py
and 
python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py#L186 (federated find process)
