### ISSUE TITLE
Homo_onehot存在特征不能对齐的bug！

### ISSUE THREAD

**Issue by xiaoqing928** [FederatedAI/FATE#2758]
**1、问题描述**
在真实场景下使用横向onehot对数据做处理，之后再用横向LR模型，得到的结果与预期相差非常大（远远不如只使用本地数据），完全不可用。
**2、实验过程**
经过多次实验，发现横向LR得到的结果均很差，Debug横向LR的计算逻辑，没有发现问题，十分无助。后来，无意中检查了onehot之后的特征列，如下图所示：
![image](https://user-images.githubusercontent.com/34981842/115832226-3c854e00-a445-11eb-92b5-5f3cf59dfe17.png)
上图是guest方使用homo_onehot之后特征顺序的结果
![image](https://user-images.githubusercontent.com/34981842/115832412-76eeeb00-a445-11eb-9ae4-f395d4de6642.png)
上图是host方使用homo_onehot之后特征顺序的结果
可以看到，使用homo_onehot得到的特征顺序不一致！
**不免有些疑惑，计算的时候是根据字段名还是字段顺序计算的？**
![image](https://user-images.githubusercontent.com/34981842/115832694-c46b5800-a445-11eb-8643-133dafe1ba3f.png)
上图是guest方第一次本地计算的参数结果
![image](https://user-images.githubusercontent.com/34981842/115832784-e1079000-a445-11eb-9426-73f5d9c5bc88.png)
 上图是host方第一次本地计算的参数结果
由于在实验条件下两边上传了一样的数据，可以看到对应特征名下的参数值是相同的，接下来看一下聚合的结果：
![image](https://user-images.githubusercontent.com/34981842/115833183-53787000-a446-11eb-93d4-3c6a9f848dc5.png)
**3、结论**
不免有些惊讶，竟然是根据特征顺序进行计算的，但是homo_onehot得到的特征顺序又不一致，导致参数更新时梯度信息混乱，得到十分意外的结果。
感谢FATE平台，感谢FATE开源社区，希望FATE能够越来越好！！

**Comment by tanmc123** [comment]
确实有这个问题，预计将在1.5.2修复，感谢提出
