### ISSUE TITLE
sm3 encode error

### ISSUE THREAD

**Issue by Laughingtt** [FederatedAI/FATE#2773]
sm3 在base64下编码错误,多加了encode语句

![image](https://user-images.githubusercontent.com/56598312/117402353-cc90c080-af38-11eb-8824-86a47ae34fc2.png)
![image](https://user-images.githubusercontent.com/56598312/117402381-dadedc80-af38-11eb-80c7-2bf844478912.png)

**Comment by nemirorox** [comment]
感谢提起issue。
截图中错误已计划在1.7版本修复，使用当前1.6版本可以先按照上述截图修改对应文件：
https://github.com/FederatedAI/FATE/blob/master/python/federatedml/secureprotol/hash/hash_factory.py#L67
