### ISSUE TITLE
Layers support

### ISSUE THREAD

**Issue by saviord7** [FederatedAI/FATE#2784]
Hello!

Is FATE still does not support LSTM layers and timeseries data in deploying NN models?

Thank you.

**Comment by SaviorD7** [comment]
Any answers ?  :/

**Comment by SennriSyunnga** [comment]
maybe you can use 'keras' config
In that case, you just use keras sequential directly，and you can build any layer defined in keras layers, such as LSTM & Conv1D
Thought somehow it works, , but i am not for sure FATE support rnn & cnn well indeed.
