### ISSUE TITLE
Can FATE Work in Vertical Federated Learning Scenario?

### ISSUE THREAD

**Issue by JiminKung** [FederatedAI/FATE#2785]
Hello, 
I'm new to FATE. I really wonder whether FATE can be great in the industrial internet area and how to applied FATE in vertical federated learning. 
Looking for your reply.

**Comment by SaviorD7** [comment]
You can check Hetero Algorithms [here](https://github.com/FederatedAI/FATE/tree/master/python/federatedml)

**Comment by JiminKung** [comment]
@SaviorD7 Thank you, I'll take a look : )
