### ISSUE TITLE
【report】component_properties.py中抛出错误的英文逻辑有误

### ISSUE THREAD

**Issue by SennriSyunnga** [FederatedAI/FATE#2796]
if self.need_cv or self.need_stepwise:
            if not self.has_train_data:
                raise DSLConfigError("Train_data should be configured in cross-validate "
                                     "task or stepwise task")
            if self.has_validate_data or self.has_normal_input_data or \
                    self.has_test_data:
                raise DSLConfigError("Train_data should be set only in cross-validate "
                                     "task or stepwise task")

根据上下文逻辑，实际下面这个判断应为

            if self.has_validate_data or self.has_normal_input_data or \
                    self.has_test_data:
                raise DSLConfigError("Only train_data should be set in cross-validate "
                                     "task or stepwise task")

**Comment by tanmc123** [comment]
Will Fix it. Thank you
