### ISSUE TITLE
fateboard中日志信息不显示

### ISSUE THREAD

**Issue by agenthong** [FederatedAI/FATE#2800]
fateboard看板无法显示上次数据，训练，测试等的日志和进度信息，不知道是什么原因日志上传到fateboard不行，请问下fateboard的日志在哪里可以找到呢？想看看问题在哪
![image](https://user-images.githubusercontent.com/59220627/119109618-e90e1c00-ba53-11eb-8229-18f344010618.png)
![image](https://user-images.githubusercontent.com/59220627/119109674-f4614780-ba53-11eb-88c1-d65202c4bb30.png)

**Comment by dannis97500** [comment]
新的版本fateboard会出现此问题
