### ISSUE TITLE
Run FATE with one client

### ISSUE THREAD

**Issue by saviord7** [FederatedAI/FATE#2808]
Hello!
How I can run FATE job by the one client. I mean is it possible to run FATE without Federated Learning (FL)  just like casual ml model by keras with one dataset?
 Or it is not impossible ? Maybe I can simulate FATE training without FL by some way?

**Comment by tanmc123** [comment]
@SaviorD7 I am not sure if standalone version of FATE is what you are wondering. It can simulate a FL modeling task in one client. However, the algorithm behind is still designed for FL which is not the same as casule ml model. You will still need to split data into two parts and upload each one. Then, start a model task like a normal FL task. 

If you prefer a pure casual ml model, other machine learning framework such as sklearn may be a better choice. We do have a component called "local_baseline" doing what Logistic Regression without FL. However, it is no more than a warpper of sklearn.
