### ISSUE TITLE
RandomizedIterativeAffine may break homomorphism in some conditions?

### ISSUE THREAD

**Issue by deadlywing** [FederatedAI/FATE#2815]
**Describe the bug**
Recently, I was studying the algorithms about homomorphism; I see the implementation of `RandomizedIterativeAffine`  in FATE,  and find it may occur some errors when two ciphers have different `mult_times` (parameter in `RandomizedIterativeAffineCiphertext` ) or if a cipher have too large `mult_times`(can see the examples).

**To Reproduce**

**Q1**
```python
# raw data
data = 10489.35254
data2 = 32523.454

# both randomized and deterministic share the same problem
key = IterativeAffineCipher.generate_keypair(randomized=True)

# encrypt the raw data
enc = key.encrypt(data)
enc2 = key.encrypt(data2)

# two cipher with different mult_times
dec = key.decrypt(34.565 * enc + enc2)

# homomorphism breaks
print(dec)                                          # 3041411245199.381
print(34.565 * data + data2)           # 395087.9245451

```
To compare, I add a scalar multiplication with data2, and give the following results:
```python
data = 10489.35254
data2 = 32523.454

# both randomized and deterministic share the same problem
key = IterativeAffineCipher.generate_keypair(randomized=True)

# encrypt the raw data
enc = key.encrypt(data)
enc2 = key.encrypt(data2)

# two cipher with same mult_times
dec = key.decrypt(34.565 * enc + 45.65 * enc2)

# homomorphism holds
print(dec)                                                      # 1847260.1442194579
print(34.565 * data + 45.65 * data2)         # 1847260.1456451002

```
---

**Q2**
```python
data = 10489.35254

# both randomized and deterministic share the same problem
key = IterativeAffineCipher.generate_keypair(randomized=True)

# encrypt the raw data
enc = key.encrypt(data)

# cipher with two many mult_times
dec = key.decrypt(enc * 3.43 * 32.1 * 4.65 * 3.4 * 438.325 * 3.435 * 3.3245)

# homomorphism breaks
print(dec)                                                 # 1.2086793377831546e+75
print(data * 3.43 * 32.1 * 4.65 * 3.4 * 438.325 * 3.435 * 3.3245)           # 91396386285.93674

```

**Desktop (please complete the following information):**
 - OS:  macOS, M1 chip
 - Version of FATE ：1.6

**Additional context**
In my opinion, the two questions may result from the following two parts:

**Q1**
I am confused about the logic of `__add__` method in `RandomizedIterativeAffineCiphertext`, But I can not find a paper about this algorithm, can anyone give me a detailed information about this ?
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/25818621/120280133-e203cb00-c2e9-11eb-8710-455afa64cffe.png">

---

**Q2**
`decode` method in `RandomizedIterativeAffineCipherKey`; If multiply a float multiple time,  decode function may get wrong outcome (not confirmed) ?
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/25818621/120280648-884fd080-c2ea-11eb-9fc0-f57879e36ea1.png">

---

**My try**
For Q1, My first thought is modify this as `fixpoint` do, and it work (although it has precision problem).
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/25818621/120287215-a4a33b80-c2f1-11eb-8071-0689d992a982.png">

```python
data = 10489.35254
data2 = 32523.454

key = IterativeAffineCipher.generate_keypair(randomized=True)
enc = key.encrypt(data)
enc2 = key.encrypt(data2)

dec = key.decrypt(enc2 * 12.456 * 3.987 + enc * 3.43 * 32.1 * 4.65 * 3.4)

print(dec)               # 19874295.729311418
print(data * 3.43 * 32.1 * 4.65 * 3.4 + data2 * 12.456 * 3.987)  #  19874296.292907402
```
But for Q2, I think it must change the encoding and decoding schema of float number, so it may change a huge amount of code.

**Comment by mgqa34** [comment]
We will fix the bug of Q1 in FATE-1.7.
