### ISSUE TITLE
FATE1.6.0出现mysql异常，导致fateboard无法查看任务流

### ISSUE THREAD

**Issue by dannis97500** [FederatedAI/FATE#2819]
**Describe the bug**
首先使用Kubefate安装集群，然后提交一个简单的upload命令，把系统自带breast数据集提交，然后查看日志出现mysql异常。导致fateboard没有任何信息。
直接拉取镜像部署会产生此问题，希望大佬给出有效解决方案！感激不尽

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/40295475/120471386-39cc3000-c3d7-11eb-8e14-d483d2892726.png)

![image](https://user-images.githubusercontent.com/40295475/120471471-54060e00-c3d7-11eb-8216-3e5e84c6a72f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tdye24** [comment]
Have you solved it?
