### ISSUE TITLE
No module named 'pipeline

### ISSUE THREAD

**Issue by wakawakaohoh** [FederatedAI/FATE#2820]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
/home/mingzhu/anaconda3/envs/py38/bin/python3.8 /home/mingzhu/ocr/Text-Opinion-Mining/FATE/examples/benchmark_quality/hetero_lr/pipeline-lr-binary.py
Traceback (most recent call last):
  File "/home/mingzhu/ocr/Text-Opinion-Mining/FATE/examples/benchmark_quality/hetero_lr/pipeline-lr-binary.py", line 19, in <module>
    from pipeline.backend.pipeline import PipeLine
ModuleNotFoundError: No module named 'pipeline'

**Comment by SaviorD7** [comment]
`pip install fate_client`
