### ISSUE TITLE
Get the results of training

### ISSUE THREAD

**Issue by qwertyuiop-s** [FederatedAI/FATE#2831]
Hello!

If I start FATE in cluster mode and run the training by host machine (for example, i have 1 main host machine and 2 clients), how I can get results of the training (accuracy, loss, etc) from 2 clients machine ? 
`pipeline` gives results only machine I have started.

Thank you.

**Comment by mgqa34** [comment]
In pipeline operation, only the party who submits the job can get the training result. It's  unsafe to query the result of others.
