### ISSUE TITLE
Homogeneous Neural Network

### ISSUE THREAD

**Issue by cchanzl** [FederatedAI/FATE#2834]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/homo_nn/pipeline_homo_nn_multi_layer.py
2. Update the neural network to be the following

def main(config="../../config.yaml", namespace=""):
    homo_nn_0 = HomoNN(name="homo_nn_0",
                       max_iter=epochs,
                       batch_size=batch_size)
    homo_nn_0.add(Dense(units=nodes_per_layer[0], input_shape=(12,), activation="relu"))
    homo_nn_0.add(Dropout(dropout))
    homo_nn_0.add(Dense(units=nodes_per_layer[1], activation="relu"))
    homo_nn_0.add(Dropout(dropout))
    homo_nn_0.add(Dense(units=nodes_per_layer[2], activation="relu"))
    homo_nn_0.add(Dropout(dropout))
    homo_nn_0.add(Dense(units=1, activation="relu"))
    homo_nn_0.compile(optimizer=optimizers.Adam(learning_rate=0.05),
                      metrics=["MeanSquaredError"],
                      loss="mean_squared_error")

**Expected behavior**
I expect the NN to output a single prediction of the target variable which is a continuous variable

**Errors**
ValueError: A target array with shape (16, 1) was passed for an output of shape (None, 151) while using as loss `mean_squared_error`. This loss expects targets to have the same shape as the output.

**Question**
How can I perform a regression prediction using neural network, instead of a categorical prediction shown in all 3 homo_nn examples?

Note that the error goes away if i change loss="mean_absolute_error" instead.

**Comment by mgqa34** [comment]
Homo Neural Network does not support regression task now, only supports classification task.

**Comment by cchanzl** [comment]
thanks for your reply! would be great if that can be made clearer in the documentation.
