### ISSUE TITLE
Homogeneous Logistic Regression using Gradient Aggregation not implemented?

### ISSUE THREAD

**Issue by xingzhis** [FederatedAI/FATE#2845]
Hi,
I was going through the code of homo-lr, and I wonder if the method described in the README is not implemented in the code.

**Mismatch between README and code?**
Described in https://github.com/FederatedAI/FATE/blob/7f81d654bf9ddbb1207bbd3c02e130f5ea54b1dc/python/federatedml/linear_model/logistic_regression/README.rst 
<img width="1227" alt="Screen Shot 2021-06-27 at 2 14 24 PM" src="https://user-images.githubusercontent.com/59325005/123535036-03729e00-d754-11eb-8a41-8505564df62a.png">
the homogeneous LR sends and aggregates **gradients** in each iteration. However, in the code, it is the **model weights** that are sent and aggregated:
https://github.com/FederatedAI/FATE/blob/7f81d654bf9ddbb1207bbd3c02e130f5ea54b1dc/python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py#L94-L95

and the gradient is computed and applied for weight update **within** each host
https://github.com/FederatedAI/FATE/blob/7f81d654bf9ddbb1207bbd3c02e130f5ea54b1dc/python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py#L117-L131

There seems to be a mismatch between the README and the code.  

**Describe the solution you'd like**
Is homo-lr using gradient aggregation not implemented or is the code elsewhere? Could you refer to the code if it is elsewhere?
If not implemented, could you explain if any difficulties were encountered that blocked the implementation? (e.g. encryption, numerical precision, etc.)?

**Describe alternatives you've considered**
I did an implementation to use the gradient aggregation described in the README.rst above (for simplicity I did not use encryption)
https://github.com/xingzhis/pretendFLR
It works well if precise gradients (of the cross-entropy loss) are used, but if Taylor expansion gradient is used (so that additively homomorphic encryption can be used), the numerical errors accumulate, resulting in a failure to learn the model correctly.

Thank you very much!

**Comment by tanmc123** [comment]
@xingzhis Sorry for misunderstanding you. We do aggregate the model_weights instead of gradient. The Readme will be fix in next version.

**Comment by xingzhis** [comment]
@tanmc123 Thank you very much!
