### ISSUE TITLE
Local Steps Settings.

### ISSUE THREAD

**Issue by SamuraiChamplooo** [FederatedAI/FATE#2855]
I can't find related parameters in conf.json
Where should I modify the configuration to see FL performance at different aggregation frequencies？？

**Comment by mgqa34** [comment]
May I ask which algorithm you want to use? 
If trainning homo_nn, please refer to https://github.com/FederatedAI/FATE/blob/master/python/federatedml/param/homo_nn_param.py#L62.
If trainning  homo_lr,  refer to https://github.com/FederatedAI/FATE/blob/master/python/federatedml/param/logistic_regression_param.py#L249

**Comment by SamuraiChamplooo** [comment]
Thank you for your reply~
