### ISSUE TITLE
Does homo_lr support ovr now? Will it support ?

### ISSUE THREAD

**Issue by SennriSyunnga** [FederatedAI/FATE#2860]
I am using FATE v.1.5.1
When i read the source code,
I found only hetero_lr have code to judge whether the data is multi_class,
What's more, homo_lr doesnt have any code about 'ovr' int 'predict' function indeed.
Does it have some reasons to do so?
will it support ovr in the future?

**Comment by tanmc123** [comment]
@SennriSyunnga It it not supported yet. This function is suspended since there was no requirement for it. However, we would consider supporting it in the future because of your proposal. Thanks.

**Comment by SennriSyunnga** [comment]
> @SennriSyunnga It it not supported yet. This function is suspended since there was no requirement for it. However, we would consider supporting it in the future because of your proposal. Thanks.

Get it.
Many thanks to you！
