### ISSUE TITLE
使用1.6.0 All in one Native部署FATE集群无法连接mysql

### ISSUE THREAD

**Issue by yumiaoGitHub** [FederatedAI/FATE#2863]
Fateflow服务无法启动，查看errorlog内容如下:
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on ‘my ip’ (timed out)")
peewee.OperationalError: (2003, "Can't connect to MySQL server on ‘my ip’ (timed out)")
已经重新卸载mysql 并重新部署安装，查看端口3306正常运行；也尝试过先停止所有服务，然后先开启mysql再开启fateflow
但是仍出现上述错误。感谢提供解决思路！
![image](https://user-images.githubusercontent.com/17609160/124847040-acc75880-dfcc-11eb-9beb-405f4d3da99b.png)

**Comment by wodeyoulai** [comment]
我也一样，尝试了很多方法也没解决

**Comment by SennriSyunnga** [comment]
看看本机上是否有已经装好的mysql，卸载；
看看本机上是否有已经在跑的mysqld 和 mysqld_safe进程
杀死。
