### ISSUE TITLE
"retmsg": "SQLError: no such table: t_engine_registry"

### ISSUE THREAD

**Issue by Li-Rongchang** [FederatedAI/FATE#2888]
root@0ae45110:~# python /FATE/python/fate_flow/fate_flow_client.py -f upload -c /FATE/examples/dsl/v1/upload_data.json
{
    "retcode": 100,
    "retmsg": "SQLError: no such table: t_storage_table_meta"
}

我用docker安装了FATE。当我利用fate_flow_client文件上传数据时，出现了这个错误。请问哪里出现了问题，谢谢。

**Comment by Oqaily** [comment]
Hi, [Li-Rongchang](https://github.com/Li-Rongchang)
 I have also encountered similar error. Did you find a solution to this issue?
