### ISSUE TITLE
FATEBoard need user and password ，FATEBoard 登录需要用户名密码？

### ISSUE THREAD

**Issue by wangyuqian1007** [FederatedAI/FATE#2942]
fate 1.5.2
![image](https://user-images.githubusercontent.com/67529426/127945437-a1d4a1de-cdf2-4adc-be6c-4c08c695b7a1.png)

**Comment by dylan-fan** [comment]
admin/admin

**Comment by dylan-fan** [comment]
in fate v1.5.2, you will use fateboard v1.5.3

**Comment by wangyuqian1007** [comment]
![image](https://user-images.githubusercontent.com/67529426/127946177-311e89f3-5670-4c4f-a56a-a25b7b185cec.png)
 Incorrect username or password

**Comment by wangyuqian1007** [comment]
how to use use fateboard v1.5.3

**Comment by mgqa34** [comment]
> how to use use fateboard v1.5.3

Make sure that the conf/application.properties is updated. 
It should have config like: 
    server.board.login.username=admin
    server.board.login.password=admin

**Comment by wood-j** [comment]
> ![image](https://user-images.githubusercontent.com/25281865/174215208-84db705b-9745-4fa0-b9fc-3cb5e2b8028e.png) ![image](https://user-images.githubusercontent.com/25281865/174215240-598380af-44ef-4cf7-941c-096a86672199.png) The application.propertis is configed admin/admin, but FATEBoard still cannot login. What is wrong?

Check the incorrect datetime between the server and local. It shoule be less than 1 minute diff from my test.
