### ISSUE TITLE
Fate on spark模式在执行data_io模块时，在日志中出现大量的print的数据信息，数据量过大情况下造成加载慢

### ISSUE THREAD

**Issue by zapjone** [FederatedAI/FATE#2946]
![image](https://user-images.githubusercontent.com/19503929/128336457-f9bfdad8-f0c9-4147-8da4-21a01a4e41cd.png)
在输出的日志中有很多这种features和header的数据输出，数据量过大时，加载日志会造成页面加载失败，从源码中搜索都没发现具体是那里打印输出的

**Comment by zapjone** [comment]
这种数据输出也没有任何意义啊

**Comment by dylan-fan** [comment]
你是哪个版本

**Comment by zapjone** [comment]
fate版本是1.6.0

**Comment by zhihuiwan** [comment]
此问题已经修复， 你可使用最近的版本再试试， 感谢您的反馈！
