### ISSUE TITLE
Poor Implementation of SPDZ protocol

### ISSUE THREAD

**Issue by a7853z** [FederatedAI/FATE#2955]
**Describe the bug**
The implementation of SPDZ protocol is incomplete, crucial features of the original protocol are truncated.
1. Not secure against active malicious adversary.
Without using information theoretic MACs or zero-knowledge proofs as the original protocol, active malicious adversary can cheat on their inputs and render incorrect results.  

2. Only support two parties.
The implementation uses Paillier encryption to produce beaver triplets which makes it limit to two parties while the original SPDZ has no party number limits. Should use somewhat FHE or leveled FHE like BGV, BFV to produce beaver triplets instead.

**Comment by weiwee** [comment]
Thanks report. 

>     1. Not secure against active malicious adversary.
>        Without using information theoretic MACs or zero-knowledge proofs as the original protocol, active malicious adversary can cheat on their inputs and render incorrect results.

The `secure against active malicious adversary` is not the goal we try to achieve in recent version, but pull requests are always welcome.

>     2. Only support two parties.
>        The implementation uses Paillier encryption to produce beaver triplets which makes it limit to two parties while the original SPDZ has no party number limits. Should use somewhat FHE or leveled FHE like BGV, BFV to produce beaver triplets instead.

Yes, we support two parties now becasue we meat some fixpoint-encoder issue, not becuase we use the `Paillier encryption` 
protocol. And we don't see the point of goodness to use somewhat FHE to genearete beaver triplets. Could you please provide any more detailed explanation？

**Comment by a7853z** [comment]
> somewhat



> Thanks report.
> 
> > ```
> > 1. Not secure against active malicious adversary.
> >    Without using information theoretic MACs or zero-knowledge proofs as the original protocol, active malicious adversary can cheat on their inputs and render incorrect results.
> > ```
> 
> The `secure against active malicious adversary` is not the goal we try to achieve in recent version, but pull requests are always welcome.
> 
> > ```
> > 2. Only support two parties.
> >    The implementation uses Paillier encryption to produce beaver triplets which makes it limit to two parties while the original SPDZ has no party number limits. Should use somewhat FHE or leveled FHE like BGV, BFV to produce beaver triplets instead.
> > ```
> 
> Yes, we support two parties now becasue we meat some fixpoint-encoder issue, not becuase we use the `Paillier encryption`
My mistake, if Paillier supports multiplication between ciphertext and you followed the SPDZ2's triplets generation protocol, fate's beaver_triplets doesn't have party number limitation.  Also, can you give me more details of this fixpoint-encoder issue? I am working on the two party limit issue.  And can we use Microsoft Seal's CKKS instead of Paillier to fix this issue? 
> protocol. And we don't see the point of goodness to use somewhat FHE to genearete beaver triplets. Could you please provide any more detailed explanation？
SPDZ2's paper do mention some benefits of using Leveled FHE BGV over Paillier at the last paragraphy of its Introduction section.

**Comment by a7853z** [comment]
> Thanks report.
> 
> > ```
> > 1. Not secure against active malicious adversary.
> >    Without using information theoretic MACs or zero-knowledge proofs as the original protocol, active malicious adversary can cheat on their inputs and render incorrect results.
> > ```
> 
> The `secure against active malicious adversary` is not the goal we try to achieve in recent version, but pull requests are always welcome.
> 
> > ```
> > 2. Only support two parties.
> >    The implementation uses Paillier encryption to produce beaver triplets which makes it limit to two parties while the original SPDZ has no party number limits. Should use somewhat FHE or leveled FHE like BGV, BFV to produce beaver triplets instead.
> > ```
> 
> Yes, we support two parties now becasue we meat some fixpoint-encoder issue, not becuase we use the `Paillier encryption`

**_> My mistake, if Paillier supports multiplication between ciphertext and constants, and you followed the SPDZ2's triplets generation protocol, fate's beaver_triplets doesn't have party number limitation. Also, can you give me more details of this fixpoint-encoder issue? I am working on the two party limit issue. And can we use Microsoft Seal's CKKS instead of Paillier to fix this issue?_**

> protocol. And we don't see the point of goodness to use somewhat FHE to genearete beaver triplets. Could you please provide any more detailed explanation？

**_> SPDZ2's` paper do mention some benefits of using Leveled FHE BGV over Paillier at the last paragraphy of its Introduction section._**

**_> One more thing to mention, SPDZ's unit test shows errors : module "fate_arch.session" has no attirbute "init"._**

**Comment by a7853z** [comment]
@weiwee 
**Good News**: The party number limit of SPDZ can be removed by using Microsoft Seal's CKKS as well as all the redundant fixpoint encoding and decoding code.   I tested the modified SPDZ in hetero_pearson with three parties:1 Guest, 2 Hosts, and the data I used is breast_hetero_guest and breast_hetero_host. 
Here is the first corr row:

>  [0.9739451840944395 0.42625413530776457 0.9755094378288185
>  0.9697823086090491 0.05205141649569391 0.561382889899243
>  0.7069897199142066 0.7481190687094059 -0.19798667287048125
>  -0.5964790654824891 0.4159688144789205 -0.08748228172470007
>  0.38501085106115696 0.758014080265595 -0.44258157229279843
>  -0.014301103237581181 0.13761181368069303 0.43303178978547496
>  -0.5738301629347646 -0.388682601417217]

And the first corr row using original  SPDZ:

> [0.97387 0.42623 0.97545 0.96972 0.052039999999999996 0.56136
>  0.7069300000000001 0.74806 -0.19799 -0.59645 0.41595000000000004 -0.08748
>  0.38499 0.75797 -0.44254 -0.014299999999999998 0.13759 0.433
>  -0.5738000000000001 -0.38864]

We can see the results are pretty close.  

**Bad News** :   The ciphertext is too large(nearly 1.9GB) for the tested table(Using CKKS.tensor for encryption). It caused memory error when I tried to remote. To pass the test, I cut breast_hetero_guest to 10 rows.  

Nary a douobt. This large ciphertext size issue will limit its applications. Have to work on that latter.    Close this issue first.
