### ISSUE TITLE
pytorch mnist_demo一直处于标签对齐状态

### ISSUE THREAD

**Issue by YYangyuan** [FederatedAI/FATE#2964]
运行官方的homo_nn/mnist_demo，提示“start homo label alignments”之后，不再有新的进展，程序一直运行，但不报错。
[INFO] [2021-08-12 02:47:27,404] [622:139817909348160] - homo_label_encoder.py[line:14]: start homo label alignments

**Comment by dododo778** [comment]
我也遇到了一样的问题，请问你现在解决了吗

**Comment by dododo778** [comment]
> 运行官方的homo_nn/mnist_demo，提示“start homo label alignments”之后，不再有新的进展，程序一直运行，但不报错。 [INFO] [2021-08-12 02:47:27,404] [622:139817909348160] - homo_label_encoder.py[line:14]: start homo label alignments

我也遇到了一样的问题，请问你现在解决了吗

**Comment by YYangyuan** [comment]
这个是pytorch_lightning版本的问题，可能自己升级过它，按照官方默认的版本就可以了。或者是使用python_nn这个镜像（在部署的时候提前配置好）



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dododo778 ***@***.***&gt;
发送时间: 2022年1月6日 16:27
收件人: FederatedAI/FATE ***@***.***&gt;
抄送: YYangyuan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[FederatedAI/FATE] pytorch mnist_demo一直处于标签对齐状态 (#2964)





 
我也遇到了一样的问题，请问你现在解决了吗

**Comment by dododo778** [comment]
> 这个是pytorch_lightning版本的问题，可能自己升级过它，按照官方默认的版本就可以了。或者是使用python_nn这个镜像（在部署的时候提前配置好） 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: dododo778 ***@***.***&gt; 发送时间: 2022年1月6日 16:27 收件人: FederatedAI/FATE ***@***.***&gt; 抄送: YYangyuan ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[FederatedAI/FATE] pytorch mnist_demo一直处于标签对齐状态 (#2964) 我也遇到了一样的问题，请问你现在解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

确实是。已经解决了！非常感谢！

**Comment by dxy0202** [comment]
> 这个是pytorch_lightning的问题，可能自己过了它，可能按照官方默认的升级就了。或者是使用python_nn这个镜像（在部署的时候可以提前配置版本好）iPhone的
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: dododo778 ***@***.***&gt; 发送时间: 2022年1月6日 16:27 收件人: FederatedAI/FATE ***@***.***&gt; 抄送: YYangyuan ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[FederatedAI/FATE] pytorch mnist_demo一直处于标签对齐状态 (#2964) 我也遇到了一样的问题，请问你现在解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我也遇到了同样的问题，我是完全按照官方文档进行部署的。请问有什么解决办法嘛？

**Comment by dododo778** [comment]
> > 这个是pytorch_lightning的问题，可能自己过了它，可能按照官方默认的升级就了。或者是使用python_nn这个镜像（在部署的时候可以提前配置版本好）iPhone的
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: dododo778 _**@**_._**> 发送时间: 2022年1月6日 16:27 收件人: FederatedAI/FATE _**@**_.**_> 抄送: YYangyuan _**@**_._**>, Author _**@**_.**_> 主题: 回复：[FederatedAI/FATE] pytorch mnist_demo一直处于标签对齐状态 (#2964) 我也遇到了一样的问题，请问你现在解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 我也遇到了同样的问题，我是完全按照官方文档进行部署的。请问有什么解决办法嘛？

部署的时候要配置pytorch_nn，就是在docker-deploy这个文件里，enabled_nn设为true
