### ISSUE TITLE
Executor exits during the training of FATE on Spark

### ISSUE THREAD

**Issue by jiahaoc1993** [FederatedAI/FATE#2965]
**Describe the bug**
Currently, in FATE on Spark, we observe that the executor will exit by uncaught exceptions. Although the driver will pull another executor up, and the executor will reconstruct the missing `RDD` by fetching data from the message queue. But due to the data was acknowledged, it is no able to be fetched again. And eventually, cause the task hangs on the receiving message from the message queue.

According to our investigation, two types of API sets that will cause the "EXITED" status of Spark executor:
1. federation(python/fate_arch/federation/pulsar/_federation.py)
2. computing(python/fate_arch/computing/spark/_table.py)

The federation error is fixed by this [PR](https://github.com/FederatedAI/FATE/pull/2962), it handles errors within the map-reduce operator to avoid executor exit.

However, I meet strange errors when I try to fix the computing error by adding `try catch` decorator to core map-reduce functions like map, mapValues.

**To Reproduce**
1.  define a try catch decorator
```
def handle_exceptions(f):
    @wraps(f)
    def wrapper(self, *args, **kargs):
        try:
            f(self, *args, **kargs)
        except Exception as e:
            LOGGER.error(e)
    return wrapper
```
2. add the decorator to FATE's spark computing table
add decorator to following function:
- map
- take
- mapValues
...
```
@computing_profile
@handle_exceptions
def map(self, func, **kwargs):
   return from_rdd(_map(self._rdd, func))
...
```
3. start FATE and run min_test example

The result is dataIo model was failed to finish, follow is the critical log:
```
[INFO] [2021-08-12 02:46:08,349] [12929:140439838705472] - task_executor.py[line:301]: load computing table use 2
7
[WARNING] [2021-08-12 02:46:25,743] [12929:140439838705472] - data_io.py[line:855]: DataIO is deprecated, and will be removed in 1.7, use DataTransform module instead
8
[INFO] [2021-08-12 02:46:25,880] [12929:140439838705472] - data_io.py[line:118]: start to read dense data and change data to instance
9
[ERROR] [2021-08-12 02:46:27,507] [12929:140439838705472] - task_executor.py[line:179]: 'NoneType' object has no attribute 'schema'
10
Traceback (most recent call last):
11
  File "./fate/python/fate_flow/operation/task_executor.py", line 154, in run_task
12
    run_object.run(component_parameters_on_party, task_run_args)
13
  File "./fate/python/federatedml/model_base.py", line 98, in run
14
    this_data_output = func(*real_param)
15
  File "./fate/python/federatedml/util/data_io.py", line 886, in fit
16
    data_inst = self.reader.read_data(data_inst, "fit")
17
  File "./fate/python/federatedml/util/data_io.py", line 146, in read_data
18
    data_instance = self.fit(input_data, input_data_features, input_data_labels)
19
  File "./fate/python/federatedml/util/data_io.py", line 156, in fit
20
    set_schema(input_data_features, schema)
21
  File "./fate/python/federatedml/util/data_io.py", line 918, in set_schema
22
    data_instance.schema = schema
23
```

**Expected behavior**
Pass the example normally, and record all exceptions to the logger.

**Comment by dylan-fan** [comment]
Missing return !

def handle_exceptions(f):
    @wraps(f)
    def wrapper(self, *args, **kargs):
        try:
            return f(self, *args, **kargs)
        except Exception as e:
            LOGGER.error(e)
            return None
    return wrapper

**Comment by weiwee** [comment]
> **Describe the bug** Currently, in FATE on Spark, we observe that the executor will exit by uncaught exceptions. Although the driver will pull another executor up, and the executor will reconstruct the missing `RDD` by fetching data from the message queue. But due to the data was acknowledged, it is no able to be fetched again. And eventually, cause the task hangs on the receiving message from the message queue.
> 
> According to our investigation, two types of API sets that will cause the "EXITED" status of Spark executor:
> 
>     1. federation(python/fate_arch/federation/pulsar/_federation.py)
> 
>     2. computing(python/fate_arch/computing/spark/_table.py)
> 
> 
> The federation error is fixed by this [PR](https://github.com/FederatedAI/FATE/pull/2962), it handles errors within the map-reduce operator to avoid executor exit.
> 
> However, I meet strange errors when I try to fix the computing error by adding `try catch` decorator to core map-reduce functions like map, mapValues.
> 
> **To Reproduce**
> 
>     1. define a try catch decorator
> 
> 
> ```
> def handle_exceptions(f):
>     @wraps(f)
>     def wrapper(self, *args, **kargs):
>         try:
>             f(self, *args, **kargs)
>         except Exception as e:
>             LOGGER.error(e)
>     return wrapper
> ```
> 
>     1. add the decorator to FATE's spark computing table
>        add decorator to following function:
> 
> 
>     * map
> 
>     * take
> 
>     * mapValues
>       ...
> 
> 
> ```
> @computing_profile
> @handle_exceptions
> def map(self, func, **kwargs):
>    return from_rdd(_map(self._rdd, func))
> ...
> ```
> 
>     1. start FATE and run min_test example
> 
> 
> The result is dataIo model was failed to finish, follow is the critical log:
> 
> ```
> [INFO] [2021-08-12 02:46:08,349] [12929:140439838705472] - task_executor.py[line:301]: load computing table use 2
> 7
> [WARNING] [2021-08-12 02:46:25,743] [12929:140439838705472] - data_io.py[line:855]: DataIO is deprecated, and will be removed in 1.7, use DataTransform module instead
> 8
> [INFO] [2021-08-12 02:46:25,880] [12929:140439838705472] - data_io.py[line:118]: start to read dense data and change data to instance
> 9
> [ERROR] [2021-08-12 02:46:27,507] [12929:140439838705472] - task_executor.py[line:179]: 'NoneType' object has no attribute 'schema'
> 10
> Traceback (most recent call last):
> 11
>   File "./fate/python/fate_flow/operation/task_executor.py", line 154, in run_task
> 12
>     run_object.run(component_parameters_on_party, task_run_args)
> 13
>   File "./fate/python/federatedml/model_base.py", line 98, in run
> 14
>     this_data_output = func(*real_param)
> 15
>   File "./fate/python/federatedml/util/data_io.py", line 886, in fit
> 16
>     data_inst = self.reader.read_data(data_inst, "fit")
> 17
>   File "./fate/python/federatedml/util/data_io.py", line 146, in read_data
> 18
>     data_instance = self.fit(input_data, input_data_features, input_data_labels)
> 19
>   File "./fate/python/federatedml/util/data_io.py", line 156, in fit
> 20
>     set_schema(input_data_features, schema)
> 21
>   File "./fate/python/federatedml/util/data_io.py", line 918, in set_schema
> 22
>     data_instance.schema = schema
> 23
> ```
> 
> **Expected behavior** Pass the example normally, and record all exceptions to the logger.

The behavior exsits because the wrapper`handle_exceptions` returns nothing and could be fixed as described by https://github.com/FederatedAI/FATE/issues/2965#issuecomment-962847404

By the way, I don't think it's good idea to add try-catch  blocks to `mapValues` or `map` apis since it expected to returns an new `table`. 

I think it's better idea to logger exception and re-throw it:

```python
def handle_exceptions(f):
    @wraps(f)
    def wrapper(self, *args, **kargs):
        try:
            return f(self, *args, **kargs)
        except Exception as e:
            LOGGER.error(e)
            raise e
    return wrapper
```

**Comment by jiahaoc1993** [comment]
Tanks for the comments, and sure, I would like to submit a PR to address the this issue.
