### ISSUE TITLE
"predict_score" for logistic regression test on Fate Board wrong in magnitude

### ISSUE THREAD

**Issue by Alexanderia-Mike** [FederatedAI/FATE#2977]
**Describe the bug**
In fateboard, the "predict_score" for logistic regression test will sometimes be larger than 1. For example, look at the following screenshot:
![Screen Shot 2021-08-17 at 4 31 29 PM](https://user-images.githubusercontent.com/62225631/129692241-01f66ac4-7466-44af-a86d-fca5cde86178.png)
and after a deeper insight, I find that it's actually missing a magnitude specification. For example, the value 2.719735 is actually 2.719735...e-12. But somehow the magnitude "e-12" is missing, which really confuses users.
![Screen Shot 2021-08-17 at 4 34 03 PM](https://user-images.githubusercontent.com/62225631/129692652-d23ae2a5-4f4d-4cc8-8147-07995c6722c4.png)

**Comment by mgqa34** [comment]
We will fix this issue in FATE-Board V1.6.1，thanks for your carefulness.
