### ISSUE TITLE
Any detail about split_calculation option?

### ISSUE THREAD

**Issue by X1anWang** [FederatedAI/FATE#3075]
Hi, in [Intersection Part](https://github.com/FederatedAI/FATE/tree/178f04d1a58181359d6550b4673d4b4dc72a778f/python/federatedml/statistic/intersect), it briefly describes a more efficient split_calculation option.

I request a more detailed explaination or support material on this split_calculation intersection operation design.

Thank you very much.

**Comment by a7853z** [comment]
I briefly took a look at the code:
Looks like the guest split its ids into two sets: odd ids and even ids.

- For odd ids, it's the same as the multi-host case illustrated in multi_host.png.

- For even ids, guest and hosts does the same as the multi-host case. But they do it reversely for key generation and intermediate results computation. For example, guest will generate the rsa pk/sk key pairs.  The only difference is guest is still the one to compute the final intersection.    

In the end, the guest will combine the intersection results for odd ids and even ids.

**Comment by a7853z** [comment]
But be careful when you using multi-host PSI, guest learns more than he should know.
