### ISSUE TITLE
在线推理支持横向联邦模型

### ISSUE THREAD

**Issue by turkeymz** [FederatedAI/FATE#3090]
**Is your feature request related to a problem? Please describe.**
在fate在线预测中，我发现不支持横向联邦。这导致整个在线预测适用模型非常少。

**Describe the solution you'd like**
希望fate-serving能推出在线预测功能。或者告知是否有这个计划？如果没有，可能会想办法二开

**Describe alternatives you've considered**
暂时想法会在训练完成时。把另外的把模型实例化成一个pkl文件，然后部署会提供这个pkl进行在线预测

**Additional context**
暂无深入调研，若fate短期不支持，而需求必须做的时候。考虑进行进入调研且二开适配

**Comment by dylan-fan** [comment]
目前暂无计划在fate-serving中支持横向联邦，在1.7版本后，支持横向模型倒出标准格式，用户可以用业界通用的在线服务来加载模型

**Comment by liuyanfeng1981** [comment]
你好，横向模型倒出标准格式是否已经支持，如果支持了是怎么使用的？我看示例中的export接口已之前好像没有什么区别，谢谢

**Comment by liuyanfeng1981** [comment]
你好，横向模型倒出标准格式是否已经支持，如果支持了是怎么使用的？我看export接口与之前好像没有什么区别，谢谢
