### ISSUE TITLE
how to disable paillier encrypt during training

### ISSUE THREAD

**Issue by majorinche** [FederatedAI/FATE#3131]
"encrypt_param": {"method": "Paillier", "key_length": 2048},

try to disable encrypt by setting: "encrypt_param": {"method": "", "key_length": 2048},
report error:
Component hetero_lr_0, module HeteroLR, does not pass component check, error msg is encrypt_param's method  not supported

so is it possible to disable encrypt?

thank you

**Comment by tanmc123** [comment]
No, it is not supported in hetero-lr
