### ISSUE TITLE
No module named 'fate_arch'

### ISSUE THREAD

**Issue by troublesuffer** [FederatedAI/FATE#3133]
![image](https://user-images.githubusercontent.com/91310466/134634007-fda069ca-06db-4389-af7b-79a2cf8664a4.png)
主机单机部署fate_1.6.0：
 使用 python ${fate}/fate_flow/fate_flow_client.py -f submit_job -d xxx_dsl.json -c xxx_conf.json命令提交任务时，报错No module named 'fate_arch'
![image](https://user-images.githubusercontent.com/91310466/134634528-fe65612b-4304-4629-bd7a-b2c5350d2274.png)
PYTHONPATH为fate_flow所在目录的上级目录
fate_arch目录存在且并未进行任何修改
![image](https://user-images.githubusercontent.com/91310466/134634719-0cf538c8-b550-4e90-a994-952acc4c3b28.png)
请问是哪里可能出现了问题？怎么修改

**Comment by mgqa34** [comment]
source bin/init_env.sh first may help.
