### ISSUE TITLE
fateboard显示为空白

### ISSUE THREAD

**Issue by troublesuffer** [FederatedAI/FATE#3134]
主机单机部署fate1.6.0：
 使用flow job submit -c xxx_conf.json -d xxx_dsl.json命令成功提交任务后，board_url提供的可视化界面显示为白板，历史任务里也没有该任务的记录
![image](https://user-images.githubusercontent.com/91310466/134635181-b510193b-a7cf-45a6-908e-18dba753139a.png)
![image](https://user-images.githubusercontent.com/91310466/134635217-d63ca398-02a9-4568-9d99-61d156eaba9c.png)
请问该如何解决？

**Comment by dylan-fan** [comment]
please check fate or fate-flow address in FATE-Board
