### ISSUE TITLE
HDFS存储引擎数据量大于10000条时Reader组件复制表失败

### ISSUE THREAD

**Issue by fankp** [FederatedAI/FATE#3139]
版本：
Fate1.6.0

问题现象：
fate_flow/components/reader.py 中定义了MAX_NUM=10000，每次写入10000条分批写入hdfs，数据量大于1w条时只有第一次写入成功，后续条目写入报Hdfs异常

**Comment by zhihuiwan** [comment]
可以使用最新版本试试
