### ISSUE TITLE
Does Fate Flow support login? / Fate Flow支持登录吗？

### ISSUE THREAD

**Issue by jhdxr** [FederatedAI/FATE#3143]
I get an error message saying I have to login first when I try some examples provided (e.g. `flow job submit -c homo_lr_train_eval_conf.json -d homo_lr_train_eval_dsl.json`):
```
{
    "code": 10015,
    "msg": "Please login first!"
}
```

I try to search for related issue/wiki but unfortunately I didn't find anything useful. According to the commit (FederatedAI/FATE-Board@e6b3456280831bb717c7d61964a271385882a998), it seems to be introduced in 1.5.x which is half year ago already. so I'm wondering if the fate flow doesn't support login (then it breaks everything) indeed, or there is something wrong with my configuration?

--- 

我在尝试example中的例子时（例如`flow job submit -c homo_lr_train_eval_conf.json -d homo_lr_train_eval_dsl.json`）报错提示未登录：
```
{
    "code": 10015,
    "msg": "Please login first!"
}
```
翻了下没有找到相关的issue/wiki说明这个，似乎是1.5.x引入的校验 (FederatedAI/FATE-Board@e6b3456280831bb717c7d61964a271385882a998)，目前flow是还没有实现相关的支持吗？

**Comment by canfuu** [comment]
> I found what went wrong. The English document is not clear enough. The fate client should be installed in the container and linked with fate flow server (default port 9380). Port 8080 is running fate board which has nothing to do with fate flow.
> 
> I think #3123 is caused by same issue.
> 
> For people who are also looking for a solution, besides running flow in the container, an alternative solution is to expose container's 9380 to outside (e.g. `-p 9380:9380`) so you can run flow in the host.

一开始我也是这么想的，但是我打开了9380端口之后，依旧无法使用，最新版本的fate把原来的客户端与flow合并了，并没有9380端口在容器内部启动
