### ISSUE TITLE
最后提交测试的时候报500 Internal Server Error

### ISSUE THREAD

**Issue by Hiramdu** [FederatedAI/FATE#3196]
请教：
当运行最后测试环节的时候python fate_flow/fate_flow_client.py -f submit_job -c standalone-fate-master-1.5.0/examples/dsl/v1/hetero_logistic_regression/test_predict_conf.json，提示报错：
{
    "retcode": 100,
    "retmsg": "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
}
我是在公司的server上跑的，不知道该如何解决，谢谢大家！

**Comment by mgqa34** [comment]
Please make sure that the Flask's version is 1.0.2, pip list | grep Flask.
