### ISSUE TITLE
load 模型，但是模型fate-serving上看到的模型不完整

### ISSUE THREAD

**Issue by david-zhouyu** [FederatedAI/FATE#3237]
我在fate中训练/data/projects/fate/examples/dsl/v2/hetero_nn，操作如下：
1、flow job submit -d  test_hetero_nn_dsl.json -c  test_hetero_nn_binary_conf.json
2、flow model deploy --model-id guest-9999#host-10000#model --model-version 202110260516394222190
3、flow model -c publis.json
{
    "initiator": {
        "party_id": "9999",
        "role": "guest"
    },
    "role": {
        "guest": ["9999"],
        "host": ["10000"]
    },
    "job_parameters": {
        "work_mode": 1,
        "model_id": "guest-9999#host-10000#model",
        "model_version": "202110260558379067340"
    }
}
3、从fate serving上查看model时，只有dataIO，其他的组件都没有？
这是为什么？

**Comment by jmj2633500154** [comment]
flow model load -c fateflow/examples/model/publish_load_model.json
{
    "data": {
        "detail": {
            "guest": {
                "9999": {
                    "retcode": 100,
                    "retmsg": "<_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1704163647.256664044\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3217,\"referenced_errors\":[{\"created\":\"@1704163647.256661624\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":165,\"grpc_status\":14}]}\"\n>"
                }
            },
            "host": {
                "10000": {
                    "retcode": 100,
                    "retmsg": "<_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1704163647.290205261\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3217,\"referenced_errors\":[{\"created\":\"@1704163647.290197412\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":165,\"grpc_status\":14}]}\"\n>"
                }
            }
        },
        "guest": {
            "9999": 100
        },
        "host": {
            "10000": 100
        }
    },
    "jobId": "202401021047272331530",
    "retcode": 101,
    "retmsg": "failed"
}
加载模型报错是什么原因？
