### ISSUE TITLE
Insecure parameters for paillier

### ISSUE THREAD

**Issue by vincehong** [FederatedAI/FATE#3246]
https://github.com/FederatedAI/FATE/blob/master/python/federatedml/secureprotol/fate_paillier.py#L30

According to [NIST's Recommendation for
Key Management](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf) , 1024 bit of n only reaches <= 80 bit security, which is no longer considered sufficiently secure.

**Comment by dylan-fan** [comment]
thanks for your advice
