### ISSUE TITLE
任务失败，fate board不显示报错信息

### ISSUE THREAD

**Issue by ydnnh2008** [FederatedAI/FATE#3284]
![image](https://user-images.githubusercontent.com/47730754/140473049-3268b3f5-780d-40f4-958a-f331e3484018.png)
![image](https://user-images.githubusercontent.com/47730754/140473087-4becabb6-fa40-4f48-89b6-53ffa65ee469.png)

![image](https://user-images.githubusercontent.com/47730754/140473171-35e5207b-db78-48bb-872d-80d780fd3ec5.png)

跑的是官方例子pipeline-hetero-sbt-binary-with-missing-value.py做的修改，跑自己的数据，就几十条。但不知道为啥，任务失败，但是fate board不显示报错信息，这样子没法排查

**Comment by mgqa34** [comment]
May be the error is in host,  give more information  of figure 2. Click the tag "Schedule Log".

**Comment by ydnnh2008** [comment]
you are right,the error  is in guest,not in host.
