### ISSUE TITLE
如何删除job？

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3301]
进行测试的时候，产生了大量的job，占据存储空间。请问如何删除这些job？

**Comment by gm100861** [comment]
这些都是存在磁盘上的文件，删除对应文件即可。如果需要同事删除board上显示的job则需要自己写代码实现删除t_job和t_task表中对应的记录。磁盘文件主要存在logs/{job_id}   jobs/{job_id}  data/output_{job_id}
