### ISSUE TITLE
[HomoLR]Why Fate add RandomPads to Paillier Encrypted Model directly without Encrypting RandomPads?

### ISSUE THREAD

**Issue by SennriSyunnga** [FederatedAI/FATE#3308]
Let us use a binary situation as an example,
RandomPadsCypher will add randA to Model A, add randB to Model b, 
where randA plus randB equals zero. (indeed i know its not safe to use secure aggregator in binary situation, just for example)

if we call pallier function P(x)
as far as i know, P(modelA) + P(randA) = P(modelB)+P(randB)
while P(modelA) + randA != P(modelB)+randB
But in Fate, it seems like randomPads will add to Paillier encrypted model directly,
and i couldnt find the part of code to encrypt those random pads
Did i miss somthing? 
Or there is 'P(0）=0' in pallier algorithm？

**Comment by weiwee** [comment]
1. if model $X$ is encrypted using `Pallier`, $X + a$ means $X + encrypt(a)$, which is implemented using python's magic method  `__add__`
2. if model is plain, adding random padding is sufficent to cover the original infomation, which is what `SecureAggregation` do.

**Comment by SennriSyunnga** [comment]
> 1. if model $X$ is encrypted using `Pallier`, $X + a$ means $X + encrypt(a)$, which is implemented using python's magic method  `__add__`
> 2. if model is plain, adding random padding is sufficent to cover the original infomation, which is what `SecureAggregation` do.

Thanks a lot, I read __add_scalar function before, but didnt notice that there is other more important code in __add_fixpointnumber,
```python
    def __add_fixpointnumber(self, encoded):
        """return PaillierEncryptedNumber: z = E(x) + FixedPointNumber(y)
        """
        if self.public_key.n != encoded.n:
            raise ValueError("Attempted to add numbers encoded against different public keys!")

        # their exponents must match, and align.
        x, y = self.__align_exponent(self, encoded)

        encrypted_scalar = x.public_key.raw_encrypt(y.encoding, 1)
        encryptednumber = self.__raw_add(x.ciphertext(False), encrypted_scalar, x.exponent)

        return encryptednumber
```
`return PaillierEncryptedNumber: z = E(x) + y`
This annotion misslead me.
maybe it should be replaced with `return PaillierEncryptedNumber: z = E(x) + E(scalar)`?
