### ISSUE TITLE
how can I get the output of predict by python API?

### ISSUE THREAD

**Issue by ydnnh2008** [FederatedAI/FATE#3330]
how can I get the output of predict by python API?

I run the predict code as below:
...
    # run predict model
    rr = predict_pipeline.predict(JobParameters(backend=Backend.EGGROLL, work_mode=WorkMode.CLUSTER))
...

it works,but I don't know where can I get the output of predict by python API

**Comment by nemirorox** [comment]
Please refer this document for getting component output: 
https://github.com/FederatedAI/FATE/tree/master/python/fate_client/pipeline/component#task-info

Code for extracting prediction data output would likely look like this: 
`predict_pipeline.get_component("model_component_0").get_output_data()`

**Comment by ydnnh2008** [comment]
> Please refer this document for getting component output: https://github.com/FederatedAI/FATE/tree/master/python/fate_client/pipeline/component#task-info
> 
> Code for extracting prediction data output would likely look like this: `predict_pipeline.get_component("model_component_0").get_output_data()`

![image](https://user-images.githubusercontent.com/47730754/141068669-181ec8d0-9ea0-4c40-ae2a-12bec2e14542.png)

I can't get component 'hetero_ftl_0'，and the code report error info in here:
'''
model_output = predict_pipeline.get_component("hetero_ftl_0").get_output_data()
'''
