### ISSUE TITLE
bug in Confusion Matrix?

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3424]
**Describe the bug**
fate 1.6.0 版本中，evaluation模块中，Confusion Matrix 计算结果与data下载结果不一致。例如 dsl/v2/homo_lr/train中的例子

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by talkingwallace** [comment]
好的我这边跟进一下

**Comment by talkingwallace** [comment]
请问你使用的是这个命令吗
![企业微信截图_16375796591808](https://user-images.githubusercontent.com/10768970/142852302-6f0ed0d4-6e95-4b11-aa1b-b601cb792852.png)
我这边获得的结果和前端拿到的应该是一样的， 不知道你指的不一致是在哪里
![企业微信截图_16375796279477](https://user-images.githubusercontent.com/10768970/142851852-e975a1cb-a6cf-4b33-9fd7-fd289a816af3.png)

**Comment by gxcuit** [comment]
> 

你好！
我fate 版本是1.6.0，相关配置文件是：`/examples/dsl/v2/homo_logistic_regression/homo_lr_train_conf.json 以及homo_lr_train_dsl.json` 

我在fate-board中查看eval模块，发现confusion matrix 如图所示，TN为70
![image](https://user-images.githubusercontent.com/18736196/142985960-bba0982d-a1fd-4e73-8ab2-10f790e51cc8.png)

但是我下载homo-lr-0 的output csv文件，显示TN的数量为68，如下图所示
![image](https://user-images.githubusercontent.com/18736196/142986066-b4d4a20e-2946-4d2b-8bb8-63eb3fd1b4ba.png)

**Comment by talkingwallace** [comment]
好 我这里看下

**Comment by talkingwallace** [comment]
这边确实是发现有不一致的情况，主要是因为，现在后端计算时threshold采用的是实际的预测值，而前端在选取threshold的时候，会从实际的预测值列表里选择最接近的threshold，然后再展示对应的结果。比方说，这里是0.5，然后样本实际预测值里0.478最靠近，所以实际展示的结果是0.478作为threshold的，因此造成了不一致。
十分感谢反馈，我们会改进这个问题

**Comment by gxcuit** [comment]
> 这边确实是发现有不一致的情况，主要是因为，现在后端计算时threshold采用的是实际的预测值，而前端在选取threshold的时候，会从实际的预测值列表里选择最接近的threshold，然后再展示对应的结果。比方说，这里是0.5，然后样本实际预测值里0.478最靠近，所以实际展示的结果是0.478作为threshold的，因此造成了不一致。 十分感谢反馈，我们会改进这个问题

Ok,我理解的你的意思是，“下载下来的csv是准确的，而前端展现的是0.478作为threshold的”，是这个意思吗？

**Comment by gxcuit** [comment]
> 这边确实是发现有不一致的情况，主要是因为，现在后端计算时threshold采用的是实际的预测值，而前端在选取threshold的时候，会从实际的预测值列表里选择最接近的threshold，然后再展示对应的结果。比方说，这里是0.5，然后样本实际预测值里0.478最靠近，所以实际展示的结果是0.478作为threshold的，因此造成了不一致。 十分感谢反馈，我们会改进这个问题

BTW,正常情况下，差别不是很大。但当训练效果不理想的时候，数据的差距会比较大~
