### ISSUE TITLE
Secureboost bug

### ISSUE THREAD

**Issue by Hiramdu** [FederatedAI/FATE#3434]
I submit test_secureboost_train_dsl.json and test_secureboost_train_binary_conf.json in the demo, but it has an error:
<img width="255" alt="Screen Shot 2021-11-20 at 4 42 42 PM" src="https://user-images.githubusercontent.com/19141771/142741738-44806b48-b5cc-4869-b091-7dd335874983.png">
<img width="1047" alt="Screen Shot 2021-11-20 at 4 43 15 PM" src="https://user-images.githubusercontent.com/19141771/142741739-c1b122aa-1658-4a43-944c-c4b3de53399b.png">

**Comment by dylan-fan** [comment]
data_io_1 has not data?

**Comment by dylan-fan** [comment]
pipeline or dsl/v2 will be recommended.  dsl/v1 will be remove

**Comment by Hiramdu** [comment]
> pipeline or dsl/v2 will be recommended. dsl/v1 will be remove

I use dsl/v2, and it has another error. May you have a look?
<img width="1646" alt="Screen Shot 2021-11-22 at 7 53 17 PM" src="https://user-images.githubusercontent.com/19141771/142956405-024b1abf-9b7c-4006-9ce0-3098384f5953.png">
