### ISSUE TITLE
request for supporting re-run job/component

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3457]
**Is your feature request related to a problem? Please describe.**
当我修改job的参数的时候，我想重新运行这个job，或者重新运行具体的component。目前的版本（1.6.0），我只能重新提交一个job，这将生成新的job，以及对应job-id。对开发者来说，维护海量job不是很友好。

**Describe the solution you'd like**
可以重新运行job，或job里具体的某一个组件。在fate-board中，不生成新的job-id、

**Describe alternatives you've considered**
目前我的方法是，手动调用task_executor.py，并指定参数

**Additional context**

**Comment by gm100861** [comment]
这个可以自己写代码实现， 1.7里面好像已经支持了，但是不支持修改组件后自动创建组件及其下游组件的新版本，这个功能我实现了。需要修改他们源代码

**Comment by gxcuit** [comment]
> 这个可以自己写代码实现， 1.7里面好像已经支持了，但是不支持修改组件后自动创建组件及其下游组件的新版本，这个功能我实现了。需要修改他们源代码

1.7 里如何重新运行component？ 1.6 之前的版本可以直接 调用 `task_executor` ， 1.7 之后不行了
