### ISSUE TITLE
"retmsg": "'job_parameters'"

### ISSUE THREAD

**Issue by Hiramdu** [FederatedAI/FATE#3465]
I am running homo secureboost Binary-Class demo, but it has an error:
<img width="1646" alt="Screen Shot 2021-11-23 at 11 14 09 AM" src="https://user-images.githubusercontent.com/19141771/143061624-918358f2-94ee-4361-9069-db3b6924dffa.png">
I didn't meet this error in Cross Validation Class Binary-Class demo in the same dataset.

**Comment by SennriSyunnga** [comment]
Did you change the conf file content? Can you show us the file content?
Maybe you can just install flow client with the command `pip install fate-client==1.5.1`(replace the version with your real fate version)
and then use another way to run this job like:
`flow job submit -c xxxx.json -d xxx.json`, 
What's more, you can search the retmsg in this repository to find what cause this problem
