### ISSUE TITLE
Feature Request: operator overloading in class Weights?

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3475]
**Describe the bug**
Weights 中的加法、乘法 运算符重载，是否应该支持反向方法（reflected (swapped) operands）？

比如，我想计算 `2*LinearModelWeights` ，在当前的版本中，会出现 `TypeError: unsupported operand type(s) for *: 'int' and 'LinearModelWeights'` 错误；然而 `LinearModelWeights*2` 则正常。

是否应考虑在基类实现 `__rmul__` 方法？

**To Reproduce**
同上

**Comment by weiwee** [comment]
> **Describe the bug** Weights 中的加法、乘法 运算符重载，是否应该支持反向方法（reflected (swapped) operands）？
> 
> 比如，我想计算 `2*LinearModelWeights` ，在当前的版本中，会出现 `TypeError: unsupported operand type(s) for *: 'int' and 'LinearModelWeights'` 错误；然而 `LinearModelWeights*2` 则正常。
> 
> 是否应考虑在基类实现 `__rmul__` 方法？
> 
> **To Reproduce** 同上

Make sense.  Will implemented in version 1.8, or would you like to make a PR? @gxcuit

**Comment by gxcuit** [comment]
> > **Describe the bug** Weights 中的加法、乘法 运算符重载，是否应该支持反向方法（reflected (swapped) operands）？
> > 比如，我想计算 `2*LinearModelWeights` ，在当前的版本中，会出现 `TypeError: unsupported operand type(s) for *: 'int' and 'LinearModelWeights'` 错误；然而 `LinearModelWeights*2` 则正常。
> > 是否应考虑在基类实现 `__rmul__` 方法？
> > **To Reproduce** 同上
> 
> Make sense. Will implemented in version 1.8, or would you like to make a PR? @gxcuit

Hi, Thanks for your reply.
I will make a PR.

**Comment by weiwee** [comment]
> > > **Describe the bug** Weights 中的加法、乘法 运算符重载，是否应该支持反向方法（reflected (swapped) operands）？
> > > 比如，我想计算 `2*LinearModelWeights` ，在当前的版本中，会出现 `TypeError: unsupported operand type(s) for *: 'int' and 'LinearModelWeights'` 错误；然而 `LinearModelWeights*2` 则正常。
> > > 是否应考虑在基类实现 `__rmul__` 方法？
> > > **To Reproduce** 同上
> > 
> > 
> > Make sense. Will implemented in version 1.8, or would you like to make a PR? @gxcuit
> 
> Hi, Thanks for your reply. I will make a PR.

👍  merged to [develop-1.8](https://github.com/FederatedAI/FATE/tree/develop-1.8). Thinks for reporting issue and the pull-request.
