### ISSUE TITLE
Fate On Spark v1.6 : Guest and host pulsar clusters cannot be intersected

### ISSUE THREAD

**Issue by FranisiL** [FederatedAI/FATE#3477]
**Describe the bug**
If guest and host use their own pulsar cluster, they will always be running in the process of intersection. However, if guest and host use the same pulsar cluster, the intersection task can run successfully. I know that the above problems are caused by problems in the cluster interaction between guest and host's pulsar cluster,

**To Reproduce**
1. 部署Fate on Spark ，pulsar 分别别部署两套，每套都是三个节点，
2. 执行：python  fate_flow_client.py  -f submit_job -d  test_secureboost_train_dsl.json -c  test_secureboost_train_binary_conf.json（注意：test_secureboost_train_binary_conf.json中backend：2）
3. Data IO可以正常运行，但是到了intersection_0，就会一直在运行
4. 查看intersection_0日志显示卡在
[INFO] [2021-11-29 11:33:25,347] [8213:140451071149888] - intersect_model.py[line:50]: Using rsa intersection, role is guest
10
[INFO] [2021-11-29 11:33:25,348] [8213:140451071149888] - intersect.py[line:251]: Start RSA Intersection
11
[INFO] [2021-11-29 11:33:25,348] [8213:140451071149888] - intersect_guest.py[line:170]: RSA intersect using unified calculation.

5. 就是guest和host获取不到对方的public_key

**Expected behavior**
我期望可以走完整个训练任务流程

**Screenshots**

**Comment by dylan-fan** [comment]
any update ？

**Comment by dylan-fan** [comment]
is there same error for toy example？
