### ISSUE TITLE
Bugs in `self.prev_round_weights` of `homo_lr_guest` ？

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3491]
**Describe the bug**
在 `homo_lr_guest.py` 中，大约82-83行，
https://github.com/FederatedAI/FATE/blob/fbabd8c00efa5517113db3ea6684f39baa0ff2a1/python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_guest.py#L82..L83
```python
                # store prev_round_weights after aggregation
                self.prev_round_weights = copy.deepcopy(self.model_weights)
```

我理解的是， `self.prev_round_weights` 保存的是aggregate 之前的模型weights，然而`self.model_weights` 目前是aggregate之后的模型weights。是否应改为`self.prev_round_weights = copy.deepcopy(model_weights)` ？

**Additional context**

**Comment by tanmc123** [comment]
> **Describe the bug** 在 `homo_lr_guest.py` 中，大约82-83行， https://github.com/FederatedAI/FATE/blob/fbabd8c00efa5517113db3ea6684f39baa0ff2a1/python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_guest.py#L82..L83
> 
> ```python
>                 # store prev_round_weights after aggregation
>                 self.prev_round_weights = copy.deepcopy(self.model_weights)
> ```
> 
> 我理解的是， `self.prev_round_weights` 保存的是aggregate 之前的模型weights，然而`self.model_weights` 目前是aggregate之后的模型weights。是否应改为`self.prev_round_weights = copy.deepcopy(model_weights)` ？
> 
> **Additional context** Add any other context about the problem here.

不应该换，要保存的就是聚合后的模型，目的是和后面更新了但还没进行下一次聚合的model_weights分开，
不过后面求loss这里，写得有点点confuse，写成这样可能好
```python
                loss = self._compute_loss(data_instances, self.model_weights)
```
Anyway，逻辑应该是OK的

**Comment by gxcuit** [comment]
> > **Describe the bug** 在 `homo_lr_guest.py` 中，大约82-83行， https://github.com/FederatedAI/FATE/blob/fbabd8c00efa5517113db3ea6684f39baa0ff2a1/python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_guest.py#L82..L83
> > ```python
> >                 # store prev_round_weights after aggregation
> >                 self.prev_round_weights = copy.deepcopy(self.model_weights)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我理解的是， `self.prev_round_weights` 保存的是aggregate 之前的模型weights，然而`self.model_weights` 目前是aggregate之后的模型weights。是否应改为`self.prev_round_weights = copy.deepcopy(model_weights)` ？
> > **Additional context** Add any other context about the problem here.
> 
> 不应该换，要保存的就是聚合后的模型，目的是和后面更新了但还没进行下一次聚合的model_weights分开， 不过后面求loss这里，写得有点点confuse，写成这样可能好
> 
> ```python
>                 loss = self._compute_loss(data_instances, self.model_weights)
> ```
> 
> Anyway，逻辑应该是OK的

HI，@tanmc123 我还有个问题。

您说 > >_目的是和后面更新了但还没进行下一次聚合的model_weights分开_

我看代码中，**更新后，还没聚合的** 模型权重是`model_weights` ，  而聚合后的模型权重是`self.model_weights`了，这不是已经区分开了吗？
@tanmc123
