### ISSUE TITLE
训练了一个cross_validation，然后用官方例子调用predict的时候，报错，请问哪里设置的不对吗？谢谢

### ISSUE THREAD

**Issue by inseptember** [FederatedAI/FATE#3496]
训练了一个cross_validation，然后用官方例子调用predict的时候，报错，请问哪里设置的不对吗？谢谢
02 [ERROR] [2021-12-01 14:07:09,725] [202112011406539819270] [62746:140554232129344] - [task_executor._run_] [line:243]: Train_data should be configured in cross-validate task or stepwise task
403 Traceback (most recent call last):
404   File "./fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
405     cpn_output = run_object.run(cpn_input)
406   File "./fate/fate/python/federatedml/model_base.py", line 209, in run
407     method(cpn_input)
408   File "./fate/fate/python/federatedml/model_base.py", line 232, in _run
409     datasets=cpn_input.datasets, models=cpn_input.models, cpn=self
410   File "./fate/fate/python/federatedml/util/component_properties.py", line 299, in extract_running_rules
411     datasets, cpn
412   File "./fate/fate/python/federatedml/util/component_properties.py", line 248, in extract_input_data
413     self._abnormal_dsl_config_detect()
414   File "./fate/fate/python/federatedml/util/component_properties.py", line 178, in _abnormal_dsl_config_detect
415     "Train_data should be configured in cross-validate "

**Comment by mgqa34** [comment]
CV task does not support prediction,  in current version, cv task is designed to evaluate the performance of data.
