### ISSUE TITLE
Can the encryption and decryption module be turned off? It costs too much training time.......

### ISSUE THREAD

**Issue by DuJiahao1996** [FederatedAI/FATE#3501]
Where can I close it in the source program？

**Comment by DuJiahao1996** [comment]
Where can I close it  in the source program？

**Comment by dylan-fan** [comment]
It doesn't meet FATE design principles

**Comment by DuJiahao1996** [comment]
I just want to turn off the encryption module to improve my training efficiency, and then add the encryption module to see the final effect after the initial effect is satisfactory.

**Comment by DuJiahao1996** [comment]
> I just want to turn off the encryption module to improve my training efficiency, and then add the encryption module to see the final effect after the initial effect is satisfactory.

**Comment by DuJiahao1996** [comment]
> It doesn't meet FATE design principles

I just want to turn off the encryption module to improve my training efficiency, and then add the encryption module to see the final effect after the initial effect is satisfactory.

**Comment by DuJiahao1996** [comment]
> It doesn't meet FATE design principles

I just want to turn off the encryption module temporarily to reduce training time and improve training efficiency, and then add the encryption module to see the final effect after the initial effect is satisfactory.

**Comment by SennriSyunnga** [comment]
Only homo train job can turn off this configuration.

**Comment by DuJiahao1996** [comment]
> Only homo train job can turn off this configuration.

I just exactly use Homo. Where do I turn it off in the program，please sir.

**Comment by SennriSyunnga** [comment]
> > Only homo train job can turn off this configuration.
> 
> I just exactly use Homo. Where do I turn it off in the program，please sir.
Maybe it is not very precise……
If you are using homolr, you should set the conf like below :
```
"encrypt_param": {
                "method": null
}
```
in algo_parameters(also called 'common' in v2 dsl conf) 
If you don't set this method as null, fate will use Paillier as default. 
however, as far as i know, homo_nn dosen't have this configuration, 
which means that you cant turn of encrytion for it. 
Perhaps only few algorithmn support it.
You can check directory `/data/projects/fate/python/federatedml/param/` to find out whether the algorithmn you try support this configuration.
