### ISSUE TITLE
python容器一直重启，报错：Cannot assign requested address

### ISSUE THREAD

**Issue by JackieeYin** [FederatedAI/FATE#3515]
安装版本：kubefate1.5.0    serving: 2.0.0  集群部署
问题详情： python容器一直重启，logs报错如下：
{"created":"@1638784764.237329786","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1638784764.237323739","description":"Unable to configure socket","fd":13,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1638784764.237316178","description":"Cannot assign requested address","errno":99,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Cannot assign requested address","syscall":"bind"}]}]}
尝试解决：（看到有朋友说需要修改IP，我不太懂这个IP指的是哪里的IP），因此尝试修改docker-compose.yml文件中 ipv4_address: 192.167.0.100（具体位置如下），并将其修改为本机ip和其他任意地址后，并重新使用docker-compose up 重新部署后也没有解决这个问题。

 ` python:
    image: "federatedai/python:${TAG}"
    ports:
      - "9360:9360"
      - "9380:9380"
    restart: always
    volumes:
      - shared_dir_federatedml:/data/projects/fate/python/federat
      - shared_dir_examples:/data/projects/fate/examples
      - download_dir:/data/projects/fate/python/download_dir
      - ./confs/fate_flow/conf:/data/projects/fate/conf
      - ./confs/eggroll/conf:/data/projects/fate/eggroll/conf
      - fate_flow_logs:/data/projects/fate/logs
    depends_on:
      - mysql
      - rollsite
      - clustermanager
      - nodemanager
    networks:
      fate-network:
        ipv4_address: 192.167.0.100
`

请问有朋友知道这个问题应该怎么解决吗，感谢感谢~

**Comment by SennriSyunnga** [comment]
我上次看到这个问题，是我setup.conf配置文件中没有改各个hostip为真实ip造成的。
