### ISSUE TITLE
Bug and Ferture Request for `flow_client`: Relative path issue in `upload-conf.json` when uploading data.

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3516]
**Describe the bug**
一个Bug，一个Feature request。

** 1 Bug：**
在使用`flow data upload`上传文件的时候，配置文件`"file":`选项，如果使用相对路径`../`访问上级目录会有问题，而`./`则正常。这是下述代码导致的：
详情见 `cli_utils.py` --》`def check_abs_path(path)`方法: 只是简单的进行替换:

```
def check_abs_path(path):
    if not os.path.isabs(path):
        return os.path.join(os.path.abspath(os.curdir), path).replace("./", "")
    return path
```

** 2 Ferture Request**
在处理`upload-conf.json`涉及相对路径的时候，有些confusing。目前实现的是：相对路径是相对于flow-client运行的路径。而我感觉，既然相对路径是在`upload-conf.json`中定义的，那么相对路径应该是相对于`upload-conf.json`这个文件所在的目录，而不是`flow-client` 工作目录。 

目前如果`upload.json`中`file`使用相对路径，当`flow-client` 工作在不同目录（其他配置都不变），会有bug。

**Additional context**
不知道我的表述是否清楚？是否reasonable？If so, may I submit a PR?

**Comment by jat001** [comment]
https://github.com/FederatedAI/FATE/commit/8a6ec59c509508764e8c711984d1f072d112d8ab#diff-aa637d9a5cb67f9f347398e9c443342517a6b317b498f757968f409a4ca670a7R135

不太确定为什么加 `replace("./", "")`，看起来像个 bug

这里如果是相对路径的话，应该是相对于当前工作目录的路径，这个逻辑还是先不要动了
