### ISSUE TITLE
一个job完成结束之后，为什么guest和host之间底层还会有tcp报文通信，监测guesty与host各自的9370端口，还会有长度为17的报文相互发送

### ISSUE THREAD

**Issue by yidiexiaocaipx** [FederatedAI/FATE#3517]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhihuiwan** [comment]
job状态修改之后可能会有一些额外的操作(如清理)需要调用通信接口发送命令

**Comment by yidiexiaocaipx** [comment]
想问下底层grpc协议创建channel有默认的keepalive时间是6分钟吗，这个超出了使用设备的防火墙长连接超时时间，可以设置保活或者修改keepalive时间吗
