### ISSUE TITLE
dev-doc: `Fate-flow` need to be restarted after developing/modifying parameters of the model

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3522]
After developing/modifying parameters of the model, the `fate-flow` need to be restarted. Otherwise, it will cause `redundant parameter` error as follows:
```
{
    "retcode": 100,
    "retmsg": "Component homo_lr_0, module HomoLRMP, has redundant parameter test"
}
```

Currently, the develop doc does not mention this point.

**Comment by zhihuiwan** [comment]
The debug mode of fate flow 1.7 can solve this problem, you can start the service through：
"python fate_flow_server.py --debug"

**Comment by gxcuit** [comment]
> The debug mode of fate flow V1.7 can solve this problem, you can start the server through： "python fate_flow_server.py --debug"

Ok, I will try it later. Does the develop doc need to mention this point in order to make it more friendly to developers?

**Comment by mgqa34** [comment]
In. FATE-v1.8, develop doc is modified according to this issue, thanks for your suggestion
