### ISSUE TITLE
Bug in standalone deployment `init.sh` :  `fate_sed_cmd: command not found`

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3526]
**Describe the bug**
I install fate in the host (using the compiled installer), as suggested in  [doc ](https://github.com/FederatedAI/FATE/tree/master/deploy/standalone-deploy).  
When I execute `sh init.sh init`, I get an error like this:
`fate_sed_cmd: command not found`.

The `fate-sed` command has already set in `bin/common.sh`. However, according to [ref1](https://unix.stackexchange.com/questions/158038/non-interactive-shell-expand-alias) and [ref2](https://www.codenong.com/24054154/):  

> Aliases are not expanded when the shell is not interactive, unless the expand_aliases shell option is set using shopt

**Therefore, I suggest add `shopt -s expand_aliases` in `bin/common.sh`.**

**To Reproduce**
1. install fate via `bash init.sh init`

**Expected behavior**
Success without errors.

**Screenshots**.

**Desktop (please complete the following information):**
[INFO] kernel: Linux
[INFO] linux system: Ubuntu 18.04
[INFO] os: Ubuntu 18.04

**Additional context**

**Comment by Yonggie** [comment]
I'm following the [docs](https://fate.readthedocs.io/en/latest/deploy/standalone-deploy/) and gets the same error when running ``bash init.sh init``
