### ISSUE TITLE
Can we upload the MNIST image data? 

### ISSUE THREAD

**Issue by AArchLichKing** [FederatedAI/FATE#3538]
Could you please provide some guides on how to upload MNIST image data? I notice that there is a demo [here](https://github.com/FederatedAI/FATE/tree/develop-1.7/examples/dsl/v2/homo_nn/mnist_demo) where MNIST is of the form of image data, but following this one leads to the following errors: 

[ERROR] [2021-12-15 19:58:32,136] [202112151958174223810] [515421:139859674400576] - [task_executor._run_] [line:243]: can not found table name: mnist_images_host_1 namespace: experiment
Traceback (most recent call last):
  File "/home/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/home/DAIR/duzx/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/components/_base.py", line 149, in run
    method(cpn_input)
  File "/home/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/components/reader.py", line 93, in _run
    output_storage_address=output_storage_address,
  File "/home/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/components/reader.py", line 219, in convert_check
    f"can not found table name: {input_name} namespace: {input_namespace}"
RuntimeError: can not found table name: mnist_images_host_1 namespace: experiment

I guess this is due to not uploading data. 

Thank you very much in advance!!!!!!

**Comment by AArchLichKing** [comment]
Following up problems,

if I use `fate_test suite -i mnist_nn_testsuite.json` and abort the job before the table is deleted, 

then the output logs of ` flow job submit -c mnist_conf.json -d mnist_dsl.json` are of the following structure


`/home/standalone_fate_install_1.7.0_release/fateflow/logs/202112160924124976150/
├── fate_flow_audit.log
├── fate_flow_schedule.log
└── fate_flow_sql.log`

**Comment by weiwee** [comment]
> Could you please provide some guides on how to upload MNIST image data? I notice that there is a demo [here](https://github.com/FederatedAI/FATE/tree/develop-1.7/examples/dsl/v2/homo_nn/mnist_demo) where MNIST is of the form of image data, but following this one leads to the following errors:
> 
> [ERROR] [2021-12-15 19:58:32,136] [202112151958174223810] [515421:139859674400576] - [task_executor._run_] [line:243]: can not found table name: mnist_images_host_1 namespace: experiment Traceback (most recent call last): File "/home/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_ cpn_output = run_object.run(cpn_input) File "/home/DAIR/duzx/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/components/_base.py", line 149, in run method(cpn_input) File "/home/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/components/reader.py", line 93, in _run output_storage_address=output_storage_address, File "/home/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/components/reader.py", line 219, in convert_check f"can not found table name: {input_name} namespace: {input_namespace}" RuntimeError: can not found table name: mnist_images_host_1 namespace: experiment
> 
> I guess this is due to not uploading data.
> 
> Thank you very much in advance!!!!!!

I think there is `name` mismatch between [`bind_local_path`](https://github.com/FederatedAI/FATE/blob/fbabd8c00efa5517113db3ea6684f39baa0ff2a1/examples/dsl/v2/homo_nn/mnist_demo/bind_local_path.json#L3..L4) and [`mnist_conf.json`](https://github.com/FederatedAI/FATE/blob/fbabd8c00efa5517113db3ea6684f39baa0ff2a1/examples/dsl/v2/homo_nn/mnist_demo/mnist_conf.json#L102..L121)

try to bind local path to table with correct `name` and `namespace` with `bind command` according to [`README.md`](https://github.com/FederatedAI/FATE/blob/fbabd8c00efa5517113db3ea6684f39baa0ff2a1/examples/dsl/v2/homo_nn/mnist_demo/README.md?plain=1#L13..L15)

**Comment by AArchLichKing** [comment]
It works! closed the issues.

**Comment by davadd** [comment]
你好，图像识别做成了吗？我的报错是没有ymal文件
