### ISSUE TITLE
ERROR: error while removing network: network confs-10000_fate-network has active endpoints

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#3546]
when i execute "bash docker_deploy.sh all"
error uccurs 
![image](https://user-images.githubusercontent.com/37823459/146644436-f3f82b36-3340-447e-9d06-ad775781800e.png)

version：kubefate-docker-compose-v1.7.0.tar

**Comment by weiwee** [comment]
As the `ERROR` message indicate, you have active endpoints with same network, try to disconnect it before running script again.
