### ISSUE TITLE
The latest version of `fate-test` in `pypi` is 1.6.1, instead of 1.7.0

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3550]
**Is your feature request related to a problem? Please describe.**
The latest version of `fate-test` in [pypi ](https://pypi.org/project/fate-test/)is 1.6.1, instead of 1.7.0. Therefore I cannot install the latest version of fate-client through` pip install fate-test`. 

Is there any way that I can use fate-test 1.7.0?

**Comment by mgqa34** [comment]
FATE-Test is not a client-side python package, so it will not be pushed to fate_test since fate-v1.7. 
If you want to use it in server-side, please refer to https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_test_tutorial.md, use command "pip install -e python/fate_test".

**Comment by weiwee** [comment]
We no longer release `fate-test` since version 1.7.0, because it is intended for development testing. 
You still could use latest `fate-test` by install [editable](https://pip-python3.readthedocs.io/en/latest/reference/pip_install.html#vcs-support):

```bash
python -m pip install -e python/fate_client
python -m pip install -e python/fate_test
```

or locally 

```bash
python -m pip install  python/fate_client
python -m pip install  python/fate_test
```

**Comment by gxcuit** [comment]
> FATE-Test is not a client-side python package, so it will not be pushed to fate_test since fate-v1.7. If you want to use it in server-side, please refer to https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_test_tutorial.md, use command "pip install -e python/fate_test".

Thanks a lot! BTW, does the version in `pyproject.toml`  need to change? It is confusing when I install fate-test in this way. https://github.com/FederatedAI/FATE/blob/6a9c2dd6ff95fcab6f336a2e188a0c58f3777d39/python/fate_test/pyproject.toml#L3

**Comment by weiwee** [comment]
You can bump the version if you like to. We would like to preserve `0.1` in code and bump the version only when publishing to PIPy with GitHub Action https://github.com/FederatedAI/FATE/blob/6a9c2dd6ff95fcab6f336a2e188a0c58f3777d39/.github/workflows/pypi.yml#L44
