### ISSUE TITLE
5000w id

### ISSUE THREAD

**Issue by JasonBian** [FederatedAI/FATE#3561]
==== detail start, at 20211223.062242.684 ====
Traceback (most recent call last):

  File "./fate/eggroll/python/eggroll/core/pair_store/lmdb.py", line 244, in put

    ret = self.txn.put(k, v)

lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached

**Comment by mgqa34** [comment]
Use more partitions, upload config's partitions or submit_conf's task_cores should be set bigger to avoid a single partition's disk space > 16G

**Comment by JasonBian** [comment]
> 
ok, Thanks for your advise

**Comment by JasonBian** [comment]
@mgqa34 Thanks for your advise
