### ISSUE TITLE
大数据量情况下使用Spark 的问题

### ISSUE THREAD

**Issue by huajinghua** [FederatedAI/FATE#3562]
**Describe the bug**
使用10亿PSI求交时

**To Reproduce**
1. 使用10亿vs10亿求PSI，BloomFilter+Hash求交
2. 参数设置误差率0.1，此时每个布隆过滤器位图大小为577M 左右；10亿数据，如果分区数比较大，比如100
3. 那么在construct_filter 的new_array = data.mapPartitions(f).reduce(lambda x, y: x | y) 语句执行会出现问题，主要是在reduce阶段，pyspark原始api会将所有分区数据拉到driver上执行本地reduce，那么此时reduce接收数据量大小为574M*100 ，将内存撑爆，后续无法执行

解决方案：
此时需要使用treeReduce 模式，对每个分区位图进行逐个reduce

**Comment by huajinghua** [comment]
建议算法中存在大对象Reduce的地方都需要适配下

**Comment by huajinghua** [comment]
建议算法中存在大对象Reduce的地方都需要适配下

**Comment by weiwee** [comment]
make sense, 我加下treeReduce接口 请@nemirorox适配下

**Comment by weiwee** [comment]
fix in #3563, thanks report!
