### ISSUE TITLE
hetero SecureBoost early_stop死锁

### ISSUE THREAD

**Issue by zhanhtCN** [FederatedAI/FATE#3564]
**Describe the bug**
使用纵向树模型，当触发early stop时候，会任务卡死不动

**To Reproduce**
1.使用树模型和官方自带的数据和配置
2.加大树的棵树，并early_stopping_rounds=1，让触发早停
3.任务触发早停后，将会卡死。guest方卡在predict，host早停后，会继续下次迭代，卡在获取grad和hess。两方处于不同流程，在等待不同的信息，导致死锁。

**Expected behavior**
触发早停后，任务停止

**Screenshots**
![image](https://user-images.githubusercontent.com/96578077/147239696-507c5003-65d1-4c12-b15a-e0216bb48d7f.png)
![image](https://user-images.githubusercontent.com/96578077/147239715-24f48d0a-2d51-44ea-9c2e-c5b7e176b380.png)

**os**
 - centos 7

**Comment by talkingwallace** [comment]
early stop功能存在bug，我们会在1.7.1版本修复，如果在1.7使用，可以修改一行代码: 在hetero_booting.py的第339行
![image](https://user-images.githubusercontent.com/10768970/147311728-400fbf33-fecf-479c-924b-717f97425acb.png)
改为上图

**Comment by zhanhtCN** [comment]
按照上图进行了修改，问题依然存在。
1. 使用自带的conf和DSL配置https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/hetero_secureboost/test_secureboost_train_binary_conf.json
https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/hetero_secureboost/test_secureboost_train_dsl.json
2.conf改动，加大num_trees到30，添加配置"early_stopping_rounds": 1，让触发early_stop
3. 依然同样卡死状态

代码改动截图：
![image](https://user-images.githubusercontent.com/96578077/147321004-81ae5866-af06-4732-8862-fb3ff75b460e.png)

host日志截图：
![image](https://user-images.githubusercontent.com/96578077/147321058-a71c123e-4b4c-4561-93e1-7b09dc91b681.png)

补充：
看guest类似的地方，是 should_stop or self.stop_training，所以这个host代码，也应该是 or，而不是and

**Comment by gxcuit** [comment]
> 

我也感觉是or的逻辑

**Comment by talkingwallace** [comment]
是的 该使用or 是我疏忽了 原答复已经删除，在hetero_booting.py的第339行 改为与guest方相同的
![企业微信截图_16403320247410](https://user-images.githubusercontent.com/10768970/147331063-fe0aa574-ee60-42fb-977e-e08c090abb3e.png)

**Comment by gxcuit** [comment]
> self.stop_training

Hi, `homo_boosting` 是否有相同的问题？
