### ISSUE TITLE
ValueError: non-printable char found in sid_name ﻿id, please check.

### ISSUE THREAD

**Issue by hellolsk** [FederatedAI/FATE#3570]
fate1.7.0,ss-he-lr,data-transform过程中报错，是我自己新增了id列，如何解决？

**Comment by mgqa34** [comment]
Use vim or other editor to check if the raw data'header has non-printable char.

**Comment by hellolsk** [comment]
> Use vim or other editor to check if the raw data'header has non-printable char.

thanks a lot! the data should save with utf-8 with no-bom
