### ISSUE TITLE
集群部署架构图的疑问

### ISSUE THREAD

**Issue by gm100861** [FederatedAI/FATE#3573]
![image](https://user-images.githubusercontent.com/3993839/147536290-2c931f4a-ae83-4b82-93b7-314f5acf04db.png)
因为最近在部署集群,所以对该架构图有一些疑问. 双方FATE-Flow通讯经过各自端的Nginx这块没有疑问,请求到本端Nginx之后,是否是由Nginx直接请求对端的FATE-Flow了, 而不是到对端的Nginx服务器? 即我图中标的结果.
仔细分析了router.lua和route_table.lua, 看起来是这样,所以想确认下是否图画的有误

**Comment by jarviszeng-zjc** [comment]
图没有错的，目前的版本转发的链路是依据route table来，route table中可以同时配proxy地址和flow地址，flow地址优先，所以实际生产中，除了本方party配置flow地址，其他方都配置该方的proxy，那链路就跟图一致了

**Comment by FranisiL** [comment]
那就是说在现在实际使用过程中就是像“提问同学”画的这样对吧，我看代码中使用的都是fate地址，也就是直接访问的fate_flow服务，并没有经过nginx转发，那proxy什么情况下会使用呢？

**Comment by gm100861** [comment]
图画的没有问题, 确实是配置的事情, 按照图中配置也可以实现. 又跟我们运维沟通了一下, 按照官方图中的配置, 业务可以正常运行.
