### ISSUE TITLE
how to delete uploaded data?

### ISSUE THREAD

**Issue by kaiwang0112006** [FederatedAI/FATE#3584]
I upload data following the instruction of [upload script](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/demo/pipeline-upload.py)
. After reading the source code of https://github.com/FederatedAI/FATE/blob/6a9c2dd6ff95fcab6f336a2e188a0c58f3777d39/python/fate_client/pipeline/backend/pipeline.py, I cannot find a function to delete the uploaded data. I'm wondering is there a fast way to do that?

**Comment by gxcuit** [comment]
> I upload data following the instruction of [upload script](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/demo/pipeline-upload.py) . After reading the source code of https://github.com/FederatedAI/FATE/blob/6a9c2dd6ff95fcab6f336a2e188a0c58f3777d39/python/fate_client/pipeline/backend/pipeline.py, I cannot find a function to delete the uploaded data. I'm wondering is there a fast way to do that?

Hi, You can delete table data with table delete
`flow table delete --name(table name) --namespace`

```
parameter name	required	type	description
name	yes	string	fate table name
namespace	yes	string	fate table namespace
```

**Comment by kaiwang0112006** [comment]
ok. thx for the quick support. I'll close this issue

**Comment by gxcuit** [comment]
> ok. thx for the quick support. I'll close this issue

Note: If you use FATE 1.7+, please change parameter name from  `name` to `table-name`.
You can find the command usage by `flow table info -h`
