### ISSUE TITLE
I can't get my model data output

### ISSUE THREAD

**Issue by grey2818** [FederatedAI/FATE#3589]
I am not quite clear about where and how FATE should define the model to output its own data, and finally it can be displayed in the output of Fateboard. It would be really appreciated if you can provide some examples.

**Comment by grey2818** [comment]
when the task finished, my log show that:
[task_executor._run_] [line:199]: task output data [None]
but I look at its own algorithm：
task output data [<fate_arch.computing.eggroll._table.Table object at 0x7f363839bc88>]
The algorithm I wrote myself didn't have any output.

**Comment by JianhuanZeng** [comment]
+1, when the task finished
the good one with output
1. [INFO] [2022-05-18 10:14:51,234] [202205181005213579990] [22886:139674820912960] - [task_executor._run_] [line:199]: task output data [<fate_arch.computing.eggroll._table.Table object at 0x7f086de02390>]
the bad one without output
2. [INFO] [2022-05-18 10:11:59,457] [202205180957391574150] [18041:139769249228608] - [task_executor._run_] [line:199]: task output data [None]
