### ISSUE TITLE
Can I convert a HomoSecureBoost model of pkl file to sklearn-style object

### ISSUE THREAD

**Issue by kaiwang0112006** [FederatedAI/FATE#3605]
I can complete a homo-sbt-job following [this example](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/homo_sbt/pipeline-homo-sbt-binary-with-predict.py) and save the model by *pipeline.dump("hflpipeline_saved.pkl")*

Can I convert a HomoSecureBoost model of pkl file to sklearn-style object? So I can develop a model service with flask same as a local model?

**Comment by talkingwallace** [comment]
In the latest version of FATE, we can convert Homo-Secureboost models to local LightGBM models.

**Comment by matthew-wei** [comment]
> 

Please show the detail.

**Comment by matthew-wei** [comment]
@talkingwallace 
Please show the detail.

**Comment by talkingwallace** [comment]
> @talkingwallace Please show the detail.

flow client offers this function
 see https://federatedai.github.io/FATE-Flow/latest/backup/fate_flow_client.zh/#homo-convert for more details

**Comment by matthew-wei** [comment]
> > @talkingwallace Please show the detail.
> 
> flow client offers this function see https://federatedai.github.io/FATE-Flow/latest/backup/fate_flow_client.zh/#homo-convert for more details

Thanks,  I follow the directions and get the model files.
