### ISSUE TITLE
Feature request: operator overloading in `PaillierEncryptedNumber`

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3607]
**Is your feature request related to a problem? Please describe.**

Right now, the `PaillierEncryptedNumber` does not support Arithmetic unary negation, i.e, `- PaillierEncryptedNumber`.  When the developer needs to compute the negative number of the ciphertext,  it will get an error like this ypeError: `bad operand type for unary -: 'PaillierEncryptedNumber'`. 

**Describe the solution you'd like**

Override `__neg__` function in class `PaillierEncryptedNumber`, and call self.__mul__(-1)

The result of `- PaillierEncryptedNumber`  should be same as `PaillierEncryptedNumber * -1`

**Comment by mgqa34** [comment]
You're right, same interface should also be provided in FixedPointTensor  ect.

**Comment by gxcuit** [comment]
> You're right, same interface should also be provided in FixedPointTensor etc.

Ok, I will make a PR.
BTW,will you please be kindly checking [the latest reply](https://github.com/FederatedAI/FATE/issues/3596#issuecomment-1005434698) of this issue ? I have replyed and did not get an answer.  I still do not think the loss is calculated correctly. Thanks !
