### ISSUE TITLE
KeyError: 'file' when using REST API to upload data

### ISSUE THREAD

**Issue by kaiwang0112006** [FederatedAI/FATE#3647]
I'm trying to use REST API  to upload data and got KeyError: 'file'

        $ curl -H "Content-Type:application/json" -X POST -d '{"table_name": "breast_hetero_guest","namespace": "experiment", "head": 1,"partition": 4,"drop":1 ,"file":"/work/fate_demo/vfl001/breast_hetero_guest.csv"}' http://10.240.16.39:9380/v1/data/upload
        <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
        <title>400 Bad Request</title>
        <h1>Bad Request</h1>
        <p>The browser (or proxy) sent a request that this server could not understand.</p><p><pre><code>KeyError: 'file'</code></pre></p>
        (base) root@bdp-privacy-test-3:/work/fate_demo/vfl001# curl -H "Content-Type:application/json" -X POST -d '{"table_name": "breast_hetero_guest","namespace": "experiment", "head": 1,"partition": 4,"drop":1,"file":"/work/fate_demo/vfl001/breast_hetero_guest.csv"}' http://10.240.16.39:9380/v1/data/upload
        <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
        <title>400 Bad Request</title>
        <h1>Bad Request</h1>
        <p>The browser (or proxy) sent a request that this server could not understand.</p><p><pre><code>KeyError: 'file'</code></pre></p>

**Comment by zhihuiwan** [comment]
By default, fate flow uses the data on the client machine. Then you need to upload a file stream. If your data is on the fateflow server machine, you can do it in the following two ways:
1. Change the configuration "UPLOAD_DATA_FROM_CLIENT" of fate_flow/settings.py to "False", and restart the fate flow；
2. Add the parameter "use_local_data" to the request body, the parameter value is 0.

**Comment by Timo9Madrid7** [comment]
Can rest API support folder upload or `table bind`, as the inputs are images?
