### ISSUE TITLE
How to make New Algorithm take effect in cluster

### ISSUE THREAD

**Issue by patricxu** [FederatedAI/FATE#3695]
I have deployed FATE on a two-machine cluster and developped a new algorithm following the [Developing guides](https://github.com/FederatedAI/FATE/blob/v1.6.0/doc/develop_guide.rst) on the host machine, but don't know how to make it work.

Do I have to reinstall the FATE package on the host? and how to sync the code of the new algorithm to client?

Thanks!

**Comment by mgqa34** [comment]
Restart fate_flow_server.py may work. 
Btw, you don't need to sync the code to client if using dsl&conf to submit the new developed algorithm, but if you want to submit it using pipeline, pipeline's code should be updated.
