### ISSUE TITLE
has any plan to implement Homo SSHE Logistic Regression?

### ISSUE THREAD

**Issue by ludeen007** [FederatedAI/FATE#3698]
FATE 1.7 already has Heterogeneous SSHE Logistic Regression, has any plan to implement Homo SSHE Logistic Regression? if has, what's the schedule?

**Comment by gxcuit** [comment]
我目前看的论文是纵向场景的的SSHE-LR。

横向的SSHE不知道有没有相关的论文？有论文的话，自然可以复现。
