### ISSUE TITLE
tensorflow 找不到

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FATE#3700]
报错信息
ModuleNotFoundError: No module named 'tensorflow'

fate 版本 1.7.0 部署使用的docker 部署的kubefate,使用notebook 运行
使用breast_homo_guest 做横向联邦
运行这个ipython notebook
https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_homo_nn.ipynb

运行到此处报错
![image](https://user-images.githubusercontent.com/19608744/153751799-50653b52-cb64-4168-bf5e-725b4556f83a.png)

![8c0931a8bd7be441df54927e41c677b](https://user-images.githubusercontent.com/19608744/153751835-ee56aa00-b982-4594-b169-c2b6dd50d96b.png)

**Comment by dylan-fan** [comment]
没有安装tf

**Comment by L-Loki** [comment]
请问这个问题你解决了吗
