### ISSUE TITLE
Optimize Hetero SecureBoost Predict Transmission Data Size.

### ISSUE THREAD

**Issue by mgqa34** [FederatedAI/FATE#3702]
**Is your feature request related to a problem? Please describe.**
In Fate's version <= 1.7.1，hetero-secureboost uses np.int64 to represent the node position in predict process. This is waste and will be a bottleneck when network bandwidth  is small. This should be optimized in later version
Code:  https://github.com/FederatedAI/FATE/blob/master/python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py#L310

**Comment by talkingwallace** [comment]
> 你好，请问下，我看hetero_secureboost_guest.py 有两个地方用到了int64,，是都可以结合树深适当改小吗？ <img alt="image" width="808" src="https://user-images.githubusercontent.com/96578077/154483948-3b269045-f8f1-4c22-87c4-5b1999ee07ba.png"> <img alt="image" width="923" src="https://user-images.githubusercontent.com/96578077/154483993-30293fd3-86ab-4426-b3aa-e0ad7da6798f.png">

是的 可以根据树高改小
