### ISSUE TITLE
有没有微信交流群？

### ISSUE THREAD

**Issue by jimmy-chow** [FederatedAI/FATE#3704]
搜了下没找到对应的交流群，自己建了个，大家交流下 :)

![2487a11ce8ce581f18a6f2426a429b2](https://user-images.githubusercontent.com/57430215/154004620-ed637fe6-b13c-4f3f-ae8c-07887ab5874f.jpg)

**Comment by mgqa34** [comment]
https://github.com/FederatedAI/FATE-Community#communicating
Here are some of the channels we use to communicate and contribute.

Mailing list: Join the FATE [mailing list](https://groups.io/g/Fate-FedAI), connect with the community and learn about the latest news and information from FATE team, as well as any discussion and feedback around FATE project or community.

Issue tracker: Use the [GitHub issue tracker](https://github.com/FederatedAI/FATE/issues) to file bugs and features request. If you need help, bring your questions via mailing list.

WeChat assistant: FATE's official technology WeChat groups, which provide technical support for any developers and users of FATE. You can communicate and learn with technical enthusiasts from various industries, and get the latest federated learning information. Join us via WeChat ID: FATEZS001

FATE是有官方社区微信交流群的，建议联系"FATEZS001"，FATE开源社区小助手去了解。

**Comment by jimmy-chow** [comment]
> https://github.com/FederatedAI/FATE-Community#communicating Here are some of the channels we use to communicate and contribute.
> 
> Mailing list: Join the FATE [mailing list](https://groups.io/g/Fate-FedAI), connect with the community and learn about the latest news and information from FATE team, as well as any discussion and feedback around FATE project or community.
> 
> Issue tracker: Use the [GitHub issue tracker](https://github.com/FederatedAI/FATE/issues) to file bugs and features request. If you need help, bring your questions via mailing list.
> 
> WeChat assistant: FATE's official technology WeChat groups, which provide technical support for any developers and users of FATE. You can communicate and learn with technical enthusiasts from various industries, and get the latest federated learning information. Join us via WeChat ID: FATEZS001
> 
> FATE是有官方社区微信交流群的，建议联系"FATEZS001"，FATE开源社区小助手去了解。

No response from wechat assistor :(

**Comment by yjx1124** [comment]
可以加我一下吗，我的微信号是yjx11245013
