### ISSUE TITLE
分布式更慢了：相同数据、相同分区、相同并行度、相同训练参数

### ISSUE THREAD

**Issue by henshy** [FederatedAI/FATE#3722]
数据维度：双边40w+450维
模型：secureboost
机器与环境：多台（32核、64G）、内网
分布式：k8s集群2台：2台
任务参数：
    "common": {
                "job_type": "train",
                "task_cores": 32,
                "task_parallelism": 1,
                "computing_partitions": 32
            }
算法参数：
    "common": {
                "hetero_secure_boost_0": {
                    "task_type": "classification",
                    "objective_param": {
                        "objective": "cross_entropy"
                    },
                    "validation_freqs": 1,
                    "encrypt_param": {
                        "method": "Paillier",
                        "key_length": 2048
                    },
                    "learning_rate": 0.1,
                    "num_trees": 10,
                    "tree_param": {
                        "max_depth": 5
                    }
                },
                "evaluation_0": {
                    "eval_type": "binary"
                },
                "data_transform_0": {
                    "input_format": "sparse"
                },
                "data_transform_1": {
                    "input_format": "sparse"
                }
            }
训练耗时（host为例）：
      分布式计算：
<img width="544" alt="image" src="https://user-images.githubusercontent.com/15920785/155057418-0559d081-19a5-4e86-9f34-5034276fc749.png">
      单机计算：
<img width="539" alt="image" src="https://user-images.githubusercontent.com/15920785/155057445-710d04a1-15dd-4562-a3c6-9dc9641e3dde.png">
      分布式通讯：
<img width="878" alt="image" src="https://user-images.githubusercontent.com/15920785/155057559-89f36767-392e-47aa-878d-64b4f7e97e68.png">
      单机通讯：
<img width="878" alt="image" src="https://user-images.githubusercontent.com/15920785/155057514-352cf6f4-4f59-4850-a65f-d29c60083946.png">
耗时总结：
       分布式的mapReducePartitions花了8000多秒，单机反而是4000多秒；
       网络通讯也一样，分布式get下的encrypted_grad_and_hess花费4343秒，单机2511秒。

**Comment by gm100861** [comment]
同样的单机环境, 1.6的速度比1.7要快. 我之前提过一个bug, 官方还没给回应

**Comment by fionser** [comment]
@gm100861 顺带请问。单机环境下 想限制 使用的多进程数量。通过设置 job_parameters 似乎没有效果。top 之后还是能看到大量的 python 进程。请问是如何调节这个参数呢
