### ISSUE TITLE
Is FATE support real multiple hosts?

### ISSUE THREAD

**Issue by hqsh** [FederatedAI/FATE#3742]
I always believe FATE support multiple hosts, as multiple companys joined as host role into federated learning.
Until I found this issue today: https://github.com/FederatedAI/FATE/issues/944.
I don't know the meaning of KathyKing replied. Multiple host roles has any difference from multi-party?

英语不好，可能表述不一定准确，中文意思如下：
我一直以为 FATE 都是通过多个 host 方来，支持多个公司作为 host 方参与联邦学习。
直到今天看到了这个令人困惑的 issue，不清楚该 issue 的答复 ”没有多方部署，以两方扩展“，是什么意思，多个 host 方组成的联邦学习，会和真正的多方，有差异吗，会有什么限制吗？是否只有所有的 host 的算法代码，都是一致的，这个限制？通信等其他各方面，都没有限制的吧？

**Comment by gxcuit** [comment]
> I always believe FATE support multiple hosts, as multiple companys joined as host role into federated learning. Until I found this issue today: #944. I don't know the meaning of KathyKing replied. Multiple host roles has any difference from multi-party?
> 
> 英语不好，可能表述不一定准确，中文意思如下： 我一直以为 FATE 都是通过多个 host 方来，支持多个公司作为 host 方参与联邦学习。 直到今天看到了这个令人困惑的 issue，不清楚该 issue 的答复 ”没有多方部署，以两方扩展“，是什么意思，多个 host 方组成的联邦学习，会和真正的多方，有差异吗，会有什么限制吗？是否只有所有的 host 的算法代码，都是一致的，这个限制？通信等其他各方面，都没有限制的吧？

Hi,我不是FATE 官方，以下是我的理解：
#994 这个issue是2020年1月的，距今已经有两年了。 FATE 目前大部分算法是支持多个host的，例如横纵向LR、secure boost等，只需要改一下conf文件即可。
Please kindly refer to：
 examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_conf.json  examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_dsl.json

**Comment by hqsh** [comment]
> > I always believe FATE support multiple hosts, as multiple companys joined as host role into federated learning. Until I found this issue today: #944. I don't know the meaning of KathyKing replied. Multiple host roles has any difference from multi-party?
> > 英语不好，可能表述不一定准确，中文意思如下： 我一直以为 FATE 都是通过多个 host 方来，支持多个公司作为 host 方参与联邦学习。 直到今天看到了这个令人困惑的 issue，不清楚该 issue 的答复 ”没有多方部署，以两方扩展“，是什么意思，多个 host 方组成的联邦学习，会和真正的多方，有差异吗，会有什么限制吗？是否只有所有的 host 的算法代码，都是一致的，这个限制？通信等其他各方面，都没有限制的吧？
> 
> Hi,我不是FATE 官方，以下是我的理解： #994 这个issue是2020年1月的，距今已经有两年了。 FATE 目前大部分算法是支持多个host的，例如横纵向LR、secure boost等，只需要改一下conf文件即可。 Please kindly refer to： examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_conf.json examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_dsl.json

感谢您的答复，我也觉得应该是这样。只是不知有没有实际部署到生产环境中，2个或更多的 host 方的场景，有没有通信速度等限制问题？谢谢！

**Comment by gxcuit** [comment]
> > > I always believe FATE support multiple hosts, as multiple companys joined as host role into federated learning. Until I found this issue today: #944. I don't know the meaning of KathyKing replied. Multiple host roles has any difference from multi-party?
> > > 英语不好，可能表述不一定准确，中文意思如下： 我一直以为 FATE 都是通过多个 host 方来，支持多个公司作为 host 方参与联邦学习。 直到今天看到了这个令人困惑的 issue，不清楚该 issue 的答复 ”没有多方部署，以两方扩展“，是什么意思，多个 host 方组成的联邦学习，会和真正的多方，有差异吗，会有什么限制吗？是否只有所有的 host 的算法代码，都是一致的，这个限制？通信等其他各方面，都没有限制的吧？
> > 
> > 
> > Hi,我不是FATE 官方，以下是我的理解： #994 这个issue是2020年1月的，距今已经有两年了。 FATE 目前大部分算法是支持多个host的，例如横纵向LR、secure boost等，只需要改一下conf文件即可。 Please kindly refer to： examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_conf.json examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_dsl.json
> 
> 感谢您的答复，我也觉得应该是这样。只是不知有没有实际部署到生产环境中，2个或更多的 host 方的场景，有没有通信速度等限制问题？谢谢！

只要是支持多host的component，目前看是没有速度限制等问题。

**Comment by hqsh** [comment]
> > > > I always believe FATE support multiple hosts, as multiple companys joined as host role into federated learning. Until I found this issue today: #944. I don't know the meaning of KathyKing replied. Multiple host roles has any difference from multi-party?
> > > > 英语不好，可能表述不一定准确，中文意思如下： 我一直以为 FATE 都是通过多个 host 方来，支持多个公司作为 host 方参与联邦学习。 直到今天看到了这个令人困惑的 issue，不清楚该 issue 的答复 ”没有多方部署，以两方扩展“，是什么意思，多个 host 方组成的联邦学习，会和真正的多方，有差异吗，会有什么限制吗？是否只有所有的 host 的算法代码，都是一致的，这个限制？通信等其他各方面，都没有限制的吧？
> > > 
> > > 
> > > Hi,我不是FATE 官方，以下是我的理解： #994 这个issue是2020年1月的，距今已经有两年了。 FATE 目前大部分算法是支持多个host的，例如横纵向LR、secure boost等，只需要改一下conf文件即可。 Please kindly refer to： examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_conf.json examples/dsl/v2/hetero_linear_regression/test_hetero_linr_multi_host_train_job_dsl.json
> > 
> > 
> > 感谢您的答复，我也觉得应该是这样。只是不知有没有实际部署到生产环境中，2个或更多的 host 方的场景，有没有通信速度等限制问题？谢谢！
> 
> 只要是支持多host的component，目前看是没有速度限制等问题。

感谢您的回答！
