### ISSUE TITLE
fate连接独立的spark集群报错

### ISSUE THREAD

**Issue by energy-blockchian** [FederatedAI/FATE#3745]
fate 1.7使用独立的spark集群报如下的错，No module named 'federatedml'， 但是我在spark集群的所有节点上都能import这个module，

![image](https://user-images.githubusercontent.com/42533434/155919028-d9f9ee23-0eaf-43ee-890b-04c90e86a8b3.png)

**Comment by zhihuiwan** [comment]
spark-env.sh中需要配置：
export PYSPARK_PYTHONPATH=/data/projects/fate/fate/python:/data/projects/fate/fateflow/python
export PYSPARK_DRIVER_PYTHONPATH=/data/projects/fate/fate/python:/data/projects/fate/fateflow/python
