### ISSUE TITLE
特征处理算子在大数据集下运行出现错误

### ISSUE THREAD

**Issue by tarantula-leo** [FederatedAI/FATE#3794]
数据集为Example中的数据集进行复制扩充得到
在两方场景中，量级千、万、十万、百万的数据集上使用相同Pipeline均无问题
请问出现下列问题的原因是什么？
1.	Homo Onehot、Hetero IV TOPK亿级
执行报错：
 
![1](https://user-images.githubusercontent.com/54618933/157405759-6cb8f5f0-4afa-4286-b36e-606d8dbb89d7.png)

2.	Hetero Data Split千万级
执行报错 fateboard面板无提示错误信息：
 
![2](https://user-images.githubusercontent.com/54618933/157405791-22d8923c-1dc3-41fb-98aa-1bff21f585fe.jpg)
![2-2](https://user-images.githubusercontent.com/54618933/157405811-0e5b8f19-07d9-43a0-9050-794551ffd7f2.png)

 
3.	Hetero Pearson千万级
执行报错：
![3](https://user-images.githubusercontent.com/54618933/157405834-8b4096c8-ebd6-4d84-82fe-e826ae113f43.jpg)

**Comment by mgqa34** [comment]
1. 每个partition的数据不能超过16G，如果数据量比较大，需要增大computing_partitions
2. 从时间上看，花了时间超过72小时，fate默认超时时间为72小时，可以在job_parameters里面设置timeout参数，这里问下，使用的是fate哪个版本？
3. 使用的部署方式是容器化部署还是直接源码部署？

**Comment by tarantula-leo** [comment]
> 1. 每个partition的数据不能超过16G，如果数据量比较大，需要增大computing_partitions
> 2. 从时间上看，花了时间超过72小时，fate默认超时时间为72小时，可以在job_parameters里面设置timeout参数，这里问下，使用的是fate哪个版本？
> 3. 使用的部署方式是容器化部署还是直接源码部署？

1. 增大computing_partitions是否就可以执行超过16G的数据？
2. 使用的是1.6版本，纵向数据拆分这里是否可能存在其它问题？在万、十万、百万的运行时间分别是1.30min、2.30min、90min，千万级的也有在20多个小时failed的情况，无报错信息
3. 使用的是源码部署

**Comment by mgqa34** [comment]
1. 这个是要根据数据量来调整，如果不够，可以持续增大
2. 可以看下所有方是否都无报错信息
