### ISSUE TITLE
请问为什么 v1.7.1.1 中DataTransform强制把数据列名改为小写？可以保持原状吗？

### ISSUE THREAD

**Issue by MDGBDGMG** [FederatedAI/FATE#3798]
数据列名在reader中还是大写，到了datatransform就变成了小写
![8cae92f8d3b29e942008320a2bf65cc](https://user-images.githubusercontent.com/45615979/157595249-b0d8936e-228f-4f99-8d44-3e6b8665f687.png)

如果我把代码里的lower()去掉，影响有多大？
![cc8470602917471f175e6b4e39c1870](https://user-images.githubusercontent.com/45615979/157595447-44d83677-82c1-4f80-b06b-794cfe7b3894.png)

**Comment by dylan-fan** [comment]
1.6开始，主要是是对大小写不敏感
