### ISSUE TITLE
Can we use torch backend in HomoNN?

### ISSUE THREAD

**Issue by patricxu** [FederatedAI/FATE#3802]
I have noticed the you have implemented the torch module for HomoNN, but the config_type in Component module is fixed as keras. Can we use the torch backend if we develop the coresponding Component?

**Comment by patricxu** [comment]
@weiwee I have implemented  the torch-backend HomoNN based on FATE 1.6.1. Maybe I can branch it later.

**Comment by weiwee** [comment]
#4058
