### ISSUE TITLE
Add better support for upgrading from older major versions

### ISSUE THREAD

**Issue by wfangchi** [FederatedAI/FATE#3803]
**Is your feature request related to a problem? Please describe.**
For a new major release, some times I am not confident enough to upgrade when I am already running an older version. I am not sure if there are certain steps I need to perform. For example whether I need to change the schema of my db? clean-up any folders? remove or backup any files? etc. ?

**Describe the solution you'd like**

- General and common upgrade guide and script between major releases.
- If necessary, specific guide and script for a specific new major release.
- If necessary, add code changes too to support upgrade scenarios.
- Documentation on the impact of the upgrade (for example, if logs, data, models can preserve, etc.) 

In general, for a new major release, I can follow the guide to upgrade my running instance to the latest version, with as minimal impact as possible.

**Describe alternatives you've considered**
I just deploy the newer version and launch it. And try to fix any errors on the fly.

**Additional context**
I noticed there are already some docs in https://github.com/FederatedAI/FATE/tree/master/deploy/cluster-deploy/upgrade .  We can update them for newer versions and enhance them if they are not complete.

**Comment by JingChen23** [comment]
Hi @jat001 , is there any plan or proposal for the solution of this issue?

**Comment by JingChen23** [comment]
My understanding is: when fate 1.9.0 is released, then kubefate cli 1.4.5 should at least support 1.8 -> 1.9 upgrade.
