### ISSUE TITLE
fate-1.7.2版本，guest方和host方的属性列名称不相同时，执行特定列的分箱操作失败，特征择选操作被卡住，且持续运行，如选择X0、X1列

### ISSUE THREAD

**Issue by zhangle871012** [FederatedAI/FATE#3805]
在fate-1.7.1和fate-1.7.2版本中：
1、guest方和host方的属性列名称不相同时，执行特定列的分箱操作失败，特征择选操作被卡住，且持续运行，如选择X0、X1列；
2、guest方和host方的属性列名称相同时，分箱操作选择特定列，如X0、X1列，则分箱操作和特征择选操作能顺利执行；

**Comment by dylan-fan** [comment]
如果每一方指定特征列进行特征选择，算法参数不要在common设置

**Comment by mgqa34** [comment]
该问题已在fate-v1.8.0进行修复，issue将会关闭
