### ISSUE TITLE
（1.7）版本手写字符识别的案例报错

### ISSUE THREAD

**Issue by davadd** [FederatedAI/FATE#3824]
[ERROR] [2022-03-21 08:01:43,386] [202203210801364997640] [12022:140171217692480] - [task_executor._run_] [line:243]: [Errno loading yaml file config from /examples/data/mnist_train/config.yaml failed:] [Errno 2] No such file or directory: '/examples/data/mnist_train/config.yaml'（在guest端的报错）
[ERROR] [2022-03-21 08:01:43,452] [202203210801364997640] [12019:140426159630144] - [task_executor._run_] [line:243]: [Errno 2] No such file or directory: 'examples/data/mnist_train/images'（host端报错）

我不知道那一步有问题，向您请教，谢谢！

**Comment by talkingwallace** [comment]
应该是没有下载数据

**Comment by davadd** [comment]
数据集现在下载好了，现在报错是缺少yaml，识别不到，我访问该目录是有的，请问什么原因呢







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 下午3:47
收件人: ***@***.***&gt;; 
抄送: "　　Day  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE] （1.7）版本手写字符识别的案例报错 (Issue #3824)





 
应该是没有下载数据
