### ISSUE TITLE
请问未来FATE的docker镜像会添加对linux/arm64的支持吗？

### ISSUE THREAD

**Issue by cifuki** [FederatedAI/FATE#3828]
请问：目前FATE的docker镜像仅支持linux/amd64，在Apple silicon的Mac电脑上无法成功部署，请问未来FATE的docker镜像会添加对linux/arm64的支持吗？谢谢～

**Comment by HHHJiro** [comment]
使用m1芯片docker部署后运行toy和单元测试一直失败

**Comment by huangqihanssh** [comment]
Apple M1 Max 同一样不支持，toy test 和unit test 报错
auto check log failed, please check /data/projects/fate/logs/toy/job_202203300833554452090_log

**Comment by lwx2018** [comment]
请问现在这个问题有解决嘛

**Comment by kanppa** [comment]
https://github.com/kanppa/FATE-ARM64 供参考

**Comment by SquirminatorHotHead** [comment]
https://github.com/FederatedAI/FATE/issues/4584#issuecomment-1541258136
