### ISSUE TITLE
sir-reader_0 table use

### ISSUE THREAD

**Issue by majorinche** [FederatedAI/FATE#3832]
https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/secure_information_retrieval/test_secure_information_retrieval_conf.json

"guest": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "breast_hetero_host",
                            "namespace": "experiment"
                        }
                    },
                    "data_transform_0": {
                        "with_label": false
                    }
                }
            },

请问下，这里guest的reader_0用的数据为什么是breast_hetero_host呢？

**Comment by gxcuit** [comment]
> https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/secure_information_retrieval/test_secure_information_retrieval_conf.json
> 
> "guest": { "0": { "reader_0": { "table": { "name": "breast_hetero_host", "namespace": "experiment" } }, "data_transform_0": { "with_label": false } } },
> 
> 请问下，这里guest的reader_0用的数据为什么是breast_hetero_host呢？

I think it may be a typo in the conf file. I have already mentioned this issue in #3743. Swapping the table name between the host and the guest can solve this problem.

**Comment by dylan-fan** [comment]
https://github.com/FederatedAI/FATE/pull/3744

**Comment by majorinche** [comment]
ok, thank you.

**Comment by nemirorox** [comment]
Hi,  this config file is to demonstrate server(guest) securely retrieves value from client(host). Use of datasets do not have to be restricted here as for other modules. Here we keep the choice of data sets consistent with the [earliest version](https://github.com/FederatedAI/FATE/blob/v1.5.0/examples/dsl/v1/secure_information_retrieval/test_secure_information_retrieval_conf.json).
