### ISSUE TITLE
typo in source code

### ISSUE THREAD

**Issue by hainingzhang** [FederatedAI/FATE#3845]
**Describe the bug**

When I was editing the document, I found a typo in the source code `python/federatedml/param/base_param.py`.

Line 68, 

def check(self):
        raise NotImplementedError("Parameter Object should have be check")

The error message should read:
raise NotImplementedError("Parameter Object should be checked.")

Not a big issue, just rephrase it a bit.

**Comment by mgqa34** [comment]
Fixed in newly pull request. Thanks for pointing out~
