### ISSUE TITLE
Expect a minor version to support only PSI functionality

### ISSUE THREAD

**Issue by excellent-lixl** [FederatedAI/FATE#3854]
Because we are in the process of actual use, the existing exploratory tests are basically only PSI tasks, and further cooperation is possible only after the intersection of the real situation and the real situation is clear.

**Comment by LaynePeng** [comment]
Because the task looks like two parts, so I kept this issue in FATE and added a ref. ticket to KubeFATE for tracking tasks for building images and deploying facilities.

**Comment by JingChen23** [comment]
Hi, what is the timeline of progress for this task?
I'm also confused what will be the exit criteria for this issue.

**Comment by JingChen23** [comment]
Hi @excellent-lixl , after this change, we have reduced the size of 2 images, eggroll and python. And the size of all you need images now are:

### for FATE only images
client: 570 MB
eggroll: 859 MB -> 635 MB
fateboard: 97 MB
python: 815 MB -> 606 MB
kubefate: 20 MB

### for general images
mysql: 147 MB
fluentd: 18 MB
nginx: 199 MB
mariadb: 120 MB

Please notice, the docker images are layer based, so the size is not as big as above.
For example:
eggroll and python are built based on our base image:
This means that there is only one copy of base image needed, which is 479MB.
Then eggroll just need extra 156 MB, python need extra 127MB.

So if you add them up:

479+156+127 (base + eggroll + python) = 762
570+97+20 (client + fateboard + kubefate) = 687 (kubefate is not needed if you use docker-compose)
147+18+199+120 (mysql + fluentd + nginx + mariadb) =484 (maraidb is not needed if you use docker-compose)

762 + 687 + 484 = 1933MB < 2GB

Could we close this issue now?

**Comment by excellent-lixl** [comment]
Please Take A Look
