### ISSUE TITLE
The support of PIR function

### ISSUE THREAD

**Issue by excellent-lixl** [FederatedAI/FATE#3857]
We  have many modeling scenarios which need to use the PIR function, can FATE provide the PIR function in the later versions?

**Comment by dylan-fan** [comment]
you can use SIR component

**Comment by 15210831009** [comment]
But I use SIR component，now its performance cannot meet our demand.I know some company has developed another engine to support PIR,whether FATE can provide realtime PIR function.

**Comment by yellow123Nike** [comment]
请问sir组件的性能是否有提供
