### ISSUE TITLE
Hope FATE provides detailed performance report about Eggroll

### ISSUE THREAD

**Issue by Answerfxy** [FederatedAI/FATE#3867]
Based on domain knowledge, FATE has two computing engines, Spark and Eggroll.
Spark has a performance report available. However, we couldn't find the corresponding report of Eggroll.
Could you provide such a report of Eggroll?

**Comment by dylan-fan** [comment]
where is  a performance report of spark?

**Comment by dylan-fan** [comment]
Liu Y, Fan T, Chen T, et al. FATE: An industrial grade platform for collaborative learning with data protection[J]. Journal of Machine Learning Research, 2021, 22(226): 1-6

This paper has a performance report for fate on eggroll
