### ISSUE TITLE
是否能提供获取所有  t_storage_table_meta 数据接口 和 all partyid (route_table.json) 接口

### ISSUE THREAD

**Issue by baiguidong** [FederatedAI/FATE#3882]
**Is your feature request related to a problem? Please describe.**
通过服务能够获取所有输入输出表信息，以及party 信息，方便页面编排选择party

**Comment by zhihuiwan** [comment]
/table/list可以获取某个job的输入输出表信息，可参考接口文档：https://federatedai.github.io/FATE-Flow/1.8.0/swagger/

**Comment by baiguidong** [comment]
感谢，现在按照获取所有 job 然后 调用 /table/list
