### ISSUE TITLE
sh init.sh start failed

### ISSUE THREAD

**Issue by liuyuqinggg** [FederatedAI/FATE#3884]
**Describe the bug**
when I run the sh init.sh start，it report failed like below picture, somebody can help me?

![F$TG@K8V VFJ7I6OM2(RLDO](https://user-images.githubusercontent.com/46989662/162599473-4cd53564-bd6b-446f-a44f-2307a5d3f15c.png)
![UBS66TP7%XZ4BICJF9W{L@P](https://user-images.githubusercontent.com/46989662/162599475-27b7f34c-34b3-45b6-ae6a-3ba1a7af6e14.png)

**Comment by dylan-fan** [comment]
pip install grpc

**Comment by SennriSyunnga** [comment]
It means you failed to install grpc module when you installed Fate somehow,  you can check the install log to make sure whether other modules has been installed successfully.
You can active virtual env then execute pip install grpc to manually complete the installing process as mentioned above.
