### ISSUE TITLE
超大文件在reader_0阶段发生out of memory异常被系统killed

### ISSUE THREAD

**Issue by sunshine920103** [FederatedAI/FATE#3887]
**Describe the bug**
fate版本 1.7.2 ，底层引擎选用spark+hdfs
一个1.5T大小的csv文件在hdfs上，通过table bind的方式绑定到fate的表中，然后在实际计算时，reader_0阶段，
观察到python进程会读取整个文件大小，不停的吃内存，直到最后占满服务器内存，被系统killed。

通过跟踪代码发现，是在/python/fate_arch/storage/hdfs/_table.py中，
def _as_generator(self):函数代码有问题：

with io.TextIOWrapper(buffer=self._hdfs_client.open_input_stream(self.path), encoding="utf-8") as reader:

通过pyarrow的open_input_stream读取，会加载整个文件，导致在文件大小超过系统内存时，会占满服务器内存，被系统killed。

**Comment by sunshine920103** [comment]
我已经尝试解决，并实际运行通过，解决了这个bug。是否可以发起一个PR，贡献代码？

**Comment by dylan-fan** [comment]
欢迎pr给FATE，建议在正式pr前，说明下拟解决方案，方便评估。

**Comment by dylan-fan** [comment]
我们这周会发布1.8版本，如果需要pr的，请尽快

**Comment by sunshine920103** [comment]
解决方案如下：
   1.注释掉原代码段：
            # with io.TextIOWrapper(
            #         buffer=self._hdfs_client.open_input_stream(self.path), encoding="utf-8"
            # ) as reader:
            #     for line in reader:
            #         yield line
2. 更新代码块为：
            content_pipe = subprocess.Popen(["hdfs", "dfs", "-cat", self.path], stdout=subprocess.PIPE)
            for line in content_pipe.stdout:
                yield line.decode(encoding="utf-8")
实测reader阶段顺利完成，测试数据5亿+，数据大小1.5T。内存影响很小，不会无限增加。

**Comment by zhihuiwan** [comment]
非常感谢你提的解决方案，这种方案确实是可以解决这个问题，但是有以下问题：
1. 这里采用调系统命令读取文件不太合理，而且如果系统中没配置hadoop环境变量(这个操作fate不太care)就读取不到数据。
2. 新启进程方式会引入进程维护问题
fate hdfs table采用的是pyarrow接口操作hdfs，目前看pyarrow官网文档显示还未实现pyarrow.NativeFile的readline和readlines方法，后续版本我们会优化这个问题。

**Comment by sunshine920103** [comment]
是的，这是个比较折中的方案，我目前发现reader中的count操作，还有接下来的copy table 复制数据到hdfs中的操作，都是走的这个pyarrow 的输入输出流，这种单线程机制感觉应付大数据量还是太耗时了。
我在想是否可以底层改成spark来处理？
如果有这方面的考虑的话，我乐意来做这部分的开发工作

**Comment by zhihuiwan** [comment]
当前这里的操作其实是fate的存储操作，不适合使用spark来处理。如果你有好的点子，欢迎pr给FATE，非常感谢！
