### ISSUE TITLE
fateboard system error in standalone deploy mode

### ISSUE THREAD

**Issue by patricxu** [FederatedAI/FATE#3894]
my fateboard error.log shows it might be some error about the database. 
![image](https://user-images.githubusercontent.com/9252137/162917935-a7d8aa59-d5d9-4261-9ff8-60875a1344d6.png)

However I have set the   conf/application.properties according to the [guide](https://github.com/FederatedAI/FATE-Board/tree/0c4f24c860f2e814e563faffd10a15183d0eaede)'s database configuration and my setting is 
![image](https://user-images.githubusercontent.com/9252137/162919117-56d05865-7514-4cc8-9ff5-200b2f589afe.png)

I am sure there are some valid records in fate_sqlite.db. Why I still get the error?
THX

**Comment by sy0507** [comment]
Have you solved this problem? Can you teach me if it's solved? esteem it a favor
