### ISSUE TITLE
a bug from pipeline method _get_task_inst

### ISSUE THREAD

**Issue by jinjiel1994** [FederatedAI/FATE#3922]
**Describe the bug**
In the file /data/projects/fate/fate/python/fate_client/pipeline/backend/pipeline.py
Line 267 raise ValueError(f"Component {component} does not exist")
While the component is None, the error message {component} should have been {name}.

**Expected behavior**
While encountering this error, the output message should print the name of the component (which should be the param name) instead of the None param component.

**Comment by mgqa34** [comment]
Yes, you're right, this warning message is confusing. Can you fix it and make a pull request ?
