### ISSUE TITLE
[WIP]implement algorithm multi-party addition-subtraction-multiplication-division

### ISSUE THREAD

**Issue by wanglg007** [FederatedAI/FATE#3925]
(1)New Algorithm
The algorithm is implemented according to the requirements of the Research Institute. It is required to realize multi-party addition, subtraction, multiplication and division
本算法根据研究院的要求进行实现。要求实现多方的加法、减法、乘法、除法。

- Name:        hetero_arithmetic
- Category:   param = { "operator_method": "+",      "operator_type": "int64"    }

(2)Short Description
Operator of this algorithm_ Methods include + - * / operators_ Type includes Int64 and float64;
本算法的operator_method包括+、-、*、/四种，operator_type包括int64和float64两种类型；

(3)WIP
(3.1)主要代码
(3.1.1)在FATE\python\federatedml里面创建arithmetic package，并将homo_arithmetic.py文件上传到该目录。
[homo_arithmetic.txt](https://github.com/FederatedAI/FATE/files/8528205/homo_arithmetic.txt)

(3.1.2)在FATE\python\federatedml\components里面上传homo_arithmetic.py文件。
[homo_arithmetic.txt](https://github.com/FederatedAI/FATE/files/8528209/homo_arithmetic.txt)

(3.1.3)在FATE\python\federatedml\param里面上传arithmetic_param.py文件，并更新__init__.py文件。其中__init.py里面添加内容如下：
<1>引入参数包文件
from federatedml.param.arithmetic_param import ArithmeticParam
<2>在__all__里面添加参数
"ArithmeticParam",
<3>文件
[arithmetic_param.txt](https://github.com/FederatedAI/FATE/files/8527991/arithmetic_param.txt)

(3.1.4)在FATE\python\federatedml\transfer_variable\transfer_class里面添加homo_arithmetic_transfer_variable.py
[homo_arithmetic_transfer_variable.txt](https://github.com/FederatedAI/FATE/files/8528227/homo_arithmetic_transfer_variable.txt)

(3.1.5)在FATE\python\fate_client\pipeline\component里面添加homo_arithmetic.py文件；并更新__init__.py文件；
<1>引入参数包文件
from pipeline.component.homo_arithmetic import HomoArithmetic
<2>在__all__里面添加参数
"HomoArithmetic"
<3>文件
[homo_arithmetic.txt](https://github.com/FederatedAI/FATE/files/8528234/homo_arithmetic.txt)

(3.1.6)在FATE\python\fate_client\pipeline\param里面添加arithmetic_param.py文件，并更新__init__.py文件
<1>引入参数包文件
from pipeline.param.arithmetic_param import ArithmeticParam
<2>在__all__里面添加参数
"ArithmeticParam"
<3>文件
[arithmetic_param.txt](https://github.com/FederatedAI/FATE/files/8528087/arithmetic_param.txt)

(3.1.7)在FATE\examples\data目录里面添加两个数据文件：
[arithmetic_guest.csv](https://github.com/FederatedAI/FATE/files/8528099/arithmetic_guest.csv)
[arithmetic_host.csv](https://github.com/FederatedAI/FATE/files/8528100/arithmetic_host.csv)

(3.1.8)在FATE\examples\pipeline里面添加python package，名字为arithmetic。添加pipeline文件pipeline-arithmetic-multi-host.py
[pipeline-arithmetic-multi-host.txt](https://github.com/FederatedAI/FATE/files/8528257/pipeline-arithmetic-multi-host.txt)

(3.1.9)该版本基于1.7.2进行测试，测试结果通过上面的pipeline可以直接打印出结果；

(4)Check and Acceptance 
- [ ] PR
  - [ ] add reviewer: @mgqa34 @dylan-fan 
  - [ ] add assigner
  - [ ] add labels
  - [ ] link projects
  - [ ] link this issue

- [ ] Confirm `Params` consistent between `federatedml` and `pipeline`
- [ ] Examples tested

**Comment by mgqa34** [comment]
It seems that no secure multi-party computing protocol is used in the code, just plaintext computation?  It's not secure enough.
