### ISSUE TITLE
Provide federatedai/client image dockerfile

### ISSUE THREAD

**Issue by wanglg007** [FederatedAI/FATE#3927]
**Is your feature request related to a problem? Please describe.**
After adding a new algorithm in fat, you need to update the corresponding federatedai / client image to interact with the outside world, but the image generation method has not been found in the project.
在FATE里面添加新算法后，需要更新相应的federatedai/client镜像才能与外界进行交互，但在项目工程中暂未发现该镜像生成方式。

**Describe the solution you'd like**
Add the generation method of the image in the fat / build / docker build directory and provide the corresponding dockefile.
在FATE/build/docker-build目录里面添加该镜像的生成方式，并提供相应的DockeFile.

**Comment by wanglg007** [comment]
client dockerfile在kubefate工程里面

**Comment by danna88** [comment]
你好，我也有这个疑问，请问你说的dockerfile具体在哪儿？我在kubefate也没找到呀？

> client dockerfile在kubefate工程里面
