### ISSUE TITLE
The FATE restful api interface documentation is too simple, hope to supplement the calling examples.

### ISSUE THREAD

**Issue by excellent-lixl** [FederatedAI/FATE#3935]
For example, cpn_list in /v1/model/deploy, what is an array-like string?

**Comment by gxcuit** [comment]
Same request, please kindly refer to https://github.com/FederatedAI/FATE-Flow/issues/222

If possible, may I make a PR?

**Comment by jat001** [comment]
where did "an array-like string" come from?

**Comment by zhihuiwan** [comment]
we are adding, and welcome PR
