### ISSUE TITLE
fate flow sdk  AttributeError: 'str' object has no attribute 'pop'

### ISSUE THREAD

**Issue by caihy05** [FederatedAI/FATE#3937]
**Describe the bug**
flow_sdk.zh.md文档的dsl和conf路径说的不准确

**To Reproduce**
`    client = FlowClient('127.0.0.1', 9380, 'v1')
    # jobs = client.data.upload_history(limit=10, job_id=None)
    # print(jobs)
    # conf_path = r"D:\workspace\src\LSFM\data\upload_conf.json"  # 直接写路径不正确
    conf_path = {
        "file": "D:\\workspace\\src\\LSFM\\data\\breast_hetero_guest.csv",
        "id_delimiter": ",",
        "table_name": "breast_hetero_guest",
        "namespace": "experiment",
        "head": 1,
        "partition": 8
    }
    jobs = client.data.upload(conf_path, verbose=0, drop=1)
    print(jobs)`

**Comment by zhihuiwan** [comment]
sdk client.data.upload接口文档问题，我们会尽快修复， 感谢纠正！

**Comment by qinghe-jingxing** [comment]
目前flow_sdk.client的FlowClient,需要conf_path路径的job.submit、data.upload目前还是只能解析读取的json字典，不能解析string路径吗
