### ISSUE TITLE
update job status does not take effect

### ISSUE THREAD

**Issue by NookLook2014** [FederatedAI/FATE#3940]
执行**两方**的纵向逻辑回归，在Schedule Log里面报如下错误，但是仍然能够成功执行。不过，执行**三方**的纵向逻辑回归时就卡在HeteroLR: hetero_lr_0处失败，没有其他报错日志，也是只有如下的调度日志报错。
使用的时Ansible部署的Exchange模式下的FATE1.7.0,算法代码也是很简单的reader、transform、intersection和heteroLR，请问有遇到过这个问题的么？

1
[ERROR] [2022-04-26 10:38:17,694] [202204261038075892820] [2313:140654841952000] - [federated_scheduler.task_command] [line:246]: failed to execute federated task reader_0 command(status/running) detail: 
2
{'guest': {'211': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}, 'host': {'212': {'retcode': 0, 'retmsg': 'success'}}}
3
[ERROR] [2022-04-26 10:38:48,420] [202204261038075892820] [2313:140654841952000] - [federated_scheduler.task_command] [line:246]: failed to execute federated task data_transform_0 command(status/running) detail: 
4
{'guest': {'211': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}, 'host': {'212': {'retcode': 0, 'retmsg': 'success'}}}
5
[ERROR] [2022-04-26 10:39:16,409] [202204261038075892820] [2313:140654841952000] - [federated_scheduler.task_command] [line:246]: failed to execute federated task intersection_0 command(status/running) detail: 
6
{'guest': {'211': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}, 'host': {'212': {'retcode': 0, 'retmsg': 'success'}}}
7
[ERROR] [2022-04-26 10:39:57,652] [202204261038075892820] [2313:140654841952000] - [federated_scheduler.task_command] [line:246]: failed to execute federated task hetero_lr_0 command(status/running) detail: 
8
{'arbiter': {'212': {'retcode': 0, 'retmsg': 'success'}}, 'guest': {'211': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}, 'host': {'212': {'retcode': 0, 'retmsg': 'success'}}}
9
[ERROR] [2022-04-26 11:02:42,247] [202204261038075892820] [2313:140654841952000] - [federated_scheduler.task_command] [line:246]: failed to execute federated task evaluation_0 command(status/running) detail: 
10
{'arbiter': {'212': {'retcode': 0, 'retmsg': 'success'}}, 'guest': {'211': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}, 'host': {'212': {'retcode': 0, 'retmsg': 'success'}}}

查看Host的调度日志，会出现如下错误：
1312
Traceback (most recent call last):
1313
  File "./fate/fateflow/python/fate_flow/manager/worker_manager.py", line 293, in kill_task_all_workers
1314
    cls.kill_worker(worker_info)
1315
  File "./fate/fateflow/python/fate_flow/manager/worker_manager.py", line 303, in kill_worker
1316
    process = psutil.Process(worker_info.f_run_pid)
1317
  File "./fate/common/python/venv/lib/python3.6/site-packages/psutil/__init__.py", line 326, in __init__
1318
    self._init(pid)
1319
  File "./fate/common/python/venv/lib/python3.6/site-packages/psutil/__init__.py", line 367, in _init
1320
    raise NoSuchProcess(pid, None, msg)
1321
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 31067
1322
[INFO] [2022-04-26 12:10:45,490] [202204261206089786280] [8584:140317630121728] - [worker_manager.kill_task_all_workers] [line:299]: task 202204261206089786280_reader_0 0 kill all workers successfully on host 213

**Comment by zhihuiwan** [comment]
这些调度日志其实是warn,在后面版本我们有优化。请问下“逻辑回归时就卡在HeteroLR“的现象具体是怎样的？task状态一直处于running吗

**Comment by NookLook2014** [comment]
> 这些调度日志其实是warn,在后面版本我们有优化。请问下“逻辑回归时就卡在HeteroLR“的现象具体是怎样的？task状态一直处于running吗

具体现象就是：
1、同样的三方数据，我如果任选两方用HeteroLR，可以执行成功，也出行上面的warn日志；如果三方联合训练，在HeteroLR组件这里iter=0的时候就task就失败了，日志里面依然只有那些，看不到错误信息。
2、我又换了新的三方的数据集，用HeteroLR训练，依然失败；
3、另外，如果我用SBT拿同样的数据进行三方联合是可以成功训练模型的。

**Comment by zhihuiwan** [comment]
能贴一下conf和dsl看看吗

**Comment by NookLook2014** [comment]
> 能贴一下conf和dsl看看吗

conf：
{
    "dsl_version": 2,
    "initiator": {
        "role": "guest",
        "party_id": 211
    },
    "role": {
        "arbiter": [
            212
        ],
        "host": [
            10000,
            212
        ],
        "guest": [
            211
        ]
    },
    "job_parameters": {
        "common": {
            "job_type": "train",
            "computing_engine": "EGGROLL",
            "engines_address": {},
            "federated_mode": "MULTIPLE",
            "task_parallelism": 1,
            "computing_partitions": 4,
            "federated_status_collect_type": "PUSH",
            "model_id": "arbiter-212#guest-211#host-212_10000#model",
            "model_version": "202204261529198849290",
            "auto_retries": 0,
            "auto_retry_delay": 1,
            "eggroll_run": {},
            "spark_run": {},
            "rabbitmq_run": {},
            "pulsar_run": {},
            "adaptation_parameters": {
                "task_nodes": 1,
                "task_cores_per_node": 4,
                "task_memory_per_node": 0,
                "request_task_cores": 4,
                "if_initiator_baseline": true
            }
        }
    },
    "component_parameters": {
        "role": {
            "host": {
                "0|1": {
                    "data_transform_0": {
                        "with_label": false
                    }
                },
                "1": {
                    "reader_0": {
                        "table": {
                            "name": "212_edu_data",
                            "namespace": "partner"
                        }
                    }
                },
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "10000_civil_data",
                            "namespace": "partner"
                        }
                    }
                }
            },
            "guest": {
                "0": {
                    "data_transform_0": {
                        "with_label": true,
                        "label_name": "default.payment.next.month"
                    },
                    "reader_0": {
                        "table": {
                            "name": "211_credit_train",
                            "namespace": "partner"
                        }
                    }
                }
            }
        },
        "common": {
            "hetero_lr_0": {
                "batch_size": 5000,
                "learning_rate": 0.001,
                "max_iter": 3,
                "encrypted_mode_calculator_param": {
                    "mode": "fast"
                }
            },
            "evaluation_0": {
                "eval_type": "binary"
            }
        }
    }
}


dsl：
{
    "components": {
        "reader_0": {
            "module": "Reader",
            "output": {
                "data": [
                    "data"
                ]
            },
            "provider": "fate_flow@1.7.0"
        },
        "data_transform_0": {
            "module": "DataTransform",
            "input": {
                "data": {
                    "data": [
                        "reader_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ],
                "model": [
                    "model"
                ]
            },
            "provider": "fate@1.7.0"
        },
        "intersection_0": {
            "module": "Intersection",
            "input": {
                "data": {
                    "data": [
                        "data_transform_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ],
                "cache": [
                    "cache"
                ]
            },
            "provider": "fate@1.7.0"
        },
        "hetero_lr_0": {
            "module": "HeteroLR",
            "input": {
                "data": {
                    "data": [
                        "intersection_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ],
                "model": [
                    "model"
                ]
            },
            "provider": "fate@1.7.0"
        },
        "evaluation_0": {
            "module": "Evaluation",
            "input": {
                "data": {
                    "data": [
                        "hetero_lr_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ]
            },
            "provider": "fate@1.7.0"
        }
    }
}

流程图为：
![image](https://user-images.githubusercontent.com/15016772/165889911-4e854732-aaa1-4a5f-bb5c-d88ad62be66d.png)

日志到截图位置就没了：
![image](https://user-images.githubusercontent.com/15016772/165889964-68c05db2-3c3a-480b-a25f-6190d4c055d4.png)

**Comment by mgqa34** [comment]
Hetero-SSHE-LR does not support multi-host，it will raise error in later version like fate-1.8
https://github.com/FederatedAI/FATE/blob/v1.8.0/python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_model.py#L217
![image](https://user-images.githubusercontent.com/13565267/165896395-492d8df8-d370-4cea-bedc-91539e05b417.png)

**Comment by Acecai** [comment]
when i train hetero model with 3 partys, I meet the same problem with fate v1.7.2
