### ISSUE TITLE
fate1.7.1之后的版本，执行intersect交集计算的结果不会在fateboard上展示

### ISSUE THREAD

**Issue by zdh252927993** [FederatedAI/FATE#3943]
**Describe the bug**
fate1.7.1之后的版本，执行intersect交集计算的结果不会在fateboard上展示。
但是执行HETERO_LR等其他包含intersect的作业时，intersect组件会展示结果。

**To Reproduce**
1. 发起intersect任务
curl --location --request POST 'http://10.10.196.217:9380/v1/job/submit' \
--header 'User-Agent: Apipost client Runtime/+https://www.apipost.cn/' \
--header 'Content-Type: application/json' \
--data '{"job_dsl":{"components":{"data_transform_0":{"input":{"data":{"data":["reader_0.data"]}},"module":"DataTransform","output":{"data":["data"]}},"intersect_0":{"input":{"data":{"data":["data_transform_0.data"]}},"module":"Intersection","output":{"data":["data"]}},"reader_0":{"module":"Reader","output":{"data":["data"]}}}},"job_runtime_conf":{"component_parameters":{"common":{"intersect_0":{"intersect_method":"rsa","only_output_key":true,"rsa_params":{"final_hash_method":"sha256","hash_method":"sha256","key_length":2048,"split_calculation":false},"sync_intersect_ids":false}},"role":{"guest":{"0":{"data_transform_0":{"output_format":"dense","with_label":false},"reader_0":{"table":{"name":"breast_hetero_guest","namespace":"experiment"}}}},"host":{"0":{"data_transform_0":{"output_format":"dense","with_label":false},"reader_0":{"table":{"name":"breast_hetero_host","namespace":"experiment"}}}}}},"dsl_version":2,"initiator":{"party_id":9999,"role":"guest"},"role":{"guest":[9999],"host":[9999]}}}'
2. 登录partyId为9999的fateboard，点击JOBS，待相应job完成。
3. 进入guest对应的job详情页，点击intersect_0 -> view the outputs -> data output
4. 页面中没有展示任何数据
![image](https://user-images.githubusercontent.com/52805841/165248045-8750bb82-d083-4325-96eb-09c2f551d1b9.png)

**Expected behavior**
1.7.0版本中会展示如下内容
![image](https://user-images.githubusercontent.com/52805841/165247950-7f1883cd-25d6-444c-8c1c-8b81a14be672.png)

**Screenshots**
请求data的响应中是有数据的，但header是空，导致页面不展示
![image](https://user-images.githubusercontent.com/52805841/165248637-eed24b4a-ebbd-407d-8c48-e06c1b09bfdd.png)

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Browser：chrome

**Comment by SennriSyunnga** [comment]
Because of `"sync_intersect_ids":false`？
The description is:
```
In rsa, 'sync_intersect_ids' is True means guest or host will send intersect results to the others, and False will not.
```
To be honest, I am not sure……
