### ISSUE TITLE
Question about Hetero-LR on guest side sum operation

### ISSUE THREAD

**Issue by toufunao** [FederatedAI/FATE#3952]
When I looked into the code, I felt confused about the following question.
![image](https://user-images.githubusercontent.com/39375136/165746145-750857ec-6731-4eb5-b87b-ee70255d7fbf.png)
Fore_gradient just added the host_forward. But host_forward was encrypted and fore_gradient is plaintext, it was different from the paper. I wondered if I had a wrong understanding.

Thanks a lot if u can give some suggestions.

**Comment by toufunao** [comment]
The code was substracted from class Guest in /federatedml/optim/gradient/hetero_linear_model_gradient.py .

**Comment by SennriSyunnga** [comment]
I remember that they just overwrite the function of  `+`  operation between Paillier-Encrypted number and plaintext.
