### ISSUE TITLE
exclusive_data_type 貌似没有生效

### ISSUE THREAD

**Issue by NookLook2014** [FederatedAI/FATE#3953]
FATE 1.7.0版本，定义Transform指定了exclusive_data_type ，如下所示：
data_transform_0= DataTransform(name="data_transform_0")
data_transform_0.get_party_instance(role='guest', party_id=guest)\
        .component_param(with_label=True, label_name="y", output_format="dense", exclusive_data_type={'CODE_GENDER':'str'}) 
其中，CODE_GENDER列为包含M和F的字符串。
执行时报错，错误信息为：
### ValueError: could not convert string to float: 'M'
991
992
During handling of the above exception, another exception occurred:
993
994
Traceback (most recent call last):
995
  File "./fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper
996
    return func(*args, **kw)
997
  File "./fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 414, in run_task
998
    self._run_binary(merge_join_wrapper, task)
999
  File "./fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 161, in _run_binary
1000
    raise EnvironmentError("exec task:{} error".format(task), e)
1001
OSError: [Errno exec task:<ErTask(id=202204291747444663880_data_transform_0_1_guest_211-py-job-20220429.174952.276598_join-task-0, name=join, inputs=[<ErPartition(id=0, store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=202204291747444663880_data_transform_0_1_guest_211, name=783a1f68c7a111ec8dfa5254004cb936_20220429.174950.283606.1, path=, total_partitions=4, partitioner=, serdes=) at 0x7f7e322e7828>, processor=<ErProcessor(id=3561, server_node_id=2, name=, processor_type=egg_pair, status=RUNNING, command_endpoint=<ErEndpoint(host=xxx.xxx, port=34053) at 0x7f7e322e7860>, transfer_endpoint=<ErEndpoint(host=xxx.xxx, port=35859) at 0x7f7e322e7ac8>, pid=7690, options=[{}], tag=) at 0x7f7e322e7b00>, rank_in_node=-1) at 0x7f7e322e7780>, <ErPartition(id=0, store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=202204291747444663880_data_transform_0_1_guest_211, name=783a1f68c7a111ec8dfa5254004cb936_20220429.174952.039342.2, path=, total_partitions=4, partitioner=, serdes=) at 0x7f7e322e7940>, processor=<ErProcessor(id=3561, server_node_id=2, name=, processor_type=egg_pair, status=RUNNING, command_endpoint=<ErEndpoint(host=xxx.xxx, port=34053) at 0x7f7e322e7978>, transfer_endpoint=<ErEndpoint(host=xxx.xxx, port=35859) at 0x7f7e322e7198>, pid=7690, options=[{}], tag=) at 0x7f7e322e7400>, rank_in_node=-1) at 0x7f7e322e73c8>], outputs=[<ErPartition(id=0, store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=202204291747444663880_data_transform_0_1_guest_211, name=783a1f68c7a111ec8dfa5254004cb936_20220429.174952.276732.1, path=, total_partitions=4, partitioner=, serdes=) at 0x7f7e322e7a58>, processor=<ErProcessor(id=3561, server_node_id=2, name=, processor_type=egg_pair, status=RUNNING, command_endpoint=<ErEndpoint(host=xxx.xxx, port=34053) at 0x7f7e322e7a90>, transfer_endpoint=<ErEndpoint(host=xxx.xxx, port=35859) at 0x7f7e322e7cf8>, pid=7690, options=[{}], tag=) at 0x7f7e322e7fd0>, rank_in_node=-1) at 0x7f7e322e79b0>], job=<ErJob(id=202204291747444663880_data_transform_0_1_guest_211-py-job-20220429.174952.276598_join, name=join, inputs=[<ErStore(store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=202204291747444663880_data_transform_0_1_guest_211, name=783a1f68c7a111ec8dfa5254004cb936_20220429.174950.283606.1, path=, total_partitions=4, partitioner=, serdes=) at 0x7f7e322e7748>, partitions=[***, len=4], options=[{}]) at 0x7f7e322e7240>, <ErStore(store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=202204291747444663880_data_transform_0_1_guest_211, name=783a1f68c7a111ec8dfa5254004cb936_20220429.174952.039342.2, path=, total_partitions=4, partitioner=, serdes=) at 0x7f7e322e7710>, partitions=[***, len=4], options=[{}]) at 0x7f7e1008cb00>], outputs=[<ErStore(store_locator=<ErStoreLocator(id=0, store_type=IN_MEMORY, namespace=202204291747444663880_data_transform_0_1_guest_211, name=783a1f68c7a111ec8dfa5254004cb936_20220429.174952.276732.1, path=, total_partitions=4, partitioner=, serdes=) at 0x7f7e1008cef0>, partitions=[***, len=4], options=[{}]) at 0x7f7e1008ce10>], functors=[1], options={}) at 0x7f7e322e7a20>) at 0x7f7e322e7d30> error] could not convert string to float: 'M'
1033
1034
During handling of the above exception, another exception occurred:
1035
1036
Traceback (most recent call last):
1037
  File "./fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper
1038
    return func(*args, **kw)
1039
  File "./fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 414, in run_task
1040
    self._run_binary(merge_join_wrapper, task)
1041
  File "./fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 161, in _run_binary
1042
    raise EnvironmentError("exec task:{} error".format(task), e)

**Comment by mgqa34** [comment]
Please change {'CODE_GENDER':'str'} to {'code_gender':'str'}, and test again. This maybe a bug because column names are changing to lowercases, but names in exclusive_data_type  are not.

**Comment by NookLook2014** [comment]
Ok, tks!
