### ISSUE TITLE
单机版的1.7.0安装包的网址改变了吗

### ISSUE THREAD

**Issue by davadd** [FederatedAI/FATE#3955]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mgqa34** [comment]
Please refer to fate-v1.7.0' s [standalone deployment document](https://github.com/FederatedAI/FATE/tree/v1.7.0/deploy/standalone-deploy)

**Comment by davadd** [comment]
wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/${version}/release/standalone_fate_docker_image_${version}_release.tar.gz
--2022-05-01 01:02:11--  https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/1.7.0/release/standalone_fate_docker_image_1.7.0_release.tar.gz
Resolving webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)... 112.49.57.176, 112.49.57.186, 112.49.57.185, ...
Connecting to webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)|112.49.57.176|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-01 01:02:11 ERROR 404: Not Found.

**Comment by davadd** [comment]
用windows打开网址也是错误的

**Comment by mgqa34** [comment]
Please  read the document carefully, the link is https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/1.7.0/release/standalone_fate_docker_image_1.7.0_release.tar, without ".gz" in the end

**Comment by davadd** [comment]
thanks
