### ISSUE TITLE
Error in running flow job submit (FATE/examples/dsl/v2/hetero_secureboost)

### ISSUE THREAD

**Issue by EudaldJuvanteny** [FederatedAI/FATE#3956]
I followed the Standalone deployment and i pass all tests.
Now I'm trying to execute some tests of your examples but there is an error. Can you help me please?
https://github.com/FederatedAI/FATE/tree/master/examples/dsl/v2/hetero_secureboost

![image](https://user-images.githubusercontent.com/104132653/166326410-01b99531-adec-42b7-ae9d-9186068af238.png)

On other hand, how could I test some algorithms like heterosecureboost with my own dataset?

Regards

**Comment by meijiu** [comment]
it seems like you're in the `fate` folder when you run the job submit command. for your `--dsl-path`, you need to include the path to the json file. `test_secureboost_train_dsl.json` is inside `/data/projects/fate/examples/dsl/v2/hetero_secureboost`.
