### ISSUE TITLE
fate 集群版安装后，toy单边案例测试不通过

### ISSUE THREAD

**Issue by mpmiles** [FederatedAI/FATE#3959]
安装的是fate原生版集群。在虚拟机内存14g，集群部署完毕后，服务正常启动，fateboard启动正常，测试test toy 单边案例，一直在 wating，然后就超时。日志查看不出错误信息。有没有大佬遇到这种问题的，帮忙指点一下。

**Comment by mgqa34** [comment]
是单台机器还是两个party_id？这里的waiting指的是任务已经提交上去了但job状态waiting，还是说任务提交不上去，一直卡住到超时？

**Comment by mpmiles** [comment]
> 是单台机器还是两个party_id？这里的waiting指的是任务已经提交上去了但job状态waiting，还是说任务提交不上去，一直卡住到超时？

单台机器部署的单party，测试的是自带的flow test toy -gid 9999 -hid 9999 案例，任务应该是已经提交上去了，在fateboard是有这个jobid的，下边是部分job日志
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
toy test job 202205060956109945590 is waiting
check job status timeout
auto check log failed, please check /data/projects/fate/logs/toy/job_202205060956109945590_log

**Comment by mgqa34** [comment]
怀疑是资源申请的问题，总核数<4，toy里面默认使用的资源配置是2核/party，所以需要的总资源是4核。可以看下fateflow/$jobid/下面的schedule日志，确认下guest\host是不是有一方资源申请成功，一边没成功

或者跑toy的时候--task-cores 1看下能否成功（注意先停掉已有的waiting任务）

**Comment by mpmiles** [comment]
> 怀疑是资源申请的问题，总核数<4，toy里面默认使用的资源配置是2核/party，所以需要的总资源是4核。可以看下fateflow/$jobid/下面的schedule日志，确认下guest\host是不是有一方资源申请成功，一边没成功
> 
> 或者跑toy的时候--task-cores 1看下能否成功（注意先停掉已有的waiting任务）

**Comment by mgqa34** [comment]
> > 怀疑是资源申请的问题，总核数<4，toy里面默认使用的资源配置是2核/party，所以需要的总资源是4核。可以看下fateflow/$jobid/下面的schedule日志，确认下guest\host是不是有一方资源申请成功，一边没成功
> > 或者跑toy的时候--task-cores 1看下能否成功（注意先停掉已有的waiting任务）

是否还有其他问题呢？ 没的话该issue将会关闭

**Comment by mpmiles** [comment]
> > > 怀疑是资源申请的问题，总核数<4，toy里面默认使用的资源配置是2核/party，所以需要的总资源是4核。可以看下fateflow/$jobid/下面的schedule日志，确认下guest\host是不是有一方资源申请成功，一边没成功
> > > 或者跑toy的时候--task-cores 1看下能否成功（注意先停掉已有的waiting任务）
> 
> 是否还有其他问题呢？ 没的话该issue将会关闭

已经解决，谢谢。我现在关闭

**Comment by oceanqdu** [comment]
您好，我也遇到了这个问题，fate 集群版安装后，toy单边案例测试不通过，
![6a47e761e71206ab6a95823cab9a76b](https://user-images.githubusercontent.com/49178688/179195007-b2b0029d-b90a-4f0f-bd34-8417abe0708c.png)
根据提示打开日志显示
![96b89eade4df4d141139e986c0f40a9](https://user-images.githubusercontent.com/49178688/179195062-41a28724-e7b0-45e1-a159-ab7b1f74388e.png)
看schedule日志里任务也提交成功了
![b25f46a0c9c017dee6a578dd2093880](https://user-images.githubusercontent.com/49178688/179195119-d0d3cefd-3b0a-48bd-9f92-3a680ee0b630.png)

**Comment by mpmiles** [comment]
> 您好，我也遇到了这个问题，fate 集群版安装后，toy单边案例测试不通过， ![6a47e761e71206ab6a95823cab9a76b](https://user-images.githubusercontent.com/49178688/179195007-b2b0029d-b90a-4f0f-bd34-8417abe0708c.png) 根据提示打开日志显示 ![96b89eade4df4d141139e986c0f40a9](https://user-images.githubusercontent.com/49178688/179195062-41a28724-e7b0-45e1-a159-ab7b1f74388e.png) 看schedule日志里任务也提交成功了 ![b25f46a0c9c017dee6a578dd2093880](https://user-images.githubusercontent.com/49178688/179195119-d0d3cefd-3b0a-48bd-9f92-3a680ee0b630.png)

可能是资源问题，我把虚拟机核数和内存扩大之后问题就解决了，参考上边其他人的回复

**Comment by Arrebooool** [comment]
为什么我的(venv) [app@vm_0_2_centos 2024-06-03]$ flow test toy gid 9999 hid 9999 --task-cores 1
Usage: flow test toy [OPTIONS]
Try 'flow test toy -h' for help.

Error: No such option: --task-cores
无法修改task--cores 1
