### ISSUE TITLE
fateboard 1.8无法登录

### ISSUE THREAD

**Issue by turkeymz** [FederatedAI/FATE#3962]
# New Algorithm
更新fate V1.8之后无法登录fateboard

## Short Description
更新fate1.8以后，无法登录fateboard
1. 默认不设置情况下，无法使用admin/admin登录
2. yaml配置admin/admin（容器内部配置文件修改成功），依然无法登录

## 配置与截图
```
server.port=8080
fateflow.url=http://fateflow:9380
fateflow.http_app_key=
fateflow.http_secret_key=
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
server.tomcat.uri-encoding=UTF-8
fateboard.front_end.cors=false
fateboard.front_end.url=http://localhost:8028
server.tomcat.max-threads=1000
server.tomcat.max-connections=20000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.board.login.username=admin
server.board.login.password=admin
server.servlet.session.timeout=4h
server.servlet.session.cookie.max-age=4h
management.endpoints.web.exposure.exclude=*
```
![fateerror](https://user-images.githubusercontent.com/7101412/167103154-13264771-58f4-4287-aac3-d21391c1691a.png)

**Comment by dylan-fan** [comment]
你修改后，重启服务了吗

**Comment by jat001** [comment]
先确保清除了缓存，1.8更新登录这块的代码，如果有浏览器缓存的话是无法登录的

**Comment by turkeymz** [comment]
> 先确保清除了缓存，1.8更新登录这块的代码，如果有浏览器缓存的话是无法登录的

老师您好。我已经重启过了服务。同时尝试清理缓存、使用无痕模式。均无法登录。
请问还有没有别的地方需要修改的？或者有没有详细日志，我去截取提供出来，便于分析

**Comment by jat001** [comment]
打开浏览器的控制台（一般快捷键是F12），切换到network一栏，输完账号密码点击登录时会有一个请求，点开这个请求截个图

**Comment by jat001** [comment]
还有一个可能的问题是，容器内的时间跟系统时间不一样，在浏览器控制台输入`Date()`，在容器里输入`date`，看下两边时间是否一致

**Comment by turkeymz** [comment]
> 打开浏览器的控制台（一般快捷键是F12），切换到network一栏，输完账号密码点击登录时会有一个请求，点开这个请求截个图
请求头+url
![fate_error1](https://user-images.githubusercontent.com/7101412/167332588-72b98b0f-a349-4337-bfc4-0031a
请求体
![fate_error2](https://user-images.githubusercontent.com/7101412/167332666-a3b7e17f-902d-4fab-8658-2cdbf2d8975e.png)
1e307e4.png)
响应体
![fate_error3](https://user-images.githubusercontent.com/7101412/167332675-0d7980f1-ca99-42ca-beac-ec857c821cf4.png)

**Comment by turkeymz** [comment]
> 还有一个可能的问题是，容器内的时间跟系统时间不一样，在浏览器控制台输入`Date()`，在容器里输入`date`，看下两边时间是否一致

确定是时间问题，修改时间后可正常运行。谢谢老师

**Comment by jat001** [comment]
不客气，那我关掉issue了

**Comment by turkeymz** [comment]
> 不客气，那我关掉issue了

老师，我还有一个问题。新版本上传数据的代码放哪了？我们有针对1.6上传数据进行二次开发，但1.8的找不到了
