### ISSUE TITLE
关于fate的Intersection使用，怎么做到数据安全呢？

### ISSUE THREAD

**Issue by SpinSi** [FederatedAI/FATE#3965]
单机docker安装了一下fate 然后按照文档体验了一下 RSA Intersection 任务

先是执行 fate_test suite -i intersect_testsuite.json --data-only 上传数据
以上操作，用到的数据是examples/data/breast_hetero_host.csv , examples/data/breast_hetero_guest.csv
有两个疑问，1 既然这两个数据文档都上传到 fate 服务器了，肯定是泄露出去了，怎么体现数据安全的呢？
2 ，执行命令 flow job submit -c test_intersect_job_rsa_conf.json -d test_intersect_job_dsl.json
按照 [ Intersection PSI介绍](https://github.com/FederatedAI/FATE/blob/master/doc/federatedml_component/intersect.md)
没有RSA公钥和私钥。又是怎么做到数据安全的呢？

有没有更加详细的PSI 使用文档或者正确的 rsa  intersect PSI使用姿势demo 给参考下。谢谢 🙏

**Comment by qxzhou1010** [comment]
1. 图中的e,n就是公钥，d就是私钥呀。Intersection PSI介绍页面也有RSA-PSI的原文出处，看一下就明白了。
2. 第一个疑问，这应该只是个demo，实际部署中，各参与方的明文数据都在自己手上，然后加密数据进行交互。
