### ISSUE TITLE
Is there any way to figure out why the kube-fate is so slow?

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#3967]
**Describe the bug**
为了表述清楚，暂用中文。
在使用kube-fate via docker-compose 时候，发现建模速度很慢。单机版不存在这个问题，主要是无法定位问题
例如下述的任务，从提交到启动花费了近半分钟。对于横向lr，单机版只需要3分钟，而docker-compose 部署的，需要7分钟
![image](https://user-images.githubusercontent.com/18736196/167359149-b7ad83d9-2842-4c1d-a113-0b5d2374b3ae.png)

不清楚是kube-fate 的问题还是fateflow 的问题，下述是fateflow 的log

(请忽略时区问题)
在board中看到是42分32秒提交的任务，但在flow的log中42分56秒才收到请求

![image](https://user-images.githubusercontent.com/18736196/167360223-3925edc7-6868-441b-9534-ba5fb75acc6d.png)

看上去网络也不存在问题，通过请求version接口，响应也很快
![image](https://user-images.githubusercontent.com/18736196/168194154-a1efa469-7cf6-4937-a8b6-a5ba5b7e14e2.png)

我在#3565 里，好像也存在这个问题？观察第一张图的submit time 和start time

**Desktop (please complete the following information):**
- kube fate 1.7.0 via docker-compose

**Comment by LaynePeng** [comment]
Duplicated to: https://github.com/FederatedAI/KubeFATE/issues/613 it is a very general question, and hard to locate the problem. As the answer in that thread, standalone and cluster is a totally different architectures. We can continue to discuss this there.
