### ISSUE TITLE
How can I register a fateboard account? The register button is not found.

### ISSUE THREAD

**Issue by LLYYKK** [FederatedAI/FATE#3968]
Version 1.8.0 
When I accessed 127.0.0.1:8080 and went to FateBoard, it told me to enter my account and password, but I don't have them and I couldn't find the register button.

**Comment by dcdamowangdc** [comment]
> the default username and password is 'admin'. To change these options you can go to `FATEBoard/src/main/resources/application.properties`.

Hello, I have a question. I noticed that FATEBoard can see the input and output data of all jobs when logging in with admin. How can we ensure the data security of the data uploader?
