### ISSUE TITLE
ValueError: Unauthorized variable: host_uuid

### ISSUE THREAD

**Issue by connorzh** [FederatedAI/FATE#3976]
使用FATE1.3.0部署了https://github.com/chengziqiang/FL_DrugDiscovery中的模型，但是在FATEboard看到训练过程中出现如题所示报错。下为日志内容：
"2022-05-16 16:53:14,549 - task_executor.py[line:132] - ERROR: Unauthorized variable: host_uuid"
128 Traceback (most recent call last):
129 File "/fate/fate_flow/driver/task_executor.py", line 119, in run_task
130 run_object.run(parameters, task_run_args)
131 File "/fate/federatedml/model_base.py", line 75, in run
132 self._init_runtime_parameters(component_parameters)
133 File "/fate/federatedml/model_base.py", line 47, in _init_runtime_parameters
134 self._init_model(param)
135 File "/fate/federatedml/nn/ecfp_nn/enter_point.py", line 127, in _init_model
136 super(ECFPNNClient, self)._init_model(param)
137 File "/fate/federatedml/nn/ecfp_nn/enter_point.py", line 64, in _init_model
138 enable_secure_aggregate=secure_aggregate)
139 File "/fate/federatedml/framework/homo/procedure/aggregator.py", line 191, in with_role
140 return Host().register_aggregator(transfer_variable, enable_secure_aggregate)
141 File "/fate/federatedml/framework/homo/procedure/aggregator.py", line 170, in register_aggregator
142 transfer_variables).create_cipher()
143 File "/fate/federatedml/framework/homo/procedure/random_padding_cipher.py", line 60, in create_cipher
144 uuid = self.generate_uuid()
145 File "/fate/federatedml/framework/homo/sync/identify_uuid_sync.py", line 60, in generate_uuid
146 self._uuid_transfer_variable.remote(obj=_uid, role=consts.ARBITER, idx=0, suffix=ind)
147 File "/fate/federatedml/transfer_variable/base_transfer_variable.py", line 117, in remote
148 return self.remote_parties(obj=obj, parties=parties, suffix=suffix)
149 File "/fate/federatedml/transfer_variable/base_transfer_variable.py", line 72, in remote_parties
150 parties=parties)
151 File "/fate/arch/api/transfer/standalone.py", line 59, in remote
152 self._remote_side_auth(name=name, parties=parties)
153 File "/fate/arch/api/transfer/__init__.py", line 271, in _remote_side_auth
154 if self._role not in self._authorize.authorized_src_roles(variable_name=name):
155 File "/fate/arch/api/transfer/__init__.py", line 209, in authorized_src_roles
156 self._update_auth(variable_name)
157 File "/fate/arch/api/transfer/__init__.py", line 199, in _update_auth
158 raise ValueError(f"Unauthorized variable: {v_name}")
![image](https://user-images.githubusercontent.com/58322352/168646114-6832084f-24f4-4cd6-89ae-3b9f61427183.png)

**Comment by mgqa34** [comment]
看起来是transfer_variable的鉴权有问题，看下federatedml/transfer_variable/definition下是否有transfer_variable的json文件

**Comment by connorzh** [comment]
> 看起来是transfer_variable的鉴权有问题，看下federatedml/transfer_variable/definition下是否有transfer_variable的json文件

https://github.com/chengziqiang/FL_DrugDiscovery
在你说的文件夹里面有homo.json文件。因为我只是想用他的模型进行一个预测，所以不是很懂文件配置的问题。

**Comment by mgqa34** [comment]
> > 看起来是transfer_variable的鉴权有问题，看下federatedml/transfer_variable/definition下是否有transfer_variable的json文件
> 
> https://github.com/chengziqiang/FL_DrugDiscovery 在你说的文件夹里面有homo.json文件。因为我只是想用他的模型进行一个预测，所以不是很懂文件配置的问题。

json文件的类名和transfer_class里面的文件类名不一致，修改json文件内容看是否work，HomoTransferVariable->ECFPTTransferVariable，版本有点久远，还有问题的话可以看下相关开发文档说明

**Comment by connorzh** [comment]
> > > 看起来是transfer_variable的鉴权有问题，看下federatedml/transfer_variable/definition下是否有transfer_variable的json文件
> > 
> > 
> > https://github.com/chengziqiang/FL_DrugDiscovery 在你说的文件夹里面有homo.json文件。因为我只是想用他的模型进行一个预测，所以不是很懂文件配置的问题。
> 
> json文件的类名和transfer_class里面的文件类名不一致，修改json文件内容看是否work，HomoTransferVariable->ECFPTTransferVariable，版本有点久远，还有问题的话可以看下相关开发文档说明

改名ECFPTransferVariable依然报错，尝试把文件名改为ecfp.json，依然报错。
开发文档因为版本太久远，找不到了
"2022-05-17 09:12:45,441 - random_padding_cipher.py[line:59] - INFO: synchronizing uuid"
100 "2022-05-17 09:12:45,441 - random_padding_cipher.py[line:59] - INFO: synchronizing uuid"
101 "2022-05-17 09:12:45,453 - task_executor.py[line:132] - ERROR: Unauthorized variable: host_uuid"
102 Traceback (most recent call last):
103 File "/fate/fate_flow/driver/task_executor.py", line 119, in run_task
104 run_object.run(parameters, task_run_args)
105 File "/fate/federatedml/model_base.py", line 75, in run
106 self._init_runtime_parameters(component_parameters)
107 File "/fate/federatedml/model_base.py", line 47, in _init_runtime_parameters
108 self._init_model(param)
109 File "/fate/federatedml/nn/ecfp_nn/enter_point.py", line 127, in _init_model
110 super(ECFPNNClient, self)._init_model(param)
111 File "/fate/federatedml/nn/ecfp_nn/enter_point.py", line 64, in _init_model
112 enable_secure_aggregate=secure_aggregate)
113 File "/fate/federatedml/framework/homo/procedure/aggregator.py", line 191, in with_role
114 return Host().register_aggregator(transfer_variable, enable_secure_aggregate)
115 File "/fate/federatedml/framework/homo/procedure/aggregator.py", line 170, in register_aggregator
116 transfer_variables).create_cipher()
117 File "/fate/federatedml/framework/homo/procedure/random_padding_cipher.py", line 60, in create_cipher
118 uuid = self.generate_uuid()
119 File "/fate/federatedml/framework/homo/sync/identify_uuid_sync.py", line 60, in generate_uuid
120 self._uuid_transfer_variable.remote(obj=_uid, role=consts.ARBITER, idx=0, suffix=ind)
121 File "/fate/federatedml/transfer_variable/base_transfer_variable.py", line 117, in remote
122 return self.remote_parties(obj=obj, parties=parties, suffix=suffix)
123 File "/fate/federatedml/transfer_variable/base_transfer_variable.py", line 72, in remote_parties
124 parties=parties)
125 File "/fate/arch/api/transfer/standalone.py", line 59, in remote
126 self._remote_side_auth(name=name, parties=parties)
127 File "/fate/arch/api/transfer/__init__.py", line 271, in _remote_side_auth
128 if self._role not in self._authorize.authorized_src_roles(variable_name=name):
129 File "/fate/arch/api/transfer/__init__.py", line 209, in authorized_src_roles
130 self._update_auth(variable_name)
131 File "/fate/arch/api/transfer/__init__.py", line 199, in _update_auth
132 raise ValueError(f"Unauthorized variable: {v_name}")
