### ISSUE TITLE
fateboard日志显示正常，但提示system error，dashboard无反应

### ISSUE THREAD

**Issue by gaolje** [FederatedAI/FATE#3977]
![260cffc6fc45b9131b4e3256965990f](https://user-images.githubusercontent.com/105529434/168771783-53d33b6a-0d23-466d-98d6-2264617a3fec.png)

**Comment by mgqa34** [comment]
确认fate_flow服务是否还在，另一种可能是是系统在运行比较大的任务，吃满系统资源

**Comment by gaolje** [comment]
进入fateboard容器找到error日志发现是配置问题，修改之后就可以可以正常显示了。
![`G3}M}{6)I%@X8`LUP~UFHC](https://user-images.githubusercontent.com/105529434/168945510-43662de8-3728-426f-af3c-a06030b3ea43.png)

**Comment by sy0507** [comment]
您好，请问一下，您是怎么解决的，我自己装了sqlite，他会报缺少表

**Comment by sy0507** [comment]
不胜感激

**Comment by gaolje** [comment]
> 不胜感激
我部署的fate单机版1.4，不需要自己装sqlite

**Comment by gaolje** [comment]
谢谢！我检查检查，感谢回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] fateboard日志显示正常，但提示system error，dashboard无反应 (Issue #3977)





 
确认fate_flow服务是否还在，另一种可能是是系统在运行比较大的任务，吃满系统资源

**Comment by ixfcao** [comment]
解决了吗 我也是报这个错误
