### ISSUE TITLE
刚提交任务报错，dataio_0未成功……

### ISSUE THREAD

**Issue by gaolje** [FederatedAI/FATE#3981]
![59a53c2e795e0a76354387e1efe5dea](https://user-images.githubusercontent.com/105529434/168832470-264743b4-ae41-4031-b91c-5621834d589c.png)
![ebfe9341a39892e6fa3b45352b45ea2](https://user-images.githubusercontent.com/105529434/168832523-08d2b353-b770-47a0-91d4-5227421acf22.png)

**Comment by gaolje** [comment]
![image](https://user-images.githubusercontent.com/105529434/168936420-c8d79f0d-860a-46bc-8d06-9c2c071ead12.png)

**Comment by mgqa34** [comment]
确认数据每一行的列数量和header是否一致，报错是使用header中y所在的列去解析每一行的标签的时候越界了

**Comment by gaolje** [comment]
谢谢回复，请问如何确定数据每行的列数量以及header中的列数量呢……我这里的数据集是breast.csv,这里的列数量是指excel打开之后每行有32列的32么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 中午12:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] 刚提交任务报错，dataio_0未成功…… (Issue #3981)





 
确认数据每一行的列数量和header是否一致，报错是使用header中y所在的列去解析每一行的标签的时候越界了

**Comment by gaolje** [comment]
重新上传数据集，配置数据上传文件时，重新命名table_name，namespace（注意不能与之前名字重复）。再次提交任务就🆗了，我之前多次对同一个table_name，namespace上传数据，可能是这个原因导致这个错误。
