### ISSUE TITLE
Security Risk for RSA Intersection Cardinality: Intersection items exposed. 

### ISSUE THREAD

**Issue by a7853z** [FederatedAI/FATE#3984]
**Describe the bug**
Specific Intersection items are exposed on the Guest Side for Intersection Cardinality, consider the definition of PSI-CA protocol, this is not considered secure.
  

> Private [set intersection] cardinality (PSI-CA) allows two parties, the sender and receiver, to compute the cardinality of the intersection, without revealing anything more to the other party.

Check the 310th line of rsa_intersect_guest.py:
`intersect_ids_list = [ids.map(lambda k, v: (v[0], 1)) for ids in intersect_ids_list]   `
in which v[0] is actually the private id and I can print out these private ids in log。

I checked the run_cardinality function. It seems that oher than the Bloom Filters to filter the private intersection. Other parts basically stays the same as original PSI.  

Please verify this security risk or is it a design by intention.

**Comment by nemirorox** [comment]
Hi, 
In current version of FATE, cardinality calculation is a process of estimation with BloomFilter, and so the resulted cardinality count is not exact, neither are the `intersect_ids` in the intermediate process. On the other hand, ’cardinality_only’ mode is designed to allow Host(often data source with large amount of ids) and Guest quickly estimate their intersection count without revealing Guest’s ids to Host. This situation is most common in industrial applications, where compared to Host, whose database covers huge amount of users, Guest holds a limited but indicative number of ids. In such cases, Guest’s id collection need to be held unknown to Host, and so security of intersection id set against Host takes priority.

As for the mentioned scenario where neither participants can gain more information than cardinality, we arranged plans to implement DH-based PSI-CA in the upcoming 1.9 version, you may follow this ISSUE #3856 for any updates.

**Comment by a7853z** [comment]
Thanks for the clarification. @nemirorox
