### ISSUE TITLE
nodemanager temp data is too large

### ISSUE THREAD

**Issue by majorinche** [FederatedAI/FATE#3985]
when we run many jobs , the data under LMDB will expand too quickly and too large.
![node-too large](https://user-images.githubusercontent.com/19666925/169474007-0638e9c8-2c2d-45e1-95a1-4f854698912d.png)

can we just give some configuration for us to decide, like
how long we will keep these temparary data? or what is the maximum days?

maybe just put it in the service_conf file?
![service_conf](https://user-images.githubusercontent.com/19666925/169475145-a685aa9f-b8c2-4c4b-b00c-31823531189c.png)

thanks
majorin

**Comment by dylan-fan** [comment]
The data is the component output data of job.  
You can clean the data if you don't not need it.

**Comment by dylan-fan** [comment]
The data is the component output data of job.  
You can clean the data if you don't not need it.
