### ISSUE TITLE
Fate1.5 运行项目 pipeline-upload.py 脚本，出错

### ISSUE THREAD

**Issue by zhougz2018** [FederatedAI/FATE#3996]
UPLOADING:||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||100.00%
2022-05-23 16:30:02.024 | ERROR    | __main__:main:54 - An error has been caught in function 'main', process 'MainProcess' (15176), thread 'MainThread' (10680):
Traceback (most recent call last):

  File "G:\ProgramData\Miniconda3\envs\FL\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 105, in upload_data
    raise ValueError

ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "F:/study/联邦学习/源码/FATE/examples/pipeline/upload\pipeline-upload.py", line 58, in <module>
    main()
    └ <function main at 0x0000023A4E8A2F28>

> File "F:/study/联邦学习/源码/FATE/examples/pipeline/upload\pipeline-upload.py", line 54, in main
    pipeline_upload.upload(drop=1)
    │               └ <function PipeLine.upload at 0x0000023A6128F1E0>
    └ <pipeline.backend.pipeline.PipeLine object at 0x0000023A6127B940>

  File "G:\ProgramData\Miniconda3\envs\FL\lib\site-packages\pipeline\backend\pipeline.py", line 508, in upload
    self._train_job_id, detail_info = self._job_invoker.upload_data(upload_conf, int(drop))
    │    │                            │    │            │           │                └ 1
    │    │                            │    │            │           └ {'file': 'F:/study/FL/data/breast_hetero_guest.csv', 'table_name': 'breast_hetero_guest', 'namespace': 'experiment', 'head': ...
    │    │                            │    │            └ <function JobInvoker.upload_data at 0x0000023A612809D8>
    │    │                            │    └ <pipeline.utils.invoker.job_submitter.JobInvoker object at 0x0000023A6127B898>
    │    │                            └ <pipeline.backend.pipeline.PipeLine object at 0x0000023A6127B940>
    │    └ None
    └ <pipeline.backend.pipeline.PipeLine object at 0x0000023A6127B940>

  File "G:\ProgramData\Miniconda3\envs\FL\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 113, in upload_data
    raise ValueError("job submit failed, err msg: {}".format(result))
                                                             └ {'retcode': 100, 'retmsg': 'required parameters are missing: work_mode,namespace,table_name,head,partition;'}

ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'required parameters are missing: work_mode,namespace,table_name,head,partition;'}
Traceback (most recent call last):
  File "G:\ProgramData\Miniconda3\envs\FL\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 105, in upload_data
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/study/联邦学习/源码/FATE/examples/pipeline/upload/pipeline-upload.py", line 58, in <module>
    main()
  File "F:/study/联邦学习/源码/FATE/examples/pipeline/upload/pipeline-upload.py", line 54, in main
    pipeline_upload.upload(drop=1)
  File "G:\ProgramData\Miniconda3\envs\FL\lib\site-packages\loguru\_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "G:\ProgramData\Miniconda3\envs\FL\lib\site-packages\pipeline\backend\pipeline.py", line 508, in upload
    self._train_job_id, detail_info = self._job_invoker.upload_data(upload_conf, int(drop))
  File "G:\ProgramData\Miniconda3\envs\FL\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 113, in upload_data
    raise ValueError("job submit failed, err msg: {}".format(result))
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'required parameters are missing: work_mode,namespace,table_name,head,partition;'}

Process finished with exit code 1

**Comment by mgqa34** [comment]
可以附上Pipeline的代码，这些参数看1.5的examples都是有的，是否使用了更高版本的examples但fate版本是旧的呢？

**Comment by zhougz2018** [comment]
def main(config="../../config.yaml", namespace=""):
    # obtain config
    if isinstance(config, str):
        config = load_job_config(config)
    parties = config.parties
    guest = parties.guest[0]
    data_base = config.data_base_dir

    # partition for data storage
    partition = 4

    # table name and namespace, used in FATE job configuration
    dense_data = {"name": "breast_hetero_guest", "namespace": f"experiment{namespace}"}
    tag_data = {"name": "tag_value_1", "namespace": f"experiment{namespace}"}

    pipeline_upload = PipeLine().set_initiator(role="guest", party_id=guest).set_roles(guest=guest)

    # add upload data info
    # path to csv file(s) to be uploaded
    pipeline_upload.add_upload_data(file=os.path.join(data_base, "breast_hetero_guest.csv"),
                                    table_name=dense_data["name"],             # table name
                                    namespace=dense_data["namespace"],         # namespace
                                    head=1, partition=partition,               # data info
                                    id_delimiter=",")

    pipeline_upload.add_upload_data(file=os.path.join(data_base, "tag_value_1000_140.csv"),
                                    table_name=tag_data["name"],
                                    namespace=tag_data["namespace"],
                                    head=0, partition=partition,
                                    id_delimiter=",")
    # upload both data
    pipeline_upload.upload(drop=1)


if __name__ == "__main__":
    main()

**Comment by zhougz2018** [comment]
docker最新是1.8？

**Comment by mgqa34** [comment]
> def main(config="../../config.yaml", namespace=""): # obtain config if isinstance(config, str): config = load_job_config(config) parties = config.parties guest = parties.guest[0] data_base = config.data_base_dir
> 
> ```
> # partition for data storage
> partition = 4
> 
> # table name and namespace, used in FATE job configuration
> dense_data = {"name": "breast_hetero_guest", "namespace": f"experiment{namespace}"}
> tag_data = {"name": "tag_value_1", "namespace": f"experiment{namespace}"}
> 
> pipeline_upload = PipeLine().set_initiator(role="guest", party_id=guest).set_roles(guest=guest)
> 
> # add upload data info
> # path to csv file(s) to be uploaded
> pipeline_upload.add_upload_data(file=os.path.join(data_base, "breast_hetero_guest.csv"),
>                                 table_name=dense_data["name"],             # table name
>                                 namespace=dense_data["namespace"],         # namespace
>                                 head=1, partition=partition,               # data info
>                                 id_delimiter=",")
> 
> pipeline_upload.add_upload_data(file=os.path.join(data_base, "tag_value_1000_140.csv"),
>                                 table_name=tag_data["name"],
>                                 namespace=tag_data["namespace"],
>                                 head=0, partition=partition,
>                                 id_delimiter=",")
> # upload both data
> pipeline_upload.upload(drop=1)
> ```
> 
> if **name** == "**main**": main()

这个examples不是1.5.x的，可以在tags下找对应版本的examples使用

**Comment by ivan0410** [comment]
how to deal with this:
2023-04-26 07:52:59.537 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (217), thread 'MainThread' (140416950314816):
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x7fb55e4afbe0, file "/usr/local/lib/python3.8/site-packages/ipykernel_launcher.py", line 1>
           └ <function _run_code at 0x7fb55e4be940>
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x7fb55e4afbe0, file "/usr/local/lib/python3.8/site-packages/ipykernel_launcher.py", line 1>
  File "/usr/local/lib/python3.8/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/usr/local/lib/python3.8/site-packages/ipykernel/kernelapp.py'>
  File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 1041, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x7fb55a05e0d0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7fb55e67a4c0>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x7fb55bcf98b0>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fb55a05c6a0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7fb55e67a4c0>
  File "/usr/local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x7fb55dcb9b80>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fb55a05c6a0>
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fb55dcbb700>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fb55dcfe4c0>
    └ <Handle <TaskWakeupMethWrapper object at 0x7fb55a0813d0>(<Future finis...720>, ...],))>)>
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7fb55a0813d0>(<Future finis...720>, ...],))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7fb55a0813d0>(<Future finis...720>, ...],))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7fb55a0813d0>(<Future finis...720>, ...],))>)>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
          │    └ <function Kernel.process_one at 0x7fb55a9c6160>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x7fb55a006700>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
          │         └ ([<zmq.sugar.frame.Frame object at 0x7fb5587d5670>, <zmq.sugar.frame.Frame object at 0x7fb5587d5460>, <zmq.sugar.frame.Frame ...
          └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x7fb55a006700>>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
          └ <coroutine object Kernel.execute_request at 0x7fb55877d1c0>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x7fb55877d140>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x7fb55a0cb820>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fb55a006c70>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 530, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('pipeline_upload.upload(drop=1)',)
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2945, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x7fb55b457700>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fb55a006c70>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3000, in _run_cell
    return runner(coro)
           │      └ <coroutine object InteractiveShell.run_cell_async at 0x7fb55877d540>
           └ <function _pseudo_sync_runner at 0x7fb55b44b040>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x7fb55877d540>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3203, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/tmp/ipykernel_217/330354976.py'
                       │    │             │        └ [<_ast.Expr object at 0x7fb5587cce80>]
                       │    │             └ <_ast.Module object at 0x7fb5587cc5b0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x7fb55b4579d0>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fb55a006c70>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3382, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 7fb5587d1520, execution_count=13 error_before_exec=None error_in_exec=None info=<ExecutionInfo obj...
             │    │        └ <code object <module> at 0x7fb5587cdea0, file "/tmp/ipykernel_217/330354976.py", line 1>
             │    └ <function InteractiveShell.run_code at 0x7fb55b457a60>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fb55a006c70>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fb55a006c70>
         │         │    └ <property object at 0x7fb55b447b80>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fb55a006c70>
         └ <code object <module> at 0x7fb5587cdea0, file "/tmp/ipykernel_217/330354976.py", line 1>

> File "/tmp/ipykernel_217/330354976.py", line 1, in <module>
    pipeline_upload.upload(drop=1)
    │               └ <function PipeLine.upload at 0x7fb4a7f3c5e0>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fb4a7f43c70>

  File "/usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py", line 665, in upload
    self._train_board_url = detail_info["board_url"]
    │    │                  └ {'code': 103, 'job_id': '202304260752593146000', 'message': 'Traceback (most recent call last):\n  File "/data/projects/fate/...
    │    └ None
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fb4a7f43c70>

KeyError: 'board_url'

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[13], line 1
----> 1 pipeline_upload.upload(drop=1)

File /usr/local/lib/python3.8/site-packages/loguru/_logger.py:1226, in Logger.catch.<locals>.Catcher.__call__.<locals>.catch_wrapper(*args, **kwargs)
   1224 def catch_wrapper(*args, **kwargs):
   1225     with catcher:
-> 1226         return function(*args, **kwargs)
   1227     return default

File /usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py:665, in PipeLine.upload(self, drop)
    663 LOGGER.debug(f"upload_conf is {json.dumps(upload_conf)}")
    664 self._train_job_id, detail_info = self._job_invoker.upload_data(upload_conf, int(drop))
--> 665 self._train_board_url = detail_info["board_url"]
    666 self._job_invoker.monitor_job_status(self._train_job_id,
    667                                      "local",
    668                                      0)

KeyError: 'board_url'
