### ISSUE TITLE
请问一下可以支持纵向联邦学习模型的拓展吗

### ISSUE THREAD

**Issue by ATowerz** [FederatedAI/FATE#3997]
可以将自己的机器学习模型应用到FATE的纵向联邦学习中吗，还是说只能使用现在FATE库里已有的纵向联邦学习的模型实现呢？

Can I apply my own machine learning model to FATE's vertical federated learning, or  I only use the existing vertical federated learning model in the FATE library?

**Comment by mgqa34** [comment]
传统的机器学习模型应该要设计成可联邦化，比如使用的多方安全计算的协议等等。 待设计完成后，开发新算法的过程可以参考开发文档：https://github.com/FederatedAI/FATE/blob/master/doc/develop/develop_guide.md
