### ISSUE TITLE
Failed to run demo, SecretShare MPC Protocol(SPDZ) demo.

### ISSUE THREAD

**Issue by magic-hya** [FederatedAI/FATE#4000]
Session.init_federation property 'service_conf' is required in version 1.7.2.
![1653446938(1)](https://user-images.githubusercontent.com/85269941/170169391-98423588-cca5-44cc-8572-026e4d096b0e.jpg)
I don't know what to fill in this value.
I tried two ways:
1.Fill in the IP and port of the other party.
service_conf={"host":"other ip","port" :9370}
2.Fill in my own IP and port.
service_conf={"host":"my ip","port" :9370}

Both failed!

**Comment by mgqa34** [comment]
> Session.init_federation property 'service_conf' is required in version 1.7.2. ![1653446938(1)](https://user-images.githubusercontent.com/85269941/170169391-98423588-cca5-44cc-8572-026e4d096b0e.jpg) I don't know what to fill in this value. I tried two ways: 1.Fill in the IP and port of the other party. service_conf={"host":"other ip","port" :9370} 2.Fill in my own IP and port. service_conf={"host":"my ip","port" :9370}
> 
> Both failed!

Please give the error message of the second type.

**Comment by magic-hya** [comment]
After waiting for a few minutes, the program is wrong.
![1653467487(1)](https://user-images.githubusercontent.com/85269941/170218197-7424ffc5-a74e-4a23-842e-e36bc868f413.jpg)
![image](https://user-images.githubusercontent.com/85269941/170218605-18709a6d-156f-4831-9145-26554b06491b.png)

**Comment by magic-hya** [comment]
After waiting for a few minutes, the program is wrong.
The code:
![1653468030(1)](https://user-images.githubusercontent.com/85269941/170222039-35e64207-5567-4243-a287-39e0064a459b.jpg)
![image](https://user-images.githubusercontent.com/85269941/170222256-74ad96ce-c527-4fd9-8cb7-a51a58a8d70a.png)

error message:
![image](https://user-images.githubusercontent.com/85269941/170224401-be79421e-cb01-47fe-9a3c-c1d205f1c566.png)
![1653469313(1)](https://user-images.githubusercontent.com/85269941/170224864-b3029cf3-e0a3-4479-8b28-c4cb5fbcdebe.jpg)

**Comment by magic-hya** [comment]
Hi
I tried, but it was the same error.
Modified code:
![image](https://user-images.githubusercontent.com/85269941/170453909-fc10460c-2e35-418f-afde-d9d6f7699831.png)
![1653555198(1)](https://user-images.githubusercontent.com/85269941/170454620-3bd911a3-532c-4f0a-974a-2fe32fe66233.jpg)

The same error message:
![image](https://user-images.githubusercontent.com/85269941/170454741-472ca243-b604-4e34-8928-8072b620a4db.png)

**Comment by mgqa34** [comment]
guest: 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/13565267/170920312-d0144fde-f9cc-4b4a-b234-52f0915b4b67.png">

host:
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/13565267/170920368-cc9b9e33-dd59-441f-a25d-28744ac2bb9d.png">

I use the above config and runs spdz sucessfully

**Comment by magic-hya** [comment]
Thank you very much. The problem has been solved. 
Can I submit the demo I ran successfully and update the MD document？
