### ISSUE TITLE
关于1.8.0版本secure_information_retrieval组件的使用问题

### ISSUE THREAD

**Issue by yyouyou** [FederatedAI/FATE#4001]
**Describe the bug**
1.8.0 版本secure_information_retrieval组件使用，dsl v2方式，example中案例包含Reader，DataTransform，SecureInformationRetrieval三个组件，可以执行成功
1.5.0版本中secure_information_retrieval组件使用，dsl v1方式，example中案例包含DataIO，SecureInformationRetrieval，两个组件，可以执行成功
问题在于，1.8.0 版本secure_information_retrieval组件使用，dsl v2方式，配置Reader和SecureInformationRetrieval失败报错，请问1.8.0版本后，如果要用到secure_information_retrieval组件，就必须要配置DataTransform组件吗

**To Reproduce**
执行命令：flow job submit -c test_secure_information_retrieval_conf.json -d test_secure_information_retrieval_dsl.json
1.8.0 secure_information_retrieval dsl配置文件
test_secure_information_retrieval_conf.json
```
{
    "dsl_version": 2,
    "initiator": {
        "role": "guest",
        "party_id": 10000
    },
    "role": {
        "host": [
            9999
        ],
        "guest": [
            10000
        ]
    },
    "component_parameters": {
        "role": {
            "guest": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "breast_hetero_guest",
                            "namespace": "experiment"
                        }
                    }
                }
            },
            "host": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "breast_hetero_host",
                            "namespace": "experiment"
                        }
                    }
                }
            }
        },
        "common": {
            "secure_information_retrieval_0": {
                "security_level": 0.5,
                "oblivious_transfer_protocol": "OT_Hauck",
                "commutative_encryption": "CommutativeEncryptionPohligHellman",
                "non_committing_encryption": "aes",
                "dh_params": {
                    "key_length": 1024
                },
                "raw_retrieval": false,
                "target_cols": [
                    "x10",
                    "x11"
                ]
            }
        }
    }
}
```

test_secure_information_retrieval_dsl.json
```
{
    "components": {
        "reader_0": {
            "module": "Reader",
            "output": {
                "data": [
                    "data"
                ]
            }
        },
        "secure_information_retrieval_0": {
            "module": "SecureInformationRetrieval",
            "input": {
                "data": {
                    "data": [
                        "reader_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ],
                "model": [
                    "model"
                ]
            }
        }
    }
}
```
**报错日志**
host方
```
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 236, in run
    self._run(cpn_input=cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 311, in _run
    this_data_output = func(*real_param)
  File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 98, in fit
    self.need_label)      # List[(Ei, val)]
  File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 229, in _restore_value
lambda v, u:
  File "/data/projects/fate/fate/python/fate_arch/common/profile.py", line 318, in _fn
    rtn = func(*args, **kwargs)
  File "/data/projects/fate/fate/python/fate_arch/computing/eggroll/_table.py", line 117, in join
    return Table(self._rp.join(other._rp, func=func))
  File "/data/projects/fate/eggroll/python/eggroll/core/aspects.py", line 30, in wrapper
    result = func(*args, **kwargs)
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/roll_pair.py", line 1114, in join
    task_results = self._run_job(job=job)
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/roll_pair.py", line 475, in _run_job
    results.append(future.result())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/data/projects/fate/eggroll/python/eggroll/core/datastructure/threadpool.py", line 51, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 97, in sync_send
    raise CommandCallError(command_uri, endpoint, e)
eggroll.core.client.CommandCallError: ('Failed to call command: CommandURI(_uri=v1/egg-pair/runTask) to endpoint: nodemanager:46412, caused by: ', <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 
==== detail start, at 20220525.032430.311 ====
Traceback (most recent call last):
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 158, in _run_binary
    output_writebatch)
  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 418, in merge_join_wrapper
    right_value_serdes.deserialize(v_right_bytes))))
  File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 232, in <lambda>
    need_label))
  File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 169, in extract_value
    features = [instance.features[i] for i in target_indexes]
  File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 169, in <listcomp>
    features = [instance.features[i] for i in target_indexes]
AttributeError: 'str' object has no attribute 'features'
```

**Comment by mgqa34** [comment]
> **Describe the bug** 1.8.0 版本secure_information_retrieval组件使用，dsl v2方式，example中案例包含Reader，DataTransform，SecureInformationRetrieval三个组件，可以执行成功 1.5.0版本中secure_information_retrieval组件使用，dsl v1方式，example中案例包含DataIO，SecureInformationRetrieval，两个组件，可以执行成功 问题在于，1.8.0 版本secure_information_retrieval组件使用，dsl v2方式，配置Reader和SecureInformationRetrieval失败报错，请问1.8.0版本后，如果要用到secure_information_retrieval组件，就必须要配置DataTransform组件吗
> 
> **To Reproduce** 执行命令：flow job submit -c test_secure_information_retrieval_conf.json -d test_secure_information_retrieval_dsl.json 1.8.0 secure_information_retrieval dsl配置文件 test_secure_information_retrieval_conf.json
> 
> ```
> {
>     "dsl_version": 2,
>     "initiator": {
>         "role": "guest",
>         "party_id": 10000
>     },
>     "role": {
>         "host": [
>             9999
>         ],
>         "guest": [
>             10000
>         ]
>     },
>     "component_parameters": {
>         "role": {
>             "guest": {
>                 "0": {
>                     "reader_0": {
>                         "table": {
>                             "name": "breast_hetero_guest",
>                             "namespace": "experiment"
>                         }
>                     }
>                 }
>             },
>             "host": {
>                 "0": {
>                     "reader_0": {
>                         "table": {
>                             "name": "breast_hetero_host",
>                             "namespace": "experiment"
>                         }
>                     }
>                 }
>             }
>         },
>         "common": {
>             "secure_information_retrieval_0": {
>                 "security_level": 0.5,
>                 "oblivious_transfer_protocol": "OT_Hauck",
>                 "commutative_encryption": "CommutativeEncryptionPohligHellman",
>                 "non_committing_encryption": "aes",
>                 "dh_params": {
>                     "key_length": 1024
>                 },
>                 "raw_retrieval": false,
>                 "target_cols": [
>                     "x10",
>                     "x11"
>                 ]
>             }
>         }
>     }
> }
> ```
> 
> test_secure_information_retrieval_dsl.json
> 
> ```
> {
>     "components": {
>         "reader_0": {
>             "module": "Reader",
>             "output": {
>                 "data": [
>                     "data"
>                 ]
>             }
>         },
>         "secure_information_retrieval_0": {
>             "module": "SecureInformationRetrieval",
>             "input": {
>                 "data": {
>                     "data": [
>                         "reader_0.data"
>                     ]
>                 }
>             },
>             "output": {
>                 "data": [
>                     "data"
>                 ],
>                 "model": [
>                     "model"
>                 ]
>             }
>         }
>     }
> }
> ```
> 
> **报错日志** host方
> 
> ```
>   File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
>     cpn_output = run_object.run(cpn_input)
>   File "/data/projects/fate/fate/python/federatedml/model_base.py", line 236, in run
>     self._run(cpn_input=cpn_input)
>   File "/data/projects/fate/fate/python/federatedml/model_base.py", line 311, in _run
>     this_data_output = func(*real_param)
>   File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 98, in fit
>     self.need_label)      # List[(Ei, val)]
>   File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 229, in _restore_value
> lambda v, u:
>   File "/data/projects/fate/fate/python/fate_arch/common/profile.py", line 318, in _fn
>     rtn = func(*args, **kwargs)
>   File "/data/projects/fate/fate/python/fate_arch/computing/eggroll/_table.py", line 117, in join
>     return Table(self._rp.join(other._rp, func=func))
>   File "/data/projects/fate/eggroll/python/eggroll/core/aspects.py", line 30, in wrapper
>     result = func(*args, **kwargs)
>   File "/data/projects/fate/eggroll/python/eggroll/roll_pair/roll_pair.py", line 1114, in join
>     task_results = self._run_job(job=job)
>   File "/data/projects/fate/eggroll/python/eggroll/roll_pair/roll_pair.py", line 475, in _run_job
>     results.append(future.result())
>   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
>   File "/data/projects/fate/eggroll/python/eggroll/core/datastructure/threadpool.py", line 51, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 97, in sync_send
>     raise CommandCallError(command_uri, endpoint, e)
> eggroll.core.client.CommandCallError: ('Failed to call command: CommandURI(_uri=v1/egg-pair/runTask) to endpoint: nodemanager:46412, caused by: ', <_Rendezvous of RPC that terminated with:
> 	status = StatusCode.UNKNOWN
> 	details = "Exception calling application: 
> ==== detail start, at 20220525.032430.311 ====
> Traceback (most recent call last):
>   File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 158, in _run_binary
>     output_writebatch)
>   File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 418, in merge_join_wrapper
>     right_value_serdes.deserialize(v_right_bytes))))
>   File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 232, in <lambda>
>     need_label))
>   File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 169, in extract_value
>     features = [instance.features[i] for i in target_indexes]
>   File "/data/projects/fate/fate/python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py", line 169, in <listcomp>
>     features = [instance.features[i] for i in target_indexes]
> AttributeError: 'str' object has no attribute 'features'
> ```

需要的，DataTransform其实是DataIO的升级版组件，已不再维护DataIO，用Reader->DataTransform(DataIO)->SIR都可以

**Comment by yyouyou** [comment]
> 

了解了，谢谢
