### ISSUE TITLE
FederatedAI / FATE这个仓库default分支是master，FederatedAI / FATE-Flow仓库default分支是main，现在github不是因为种族歧视问题已经禁止master/slave分支命名了吗？为啥还会出现呢？FATE具有一定影响力，这个会不会有问题？

### ISSUE THREAD

**Issue by MiKKiYang** [FederatedAI/FATE#4006]
FederatedAI / FATE这个仓库default分支是master，FederatedAI / FATE-Flow仓库default分支是main，现在github不是因为种族歧视问题已经禁止master/slave分支命名了吗？为啥还会出现呢？FATE具有一定影响力，这个会不会有问题？

**Comment by MiKKiYang** [comment]
@jat001 @dylan-fan @hainingzhang @zhihuiwan

**Comment by weiwee** [comment]
@MiKKiYang  我个人觉得没有这个必要，修改主分支名还可能破坏已有的一些第三方链接， 事实上有大量的更有影响力的项目都继续保持了主分支的命名， 比如tensorflow。 
默认以master为主分支的命名方式有非常久的历史了，本身也不是为了冒犯某些群体，我们是技术开源项目，我想我们应该更关注技术本身。

**Comment by MiKKiYang** [comment]
> @MiKKiYang 我个人觉得没有这个必要，修改主分支名还可能破坏已有的一些第三方链接， 事实上有大量的更有影响力的项目都继续保持了主分支的命名， 比如tensorflow。 默认以master为主分支的命名方式有非常久的历史了，本身也不是为了冒犯某些群体，我们是技术开源项目，我想我们应该更关注技术本身。

好的好的、了解了、tks~
