### ISSUE TITLE
怎么将一个已训练好的横向secureboost模型，将其返回成一个Booster类的模型呢？

### ISSUE THREAD

**Issue by jomaron** [FederatedAI/FATE#4008]
有两个问题请教专家，还请专家指点，感谢答疑。
（1）FATE1.7.2，怎么将一个已训练好的横向secureboost模型，将其返回成一个Booster类的模型呢？
（2）FATE1.7.2，怎么将一个已训练好的横向secureboost模型转化成lightgbm模型，并返回一个Booster类的模型呢？

**Comment by talkingwallace** [comment]
使用flow model homo-convertor 可以得到lgb txt格式的模型文件

**Comment by jomaron** [comment]
> 使用flow model homo-convertor 可以得到lgb txt格式的模型文件

感谢专家答疑！确实看到了这个命令，比如说我训练了一个模型的id，那怎么对应这个模型id去用homo-convert去转化呢？再次感谢帮助哈

**Comment by jomaron** [comment]
> 使用flow model homo-convertor 可以得到lgb txt格式的模型文件

您好！这个命令后面应该需要一个json文件，文件里配有model_id, model_version_和party_id。 但是json文件里面的model_id、 model_version_和party_id的格式大概是怎样的呢？感谢答疑！

**Comment by talkingwallace** [comment]
hello, moder_version 和party_id应该在你提交任务后是看得到的
