### ISSUE TITLE
Host/Guest 不在一台主机，可使用standalone进行部署吗？或可使用standalone作为存储/计算引擎吗？

### ISSUE THREAD

**Issue by gxcuit** [FederatedAI/FATE#4009]
目前fate standalone 好像是host、guest、arbiter在一台机器上，供开发和测试使用

实际中，假设我有两台设备，192.168.19.1、192.168.19.2

19.1 作为Host，19.2 作为Guest，是只能使用kube-fate进行部署吗？kube-fate默认引擎是eggroll，在小数据集和不牵涉分布式的时候，效率比standalone慢很多

我的疑问是，假设Host、Guest不在一台设备上，能否使用standalone？或者将计算、存储、通信引擎改为standalone？ 如果可以，需修改哪些配置文件？

**Comment by dylan-fan** [comment]
1.9开始可以，1.8还不行

**Comment by magic-hya** [comment]
> 1.9开始可以，1.8还不行

这个standalone能实现分布式还是很有用的，有时并不需要那种非常复杂的部署

**Comment by yyf1986** [comment]
问下standalone的 引擎是什么？@gxcuit

**Comment by magic-hya** [comment]
> 问下standalone的 引擎是什么？@gxcuit

eggroll
