### ISSUE TITLE
关于 Heterogeneous SSHE Logistic Regression 的两点疑问

### ISSUE THREAD

**Issue by tanjuntao** [FederatedAI/FATE#4016]
从[官方文档](https://fate.readthedocs.io/en/latest/federatedml_component/logistic_regression/#heterogeneous-sshe-logistic-regression)中得知，FATE 实现了一种基于 SS+HE 的混合纵向 LR 训练协议，在阅读协议流程图中，有以下两点问题想请教下：
1. SS+HE 的方案中，使用的损失函数是什么？从残差的计算方式中，猜测应该不是 Taylor Loss
2. 在 `forward` 流程中，Host Party 为何要将 `<WX>1` 同态加密后发送给 Guest Party? 仅仅是为了方便 Guest Party 计算出完整的密态残差吗？因为如果 Host Party 的 `<WX>1` 保留在本地，那么后续这两方可以分别计算 share of residue, 从而计算 share of gradient, 进一步更新 share of parameters。所以不知道为何 FATE 在这里是这么处理的，有什么特殊的考虑吗？

希望能获得官方的解答，谢谢。

**Comment by talkingwallace** [comment]
https://arxiv.org/pdf/2008.08753.pdf 可以参考这个论文
