### ISSUE TITLE
建议增加组件输出所有数据的接口(分页)

### ISSUE THREAD

**Issue by zlt2000** [FederatedAI/FATE#4023]
场景：使用模型预测结果后，下游服务通过接口获取预测的结果。

问题：目前获取组件的数据输出接口只有 `/v1/tracking/component/output/data` 该接口只能返回100条数据。

建议：增加或者修改原有的接口，支持分页查询，获取所有的数据。

**Comment by wanglg007** [comment]
使用/v1/tracking/component/output/data/download接口可以实现数据下载。
