### ISSUE TITLE
我在使用homo_nn自定义模型训练mnist时，出现这个了错误，‘NoneType' object has no attribute 'count'

### ISSUE THREAD

**Issue by gaolje** [FederatedAI/FATE#4031]
![image](https://user-images.githubusercontent.com/105529434/173223122-588d6dd8-ca17-423a-8d70-ad3ed3e0209a.png)
![image](https://user-images.githubusercontent.com/105529434/173223218-a20f58c0-a3f7-4403-9482-df1ff1392dcb.png)

**Comment by mgqa34** [comment]
What's the version of fate? The error means homo_nn's input data is None

**Comment by gaolje** [comment]
My fate version is 1.4。standlone deployed&nbsp;


高露洁丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月13日(星期一) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE] 我在使用homo_nn自定义模型训练mnist时，出现这个了错误，‘NoneType&#39; object has no attribute &#39;count&#39; (Issue #4031)





 
What's the version of fate? The error means homo_nn's input data is None

**Comment by mgqa34** [comment]
Check the consistence of dataio's output and homo_nn's input in dsl json file please.

**Comment by gaolje** [comment]
{
&nbsp; "components": {
&nbsp; &nbsp; &nbsp; "dataio_0": {
&nbsp; &nbsp; &nbsp; "module": "DataIO",
&nbsp; &nbsp; &nbsp; "input": {
&nbsp; &nbsp; &nbsp; &nbsp; "data": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "data": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "args.train_data"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; "output": {
&nbsp; &nbsp; &nbsp; &nbsp; "data": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "train"
&nbsp; &nbsp; &nbsp; &nbsp; ],
&nbsp; &nbsp; &nbsp; &nbsp; "model": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "dataio"
&nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
&nbsp; &nbsp; "homo_nn_0": {
&nbsp; &nbsp; &nbsp; "module": "HomoNN",
&nbsp; &nbsp; &nbsp; "input": {
&nbsp; &nbsp; &nbsp; &nbsp; "data": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "train_data": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "dataio_0.train"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; "output": {
&nbsp; &nbsp; &nbsp; &nbsp; "data": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "train"
&nbsp; &nbsp; &nbsp; &nbsp; ],
&nbsp; &nbsp; &nbsp; &nbsp; "model": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "homo_nn"
&nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
	"evaluation_0":{
	 "module": "Evaluation",
	 "input": {
		"data" :{
			"data": ["homo_nn_0.train"]
	 }			
	}
&nbsp; }
&nbsp; }}
this is my dsl file&nbsp;
&nbsp;


高露洁丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月13日(星期一) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE] 我在使用homo_nn自定义模型训练mnist时，出现这个了错误，‘NoneType&#39; object has no attribute &#39;count&#39; (Issue #4031)





 
Check the consistence of dataio's output and homo_nn's input in dsl json file please.

**Comment by gaolje** [comment]
{
  "components": {
       "dataio_0": {
      "module": "DataIO",
      "input": {
        "data": {
          "data": [
            "args.train_data"
          ]
        }
      },
      "output": {
        "data": [
          "data"
        ],
        "model": [
          "dataio"
        ]
      }
    },
    "homo_nn_0": {
      "module": "HomoNN",
      "input": {
        "data": {
          "train_data": [
            "dataio_0.train"
          ]
        }
      },
      "output": {
        "data": [
          "train"
        ],
        "model": [
          "homo_nn"
        ]
      }
    },
	"evaluation_0":{
	 "module": "Evaluation",
	 "input": {
		"data" :{
			"data": ["homo_nn_0.train"]
	 }			
	}
  }
  }}
this is my dsl file.

**Comment by mgqa34** [comment]
> { "components": { "dataio_0": { "module": "DataIO", "input": { "data": { "data": [ "args.train_data" ] } }, "output": { "data": [ "data" ], "model": [ "dataio" ] } }, "homo_nn_0": { "module": "HomoNN", "input": { "data": { "train_data": [ "dataio_0.train" ] } }, "output": { "data": [ "train" ], "model": [ "homo_nn" ] } }, "evaluation_0":{ "module": "Evaluation", "input": { "data" :{ "data": ["homo_nn_0.train"] } } } }} this is my dsl file.

input data of homo_nn should be "dataio_0.train" instead of "dataio_0.data"

**Comment by gaolje** [comment]
oh,thanks
&nbsp;


高露洁丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月15日(星期三) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE] 我在使用homo_nn自定义模型训练mnist时，出现这个了错误，‘NoneType&#39; object has no attribute &#39;count&#39; (Issue #4031)





  
{ "components": { "dataio_0": { "module": "DataIO", "input": { "data": { "data": [ "args.train_data" ] } }, "output": { "data": [ "data" ], "model": [ "dataio" ] } }, "homo_nn_0": { "module": "HomoNN", "input": { "data": { "train_data": [ "dataio_0.train" ] } }, "output": { "data": [ "train" ], "model": [ "homo_nn" ] } }, "evaluation_0":{ "module": "Evaluation", "input": { "data" :{ "data": ["homo_nn_0.train"] } } } }} this is my dsl file.
  
input data of homo_nn should be "dataio_0.train" instead of "dataio_0.data"
