### ISSUE TITLE
secure information retrieval 单个id隐匿查询

### ISSUE THREAD

**Issue by tujianxin** [FederatedAI/FATE#4038]
fate当前版本是将guest和host方所有交集id的x0,x3值查询出来，如果guest和host方交集只有一个id,对应的x0,x3值查询不出来，当前隐匿查询不支持单个id的查询是吗？

**Comment by tujianxin** [comment]
如果想支持单个id的隐匿查询，需要修改什么地方？

**Comment by tujianxin** [comment]
已经解决

**Comment by zb-zhouhao** [comment]
你好，我也遇到了同样的问题，请问如何解决呢？
