### ISSUE TITLE
您好，联邦的vif（方差膨胀系数）没看到有代码实现，但是在dsl接口中有对应的接口，是纵向联邦的vif没有对应实现吗

### ISSUE THREAD

**Issue by Tringname** [FederatedAI/FATE#4039]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by weiwee** [comment]
是的 目前只有本地的vif 联邦的vif方案存在但是复杂度太高了 目前并没有实现
