### ISSUE TITLE
使用pipeline建立nn模型时报错

### ISSUE THREAD

**Issue by Aexcellent** [FederatedAI/FATE#4049]
![image](https://user-images.githubusercontent.com/33534276/174574713-66a08c94-297a-46b7-9b36-b62f9ecaf902.png)
报错代码位置:
![image](https://user-images.githubusercontent.com/33534276/174574507-bcf6e5b2-2d4b-4cb9-8d7b-55637fbbcb14.png)
示例中的keras.layers.core.Dense与tensorflow.python.keras.engine.base_layer.Layer
isinstance总为false

**Comment by mgqa34** [comment]
Give more details like  "executable code", do you modify something? Examples in fate are always tested before release.

**Comment by Aexcellent** [comment]
tensorflow版本影响，回退至2.3.0，不报错
