### ISSUE TITLE
单机部署后如何使用在线预测功能？

### ISSUE THREAD

**Issue by zlt2000** [FederatedAI/FATE#4057]
场景：基于 [官方部署文档](https://fate.readthedocs.io/en/latest/zh/deploy/standalone-deploy/) 单机部署了环境，然后进行模型训练后，想使用在线预测功能。

问题：由于 `standalone-deploy` 只部署了 `FATE-Flow` 和 `FATE-Board` 两个服务，缺少 `FATE-Serving` 服务，无法使用 **在线预测功能**，请问在单机环境下如何部署 `FATE-Serving` 服务，有没有相关文档。

**Comment by mgqa34** [comment]
Standalone does not support publish model to Fate-Serving, use cluster deploy instead.
