### ISSUE TITLE
different prediction result from same prediction data 

### ISSUE THREAD

**Issue by yangchun222001** [FederatedAI/FATE#4066]
**Describe the bug**
host and guest have same prediction data but get different prediction result
model: homo secure boosting 

**To Reproduce**
environment: docker deploy cluster
training: HomoSecureBoost

prediction data: 
    host: {sid: 127, x1:  1882} 
    guest: {sid: 127, x1:  1882} 

prediction result:
    host: 1315.755862
    guest: 803.990449

**Expected behavior**
prediction result from host and guest are supposed to be the same

**Screenshots**
<img width="255" alt="1656466106047" src="https://user-images.githubusercontent.com/7354609/176331524-2933b033-e4e0-4c22-983b-933b60f6fff8.png">
<img width="960" alt="1656465926646" src="https://user-images.githubusercontent.com/7354609/176331157-55a2fe89-a731-4049-b123-08b332213a7c.png">
<img width="769" alt="1656466001396" src="https://user-images.githubusercontent.com/7354609/176331295-ed0db23d-6be1-4fb5-9f33-1a065538b7dc.png">
<img width="773" alt="1656466042191" src="https://user-images.githubusercontent.com/7354609/176331356-1b4de053-7b69-48d1-ad5c-42a21e6caf46.png">
<img width="770" alt="1656466074551" src="https://user-images.githubusercontent.com/7354609/176331445-c3237627-30e7-4cf2-8a40-f13827121fad.png">

**Comment by yangchun222001** [comment]
for the config info:

training:
```python
    pipeline = PipeLine().set_initiator(role='guest', party_id=guest).set_roles(guest=guest, host=host, arbiter=arbiter)
    
    reader_0 = Reader(name="reader_0")
    reader_0.get_party_instance(role='guest', party_id=guest).component_param(table=guest_train_data)
    reader_0.get_party_instance(role='host', party_id=host).component_param(table=host_train_data)
    
    data_transform_0 = DataTransform(name="data_transform_0")
    data_transform_0.get_party_instance(
        role='guest',
        party_id=guest).component_param(
        with_label=True,
        output_format="dense",
        label_type="float")
    data_transform_0.get_party_instance(
        role='host',
        party_id=host).component_param(
        with_label=True,
        output_format="dense",
        label_type="float")
    

    homo_secureboost_0 = HomoSecureBoost(name="homo_secureboost_0",
                                         num_trees=50,
                                         task_type='regression',
                                         objective_param={"objective": "lse"},
                                         tree_param={
                                             "max_depth": 50
                                         },
                                         validation_freqs=1
                                         )


    pipeline.add_component(reader_0)
    pipeline.add_component(data_transform_0, data=Data(data=reader_0.output.data))
    pipeline.add_component(homo_secureboost_0, data=Data(train_data=data_transform_0.output.data))
```

prediction:
```python
    pipeline = PipeLine.load_model_from_file(model)
    pipeline.deploy_component([pipeline.data_transform_0, pipeline.homo_secureboost_0])

    predict_pipeline = PipeLine()  
    
    reader_1 = Reader(name="reader_1")
    reader_1.get_party_instance(role='guest', party_id=guest).component_param(table=guest_predict_data)
    reader_1.get_party_instance(role='host', party_id=host).component_param(table=host_predict_data)

    predict_pipeline.add_component(reader_1)
    predict_pipeline.add_component(pipeline, data=Data(predict_input={pipeline.data_transform_0.input.data: 
reader_1.output.data}))
    predict_pipeline.predict()
```

parts of training data:
sid,x1,y
70,621,1151
71,1151,807
72,807,741
73,741,1429
74,1429,688
75,688,801
76,801,931
77,931,1343
78,1343,691
79,691,1564
80,1564,1459
81,1459,1458
82,1458,1201
.....

**Comment by mgqa34** [comment]
Please give the version of fate.  Moreover, it will be much better if full dataset is given.

**Comment by yangchun222001** [comment]
**host training data：**
sid,x1,y
70,621,1151
71,1151,807
72,807,741
73,741,1429
74,1429,688
75,688,801
76,801,931
77,931,1343
78,1343,691
79,691,1564
80,1564,1459
81,1459,1458
82,1458,1201
83,1201,1403
84,1403,1527
85,1527,902
86,902,1371
87,1371,1697
88,1697,1579
89,1579,1168
90,1168,1545
91,1545,1104
92,1104,1144
93,1144,1484
94,1484,1318
95,1318,883
96,883,1344
97,1344,1769
98,1769,1195
99,1195,933
100,933,1606
101,1606,1810
102,1810,1162
103,1162,1069
104,1069,1204
105,1204,993
106,993,1126
107,1126,1234
108,1234,1318
109,1318,1704
110,1704,1381
111,1381,1706
112,1706,1020
113,1020,1675
114,1675,1869
115,1869,1199
116,1199,1182
117,1182,1355
118,1355,1668
119,1668,1364
120,1364,1731
121,1731,1765
122,1765,1707
123,1707,1710
124,1710,1738
125,1738,1443
126,1443,1882


**guest training data：**
sid,x1,y
0,462,339
1,339,368
2,368,621
3,621,527
4,527,389
5,389,999
6,999,134
7,134,299
8,299,328
9,328,894
10,894,879
11,879,254
12,254,984
13,984,988
14,988,769
15,769,639
16,639,1003
17,1003,514
18,514,988
19,988,327
20,327,491
21,491,390
22,390,576
23,576,476
24,476,733
25,733,436
26,436,933
27,933,540
28,540,584
29,584,596
30,596,1072
31,1072,970
32,970,385
33,385,562
34,562,530
35,530,784
36,784,1000
37,1000,1022
38,1022,1280
39,1280,1249
40,1249,1289
41,1289,487
42,487,784
43,784,635
44,635,1150
45,1150,561
46,561,548
47,548,1270
48,1270,775
49,775,911
50,911,1320
51,1320,1013
52,1013,1037
53,1037,1327
54,1327,1229
55,1229,656
56,656,1018
57,1018,1337
58,1337,1253
59,1253,1284
60,1284,904
61,904,1288
62,1288,1459
63,1459,1041
64,1041,1269
65,1269,1486
66,1486,1055
67,1055,1143
68,1143,816
69,816,621

**Comment by talkingwallace** [comment]
Hi！ Could you please provide the model files or the origin dataset, if possible? So that we can reproduce the problem locally. Thanks.

**Comment by yangchun222001** [comment]
> 

thank you for your reply, the version I used is 1.7.2 docker compose deployment, and the full dataset is attached above. thanks.

**Comment by yangchun222001** [comment]
> Please give the version of fate. Moreover, it will be much better if full dataset is given.

thank you for your reply, the version I used is 1.7.2 docker compose deployment, and the full dataset is attached above. thanks.

**Comment by talkingwallace** [comment]
Hi! This problem is caused by init-score initialization. In the regression task, init scores are computed by averaging labels, so guest/host models have different init scores. This causes the difference in predicted results. 
Thanks for your feedback, we ll fix this in the following version.
