### ISSUE TITLE
跑fateboard出现问题

### ISSUE THREAD

**Issue by sy0507** [FederatedAI/FATE#4073]
在运行fateboard的时候报错system error ，然后看了error log，发现报了一个数据库的错误，接下来看了官方文档，说单机版要下sqlite，请问是随便下一个版本，然后修改properties嘛？这样可以生效嘛？

**Comment by sy0507** [comment]
您好，是具体有什么命令吗？还是初始化的时候会安装？因为我用那个初始化命令发现有很多包没装好，然后一个一个自己装的，别的都是正常的，只有fateboard有问题，请问您遇到过这个问题吗？版本是1.6.0

**Comment by talkingwallace** [comment]
是使用的ubuntu还是什么系统吗？一般来说跑完是可以直接完成初始化的，可能初始化脚本有bug 不妨试一下最新的1.8

**Comment by sy0507** [comment]
一直没解决，没办法只能换成docker版本的，比较轻松就搞定了



------------------&nbsp;Original message&nbsp;------------------
From: "Chen"; 
Sendtime: Monday, Jul 4, 2022 4:26 PM
To: "FederatedAI/FATE"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [FederatedAI/FATE] 跑fateboard出现问题 (Issue #4073)





 
是使用的ubuntu还是什么系统吗？一般来说跑完是可以直接完成初始化的，可能初始化脚本有bug 不妨试一下最新的1.8
