### ISSUE TITLE
社区要加油啊，隔壁蚂蚁刚刚开源了他们的隐私计算框架 隐语

### ISSUE THREAD

**Issue by jfly0902** [FederatedAI/FATE#4078]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mgqa34** [comment]
Let's work hard together to make privacy preserving better~.  By the way, it will be much better to discuss technical problems when opening an issue.
