### ISSUE TITLE
FATE1.8 运行10万级数据逻辑回归报错

### ISSUE THREAD

**Issue by lvying0019** [FederatedAI/FATE#4093]
用kubefate的docker方式安装了FATE1.8版本，运行10万*500特征逻辑回归报错，前端页面无报错信息，具体报错内容如下。
Guest日志
![image](https://user-images.githubusercontent.com/62459458/178182421-80fb2c1c-b821-4601-af36-a3e20b006ee2.png)
Host日志
![image](https://user-images.githubusercontent.com/62459458/178182443-7de3a07c-fd5f-44b0-9e9c-9d9b2a2fdb59.png)
页面信息如下：
![image](https://user-images.githubusercontent.com/62459458/178182455-6b1567d9-e541-4145-86b9-659e3ec03b6c.png)
![image](https://user-images.githubusercontent.com/62459458/178182469-65bb6c78-aaea-4fa2-b7c4-00c2644a2118.png)

**Comment by mgqa34** [comment]
看起来这是三方逻辑回归？ 是的话麻烦检查下arbiter日志是否有错误

**Comment by lvying0019** [comment]
补充arbiter日志，日志中没有报错，而是直接终止了。
Arbiter日志
![image](https://user-images.githubusercontent.com/62459458/178190988-f401ec57-254b-4f95-8cee-29c57c9147b3.png)
![image](https://user-images.githubusercontent.com/62459458/178191003-dde4cb0e-f0cd-4c9b-beb3-2ad3aeba6fb0.png)


> 看起来这是三方逻辑回归？ 是的话麻烦检查下arbiter日志是否有错误

**Comment by mgqa34** [comment]
> 补充arbiter日志，日志中没有报错，而是直接终止了。 Arbiter日志 ![image](https://user-images.githubusercontent.com/62459458/178190988-f401ec57-254b-4f95-8cee-29c57c9147b3.png) ![image](https://user-images.githubusercontent.com/62459458/178191003-dde4cb0e-f0cd-4c9b-beb3-2ad3aeba6fb0.png)
> 
> > 看起来这是三方逻辑回归？ 是的话麻烦检查下arbiter日志是否有错误

看了一下图片，任务运行超过72小时了，默认任务超市时间是72小时，可以在job_parameters::common::timeout字段设置下，单位是秒

**Comment by lvying0019** [comment]
> > 补充arbiter日志，日志中没有报错，而是直接终止了。 Arbiter日志 ![image](https://user-images.githubusercontent.com/62459458/178190988-f401ec57-254b-4f95-8cee-29c57c9147b3.png) ![image](https://user-images.githubusercontent.com/62459458/178191003-dde4cb0e-f0cd-4c9b-beb3-2ad3aeba6fb0.png)
> > > 看起来这是三方逻辑回归？ 是的话麻烦检查下arbiter日志是否有错误
> 
> 看了一下图片，任务运行超过72小时了，默认任务超市时间是72小时，可以在job_parameters::common::timeout字段设置下，单位是秒

好的，我试试，谢谢
