### ISSUE TITLE
发起联邦任务时出现parameter to mergefrom() must be instance of same class错误

### ISSUE THREAD

**Issue by ykcirh** [FederatedAI/FATE#4099]
在arm芯片服务器上部署了fate之后，运行run_toy_example.py出现如下错误：
Federated schedule error, Parameter to mergefrom() must be instance of same class: expected basic_meta_pb2.Endpoint got basic_meta_pb2.Endpoint. for field Topic.callback
想请教一下为啥出现这样的错误，然后应该如何处理呢？谢谢～

**Comment by forgivedengkai** [comment]
将 eggroll/core/proto/proxy_pb2.py 文件中  import basic_meta_pb2 as basic__meta__pb2   改为  from eggroll.core.proto import basic_meta_pb2  as basic__meta__pb2   可解决此问题

**Comment by ykcirh** [comment]
将所有容器中eggroll/core/proto/proxy_pb2.py文件修改后还是出现同样的错误，请问这样应该怎么处理呢？

**Comment by dylan-fan** [comment]
看下grpc版本问题

**Comment by ykcirh** [comment]
已解决，需要将所有pb2模块替换

**Comment by gaojunjie03** [comment]
> 已解决，需要将所有pb2模块替换

怎么替换 可以指导一下整个流程不？

**Comment by ykcirh** [comment]
> 流程

将所有类似import basic_meta_pb2 as basic__meta__pb2这种结构的都改为 from eggroll.core.proto import basic_meta_pb2 as basic__meta__pb2

**Comment by liuyanfeng1981** [comment]
请教一下，在arm上部署fate集群，是不是只能allinone部署？我这里部署一直有问题，谢谢

**Comment by ykcirh** [comment]
官方docker-compose，需要修改一下

**Comment by gxcuit** [comment]
> 官方docker-compose，需要修改一下



> 

请问是怎么修改的呢

**Comment by ykcirh** [comment]
> > 官方docker-compose，需要修改一下
> 
> 因为我看dockerhub上没有arm的镜像

1. python的各个模块在arm系统官网找到对应版本进行替换
2. 将所有类似import basic_meta_pb2 as basic__meta__pb2这种结构的都改为 from eggroll.core.proto import basic_meta_pb2 as basic__meta__pb2
有其他问题或者细节可以直接微信沟通

**Comment by jiejielu-0309** [comment]
> > > 官方docker-compose，需要修改一下
> > 
> > 
> > 因为看dockerhub上没有arm的镜像
> 
> 1. python 决策模块在 arm系统官网找到对应版本进行替换
> 2. 我们也类似import basic_meta_pb2 as basic__meta__pb2这种结构都改为 from eggroll.core.proto import basic_meta_pb2 as basic__meta__pb2
>    有其他问题或者细节可以直接微信沟通

大佬，可以加个微信不，想请教下arm上部署fate问题
