### ISSUE TITLE
use standalone_fate:1.8.0,can not upload data

### ISSUE THREAD

**Issue by yyf1986** [FederatedAI/FATE#4107]
**Describe the bug**

**To Reproduce**
export version=1.8.0
docker pull federatedai/standalone_fate:${version}
docker run -d --name standalone_fate -p 8080:8080 federatedai/standalone_fate:${version}
docker exec -it $(docker ps -aqf "name=standalone_fate") bash
vi aaa
`
{
    "file": "examples/data/breast_hetero_guest.csv",
    "id_delimiter": ",",
    "head": 1,
    "partition": 1,
    "namespace": "experiment",
    "table_name": "breast_hetero_guest",
    "storage_engine": "EGGROLL",
    "use_local_data": 0
}
`
flow data upload -c aaaa
```
{
    "data": {
        "board_url": "http://127.0.0.1:8080/index.html#/dashboard?job_id=202207150852574621610&role=local&party_id=0",
        "code": 0,
        "dsl_path": "/data/projects/fate/fateflow/jobs/202207150852574621610/job_dsl.json",
        "job_id": "202207150852574621610",
        "logs_directory": "/data/projects/fate/fateflow/logs/202207150852574621610",
        "message": "success",
        "model_info": {
            "model_id": "local-0#model",
            "model_version": "202207150852574621610"
        },
        "namespace": "experiment",
        "pipeline_dsl_path": "/data/projects/fate/fateflow/jobs/202207150852574621610/pipeline_dsl.json",
        "runtime_conf_on_party_path": "/data/projects/fate/fateflow/jobs/202207150852574621610/local/0/job_runtime_on_party_conf.json",
        "runtime_conf_path": "/data/projects/fate/fateflow/jobs/202207150852574621610/job_runtime_conf.json",
        "table_name": "breast_hetero_guest",
        "train_runtime_conf_path": "/data/projects/fate/fateflow/jobs/202207150852574621610/train_runtime_conf.json"
    },
    "jobId": "202207150852574621610",
    "retcode": 0,
    "retmsg": "success"
}
```
flow table info -n experiment -t breast_hetero_guest
```
{
    "data": {
        "address": null,
        "count": 0,
        "enable": true,
        "exist": 0,
        "namespace": "experiment",
        "origin": null,
        "partition": null,
        "schema": null,
        "table_name": "breast_hetero_guest"
    },
    "retcode": 0,
    "retmsg": "success"
}
```
cd /data/projects/fate/fateflow/logs/202207150852574621610
cat fate_flow_schedule_error.log
```
[ERROR] [2022-07-15 08:53:09,113] [202207150852574621610] [1431:139914187827008] - [_session.get_session_from_record] [line:397]: No module named 'eggroll'
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yyf1986** [comment]
使用fateflow/examples/upload/upload_guest.json这个文件可以创建成功。
看到了一个引擎"storage_type": "LMDB"，但是我在文档里面没看到这种引擎。
https://fate-flow.readthedocs.io/en/latest/zh/fate_flow_data_access/

**Comment by mgqa34** [comment]
> 使用fateflow/examples/upload/upload_guest.json这个文件可以创建成功。 看到了一个引擎"storage_type": "LMDB"，但是我在文档里面没看到这种引擎。 https://fate-flow.readthedocs.io/en/latest/zh/fate_flow_data_access/

单机版不是使用的EGGROLL，用默认配置上传即可

**Comment by yyf1986** [comment]
@mgqa34 的确是这样，社区的文档有点不太全。
