### ISSUE TITLE
fate on spark 是否支持以cluster模式提交任务

### ISSUE THREAD

**Issue by mamingliang-myy** [FederatedAI/FATE#4124]
我们在测试fate on spark ，spark集群是现有大数据集群，提交fate任务时，只支持client模式。用cluster模式提交任务时，fate_flow部分报错。
请问目前是否支持以cluster（--deploy-mode cluster)模式提交任务。
fate版本：1.6

**Comment by dylan-fan** [comment]
暂时不支持
