### ISSUE TITLE
hetero_pearson 报AttributeError: 'NoneType' object has no attribute 'count'错误

### ISSUE THREAD

**Issue by alikobe** [FederatedAI/FATE#4134]
# New Algorithm

- Name:hetero_pearson
-test_hetero_pearson_default_conf.json
{
    "dsl_version": 2,
    "initiator": {
        "role": "guest",
        "party_id": 9999
    },
    "role": {
        "host": [
            10000
        ],
        "guest": [
            9999
        ]
    },
    "component_parameters": {
        "common": {
            "hetero_pearson_0": {
                "column_indexes": -1
            }
        },
        "role": {
            "guest": {
                "0": {
                    "data_transform_0": {
                        "with_label": true,
                        "output_format": "dense"
                    },
                    "reader_0": {
                        "table": {
                            "name": "200w_200d_b",
                            "namespace": "experiment"
                        }
                    }
                }
            },
            "host": {
                "0": {
                    "data_transform_0": {
                        "with_label": false
                    },
                    "reader_0": {
                        "table": {
                            "name": "200w_200d_a",
                            "namespace": "experiment"
                        }
                    }
                }
            }
        }
    }
}

error msg:
[ERROR] [2022-07-21 20:52:11,267] [202207212051167416080] [7236:140270744303424] - [task_executor._run_] [line:243]: 'NoneType' object has no attribute 'count'
2
Traceback (most recent call last):
3
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
4
    cpn_output = run_object.run(cpn_input)
5
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 236, in run
6
    self._run(cpn_input=cpn_input)
7
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 311, in _run
8
    this_data_output = func(*real_param)
9
  File "/data/projects/fate/fate/python/federatedml/util/data_transform.py", line 969, in fit
10
    data_inst = self.transformer.read_data(data_inst, "fit")
11
  File "/data/projects/fate/fate/python/federatedml/util/data_transform.py", line 155, in read_data
12
    abnormal_detection.empty_table_detection(input_data)
13
  File "/data/projects/fate/fate/python/federatedml/util/abnormal_detection.py", line 27, in empty_table_detection
14
    num_data = data_instances.count()
15
AttributeError: 'NoneType' object has no attribute 'count'

**Comment by weiwee** [comment]
hi @alikobe, as the error message indicated, the data transform complaints that input data is `None`.  You may check if you have correctly uploaded data and correctly configured the conf and dsl

**Comment by alikobe** [comment]
The problem has been solved, thank you
