### ISSUE TITLE
最新版本的 fate 的 fastjson、log4j、jolokia 有安全漏洞

### ISSUE THREAD

**Issue by alikobe** [FederatedAI/FATE#4153]
fate version：1.8.0
最新版本的 fate 的 fastjson、log4j、jolokia 可能有“代码执行漏洞”

麻烦fix一下

**Comment by dylan-fan** [comment]
这个应该是eggroll仓库依赖第三方包，我们会在eggroll仓库更新下依赖。

**Comment by dylan-fan** [comment]
fastjson、log4j、jolokia 请问你在哪个组件中检测出来的，board 还是eggroll？ 有建议升级到哪个版本吗

**Comment by dylan-fan** [comment]
https://github.com/FederatedAI/FATE-Board/pull/141/files，修复了fastjson、log4j。暂时没找到jolokia。请提供下jolokia信息

**Comment by alikobe** [comment]
> fastjson、log4j、jolokia 请问你在哪个组件中检测出来的，board 还是eggroll？ 有建议升级到哪个版本吗

board
