### ISSUE TITLE
secureboost训练完成后，guest侧和host侧通过component_output_model都可以获得完整的树结构，这样不会造成模型在一侧泄漏吗

### ISSUE THREAD

**Issue by yidiexiaocaipx** [FederatedAI/FATE#4164]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by talkingwallace** [comment]
hi
目前主流的纵向树模型都是有如此的设定，对于各方来说，都无法得知树结构中的敏感信息。各方只能知道节点归属哪一方的，使用的特征及分裂值这些都是各自保存的，对于guest标签提供方来说，它存储了树叶子结点weight，其它方无法得知这个信息。
