### ISSUE TITLE
Ansible两方部署完成后，flow test toy单边测试报错。Please check rollSite and fateflow network connectivityrpc request error:...

### ISSUE THREAD

**Issue by liuyucong** [FederatedAI/FATE#4169]
Ansible两方部署完成后，使用命令flow test toy -gid 10000 -hid 10000 进行单边测试报错。请问是什么原因呢。
![WechatIMG81](https://user-images.githubusercontent.com/20422867/182133224-a9638a4c-c69f-4f98-acb9-dc12bd6e128f.jpeg)
两方均部署在了aws云服务器上。

**Comment by fanla2021** [comment]
network connectivityrpc request error,报错显示为网络问题，你排查下两方网络是否珂通信
