### ISSUE TITLE
上传数据出现processor in session meta is not valid错误

### ISSUE THREAD

**Issue by ykcirh** [FederatedAI/FATE#4202]
ARM环境下部署FATE，上传数据时出现如下错误：
[ERROR] [2022-08-03 10:38:25,779] [202208031035192942580] [59:548422602752] - [task_executor._run_] [line:243]: processor in session meta is not valid: <ErSessionMeta(id=202208031035192942580_upload_0_0_local_0, name=, status=ERROR, tag=, processors=[***, len=4], options=[{'eggroll.session.deploy.mode': 'cluster', 'python.venv': 'None', 'eggroll.session.processors.per.node': '4', 'python.path': '/data/projects/fate/fateflow/python::/data/projects/fate/:/data/projects/fate/eggroll/python:/data/projects/fate/fate/python:/data/projects/fate/fateflow/python', 'eggroll.rollpair.inmemory_output': 'True'}]) at 0x7f9eddc208>
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 134, in _run_
    sess.init_computing(computing_session_id=args.session_id, options=session_options)
  File "/data/projects/fate/fate/python/fate_arch/session/_session.py", line 117, in init_computing
    session_id=computing_session_id, options=options
  File "/data/projects/fate/fate/python/fate_arch/computing/eggroll/_csession.py", line 38, in __init__
    self._rp_session = session_init(session_id=session_id, options=options)
  File "/data/projects/fate/eggroll/python/eggroll/core/session.py", line 42, in session_init
    er_session = ErSession(session_id=session_id, options=options)
  File "/data/projects/fate/eggroll/python/eggroll/core/session.py", line 199, in __init__
    self.__session_meta = self._cluster_manager_client.get_or_create_session(session_meta)
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 189, in get_or_create_session
    serdes_type=self.__serdes_type))
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 243, in __check_processors
    raise ValueError(f"processor in session meta is not valid: {session_meta}")
ValueError: processor in session meta is not valid: <ErSessionMeta(id=202208031035192942580_upload_0_0_local_0, name=, status=ERROR, tag=, processors=[***, len=4], options=[{'eggroll.session.deploy.mode': 'cluster', 'python.venv': 'None', 'eggroll.session.processors.per.node': '4', 'python.path': '/data/projects/fate/fateflow/python::/data/projects/fate/:/data/projects/fate/eggroll/python:/data/projects/fate/fate/python:/data/projects/fate/fateflow/python', 'eggroll.rollpair.inmemory_output': 'True'}]) at 0x7f9eddc208>
想请教一下为啥出现这样的错误，然后应该如何处理呢？谢谢～

**Comment by ykcirh** [comment]
已解决，环境变量中venv路径无法识别，修改后正常

**Comment by relinda2019** [comment]
老师，您好，请问您具体是怎么操作修改的呢？我也遇到了同样的问题，麻烦您解答一下哈，谢谢

**Comment by sealofyou** [comment]
遇到相同问题，请问如何解决？

**Comment by sealofyou** [comment]
#### 解决方式
排查方式：

根据FATEBoard排查报错：

```plain
ValueError: processor in session meta is not valid: <ErSessionMeta(id=202410220229346428690_nn_0_0_guest_9999, name=, status=KILLED, tag=, processors=[***, len=4], options=[{'eggroll.session.deploy.mode': 'cluster', 'python.path': '/data/projects/fate/fate/python:/data/projects/fate/fate/python:/data/projects/fate/fateflow/python:/data/projects/fate/eggroll/python', 'eggroll.rollpair.inmemory_output': 'True', 'python.venv': '/data/projects/fate/common/python/venv', 'eggroll.session.processors.per.node': '4'}]) at 0x7fd91230fd00>
```

发现这个跟eggroll有关，查询eggroll报错/data/projects/fate/eggroll/logs/202410220229346428690_nn_0_0_guest_9999 （这里是FATEBoard报错的id）目录。

查询bootstrap-egg_pair-xxx.err发现`egg_pair_bootstrap.sh: unrecognized option '--python-venv'`。

再根据[https://github.com/FederatedAI/FATE/issues/4202](https://github.com/FederatedAI/FATE/issues/4202)的情况断定这个是 **<font style="color:rgb(31, 35, 40);">环境变量中venv路径无法识别</font>**

解决方式：

> issues里的venv有两个: ,所以我怀疑我是因为两个相同的导致的报错


我这里发现venv中python.path有两个`/data/projects/fate/fate/python`，所以在`/data/projects/fate/eggroll/conf/eggroll.properties`将`/data/projects/fate/fate/python`去掉，然后重启服务。（一个是这样改后解决的）

```plain
# 原 
eggroll.resourcemanager.bootstrap.egg_pair.pythonpath=/data/projects/fate/fate/python:/data/projects/fate/fateflow/python:/data/projects/fate/eggroll/python
# 改
eggroll.resourcemanager.bootstrap.egg_pair.pythonpath=/data/projects/fate/fateflow/python:/data/projects/fate/eggroll/python

```

更换报错：

```plain
ValueError: processor in session meta is not valid: <ErSessionMeta(id=202410220301412741650_reader_0_0_guest_9999, name=, status=KILLED, tag=, processors=[***, len=4], options=[{'python.venv': '/data/projects/fate/common/python/venv', 'eggroll.session.processors.per.node': '4', 'eggroll.rollpair.inmemory_output': 'True', 'python.path': '/data/projects/fate/fateflow/python:/data/projects/fate/fate/python:/data/projects/fate/fateflow/python:/data/projects/fate/eggroll/python', 'eggroll.session.deploy.mode': 'cluster'}]) at 0x7fc50e5b2d30>
```

尝试另一个改过的地方：'eggroll.session.processors.per.node': '4',  改为8。

解决了。 ？不知道为啥解决的。

**Comment by sealofyou** [comment]
如果还有问题，提高cpu数量，8核时莫名其妙FATEBoard一直重启，可能是进程被杀导致的这个报错。
![image](https://github.com/user-attachments/assets/98a2f5c5-6a9a-49bb-8fea-246cd410c04f)
16核后FATEBoard问题未解决，但该问题暂时没有再出现。
