### ISSUE TITLE
Unable to view and download output data

### ISSUE THREAD

**Issue by NTang7** [FederatedAI/FATE#4242]
I'm using the standalone version of fate-client. I've successfully completed a train and predict job using homosecureboost for the multi-classification tasks. I have obtained the evaluation results for both trained and predicted jobs.  However, I was unable to obtain neither the trained output data nor the predicted output data.

The output is blank for both the train and test modules. (my dataset size is around 2000 x 7)
<img width="1181" alt="MG79" src="https://user-images.githubusercontent.com/100176448/185577641-83d6922d-d499-4ac7-9bb6-0370685042af.png">
and I tried to use the command to download it, and the errors msg pops out.
<img width="687" alt="MG80" src="https://user-images.githubusercontent.com/100176448/185577965-99d50471-0c53-4abf-a571-e80ae3ed9716.png">
![MG82](https://user-images.githubusercontent.com/100176448/185578414-700731c9-7325-45af-a4d4-e66cb420ce9d.jpeg)

here is my setup, 
<img width="585" alt="MG81" src="https://user-images.githubusercontent.com/100176448/185578476-a1e9fcf4-e689-4756-9c67-6b1a09239523.png">

Could you please let me know what the issue could be and how could it be fixed?

Thanks!

**Comment by BiancaZYCao** [comment]
Hi, you can check ERROR.log about details under "/data/projects/fate/fateflow/logs/fate_flow"
Please check if the page you open is for right party as arbiter will not show any data outputs.
