### ISSUE TITLE
[Question] How to correctly give different metrics to evaluate the performance of the model?

### ISSUE THREAD

**Issue by vic4code** [FederatedAI/FATE#4243]
Hi, I tried to run the `pipeline_hetero_sbt_binary.py` with my own data and follow the scripts to inspect the other metrics like `Accuarcy`, `precision`, `recall` instead of just the default metrics `auc` and `ks` for the binary classification task. 

I found two places to set the list of metrics in the parameters of the class, one is in the `Component` of the model, as follows.
```
# secure boost component
    hetero_secure_boost_0 = HeteroSecureBoost(name="hetero_secure_boost_0",
                                              num_trees=5,
                                              task_type="classification",
                                              objective_param={"objective": "cross_entropy"},
                                              encrypt_param={"method": "Paillier"},
                                              tree_param={"max_depth": 3},
                                              complete_secure=True,
                                              validation_freqs=1,
                                              # metrics=["accuracy", "precision", "recall"],
                                              )
```
Another way is to give the metrics to the `Evaluation` `Component` like this.

```
# evaluation component
    evaluation_0 = Evaluation(name="evaluation_0", eval_type="binary", metrics = ["accuracy", "precision", "recall"])

```

However, both of them did not work as expected and still show the default results, how to properly give different metrics to evaluate the performance of the model?

Thanks!

**Comment by talkingwallace** [comment]
Currently in binary tasks pipeline can only get single value metrics as return, however 'accuracy', 'precision', and 'recall' are displayed in curves in the binary tasks. You can see these curves on the fateboard.

**Comment by vic4code** [comment]
Thanks for the reply, I will try it!
