### ISSUE TITLE
FATE can it be installed and run in the environment of python3.7?

### ISSUE THREAD

**Issue by Averryjj** [FederatedAI/FATE#4244]
Does FATE work on environments with python version greater than 3.7? Is python3.6.5 mandatory for python version?

**Comment by mgqa34** [comment]
Yes, both python3.6 & 3.7 are supported in Fate's version < 1.9.0. But in fate v1.9.0 or later, python will be upgraded to python3.8+

**Comment by amyseoj1** [comment]
Hello @mgqa34,

I don't have any software engineering background, and I am having difficulties getting FATE started. 
I followed the standalone-docker deployment guide and executed docker container, but I am not sure how to run the example scripts within the container. I tried to open a Jupyter environment and run the files, but the Jupiter server does not work. 

I tried to run below commands, but the Jupyter server cannot be found. Could you tell me how you open Jupyter notebook within the docker container?

$ pip install notebook fate-client
$ jupyter notebook --ip=0.0.0.0 --port=20000 --allow-root --debug --no-browser --NotebookApp.token='' --NotebookApp.password=''
