### ISSUE TITLE
homo_nn中创建pl.Trainer的时候，max_epoch和min_epoch赋值都是total_epoch，那当触发early_stop的epoch会小于min_epoch，不会停止训练

### ISSUE THREAD

**Issue by xixisleep** [FederatedAI/FATE#4252]
homo_nn中创建pl.Trainer的时候，max_epoch和min_epoch赋值都是total_epoch，那当触发early_stop的epoch会小于min_epoch，不会停止训练

![1661222552345](https://user-images.githubusercontent.com/30097350/186058479-ed2671f1-0b9a-418c-a793-c505d1d1ace0.png)

**Comment by weiwee** [comment]
@xixisleep 谢谢 #4253 修复了这个问题 将在月底随1.9.0版本发布
