### ISSUE TITLE
sh init.sh init failed when trying to install standalone 

### ISSUE THREAD

**Issue by mahmoudsajjadi** [FederatedAI/FATE#4259]
When I execute sh init.sh init, I get an error like this:

found service conf: /mnt/c/Python/fate/standalone_fate_master_1.5.1/conf/service_conf.yaml
fate flow http port: 9380, grpc port: 9360

service.sh: 105: Syntax error: Bad for loop variable
service.sh: 23: export: Files/CMake/bin:/snap/bin:/mnt/c/Python/fate/standalone_fate_master_1.5.1/jdk/jdk1.8.0_192/bin: bad variable name

To Reproduce

install fate via bash init.sh init

![image](https://user-images.githubusercontent.com/73462745/186208145-9406f1f3-f18f-42be-99dc-dd2da6f20ae2.png)

**Desktop 
 - OS: Ubuntu

**Comment by talkingwallace** [comment]
This happens when you run init.sh of 1.5 version on Ubuntu.
1. You can install standalone on CentOS
2. Use the latest version (1.8) on Ubuntu

**Comment by mahmoudsajjadi** [comment]
Hi @talkingwallace 

Thank you for your help. I am trying to download v1.8.0 but it seems it is not available. 

 wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone_fate_master_1.8.0.tar.gz


--2022-08-25 08:01:57--  https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone_fate_master_1.8.0.tar.gz
Resolving webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)... 159.75.57.69, 159.75.57.36
Connecting to webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)|159.75.57.69|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-25 08:01:59 ERROR 404: Not Found.

**Comment by mgqa34** [comment]
> Hi @talkingwallace
> 
> Thank you for your help. I am trying to download v1.8.0 but it seems it is not available.
> 
> wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone_fate_master_1.8.0.tar.gz
> 
> --2022-08-25 08:01:57-- https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/standalone_fate_master_1.8.0.tar.gz Resolving webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)... 159.75.57.69, 159.75.57.36 Connecting to webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)|159.75.57.69|:443... connected. HTTP request sent, awaiting response... 404 Not Found 2022-08-25 08:01:59 ERROR 404: Not Found.

two ways you can try:
a.  the download link is wrong, refer this [tutorial](https://github.com/FederatedAI/FATE/tree/master/deploy/standalone-deploy#32-get-the-installation-package)
b. deploy by source code if the network is slow. read this [doc](https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md#source-code-deployment-fate-standalone)
