### ISSUE TITLE
About Homogeneous LR

### ISSUE THREAD

**Issue by StuTang** [FederatedAI/FATE#4274]
Sorry, I'm a noob and I don't know if my question is helpful.
1. I learned from the experts in the video that in the horizontal federated learning of FATE, all modules except Homogeneous LR do not use homomorphic encryption. Does this mean that horizontal LR uses homomorphic encryption, but the [official document](https://fate.readthedocs.io/en/latest/zh/federatedml_component/logistic_regression/) about the detail of Homogeneou LR is the solution proposed by Google at CCS in 2017 (where the fault-tolerance mechanism seems to be inconsistent with reality), I don't know if there is a problem here.
2. I would also like to ask why the Homogeneous LR module is separated from the security aggregation module, is it because the two are incompatible or something else.

**Comment by talkingwallace** [comment]
Secure aggregation is used by several algorithms, so it is a public module

**Comment by StuTang** [comment]
> Secure aggregation is used by several algorithms, so it is a public module

Thks for solving one of my question. Actually, i prefer to know that if the homogeneous module of the FATE Framework contains a fault tolerance mechanism and  if the homogeneous LR module is designed by homomorphic encryption

**Comment by talkingwallace** [comment]
> > Secure aggregation is used by several algorithms, so it is a public module
> 
> Thks for solving one of my question. Actually, i prefer to know that if the homogeneous module of the FATE Framework contains a fault tolerance mechanism and if the homogeneous LR module is designed by homomorphic encryption

Hi, Homo LR supports secure aggregation and homomorphic encryption. I don't really know what does 'fault tolerance mechanism' means. Could you explain that?

**Comment by StuTang** [comment]
> 

Generally, what I mean by fault tolerance is that some computing nodes cannot participate in the current round of work due to crashes or network congestion during the model iteration process.

**Comment by talkingwallace** [comment]
> 
For now, fate does not support this mechanism in Homo-NN.  Maybe you can modify the original codes to realize this function.
