### ISSUE TITLE
model training based mnist dataset (standalon + pytorch)

### ISSUE THREAD

**Issue by zhangyimeng960916** [FederatedAI/FATE#4297]
How to use the mnist_nn_testsuite.json file when I perform model training (pytorch) based on the mnist dataset?   thanks!
  --- standalone,    fate_version:1.7.1.1

**Comment by talkingwallace** [comment]
hi, there is a documentation in examples/dsl/v2/homo_nn. It shows you how to use the mnist example.

**Comment by BiancaZYCao** [comment]
You may try MNIST example without using testsuite: https://github.com/FederatedAI/FATE/tree/master/examples/dsl/v2/homo_nn/mnist_demo
1. use `fate_test data download -t mnist` to download dataset
2. use `flow table bind -c bind_local_path.json` to bind dataset. 
The dataset consists of: config.yaml, filenames, targets, images (a folder with 60,000 jpg files inside) 
3. use `flow job submit -c mnist_conf.json -d mnist_dsl.json`

If you want to use testsuite to run the collection of jobs, you will need to use fate_test cmd https://github.com/FederatedAI/FATE/blob/3ee02ea81c62d60353b2df40e141529b151d7c67/doc/tutorial/fate_test_tutorial.md#command-types
`fate_test suite -i <path contains *testsuite.json>`
