### ISSUE TITLE
pipeline error: no such column t1.f_origin

### ISSUE THREAD

**Issue by patricxu** [FederatedAI/FATE#4298]
I have deployed a standalone FATE, and passed all the unit test. However, an error occured when I upload the demo dataset wich pipeline or try to run any pipeline demo.

![image](https://user-images.githubusercontent.com/9252137/187360022-3134b9de-4741-4c87-b08c-8079abbdd2bf.png)

**Comment by mgqa34** [comment]
It seems that you have upgraded  source code of fateflow from older version but the fields in db are not upgraded, remove fate_sqlite.db  or  drop database fate_flow.

**Comment by patricxu** [comment]
Fixed This by:
1. remove the code 
`    # f_origin = CharField(max_length=50, default='')
    # f_disable = BooleanField(default=False)`
  in python/fate_arch/metastore/db_models.py 
2. delete fate_sqlite.db
3. bash fateflow/bin/service.sh restart
