### ISSUE TITLE
FederatedAI/FATE/tree/master/examples/dsl/v2例子出现error

### ISSUE THREAD

**Issue by Alan-JW** [FederatedAI/FATE#4313]
**Describe the bug**
当我运行FederatedAI/FATE/tree/master/examples/dsl/v2/hetero_logistic_regression中的例子时候，
![image](https://user-images.githubusercontent.com/74579183/188264657-dcb4f182-b70b-47f8-9d66-05b652524623.png)
![image](https://user-images.githubusercontent.com/74579183/188264667-7dd71184-2b9d-4895-9140-68af4b8c9808.png)
出现了这个bug

使用的FATE的最新单机部署版本利用docker部署的。

**Comment by mgqa34** [comment]
Please upload example data first.

**Comment by Alan-JW** [comment]
> upload example data

 How to upload example data?

**Comment by mgqa34** [comment]
Conf [uploading guide](./https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/dsl_conf/upload_data_guide.md)
Pipeline [uploading guide](./https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb)

**Comment by Alan-JW** [comment]
What data needs to be uploaded for each example here?
![image](https://user-images.githubusercontent.com/74579183/188475924-9c7a8a77-1b20-4453-b9ce-04c21ef0806b.png)

**Comment by mgqa34** [comment]
Have a look at this [link](https://github.com/FederatedAI/FATE/tree/master/examples/data#data-set-naming-rule)，and find  out which datasets are needed.  Or uploading all examples's data by [fate_test](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_test_tutorial.md#command-types) : fate_test data upload -t all_examples. If you want to use fate_test to upload all examples's data,  make sure that your fate's version >= 1.8.0
