### ISSUE TITLE
有关FATE联邦学习横向联邦学习的问题

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4314]
场景：参与方A和B使用FATE的HomoSecureBoost训练得到一个横向联邦学习模型。在得到模型后，参与方A想要使用这个模型进行预测，因此只需要A上传预测数据。在执行过程中发现无法执行预测任务。
问题：在横向联邦学习中训练得到模型是分布式存储在两个参与方的吗？如果一方想使用模型进行预测，另一方只作为计算方可以吗？
希望能够得到您的解答

**Comment by mgqa34** [comment]
Homo SecureBoost supports predicting in a single party, changes `role in predict conf and delete redundant role or parties in  component_parameters will work.

**Comment by oceanqdu** [comment]
> Homo SecureBoost supports predicting in a single party, changes `role in predict conf and delete redundant role or parties in component_parameters will work.

请问一下您，如果是使用pipeline进行预测应该怎么更改配置？

**Comment by oceanqdu** [comment]
> 
例如再我的代码中
`from pipeline.backend.pipeline import PipeLine
from pipeline.component import Reader, DataTransform, Intersection, HeteroSecureBoost, Evaluation
from pipeline.interface import Data
import os




pipeline = PipeLine.load_model_from_file('../model/bank_saved_test1.pkl')
pipeline.deploy_component([pipeline.data_transform_0,  pipeline.scale_0,pipeline.homo_secureboost_0])


reader_1 = Reader(name="reader_1")
reader_1.get_party_instance(role="guest", party_id=9999).component_param(table={"name": "bank_guest_predict", "namespace": "experiment"})
#reader_1.get_party_instance(role="host", party_id=10000).component_param(table={"name": "bank_host_predict", "namespace": "experiment"})



evaluation_0 = Evaluation(name="evaluation_0", eval_type="binary")


predict_pipeline = PipeLine()
predict_pipeline.add_component(reader_1)\
                .add_component(pipeline, 
                               data=Data(predict_input={pipeline.data_transform_0.input.data: reader_1.output.data}))\
                .add_component(evaluation_0, data=Data(data=pipeline.homo_secureboost_0.output.data))

predict_pipeline.predict()`
应该做哪些修改，才能够使得能够在单个参与方中进行预测？希望您能够解答一下

**Comment by mgqa34** [comment]
If you want to predict in a single party, use conf to submit job instead of pipeline. 
For examples, in this [conf](https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/homo_secureboost/test_predict_conf.json) ，delete guest & arbiter in role, also delete guest reader in component_parameters, then you can do predicting jobs in host:10000

**Comment by oceanqdu** [comment]
> If you want to predict in a single party, use conf to submit job instead of pipeline. For examples, in this [conf](https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/homo_secureboost/test_predict_conf.json) ，delete guest & arbiter in role, also delete guest reader in component_parameters, then you can submit predicting jobs in host:10000

请问横向联邦学习支持单个party进行预测吗？例如hetero_secure_boost模块。

**Comment by BiancaZYCao** [comment]
Hope this helps if you want to use pipeline to predict results. 
Link: https://github.com/FederatedAI/FATE/blob/deature-1.7.1-fate-test/examples/pipeline/homo_sbt/pipeline-homo-sbt-binary-with-predict.py
```
# predict
# deploy required components
pipeline.deploy_component([data_transform_0, homo_secureboost_0])

predict_pipeline = PipeLine()
# add data reader onto predict pipeline
predict_pipeline.add_component(reader_1)
# add selected components from train pipeline onto predict pipeline
# specify data source
predict_pipeline.add_component(pipeline,
                               data=Data(predict_input={pipeline.data_transform_0.input.data: reader_1.output.data}))
# run predict model
predict_pipeline.predict()
```

**Comment by BiancaZYCao** [comment]
> > If you want to predict in a single party, use conf to submit job instead of pipeline. For examples, in this [conf](https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/homo_secureboost/test_predict_conf.json) ，delete guest & arbiter in role, also delete guest reader in component_parameters, then you can submit predicting jobs in host:10000
> 
> 请问横向联邦学习支持单个party进行预测吗？例如hetero_secure_boost模块。

BTW，Hetero 是纵向， homo是横向

**Comment by oceanqdu** [comment]
> Hope this helps if you want to use pipeline to predict results. Link: https://github.com/FederatedAI/FATE/blob/deature-1.7.1-fate-test/examples/pipeline/homo_sbt/pipeline-homo-sbt-binary-with-predict.py
> 
> ```
> # predict
> # deploy required components
> pipeline.deploy_component([data_transform_0, homo_secureboost_0])
> 
> predict_pipeline = PipeLine()
> # add data reader onto predict pipeline
> predict_pipeline.add_component(reader_1)
> # add selected components from train pipeline onto predict pipeline
> # specify data source
> predict_pipeline.add_component(pipeline,
>                                data=Data(predict_input={pipeline.data_transform_0.input.data: reader_1.output.data}))
> # run predict model
> predict_pipeline.predict()
> ```

感谢您的回复，在这个demo中的预测过程同样需要两方提供预测数据，
`    reader_1.get_party_instance(role='guest', party_id=guest).component_param(table=guest_validate_data)
    reader_1.get_party_instance(role='host', party_id=host).component_param(table=host_validate_data)`
我的疑问是能否使用pipeline实现单个参与方上传数据进行预测？
第二个问题是纵向联邦学习是不是无法实现单个party进行预测？例如hetero_secure_boost模块。

假设在这样一个场景中：参与方A和参与方B共同训练一个纵向联邦学习模型。其中A拥有五个特征，B拥有5个特征和真实标签。训练完成后，假设在预测过程中，A使用了一条新的数据a，这条数据所属的客户在B中不存在，那么参与方A是不是就无法使用纵向联邦学习模型对a这条数据进行预测呢？
在预测阶段所使用的样本数据是否也需要多方进行隐私集合求交才能够确定是否能进行预测？

**Comment by BiancaZYCao** [comment]
> 感谢您的回复，在这个demo中的预测过程同样需要两方提供预测数据， ` reader_1.get_party_instance(role='guest', party_id=guest).component_param(table=guest_validate_data) reader_1.get_party_instance(role='host', party_id=host).component_param(table=host_validate_data)` 我的疑问是能否使用pipeline实现单个参与方上传数据进行预测？ 第二个问题是纵向联邦学习是不是无法实现单个party进行预测？例如hetero_secure_boost模块。
> 
> 假设在这样一个场景中：参与方A和参与方B共同训练一个纵向联邦学习模型。其中A拥有五个特征，B拥有5个特征和真实标签。训练完成后，假设在预测过程中，A使用了一条新的数据a，这条数据所属的客户在B中不存在，那么参与方A是不是就无法使用纵向联邦学习模型对a这条数据进行预测呢？ 在预测阶段所使用的样本数据是否也需要多方进行隐私集合求交才能够确定是否能进行预测？

是的，
1. 对于homo_secure_boost 横向可以单方预测，也就是这里的reader_1可以只有guest一方
2. 对于hetero_secure_boost 纵向必须双方隐私求交才能预测， 即如果A方的预测数据的id在B方中没有记录则无法预测。

**Comment by oceanqdu** [comment]
> 

感谢您的解答！

**Comment by FFinchR** [comment]
> If you want to predict in a single party, use conf to submit job instead of pipeline. For examples, in this [conf](https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/homo_secureboost/test_predict_conf.json) ，delete guest & arbiter in role, also delete guest reader in component_parameters, then you can submit predicting jobs in host:10000

Hi there, I followed this path to do a single party prediction, it worked at guest party, but it couldn't work at host party.
According to my understanding, before predict job, model must be deployed. 
Then, I run deploy command at host party:
`!flow model deploy --model-id arbiter-9998#guest-9999#host-9998#model --model-version 202303220252081986320 --dsl-path /data/projects/fate/examples/dsl/v2/homo_logistic_regression/homo-lr-normal-predict-dsl.json`

Errors:

```
{
    "retmsg": "Deploy model failed. Cannot found model of initiator role or the fate version of model is older than 1.5.0",
    "retcode": 404
}
```

what should i do?
Thank you. @mgqa34

**Comment by DongRuiHust** [comment]
@oceanqdu 请问你在使用 pipeline 预测时，解决这个问题吗？现在也遇到这个问题。

**Comment by oceanqdu** [comment]
> @oceanqdu 请问你在使用 pipeline 预测时，解决这个问题吗？现在也遇到这个问题。

我实现了使用python借用fate  flow的一些接口进行单方预测。我的思路是再python文件中可以通过pkl文件获得job id以及jobversion 然后再python文件中使用 flow deploy进行部署 再进行预测任务。
