### ISSUE TITLE
请问fate是否支持开发自定义的数据处理模块

### ISSUE THREAD

**Issue by NTang7** [FederatedAI/FATE#4318]
需求是1. 在进行模型联邦训练前在本地根据条件计算或构建新的特征，
2. 在完成训练后对数据进行进一步的计算（类似于scorecard，但具体评分方式不一样）。

**Comment by mgqa34** [comment]
我理解这些都可以自己去开发相关组件去完成？ 关于组件开发可以参考链接：[开发指南](./https://github.com/FederatedAI/FATE/blob/master/doc/develop/develop_guide.md)
