### ISSUE TITLE
直接使用fate镜像新建容器，启动后没办法使用fateboard

### ISSUE THREAD

**Issue by young-chao** [FederatedAI/FATE#4319]
采用python ./examples/pipeline/demo/pipeline-mini-demo.py方式运行示例任务，fateflow的logs文件夹中有相应日志记录，而fateboard文件夹内无日志生成。在浏览器中无法打开127.0.0.1:8080无反应。

**Comment by talkingwallace** [comment]
fateboard是否启动呢

**Comment by young-chao** [comment]
1.请问官方提供的镜像中是否含fate-board代码，未找到相应代码?是否应该另外自行下载？
2,.请问如何启动FATEBoard，根据官方文档中似乎表述不明，我之前理解为FATEBoard会自动启动。

如FATEBoard的说明（https://github.com/FederatedAI/FATE-Board/blob/master/README-CN.md），看完之后还是完全没有理解如何启动FATEBoard：
**启动FATEBoard**
FATEBoard代码使用spring-boot框架并嵌入在tomcat容器中，默认的网络端口是8080。在启动前，需要检查机器的8080端口是否被占用，如果端口被占用，FATEBoard将会启动失败。
FATEBoard通过访问mysql数据库来获得任务列表，如果没有正确安装数据库，那么任务获取就会失败。
FATEBoard通过HTTP协议来访问FATEFlow。如果没有正常启动FATEFlow，FATEBoard将无法呈现任务图表。
你可以通过 http://{FATEBoard-ip}:8080来访问FATEBoard。

**启动一个新的建模任务**
1.准备条件：配置一个pipeline，创建DAG图，定义参数。 2.**启动FATEBoard：提交并启动任务后，返回一个任务URL，点击URL即可在网页上访问这个任务。**或者，在任务启动时，你可以通过web浏览器访问http://{FATEBoard-ip}:8080来查看FATEBoard。 host或arbiter方也可以通过http://{FATEBoard-ip}:8080访问FATEBoard。 3.监控任务：dashboard可视化了任务运行全过程。 4.查看任务：可视化查看每个算法组件的模型输出、数据输出、运行日志等。
