### ISSUE TITLE
fate1.6中 fate_arch、fate_client 等是否可以封装成whl文件库

### ISSUE THREAD

**Issue by mamingliang-myy** [FederatedAI/FATE#4328]
您好，fate1.6中 python目录下的依赖环境，如：fate_arch、fate_client 等是否可以封装成whl文件库

**Comment by mamingliang-myy** [comment]
fate/python目录下的setup.py文件有没有1.6版本的呢，git上1.6下面的是1.5版本的

**Comment by weiwee** [comment]
> fate/python目录下的setup.py文件有没有1.6版本的呢，git上1.6下面的是1.5版本的

你可以选择自己修改编译打包
```bash
python3 -m pip install build
python3 -m build --sdist
```

如果有困难，我可以提供编译好的包，请先自己尝试下
