### ISSUE TITLE
有关pipeline实现横向联邦学习的预测

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4330]
#https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_hetero_sbt.ipynb
正如教程中所示通过pipeline只能实现纵向联邦学习的预测过程，而在横向联邦学习的某些场景下，有时候并不需要所有参与方在预测过程中都提供数据，正如 #4314中所假设的场景，希望pipeline能够实现在横向联邦学习中单个参与方进行预测。

**Comment by weiwee** [comment]
@oceanqdu 谢谢你的建议 横向在很多时候只在训练阶段有联邦的需求，在训练完成之后各种用模型去推理即可，我们会考虑在后续改进。如果你有兴趣也可以给我们提PR贡献，不过在此之前，请跟我们讨论下方案。你可以 @talkingwallace @weiwee @dylan-fan @mgqa34

**Comment by oceanqdu** [comment]
> @oceanqdu 谢谢你的建议 横向在很多时候只在训练阶段有联邦的需求，在训练完成之后各种用模型去推理即可，我们会考虑在后续改进。如果你有兴趣也可以给我们提PR贡献，不过在此之前，请跟我们讨论下方案。你可以 @talkingwallace @weiwee @dylan-fan @mgqa34

感谢您的回复，我认为您说的很有道理，横向在很多时候只在训练阶段有联邦的需求。在预测推理阶段，各方可以单独使用模型来推理自己的数据，我看到fate可以通过dsl方式完成单方预测，单pipeline并不支持单方使用模型进行预测。
我还有一些疑惑想请教下您。
1、我在使用fate框架时，模拟了两个参与方A和B进行了横向联邦学习训练（pipeline的形式），B通过pipeline提交了训练任务并通过dump函数下载得到了一个pkl模型文件，这个pkl文件是明文的模型吗？
2、这个pkl模型可以在fate框架之外使用吗？
3、A有没有办法下载得到这个pkl模型文件？
以上三个问题希望能够得到您的解答，非常感谢！

**Comment by weiwee** [comment]
1. pkl 里面是明文的
2. 可以，但是pkl里面可能有其他东西? @talkingwallace @mgqa34 
3. https://fate.readthedocs.io/en/latest/api/fate_client/pipeline/#convert-homo-model-to-formats-from-other-machine-learning-system

**Comment by weiwee** [comment]
1. pkl 里面是明文的
2. 可以，但是pkl里面可能有其他东西? @talkingwallace @mgqa34 
3. https://fate.readthedocs.io/en/latest/api/fate_client/pipeline/#convert-homo-model-to-formats-from-other-machine-learning-system

> > @oceanqdu 谢谢你的建议 横向在很多时候只在训练阶段有联邦的需求，在训练完成之后各种用模型去推理即可，我们会考虑在后续改进。如果你有兴趣也可以给我们提PR贡献，不过在此之前，请跟我们讨论下方案。你可以 @talkingwallace @weiwee @dylan-fan @mgqa34
> 
> 感谢您的回复，我认为您说的很有道理，横向在很多时候只在训练阶段有联邦的需求。在预测推理阶段，各方可以单独使用模型来推理自己的数据，我看到fate可以通过dsl方式完成单方预测，单pipeline并不支持单方使用模型进行预测。 我还有一些疑惑想请教下您。 1、我在使用fate框架时，模拟了两个参与方A和B进行了横向联邦学习训练（pipeline的形式），B通过pipeline提交了训练任务并通过dump函数下载得到了一个pkl模型文件，这个pkl文件是明文的模型吗？ 2、这个pkl模型可以在fate框架之外使用吗？ 3、A有没有办法下载得到这个pkl模型文件？ 以上三个问题希望能够得到您的解答，非常感谢！

1. pkl 里面是明文的
2. 可以，但是pkl里面可能有其他东西? @talkingwallace @mgqa34 
3. https://fate.readthedocs.io/en/latest/api/fate_client/pipeline/#convert-homo-model-to-formats-from-other-machine-learning-system

**Comment by oceanqdu** [comment]
> 1. pkl 里面是明文的
> 2. 可以，但是pkl里面可能有其他东西? @talkingwallace @mgqa34
> 3. https://fate.readthedocs.io/en/latest/api/fate_client/pipeline/#convert-homo-model-to-formats-from-other-machine-learning-system
> 
> > > @oceanqdu 谢谢你的建议 横向在很多时候只在训练阶段有联邦的需求，在训练完成之后各种用模型去推理即可，我们会考虑在后续改进。如果你有兴趣也可以给我们提PR贡献，不过在此之前，请跟我们讨论下方案。你可以 @talkingwallace @weiwee @dylan-fan @mgqa34
> > 
> > 
> > 感谢您的回复，我认为您说的很有道理，横向在很多时候只在训练阶段有联邦的需求。在预测推理阶段，各方可以单独使用模型来推理自己的数据，我看到fate可以通过dsl方式完成单方预测，单pipeline并不支持单方使用模型进行预测。 我还有一些疑惑想请教下您。 1、我在使用fate框架时，模拟了两个参与方A和B进行了横向联邦学习训练（pipeline的形式），B通过pipeline提交了训练任务并通过dump函数下载得到了一个pkl模型文件，这个pkl文件是明文的模型吗？ 2、这个pkl模型可以在fate框架之外使用吗？ 3、A有没有办法下载得到这个pkl模型文件？ 以上三个问题希望能够得到您的解答，非常感谢！
> 
> 1. pkl 里面是明文的
> 2. 可以，但是pkl里面可能有其他东西? @talkingwallace @mgqa34
> 3. https://fate.readthedocs.io/en/latest/api/fate_client/pipeline/#convert-homo-model-to-formats-from-other-machine-learning-system
>    https://fate-flow.readthedocs.io/en/latest/fate_flow_client/#homo-convert
>    https://github.com/FederatedAI/FATE-Flow/tree/main/examples/model

非常感谢您解答我疑惑。第一个问题您的回答是明文的。另一些令我好奇的点是，
1、如果是纵向联邦学习训练，通过dump下载的pkl也是明文的吗？
2、如果是纵向也是明文的话，dump下来的是完整的模型吗？还是只会下载自己所拥有的那部分特征数据所对应的模型权重？
非常抱歉再次提出那么多问题麻烦您，希望您有时间能解答一些，非常感谢您的帮助！

**Comment by mgqa34** [comment]
> > 1. pkl 里面是明文的
> > 2. 可以，但是pkl里面可能有其他东西? @talkingwallace @mgqa34
> > 3. https://fate.readthedocs.io/en/latest/api/fate_client/pipeline/#convert-homo-model-to-formats-from-other-machine-learning-system
> > 
> > > > @oceanqdu 谢谢你的建议 横向在很多时候只在训练阶段有联邦的需求，在训练完成之后各种用模型去推理即可，我们会考虑在后续改进。如果你有兴趣也可以给我们提PR贡献，不过在此之前，请跟我们讨论下方案。你可以 @talkingwallace @weiwee @dylan-fan @mgqa34
> > > 
> > > 
> > > 感谢您的回复，我认为您说的很有道理，横向在很多时候只在训练阶段有联邦的需求。在预测推理阶段，各方可以单独使用模型来推理自己的数据，我看到fate可以通过dsl方式完成单方预测，单pipeline并不支持单方使用模型进行预测。 我还有一些疑惑想请教下您。 1、我在使用fate框架时，模拟了两个参与方A和B进行了横向联邦学习训练（pipeline的形式），B通过pipeline提交了训练任务并通过dump函数下载得到了一个pkl模型文件，这个pkl文件是明文的模型吗？ 2、这个pkl模型可以在fate框架之外使用吗？ 3、A有没有办法下载得到这个pkl模型文件？ 以上三个问题希望能够得到您的解答，非常感谢！
> > 
> > 
> > 
> > 1. pkl 里面是明文的
> > 2. 可以，但是pkl里面可能有其他东西? @talkingwallace @mgqa34
> > 3. https://fate.readthedocs.io/en/latest/api/fate_client/pipeline/#convert-homo-model-to-formats-from-other-machine-learning-system
> >    https://fate-flow.readthedocs.io/en/latest/fate_flow_client/#homo-convert
> >    https://github.com/FederatedAI/FATE-Flow/tree/main/examples/model
> 
> 非常感谢您解答我疑惑。第一个问题您的回答是明文的。另一些令我好奇的点是， 1、如果是纵向联邦学习训练，通过dump下载的pkl也是明文的吗？ 2、如果是纵向也是明文的话，dump下来的是完整的模型吗？还是只会下载自己所拥有的那部分特征数据所对应的模型权重？ 非常抱歉再次提出那么多问题麻烦您，希望您有时间能解答一些，非常感谢您的帮助！

1. 这里澄净一个概念，pkl应该指的是pipeline.dump这个动作？这样的话，其实存的是pipeline的信息，和运行在fate生成后的模型是有diff的
2. 如果想获取fate的模型的话，可以通过pipeline.get_model_param，传参组件名去获取对应组件的模型输出
3. 另外的话，这个pipeline的pkl文件是针对当前party的，所以没法脱离fate直接去用

**Comment by mgqa34** [comment]
有个比较有趣的功能目前pipeline是没实现的，通过model_id\version其实是可以直接做预测的（conf&dsl模式），但pipeline做预测是依赖于训练的pipeline，但其实pipeline可以通过flow提供的sdk接口+model_id\version，去flow处查询得到dsl和组件参数后，重构训练 pipeline的context，从而使得其可以用于预测。有兴趣的话可以开发贡献到fate社区，这样的话每一方拿到model_id\version，自己就可以构建pipeline去做预测任务了

**Comment by oceanqdu** [comment]
> 有个比较有趣的功能目前pipeline是没实现的，通过model_id\version其实是可以直接做预测的（conf&dsl模式），但pipeline做预测是依赖于训练的pipeline，但其实pipeline可以通过flow提供的sdk接口+model_id\version，去flow处查询得到dsl和组件参数后，重构训练 pipeline的context，从而使得其可以用于预测。有兴趣的话可以开发贡献到fate社区，这样的话每一方拿到model_id\version，自己就可以构建pipeline去做预测任务了

还有两个问题想问您，
1、pipeline.dump这个动作下载下来的pkl文件存的是pipeline的信息，那么假设A和B两个参与方参与联邦学习训练,B通过pipeline.dump这个动作下载下来一个model.pkl文件（参与方B可以通过PipeLine.load_model_from_file("model.pkl")来部署推理过程），如果参与方B把这个model.pkl文件给参与方A，参与方A能直接使用model.pkl部署推理过程吗，使用方式和A有什么不同？
2、任务完成后可以在fateboard上查看evaluation模块的模型评估信息，那么可以使用pipeline的方式可以down下来evaluation模块的所有信息吗？

**Comment by mgqa34** [comment]
1. initiator和roles在预测的时候可能还是记录在A方，这会导致B方单独预测的时候，B方的flow找不到相关信息
2. pipeline.get_component("evaluation_0").get_summary()可以获取相关数据

**Comment by oceanqdu** [comment]
> 1. initiator和roles在预测的时候可能还是记录在A方，这会导致B方单独预测的时候，B方的flow找不到相关信息
> 2. pipeline.get_component("evaluation_0").get_summary()可以获取相关数据

感谢您的解答！
