### ISSUE TITLE
你们文档是怎么写的？

### ISSUE THREAD

**Issue by HeliumzzZ** [FederatedAI/FATE#4333]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mgqa34** [comment]
Please describe the problem you have met when reading the documents.

**Comment by talkingwallace** [comment]
请问文档哪里有问题呢
