### ISSUE TITLE
你们文档为什么没有更新？bin目录下没有activate安装不了

### ISSUE THREAD

**Issue by HeliumzzZ** [FederatedAI/FATE#4334]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mgqa34** [comment]
Please read the deployment guides first. Source code deployment guide is [here](https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md)

**Comment by HeliumzzZ** [comment]
bash bin/service.sh start



service start failed, please check /root/standalone_fate_install_1.7.0_release/fateflow/logs/error.log and /root/standalone_fate_install_1.7.0_release/fateflow/logs/console.log
check process by http port and grpc port
service not running
(fate) ***@***.***:~/standalone_fate_install_1.7.0_release/fateflow# cat /root/standalone_fate_install_1.7.0_release/fateflow/logs/error.log
Traceback (most recent call last):
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/fate_flow_server.py", line 23, in <module&gt;
&nbsp; &nbsp; import grpc
ModuleNotFoundError: No module named 'grpc'
Traceback (most recent call last):
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/fate_flow_server.py", line 23, in <module&gt;
&nbsp; &nbsp; import grpc
ModuleNotFoundError: No module named 'grpc'
Traceback (most recent call last):
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/fate_flow_server.py", line 23, in <module&gt;
&nbsp; &nbsp; import grpc
ModuleNotFoundError: No module named 'grpc'
Traceback (most recent call last):
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/fate_flow_server.py", line 23, in <module&gt;
&nbsp; &nbsp; import grpc
ModuleNotFoundError: No module named 'grpc'
Traceback (most recent call last):
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/fate_flow_server.py", line 23, in <module&gt;
&nbsp; &nbsp; import grpc
ModuleNotFoundError: No module named 'grpc'
Traceback (most recent call last):
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/fate_flow_server.py", line 27, in <module&gt;
&nbsp; &nbsp; from fate_flow import set_env
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/__init__.py", line 18, in <module&gt;
&nbsp; &nbsp; from fate_flow.entity.types import ProcessRole
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/entity/__init__.py", line 16, in <module&gt;
&nbsp; &nbsp; from ._base import BaseEntity
&nbsp; File "/root/standalone_fate_install_1.7.0_release/fateflow/python/fate_flow/entity/_base.py", line 16, in <module&gt;
&nbsp; &nbsp; from fate_arch.common import BaseType
ModuleNotFoundError: No module named 'fate_arch'







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 中午12:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE] 你们文档为什么没有更新？bin目录下没有activate安装不了 (Issue #4334)





 
Please read the deployment guides first. Source code deployment guide is here

**Comment by HeliumzzZ** [comment]
我现在应该下哪个版本的代码来部署




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 中午12:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE] 你们文档为什么没有更新？bin目录下没有activate安装不了 (Issue #4334)





 
Please read the deployment guides first. Source code deployment guide is here

**Comment by HeliumzzZ** [comment]
&nbsp; ERROR: Command errored out with exit status 1:
&nbsp; &nbsp;command: /root/fate/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yxkh414_/gmpy2_84cfa3dfb0ce4fdcb26ff509188c903c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yxkh414_/gmpy2_84cfa3dfb0ce4fdcb26ff509188c903c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3es_svjy
&nbsp; &nbsp; &nbsp; &nbsp;cwd: /tmp/pip-install-yxkh414_/gmpy2_84cfa3dfb0ce4fdcb26ff509188c903c/
&nbsp; Complete output (14 lines):
&nbsp; running bdist_wheel
&nbsp; running build
&nbsp; running build_ext
&nbsp; building 'gmpy2' extension
&nbsp; creating build
&nbsp; creating build/temp.linux-x86_64-3.8
&nbsp; creating build/temp.linux-x86_64-3.8/src
&nbsp; gcc -pthread -B /root/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITHMPFR -DWITHMPC -I/root/fate/include -I/root/miniconda3/include/python3.8 -c src/gmpy2.c -o build/temp.linux-x86_64-3.8/src/gmpy2.o
&nbsp; In file included from src/gmpy2.c:426:0:
&nbsp; src/gmpy.h:106:12: fatal error: gmp.h: No such file or directory
&nbsp; &nbsp;#&nbsp; include "gmp.h"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^~~~~~~
&nbsp; compilation terminated.
&nbsp; error: command 'gcc' failed with exit status 1







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 中午12:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FederatedAI/FATE] 你们文档为什么没有更新？bin目录下没有activate安装不了 (Issue #4334)





 
Please read the deployment guides first. Source code deployment guide is here

**Comment by HeliumzzZ** [comment]
&nbsp; numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
&nbsp; ----------------------------------------
&nbsp; ERROR: Failed building wheel for scipy





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 中午12:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] 你们文档为什么没有更新？bin目录下没有activate安装不了 (Issue #4334)





 
Please read the deployment guides first. Source code deployment guide is here

**Comment by weiwee** [comment]
@HeliumzzZ 请在抱怨和寻求帮助之前 根据文档仔细检查部署步骤 https://github.com/FederatedAI/FATE/tree/master/deploy
纯粹的抱怨并不能帮你解决问题
PS：最新的版本号查看release或者tag都应该能知道

**Comment by HeliumzzZ** [comment]
&nbsp; Add `--force` to your command to use it anyway if you must (unsupported).
&nbsp;&nbsp;
&nbsp; ----------------------------------------
&nbsp; ERROR: Failed cleaning build dir for scipy



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 中午12:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] 你们文档为什么没有更新？bin目录下没有activate安装不了 (Issue #4334)





 
Please read the deployment guides first. Source code deployment guide is here
