### ISSUE TITLE
Is the Interactive Layer in HeretoNN automatically inferring the input shape?

### ISSUE THREAD

**Issue by ZPZhou-lab** [FederatedAI/FATE#4341]
I learned that the forward inference process of the Interactive Layer is as follows:
z = zB + zA + αA * ε_acc = αB * WB + αA * WA + αA * ε_acc = αB * WB + αA * (WA + εacc) = αB * WB + αA * WA',
which is a matrix multiplication z = α * W given α = concat(αA, αB) and W = concat(WA', WB).

In the tutorial notebook [[Build Hetero NN model in FATE-Pipeline with Pytorch-backend](https://fate.readthedocs.io/en/latest/zh/tutorial/pipeline/pipeline_tutorial_hetero_nn_torch.ipynb)], 
The following is the definition of the HeretoNN structure: 
```python3
# guest bottom model
guest_bottom_a = nn.Linear(10, 10, True)
guest_bottom_b = nn.Linear(10, 8, True)
guest_bottom_seq = torch.nn.Sequential(
    OrderedDict([
        ('layer_0', guest_bottom_a),
        ('relu_0', nn.ReLU()),
        ('layer_1', guest_bottom_b),
        ('relu_1', nn.ReLU())
    ])
)

# host bottom model
host_bottom_model = nn.Sequential(
    nn.Linear(20, 16, True),
    nn.ReLU(),
    nn.Linear(16, 8, True),
    nn.ReLU()
)

# interactive layer
interactive_layer = nn.Linear(8, 4, True)

# guest top model
guest_top_seq = torch.nn.Sequential(
    nn.Linear(4, 1, True),
    nn.Sigmoid()
)
```

**Note that the input dimension of the interactive layer is 8, which does not match the dimension 16 of concat(αA, αB)**

I want to know whether you have completed the automatic dimension inference function in the interactive layer, so the configuration of the interactive layer only needs to consider the output dimension? it may cause misunderstanding to the first time users.

Thanks! 😊

**Comment by talkingwallace** [comment]
Hi! 
Yes, the Interactive layer will automatically infer the input shape

**Comment by talkingwallace** [comment]
Since the forward route of the interactive layer is:
Linear( guest_fw + host_fw). In this case, guest_fw + host_fw yields a tensor of dimension 8.
So this configuration of the interactive layer actually matches the input from the bottom models.

**Comment by ZPZhou-lab** [comment]
> Hi! Yes, the Interactive layer will automatically infer the input shape, but in this case, the configuration is OK

Thank you!
