### ISSUE TITLE
两方不做互相免密如何部署啊？

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4343]
两方不做互相免密如何部署啊？

**Comment by mgqa34** [comment]
需要每一方单独部署，然后改下各方的路由表，比如eggroll的话，需要修改eggroll/conf/route_table.json，加入对方的信息

**Comment by Chuang007** [comment]
您的邮件已收到  谢谢~

**Comment by hongsedating** [comment]
您好，我也遇到了同样问题，请问是否可以也发我一下这个邮件呢？谢谢！

**Comment by Chuang007** [comment]
您的邮件已收到  谢谢~

**Comment by Chuang007** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            需要每一方单独部署，然后改下各方的路由表，比如eggroll的话，需要修改eggroll/conf/route_table.json，加入对方的信息
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1539418001
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年03月22日 09:21
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [FederatedAI/FATE] 两方不做互相免密如何部署啊？ (Issue #4343)
        
      
    
  
  
您好，我也遇到了同样问题，请问是否可以也发我一下这个邮件呢？谢谢！

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
