### ISSUE TITLE
RuntimeError:can not found tabel name：XXX namespace：XXX

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4357]
明明上传数据了，为什么还报这个错呢？RuntimeError:can not found tabel name：XXX namespace：XXX

**Comment by Chuang007** [comment]
我发现在fate01上传的数据，对应的jobs记录竟然在fate02的fateboard里，这是什么原因呢？

**Comment by mgqa34** [comment]
这里fate01\02指的是两个不同的partyid（集群）？数据上传的方式是通过flow client上传的吗？如果是的话，要确认01的flow init的ip是fate01而不是指向了fate02的服务

**Comment by Chuang007** [comment]
> 这里fate01\02指的是两个不同的partyid（集群）？数据上传的方式是通过flow client上传的吗？如果是的话，要确认01的flow init的ip是fate01而不是指向了fate02的服务

谢谢，是init的问题
