### ISSUE TITLE
HomoNN模型验证时，否支持 eval_type = 'multi' 

### ISSUE THREAD

**Issue by yueyueshine** [FederatedAI/FATE#4358]
在conf文件中，设置了eval_type:'multi'，但是在log打印时候仍然显示 eval_type is binary。然后在EvaluateParam类中看到注释  Parameters
----------
eval_type : {'binary', 'regression', 'multi'}
 support 'binary' for HomoLR, HeteroLR and Secureboosting,
 support 'regression' for Secureboosting,
 'multi' is not support these version
请问，homoNN的验证集是否支持‘multi'呢？ Fate版本1.8

**Comment by mgqa34** [comment]
Evaluation组件是支持multi的，文档的表达可能旧了，evaluation的参数eval_type和上游组件关系不大，是一个独立解耦的，只是说要用什么类型的指标去评估输入数据。可以在fateboard上查看这个参数配置是否真的生效，然后log的话也麻烦给出对应哪一行代码打出来的，这样方便查案
