### ISSUE TITLE
confusion matrix

### ISSUE THREAD

**Issue by mahmoudsajjadi** [FederatedAI/FATE#4359]
**Describe the bug**
Hi, I am trying to have confusion matrix for homo secure boost algorithm. I will appreciate it if you let me know how can I add and see this metric.

**Comment by talkingwallace** [comment]
Hi, you can refer to this conf:https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/homo_secureboost/test_secureboost_train_binary_conf.json.
The evaluation module will automatically compute the confusion matrix.
