### ISSUE TITLE
如何确保评分卡模型中的逻辑回归的权重都大于零

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4362]
评分卡模型在实际使用当中需要模型中的逻辑回归的权重都大于零，那么在fate中如何实现这个呢？

**Comment by dylan-fan** [comment]
把原特征值分箱后换成woe值

**Comment by Chuang007** [comment]
> 

谢谢

**Comment by Chuang007** [comment]
> 把原特征值分箱后换成woe值

我转成woe后训练出的权重还是有负值，哪地方不对呢？您能详细指导一下吗？
