### ISSUE TITLE
RuntimeError：The model weights are overflow，please check if the input data has been normalized

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4363]
在加入特征选择模块后报错RuntimeError：The model weights are overflow，please check if the input data has been normalized

**Comment by mgqa34** [comment]
这个报错应该是三方（有协调方的）LR组件的报错？ 可以加一个scale组件或者binning+onehot去解决这个问题，对数据进行归一化后再进入LR组件，报错是模型权重太大(超过1e8)，发散了
