### ISSUE TITLE
用已编译安装包安装单机版时执行bash init.sh init的问题

### ISSUE THREAD

**Issue by CSUzxy57** [FederatedAI/FATE#4368]
用已编译安装包安装单机版时执行bash init.sh init时出现：
[INFO] env dir: /root/standalone_fate_install_1.9.0_release/env
[INFO] jdk dir: /root/standalone_fate_install_1.9.0_release/env/jdk/jdk-8u192
[INFO] venv dir: /root/standalone_fate_install_1.9.0_release/env/python/venv
[INFO] kernel: Linux
[INFO] linux system: CentOS Linux
[INFO] os: CentOS
[INFO] is root user
[INFO] install os dependency
/var/tmp/scl4Bv80E:行8: -nv: 未找到命令

请问有什么解决方法吗？

**Comment by ghost** [comment]
请问您解决了吗
