### ISSUE TITLE
新增自定义算法的过程中，出现fateboard执行组件流抖动，并且任务完成后不显示组件流，无法查看每个组件的输出

### ISSUE THREAD

**Issue by Averryjj** [FederatedAI/FATE#4372]
你好，我尝试新增自定义组件A，组件A只是简单的数据处理，不涉及多方，但是组件A的输出为两个表，组件B接收组件A的两个表作为输入，这样的场景下出现，任务可执行成功，但是fateboard的组件执行流的展示出现问题，在运行过程中出现抖动，运行结束后不显示执行流，无法查看每个组件的输出,请指教，谢谢！
FATE版本1.7和FATE1.8都进行了尝试，问题都是这样的。

**Comment by talkingwallace** [comment]
hi
请问组件是多输出吗，就是一次返回多个表？
可以参考下Data Split这个组件，对照的看一下，看看是不是什么返回上的细节不一致？

**Comment by Yejiajun227** [comment]
你好，我好像遇到了和你一样的问题，我想问下最后解决了吗？

**Comment by Averryjj** [comment]
没有解决
