### ISSUE TITLE
建议增加fate各算法模块每个参数的具体含义及示例

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4373]
建议增加fate各算法模块每个参数的具体含义及示例，目前只有一个算法列表，其中算法的参数众多，个别的能猜到什么意思，大部分不知道什么意思，不知如何设置

**Comment by talkingwallace** [comment]
hi, 
目前文档中有算法参数的解释，或者你也可以到federatedml/param下的各个参数文件里查看下参数，目前所有算法都是有参数注释的

**Comment by Chuang007** [comment]
> federatedml/param

好的，谢谢
