### ISSUE TITLE
Does FATE has plan to support TEE, like remote attestation and trust execution environment Provisioning ?

### ISSUE THREAD

**Issue by PenglinYang** [FederatedAI/FATE#4374]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dylan-fan** [comment]
it will be supported in 2.x version

**Comment by PenglinYang** [comment]
Thanks. If does, there is an IETF draft maybe useful to provide information about how to provision general TEE devices. The link is here: [https://datatracker.ietf.org/doc/draft-ietf-teep-usecase-for-cc-in-network/](url). My personal opinion is that a design to include different TEE architectures is more popular and is more easy to be accepted by industry : )
