### ISSUE TITLE
[Transfer Issue] 使用docker-compose版本测试homo_nn遇到的问题

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4377]
**What deployment mode you are use?  **
docker-compose;

**What KubeFATE and FATE version you are using?  **
 kubefate-docker-compose-v1.8.0

在使用docker-compose测试参考文档https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_homo_nn.ipynb 测试homo_nn遇到了一个报错
![image](https://user-images.githubusercontent.com/49178688/195055459-b8bc54d9-79c6-47b3-95c7-9dca30b7f9a7.png)

`ValueError: Layer type <class 'keras.layers.core.Dense'> not support yet`

在部署kubefate时我已经修改了我的parties.conf 文件，文件内容如下：
![image](https://user-images.githubusercontent.com/49178688/195055136-9fbd9adc-5fdf-4293-b547-799b3ce5f7a2.png)

我想问一下应该怎么解决这个问题呢

**Comment by LaynePeng** [comment]
It looks like an issue of FATE to run NN algorithm.

**Comment by oceanqdu** [comment]
> In the meantime, this could be a known issue so please check if fate v1.9.0 have this problem resolved.
@JingChen23 
 当我按照您的建议使用v1.9.0版本时遇到了一个新的问题，在使用docker-compose部署kubefate时，我首先对parties.conf文件进行了更改，当配置如下，`algorithm=Basic`时，成功部署了fate

![image](https://user-images.githubusercontent.com/49178688/195261987-3cc2a84a-0a21-48d2-a22a-3acde20429f7.png)
结果如下：
![image](https://user-images.githubusercontent.com/49178688/195262191-eb53b40a-6f3c-4e23-8ec7-f965555b1adf.png)
然而当我删除了以上部署并希望使用神经网络功能时出现了问题。
首先我修改parties.conf文件的配置，将`algorithm=NN`
![image](https://user-images.githubusercontent.com/49178688/195264515-9dcb15fe-7e56-415b-a5c3-251dda883cbb.png)

接下来我执行了
`#bash ./generate_config.sh `
成功。
但是当我执行
`#bash ./docker_deploy.sh all`
出现了以下问题
![image](https://user-images.githubusercontent.com/49178688/195267935-75c0fbaf-4cbc-4423-8d00-20a338dc9225.png)
请问这是什么原因呢

**Comment by oceanqdu** [comment]
> In the meantime, this could be a known issue so please check if fate v1.9.0 have this problem resolved.

@JingChen23 经过测试 1.9.0版本也是同样的问题，请问这和下载的tensorflow版本有关系吗？
在我第一次执行上述python代码时，提示我没有tensorflow模块，
![6d2cf4521b3799006b7f6fd7616f58f](https://user-images.githubusercontent.com/49178688/195511424-1e3bccf9-6b8e-4c27-b03b-32db4bf37ebc.jpg)
于是我使用了 pip install tensorflow 命令安装了 tensorflow模块，tensorflow的版本信息如下
![image](https://user-images.githubusercontent.com/49178688/195511720-d1608306-7d62-4b32-9587-b8980df52d01.png)
再次执行上述python代码，报错如下：
![image](https://user-images.githubusercontent.com/49178688/195512209-1e312576-baf1-4682-9254-42059a986bc3.png)

**Comment by JingChen23** [comment]
We didn't push the eggroll-nn image to 163, this has been done just now, please retry.
![Screen Shot 2022-10-13 at 13 48 35](https://user-images.githubusercontent.com/15973672/195512498-7cd3b65e-4734-40a4-870d-a4b7c1af49d9.png)

**Comment by oceanqdu** [comment]
> We didn't push the eggroll-nn image to 163, this has been done just now, please retry. ![Screen Shot 2022-10-13 at 13 48 35](https://user-images.githubusercontent.com/15973672/195512498-7cd3b65e-4734-40a4-870d-a4b7c1af49d9.png)
@JingChen23 
在我将`RegistryURI=hub.c.163.com`
修改为`RegistryURI=`
已经成功拉取了eggroll-nn，但同样遇到了上述问题。
