### ISSUE TITLE
fate v1.9.0 有关神经网络的问题

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4381]
在fate v1.9.0版本参考文档给出的demo https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_homo_nn.ipynb测试神经网络发现一个错误。

1.首次执行代码提示缺失tensorflow模块
![image](https://user-images.githubusercontent.com/49178688/195562885-84dd7618-7a8d-4c21-bb85-6613d3bb904a.png)
在我使用了`pip install tensorflow`下载了tensorflow模块并再次执行了代码，再次发生以下错误
 #4377 ，错误信息如下
![image](https://user-images.githubusercontent.com/49178688/195562463-a528d54f-cab4-4bc2-a1b0-5001668a2d00.png)
追入/pipeline/component/nn/models/sequantial.py
发现问题代码如下：
`    def add(self, layer):
        if _TF_KERAS_VALID and isinstance(layer, base_layer.Layer):
            layer_type = "keras"
        elif isinstance(layer, dict):
            layer_type = "nn"
        elif hasattr(layer, "__module__") and getattr(layer, "__module__").startswith("torch.nn.modules"):
            layer_type = "pytorch"
        else:
          
            raise ValueError("Layer type {} not support yet".format(type(layer)))`

在 isinstance(layer, base_layer.Layer)中返回的是false，所以抛出了以上错误，
将sequantial.py文件中的` from tensorflow.python.keras.engine import base_layer`
修改为 `from keras.engine import base_layer`则解决了这个问题。
所以是因为我下载的tensorflow版本发生了错误还是需要修改一下文档？
修改的文档在这里 #4380

**Comment by oceanqdu** [comment]
> 似乎你使用的是1.8.x的版本，我们在1.9.0升级tensorflow版本的同时修复了这个版本变更导致的问题[832be56?from_wecom=1](https://github.com/FederatedAI/FATE/commit/832be562f7ec06f25046c5e6b1cd9923b7de570c?from_wecom=1) 。 请重新确认下你本地版本是否有问题，报错信息对应的是旧的代码，也许你需要升级下fate_client的版本。

@weiwee 看了您给出的链接，和本地版本中代码确实有所不同，但是我是使用的1.9.0版本。我是通过kubefate部署的fate
1.9.0版本，部署的版本如下图所示
![image](https://user-images.githubusercontent.com/49178688/195740196-45d1658e-90f3-408c-9d10-b4adb28c69fa.png)
不知道是使用docker-compose 部署kubefate发生的版本变更的问题还是我在部署中出现了一些问题？

**Comment by JingChen23** [comment]
Checking

**Comment by JingChen23** [comment]
I just checked the fateflow-nn image, it contians this code change: https://github.com/FederatedAI/FATE/commit/832be562f7ec06f25046c5e6b1cd9923b7de570c?from_wecom=1

Image: https://hub.docker.com/layers/federatedai/fateflow-nn/1.9.0-release/images/sha256-2efc54022768d84b60f418394e56511abdfc59eebad630733bf20b1abfb9312f?context=explore

@oceanqdu  Could you repull this image and reinstall the cluster?

**Comment by JingChen23** [comment]
@oceanqdu 

> 1.首次执行代码提示缺失tensorflow模块

Where did you execute the code? Inside the client container?

**Comment by oceanqdu** [comment]
> @oceanqdu
> 
> > 1.首次执行代码提示缺失tensorflow模块
> 
> Where did you execute the code? Inside the client container?

@JingChen23  我是在 client container里执行的。
在安装1.9.0版本之前我通过kubefate安装过1.8.0版本的fate。在1.8.0版本出现上述问题之后，我删除了1.8.0版本的部署以及镜像并重新部署了1.9.0。有没有可能是因为这个原因呢？

**Comment by oceanqdu** [comment]
> > @oceanqdu
> > > 1.首次执行代码提示缺失tensorflow模块
> > 
> > 
> > Where did you execute the code? Inside the client container?
> 
> @JingChen23 我是在 client container里执行的。 在安装1.9.0版本之前我通过kubefate安装过1.8.0版本的fate。在1.8.0版本出现上述问题之后，我删除了1.8.0版本的部署以及镜像并重新部署了1.9.0。有没有可能是因为这个原因呢？

通过刚刚的检查我发现我的第一台电脑删除了1.8.0的所有镜像，但是我的第二台机器中的images镜像中同时存在1.8.0版本和1.9.0版本。在上述任务中，guest方是我的第二台电脑。是不是因为在容器初始化的时候错误的使用了1.8.0版本的镜像才会出现这个问题
![image](https://user-images.githubusercontent.com/49178688/196136342-24ffe6aa-be8f-4f80-95ac-1ccc6d7d8196.png)

**Comment by JingChen23** [comment]
@oceanqdu 可能是我们之前build v1.9.0的client镜像的时候，FATE这边还没有release最新的fate-client python包。所以[这一行代码](https://github.com/FederatedAI/FATE-Builder/blob/main/docker-build/modules/client/Dockerfile#L13)就错误地安装了v1.8.0的fate-client。我来重新build一下v1.9.0的client镜像之后，上传到dockerhub和163，然后ping你再试一次。

**Comment by JingChen23** [comment]
@oceanqdu 
We have pused the new federatedai/client:1.9.0-release image to both dockerhub and 163, please pull the image and try again.

**Comment by Omelette9619** [comment]
您好，目前在基于KubeFATE和docker-compose部署的FATE中，python容器内是否包含tensorflow框架？我使用1.8.0版本时同样是没有tensorflow框架，在confs-xxxx_python_1容器中自行安装了tensorflow==1.15.0，执行神经网络的样例任务，训练过程正常，但在预测时遇到了issue 4348的问题。是否能通过修改tensorflow版本解决问题？是否发布了包含适配tensorflow框架的FATE部署方案？

**Comment by oceanqdu** [comment]
> 您好，目前在基于KubeFATE和docker-compose部署的FATE中，python容器内是否包含tensorflow框架？我使用1.8.0版本时同样是没有tensorflow框架，在confs-xxxx_python_1容器中自行安装了tensorflow==1.15.0，执行神经网络的样例任务，训练过程正常，但在预测时遇到了issue 4348的问题。是否能通过修改tensorflow版本解决问题？是否发布了包含适配tensorflow框架的FATE部署方案？

@Omelette9619 在部署的过程中是不带tensorflow框架的，我在容器中安装的tensorflow版本为2.10.0。在使用fate 1.8.0版本中执行神经网络的训练任务会报上述我所说的错误，按照我的方式进行修改之后，解决报错。预测正常进行，这些问题应该都是因为tensorflow的版本不适配的问题，或者你也可以使用最新的1.9.0版本。
