### ISSUE TITLE
standalone部署过程中Compile package to install fateboard遇到问题

### ISSUE THREAD

**Issue by deucalionAlpha** [FederatedAI/FATE#4382]
https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/README.md
9.2步骤中的：wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/${version}/release/fateboard.tar.gz; 出现错误，这是我自己的网络原因还是什么问题呢？version是1.9.0

问题：
--2022-10-13 17:55:05--  https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/1.9.0/release/fateboard.tar.gz
正在解析主机 webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)... 27.155.119.152, 27.155.119.140, 27.155.119.187, ...
正在连接 webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com (webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com)|27.155.119.152|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2022-10-13 17:55:06 错误 404：Not Found。

**Comment by jat001** [comment]
fateboard 不在提供单独的 jar 包，请自行编译 (#4383)，或下载 [fate install](https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/1.9.0/release/fate_install_1.9.0_release.tar.gz)
