### ISSUE TITLE
Is there any way to avoid the fateboard login?

### ISSUE THREAD

**Issue by SnakeCN21** [FederatedAI/FATE#4386]
We have a development for fate, and now all of our fate operations are done through the fate flow, but when we want to see the progress and details of fate, we have to log in to fateboard once.
I wonder is there a way to enter the fateboard without a login or to get all the information about that task via jobId.

**Comment by dylan-fan** [comment]
you can get all fateboard information from fate-flow api

**Comment by SnakeCN21** [comment]
> you can get all fateboard information from fate-flow api

How? I want to be able to visuthe following details link like:
http://localhost:8080/#/details?job_id=202210191059520858500&role=guest&party_id=9999&from=Job%20overview&page=1
