### ISSUE TITLE
How can I run a Heterogeneous LinR algorithm in unencrypted version?

### ISSUE THREAD

**Issue by furuifr** [FederatedAI/FATE#4388]
![image](https://user-images.githubusercontent.com/30371036/196927778-3e8c9285-1ba6-4b56-bd86-40f86e94d23d.png)

How can I run a Heterogeneous LinR algorithm in unencrypted version?

**Comment by talkingwallace** [comment]
Fate does not support unencrypted LR.
But if you want an unencrypted version, you can modify codes in encrypted, let encrypt&decrypt API return plaintext directly.

**Comment by talkingwallace** [comment]
Fate does not support unencrypted LR.
But if you want an unencrypted version, you can modify codes in encrypted, let encrypt&decrypt API return plaintext directly.
