### ISSUE TITLE
什么时候算法需要定义model

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4392]
例如：
"hetero_feature_binning_1": {
              "module": "HeteroFeatureBinning",
              "input": {
                  "data": {
                      "data": [
                          "dataio_1.validate_data"
                      ]
                  },
                  "model": [
                      "hetero_feature_binning_0.fit_model"
                  ]
              },
              "output": {
                  "data": ["validate_data"],
                "model": ["eval_model"]
              }
          }
输入中是要给出model，那么如何知道某个算法是否需要指定model，哪个地方的教程有注明呢？

**Comment by mgqa34** [comment]
输入中要给出model指的是binning_1复用binning_0的模型吗？如果是的话，存在模型复用的时候则需要指定输入model.

**Comment by Chuang007** [comment]
> 输入中要给出model指的是binning_1复用binning_0的模型吗？如果是的话，存在模型复用的时候则需要指定输入model.

好的，谢谢
