### ISSUE TITLE
homo-convert发生错误

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4394]
在根据给出的demo执行
`flow model homo-convert -c examples/model/homo_convert_model.json`
发生以下错误。
![image](https://user-images.githubusercontent.com/49178688/197676898-5d2cdbe3-517c-4d89-a5c4-80e9eb5591cd.png)
同时在使用pipeline提交任务并使用，
`pipeline.model_convert.convert()`
将会发生同样的错误
![e4783ba611287fba0122876cf07d90c](https://user-images.githubusercontent.com/49178688/197677052-a4bbd86a-4ad2-4346-a294-af3876c12ebf.jpg)

fate版本 1.8.0
centos7
请问一下是什么原因？

**Comment by mgqa34** [comment]
model_id\version\role这些信息确认是没问题的吗？

**Comment by oceanqdu** [comment]
> model_id\version\role这些信息确认是没问题的吗？
@mgqa34 @jat001 
下面是我的执行步骤：
1.首先我执行了

`flow job submit -c ./dsl/homo_lr_conf.json -d ./dsl/homo_lr_dsl,json`
返回了以下信息，显示提交成功。
![image](https://user-images.githubusercontent.com/49178688/197700028-bdc0ae16-b2d8-44d2-b8c4-435ad2a676be.png)
进入fateborad查看情况如下：
![c01e733e0e4faa0e8713c09de818fed](https://user-images.githubusercontent.com/49178688/197701086-1b2932c9-ff08-484b-a574-055b32c6e789.jpg)

2.接下来我修改了homo_convert_model.json 的内容如下：
![554627f08b2fc68c41d76e2ee716ab0](https://user-images.githubusercontent.com/49178688/197715190-08a9f08c-9966-4761-b373-87855faba64e.jpg)

3.提交`flow model homo-convert -c examples/model/homo_convert_model.json`出现以下问题

![4ee0c0ea104aa38abc4948eed26cea4](https://user-images.githubusercontent.com/49178688/197715112-af769402-77cf-4f28-b547-596934f1a10e.jpg)

上述步骤应该没有问题吧

**Comment by jat001** [comment]
感谢反馈，这是一个bug，会在下个版本修复

临时修复请把[这一行](https://github.com/FederatedAI/FATE-Flow/blob/3afbc3e5d335ac96634eadfc493c4c697ecbfc19/python/fate_flow/pipelined_model/publish_model.py#L145)改成
```
define_meta = model.pipelined_component.get_define_meta()
```

**Comment by oceanqdu** [comment]
> 感谢反馈，这是一个bug，会在下个版本修复
> 
> 临时修复请把[这一行](https://github.com/FederatedAI/FATE-Flow/blob/3afbc3e5d335ac96634eadfc493c4c697ecbfc19/python/fate_flow/pipelined_model/publish_model.py#L145)改成
> 
> ```
> define_meta = model.pipelined_component.get_define_meta()
> ```


@jat001 您好，请问能具体一点说明吗，应该把那个文件中哪一行代码 改成您所说的
`define_meta = model.pipelined_component.get_define_meta()`

**Comment by jat001** [comment]
https://github.com/FederatedAI/FATE-Flow/blob/3afbc3e5d335ac96634eadfc493c4c697ecbfc19/python/fate_flow/pipelined_model/publish_model.py#L145

**Comment by oceanqdu** [comment]
> https://github.com/FederatedAI/FATE-Flow/blob/3afbc3e5d335ac96634eadfc493c4c697ecbfc19/python/fate_flow/pipelined_model/publish_model.py#L145

@jat001 ，您好，经过修改之后，homo-convert确实起了作用，我现在对于homo-convert的作用还有一些疑惑请问您能解答一下吗？
1.在使用homo-convert之后，同样需要使用export才能够将对应的模型下载下来。在我查看了下载结果之后发现，这与我之前没有使用homo-convert而直接使用export导出的模型几乎一样。请问二者之间存在不同吗？有哪些不同
2、使用homo-convert将横向联邦学习进行转换之后export得到的模型我看是zip压缩包的形式，请问应该怎么在其他框架中使用这种模型。
希望您能够解答一下

**Comment by jat001** [comment]
> > https://github.com/FederatedAI/FATE-Flow/blob/3afbc3e5d335ac96634eadfc493c4c697ecbfc19/python/fate_flow/pipelined_model/publish_model.py#L145
> 
> @jat001 ，您好，经过修改之后，homo-convert确实起了作用，我现在对于homo-convert的作用还有一些疑惑请问您能解答一下吗？ 1.在使用homo-convert之后，同样需要使用export才能够将对应的模型下载下来。在我查看了下载结果之后发现，这与我之前没有使用homo-convert而直接使用export导出的模型几乎一样。请问二者之间存在不同吗？有哪些不同 2、使用homo-convert将横向联邦学习进行转换之后export得到的模型我看是zip压缩包的形式，请问应该怎么在其他框架中使用这种模型。 希望您能够解答一下

@mgqa34

**Comment by mgqa34** [comment]
> > https://github.com/FederatedAI/FATE-Flow/blob/3afbc3e5d335ac96634eadfc493c4c697ecbfc19/python/fate_flow/pipelined_model/publish_model.py#L145
> 
> @jat001 ，您好，经过修改之后，homo-convert确实起了作用，我现在对于homo-convert的作用还有一些疑惑请问您能解答一下吗？ 1.在使用homo-convert之后，同样需要使用export才能够将对应的模型下载下来。在我查看了下载结果之后发现，这与我之前没有使用homo-convert而直接使用export导出的模型几乎一样。请问二者之间存在不同吗？有哪些不同 2、使用homo-convert将横向联邦学习进行转换之后export得到的模型我看是zip压缩包的形式，请问应该怎么在其他框架中使用这种模型。 希望您能够解答一下

homo-convert执行后，输出信息会有"converted_model_path"关键字表示转化后的模型文件地址，直接读取即可

**Comment by oceanqdu** [comment]
> 

感谢回复，已经明白了！谢谢

**Comment by Timo9Madrid7** [comment]
This error still occurs in docker deploying Fate:1.9.0.
