### ISSUE TITLE
Failed while run mnist_demo

### ISSUE THREAD

**Issue by Jason-wwww** [FederatedAI/FATE#4403]
**Describe the bug**
Error of No module named \'pytorch_lightning\' while try to run `mnist_demo` in the folder `examples/dsl/v2/homo_nn/mnist_demo/`.

Full error msg from fateboard:
`{'job_id': '202210280540489840880', 'component_name': 'homo_nn_0', 'task_id': '202210280540489840880_homo_nn_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': 'xxx.xxx.xxx.xxx', 'run_pid': 184, 'run_port': '9380', 'party_status': 'failed', 'error_report': 'Traceback (most recent call last):\n  File "xxx/fate_flow/worker/task_executor.py", line 209, in _run_\n    cpn_output = run_object.run(cpn_input)\n  File "xxx/federatedml/model_base.py", line 239, in run\n    self._run(cpn_input=cpn_input)\n  File "xxx/federatedml/model_base.py", line 318, in _run\n    this_data_output = func(*params)\n  File "xxx/federatedml/nn/homo_nn/enter_point.py", line 154, in fit\n    from federatedml.nn.homo_nn._torch import build_trainer\n  File "xxx/federatedml/nn/homo_nn/_torch.py", line 24, in <module>\n    import pytorch_lightning as pl\nModuleNotFoundError: No module named \'pytorch_lightning\'', 'end_time': 1666935679123, 'elapsed': 3570}`

dsl.json
`{
    "components": {
        "reader_0": {
            "module": "Reader",
            "output": {
                "data": [
                    "data"
                ]
            }
        },
        "homo_nn_0": {
            "module": "HomoNN",
            "input": {
                "data": {
                    "train_data": [
                        "reader_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ],
                "model": [
                    "model"
                ]
            }
        }
    }
`

conf.json
`{
    "dsl_version": 2,
    "initiator": {
        "role": "guest",
        "party_id": 9999
    },
    "role": {
        "arbiter": [
            10000
        ],
        "host": [
            10000
        ],
        "guest": [
            9999
        ]
    },
    "component_parameters": {
        "common": {
            "homo_nn_0": {
                "api_version": 2,
                "encode_label": true,
                "max_iter": 2,
                "batch_size": 32,
                "early_stop": {
                    "early_stop": "diff",
                    "eps": 0.0001
                },
                "optimizer": {
                    "lr": 0.001,
                    "optimizer": "Adam"
                },
                "loss": "NLLLoss",
                "metrics": [
                    "accuracy"
                ],
                "nn_define": [
                    {
                        "layer": "Conv2d",
                        "in_channels": 1,
                        "out_channels": 10,
                        "kernel_size": [
                            5,
                            5
                        ]
                    },
                    {
                        "layer": "MaxPool2d",
                        "kernel_size": 2
                    },
                    {
                        "layer": "ReLU"
                    },
                    {
                        "layer": "Conv2d",
                        "in_channels": 10,
                        "out_channels": 20,
                        "kernel_size": [
                            5,
                            5
                        ]
                    },
                    {
                        "layer": "Dropout2d"
                    },
                    {
                        "layer": "MaxPool2d",
                        "kernel_size": 2
                    },
                    {
                        "layer": "ReLU"
                    },
                    {
                        "layer": "Flatten"
                    },
                    {
                        "layer": "Linear",
                        "in_features": 320,
                        "out_features": 50
                    },
                    {
                        "layer": "ReLU"
                    },
                    {
                        "layer": "Linear",
                        "in_features": 50,
                        "out_features": 10
                    },
                    {
                        "layer": "LogSoftmax"
                    }
                ],
                "config_type": "pytorch"
            }
        },
        "role": {
            "host": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "homo_mnist_host",
                            "namespace": "homo_mnist_host"
                        }
                    }
                }
            },
            "guest": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "homo_mnist_guest",
                            "namespace": "homo_mnist_guest"
                        }
                    }
                }
            }
        }
    }`

**Comment by mgqa34** [comment]
What's the deployment mode of FATE? If it's docker compose or kubefate? If so, maybe you need to choose a version which  contains nn dependency like pytorch, or you should install the requirements yourself.

**Comment by talkingwallace** [comment]
hi! Would you mind trying our new demo branch? We have an update on homo-nn, now you can easily run MNIST example. :D
https://github.com/FederatedAI/FATE/tree/feature-1.10-nn-upgrade/%E6%95%99%E7%A8%8B
