### ISSUE TITLE
how fate do feature alignment?

### ISSUE THREAD

**Issue by bitdaocao** [FederatedAI/FATE#4404]
if the length of features in guest and host are not the same，errors will be occur In homoLR training；how can i train homoLR if guest and host have different length of features？

**Comment by dylan-fan** [comment]
now you will do it offline

**Comment by bitdaocao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by bitdaocao** [comment]
> now you will do it offline

ok，thanks。

**Comment by bitdaocao** [comment]
> > now you will do it offline
> 
> ok，thanks。



> now you will do it offline

in feature versions,will fate add function about feature alignment?
