### ISSUE TITLE
How to achieve federated learning on two or more machines using FATE?

### ISSUE THREAD

**Issue by navjotmakkar** [FederatedAI/FATE#4414]
### Discussed in https://github.com/FederatedAI/FATE/discussions/4410

<div type='discussions-op-text'>

<sup>Originally posted by **navjotmakkar** October 31, 2022</sup>
1. On one node(machine), the data scientist will have the model.
2. On multiple nodes(machines), the data owner are present with their own set of data.
During training the data is fetched from all the client nodes and the model is trained at the data scientist node just like it is done with PySyft.

Is it feasible to accomplish this use case with FATE, and if so, how? </div>

**Comment by talkingwallace** [comment]
Hi, currently FATE does not have certain algorithms/ modules that can meet your demands. However, you can develop your own algorithms modules. Based on the current FATE structure is possible to support this feature.
