### ISSUE TITLE
feature_selection筛选后到后面的模块发现特征并没有减少，在feature_selection处查看明明是显示变灰了好多变量

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4415]
feature_selection筛选后到后面的模块发现特征并没有减少，在feature_selection处查看明明是显示变灰了好多变量，是哪地方设置有问题吗？

**Comment by mgqa34** [comment]
麻烦截图下fate-board上selection的模型输出置灰部分详情，以及确认下data_output输出的特征真的依然包含这些过滤列，data_output可以从fateboard的data_ouptut页面看，或者使用flow tracking output-data-table获得输出的表库名后，再通过flow table info -t $table_name -n $table_namespace 获取表的header.
