### ISSUE TITLE
请问flow data upload上传的数据储存在哪里了呢？

### ISSUE THREAD

**Issue by sweetboxwwy** [FederatedAI/FATE#4416]

**Comment by yyf1986** [comment]
eggroll

**Comment by lidh15** [comment]
eggroll究竟是什么。。。是一种inno db？一种hdfs？
上传以后数据还是以某种格式存在的文件？还是变到一个memory里只能通过特定API看到？
是否有详细的文档解释eggroll到底干了什么

**Comment by lidh15** [comment]
FATE的开发者何必如此傲慢觉得这类问题都是弱智而拒绝明确回答，所谓社区不是带货直播间，哪怕真的是带货直播间也是把产品介绍清楚才更好卖

**Comment by zhihuiwan** [comment]
> eggroll究竟是什么。。。是一种inno db？一种hdfs？ 上传以后数据还是以某种格式存在的文件？还是变到一个memory里只能通过特定API看到？ 是否有详细的文档解释eggroll到底干了什么

eggroll是一个具有集成基础设施的多范式计算框架，其中基础设施包括编译/计算/存储/网络综合等内容。
上传数据后数据采用的是lmdb存储，并且支持分布式存储模式。详细可以参考：https://github.com/WeBankFinTech/eggroll

**Comment by zhihuiwan** [comment]
upload是fate提供的数据上传组件，其存储引擎支持egroll、hdfs等，由上传参数配置决定，默认存储引擎由系统配置决定。

**Comment by lidh15** [comment]
> 



> > eggroll究竟是什么。。。是一种inno db？一种hdfs？ 上传以后数据还是以某种格式存在的文件？还是变到一个memory里只能通过特定API看到？ 是否有详细的文档解释eggroll到底干了什么
> 
> eggroll是一个具有集成基础设施的多范式计算框架，其中基础设施包括编译/计算/存储/网络综合等内容。 上传数据后数据采用的是lmdb存储，并且支持分布式存储模式。详细可以参考：https://github.com/WeBankFinTech/eggroll

这个代码库里并没有详细介绍太多原理，比如为什么eggroll选择了lmdb这样一个在db-engine上热度只有redis百分之一的db，如果追求高效k-v存储为什么不使用redis？仅仅是因为数据文件不容易转化为适合redis存储的格式吗？

**Comment by lidh15** [comment]
> upload是fate提供的数据上传组件，其存储引擎支持egroll、hdfs等，由上传参数配置决定，默认存储引擎由系统配置决定。

是否有不使用egg roll的example？https://github.com/WeBankFinTech/eggroll 这个repo本身也没有任何example，fate的上传example里似乎也没有不使用egg roll的，作为使用者很难不认为fate只能使用eggroll，另外egg roll少写了一个g
