### ISSUE TITLE
纵向联邦学习中的Softmax问题

### ISSUE THREAD

**Issue by ATowerz** [FederatedAI/FATE#4417]
如果在纵向联邦学习中，A方拥有2种标签，B方拥有1种标签，A方神经网络输出层大小为2，B方神经网络输出层大小为1。想要对其进行全局化的Softmax应该怎么进行？

**Comment by talkingwallace** [comment]
目前FATE的hetero-nn还无法支持这种方式，标签只能在一方计算loss(即guest方）,如果需要实现，那需要修改原代码了

**Comment by ATowerz** [comment]
> 目前FATE的hetero-nn还无法支持这种方式，标签只能在一方计算loss(即guest方）,如果需要实现，那需要修改原代码了

请问一下实现的大概思路是什么呢，需要加密后直接softmax还是有其他方案呢。

**Comment by talkingwallace** [comment]
a方和b方的标签是一样的吗，是指多分类中的三个类

**Comment by ATowerz** [comment]
> a方和b方的标签是一样的吗，是指多分类中的三个类

嗯嗯可以这样理解，A方有其中2个类，B方有其中1个类，怎么考虑在这种情况下softmax呢。

**Comment by talkingwallace** [comment]
我感觉这种情况下或许横向联邦更适合一些？因为都是同一组标签，纵向联邦目前只支持一方有标签的
