### ISSUE TITLE
FateonSpark1.9.0问题

### ISSUE THREAD

**Issue by RicardoNing** [FederatedAI/FATE#4418]
Bug：pyspark集群运行是没有报错，但fate运行时候报错了，提示为相对路径不存在。

尝试：1.我用find搜索了全文都没有找到python_env这个路径，只有python_env.zip被我放入了HDFS里。

本人是华润员工，我司想利用贵司平台进行应用，希望贵司能协助搭建

微信：RicardoNjw

详细Bug：
[ERROR] [2022-11-03 14:49:19,601] [202211031444001524120] [67708:140665176889152] - [task_executor._run_] [line:265]: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
2
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1) (VM-0-1-centos executor driver): java.io.IOException: Cannot run program "./python_env/python/venv/bin/python": error=2, No such file or directory

**Comment by RicardoNing** [comment]
pyspark是进行过测试例子的。主要是你这里是相对路径./python_env, 我也不知道加什么进去spark_env.sh

**Comment by zhihuiwan** [comment]
请问下您的spark环境是yarn模式吗？

**Comment by RicardoNing** [comment]
> 请问下您的spark环境是yarn模式吗？
是的

**Comment by RicardoNing** [comment]
> 请问下您的spark环境是yarn模式吗？

方便加微信进一步沟通吗 谢谢

**Comment by lvying0019** [comment]
yarn模式下好像有问题，我之前也遇到了，不支持yarn模式
