### ISSUE TITLE
fate_flow_client.py这个文件可以直接运行嘛，需要填哪些参数呢？默认值是什么？

### ISSUE THREAD

**Issue by sweetboxwwy** [FederatedAI/FATE#4419]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sweetboxwwy** [comment]
运行后报错：
{
    "retcode": 100,
    "retmsg": "local variable 'response' referenced before assignment",
    "traceback": [
        "Traceback (most recent call last):\n",
        "  File \"/home/wangwy/PycharmProjects/Docker/FATE/fateflow/python/fate_flow_client.py\", line 292, in <module>\n    response = call_fun(args.function, config_data, dsl_path, config_path)\n",
        "  File \"/home/wangwy/PycharmProjects/Docker/FATE/fateflow/python/fate_flow_client.py\", line 221, in call_fun\n    return response.json() if isinstance(response, requests.models.Response) else response\n",
        "UnboundLocalError: local variable 'response' referenced before assignment\n"
    ]
}


function填的默认值是default=DATA_FUNC + MODEL_FUNC + JOB_FUNC + JOB_OPERATE_FUNC + TASK_OPERATE_FUNC + TABLE_FUNC +
                                TRACKING_FUNC + PERMISSION_FUNC,

**Comment by mgqa34** [comment]
建议直接使用cli v2，pip install fate-client之后使用 flow xxx的命令行方式，flow cli v1已经停止维护了。
