### ISSUE TITLE
请问flow data upload -c [options]命令中的json文件最后一句是什么意思呢

### ISSUE THREAD

**Issue by sweetboxwwy** [FederatedAI/FATE#4423]
测试用的数据是breast_homo_guest.csv,breast_homo_host.csv,breast_homo_test.csv
{
    "file": "/data/projects/fate/wangwy/breast_homo_guest.csv",
    "id_delimiter": ",",
    "head": 1,
    "partition": 10,
    "namespace": "experiment",
    "table_name": "breast_homo_guest",
    "storage_engine": "EGGROLL"
}
每次加上这一句"storage_engine": "EGGROLL"程序就会报错OSError: EGGROLL_HOME is not set,去掉这句就不会报错

而且使用docker方式部署单机版并不能成功运行fate_flow_client.py程序，参考https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/README.zh.md

会报错no module named "eggroll.core"，而且/data/projects/fate/fateflow/python下面根本没有fate_arch和eggroll这些，把他们复制过来才可以运行成功

**Comment by mgqa34** [comment]
看起来您这边部署的是standalone（单机版），单机版不是基于eggroll存储引擎的，将storage_engine这个keyword删掉就行
