### ISSUE TITLE
how to do calculation between columns

### ISSUE THREAD

**Issue by nvgruel123** [FederatedAI/FATE#4428]
Is there a way to do calculations like add/sub/mul between two columns after intersection?

**Comment by nvgruel123** [comment]
from different parties

**Comment by mgqa34** [comment]
HeteroPearson uses spdz protocol to calculate the correlation between two columns, you can refer to that component.

**Comment by nvgruel123** [comment]
> HeteroPearson uses spdz protocol to calculate the correlation between two columns, you can refer to that component.

great I'll try later, thank you
