### ISSUE TITLE
many-to-many intersect support?

### ISSUE THREAD

**Issue by nvgruel123** [FederatedAI/FATE#4429]
when I using intersection components, it only support one-to-many on with match id, is there a way to support many to many intersection?

also match_id_name and match_id_index param not working, it always match the first column's values instead of name or index.

**Comment by nemirorox** [comment]
1. Would you please elaborate on the meaning of "many-to-many"? Currently, FATE supports multi-host secure PSI, and only ids existing in all parties will be returned.
2. Note that only when `match_id_name` or `match_id_index` is specified in `meta` field of data uploading configuration, either param becomes valid in DataTransform module. Here is an example: https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_uploading_data_with_meta.ipynb
