### ISSUE TITLE
heteroNN 模块对 bottom model 的输出进行加密了吗

### ISSUE THREAD

**Issue by tanjuntao** [FederatedAI/FATE#4431]
[官方文档](https://fate.readthedocs.io/en/latest/federatedml_component/hetero_nn/) 中描述了一个比较复杂的训练协议，其中对 Host 方 bottom model 的输出进行了同态加密，但是阅读 heteroNN 的源代码后，发现似乎 FATE 并没有对输出进行加密，想确认下是这样吗。

**Comment by talkingwallace** [comment]
这个肯定是加密的了

**Comment by tanjuntao** [comment]
好的谢谢，我也注意到 `interactive_layer.py` 这个文件了。

**Comment by tanjuntao** [comment]
顺便借此想问下，如果不想对 Host 方 bottom model 输出的 embedding 进行加密的话，有没有可以一键关闭的参数呢？

**Comment by talkingwallace** [comment]
> 顺便借此想问下，如果不想对 Host 方 bottom model 输出的 embedding 进行加密的话，有没有可以一键关闭的参数呢？

这个目前不支持的 加密是强制的哈
