### ISSUE TITLE
[question]what influence the output format of components?

### ISSUE THREAD

**Issue by nvgruel123** [FederatedAI/FATE#4436]
I notice some components have different display on fateboard, such as evaluation and data_transform, what makes the difference? I implement a new component, but nothing shows on fateboard, what i miss here?

**Comment by talkingwallace** [comment]
Did your component return anything in the fit() function?

**Comment by nvgruel123** [comment]
> Did your component return anything in the fit() function?

i forgot to set schema of data, so nothing display, thanks.
