### ISSUE TITLE
运行python pipeline-mini-demo.py报错！

### ISSUE THREAD

**Issue by sweetboxwwy** [FederatedAI/FATE#4448]
参考https://github.com/FederatedAI/FATE/blob/master/doc/api/fate_client/pipeline.md

Traceback (most recent call last):
  File "pipeline-mini-demo.py", line 17, in <module>
    from pipeline.backend.pipeline import PipeLine
ImportError: No module named pipeline.backend.pipeline

**Comment by mgqa34** [comment]
请确认已经安装fate-client依赖

**Comment by sweetboxwwy** [comment]
> 请确认已经安装fate-client依赖

装了的，现在又报了另一个错误~

2022-11-17 11:18:48.076133: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2022-11-17 11:18:48.076201: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-11-17 11:19:15.558 | ERROR    | __main__:main:85 - An error has been caught in function 'main', process 'MainProcess' (15428), thread 'MainThread' (140456748521280):
Traceback (most recent call last):

  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/fate_client-1.8.0-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 74, in submit_job
    raise ValueError(f"retcode err")

ValueError: retcode err


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "pipeline-mini-demo.py", line 122, in <module>
    main()
    └ <function main at 0x7fbea2902ea0>

> File "pipeline-mini-demo.py", line 85, in main
    pipeline.fit()
    │        └ <function PipeLine.fit at 0x7fbe5b5f0b70>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fbe9b0e1e10>

  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/fate_client-1.8.0-py3.6.egg/pipeline/backend/pipeline.py", line 565, in fit
    self._train_job_id, detail_info = self._job_invoker.submit_job(self._train_dsl, training_conf, callback_func)
    │    │                            │    │            │          │    │           │              └ None
    │    │                            │    │            │          │    │           └ {'dsl_version': 2, 'initiator': {'role': 'guest', 'party_id': 9999}, 'role': {'arbiter': [10000], 'host': [10000], 'guest': [...
    │    │                            │    │            │          │    └ {'components': {'reader_0': {'module': 'Reader', 'output': {'data': ['data']}, 'provider': 'fate_flow'}, 'data_transform_0': ...
    │    │                            │    │            │          └ <pipeline.backend.pipeline.PipeLine object at 0x7fbe9b0e1e10>
    │    │                            │    │            └ <function JobInvoker.submit_job at 0x7fbe5b5e7268>
    │    │                            │    └ <pipeline.utils.invoker.job_submitter.JobInvoker object at 0x7fbe9b0e1e48>
    │    │                            └ <pipeline.backend.pipeline.PipeLine object at 0x7fbe9b0e1e10>
    │    └ None
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fbe9b0e1e10>
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/fate_client-1.8.0-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 82, in submit_job
    raise ValueError("job submit failed, err msg: {}".format(result))
                                                             └ {'jobId': '202211171118504201990', 'retcode': 103, 'retmsg': 'Traceback (most recent call last):\n  File "/data/projects/fate...

ValueError: job submit failed, err msg: {'jobId': '202211171118504201990', 'retcode': 103, 'retmsg': 'Traceback (most recent call last):\n  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py", line 133, in submit\n    raise Exception("create job failed", response)\nException: (\'create job failed\', {\'arbiter\': {10000: {\'data\': {\'components\': {\'data_transform_0\': {\'need_run\': False}, \'hetero_lr_0\': {\'need_run\': True}, \'intersection_0\': {\'need_run\': False}, \'reader_0\': {\'need_run\': False}}}, \'retcode\': 0, \'retmsg\': \'success\'}}, \'host\': {10000: {\'data\': {\'components\': {\'data_transform_0\': {\'need_run\': True}, \'hetero_lr_0\': {\'need_run\': True}, \'intersection_0\': {\'need_run\': True}, \'reader_0\': {\'need_run\': True}}}, \'retcode\': 0, \'retmsg\': \'success\'}}, \'guest\': {9999:{\'retcode\': <RetCode.FEDERATED_ERROR: 104>, \'retmsg\': \'Federated schedule error, Please check rollSite and fateflow network connectivityrpc request error: <_Rendezvous of RPC that terminated with:\\n\\tstatus = StatusCode.UNAVAILABLE\\n\\tdetails = "\\n[Roll Site Error TransInfo] \\n location msg=UNAVAILABLE: Network closed for unknown reason \\n stack info=io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason\\n\\tat io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)\\n\\tat io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)\\n\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\n\\tat com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\n\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\n\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\n\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\n\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\n\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\n\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\n\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)\\n\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\n\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n\\tat java.lang.Thread.run(Thread.java:748)\\n \\n\\nexception trans path: 10.81.8.22(10000)"\\n\\tdebug_error_string = "{"created":"@1668655137.346839879","description":"Error received from peer ipv4:10.81.8.22:9370","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"\\\\n[Roll Site Error TransInfo] \\\\n location msg=UNAVAILABLE: Network closed for unknown reason \\\\n stack info=io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason\\\\n\\\\tat io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)\\\\n\\\\tat io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)\\\\n\\\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\\\n\\\\tatcom.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\\\n\\\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\\\n\\\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\\\n\\\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\\\n\\\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\\\n\\\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\\\n\\\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\\\n\\\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)\\\\n\\\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\\\n\\\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\\\n\\\\tat java.lang.Thread.run(Thread.java:748)\\\\n \\\\n\\\\nexception trans path: 10.81.8.22(10000)","grpc_status":14}"\\n>\'}}})\n'}
Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/fate_client-1.8.0-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 74, in submit_job
    raise ValueError(f"retcode err")
ValueError: retcode err

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipeline-mini-demo.py", line 122, in <module>
    main()
  File "pipeline-mini-demo.py", line 85, in main
    pipeline.fit()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/fate_client-1.8.0-py3.6.egg/pipeline/backend/pipeline.py", line 565, in fit
    self._train_job_id, detail_info = self._job_invoker.submit_job(self._train_dsl, training_conf, callback_func)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/fate_client-1.8.0-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 82, in submit_job
    raise ValueError("job submit failed, err msg: {}".format(result))
ValueError: job submit failed, err msg: {'jobId': '202211171118504201990', 'retcode': 103, 'retmsg': 'Traceback (most recent call last):\n  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py", line 133, in submit\n    raise Exception("create job failed", response)\nException: (\'create job failed\', {\'arbiter\': {10000: {\'data\': {\'components\': {\'data_transform_0\': {\'need_run\': False}, \'hetero_lr_0\': {\'need_run\': True}, \'intersection_0\': {\'need_run\': False}, \'reader_0\': {\'need_run\': False}}}, \'retcode\': 0, \'retmsg\': \'success\'}}, \'host\': {10000: {\'data\': {\'components\': {\'data_transform_0\': {\'need_run\': True}, \'hetero_lr_0\': {\'need_run\': True}, \'intersection_0\': {\'need_run\': True}, \'reader_0\': {\'need_run\': True}}}, \'retcode\': 0, \'retmsg\': \'success\'}}, \'guest\': {9999:{\'retcode\': <RetCode.FEDERATED_ERROR: 104>, \'retmsg\': \'Federated schedule error, Please check rollSite and fateflow network connectivityrpc request error: <_Rendezvous of RPC that terminated with:\\n\\tstatus = StatusCode.UNAVAILABLE\\n\\tdetails = "\\n[Roll Site Error TransInfo] \\n location msg=UNAVAILABLE: Network closed for unknown reason \\n stack info=io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason\\n\\tat io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)\\n\\tat io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)\\n\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\n\\tat com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\n\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\n\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\n\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\n\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\n\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\n\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\n\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)\\n\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\n\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n\\tat java.lang.Thread.run(Thread.java:748)\\n \\n\\nexception trans path: 10.81.8.22(10000)"\\n\\tdebug_error_string = "{"created":"@1668655137.346839879","description":"Error received from peer ipv4:10.81.8.22:9370","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"\\\\n[Roll Site Error TransInfo] \\\\n location msg=UNAVAILABLE: Network closed for unknown reason \\\\n stack info=io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason\\\\n\\\\tat io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)\\\\n\\\\tat io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)\\\\n\\\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\\\n\\\\tatcom.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\\\n\\\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\\\n\\\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\\\n\\\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\\\n\\\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\\\n\\\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\\\n\\\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\\\n\\\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)\\\\n\\\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\\\n\\\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\\\n\\\\tat java.lang.Thread.run(Thread.java:748)\\\\n \\\\n\\\\nexception trans path: 10.81.8.22(10000)","grpc_status":14}"\\n>\'}}})\n'}
