### ISSUE TITLE
fate 1.7.0 版本 top_layer_units 字段值不对

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FATE#4455]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
fate 1.7.0 版本 vehicle数据集分类数是4，分类标签是0,1,2,3 
FATE/examples/benchmark_quality/hetero_nn/hetero_nn_vehicle_scale_config.yaml  
top_layer_units这个字段值是不是不对，不应该是3吗？ 但是 配置文件中是4，请教一下

**Comment by talkingwallace** [comment]
是不能跑通吗？这个版本下，如果unit没对上，会自动匹配输入的
