### ISSUE TITLE
fate-flow注册到zookeeper时服务地址乱码

### ISSUE THREAD

**Issue by 30skl** [FederatedAI/FATE#4466]
fate-flow注册到zookeeper时服务地址乱码，
![图片](https://user-images.githubusercontent.com/93366859/202995660-7af1997c-40fe-4ef0-bbcd-5d2d7ef0e6a2.png)
例如 172.16.111.11:9360 再zookeeper中变成了172.16.111.11%3A9360

**Comment by 30skl** [comment]
fate版本1.9.0   运行环境centos7  zookeeper版本3.7.1

**Comment by aoaos111** [comment]
解决了嘛大佬
