### ISSUE TITLE
模型训练后推送模型报错

### ISSUE THREAD

**Issue by 30skl** [FederatedAI/FATE#4472]
cd /data/projects/fate/examples/min_test_task/
python run_task.py -gid 9999 -hid 10000 -aid 10000 -f fast
训练完成后修改publish_load_model.json文件model_id和version 
执行
flow model load -c fate_flow/examples/model/publish_load_model.json
报错如下:
{
    "data": {
        "detail": {
            "guest": {
                "9999": {
                    "retcode": 100,
                    "retmsg": "Only deployed models could be used to execute process of loading. Please deploy model before loading."
                }
            },
            "host": {
                "10000": {
                    "retcode": 100,
                    "retmsg": "Only deployed models could be used to execute process of loading. Please deploy model before loading."
                }
            }
        },
        "guest": {
            "9999": 100
        },
        "host": {
            "10000": 100
        }
    },
    "jobId": "202211221456514629460",
    "retcode": 101,
    "retmsg": "failed"
}

**Comment by mgqa34** [comment]
Deploy model first，please refer to  this [example](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/dsl_conf/dsl_conf_tutorial.md#make-a-predict-conf-and-generate-predict-dsl)
