### ISSUE TITLE
hetero nn 是否可以在 bottom 里面添加多个 dense 层？

### ISSUE THREAD

**Issue by nkhklholyf** [FederatedAI/FATE#4474]
发现添加了多个 dense 层之后，运行过程中容易报错退出，目前是否支持多个层？例如：
host_nn_0.add_bottom_model(Dense(units=64, input_shape=(10,), activation="relu",
                                     kernel_initializer=initializers.Constant(value=1)))
host_nn_0.add_bottom_model(Dense(units=128, activation="relu"))
host_nn_0.add_bottom_model(Dense(units=256, activation="relu"))

**Comment by talkingwallace** [comment]
这个是支持的
