### ISSUE TITLE
Fate Flow Client SDK Guide fate-client 1.6.1 有没有查询指定命名空间下的所有的表的方法

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FATE#4477]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Fate Flow Client SDK Guide fate-client 1.6.1 有没有查询指定命名空间下的已经上传的所有的表的方法
当前只有info和delete 两个方法，是不是只能通过查询fate_flow数据库查询指定命名空间下的已经上传的所有的表

**Comment by zhihuiwan** [comment]
是的
