### ISSUE TITLE
dataset issues

### ISSUE THREAD

**Issue by KAgBMan** [FederatedAI/FATE#4487]
When I was looking at the default credit dataset, I found a problem. The dataset downloaded by Kaggle was inconsistent with the data file in Docker. What did FATE do to the dataset? Normalization or other?
This was downloaded by kaggle
![image](https://user-images.githubusercontent.com/22344179/202985612-1568a93c-419a-44a1-83bc-491baf215913.png)
This is provided by fat
![image](https://user-images.githubusercontent.com/22344179/202985613-a3ab5e0d-8c52-49c2-a0c3-084a893f69fb.png)

**Comment by talkingwallace** [comment]
it's normalized
