### ISSUE TITLE
输出验证集的loss曲线

### ISSUE THREAD

**Issue by fengenbao** [FederatedAI/FATE#4488]
在训练hetero-lr时，支持输入train data和valid data，但是arbiter方只能输出train loss曲线，有没有输出valid loss的功能呢？
![image](https://user-images.githubusercontent.com/57557769/204701471-76c2c0f3-1c17-44ed-a4d7-3933818a0f9f.png)

**Comment by talkingwallace** [comment]
validate loss目前不支持的
