### ISSUE TITLE
FATE在k8s上的执行效率

### ISSUE THREAD

**Issue by Averryjj** [FederatedAI/FATE#4490]
方式1:以源码部署FATE在虚拟机上
方式2:以k8s方式部署FATE
方式1的执行效率，提交任务成功到任务真正执行间隔1秒左右，每个组件之间的数据流交互较快（在fateboard上观测到）
方式2的执行效率很慢，任务提交成功到任务开始真正执行间隔5秒左右，每个组件之间的数据流交互很慢（在fateboard上观测到）
尝试使用
![image](https://user-images.githubusercontent.com/89241701/204978023-aab92bec-08cd-4db3-adfa-211043bac948.png)
方式修改参数，好像没有用，方式2的效率还是很慢，请专家指教！感谢🙏

方式1 的部署配置：8C/16G，2个节点
方式2的部署配置：k8s 2个8C/32G 2个16C/64G的node节点，共4个

**Comment by mgqa34** [comment]
原先的issue已经transfer到了https://github.com/FederatedAI/KubeFATE/issues/809，可以在kubefate仓库进行讨论
