### ISSUE TITLE
请教一下，HeteroLR与HeteroSSHELR模型 区别是什么？都是LR模型，但是不知道他们的区别是什么？有点看不明白，您能不能帮忙解释一下

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FATE#4493]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
请教一下，HeteroLR与HeteroSSHELR模型 区别是什么？都是LR模型，但是不知道他们的区别是什么？有点看不明白，您能不能帮忙解释一下

**Comment by talkingwallace** [comment]
可以看一下文档里的介绍:
https://github.com/FederatedAI/FATE/blob/master/doc/federatedml_component/logistic_regression.md
