### ISSUE TITLE
横向安全提升树算法出错

### ISSUE THREAD

**Issue by sunyinggang** [FederatedAI/FATE#4497]
**Describe the bug**
fate1.8版本中，单机下使用横向安全提升树算法没有问题，但是使用docker-compose部署双机版（spark+rabbitmq）就会卡死，会卡在下面日志出现的这一步好几个小时都没有反应。在使用双机版横向逻辑回归就可以训练成功，因此怀疑横向安全提升树算法存在多机版不能运行的bug

**Screenshots**
guest的日志
![image](https://user-images.githubusercontent.com/27491738/205838455-43133e35-5ae7-4286-8c00-b611b7b2dbd2.png)
host的日志
![image](https://user-images.githubusercontent.com/27491738/205838636-6a0d3200-0be9-42ee-a7cf-94390452fcf8.png)
arbiter的日志
![image](https://user-images.githubusercontent.com/27491738/205838672-ddf5c0a2-3413-433e-897b-8cf23fbd2271.png)

**Comment by talkingwallace** [comment]
感觉机器间通信有问题 在DH交换的时候停住了

**Comment by sunyinggang** [comment]
> 感觉机器间通信有问题 在DH交换的时候停住了

我一开始也认为是这个问题，但是我用横向逻辑回归测试就没有问题，所以认为不是通信的问题，毕竟横向逻辑回归和安全提升树通信机制一样，后来我怀疑是算法在多机版状态中，初始化有问题，原因是我看了一下单机版横向安全提升树的日志，我这里也贴一下
guest日志
![image](https://user-images.githubusercontent.com/27491738/205850517-114267bf-cc87-48d5-96f2-7b62d56616bb.png)
host日志
![image](https://user-images.githubusercontent.com/27491738/205850542-da2e41c4-5a60-40dc-97af-e13600ad55f9.png)
arbiter日志
![image](https://user-images.githubusercontent.com/27491738/205850608-e064ca13-4806-43a0-9bbd-a5549855c25c.png)
可以看到guest和host日志，如果咱们假设密钥分发正常，是因为下一步报错，所以卡死了，那下一步日志就是和模型创建相关了，这里你们可以部署docker-compose版本的试试

**Comment by talkingwallace** [comment]
这里的话 卡死问题是稳定复现的吗？

**Comment by sunyinggang** [comment]
> 这里的话 卡死问题是稳定复现的吗？

对的，执行好几次都是卡死，包括我用官方配置文件也是，建议你们可以试一下

**Comment by talkingwallace** [comment]
好 多谢您的反馈！

**Comment by sunyinggang** [comment]
> 好 多谢您的反馈！

这两天通过日志输出测试了一下，找到了代码卡在了这里
![366a1fb3209e7ae9ab4d55cb6e3a424](https://user-images.githubusercontent.com/27491738/206842078-59c0d739-6b21-4afd-8a97-abf393f7ea9d.png)
他是根据判断属于table类型，进入到上面函数中的
![image](https://user-images.githubusercontent.com/27491738/206842151-7a66a8ee-6229-4ded-aaf6-2331326f8d0b.png)
然后我把上面rdd.count注释掉，代码可以继续执行，然后往下，同样又卡在了一个.count()函数中，而且也是进入到了table类型判断
![8dddb8791e67bf76c24563ad66bed60](https://user-images.githubusercontent.com/27491738/206842358-47f6ef84-8685-4db5-a16e-c3886d9e7e16.png)
然后我之前说横向逻辑回归可以，安全提升树这里报错，我去看了一下逻辑回归不是用的table类型，所以不会进到这个if，就不会卡死，安全提升树的是table类型，就会卡死，而且奇怪的是单机版横向安全提升树也不会卡死，能顺利训练，本来是想定位错误然后解决，但是现在错误定位到了，没有了解决思路，想问一下官方大概什么时候修复这个bug，感觉这种基础算法的bug是不是会尽快修复

**Comment by dylan-fan** [comment]
这里感觉是资源问题
