### ISSUE TITLE
请问关于pipeline的代码到底在哪里运行呢

### ISSUE THREAD

**Issue by sweetboxwwy** [FederatedAI/FATE#4498]
https://github.com/FederatedAI/FATE/blob/feature-1.10-nn-upgrade/%E6%95%99%E7%A8%8B/%E6%95%99%E7%A8%8B-1-Homo-NN%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B.ipynb
用docker部署的单机版，报错是服务没启动，但是已经运行了source init_env.sh

**Comment by talkingwallace** [comment]
应该是你没有启动fateflow 

bash fateflow/bin/service start

启动下fateflow?

**Comment by sweetboxwwy** [comment]
> 

启动了之后，运行In[9]的代码，也会报错ValueError: query job result is {'retcode': 100, 'retmsg': "BusyError('BusyError: database is locked')"}, can not parse useful info
