### ISSUE TITLE
Can not download the required package file from webank-ai

### ISSUE THREAD

**Issue by hackenjoe** [FederatedAI/FATE#4502]
I used the docker container solution for deployment of a MWE on Ubuntu
`wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/${version}/release/standalone_fate_docker_image_${version}_release.tar.gz`

--> leads to 404 not found. Version I tried to test is 1.7.0. Seems like the package is gone.

My OS:
Distributor ID: `Ubuntu`
Description:    `Ubuntu 20.04.3 LTS`

**Comment by mgqa34** [comment]
The link is wrong, use 
```shell
wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/${version}/release/standalone_fate_docker_image_${version}_release.tar
```

you can find the download links in [release list](https://github.com/FederatedAI/FATE/releases) or [wiki](https://github.com/FederatedAI/FATE/wiki/Download)
