### ISSUE TITLE
inference 接口 https://github.com/FederatedAI/KubeFATE/tree/master/docker-deploy 提供的案例中 模型guest在训练的过程中是10个参数，但是推理的时候只传递了5个参数，模型选择没有减少参数，这个是不是不对呀

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FATE#4505]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://github.com/FederatedAI/KubeFATE/tree/master/docker-deploy
curl -X POST -H 'Content-Type: application/json' -i 'http://192.168.7.2:8059/federation/v1/inference' --data '{
  "head": {
    "serviceId": "test"
  },
  "body": {
    "featureData": {
        "x0": 1.88669,
        "x1": -1.359293,
        "x2": 2.303601,
        "x3": 2.00137,
        "x4": 1.307686
    },
    "sendToRemoteFeatureData": {
        "phone_num": "122222222"
    }
  }
}'
inference 接口 https://github.com/FederatedAI/KubeFATE/tree/master/docker-deploy 提供的案例中 模型guest在训练的过程中是10个参数，但是推理的时候只传递了5个参数，模型选择也没有减少参数个数，这个是不是不对呀

**Comment by mgqa34** [comment]
docker-deploy的文档只是验证服务是否ok，在在线推理阶段，lr算法会将缺失的特征当作0值处理（如果data_transform流程不处理缺失值的话），所以不影响流程测试
