### ISSUE TITLE
请问使用bash /bin/service.sh start时是否需要服务器联网呢

### ISSUE THREAD

**Issue by sweetboxwwy** [FederatedAI/FATE#4508]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by talkingwallace** [comment]
启动fateflow不需要的

**Comment by sweetboxwwy** [comment]
> 启动fateflow不需要的



> 启动fateflow不需要的

但是没有网络总是启动失败，有网络才能成功是怎么回事呢

**Comment by talkingwallace** [comment]
看一下启动失败的返回？

**Comment by sweetboxwwy** [comment]
报错是
service start failed, please check /data/projects/fate/fateflow/logs/error.log and /data/projects/fate/fateflow/logs/console.log
check process by http port and grpc port

然后输入
vi /data/projects/fate/fateflow/logs/error.log

输出是
E1109 07:18:16.306598779    9783 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers

**Comment by talkingwallace** [comment]
这个不是联网的问题, 报错显示你的环境有其他线程在调用grpc
