### ISSUE TITLE
arbiter节点数据是否可同步给guest，host

### ISSUE THREAD

**Issue by shadowxz** [FederatedAI/FATE#4517]
Fate中逻辑回归，kmeans等算法中都有arbiter节点计算、数据输出、指标等数据是否属于隐私数据？ guest无法得知、获取这些数据是否影响模型训练？

**Comment by shadowxz** [comment]
@weiwee 请教个问题kmeans算法中arbiter节点的数据信息是否包含隐私数据，如果被guest或者host方获知了的话，算不算泄隐？

**Comment by tanmc123** [comment]
> 

个人认为，arbiter所持有的信息肯定是需要被保护的，否则的话，就没有arbiter存在的意义了，直接发给对面即可。同时，arbiter一般持有的都是算法中间的计算结果，对于guest和host而言，没有这些中间结果并不影响（或者说也足以完成）模型训练

**Comment by shadowxz** [comment]
您好，无法立即回复您的邮件。我将尽快给您回复。

**Comment by shadowxz** [comment]
您好，无法立即回复您的邮件。我将尽快给您回复。
