### ISSUE TITLE
FATE V1.9.2单机部署版本dockder容器启动问题

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4521]
使用Docker镜像安装FATE单机部署版本出现容器启动失败问题。
系统：Centos7
docker版本：20.10.21
docker-compose版本：1.25.4

防火墙已关闭
复现过程如下：
1、
export version=1.9.2

2、拉取镜像
wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/${version}/release/standalone_fate_docker_image_${version}_release.tar.gz
docker load -i standalone_fate_docker_image_${version}_release.tar.gz
docker images | grep federatedai/standalone_fate
镜像成功拉取

3、启动容器
docker run -d --name standalone_fate -p 8080:8080 federatedai/standalone_fate:${version};
无报错，但使用docker ps查看发现该容器状态为 exited（127）如下所示：
<img width="611" alt="3970404be6c020d2aeab5be8e096030" src="https://user-images.githubusercontent.com/49178688/207260752-7afab131-0ada-44ec-991e-ce207915af7c.png">

使用 docker logs 查看该容器日志如下：
<img width="606" alt="51d1990d521a62f0335eae5c003c7b9" src="https://user-images.githubusercontent.com/49178688/207261067-5036556e-c529-46ff-8f0b-005d5f1484a8.png">
请问一下是什么问题呢？ 应该怎么解决，谢谢

**Comment by oceanqdu** [comment]
补个反馈，1.9.0没有这个问题，不知道是不是1.9.2独有的问题

**Comment by jat001** [comment]
已更新，请重新拉取镜像，启动命令：
```
docker run -it --name standalone_fate -p 8080:8080 federatedai/standalone_fate:${version}
```
