### ISSUE TITLE
Question: does FATE support one guest and multiple hosts?

### ISSUE THREAD

**Issue by lemonviv** [FederatedAI/FATE#4527]
Hi, I was wondering how to execute the vertical federated learning with one guest and multiple hosts, for example, 1 guest and 2 hosts. Is it supported by the current version? If so, may I ask where I can find exemplary DSL and conf files for this scenario? Thank you.

**Comment by mgqa34** [comment]
Yes, search "mult_host" keyword in hetero_secureboost or hetero_logistic_regression in examples/dsl/v2 or "mulit-host" in examples/pipeline

**Comment by lemonviv** [comment]
Thank you for the quick reply. 

I found the example in secureboost, but for logistic regression, I am not sure if the conf file is expected https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/hetero_logistic_regression/hetero_lr_multi_host_conf.json#L35, as host 0 and host 1 share the same table name. 

Also, do all the federated ml algorithms support multi_host, or only secureboost and logistic regression support?
