### ISSUE TITLE
Question: Hetero_NN example

### ISSUE THREAD

**Issue by lemonviv** [FederatedAI/FATE#4535]
Hi, I am learning the Hetero_NN example here https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/hetero_nn/test_hetero_nn_binary_conf.json. From my understanding, Hetero_NN implements the split learning framework. In the `hetero_nn_0` mode of the example, it defines the top_layer, bottom_layer, and interactive_layer. However, I am not clear about the `hetero_nn_1` definition, where the layers are all null. 

```
"hetero_nn_1": {
                "optimizer": null,
                "bottom_nn_define": null,
                "top_nn_define": null,
                "interactive_layer_define": null,
                "config_type": "keras"
            }
```

What is the purpose of the `hetero_nn_1` model used in this example? Appreciate it if anyone can give a hint. Thanks.

**Comment by talkingwallace** [comment]
Hi! In this case, hetero-nn-1 is for predicting, you can find in the DSL that it has a model input, so you can ignore these conf setting because there are already set as the input model.

**Comment by lemonviv** [comment]
Thank you.
