### ISSUE TITLE
分箱时报错，不知道数据有什么问题

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4540]
{'job_id': '202212201924125269130', 'component_name': 'hetero_feature_binning_0', 'task_id': '202212201924125269130_hetero_feature_binning_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': 'xxx.xxx.xxx.xxx', 'run_pid': 10297, 'run_port': '9380', 'party_status': 'failed', 'error_report': 'Traceback (most recent call last):\n  File "xxx/fate_flow/worker/task_executor.py", line 209, in _run_\n    cpn_output = run_object.run(cpn_input)\n  File "xxx/federatedml/model_base.py", line 239, in run\n    self._run(cpn_input=cpn_input)\n  File "xxx/federatedml/model_base.py", line 315, in _run\n    this_data_output = func(*real_param)\n  File "xxx/federatedml/feature/hetero_feature_binning/hetero_binning_guest.py", line 96, in transform\n    if data_instances.first()[1].label is None:\nTypeError: \'NoneType\' object is not subscriptable', 'end_time': 1671535502650, 'elapsed': 4619}

**Comment by mgqa34** [comment]
使用的部署方式是？从报错信息来看，data_instances.first()返回结果为None，请确认输入到binning数据非空

**Comment by Chuang007** [comment]
您的邮件已收到  谢谢~

**Comment by Chuang007** [comment]
> 使用的部署方式是？从报错信息来看，data_instances.first()返回结果为None，请确认输入到binning数据非空

我是用pipeline的方式加载训练好的模型测试，测试的模块有包含训练时用的分箱模块

**Comment by Chuang007** [comment]
> 使用的部署方式是？从报错信息来看，data_instances.first()返回结果为None，请确认输入到binning数据非空

谢谢您，按照您说的我看了一下求交的数量为0

**Comment by Chuang007** [comment]
> 使用的部署方式是？从报错信息来看，data_instances.first()返回结果为None，请确认输入到binning数据非空

但是csv文件的id有交集，为什么求交出来的是0呢？
