### ISSUE TITLE
fate1.9训练完模型加载模型时报错

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4557]
{
    "data": {
        "detail": {
            "guest": {
                "8887": {
                    "retcode": 123,
                    "retmsg": "model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct. "
                }
            },
            "host": {
                "8888": {
                    "retcode": 123,
                    "retmsg": "model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct. "
                }
            }
        },
        "guest": {
            "8887": 123
        },
        "host": {
            "8888": 123
        }
    },
    "jobId": "202212271450006697240",
    "retcode": 101,
    "retmsg": "failed"
}

**Comment by 2294930685** [comment]
@Chuang007 May I ask how you solved it? I also encountered this problem

**Comment by Chuang007** [comment]
您的邮件已收到  谢谢~

**Comment by 2294930685** [comment]
@Chuang007 你好，这个问题我也遇到了，是需要怎么解决呀？
