### ISSUE TITLE
host方为什么不支持woe转换？

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4562]
![image](https://user-images.githubusercontent.com/50570278/209918340-428b554d-2b81-4736-9939-d06e93c52101.png)
业务需要各方都计算woe值，但报错host不能转换，为什么？

**Comment by dylan-fan** [comment]
host方拿不到woe值

**Comment by Chuang007** [comment]
> host方拿不到woe值

好的，谢谢
