### ISSUE TITLE
加载环境变量失败？

### ISSUE THREAD

**Issue by 0329-rosa** [FederatedAI/FATE#4566]
按照2下面的操作提示来，走到启动docker run it这步的时候弹出来一堆check process然后就卡住不动了，怎么操作也没反应，请问是怎么回事呢

**Comment by dylan-fan** [comment]
用的是kubefate吗？

**Comment by 0329-rosa** [comment]
> 

就是按那个单机部署指南里的docker镜像安装的教程，但是现在启动后就一直卡住不动了只显示一个Java_home=……然后测试也显示没有该文件目录😿

**Comment by mgqa34** [comment]
请问是哪个版本？使用的指令是？

**Comment by 0329-rosa** [comment]
> 请问是哪个版本？使用的指令是？

安的fate1.7.0，然后输入docker run it之后就是弹出一堆check process之后就没反应了…什么指令也跑不了

**Comment by mgqa34** [comment]
1.7.0和1.10.0的启动指令是有diff的，有可能是用错指令的问题吗？ 下面是1.7.0的启动指令：https://github.com/FederatedAI/FATE/blob/v1.7.0/deploy/standalone-deploy/README.zh.md#23-%E5%90%AF%E5%8A%A8

**Comment by 0329-rosa** [comment]
> 1.7.0和1.10.0的启动指令是有diff的，有可能是用错指令的问题吗？ 下面是1.7.0的启动指令：https://github.com/FederatedAI/FATE/blob/v1.7.0/deploy/standalone-deploy/README.zh.md#23-%E5%90%AF%E5%8A%A8

我用镜像包跑完之后出现的是1.7.0，然后启动指令用的也是这个，但是很多次了都是…出现很多check process然后就没反应了😿

**Comment by 0329-rosa** [comment]
> 1.7.0和1.10.0的启动指令是有diff的，有可能是用错指令的问题吗？ 下面是1.7.0的启动指令：https://github.com/FederatedAI/FATE/blob/v1.7.0/deploy/standalone-deploy/README.zh.md#23-%E5%90%AF%E5%8A%A8

！！用这个重新试了一下可以了！toy测试过了呜呜呜谢谢您！！
