### ISSUE TITLE
横向逻辑回归训练过程添加加密参数后训练过程卡住

### ISSUE THREAD

**Issue by kaiwang0112006** [FederatedAI/FATE#4567]
使用fate版本：1.7.2

按A，B，C三个节点部署

问题描述：

测试横向逻辑回归脚本：https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/homo_logistic_regression/pipeline-homo-lr-train-eval.py， 可以在两分钟左右完成训练，在param中增加加密参数（"encrypt_param": {"method": "Paillier", "key_length": 512}）之后，训练在第一轮完成后一直卡住不能开始第二轮迭代。
所以两个问题：

1.  如果没有“encrypt_param”，Fate的横向联邦是否安全，“encrypt_param”是不是必须的
2. 为什么训练过程卡住，是加密过程导致的吗

**Comment by dylan-fan** [comment]
这个参数不是必须得的。如果需要用，建议key_length至少1024

**Comment by dylan-fan** [comment]
1.10版本横向算法有较大升级，可以考虑升级使用

**Comment by kaiwang0112006** [comment]
> 这个参数不是必须得的。如果需要用，建议key_length至少1024

encrypt_param": {"method": "Paillier", "key_length": 1024}， 训练过程也会卡住，所以训练过程卡住的问题需要通过升级版本解决对吧，那如果没有encrypt_param，Fate的横向联邦是否安全？只是明文传输参数的训练过程吗

**Comment by dylan-fan** [comment]
横向默认用的SecureAgg保护

**Comment by kaiwang0112006** [comment]
基于Diffie-Hellman 密钥交换协议是吗
