### ISSUE TITLE
docker无法启动？

### ISSUE THREAD

**Issue by 0329-rosa** [FederatedAI/FATE#4568]
按照教程第2.3步启动docker run it的时候长久卡在一个界面，一长串的check process之后就什么也操作不了。想问一下这是怎么回事呢？

**Comment by mgqa34** [comment]
哪个版本呢？1.10.0版本启动指令和之前有diff

**Comment by 0329-rosa** [comment]
> 哪个版本呢？1.10.0版本启动指令和之前有diff

1.7.0…但是拉取镜像的时候报错no such image这样…然后也启动不了

**Comment by mgqa34** [comment]
下载可以参考wiki: https://github.com/FederatedAI/FATE/wiki/Download 
另一个问题：如果是no such image。。那是怎么获取镜像去启动的呢

**Comment by mgqa34** [comment]
看起来issue已经解决，https://github.com/FederatedAI/FATE/issues/4566，先关闭了，如果有问题的话再reopen
