### ISSUE TITLE
How to only use partial data in each epoch 

### ISSUE THREAD

**Issue by Timo9Madrid7** [FederatedAI/FATE#4569]
Hi,

I noticed that every participant will train her/his model using the whole local dataset for every online_epoch. For example, it is supposed that A/B has 3200 samples, if `batch_size=32`, A/B will use 100 mini_batches for a single local training round. Considering the convergency of aggregation and security, it would be better only use fractional mini_batches, e.g. 0.1*100=10, for the local train in each epoch. Does fate currently support configuring this hyperparameter? 

regards,
Timo

**Comment by talkingwallace** [comment]
Hi! Which algorithm you are using now?

**Comment by Timo9Madrid7** [comment]
> Hi! Which algorithm you are using now?
Homo NN with PyTorch backend

**Comment by talkingwallace** [comment]
Hi！, currently FATE does not support this function, however, I think it is easy to get this feature:

1. In fedavg trainer(https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py), you can modify the code of the train and aggregation process to meet your demand, see:
1) https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py#L170
2) https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py#L329

2.  Or you can write a new trainer:
https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-Trainer.ipynb

Hope these help you

**Comment by Timo9Madrid7** [comment]
> Hi！, currently FATE does not support this function, however, I think it is easy to get this feature:
> 
> 1. In fedavg trainer(https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py), you can modify the code of the train and aggregation process to meet your demand, see:
> 
> * https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py#L170
> * https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py#L329
> 
> 2. Or you can write a new trainer:
>    https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-Trainer.ipynb
> 
> Hope these help you

Yes, these are really helpful, but this method only works for version 1.9, doesn't it? Do you have any suggestions for a lower version like 1.7 or 1.8?

Sincerely thanks,

**Comment by talkingwallace** [comment]
> 

For the lower version, codes related to local training is here:
https://github.com/FederatedAI/FATE/blob/v1.9.0/python/federatedml/nn/homo_nn/_torch.py#L501

HomoNNClient uses the built trainer for local training, then the model will be aggregated:
https://github.com/FederatedAI/FATE/blob/v1.9.0/python/federatedml/nn/homo_nn/enter_point.py#L135

I hope this can help you :D

**Comment by Timo9Madrid7** [comment]
> > 
> 
> For the lower version, codes related to local training is here: https://github.com/FederatedAI/FATE/blob/v1.9.0/python/federatedml/nn/homo_nn/_torch.py#L501
> 
> HomoNNClient uses the built trainer for local training, then the model will be aggregated: https://github.com/FederatedAI/FATE/blob/v1.9.0/python/federatedml/nn/homo_nn/enter_point.py#L135
> 
> I hope this can help you :D

Great! Thank you 😄
