### ISSUE TITLE
Job Failed Check out fate board or fate_flow cli 

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4575]
Hello, 
All the jobs I submit fail at 'reader_0' stage. Could anyone help ? 

_______________________________________________________________________________________________________________
2023-01-06 20:18:29.382 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:83 - Job id is 202301062018283098550
                  Job is still waiting, time elapse: 0:00:01
2023-01-06 20:18:32Running component reader_0, time elapse: 0:00:28
2023-01-06 20:19:00.270 | ERROR    | __main__:main:93 - An error has been caught in function 'main', process 'MainProcess' (34149), thread 'MainThread' (274922721280):
Traceback (most recent call last):

  File "pipeline-data-statistics-partial-column.py", line 106, in <module>
    main()
    └ <function main at 0x4066a21e50>

> File "pipeline-data-statistics-partial-column.py", line 93, in main
    pipeline.fit()
    │        └ <function PipeLine.fit at 0x4067381280>
    └ <pipeline.backend.pipeline.PipeLine object at 0x406738a100>

  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.9.0-py3.8.egg/pipeline/backend/pipeline.py", line 573, in fit
    self._fit_status = self._job_invoker.monitor_job_status(self._train_job_id,
    │    │             │    │            │                  │    └ '202301062018283098550'
    │    │             │    │            │                  └ <pipeline.backend.pipeline.PipeLine object at 0x406738a100>
    │    │             │    │            └ <function JobInvoker.monitor_job_status at 0x4067374670>
    │    │             │    └ <pipeline.utils.invoker.job_submitter.JobInvoker object at 0x406738a190>
    │    │             └ <pipeline.backend.pipeline.PipeLine object at 0x406738a100>
    │    └ None
    └ <pipeline.backend.pipeline.PipeLine object at 0x406738a100>
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.9.0-py3.8.egg/pipeline/utils/invoker/job_submitter.py", line 94, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")

ValueError: Job is failed, please check out job 202301062018283098550 by fate board or fate_flow cli
Traceback (most recent call last):
  File "pipeline-data-statistics-partial-column.py", line 106, in <module>
    main()
  File "pipeline-data-statistics-partial-column.py", line 93, in main
    pipeline.fit()
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/loguru/_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.9.0-py3.8.egg/pipeline/backend/pipeline.py", line 573, in fit
    self._fit_status = self._job_invoker.monitor_job_status(self._train_job_id,
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.9.0-py3.8.egg/pipeline/utils/invoker/job_submitter.py", line 94, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")
ValueError: Job is failed, please check out job 202301062018283098550 by fate board or fate_flow cli

**Comment by amyseoj1** [comment]
+ I made sure data is uploaded.

**Comment by WSYGDJM** [comment]
一般如果出现这类情况，是需要到fateboard找问题原因，笔者之前是因为某台节点没有正确上传数据造成的问题

**Comment by amyseoj1** [comment]
> 一般如果出现这类情况，是需要到fateboard找问题原因，笔者之前是因为某台节点没有正确上传数据造成的问题

Thank you so much for your reply !
The problem is that fate board does not have any error or warning message on the initiator side. 

![Screenshot 2023-01-09 at 13 59 46](https://user-images.githubusercontent.com/73941975/211325406-a73f33b2-1166-4e45-852b-83bde41c73fe.png)

**Comment by amyseoj1** [comment]
> > 一般如果出现这类情况，是需要到fateboard找问题原因，笔者之前是因为某台节点没有正确上传数据造成的问题
> 
> Thank you so much for your reply ! The problem is that fate board does not have any error or warning message on the initiator side.
> 
> ![Screenshot 2023-01-09 at 13 59 46](https://user-images.githubusercontent.com/73941975/211325406-a73f33b2-1166-4e45-852b-83bde41c73fe.png)

Info log:


Schedule Log
error
warning
info
362
debug
366
108
            9999
6
[INFO] [2023-01-08 11:39:45,413] [202301081139302667990] [15193:274922721280] - [base_worker.run] [line:103]: FATE_DEPLOY_BASE: /data/projects/fate
109
        ],
7
[INFO] [2023-01-08 11:39:45,414] [202301081139302667990] [15193:274922721280] - [base_worker.run] [line:103]: PYTHONPATH: /data/projects/fate/fateflow/python:/data/projects/fate/fate/python:/data/projects/fate/fateflow/python
110
        "host": [
8
[INFO] [2023-01-08 11:39:45,414] [202301081139302667990] [15193:274922721280] - [base_worker.run] [line:103]: PROCESS_ROLE: worker
111
            10000
9
[INFO] [2023-01-08 11:39:47,153] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update computing engine STANDALONE fate_on_standalone registration information
112
        ]
10
[INFO] [2023-01-08 11:39:47,179] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update computing engine EGGROLL fate_on_eggroll registration information
113
    },
11
[INFO] [2023-01-08 11:39:47,194] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update computing engine SPARK fate_on_spark registration information
114
    "job_parameters": {
12
[INFO] [2023-01-08 11:39:47,212] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update computing engine LINKIS_SPARK fate_on_spark registration information
115
        "job_type": "train",
13
[INFO] [2023-01-08 11:39:47,232] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update storage engine STANDALONE fate_on_standalone registration information
116
        "inheritance_info": {},
14
[INFO] [2023-01-08 11:39:47,251] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update storage engine EGGROLL fate_on_eggroll registration information
117
        "computing_engine": "STANDALONE",
15
[INFO] [2023-01-08 11:39:47,269] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update storage engine HDFS fate_on_spark registration information
118
        "federation_engine": "STANDALONE",
16
[INFO] [2023-01-08 11:39:47,321] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update storage engine HIVE fate_on_spark registration information
17
[INFO] [2023-01-08 11:39:47,350] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update storage engine LINKIS_HIVE fate_on_spark registration information
18
[INFO] [2023-01-08 11:39:47,378] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update federation engine STANDALONE fate_on_standalone registration information
19
[INFO] [2023-01-08 11:39:47,404] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update federation engine EGGROLL fate_on_eggroll registration information
20
[INFO] [2023-01-08 11:39:47,419] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update federation engine RABBITMQ fate_on_spark registration information
21
[INFO] [2023-01-08 11:39:47,434] [202301081139302667990] [15193:274922721280] - [resource_manager.register_engine] [line:64]: update federation engine PULSAR fate_on_spark registration information
22
[INFO] [2023-01-08 11:39:47,436] [202301081139302667990] [15193:274922721280] - [task_executor._run_] [line:56]: run reader_0 202301081139302667990_reader_0 0 on guest 9999 task
23
[INFO] [2023-01-08 11:39:48,488] [202301081139302667990] [15193:274922721280] - [task_executor._run_] [line:82]: user name:
24
[INFO] [2023-01-08 11:39:48,491] [202301081139302667990] [15193:274922721280] - [task_base_worker.report_task_info_to_driver] [line:113]: report TaskExecutor 202301081139302667990_reader_0 0 guest 9999 to driver:
25
{'job_id': '202301081139302667990', 'component_name': 'reader_0', 'task_id': '202301081139302667990_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': 'xxx.xxx.xxx.xxx', 'run_pid': 15193, 'run_port': '9380', 'party_status': 'running'}
30
{
34
        "party_id": 9999
36
    "role": {
37
        "guest": [
39
        ],
41
            10000
43
    },
45
        "common": {
47
            "inheritance_info": {},
49
            "engines_address": {},
50
            "federated_mode": "SINGLE",
55
            "model_version": "202301081139302667990",
56
            "auto_retries": 0,
57
            "auto_retry_delay": 1,
58
            "eggroll_run": {},
58
            "eggroll_run": {},
59
            "spark_run": {},
60
            "rabbitmq_run": {},
61
            "pulsar_run": {},
62
            "adaptation_parameters": {
62
            "adaptation_parameters": {
63
                "task_nodes": 1,
64
                "task_cores_per_node": 4,
65
                "task_memory_per_node": 0,
66
                "request_task_cores": 4,
67
                "if_initiator_baseline": true
77
    "ComponentParam": {

**Comment by amyseoj1** [comment]
I ran the demo pipeline_upload.py to upload breast_hetero_guest.csv and breast_hetero_host.csv prior to running above model.
