### ISSUE TITLE
fate rest api在线预测结果与预期不符合

### ISSUE THREAD

**Issue by relinda2019** [FederatedAI/FATE#4578]
**Describe the bug**
 横向LR,训练完成，在线预测，返回的结果与预期不符合，应该返回prob，但返回的是模型信息

To Reproduce

load model

http://x.x.x.x:9380/v1/model/load

{
    "initiator": {
        "party_id": "10000",
        "role": "guest"
    },
    "role": {
        "guest": [
            "10000"
        ],
        "host": [
            "9997"
        ],
        "arbiter": [
            "9998"
        ]
    },
    "job_parameters": {
        "model_id": "arbiter-9998#guest-10000#host-9997#model",
        "model_version": "202301061025474546970"
    }
}
bind model

http://x.x.x.x:9380/v1/model/bind

{
    "service_id": "002",
    "initiator": {
        "party_id": "10000",
        "role": "guest"
    },
    "role": {
        "guest": [
            "10000"
        ],
        "host": [
            "9997"
        ],
        "arbiter": [
            "9998"
        ]
    },
    "job_parameters": {
        "model_id": "arbiter-9998#guest-10000#host-9997#model",
        "model_version": "202301061025474546970"
    },
    "servings": []
}
返回：
![image-20230109115147392](https://user-images.githubusercontent.com/39260479/211238544-bb2f04c7-bfaa-42ae-9267-c8851e31ef57.png)

inference

http://x.x.x.x:8059/federation/v1/inference

{
    "head": {
        "serviceId": "002"
    },
    "body": {
        "featureData": {
            "x0": 0.254879,
            "x1": -1.046633,
            "x2": 0.2096559999999999,
            "x3": 0.074214,
            "x4": -0.441366,
            "x5": -0.377645,
            "x6": -0.485934,
            "x7": 0.347072,
            "x8": -0.28757,
            "x9": -0.733474,
            "x10": 0.4495119999999999,
            "x11": -1.247226,
            "x12": 0.413178,
            "x13": 0.3037809999999999,
            "x14": -0.123848,
            "x15": -0.184227,
            "x16": -0.219076,
            "x17": 0.2685369999999999,
            "x18": 0.015996,
            "x19": -0.789267,
            "x20": -0.33736,
            "x21": -0.728193,
            "x22": -0.442587,
            "x23": -0.272757,
            "x24": -0.6080180000000001,
            "x25": -0.577235,
            "x26": -0.5011260000000001,
            "x27": 0.143371,
            "x28": -0.466431,
            "x29": -0.5541020000000001
        }
    }
}
See error

![image-20230109114921522](https://user-images.githubusercontent.com/39260479/211238585-d30a4168-4814-4067-bdd5-82f19cf2a2dc.png)

Expected behavior

![image-20230109114957488](https://user-images.githubusercontent.com/39260479/211238637-97422a3b-9990-481a-a8f2-0e808d9cb19f.png)

**Comment by mgqa34** [comment]
Serving的host方adaptor读取特征数据流程是否正常？

**Comment by relinda2019** [comment]
跑的是一个横向逻辑回归的任务，这个是在guest方进行的在线预测，host方会对其有影响吗？
