### ISSUE TITLE
SID assumption

### ISSUE THREAD

**Issue by liyakun** [FederatedAI/FATE#4580]
**Describe the bug**
The current upload in SecureBoost related tutorial, like https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_hetero_sbt.ipynb, assumes that the first column is the `id` to align between clients. I am not sure whether this has been documented in anywhere-

**To Reproduce**
1. Upload csv file with first column not `id`
2. Check the upload file in FATE, then the csv file assumes the first column is `id` and change the column name to `sid`

**Expected behavior**
Why not parsing the csv file to find the column which is named `id` and throw error if could not find it?

**Screenshots**
![image](https://user-images.githubusercontent.com/7370334/211372809-05adc25e-e8e3-42b1-b2c7-71644af0dfb6.png)

I was having `y` in the first column in the beginning, and the column is renamed to `sid`. The above screenshot is after I shift the `id` column to the first column in the csv file.

**Desktop (please complete the following information):**
 - OS: opensuse tumbleweed
 - Browser: Firefox
 - Version: 108.0.1

**Additional context**
FATE version is 1.8.1

**Comment by talkingwallace** [comment]
Hi! In FATE it will automatically take the first column as the id column

**Comment by liyakun** [comment]
@talkingwallace thanks for replying. May I ask whether this has been documented anywhere? Btw, does FATE also assumes the second column should be the `label` column for classification task? Thanks.

**Comment by talkingwallace** [comment]
For the label column, you can specify it in the Data-Transform param. For any components in FATE, you can refer to [the document](https://fate.readthedocs.io/en/latest/federatedml_component/) or [param files](https://github.com/FederatedAI/FATE/tree/master/python/federatedml/param) to find the parameters.
