### ISSUE TITLE
新的standalone版本支持mac m2吗？

### ISSUE THREAD

**Issue by jeremypxh** [FederatedAI/FATE#4581]
[the deploy guide ](https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/README.zh.md)只写了可以在CentOS Linux release 7安装，mac上可以吗，如果有，有教程吗？

**Comment by talkingwallace** [comment]
可以考虑直接使用单机版的docker版，这个是OK的

**Comment by jeremypxh** [comment]
> 可以考虑直接使用单机版的docker版，这个是OK的

感谢

**Comment by jeremypxh** [comment]
> 

你好，我docker版运行的的时候，toy-test 一直过不了。tutorial里的pipeline up load也没能连接上。运行!pipeline config check的时候显示Flow server not responsive. Please check flow server ip and port setting.请问能怎么解决呢？

**Comment by talkingwallace** [comment]
> > 
> 
> 你好，我docker版运行的的时候，toy-test 一直过不了。tutorial里的pipeline up load也没能连接上。运行!pipeline config check的时候显示Flow server not responsive. Please check flow server ip and port setting.请问能怎么解决呢？

hi，这是没启动fateflow吧，你回到项目目录，bash bin/init.sh start启动下

**Comment by SquirminatorHotHead** [comment]
#4593  Mac M2 is not tested.
