### ISSUE TITLE
Homo-NN-Customize-Trainer.ipynb中，数据经过线性层处理后Linear(30, 1)后，输出为nan

### ISSUE THREAD

**Issue by WSYGDJM** [FederatedAI/FATE#4583]
RuntimeError                              Traceback (most recent call last)
Cell In[6], line 2
      1 trainer.local_mode()
----> 2 trainer.train(ds, None, opt, loss)

Cell In[2], line 62, in ToyFedProxTrainer.train(self, train_set, validate_set, optimizer, loss, extra_data)
     55                 print(pred)
     56 #                 m = nn.Linear(30, 1)
     57 #                 output = m(batch_data)
     58 # #                 print('output', output)
     59 #                 m2 = nn.Sigmoid()
     60 #                 pred = m2(output)
     61 #                 print(pred, label)
---> 62                 loss_term_a = loss(pred, label.float())
     63 #                 print('loss_term_a', loss_term_a)
     64                 loss_term_b = self._proximal_term(self.model, global_model)

File /home/mengdu/standalone_fate_install_1.10.0_release/env/python/venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File /home/mengdu/standalone_fate_install_1.10.0_release/env/python/venv/lib/python3.8/site-packages/torch/nn/modules/loss.py:619, in BCELoss.forward(self, input, target)
    618 def forward(self, input: Tensor, target: Tensor) -> Tensor:
--> 619     return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)

File /home/mengdu/standalone_fate_install_1.10.0_release/env/python/venv/lib/python3.8/site-packages/torch/nn/functional.py:3095, in binary_cross_entropy(input, target, weight, size_average, reduce, reduction)
   3092     new_size = _infer_size(target.size(), weight.size())
   3093     weight = weight.expand(new_size)
-> 3095 return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)

RuntimeError: all elements of input should be between 0 and 1

**Comment by talkingwallace** [comment]
hi！这块的样例代码实现上存在些问题，非常感谢你的反馈
将代码的proximal_term计算改为:

class ToyFedProxTrainer(TrainerBase):

    def __init__(self, epochs, batch_size, u):
        super(ToyFedProxTrainer, self).__init__()
        # trainer parameters
        self.epochs = epochs
        self.batch_size = batch_size
        self.u = u

    # Given two model, we compute the proximal term
    def _proximal_term(self, model_a, model_b):
        diff_ = 0
        for p1, p2 in zip(model_a.parameters(), model_b.parameters()):
            diff_ += ((p1-p2.detach())**2).sum()
        return diff_

即可正常运行，我们后续会修复这个文档
