### ISSUE TITLE
Toy test fails on docker standalone on Mac M1 processor 

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4584]
Hello, 
I have installed standalone FATE v1.9.0 on Mac M1 Max, and toy test fails:

(venv) sh-4.2# flow test toy -gid 10000 -hid 10000
toy test job 202301102217212005450 is waiting
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is running
toy test job 202301102217212005450 is failed
auto check log failed, please check /data/projects/fate/logs/toy/job_202301102217212005450_log

Does standalone version support Apple Silicon chips?

**Comment by talkingwallace** [comment]
Hi, can you show us the error log in /data/projects/fate/logs/toy/job_202301102217212005450_log? Thanks

**Comment by jeremypxh** [comment]
same problem on m2 docker

**Comment by jeremypxh** [comment]
> Hi, can you show us the error log in /data/projects/fate/logs/toy/job_202301102217212005450_log? Thanks
Mine log is like this.

(venv) sh-4.2# cat fate_flow_detect.log
[INFO] [2023-01-11 05:17:08,465] [202301110517037007550] [67:275121669888] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 05:17:08,474] [202301110517037007550] [67:275121669888] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 05:17:13,532] [202301110517037007550] [67:275121669888] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 05:17:13,542] [202301110517037007550] [67:275121669888] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 05:17:23,872] [202301110517037007550] [67:275121669888] - [detector.detect_running_task] [line:71]: task 202301110517037007550_secure_add_example_0 0 on guest 10000 with running process 746 does not exist
[INFO] [2023-01-11 05:17:26,908] [202301110517037007550] [67:275121669888] - [detector.detect_running_task] [line:77]: task 202301110517037007550_secure_add_example_0 0 on guest 10000 party status has been checked twice, try to stop job
[INFO] [2023-01-11 05:17:26,910] [202301110517037007550] [67:275121669888] - [detector.detect_running_task] [line:71]: task 202301110517037007550_secure_add_example_0 0 on host 10000 with running process 756 does not exist
[INFO] [2023-01-11 05:17:29,942] [202301110517037007550] [67:275121669888] - [detector.detect_running_task] [line:77]: task 202301110517037007550_secure_add_example_0 0 on host 10000 party status has been checked twice, try to stop job
[INFO] [2023-01-11 05:17:29,961] [202301110517037007550] [67:275121669888] - [detector.request_stop_jobs] [line:223]: detector request start to stop job 202301110517037007550, because of task executor process abort

**Comment by amyseoj1** [comment]
Hello, I have the same error log as @jeremypxh

(venv) sh-4.2# cat fate_flow_detect.log
[INFO] [2023-01-11 12:24:23,397] [202301111224157081750] [67:275188795136] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 12:24:23,422] [202301111224157081750] [67:275188795136] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 12:24:28,593] [202301111224157081750] [67:275188795136] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 12:24:28,612] [202301111224157081750] [67:275188795136] - [detector.detect_cluster_instance_status] [line:231]: start detect running task instance status
[INFO] [2023-01-11 12:24:38,944] [202301111224157081750] [67:275188795136] - [detector.detect_running_task] [line:71]: task 202301111224157081750_secure_add_example_0 0 on guest 10000 with running process 766 does not exist
[INFO] [2023-01-11 12:24:41,962] [202301111224157081750] [67:275188795136] - [detector.detect_running_task] [line:77]: task 202301111224157081750_secure_add_example_0 0 on guest 10000 party status has been checked twice, try to stop job
[INFO] [2023-01-11 12:24:41,964] [202301111224157081750] [67:275188795136] - [detector.detect_running_task] [line:71]: task 202301111224157081750_secure_add_example_0 0 on host 10000 with running process 777 does not exist
[INFO] [2023-01-11 12:24:44,990] [202301111224157081750] [67:275188795136] - [detector.detect_running_task] [line:77]: task 202301111224157081750_secure_add_example_0 0 on host 10000 party status has been checked twice, try to stop job
[INFO] [2023-01-11 12:24:45,007] [202301111224157081750] [67:275188795136] - [detector.request_stop_jobs] [line:223]: detector request start to stop job 202301111224157081750, because of task executor process abort

**Comment by zhihuiwan** [comment]
Can you show us the log in: 
/data/projects/fate/fateflow/logs/$job_id/guest/$party_id/secure_add_example_0/ERROR.log、
/data/projects/fate/fateflow/logs/$job_id/host/$party_id/secure_add_example_/ERROR.log？
 Thanks

**Comment by jeremypxh** [comment]
>thanks but there are no ERROR.log files in /data/projects/fate/fateflow/logs/$job_id/host/$party_id/secure_add_example_0/
I can see other files:  DEBUG.log           PROFILING.log
fate_flow_stat.log  stat.log
INFO.log            task_executor_6253d042925111eda2d80242ac110002_std.log
which do you need? Thanks

**Comment by jeremypxh** [comment]
> Can you show us the log in: /data/projects/fate/fateflow/logs/$job_id/guest/$party_id/secure_add_example_0/ERROR.log、 /data/projects/fate/fateflow/logs/$job_id/host/$party_id/secure_add_example_0/ERROR.log？ Thanks 
here are what i found in fateboard log

198
[INFO] [2023-01-12 08:16:26,478] [202301120816129896710] [1169:274922721280] - [secure_add_host.run] [line:87]: begin to make host data
199
[INFO] [2023-01-12 08:16:27,093] [202301120816129896710] [1169:274922721280] - [secure_add_host.run] [line:90]: split data into two random parts
200
[INFO] [2023-01-12 08:16:29,782] [202301120816129896710] [1169:274922721280] - [secure_add_host.run] [line:93]: get share of one random part data from guest
201
[INFO] [2023-01-12 08:16:31,721] [202301120816129896710] [1169:274922721280] - [secure_add_host.run] [line:96]: share one random part data to guest
202
[INFO] [2023-01-12 08:16:33,468] [202301120816129896710] [1169:274922721280] - [secure_add_host.run] [line:99]: begin to get sum of host and guest
203
[INFO] [2023-01-12 08:16:36,415] [202301120816129896710] [1169:274922721280] - [secure_add_host.run] [line:102]: send host sum to guest
204
[INFO] [2023-01-12 08:16:36,705] [202301120816129896710] [1169:274922721280] - [_session.wait_remote_all_done] [line:494]: remote futures: set(), waiting...
205
[INFO] [2023-01-12 08:16:36,706] [202301120816129896710] [1169:274922721280] - [_session.wait_remote_all_done] [line:496]: remote futures: set(), all done
206
[INFO] [2023-01-12 08:16:36,707] [202301120816129896710] [1169:274922721280] - [task_executor._run_] [line:212]: task output dsl {}
207
[INFO] [2023-01-12 08:16:36,707] [202301120816129896710] [1169:274922721280] - [task_executor._run_] [line:213]: task output data [None]
208
[INFO] [2023-01-12 08:16:36,725] [202301120816129896710] [1169:274922721280] - [task_base_worker.report_task_info_to_driver] [line:113]: report TaskExecutor 202301120816129896710_secure_add_example_0 0 host 10000 to driver:
209
{'job_id': '202301120816129896710', 'component_name': 'secure_add_example_0', 'task_id': '202301120816129896710_secure_add_example_0', 'task_version': '0', 'role': 'host', 'party_id': '10000', 'run_ip': 'xxx.xxx.xxx.xxx', 'run_pid': 1169, 'run_port': '9380', 'party_status': 'success', 'end_time': 1673511396725, 'elapsed': 12926}
210
[INFO] [2023-01-12 08:16:36,726] [202301120816129896710] [1169:274922721280] - [control_client.report_task] [line:39]: request update job 202301120816129896710 task 202301120816129896710_secure_add_example_0 0 on host 10000
211
[INFO] [2023-01-12 08:16:36,832] [202301120816129896710] [1169:274922721280] - [task_executor._run_] [line:282]: finish secure_add_example_0 202301120816129896710_secure_add_example_0 0 on host 10000 with success
212
[INFO] [2023-01-12 08:16:38,652] [202301120816129896710] [1169:274922721280] - [base_worker.run] [line:125]: worker TaskExecutor, process role: ProcessRole.WORKER, pid: 1169, elapsed: 16498 ms

**Comment by jeremypxh** [comment]
> Can you show us the log in: /data/projects/fate/fateflow/logs/$job_id/guest/$party_id/secure_add_example_0/ERROR.log、 /data/projects/fate/fateflow/logs/$job_id/host/$party_id/secure_add_example_0/ERROR.log？ Thanks
here are fateboard logs
![image](https://user-images.githubusercontent.com/56855498/212025744-31b13784-0562-4598-8cc5-030323473204.png)

**Comment by jeremypxh** [comment]
> Can you show us the log in: /data/projects/fate/fateflow/logs/$job_id/guest/$party_id/secure_add_example_0/ERROR.log、 /data/projects/fate/fateflow/logs/$job_id/host/$party_id/secure_add_example_0/ERROR.log？ Thanks
[fateboard_log.txt](https://github.com/FederatedAI/FATE/files/10399987/fateboard_log.txt)

here are fateboard logs

**Comment by zhihuiwan** [comment]
> > thanks but there are no ERROR.log files in /data/projects/fate/fateflow/logs/$job_id/host/$party_id/secure_add_example_0/
> > I can see other files:  DEBUG.log           PROFILING.log
> > fate_flow_stat.log  stat.log
> > INFO.log            task_executor_6253d042925111eda2d80242ac110002_std.log
> > which do you need? Thanks

task_executor_6253d042925111eda2d80242ac110002_std.log

**Comment by jeremypxh** [comment]
> > > thanks but there are no ERROR.log files in /data/projects/fate/fateflow/logs/$job_id/host/$party_id/secure_add_example_0/
> > > I can see other files:  DEBUG.log           PROFILING.log
> > > fate_flow_stat.log  stat.log
> > > INFO.log            task_executor_6253d042925111eda2d80242ac110002_std.log
> > > which do you need? Thanks
> 
> task_executor_6253d042925111eda2d80242ac110002_std.log

Thx but nothing in the log

**Comment by amyseoj1** [comment]
I think the image does not support linux/arm64 platform. I get this warning message:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by SquirminatorHotHead** [comment]
@zhihuiwan  We  have tested this on M1 MacBook Pro with 16GB RAM and M1 MacBook Air with 8GB only, FATE toy test runs successfully on the machine with 16GB RAM with docker deployment. So it seems like just a minimum hardware requirement issue. Please check it and close this issue if it is confirmed. 
我们测试了16GB内存与8GB内存的搭载M1芯片的苹果笔记本， toy test在16GB的机器上可以跑通。测试配置为使用docker的单机部署。
