### ISSUE TITLE
JSON encoder bug: Object of type DataFrame is not JSON serializable

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4585]
**Describe the bug**

FATE version: 1.10.0 
When running [FATE](https://github.com/FederatedAI/FATE)/[doc](https://github.com/FederatedAI/FATE/tree/master/doc)/[tutorial](https://github.com/FederatedAI/FATE/tree/master/doc/tutorial)/[pipeline](https://github.com/FederatedAI/FATE/tree/master/doc/tutorial/pipeline)/pipeline_tutorial_match_id.ipynb, 
TypeError: Object of type DataFrame is not JSON serializable is raised.

**To Reproduce**
1. on FATE 1.10.0, run pipeline_tutorial_match_id tutorial.

**Expected behavior**

print component output data.

**Screenshots**

<img width="1069" alt="Screen Shot 2023-01-11 at 12 16 26 PM" src="https://user-images.githubusercontent.com/73941975/211804704-6d222b7a-c6bd-4a85-b558-f6b1f7cd3f2b.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 
 - Version:  version 12.5.1
 - Processor: Intel Core i5

**Comment by amyseoj1** [comment]
> Hello, saw your last issue. did u successfully run toy test? how did u fix the problem

Hello @jeremypxh, 

Sadly, No. FATE does not work on my M1 so I am running on my old iMac computer from 2015.  There are some bugs, but I was able run some models.

**Comment by mgqa34** [comment]
> [doc](https://github.com/FederatedAI/FATE/tree/master/doc)/[tutorial](https://github.com/FederatedAI/FATE/tree/master/doc/tutorial)/[pipeline](https://github.com/FederatedAI/FATE/tree/master/doc/tutorial/pipeline)/pipeline_tutorial_match_id.ipynb

Yes, you're right, the tutorial is written in Fate v1.7.0，get_output_data api's return value is a dict object, but in later version, the api is updated and return value is DataFrame. This doc is old, it will be fixed soon. 
Replace "print(json.dumps(pipeline.get_component("data_transform_0").get_output_data(limits=3), indent=4))" 
to "print(pipeline.get_component("data_transform_0").get_output_data(limits=3))" please.
