### ISSUE TITLE
Understanding feature scale feat_upper parameter

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4589]
Hello, 

I am currently working on examples/pipeline/feature_scale/pipeline-feature-scale-normal.py and I have trouble understanding the usage of feat_upper parameter in feature_scale component. The manual says "when feat_upper is set to a list, mode must be "normal", and list length should equal to the number of features to scale". 

breast_hetero_guest has **10 f**eature variables (x0 through x9) 
breast_hetero_host has **20** feature variables (x0 through x19)

In the example code, the feat_upper parameter is set to a list of 10 values. However, when I run this code, the host side data of 20 feature values were also scaled? I am not sure how feature_scale is automatically applied to the host data. Please correct me if I am wrong. 
________________________________________________________________________________________________________
feature_scale_0 = FeatureScale(name="feature_scale_0", method="min_max_scale", mode="normal") # 'cap' or 'normal'
feature_scale_0.get_party_instance(
    role='guest', party_id=guest).component_param(
    feat_upper=[
        **1, 2, 1, 1, 0.5, 1, 2, 2, 1, 1]**)

**Comment by mgqa34** [comment]
In your configuration, feat_upper is role parameter in guest side, feat_upper parameter works on "breast_hetero_guest" only
