### ISSUE TITLE
conf与dsl文件参数问题

### ISSUE THREAD

**Issue by KAgBMan** [FederatedAI/FATE#4591]
您好，有没有相关文档介绍example中预设的各类联邦学习算法及其他组件所需的conf和dsl文件中的参数，
包括各参数的含义、可选项、参数范围等等，如果有，能否提供一下链接地址？谢谢！

**Comment by mgqa34** [comment]
看下这个文档是否有帮助：https://fate.readthedocs.io/en/latest/federatedml_component/
