### ISSUE TITLE
mac M2部署docker版standalone toy test 失败

### ISSUE THREAD

**Issue by jeremypxh** [FederatedAI/FATE#4593]
尝试了 docker run -it --platform linux/amd64 这种方法，但还是不管用。 
把log文件附上。
链接: https://pan.baidu.com/s/1TwNT2jDEq1M7i1SYYbpGfg?pwd=rx5m 提取码: rx5m
感谢🙏

**Comment by dylan-fan** [comment]
mac M2 is not tested
