### ISSUE TITLE
FATE和KubeFate的fateboard无法查看job详情

### ISSUE THREAD

**Issue by desertfoxfj** [FederatedAI/FATE#4596]
分别部署了FATE和KubeFate的两种集群都有相同问题，在fateboard页面点击jobid想查看任务详情，但是都会一闪而过然后新增一个空白fateboard也，之前的fateboard页也边空白。两种集群都可正常使用，但是fateboard查看job详情都有相同问题。
ubuntu18.04
cpu 8核
内存16G

**Comment by dylan-fan** [comment]
哪个版本？

**Comment by desertfoxfj** [comment]
实在抱歉忘记写版本号了，就是最新版1.10
