### ISSUE TITLE
service not running

### ISSUE THREAD

**Issue by nianer** [FederatedAI/FATE#4601]
Hello, i am a complete novice at FATE.
When i executed `bash bin/service.sh start` for deploying standalone version of FATE, it threw an error information.
 ```
cPROJECT_BASE: /home/ubuntu/FATE
PYTHONPATH: /home/ubuntu/FATE/python:/home/ubuntu/FATE/fateflow/python
found service conf: /home/ubuntu/FATE/conf/service_conf.yaml
fate flow http port: 9380, grpc port: 9360

check process by http port and grpc port
service not running

```
Is there any way to fix it?

**Comment by talkingwallace** [comment]
Hi!, it will return you the paths to error logs. Could you please show us the log contents? Thanks

**Comment by nianer** [comment]
I viewed `error.log` in `fateflow/logs`, but nothing in it.

**Comment by mgqa34** [comment]
python fateflow/python/fate_flow_server.py directly，you will see the detail erros
