### ISSUE TITLE
data_transform missing_fill fails 

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4610]
**Describe the bug**

data_transform component no longer works with missing_fill defined.

data_transform_0.get_party_instance(
    role='guest',
    party_id=9999).component_param(
    with_label=True,
    **missing_fill=True,   
    outlier_replace=True)**  

**To Reproduce**

In standalone FATE 1.10.0, run  [pipeline-data-transform-missing-fill.py ](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/data_transform/pipeline-data-transform-missing-fill.py)

**Expected behavior**

This component used to work fine, but no longer works. 

**Screenshots**
<img width="1106" alt="Screen Shot 2023-02-03 at 6 03 25 PM" src="https://user-images.githubusercontent.com/73941975/216675165-0d88e46a-4413-4d4e-8909-cb8ebaa28a57.png">

**Desktop (please complete the following information):**
 - OS: mac OS Monterey 
 - Browser: safari
 - Version 12.5.1

**Comment by mgqa34** [comment]
We can't reproduce this error, is it convenient for you to give some data to reproduce this error with that pipeline?

**Comment by amyseoj1** [comment]
from pipeline.backend.pipeline import PipeLine
from pipeline.component import DataTransform
from pipeline.component import Reader
from pipeline.interface import Data


# Before start a modeling task, data to be used should be uploaded.
guest_train_data = {"name": "ionosphere_scale_hetero_guest", "namespace": f"experiment"}
host_train_data = {"name": "ionosphere_scale_hetero_host", "namespace": f"experiment"}

# Make a pipeline instance:
pipeline = PipeLine().set_initiator(role='guest', party_id=9999).set_roles(guest=9999, host=10000)

# Define a Reader to load data
reader_0 = Reader(name="reader_0")
reader_0.get_party_instance(role='guest', party_id=9999).component_param(table=guest_train_data)
reader_0.get_party_instance(role='host', party_id=10000).component_param(table=host_train_data)

# Add a DataTransform component to parse raw data into Data Instance
data_transform_0 = DataTransform(name="data_transform_0")
data_transform_0.get_party_instance(role='guest', party_id=9999).component_param(with_label=True,
                                                                                  label_name="LABEL",
                                                                                  missing_fill=True,
                                                                                  missing_fill_method="mean", 
                                                                                  outlier_replace=True)
data_transform_0.get_party_instance(role='host', party_id=10000).component_param(with_label=False,
                                                                                missing_fill=True,
                                                                                missing_fill_method="designated", 
                                                                                default_value=0,
                                                                                outlier_replace=False)

pipeline.add_component(reader_0)
pipeline.add_component(data_transform_0, data=Data(data=reader_0.output.data))

pipeline.compile()

pipeline.fit()

**Comment by mgqa34** [comment]
> from pipeline.backend.pipeline import PipeLine from pipeline.component import DataTransform from pipeline.component import Reader from pipeline.interface import Data
> 
> guest_train_data = {"name": "ionosphere_scale_hetero_guest", "namespace": f"experiment"} host_train_data = {"name": "ionosphere_scale_hetero_host", "namespace": f"experiment"}
> 
> pipeline = PipeLine().set_initiator(role='guest', party_id=9999).set_roles(guest=9999, host=10000)
> 
> reader_0 = Reader(name="reader_0") reader_0.get_party_instance(role='guest', party_id=9999).component_param(table=guest_train_data) reader_0.get_party_instance(role='host', party_id=10000).component_param(table=host_train_data)
> 
> data_transform_0 = DataTransform(name="data_transform_0") data_transform_0.get_party_instance(role='guest', party_id=9999).component_param(with_label=True, label_name="LABEL", missing_fill=True, missing_fill_method="mean", outlier_replace=True) data_transform_0.get_party_instance(role='host', party_id=10000).component_param(with_label=False, missing_fill=True, missing_fill_method="designated", default_value=0, outlier_replace=False)
> 
> pipeline.add_component(reader_0) pipeline.add_component(data_transform_0, data=Data(data=reader_0.output.data))
> 
> pipeline.compile()
> 
> pipeline.fit()

I deploy a standalone env by this [guide](https://github.com/FederatedAI/FATE/tree/master/deploy/standalone-deploy#32-get-the-installation-package) and test again with the code you had pasted, it also runs successfully in my enviroment

**Comment by amyseoj1** [comment]
I pulled the docker image again, and the error is now gone.
