### ISSUE TITLE
How to use Feature Sample to address class imbalance ? 

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4611]
Hello, 

I have question about using FederatedSample correctly to treat class imbalance in data. 
If there are plenty of class 0 but very few of class 1, and I want to upsample class 1 to have equal number of class 0 and class 1 in the data.  For example, if there are 500 class 0s and 10 class 1s in the data, I want to upsample class 1 to 500 so that I have 500 class 0s and 500 class 1s. 

Could anyone give me an example code to do this ?

**Comment by mgqa34** [comment]
This [examples](https://github.com/FederatedAI/FATE/blob/master/examples/dsl/v2/multi_model_pipeline/test_multi_pipeline_conf.json#L20) may help

**Comment by amyseoj1** [comment]
Hello,
Thank you for your reply. I have used the fractions parameter to to manually set the ratio, but is there a way to recompute the class 0:class 1 ratio after performing hetero intersection ? Can FATE automatically resample according to the class ratio after intersection ?
