### ISSUE TITLE
fate框架下神经网络多输出

### ISSUE THREAD

**Issue by daxin007** [FederatedAI/FATE#4615]
开发者您好，想麻烦问一下fate框架可以支持神经网络的多维输出吗（我们的任务输出y有多个维度，看目前github给的示例输出都只有一个维度）？如果支持的话能不能再提供下使用示例？

**Comment by talkingwallace** [comment]
y有多个维度？我理解就是label有多个维度是吗

**Comment by daxin007** [comment]
对，就是label有多个维度。比如时间序列预测，要预测未来6小时的输出，那label的维度就是6。请问fate框架支持神经网络的这种输出吗？

**Comment by talkingwallace** [comment]
Hi， 是可以的
你可以参考这个系列教程，编写自己的Dataset & Trainer就可以满足你都需要
https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/nn_tutorial/README.md
 不过FATE目前的机制只支持分类、回归数据的evaluation和展示，所以目前这种格式的数据暂时没办法展示在fateboard上，但是训练肯定是OK的
