### ISSUE TITLE
样本求交PSI，不同求交结果ID生成机制是什么

### ISSUE THREAD

**Issue by tujianxin** [FederatedAI/FATE#4616]
我现在做psi的时候，分别选择了dh,rsa,raw，only_output_key都为true,sync_intersect_id也为true,join_method为inner join,sample_id_generator都是guest，求交出来的id形式不一样，dh求交结果为都是1，rsa求交之后是哈希字符串，raw都是"intersect_id"，谁可以帮忙解释这些方法id最终生成机制是什么？或者有相关的说明文档发给我也可以，谢谢回复

**Comment by mgqa34** [comment]
用的哪个版本呢？新的版本里面RSA求交之后哈希字符串问题应该是修复了。 另外的话，value只是占位符，看第0列才是ID
