### ISSUE TITLE
fateflow的http上传模型接口报错/v1/model/import

### ISSUE THREAD

**Issue by desertfoxfj** [FederatedAI/FATE#4617]
fateflow的http上传模型接口报错
http://192.168.xxx.xxx:9380/v1/model/import
请求参数
{
  "role": "guest",
  "party_id": 9999,
  "model_id": "arbiter-10000#guest-9999#host-10000#model",
  "model_version": "202302061002408064360",
  "file": "d:\\guest#9999#arbiter-10000#guest-9999#host-10000#model_202302061002408064360.zip",
  "force_update": false
}
报错信息：
{
    "retmsg": "`file` is required.",
    "retcode": 400
}

**Comment by amenkim** [comment]
这个接口地址应该只支持文件流的形式上传模型

**Comment by desertfoxfj** [comment]
我是通过postman测试的，不太明白怎么上传，能否说详细一点

**Comment by amenkim** [comment]
postman的话，body那里选form-data，然后把Text改成File，就可以选择文件附带到请求里了

**Comment by desertfoxfj** [comment]
这样设置后，返回报错
{
    "retcode": 101,
    "retmsg": "required argument are missing: model_id,model_version,role,party_id; "
}
