### ISSUE TITLE
最小化测试脚本"min_test_task"目录在1.10版本中被删除了

### ISSUE THREAD

**Issue by hyxxsfwy** [FederatedAI/FATE#4618]
**Describe the bug**
按照文档 [Example 使用指南](https://github.com/FederatedAI/FATE/blob/master/examples/README.zh.md#min-test) 的描述，Fate 应该提供了一个最小化测试脚本 min_test_task。

**To Reproduce**
1. Go to [min-test](https://github.com/FederatedAI/FATE/blob/master/examples/README.zh.md#min-test)
2. Click on '请参考 [min_test_task](https://github.com/FederatedAI/FATE/blob/master/examples/min_test_task/README.rst)'
3. See 404 error

**Expected behavior**
恢复 [min_test_task](https://github.com/FederatedAI/FATE/blob/master/examples/min_test_task/README.rst) 目录，或者修改 [Example 使用指南](https://github.com/FederatedAI/FATE/blob/master/examples/README.zh.md#min-test) 文档，在修改的 commit 里描述一下删除 min_test_task 的原因。

**Additional context**
希望能在回复里描述一下删除 min_test_task 的原因。

**Comment by mgqa34** [comment]
1.10以后，min-test已经集成到flow cli，具体可以参考[用例](https://github.com/FederatedAI/FATE/blob/master/deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.zh.md#622-%E5%BF%AB%E9%80%9F%E6%A8%A1%E5%BC%8F)，文档问题后续会修复，谢谢指出
