### ISSUE TITLE
homo_secureboost算法再增加tree的数目时会发生错误

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4621]
使用homo_secureboost算法进行横向联邦学习，一开始设置参数num_trees=3时，任务成功运行无报错，当将num_trees修改为num_trees=70时，发生以下错误
![d24a4cb3b6d1e6fc67f48ddf2f354ab](https://user-images.githubusercontent.com/49178688/218429430-4b280749-cfc4-45d1-ae1c-41fb7f8da90b.png)
请问是什么原因呢

**Comment by oceanqdu** [comment]
上述问题是在ubuntu20下出现的，在centos7上将num_trees修改为num_trees=70时不会出现上述问题。

**Comment by talkingwallace** [comment]
这看着是底层计算引擎eggroll挂了，请问这个问题稳定复现吗
