### ISSUE TITLE
fate-manager部署问题

### ISSUE THREAD

**Issue by LemonGitMin** [FederatedAI/FATE#4622]
https://github.com/FederatedAI/FATE-Cloud/blob/master/fate-manager/deploy/FATE-Manager_Install_Guide.md
下载 fate_manager_1.4.1_release-1.0.0.tar.gz 包报错404
wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate-cloud/1.4.1/fate_manager_1.4.1_release-1.0.0.tar.gz
83d134f3c6f7ad7ac84dba5fcb5dee5
找不到 配置文件 fate_manager-install/common-deploy/conf/setup.conf

**Comment by zhihuiwan** [comment]
已经修复了，您可以再试试
