### ISSUE TITLE
有关homo-convert生成的其他 ML 框架的模型文件问题

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/FATE#4625]
在使用homo_secureboost算法进行横向联邦时，通过使用homo-convert得到了一个.zip文件。在其中发现了convert model文件夹，拿到其中的lgb.txt文件。
在明文环境下加载该lgb.txt模型，并使用训练数据进行预测，结果与在fate中得到的预测结果大不相同，请问这是什么问题呢？是我的使用方式不太对吗 以下是我的使用方式
![image](https://user-images.githubusercontent.com/49178688/218920420-43d2fb4a-8906-49d7-949d-6be1f9759845.png)

**Comment by talkingwallace** [comment]
hi，lgb的模型转换在多个版本都进行测试的，应该是不会有严重错误的，可以检查下特征的顺序等设置，看看预测结果是否OK

**Comment by oceanqdu** [comment]
> hi，lgb的模型转换在多个版本都进行测试的，应该是不会有严重错误的，可以检查下特征的顺序等设置，看看预测结果是否OK

我是用的训练的数据集来做的预测，在明文状态下得到的预测结果如下：
![1676440606909_F71FCDAE-D3AA-43ef-8309-EF924D041EEA](https://user-images.githubusercontent.com/49178688/218945846-c4c66730-ec30-45c2-8586-59ccf4b8150f.png)
在fate中预测的结果如下：
![image](https://user-images.githubusercontent.com/49178688/218946062-4b880c88-32b1-4285-8c02-be1354981561.png)
是否是因为在fate中使用预测的时候还经过了 read模块，transfom模块和scale模块的预处理，而明文状态下没有以上处理？
![image](https://user-images.githubusercontent.com/49178688/218946293-53a1da0a-0464-4e37-9fad-fd2011e8667f.png)

**Comment by oceanqdu** [comment]
我用breast数据集重新训练并使用homo-convert转换了一个新的横向secureboost模型，并采用训练数据集作为输入进行预测，预测得到的结果和用fate进行预测得到的结果是一致的，所以是因为数据集的问题吗？

**Comment by talkingwallace** [comment]
hi 你这里使用了data scale_0, 原数据应该是被改变了，所以也许用scale_0组件输出的数据预测一下结果就对上了

**Comment by oceanqdu** [comment]
还有个问题：在使用fate进行预测时可以通过 `flow job submit -c ./examples/dsl/v2/hetero_secureboost/test_predict_conf.json` 来提交预测任务，当任务完成时，通过使用 `flow tracking output-data [options]` 命令来下载预测结果。
在我的代码中我希望能够在预测任务完成时立即开始下载预测结果下载。 我应该用什么命令来实时判断预测任务是否完成？

**Comment by talkingwallace** [comment]
如果有这样的需求可以直接用pipeline吧？

**Comment by oceanqdu** [comment]
> 如果有这样的需求可以直接用pipeline吧？

之前有想过用pipeline，但是您们的回复是pipline中现在没有考虑横向联邦做预测的情况 #4330

**Comment by mgqa34** [comment]
> 还有个问题：在使用fate进行预测时可以通过 `flow job submit -c ./examples/dsl/v2/hetero_secureboost/test_predict_conf.json` 来提交预测任务，当任务完成时，通过使用 `flow tracking output-data [options]` 命令来下载预测结果。 在我的代码中我希望能够在预测任务完成时立即开始下载预测结果下载。 我应该用什么命令来实时判断预测任务是否完成？
=> 可以用flow job query -j这个接口

**Comment by mgqa34** [comment]
> 还有个问题：在使用fate进行预测时可以通过 `flow job submit -c ./examples/dsl/v2/hetero_secureboost/test_predict_conf.json` 来提交预测任务，当任务完成时，通过使用 `flow tracking output-data [options]` 命令来下载预测结果。 在我的代码中我希望能够在预测任务完成时立即开始下载预测结果下载。 我应该用什么命令来实时判断预测任务是否完成？

用什么命令来实时判断预测任务是否完成=>flow job query -j
