### ISSUE TITLE
FATE1.10 模型保存的问题

### ISSUE THREAD

**Issue by Ethan-ChiChi** [FederatedAI/FATE#4627]
FATE1.10的docker镜像，使用flow model export -c examples/model/store_model.json --to-database将模型保存指定数据库中。
运行后实际是到数据库fate_flow中建了张表保存，而不是保存在配置文件service_conf.yaml中指定的数据库中。

**Comment by zhihuiwan** [comment]
感谢您的指正，我们已经提交了修复的pr, 可参考pr修改下对应的代码：https://github.com/FederatedAI/FATE-Flow/pull/410
