### ISSUE TITLE
联邦homo-nn效果不如单独client集中式训练

### ISSUE THREAD

**Issue by NicerOuZa** [FederatedAI/FATE#4628]
**Describe the bug**
fate v1.10 的docker版本上运行homo-nn推荐算法deepfm在criteo数据集上，和torch-rechub库带的deepfm训练比较，相同数据集分为guest：host：val=4：4：2，homo-nn训练40轮验证集auc为0.68，集中式训练guest部分数据，验证集auc为0.766，集中式训练guest+host数据，验证集结果为0.756，均比联邦训练高8%左右。

**Comment by talkingwallace** [comment]
经过对齐验证，目前DeepFM在Criteo 10W采样数据上 FedAVG和本地集中训练效果相近，验证机auc均为0.74左右，效果是OK的
