### ISSUE TITLE
fate平台能进行图像分割工作吗？如果有的话有示例代码吗？

### ISSUE THREAD

**Issue by 1170300814** [FederatedAI/FATE#4635]
如题

**Comment by talkingwallace** [comment]
fate的话本身是没有附带这类算法的，不过可以用nn自定义实现一个，比方说用yolov3的pytorch代码实现一个trainer

**Comment by Dopaine999** [comment]
> fate的话本身是没有附带这类算法的，不过可以用nn自定义实现一个，比方说用yolov3的pytorch代码实现一个trainer

您好，用fate1.10做图像特征提取，有相关的开发示例吗？

**Comment by dylan-fan** [comment]
建议用FATE 2.x 开发，会比较方便
