### ISSUE TITLE
运行pipeline demo报错

### ISSUE THREAD

**Issue by SnakeTom** [FederatedAI/FATE#4636]
![image](https://user-images.githubusercontent.com/18352813/220515561-0c1b3001-517b-4224-9138-21f11c76ce4e.png)

如图，已安装fate_client

执行examples/pipeline/demo下的pipeline-mini-demo.py 报错。
看之前有相关issue,但是也没有答案。

**Comment by mgqa34** [comment]
安装的是哪个版本？ pip list | grep fate-client 可以看到

**Comment by SnakeTom** [comment]
> pip list | grep fate-client
# pip list | grep fate-client
fate-client        1.8.0

是版本的问题？

**Comment by yyf1986** [comment]
有没有可能你的fate-client安装的python不对应？

**Comment by SnakeTom** [comment]
> 有没有可能你的fate-client安装的python不对应？

这个要怎么对应，有相关的版本对应文档不？

**Comment by mgqa34** [comment]
> > 有没有可能你的fate-client安装的python不对应？
> 
> 这个要怎么对应，有相关的版本对应文档不？

要确认下pipeline和python是否同一个，命令行分别输入which pipeline 和 which python看是否在同一个层级的bin下面

**Comment by SnakeTom** [comment]
> which python

![image](https://user-images.githubusercontent.com/18352813/220557083-924a71ac-ebce-4944-af65-a06d6ac28ce9.png)

确实不一致，是我安装方式不对嘛

**Comment by mgqa34** [comment]
应该是pip和python不是同一个环境，导致安装在不同的python下去了，可能有两种解决方案，用/usr/local/bin/python启动，或者python -m pip install fate-client==1.8.0

**Comment by SnakeTom** [comment]
> python -m

我的/usr/local/bin  没有python

![image](https://user-images.githubusercontent.com/18352813/220562981-a0bfced2-f913-4332-b067-8db0c228cee9.png)

python -m pip install fate-client==1.8.0

Looking in indexes: http://xxx/simple
Collecting fate-client==1.8.0
  Could not find a version that satisfies the requirement fate-client==1.8.0 (from versions: )
No matching distribution found for fate-client==1.8.0

换了一个其他源
python -m pip install --upgrade fate-client -i  http://xxxx 也不行。

有可用的更新fate-client的源么？

**Comment by mgqa34** [comment]
> > python -m
> 
> 我的/usr/local/bin 没有python
> 
> ![image](https://user-images.githubusercontent.com/18352813/220562981-a0bfced2-f913-4332-b067-8db0c228cee9.png)
> 
> python -m pip install fate-client==1.8.0
> 
> Looking in indexes: http://xxx/simple Collecting fate-client==1.8.0 Could not find a version that satisfies the requirement fate-client==1.8.0 (from versions: ) No matching distribution found for fate-client==1.8.0
> 
> 换了一个其他源 python -m pip install --upgrade fate-client -i http://xxxx 也不行。
> 
> 有可用的更新fate-client的源么？

python的版本是哪个呢？有点怀疑是python2

**Comment by SnakeTom** [comment]
> > > python -m
> > 
> > 
> > 我的/usr/local/bin 没有python
> > ![image](https://user-images.githubusercontent.com/18352813/220562981-a0bfced2-f913-4332-b067-8db0c228cee9.png)
> > python -m pip install fate-client==1.8.0
> > Looking in indexes: http://xxx/simple Collecting fate-client==1.8.0 Could not find a version that satisfies the requirement fate-client==1.8.0 (from versions: ) No matching distribution found for fate-client==1.8.0
> > 换了一个其他源 python -m pip install --upgrade fate-client -i http://xxxx 也不行。
> > 有可用的更新fate-client的源么？
> 
> python的版本是哪个呢？有点怀疑是python2

确实是python2的问题，我换成python3可以执行了，但是报错fate flow service连接不上，我部署的standalone_fate 模式

# pipeline init --ip 127.0.0.1 --port 9380
Pipeline configuration succeeded.

# python3 pipeline-mini-demo.py
....
....
raise ValueError("job submit failed, err msg: {}".format(result))
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

是demo里面默认的端口需要修改吗？

**Comment by mgqa34** [comment]
需要确认fate flow服务是起来的，ps aux | grep fate_flow_server.py，如果已部署，需要看下fate部署目录下的conf/service_conf.yaml flow服务使用的ip:端口是127.0.0.1:9380

**Comment by SnakeTom** [comment]
> 需要确认fate flow服务是起来的，ps aux | grep fate_flow_server.py，如果已部署，需要看下fate部署目录下的conf/service_conf.yaml flow服务使用的ip:端口是127.0.0.1:9380

#ps aux | grep fate_flow_server.py
root     13825  0.9  0.5 852420 88352 pts/0    Sl+  14:25   1:41 python /data/projects/fate/fateflow/python/fate_flow/fate_flow_server.py

conf/service_conf.yaml配置的端口是127.0.0.1:9380 这个，我用127.0.0.1和改成下面图里的本机ip都不行。
![image](https://user-images.githubusercontent.com/18352813/220872981-d1e700e6-ea01-436f-8d16-49408c2160ee.png)

还是这个错误：
Traceback (most recent call last):
  File "/root/11098242/pipeline-mini-demo.py", line 122, in <module>
    main()
  File "/root/11098242/pipeline-mini-demo.py", line 85, in main
    pipeline.fit()
  File "/usr/local/lib/python3.6/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipeline/backend/pipeline.py", line 565, in fit
    self._train_job_id, detail_info = self._job_invoker.submit_job(self._train_dsl, training_conf, callback_func)
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 82, in submit_job
    raise ValueError("job submit failed, err msg: {}".format(result))
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

另外我使用的是docker部署的 安装fate-client和执行python demo.py都是在容器外面执行的。 还是说安装fate-client和执行python demo.py需要进入容器内部？

**Comment by mgqa34** [comment]
docker的使用我这边不是很熟悉，但理论上来说，容器内部的ip应该不是真实的，fate-client应该是用的是宿主机的ip，另外的话，容器的端口号可能也不是9380，要看外部是怎么做的映射

**Comment by zhihuiwan** [comment]
https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/README.zh.md#23-%E5%90%AF%E5%8A%A8
fate单机版docker部署文档默认是8080端口和主机做了映射，fate client提交任务端口号是9380，如果想要在容器外面执行fate client需要额外映射下9380端口。

容器启动命令可改为：
docker run -it --name standalone_fate -p 8080:8080 -p 9380:9380 federatedai/standalone_fate:${version}

**Comment by SnakeTom** [comment]
> https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/README.zh.md#23-%E5%90%AF%E5%8A%A8 fate单机版docker部署文档默认是8080端口和主机做了映射，fate client提交任务端口号是9380，如果想要在容器外面执行fate client需要额外映射下9380端口。
> 
> 容器启动命令可改为： docker run -it --name standalone_fate -p 8080:8080 -p 9380:9380 federatedai/standalone_fate:${version}

过程如下：
#docker run -it --name standalone_fate -p 8080:8080 federatedai/standalone_fate:1.10.0
PROJECT_BASE: /data/projects/fate
PYTHONPATH: /data/projects/fate/fate/python:/data/projects/fate/fateflow/python
found service conf: /data/projects/fate/conf/service_conf.yaml
fate flow http port: 9380, grpc port: 9360
...
service start sucessfully. pid: 31
check process by http port and grpc port
status:root        31 63.2  0.5 926408 88328 pts/0    Sl+  11:05   0:04 python /data/projects/fate/fateflow/python/fate_flow/fate_flow_server.py
python   31 root   11u  IPv4 33360938      0t0  TCP localhost:boxp (LISTEN)
python   31 root   13u  IPv4 33360938      0t0  TCP localhost:boxp (LISTEN)
python   31 root   10u  IPv4 33360935      0t0  TCP localhost:9360 (LISTEN)
JAVA_HOME=/data/projects/fate/env/jdk/jdk-8u345
service start sucessfully. pid: 534

按这种方式启动然后容器外执行
# pipeline init --ip 127.0.0.1 --port 9380
Pipeline configuration succeeded.

# python pipeline-mini-demo.py 
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 74, in submit_job
    raise ValueError(f"retcode err")
ValueError: retcode err

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipeline-mini-demo.py", line 122, in <module>
    main()
  File "pipeline-mini-demo.py", line 85, in main
    pipeline.fit()
  File "/usr/local/lib/python3.6/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipeline/backend/pipeline.py", line 565, in fit
    self._train_job_id, detail_info = self._job_invoker.submit_job(self._train_dsl, training_conf, callback_func)
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 82, in submit_job
    raise ValueError("job submit failed, err msg: {}".format(result))
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

依然提示这个错误诶。

# ps aux | grep fate_flow_server.py
root      1149  3.2  0.5 926408 89232 pts/0    Sl+  19:05   0:14 python /data/projects/fate/fateflow/python/fate_flow/fate_flow_server.py

**Comment by SnakeTom** [comment]
> https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/README.zh.md#23-%E5%90%AF%E5%8A%A8 fate单机版docker部署文档默认是8080端口和主机做了映射，fate client提交任务端口号是9380，如果想要在容器外面执行fate client需要额外映射下9380端口。
> 
> 容器启动命令可改为： docker run -it --name standalone_fate -p 8080:8080 -p 9380:9380 federatedai/standalone_fate:${version}

按这种方式启动报了另外的错误
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))", 'traceback': ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen\n    chunked=chunked,\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request\n    six.raise_from(e, None)\n', '  File "<string>", line 3, in raise_from\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse\n    response.begin()\n', '  File "/usr/lib64/python3.6/http/client.py", line 307, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n', '  File "/usr/lib64/python3.6/socket.py", line 586, in readinto\n    return self._sock.recv_into(b)\n', 'ConnectionResetError: [Errno 104] Connection reset by peer\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send\n    timeout=timeout\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 410, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise\n    raise value.with_traceback(tb)\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen\n    chunked=chunked,\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request\n    six.raise_from(e, None)\n', '  File "<string>", line 3, in raise_from\n', '  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse\n    response.begin()\n', '  File "/usr/lib64/python3.6/http/client.py", line 307, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n', '  File "/usr/lib64/python3.6/socket.py", line 586, in readinto\n    return self._sock.recv_into(b)\n', "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/site-packages/flow_sdk/client/base.py", line 81, in _request\n    response = self._http.send(prepped, stream=stream)\n', '  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send\n    raise ConnectionError(err, request=request)\n', "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n"]}

**Comment by zhihuiwan** [comment]
需要改下容器里面服务启动的ip，具体操作如下：
- 查寻对应容器id，查询命令：
```shell
docker ps -a
```
- 进入容器
```shell
docker exec -it 223f149d67d5 /bin/bash
```

- 修改下flow的ip为“0.0.0.0”:
```shell
vi /data/projects/fate/conf/service_conf.yaml
fateflow:
  host: 0.0.0.0
```
- 重启服务
```shell
source /data/projects/fate/bin/init.sh && sh /data/projects/fate/fateflow/bin/service.sh restart
```

**Comment by SnakeTom** [comment]
> 需要改下容器里面服务启动的ip，具体操作如下：
> 
> * 查寻对应容器id，查询命令：
> 
> ```shell
> docker ps -a
> ```
> 
> * 进入容器
> 
> ```shell
> docker exec -it 223f149d67d5 /bin/bash
> ```
> 
> * 修改下flow的ip为“0.0.0.0”:
> 
> ```shell
> vi /data/projects/fate/conf/service_conf.yaml
> fateflow:
>   host: 0.0.0.0
> ```
> 
> * 重启服务
> 
> ```shell
> source /data/projects/fate/bin/init_env.sh && sh /data/projects/fate/fateflow/bin/service.sh restart
> ```

非常感谢，改成host: 0.0.0.0 终于可以启动了！！！但是任务执行失败
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 138, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")
ValueError: Job is failed, please check out job 202302231316568019650 by fate board or fate_flow cli

打开任务错误日志提示表不存在：
RuntimeError: can not found table name: breast_hetero_host namespace: experiment
[ERROR] [2023-02-23 13:17:07,575] [202302231316568019650] [696:139764736976640] - [job_saver.update_task] [line:93]: role host party id 10000 task 202302231316568019650_reader_0 error report: Traceback (most recent call last):
  File "xxx/fate_flow/worker/task_executor.py", line 209, in _run_
    cpn_output = run_object.run(cpn_input)
  File "xxx/fate_flow/components/_base.py", line 156, in run
    self._run(cpn_input=cpn_input)
  File "xxx/fate_flow/components/reader.py", line 85, in _run
    ) = self.convert_check(
  File "xxx/fate_flow/components/reader.py", line 201, in convert_check
    return data_utils.convert_output(input_name, input_namespace, output_name, output_namespace, computing_engine,
  File "xxx/fate_flow/utils/data_utils.py", line 70, in convert_output
    raise RuntimeError(
RuntimeError: can not found table name: breast_hetero_host namespace: experiment

**Comment by zhihuiwan** [comment]
需要上传相应的数据：
- [pipeline上传数据](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb)
- [flow cli上传数据](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/dsl_conf/upload_data_guide.md#upload-command)

**Comment by SnakeTom** [comment]
> 需要上传相应的数据,可以通过下面两种方式：
> 
> * [pipeline上传数据](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb)
> * [flow cli上传数据](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/dsl_conf/upload_data_guide.md#upload-command)

非常感谢！可以正常运行了～

**Comment by mgqa34** [comment]
> > 需要上传相应的数据,可以通过下面两种方式：
> > 
> > * [pipeline上传数据](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb)
> > * [flow cli上传数据](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/dsl_conf/upload_data_guide.md#upload-command)
> 
> 非常感谢！可以正常运行了～

问题应该已解决，这个issue我这边先close了
