### ISSUE TITLE
OnevsRest Logistic Regression predicted probability 

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4637]
Hello, 
I am running a multi class logistic regression model, and I don't seem to understand the output predicted probabilities for each class. When running pipeline/hetero_logistic_regression/pipeline-hetero-lr-one-vs-all.py

The data output is as below. 

<img width="1003" alt="Screenshot 2023-02-22 at 03 08 03" src="https://user-images.githubusercontent.com/73941975/220603103-73d245e3-1a7b-45ed-9ee2-39a2f16d029c.png">

I need a relative probability for each class so that they add up to 1.  Could you please let me know how to do so ?

**Comment by mgqa34** [comment]
Maybe what you really need is softmax? Only OVR strategy is supported in HeteroLR.
