### ISSUE TITLE
federatedai/client:1.7.0-release  jupyter 运行pipeline_tutorial_hetero_sbt.ipynb报错

### ISSUE THREAD

**Issue by houjibofa2050** [FederatedAI/FATE#4644]
![image](https://user-images.githubusercontent.com/19608744/220837250-ea367f8d-32ef-4133-853a-13b1059553ba.png)
这段代码在我本地的编译器pycharm是可以运行的，但是在federatedai/client容器启动的jupyter中无法运行，报错，大佬抽空帮忙看看哈

**Comment by mgqa34** [comment]
这个报错应该是连接不上fateflow服务
