### ISSUE TITLE
我想要进行图像分割工作，如何将Mask图像输入进去

### ISSUE THREAD

**Issue by 1170300814** [FederatedAI/FATE#4645]
![image](https://user-images.githubusercontent.com/33786218/220846217-8400b029-e528-4d27-b8ed-ab5cab83fe78.png)
如截图所示，这个图像分割工作需要多个文件，我看到的实例中都是只能输入一个文件的，比如：
![image](https://user-images.githubusercontent.com/33786218/220847161-5e9d99ed-0139-4a1e-b13e-c805592174df.png)
这种，在guest或者host之中只有一个数据路径，我该怎么写呢？请给我一些示例，谢谢！

**Comment by talkingwallace** [comment]
可以考虑把train image/mask image都写到一个Dataset里？

**Comment by 1170300814** [comment]
都写到一个dataset的话不就无法进行分割的学习了吗？

**Comment by 1170300814** [comment]
请问您是FATE的开发者是吗？能不能指导一下呢，因为我想拿UNet做图像分割工作，这在FATE中是第一次

**Comment by 1170300814** [comment]
是的，进行Loss计算的时候需要用到mask数据集

**Comment by 1170300814** [comment]
能加您一个联系方式吗？好交流一些

**Comment by 1170300814** [comment]
或者您加一下我

**Comment by talkingwallace** [comment]
> 或者您加一下我

hi 你可以把你的联系方式发到我github主页的邮箱里

**Comment by 1170300814** [comment]
已发送，您查看一下
