### ISSUE TITLE
update job status does not take effect in secureboost

### ISSUE THREAD

**Issue by jingqidiana** [FederatedAI/FATE#4646]
在运行横向双方secureboost的时候出现了如下报错并停止运行，并不是多个host的原因，像请问这个应该怎么改呀，/(ㄒoㄒ)/
使用的是virtualbox虚拟centos7，FATE1.7.0
![image](https://user-images.githubusercontent.com/126188633/220976198-97649a98-5c16-45c4-a649-ad6a53b5ea57.png)

> [ERROR] [2023-02-23 16:30:38,035] [202302231630277106630] [41:140232945231616] - [federated_scheduler.task_command] [line:246]: failed to execute federated task reader_0 command(status/running) detail: 
2 {'host': {'9998': {'retcode': 0, 'retmsg': 'success'}}, 'guest': {'9999': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}}
3 [ERROR] [2023-02-23 16:31:11,400] [202302231630277106630] [41:140232945231616] - [federated_scheduler.task_command] [line:246]: failed to execute federated task reader_1 command(status/running) detail: 
4 {'host': {'9998': {'retcode': 0, 'retmsg': 'success'}}, 'guest': {'9999': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}}
5 [ERROR] [2023-02-23 16:31:40,765] [202302231630277106630] [41:140232945231616] - [federated_scheduler.task_command] [line:246]: failed to execute federated task data_transform_0 command(status/running) detail: 
6 {'host': {'9998': {'retcode': 0, 'retmsg': 'success'}}, 'guest': {'9999': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}}
7 [ERROR] [2023-02-23 16:32:51,744] [202302231630277106630] [41:140232945231616] - [federated_scheduler.task_command] [line:246]: failed to execute federated task data_transform_0 command(status/running) detail: 
8 {'host': {'9998': {'retcode': 0, 'retmsg': 'success'}}, 'guest': {'9999': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}}
9 [ERROR] [2023-02-23 16:40:43,588] [202302231630277106630] [41:140232945231616] - [federated_scheduler.task_command] [line:246]: failed to execute federated task data_transform_0 command(status/running) detail: 
10 {'host': {'9998': {'retcode': 0, 'retmsg': 'success'}}, 'guest': {'9999': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}}

log如下：
![bfe4483eb9c8a392071dad0f1448cab](https://user-images.githubusercontent.com/126188633/220975933-a2b83b3e-3314-4fbb-9df1-71d5e2f5bc9c.png)

**Comment by mgqa34** [comment]
可以看看host\ugest方的错误日志，上面的更新失败状态不是真正的错误
