### ISSUE TITLE
关于arbiter的问题请教一下

### ISSUE THREAD

**Issue by LemonGitMin** [FederatedAI/FATE#4647]
1. 几个参与方的角色guest、host、arbiter是在部署完成就确定了的吗？我看提交训练任务的配置文件中也有着几个参数，是在提交训练任务的时候可以重新定义哪个参与方是哪个角色吗？
2. arbiter在新的版本中是不是非必须的？如果是，什么情况下是不需要的？

**Comment by mgqa34** [comment]
1. fate部署的时候并没有指定角色
2. 大部分算法是不需要协调方的，需要协调方的算法应该是纵向联邦三方GLM和一些横向算法，对于纵向联邦GLM我们也提供了无需协调方的SSHE-LR/LinR作为使用选项。
