### ISSUE TITLE
关于fate-v1.10-dockerfateflow启动失败

### ISSUE THREAD

**Issue by NicerOuZa** [FederatedAI/FATE#4648]
之前提交任务，一提交就报错apsw.BusyError: BusyError: database is locked，然后使用命令
ps aux | grep fate | awk '{print $2}' | xargs -n1 kill -9
杀死所有fate进程后，
cd fateflow目录，输入命令
bash bin/service.sh restart
最后输出
service start failed, please check /data/projects/fate/fateflow/logs/error.log and /data/projects/fate/fateflow/logs/console.log
查看error.log发现输出日志为
Other threads are currently calling into gRPC, skipping fork() handlers
请问应如何解决？

**Comment by mgqa34** [comment]
使用的部署方式是哪种呢？

**Comment by NicerOuZa** [comment]
docker单机版镜像部署，v1.10版本
