### ISSUE TITLE
新算法开发中的数据结构

### ISSUE THREAD

**Issue by KAgBMan** [FederatedAI/FATE#4649]
您好，在我进行新算法模块开发时，算法组件上一步接的是框架已经内置的隐私求交模块，当我在新算法的fit函数中拿到train_data后不知该变量的类型和内部结构，所以不知该如何操作，请问有没有该数据的数据结构文件或其他介绍？谢谢！
`def fit(self, train_data, validate_data=None):`

**Comment by mgqa34** [comment]
> 您好，在我进行新算法模块开发时，算法组件上一步接的是框架已经内置的隐私求交模块，当我在新算法的fit函数中拿到train_data后不知该变量的类型和内部结构，所以不知该如何操作，请问有没有该数据的数据结构文件或其他介绍？谢谢！ `def fit(self, train_data, validate_data=None):`

隐私求交模块不关心数据内部结构，只关心key。如果是reader->data_transform->intersection->...的数据，data_transform会转成分布式的表，表每一行的值是data_instance(python/federatedml/feature/instance.py)，如果只是经过reader，读的是上传的数据的话，那应该是一个分布式表，然后每行是字符串
