### ISSUE TITLE
FATE高可用部署成功，fateboard页面请求fateflow信息成功，但是不展示fateflow信息

### ISSUE THREAD

**Issue by MDGBDGMG** [FederatedAI/FATE#4650]
**环境说明**
fate版本 ：V1.10.0
部署方式：Ansible
部署两个party，A和B
其中，party B是两台虚机组成的fateflow HA

跑toy测试成功，并且关闭B的任何一个虚机上fateflow，执行中的job都不受影响

**Describe the bug**
fateboard页面上，接口可以查询到两个fateflow信息，但是下拉菜单内容为空

![image](https://user-images.githubusercontent.com/45615979/222074518-ae67236f-1da5-4666-8ca2-f6653afaef57.png)

请大佬帮忙看看是什么问题，多谢

**Comment by idwenwen** [comment]
感谢你的反馈。

这个问题需要涉及到一点基于board 的 1.10.0版本源码上的变更。
**文件位置**： 

- 本地项目文件位置：项目目录/resources-front-end/src/views/job-dashboard/log/Logs.vue

- github文件对应位置：[https://github.com/FederatedAI/FATE-Board/blob/develop-1.10.0/resources-front-end/src/views/job-dashboard/log/Logs.vue](https://github.com/FederatedAI/FATE-Board/blob/develop-1.10.0/resources-front-end/src/views/job-dashboard/log/Logs.vue)

**修改方式**：
1. 找寻到 _getInstanceIdFromFlow_ 这一段方法的位置
2. 如图左侧红色标记行，替换成如图右侧绿色标记行的内容（ _for (const instance of Object.values(res.data)) {_ ）
![image](https://user-images.githubusercontent.com/9588052/222104181-b07c6f7b-99e7-4305-948b-f10f5b371927.png)
3. 重新打jar包

当前问题我们会在后续版本之中进行修复。
