### ISSUE TITLE
模型训练完成后，预测时为什么要输入host方的数据集？

### ISSUE THREAD

**Issue by liuyichen2013** [FederatedAI/FATE#4652]
**Describe the bug**
模型训练完成后，将模型导出，然后在一个新的fate环境中再导入模型，然后deploy，之后编写predict配置文件，需要填写host方的数据集，然后新的环境中是没有host的数据集的，这个怎么办？

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mgqa34** [comment]
横向联邦还是纵向联邦建模的场景？横向联邦LR\SecureBoost可以只填一方

**Comment by liuyanfeng1981** [comment]
我用的是纵向联邦，是不是纵向联邦就必须要host方的数据集配合预测？

**Comment by mgqa34** [comment]
纵向联邦guest&host得到的只是半模型，不是完整模型，所以预测阶段是需要双方联合的
