### ISSUE TITLE
migrate后的模型经过import---deploy---load---bind后，在线推理无法返回score值

### ISSUE THREAD

**Issue by liuyanfeng1981** [FederatedAI/FATE#4676]
**Describe the bug**
纵向联邦训练完成后（guest和host都是9999），migrate后（10000），然后在节点10000上import---deploy---load---bind后，在线推理无法返回结果：
![image](https://user-images.githubusercontent.com/88218731/223415947-fd5fd0df-4316-450f-8a0c-31a9e26397b6.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mgqa34** [comment]
migrate后对应的model_id\version，离线预测是否OK？ 离线任务DSL是怎样的？

**Comment by liuyanfeng1981** [comment]
> migrate后对应的model_id\version，离线预测是否OK？ 离线任务DSL是怎样的？

离线是可以的
{
    "components": {
        "reader_0": {
            "module": "Reader",
            "output": {
                "data": [
                    "data"
                ]
            }
        },
        "intersection_0": {
            "input": {
                "data": {
                    "data": [
                        "data_transform_0.data"
                    ]
                }
            },
            "module": "Intersection",
            "output": {
                "data": [
                    "data"
                ]
            }
        },
        "data_transform_0": {
            "input": {
                "data": {
                    "data": [
                        "reader_0.data"
                    ]
                },
                "model": [
                    "pipeline.data_transform_0.model"
                ]
            },
            "module": "DataTransform",
            "output": {
                "data": [
                    "data"
                ]
            }
        },
        "hetero_secure_boost_0": {
            "input": {
                "data": {
                    "test_data": [
                        "intersection_0.data"
                    ]
                },
                "model": [
                    "pipeline.hetero_secure_boost_0.model"
                ]
            },
            "module": "HeteroSecureBoost",
            "output": {
                "data": [
                    "data"
                ]
            }
        }
    }
}

**Comment by liuyanfeng1981** [comment]
我与在本节点训练并部署的模型对比了一下，导入模型的pipline参数为空：
![image](https://user-images.githubusercontent.com/88218731/223607755-ffce7f6a-29b0-46d5-a1a3-46e1112ba826.png)
![image](https://user-images.githubusercontent.com/88218731/223607826-60f70690-1707-45ad-8ac6-e9de5da774ca.png)
![image](https://user-images.githubusercontent.com/88218731/223608078-f9523354-0b22-43d7-9eb7-8e3352069f18.png)

**Comment by jhuser02** [comment]
I have encountered the same problem. May I ask if there is any solution? 
我遇到相同的问题. 请问有何解决办法吗? 
@liuyanfeng1981 @mgqa34 @zhihuiwan @cometta

**Comment by zhihuiwan** [comment]
感谢反馈，这里确实是个bug，可以参考修复：https://github.com/FederatedAI/FATE-Flow/commit/76f4145d9ad22903a382875f2010c37e22435bfa
我们会在后续版本中修复。

**Comment by jhuser02** [comment]
thx. 顺问下个版本大概啥时候发布?

**Comment by zhihuiwan** [comment]
预计下个月会发布
