### ISSUE TITLE
docker compose方式部署时会偶发python容器反复重启的问题

### ISSUE THREAD

**Issue by hust-suwb** [FederatedAI/FATE#4679]
**Describe the bug**
docker compose方式部署时会偶发python容器反复重启的问题

**Screenshots**
<img width="727" alt="image" src="https://user-images.githubusercontent.com/6924793/223660229-ffa3faa1-4bda-4730-b2e0-29b25f75e8a4.png">

**Desktop (please complete the following information):**
 - OS: CentOS7
 - Version: FATE1.7.0

**Additional context**
从异常日志可知，报错源于无法连接mysql，但此时mysql镜像是正常启动的。另外，这个事情在历次部署过程中有出现过好几次，通常docker-compose down然后docker-compose up试几次可以恢复。但也有反复重试都无法恢复的。
请问这个问题是一个已知的bug吗，如果是的话在后续哪个版本有修复吗？

**Comment by zhihuiwan** [comment]
感谢您的反馈，根据您的描述，python容器反复重启的原因是因为数据库连不上，您可以手动连接下数据库试试，这个应该和代码没关系。
