### ISSUE TITLE
1.10样本求交，单机模式，求交结果不对

### ISSUE THREAD

**Issue by tujianxin** [FederatedAI/FATE#4680]
基于1.10版本代码，用单机模式，跑各种求交算法，求交结果明显不对，示例为example/pipeline/intersection下，经过debug发现
![23dc3870cc62bf8fc0c49a175395119](https://user-images.githubusercontent.com/5936408/223663184-9b6b1b66-1fb1-4f24-85f9-1acf358e8ab1.png)
经过这个函数处理后，由原始的569变为了153条，这个地方不对应该是什么原因呢？guest方和host方都是一样的，经过并行处理后，样本数量都减少了

**Comment by nemirorox** [comment]
你好，我们在1.10单机版环境内使用rsa交集反复运行没有复现上述问题，方便的话，可以提供一些背景信息协助我们判断可能原因吗？
1. 请提供部署方法（docker/安装包等）以及部署环境信息（系统、python版本等）
2. 部署环境内是否（曾经）存在多个fate系统，如曾在同一环境使用旧版本，是怎样升级至1.10的？
3. 任务发起方式是哪种？如命令行python/fate_test批量运行/pycharm等。最好可以做如下快速验证：同样配置的任务在1.9环境中使用同样的发起方式，返回结果是否正常？

**Comment by tujianxin** [comment]
你好，我现在用的求交方式进行求交，结果不对，我把我这边的环境给你说一下
1 我用的是安装包部署方式，部署环境为centos7,python版本为3.8.1，python 安装在centos环境上
2 之前老的fate系统，我已经彻底删除干净了，我最开始也是以为是老版本代码导致的，删除之后，结果还是不对，这个升级过程是，我们之前用的是fate1.8,然后merge到fate1.10的
3 任务发起方式通过fate_flow_server启动的服务，用pycharm单个执行pipeline-intersection-rsa.py文件的，除了rsa之外，其他的dh,ecdh，raw都有验证的，结果都是不对，正确的结果应该是569，用的都是py文件中默认参数，没有做任何修改操作，谢谢
fate1.9没有使用过，

**Comment by nemirorox** [comment]
请问merge升级是指使用git pull吗？还是删除了全部环境，直接使用原始1.10安装包呢？1.10与1.8之间ml算法与flow等组件均有改动，我们还是建议使用官方安装包在全新环境进行安装。
如果使用原始1.10安装包也依然有问题，建议尝试使用同样启动方法，在1.9版本环境实验看看运行结果是否符合预期。

**Comment by tujianxin** [comment]
你好，是的，使用github上的merge操作的，然后用的是1.10安装包来运行相关代码的，你说的对，1.10和1.8之间改动实际上比较大，我们也有注意到，谢谢你的回复

**Comment by nemirorox** [comment]
了解，目前更新1.10后运行交集任务结果是否符合预期呢？如果问题已解决，请close issue，多谢
