### ISSUE TITLE
纵向深度神经网络

### ISSUE THREAD

**Issue by tujianxin** [FederatedAI/FATE#4681]
深度网络那边为啥 batch_label 有两个元素，第二个元素是啥？见图
<img width="1554" alt="dba1938f7ef326638d0b36119c5ebcc" src="https://user-images.githubusercontent.com/5936408/223890482-979d9859-1bb8-4138-a120-76426fe56762.png">
谢谢回复

**Comment by talkingwallace** [comment]
请问是用了自己定制的Dataset么
