### ISSUE TITLE
纵向联邦examples中breast_hetero 中的特征问题

### ISSUE THREAD

**Issue by fsx379** [FederatedAI/FATE#4684]
使用 breast_hetero_host.csv 和  breast_hetero_guest.csv 纵向逻辑回归的例子中。
guest 特征是 x0 ~x9 ， host 特征是  x0 ~x19 。
那么在纵向逻辑回归 中，对于id相同的用户，以哪方的   x0 ~x9特性 为准？

**Comment by talkingwallace** [comment]
没太明白您的意思？各方的命名可以是随意的，各方的特征不管如何命名都会是一个联邦任务中单独的一个特征，guest的x0~x9和host的x0~x9都会参与到训练中

**Comment by fsx379** [comment]
了解了。这些数据，如果用于横向，肯定是要有相同的特征名称；如果是纵向，把他们命名为不同特征，更好理解。

**Comment by fsx379** [comment]
了解了。这些数据，如果用于横向，肯定是要有相同的特征名称；如果是纵向，把他们命名为不同特征，更好理解。
