### ISSUE TITLE
最新版(1.10)还有矩阵分解的模块吗？

### ISSUE THREAD

**Issue by aqzl1** [FederatedAI/FATE#4686]
我想用FATE框架做一个与推荐系统相关的项目，需要进行矩阵分解，但是我在1.10版本里面找不到矩阵分解，我看1.3版本还有这个功能，请问是砍掉了吗？

**Comment by talkingwallace** [comment]
目前推荐算法单独在fedrec下，需要与FATE-1.4配合使用，1.10的话暂时不支持的

**Comment by aqzl1** [comment]
多谢
