### ISSUE TITLE
1.10intersection,new sample_id

### ISSUE THREAD

**Issue by tujianxin** [FederatedAI/FATE#4687]
我现在用1.10单机版本想运行一个new sample id示例，具体参数一下，
![image](https://user-images.githubusercontent.com/5936408/224588940-fb7110c6-4db5-46e3-afe9-ab8d7c193872.png)
样本为
![image](https://user-images.githubusercontent.com/5936408/224588978-d4658638-047c-4201-aa39-2cd8e600d2ec.png)
![image](https://user-images.githubusercontent.com/5936408/224589001-21f7bc59-0a8a-4c22-819c-df6d0bfc6803.png)
但是最终结果报错了，结果提示
![image](https://user-images.githubusercontent.com/5936408/224589172-e9a82d44-f440-424f-b7fb-06313eaea364.png)
这是什么原因？是因为我求交的时候，设置的参数不对吗？

**Comment by tujianxin** [comment]
我知道是什么问题，我设置的参数不对导致的

**Comment by tujianxin** [comment]
![image](https://user-images.githubusercontent.com/5936408/224617654-34e92144-0e1e-4262-9e0f-22637a83f166.png)
我检查了一下求交结果，发现结果不对
![image](https://user-images.githubusercontent.com/5936408/224617746-494305de-a4f5-44cf-b547-112bb5061b0b.png)
![image](https://user-images.githubusercontent.com/5936408/224617787-9f2af305-f13c-4f5a-acd3-29676efa83ff.png)
left_join的话，不应该是8条记录，怎么是5呢？

**Comment by nemirorox** [comment]
你好，根据目前提供的信息，建议从以下两个方向尝试调整任务配置看看是否可以得到预期结果：
1. 数据存在重复的match id的情况下，upload需要配置extend_sid以保留所有数据；
2. left join默认同步的是guest方的id，如果需要同步host方id（如果8个id的持有者是host），可以配置intersection组件参数'new_sample_id_generator' = 'host'.

上传数据的配置可以参考此文档：https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_match_id.ipynb
