### ISSUE TITLE
1.10 intersection left join

### ISSUE THREAD

**Issue by tujianxin** [FederatedAI/FATE#4694]
想请教一下，intersection 中 join_method为left join的时候,host方只有id，没有feature，为什么left join的时候host只有id一列，其他的列不显示，其原因是什么？能从业务帮忙回复一下吗？还有left join的应用场景是什么？谢谢回复

**Comment by nemirorox** [comment]
left join配置下host仅输出id有以下两种可能：

1. intersection组件配置中`only_output_key`=True
2. host与guest没有交集，host输出均为guest方发送的sid项

可以从以上两种角度排查具体原因。如果不需要双方id数量保持一致，配置默认的`join_method`='inner_join'即可。
