### ISSUE TITLE
bind模型后，在host端的FATE-serving上面绑定的模型没有serviceID

### ISSUE THREAD

**Issue by dxy0202** [FederatedAI/FATE#4697]
FATE版本是1.10，通过ansible三方部署
FATE-serving版本是2.1.5
我在guest端绑定模型成功后，可以在guest端的FATE-serving上面看到绑定的模型和serviceID，在host端的FATE-serving上面能看到绑定的模型，但是看不到绑定模型的serviceID，导致我在guest端发起在线预测时host端返回的是"host return code 104 host msg :mode is null"，请问这个问题应该怎么解决？
![image](https://user-images.githubusercontent.com/92411690/226106556-0e59161b-9d4b-4c3d-8a4b-4681095f2733.png)

**Comment by forgivedengkai** [comment]
serviceId 只在guest 存在 ，host端模型找不到一般需要确认几个问题， host有几个实例？是不是每个实例都已发布模型 ？  serving-proxy 到serving-server 之间的配置是否正确 ，比如如果使用zookeeper  ，zookeeper 地址是否正确？如果不使用zookeeper  各个组件地址是否配置正确 ？guest 发往host的路由配置是否正确，是不是有可能guest 发给了guest ？

**Comment by dxy0202** [comment]
> serviceId 只在guest存在，host端模型找不到一般需要确认几个问题，host有几个实例？是不是每个实例都已经发布模型？如果使用zookeeper，zookeeper地址是否正确？如果不使用zookeeper各组地址是否正确？guest发往host的路径是否正确guest，是不是？

谢谢您的回复。

**Comment by yyf1986** [comment]
你应该没有配置另外一方的severing-proxy
