### ISSUE TITLE
standalone模式部署fate2.0（branch dev-2.0-alpha），通信方式改成osx，运行fate_flow/examples/test/job.py失败

### ISSUE THREAD

**Issue by RicLee0124** [FederatedAI/FATE#4700]
**Describe the bug**
通过standalone模式部署fate2.0，运算，存储，通信引擎都是standalone模式下，运行fate_flow/examples/test/job.py用例是成功的，但是当通信方式改成osx，存储和计算保持standalone时，运行job.py用例，就会一直卡在intersection_0这一步。
调度日志如下：
![image](https://user-images.githubusercontent.com/20515783/226281089-559902f6-0894-4dcd-8387-ccfb3e596c69.png)

fate_flow的service_conf.yaml配置如下：
![image](https://user-images.githubusercontent.com/20515783/226277758-2873fd82-b3c4-4053-938d-2327346d52f4.png)
![image](https://user-images.githubusercontent.com/20515783/226278372-9fcd5688-c113-449b-bd29-35df0e9d461e.png)

osx的route_table.json配置如下：
![image](https://user-images.githubusercontent.com/20515783/226278020-2e76846e-2923-48c3-bf1b-cc1022dcb4af.png)

怀疑是route_table.json配置导致的，主要是不知道fate 2.0里面osx该怎么使用。
另外，我也有尝试过将fate_flow的service_conf.yaml中worker模式改为docker，任务在起来之后，在reader阶段就失败了，应该也是配置问题。我的配置是按照文档上推荐的配置来配的，没有修改，参考的是这份文档，https://github.com/FederatedAI/FATE-Flow/blob/v2.0.0-alpha/doc/quick_start.md
![image](https://user-images.githubusercontent.com/20515783/226278233-efd0eff3-124a-4c26-87d0-4c4a0dc75b28.png)

fate_flow没有使用到eggroll，存储和计算使用的都是standalone模式，通信 使用的是osx，这种情况下配置中的eggroll_conf_dir目录还需要配置么？而且reader阶段就失败了，但是在任务的logs里面没有看到错误日志，这种情况改怎么排查呢？
![image](https://user-images.githubusercontent.com/20515783/226276809-45f9ca42-dd82-45a5-a342-8a7c0699daae.png)

**Comment by forgivedengkai** [comment]
想了解下详细情况 ，能否加下联系方式？ 麻烦将微信发邮箱forgive_dengkai@163.com ？
