### ISSUE TITLE
如何上传多个文件？

### ISSUE THREAD

**Issue by 30033** [FederatedAI/FATE#4702]
fate 版本 1.7.2

上传单个文件的配置文件如下

upload_guest.json

{
          "file": "/data/projects/fate/examples/data/vipvip01",
          "id_delimiter": ",",
          "head": 1,
          "partition": 4,
          "namespace": "experiment",
          "table_name": "20230321_vipvip01"
}

我本地有1000多个文件 从vipvip01、vipvip02……vipvip1001 这样 如何都写进一个配置文件里？

**Comment by talkingwallace** [comment]
可以考虑使用fate_test批量上传下文件
