### ISSUE TITLE
如何从 pkl 文件中，将每个模块的参数分别导出？

### ISSUE THREAD

**Issue by DongRuiHust** [FederatedAI/FATE#4731]
假设我现在只需要其中一个模块的参数，如何从 pkl 文件中导出呢？

**Comment by talkingwallace** [comment]
是pipeline的pkl么

**Comment by DongRuiHust** [comment]
> 是pipeline的pkl么

是的，使用 pipeline 保存了 pkl 文件，然后想把单个模块的参数导出。

**Comment by DongRuiHust** [comment]
> 是pipeline的pkl么

**Comment by DongRuiHust** [comment]
>

**Comment by DongRuiHust** [comment]
> 是pipeline的pkl么

是的，这边训练完成后保存了 pkl 文件。
举个例子：假设我搭建了一个纵向联邦学习任务，然后我想把 hetero_nn 的参数解析出来做分析，或者单方（不依赖对方）只使用 hetero_nn 的参数，然后送入输入做预测。

**Comment by talkingwallace** [comment]
hi 在fateflow/local_model_cache下 可以找到模型的param的json文件，模型被转化成bytes存储在里面
另外一种方式就是你修改源代码，把模型直接dump到文件系统里也是可以的

**Comment by DongRuiHust** [comment]
> hi 在fateflow/local_model_cache下 可以找到模型的param的json文件，模型被转化成bytes存储在里面 另外一种方式就是你修改源代码，把模型直接dump到文件系统里也是可以的

感谢你的回答，还有两个问题想请教下：
（1）请问，这个 bytes 文件有什么方法能够直接恢复成数值吗？
（2）假设我想修改源码，可否指点一下思路呢？

**Comment by talkingwallace** [comment]
Hi
1. 这个bytes经过base64 encode的 然后可以找一下hetero-nn的recover_from_bytes (大概叫这个）
2. 可以看nn/hetero/下的guest.py host.py 的export_model

**Comment by DongRuiHust** [comment]
> 1. 这个bytes经过base64 encode的 然后可以找一下hetero-nn的recover_from_bytes (大概叫这个）
> 2. 可以看nn/hetero/下的guest.py host.py 的export_model

感谢！

**Comment by lidefan888** [comment]
请问实现了么，我找到了模型的param的json文件，但是不知道该如何解码
