### ISSUE TITLE
想问下纵向联邦的时候两方的数据只有一列id是共有列，可以进行联邦学习吗，看官方的实例是返回了两方的公有列数据，而不是双方的并集列

### ISSUE THREAD

**Issue by turbominxi** [FederatedAI/FATE#4732]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by turbominxi** [comment]
**'''upload data'''
from pipeline.backend.pipeline import PipeLine
pipeline_upload = PipeLine().set_initiator(role='guest', party_id=9999).set_roles(guest=9999)
partition = 4
dense_data_guest = {"name": "train_a_label", "namespace": f"experiment"}
dense_data_host = {"name": "train_b", "namespace": f"experiment"}
tag_data = {"name": "train_b", "namespace": f"experiment"}
import os

data_base = "/data/projects/fate"
pipeline_upload.add_upload_data(file=os.path.join(data_base, "train_a_label.csv"),
                                table_name=dense_data_guest["name"],             # table name
                                namespace=dense_data_guest["namespace"],         # namespace
                                head=1, partition=partition)               # data info

pipeline_upload.add_upload_data(file=os.path.join(data_base, "train_b.csv"),
                                table_name=dense_data_host["name"],
                                namespace=dense_data_host["namespace"],
                                head=1, partition=partition)

pipeline_upload.add_upload_data(file=os.path.join(data_base, "train_b.csv"),
                                table_name=tag_data["name"],
                                namespace=tag_data["namespace"],
                                head=1, partition=partition)

pipeline_upload.upload(drop=1)


'''train'''

from pipeline.component import Reader, DataTransform, Intersection, HeteroSecureBoost, Evaluation
from pipeline.interface import Data

pipeline = PipeLine() \
        .set_initiator(role='guest', party_id=9999) \
        .set_roles(guest=9999, host=10000)
reader_0 = Reader(name="reader_0")
# set guest parameter
reader_0.get_party_instance(role='guest', party_id=9999).component_param(
    table={"name": "train_a_label", "namespace": "experiment"})
# set host parameter
reader_0.get_party_instance(role='host', party_id=10000).component_param(
    table={"name": "train_b", "namespace": "experiment"})

data_transform_0 = DataTransform(name="data_transform_0")
# set guest parameter
data_transform_0.get_party_instance(role='guest', party_id=9999).component_param(
    with_label=True)
data_transform_0.get_party_instance(role='host', party_id=[10000]).component_param(
    with_label=False)

intersect_0 = Intersection(name="intersect_0")

hetero_secureboost_0 = HeteroSecureBoost(name="hetero_secureboost_0",
                                         num_trees=5,
                                         bin_num=16,
                                         task_type="classification",
                                         objective_param={"objective": "cross_entropy"},
                                         encrypt_param={"method": "paillier"},
                                         tree_param={"max_depth": 3})

evaluation_0 = Evaluation(name="evaluation_0", eval_type="binary")

pipeline.add_component(reader_0)
pipeline.add_component(data_transform_0, data=Data(data=reader_0.output.data))
pipeline.add_component(intersect_0, data=Data(data=data_transform_0.output.data))
pipeline.add_component(hetero_secureboost_0, data=Data(train_data=intersect_0.output.data))
pipeline.add_component(evaluation_0, data=Data(data=hetero_secureboost_0.output.data))
pipeline.compile();

pipeline.fit()**

**Comment by FFinchR** [comment]
官方实例指的是breast_hetero数据集吗？
这个数据集的guest方特征与host方的特征是各自独立的，只是名称相同，在处理时仍会将guest方的x0与host方的x0作为不同的特征进行处理。
同时，guest与host方的同名特征实际上是不同的。
[原始的breast数据集](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data)含有30个特征：
[breast_hetero_guest](https://github.com/FederatedAI/FATE/blob/master/examples/data/breast_hetero_guest.csv)含有其中的10个特征列；
[breast_hetero_host](https://github.com/FederatedAI/FATE/blob/master/examples/data/breast_hetero_host.csv)含有剩余的20个特征列；
这一点你也可以从[breast_homo_guest](https://github.com/FederatedAI/FATE/blob/master/examples/data/breast_homo_guest.csv)这个横向联邦数据集中得到验证。
纵向联邦求交时只会根据id求交，所以，只有id相同是可以进行纵向联邦学习的。
希望对你有所帮助。

**Comment by turbominxi** [comment]
好的，谢谢，可以帮忙看下代码有什么问题吗，就是跑的下面的代码跑到fit时报错了。


'''upload data'''
from pipeline.backend.pipeline import PipeLine
pipeline_upload = PipeLine().set_initiator(role='guest', party_id=9999).set_roles(guest=9999)
partition = 4
dense_data_guest = {"name": "train_a_label", "namespace": f"experiment"}
dense_data_host = {"name": "train_b", "namespace": f"experiment"}
tag_data = {"name": "train_b", "namespace": f"experiment"}
import os


data_base = "/data/projects/fate"
pipeline_upload.add_upload_data(file=os.path.join(data_base, "train_a_label.csv"),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; table_name=dense_data_guest["name"],&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;# table name
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; namespace=dense_data_guest["namespace"],&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;# namespace
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; head=1, partition=partition)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;# data info


pipeline_upload.add_upload_data(file=os.path.join(data_base, "train_b.csv"),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; table_name=dense_data_host["name"],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; namespace=dense_data_host["namespace"],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; head=1, partition=partition)


pipeline_upload.add_upload_data(file=os.path.join(data_base, "train_b.csv"),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; table_name=tag_data["name"],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; namespace=tag_data["namespace"],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; head=1, partition=partition)


pipeline_upload.upload(drop=1)




'''train'''


from pipeline.component import Reader, DataTransform, Intersection, HeteroSecureBoost, Evaluation
from pipeline.interface import Data


pipeline = PipeLine() \
&nbsp; &nbsp; &nbsp; &nbsp; .set_initiator(role='guest', party_id=9999) \
&nbsp; &nbsp; &nbsp; &nbsp; .set_roles(guest=9999, host=10000)
reader_0 = Reader(name="reader_0")
# set guest parameter
reader_0.get_party_instance(role='guest', party_id=9999).component_param(
&nbsp; &nbsp; table={"name": "train_a_label", "namespace": "experiment"})
# set host parameter
reader_0.get_party_instance(role='host', party_id=10000).component_param(
&nbsp; &nbsp; table={"name": "train_b", "namespace": "experiment"})


data_transform_0 = DataTransform(name="data_transform_0")
# set guest parameter
data_transform_0.get_party_instance(role='guest', party_id=9999).component_param(
&nbsp; &nbsp; with_label=True)
data_transform_0.get_party_instance(role='host', party_id=[10000]).component_param(
&nbsp; &nbsp; with_label=False)


intersect_0 = Intersection(name="intersect_0")


hetero_secureboost_0 = HeteroSecureBoost(name="hetero_secureboost_0",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;num_trees=5,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bin_num=16,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;task_type="classification",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;objective_param={"objective": "cross_entropy"},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;encrypt_param={"method": "paillier"},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;tree_param={"max_depth": 3})


evaluation_0 = Evaluation(name="evaluation_0", eval_type="binary")


pipeline.add_component(reader_0)
pipeline.add_component(data_transform_0, data=Data(data=reader_0.output.data))
pipeline.add_component(intersect_0, data=Data(data=data_transform_0.output.data))
pipeline.add_component(hetero_secureboost_0, data=Data(train_data=intersect_0.output.data))
pipeline.add_component(evaluation_0, data=Data(data=hetero_secureboost_0.output.data))
pipeline.compile();


pipeline.fit()





陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] 想问下纵向联邦的时候两方的数据只有一列id是共有列，可以进行联邦学习吗，看官方的实例是返回了两方的公有列数据，而不是双方的并集列 (Issue #4732)





 
官方实例指的是breast_hetero数据集吗？
 这个数据集的guest方特征与host方的特征是各自独立的，只是名称相同，在处理时仍会将guest方的x0与host方的x0作为不同的特征进行处理。
 同时，guest与host方的同名特征实际上是不同的。
 原始的breast数据集含有30个特征：
 breast_hetero_guest含有其中的10个特征列；
 breast_hetero_host含有剩余的20个特征列；
 这一点你也可以从breast_homo_guest这个横向联邦数据集中得到验证。
 纵向联邦求交时只会根据id求交，所以，只有id相同是可以进行纵向联邦学习的。
 希望对你有所帮助。

**Comment by FFinchR** [comment]
我也是初学者，目前看起来代码没什么问题，需要在FATE-Board里或查看job的日志，了解具体的报错。
你的数据集是“星河杯”大赛的吗？该数据集包含字符串，空值之类的，需要一定的数据预处理才能使用，我也尚未跑通。

**Comment by turbominxi** [comment]
是的，那就是说fate上传的数据是要进行预处理的数据是吧，不能直接上传原始数据之后再进行处理


陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] 想问下纵向联邦的时候两方的数据只有一列id是共有列，可以进行联邦学习吗，看官方的实例是返回了两方的公有列数据，而不是双方的并集列 (Issue #4732)





 
我也是初学者，目前看起来代码没什么问题，需要在FATE-Board里或查看job的日志，了解具体的报错。
 你的数据集是“星河杯”大赛的吗？该数据集包含字符串，空值之类的，需要一定的数据预处理才能使用，我也尚未跑通。

**Comment by FFinchR** [comment]
从文档来看，FATE应该提供了预处理的能力，只是我不太会用=)，需要等官方人员来解答一下。

**Comment by turbominxi** [comment]
好哒，感谢~




陈敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] 想问下纵向联邦的时候两方的数据只有一列id是共有列，可以进行联邦学习吗，看官方的实例是返回了两方的公有列数据，而不是双方的并集列 (Issue #4732)





 
从文档来看，FATE应该提供了预处理的能力，只是我不太会用=)，需要等官方人员来解答一下。
