### ISSUE TITLE
1. 训练数据有 label1 和 label2，如何同时使用？2. 如何导出求交结果？

### ISSUE THREAD

**Issue by DongRuiHust** [FederatedAI/FATE#4741]
问题描述：
1. 当前建模场景有两个 loss，分别使用 label1 和 label2 计算，我看那个 data_transform 模块好像只支持传入一列作为 label，请问如何识别两个 label 呢？训练模块是不是也要更改？
2. 如果导出求交结果至本地？

**Comment by mgqa34** [comment]
1. 当前只支持1列label列
2. 可以通过flow的component output_data的接口进行数据导出

**Comment by DongRuiHust** [comment]
> 1. 当前只支持1列label列
> 2. 可以通过flow的component output_data的接口进行数据导出

感谢你的回答，很好的解决了我的问题。

我这边有个补充的问题想要请教一下：我用 output-model 得到了如下所示的模型参数，请问如何解析成数值呢？因为我想做一下训练后的参数分析。

返回结果如下：
{
    "data": {
        "bestIteration": -1,
        "header": [],
        "heteroNnModelParam": {
            "bottomModelInputShape": 0,
            "bottomSavedModelBytes": "UEsDBAAACAgAAAAAAAAAAAAAAAAAAAAAAAAQABIAYXJjaGl2ZS9kYXRhLnBrbEZCDgBaWlpaWlpaWlpaWlpaWoACfXEAKFgJAAAAbm5fZGVmaW5lcQF9cQIoWAMAAAAwLTBxA31xBChYBAAAAGJpYXNxBYhYBgAAAGRldmljZXEGTlgFAAAAZHR5cGVxB05YCwAAAGluX2ZlYXR1cmVzcQhLClgMAAAAb3V0X2ZlYXR1cmVzcQlLBFgFAAAAbGF5ZXJxClgGAAAATGluZWFycQtYCwAAAGluaXRpYWxpemVycQx9cQ11WAMAAAAxLTFxDn1xDyhYBwAAAGlucGxhY2VxEIloClgEAAAAUmVMVXERaAx9cRJ1dVgFAAAAbW9kZWxxE2Njb2xsZWN0aW9ucwpPcmRlcmVkRGljdApxFClScRUoWAoAAAAwLTAud2VpZ2h0cRZjdG9yY2guX3V0aWxzCl9yZWJ1aWxkX3RlbnNvcl92MgpxFygoWAcAAABzdG9yYWdlcRhjdG9yY2gKRmxvYXRTdG9yYWdlCnEZWAEAAAAwcRpYAwAAAGNwdXEbSyh0cRxRSwBLBEsKhnEdSwpLAYZxHoloFClScR90cSBScSFYCAAAADAtMC5iaWFzcSJoFygoaBhoGVgBAAAAMXEjaBtLBHRxJFFLAEsEhXElSwGFcSaJaBQpUnEndHEoUnEpdX1xKlgJAAAAX21ldGFkYXRhcStoFClScSwoWAAAAABxLX1xLlgHAAAAdmVyc2lvbnEvSwFzWAMAAAAwLTBxMH1xMWgvSwFzWAMAAAAxLTFxMn1xM2gvSwFzdXNiWBAAAABvcHRpbWl6ZXJfZGVmaW5lcTR9cTUoWAIAAABscnE2Rz+EeuFHrhR7WAUAAABiZXRhc3E3XXE4KEc/7MzMzMzMzUc/7/fO2RaHK2VYAwAAAGVwc3E5Rz5FeY7iMIw6WAwAAAB3ZWlnaHRfZGVjYXlxOksAWAcAAABhbXNncmFkcTuJWAkAAABvcHRpbWl6ZXJxPFgEAAAAQWRhbXE9WAsAAABjb25maWdfdHlwZXE+WAcAAABweXRvcmNocT91WAkAAABvcHRpbWl6ZXJxQH1xQShYBQAAAHN0YXRlcUJ9cUMoSwB9cUQoWAQAAABzdGVwcUVoFygoaBhoGVgBAAAAMnFGaBtLAXRxR1FLACkpiWgUKVJxSHRxSVJxSlgHAAAAZXhwX2F2Z3FLaBcoKGgYaBlYAQAAADNxTGgbSyh0cU1RSwBLBEsKhnFOSwpLAYZxT4loFClScVB0cVFScVJYCgAAAGV4cF9hdmdfc3FxU2gXKChoGGgZWAEAAAA0cVRoG0sodHFVUUsASwRLCoZxVksKSwGGcVeJaBQpUnFYdHFZUnFadUsBfXFbKGhFaBcoKGgYaBlYAQAAADVxXGgbSwF0cV1RSwApKYloFClScV50cV9ScWBoS2gXKChoGGgZWAEAAAA2cWFoG0sEdHFiUUsASwSFcWNLAYVxZIloFClScWV0cWZScWdoU2gXKChoGGgZWAEAAAA3cWhoG0sEdHFpUUsASwSFcWpLAYVxa4loFClScWx0cW1ScW51dVgMAAAAcGFyYW1fZ3JvdXBzcW9dcXB9cXEoWAIAAABscnFyRz+EeuFHrhR7WAUAAABiZXRhc3FzXXF0KEc/7MzMzMzMzUc/7/fO2RaHK2VYAwAAAGVwc3F1Rz5FeY7iMIw6WAwAAAB3ZWlnaHRfZGVjYXlxdksAWAcAAABhbXNncmFkcXeJWAgAAABtYXhpbWl6ZXF4iVgHAAAAZm9yZWFjaHF5TlgKAAAAY2FwdHVyYWJsZXF6iVgOAAAAZGlmZmVyZW50aWFibGVxe4lYBQAAAGZ1c2VkcXyJWAYAAABwYXJhbXNxfV1xfihLAEsBZXVhdVgLAAAAbG9zc19kZWZpbmVxf051LlBLBwjfr70kfAUAAHwFAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAAA4ACABhcmNoaXZlL2RhdGEvMEZCBABaWlpaDs2aPmq6IjzAFBi+tAIzvV7cuL3ETs+9E5SRPqRxiz60naQ+fT2iPZ5R5z4MagI/yye4PmcYtzz4xZs93nU7vBMCzD4WwG4+4cf6Ph9EGz7GM+4+CpOxPgQMMz4sa4k8BouiPq9AUT6yItU8Df+8PrCdEz4RN+y9yILBvrwFpz1pApG90YbUvkgUPz0f/kG+LjH9vmLg2r0wyJi+psigvlBLBwimKp5voAAAAKAAAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAAA4AJABhcmNoaXZlL2RhdGEvMUZCIABaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlw1170mvrC9JqNTPuSp7T5QSwcIIhAS6BAAAAAQAAAAUEsDBAAACAgAAAAAAAAAAAAAAAAAAAAAAAAOADQAYXJjaGl2ZS9kYXRhLzJGQjAAWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaAACgQVBLBwjzEpiOBAAAAAQAAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAAA4AQABhcmNoaXZlL2RhdGEvM0ZCPABaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpijiC6E9trutV4Irp5YBK6vBkqukEYLro3pT26Bf1GulInJ7pwwfO5kYG0u5PVNbvAZbO7wQmju9OxYrsHZHy7Q3uCu1mpuLuE0la7JkcBu+NMWbykoO+7pBNYvPhfR7wd+/e7/OwXvNxpPLwo/Fu8+qsDvP5Ut7v/f588o6iJPPJioDwEp5U81sU1PGZOajwuzJQ8mqekPGJ6GTyCvwY8UEsHCA4shw6gAAAAoAAAAFBLAwQAAAgIAAAAAAAAAAAAAAAAAAAAAAAADgAkAGFyY2hpdmUvZGF0YS80RkIgAFpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpajurkM6k00TM7be4zeaHKMxRcfDPo8OAzVdD/M83zFzReLIUzJTVUM18kZzW56Vc0EJVoNTV9QzXdh6s0PSURNa8rGTWJn301WuPGNKvdVzTZKPk2L+byNV6V+TaESeA2WBwINrJcazak4a82s97xNuv3Ezb8eqI1138jN/HN2TaB7yU3PlsNN/6MWzYizL02ya0RN9ZINjcpkyE2kiD9NVBLBwi/nphXoAAAAKAAAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAAA4AJABhcmNoaXZlL2RhdGEvNUZCIABaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWgAAoEFQSwcI8xKYjgQAAAAEAAAAUEsDBAAACAgAAAAAAAAAAAAAAAAAAAAAAAAOAEAAYXJjaGl2ZS9kYXRhLzZGQjwAWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpazyrmOb2mpbtImju8bMTgvFBLBwi6l+SPEAAAABAAAABQSwMEAAAICAAAAAAAAAAAAAAAAAAAAAAAAA4ANABhcmNoaXZlL2RhdGEvN0ZCMABaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlrlRC401bI1NdoGdDZRd403UEsHCJQDIgUQAAAAEAAAAFBLAwQAAAgIAAAAAAAAAAAAAAAAAAAAAAAADwAzAGFyY2hpdmUvdmVyc2lvbkZCLwBaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWjMKUEsHCNGeZ1UCAAAAAgAAAFBLAQIAAAAACAgAAAAAAADfr70kfAUAAHwFAAAQAAAAAAAAAAAAAAAAAAAAAABhcmNoaXZlL2RhdGEucGtsUEsBAgAAAAAICAAAAAAAAKYqnm+gAAAAoAAAAA4AAAAAAAAAAAAAAAAAzAUAAGFyY2hpdmUvZGF0YS8wUEsBAgAAAAAICAAAAAAAACIQEugQAAAAEAAAAA4AAAAAAAAAAAAAAAAAsAYAAGFyY2hpdmUvZGF0YS8xUEsBAgAAAAAICAAAAAAAAPMSmI4EAAAABAAAAA4AAAAAAAAAAAAAAAAAIAcAAGFyY2hpdmUvZGF0YS8yUEsBAgAAAAAICAAAAAAAAA4shw6gAAAAoAAAAA4AAAAAAAAAAAAAAAAAlAcAAGFyY2hpdmUvZGF0YS8zUEsBAgAAAAAICAAAAAAAAL+emFegAAAAoAAAAA4AAAAAAAAAAAAAAAAAsAgAAGFyY2hpdmUvZGF0YS80UEsBAgAAAAAICAAAAAAAAPMSmI4EAAAABAAAAA4AAAAAAAAAAAAAAAAAsAkAAGFyY2hpdmUvZGF0YS81UEsBAgAAAAAICAAAAAAAALqX5I8QAAAAEAAAAA4AAAAAAAAAAAAAAAAAFAoAAGFyY2hpdmUvZGF0YS82UEsBAgAAAAAICAAAAAAAAJQDIgUQAAAAEAAAAA4AAAAAAAAAAAAAAAAAoAoAAGFyY2hpdmUvZGF0YS83UEsBAgAAAAAICAAAAAAAANGeZ1UCAAAAAgAAAA8AAAAAAAAAAAAAAAAAIAsAAGFyY2hpdmUvdmVyc2lvblBLBgYsAAAAAAAAAB4DLQAAAAAAAAAAAAoAAAAAAAAACgAAAAAAAABbAgAAAAAAAJILAAAAAAAAUEsGBwAAAADtDQAAAAAAAAEAAABQSwUGAAAAAAoACgBbAgAAkgsAAAAA",
