### ISSUE TITLE
关于 match_id 和 id_list 的用法，我理解是match_id 是可以指定某一列作为匹配 key？

### ISSUE THREAD

**Issue by DongRuiHust** [FederatedAI/FATE#4749]
我理解 with_match_id=True 是能够指定匹配的 id，match_id_name="xxx" 是指定具体的匹配 id，但我通过实操发现，他依旧是使用 id 列作为匹配key。

数据上传代码如下：
config="../../config.yaml"
namespace=""
if isinstance(config, str):
    config = load_job_config(config)
parties = config.parties
guest = parties.guest[0]
host = parties.host[0]
data_base = config.data_base_dir

dense_data = {"name": "breast_hetero_guest", "namespace": f"experiment{namespace}"}
pipeline_upload = PipeLine().set_initiator(role="guest", party_id=guest).set_roles(guest=guest)
pipeline_upload.add_upload_data(file=os.path.join(data_base, "examples/data/breast_hetero_guest.csv"),
                                    table_name=dense_data["name"],             # table name
                                    namespace=dense_data["namespace"],         # namespace
                                    head=1, partition=4,               # data info
                                    extend_sid=True,
                                    with_match_id=True,
                                    auto_increasing_sid=True,
                                    id_list=["id","x0"],
                                    id_delimiter=",")
pipeline_upload.upload(drop=1)

求带代码为：
guest_train_data = {"name": "breast_hetero_guest", "namespace": "experiment"}
host_train_data = {"name": "breast_hetero_host", "namespace": "experiment"}

reader_0 = Reader(name="reader_0")
reader_0.get_party_instance(role='guest', party_id=guest).component_param(table=guest_train_data)
reader_0.get_party_instance(role='host', party_id=host).component_param(table=host_train_data)

data_transform_0 = DataTransform(name="data_transform_0")
data_transform_0.get_party_instance(role='guest', party_id=guest).component_param(with_label=True, with_match_id=True, match_id_name="x0")
data_transform_0.get_party_instance(role='host', party_id=host).component_param(with_label=False, with_match_id=True, match_id_name="x0")
intersection_0 = Intersection(name="intersection_0")

pipeline = PipeLine().set_initiator(role='guest', party_id=guest).set_roles(guest=guest, host=host)
pipeline.add_component(reader_0)
pipeline.add_component(data_transform_0, data=Data(data=reader_0.output.data))
pipeline.add_component(intersection_0, data=Data(data=data_transform_0.output.data))
pipeline.compile()
pipeline.fit()

**Comment by mgqa34** [comment]
upload的设置有问题，id_list应该放到meta阈下面，同时激活with_meta字段，可以参考：https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_multiple_id_columns.ipynb

**Comment by DongRuiHust** [comment]
> upload的设置有问题，id_list应该放到meta阈下面，同时激活with_meta字段，可以参考：https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_multiple_id_columns.ipynb

感谢~

**Comment by DongRuiHust** [comment]
> > upload的设置有问题，id_list应该放到meta阈下面，同时激活with_meta字段，可以参考：https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_multiple_id_columns.ipynb
> 
> 感谢~

你好，我按照案例中的代码进行运行，却出现如下错误导致上传数据失败，请问是什么原因呢？
代码：
fate_project_base="/data/projects/fate"
guest_data_path = fate_project_base + "/examples/data/guest_multi_id_columns.csv"

with open(guest_data_path, "w") as fout:
    fout.write("phone,device_id,seq_id,x0\n10000,device_a,seq_1,0\n10002,device_b,seq_3,1\n10004,device_c,seq_5,2\n")
    fout.write("10006,device_d,seq_7,4\n10008,device_e,seq_9,5\n100010,device_f,seq_11,6\n100012,device_g,seq_13,7\n")
    fout.write("100014,device_h,seq_15,8\n100016,device_i,seq_17,9\n100018,device_j,seq_19,10\n")
from pipeline.backend.pipeline import PipeLine
pipeline_upload = PipeLine().set_initiator(role="guest", party_id=9999).set_roles(guest=9999)
guest_data_meta = {"delimiter": ",", "with_label": False,
                   "input_format": "dense", "data_type": "int",
                   "with_match_id": True,                 # with_match_id should be true
                   "id_list": ["phone","device_id","seq_id"]} # id_list specifies the id columns
multi_id_guest = {"name": "multi_id_guest", "namespace": f"experiment"}
pipeline_upload.add_upload_data(file=guest_data_path,
                                table_name=multi_id_guest["name"],         
                                namespace=multi_id_guest["namespace"],         
                                head=1, partition=4,
                                extend_sid=True,                      # upload data with automatically append sample id
                                with_meta=True, meta=guest_data_meta) # with_meta=True means uploading data with meta 
pipeline_upload.upload(drop=1)

报错：
1530
        "extend_sid": 1,
1531
        "auto_increasing_sid": 0,
1532
        "block_size": 1,
1533
        "schema": {},
1534
        "with_meta": true,
1535
        "meta": {
1536
            "input_format": "dense",
1537
            "delimiter": ",",
1538
            "tag_with_value": false,
1539
            "tag_value_delimiter": ":",
1540
            "with_match_id": true,
1541
            "id_list": [
1542
                "phone",
1543
                "device_id",
1544
                "seq_id"
1545
            ],
1546
            "id_range": 0,
1547
            "data_type": "int",
1548
            "with_label": false
1549
        },
1550
        "_name": "Upload#upload_0"
1551
    },
1552
1553
}
[INFO] [2023-04-06 07:16:54,345] [202304060715477185670] [100812:140295113803584] - [task_executor._run_] [line:159]: task input dsl {}
1555
[INFO] [2023-04-06 07:16:54,345] [202304060715477185670] [100812:140295113803584] - [task_executor._run_] [line:208]: profile logging is disabled
1556
[INFO] [2023-04-06 07:16:54,345] [202304060715477185670] [100812:140295113803584] - [upload._run] [line:127]: {'file': '/data/projects/fate/fateflow/jobs/202304060715477185670/fate_upload_tmp/da857e0ed44a11ed835c4e87ee18d199', 'head': 1, 'id_delimiter': ',', 'partition': 4, 'namespace': 'experiment', 'name': 'multi_id_guest', 'storage_engine': '', 'storage_address': None, 'destroy': True, 'extend_sid': 1, 'auto_increasing_sid': 0, 'block_size': 1, 'schema': {}, 'with_meta': True, 'meta': {'input_format': 'dense', 'delimiter': ',', 'tag_with_value': False, 'tag_value_delimiter': ':', 'with_match_id': True, 'id_list': ['phone', 'device_id', 'seq_id'], 'id_range': 0, 'data_type': 'int', 'with_label': False}, '_name': 'Upload#upload_0'}
1557
[INFO] [2023-04-06 07:16:54,355] [202304060715477185670] [100812:140295113803584] - [_session.save_record] [line:343]: try to save session record for manager 202304060715477185670_upload_0_5_local_0, storage EGGROLL 202304060715477185670_upload_0_5_local_0_storage_023d28f2-d44b-11ed-b8f7-4e87ee18d199
1558
[INFO] [2023-04-06 07:16:54,357] [202304060715477185670] [100812:140295113803584] - [_session.save_record] [line:363]: save session record for manager 202304060715477185670_upload_0_5_local_0, storage EGGROLL 202304060715477185670_upload_0_5_local_0_storage_023d28f2-d44b-11ed-b8f7-4e87ee18d199 successfully
[INFO] [2023-04-06 07:16:55,846] [202304060715477185670] [100812:140295113803584] - [upload._run] [line:184]: destroy table name: multi_id_guest namespace: experiment engine: EGGROLL
1560
[INFO] [2023-04-06 07:16:55,864] [202304060715477185670] [100812:140295113803584] - [upload._run] [line:230]: upload to EGGROLL storage, address: {'cores_per_node': 16, 'nodes': 2, 'name': 'multi_id_guest', 'namespace': 'experiment', 'storage_type': 'LMDB'}
1561
[INFO] [2023-04-06 07:16:55,872] [202304060715477185670] [100812:140295113803584] - [upload.update_table_schema] [line:358]: data head: phone,device_id,seq_id,x0
[INFO] [2023-04-06 07:16:55,877] [202304060715477185670] [100812:140295113803584] - [upload.upload_file] [line:308]: None
1564
[INFO] [2023-04-06 07:16:55,877] [202304060715477185670] [100812:140295113803584] - [control_client.update_job] [line:25]: request update job 202304060715477185670 on local 0
1565
[INFO] [2023-04-06 07:16:56,013] [202304060715477185670] [100812:140295113803584] - [upload.upload_file] [line:308]: None
1566
[INFO] [2023-04-06 07:16:56,053] [202304060715477185670] [100812:140295113803584] - [upload.generate_anonymous_schema] [line:349]: computing table schema: {'header': 'phone,device_id,seq_id,x0', 'sid': 'extend_sid', 'meta': {'input_format': 'dense', 'delimiter': ',', 'tag_with_value': False, 'tag_value_delimiter': ':', 'with_match_id': True, 'id_list': ['phone', 'device_id', 'seq_id'], 'id_range': 0, 'data_type': 'int', 'with_label': False}}
1567
[ERROR] [2023-04-06 07:16:56,056] [202304060715477185670] [100812:140295113803584] - [task_executor._run_] [line:265]: module 'federatedml' has no attribute 'None'
Traceback (most recent call last):
1569
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
1570
    cpn_output = run_object.run(cpn_input)
1571
  File "/data/projects/fate/fateflow/python/fate_flow/components/_base.py", line 156, in run
1572
    self._run(cpn_input=cpn_input)
1573
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 238, in _run
1574
    data_table_count = self.save_data_table(job_id, name, namespace, head)
1575
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 273, in save_data_table
1576
    metas_info.update({"schema": self.generate_anonymous_schema()})
1577
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 352, in generate_anonymous_schema
1578
    schema.update(AnonymousGenerator.generate_header(computing_table, schema))
1579
  File "/data/projects/fate/fateflow/python/fate_flow/manager/data_manager.py", line 97, in generate_header
1580
    obj = env_utils.get_class_object("data_format")
1581
  File "/data/projects/fate/fateflow/python/fate_flow/component_env_utils/env_utils.py", line 53, in get_class_object
1582
    class_obj = get_provider_class_object(provider, class_name)
1583
  File "/data/projects/fate/fateflow/python/fate_flow/component_env_utils/provider_utils.py", line 43, in get_provider_class_object
1584
    return getattr(importlib.import_module(".".join(class_path[:-1])), class_path[-1])
1585
AttributeError: module 'federatedml' has no attribute 'None'
