### ISSUE TITLE
model has not been deployed 

### ISSUE THREAD

**Issue by zdarktknight** [FederatedAI/FATE#4754]
我使用FATE 在对example进行预测时，明明部署成功，却不能预测，请问这个情况该如何解决呢？

FATE版本是1.10.0,  v2版本在进行预测的时候，要求先进行部署模型，然后预测，
`flow model deploy --model-id "arbiter-10000#guest-9999#host-10000#model" --model-version "202304050648416414790"`

看到返回部署的msg是成功的，但是当进行预测的时候，
`flow job submit -c examples/dsl/v2/homo_logistic_regression/predict_conf_20230405085541.json -d examples/dsl/v2/homo_logistic_regression/predict_dsl_20230405085529.json`
却报错说模型没有部署，
"retmsg": "Traceback (most recent call last):\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py\", line 88, in submit\n    raise Exception(f\"model has not been deployed yet\")\nException: model has not been deployed yet\n"

![issue](https://user-images.githubusercontent.com/8602335/230047447-7d65987e-cd30-4b54-8f7d-c3f46b706956.png)

**Comment by mgqa34** [comment]
Deploy后返回新的预测model_id/version，请确认是匹配的，图片中的2023***3670
