### ISSUE TITLE
请问eggroll_meta中的表是什么时候创建的？

### ISSUE THREAD

**Issue by FFinchR** [FederatedAI/FATE#4755]
使用的KubeFATE部署的FATE，服务重启后，MySQL中的表只剩下：
![image](https://user-images.githubusercontent.com/61258341/230265465-c2f0518e-319e-4102-955b-01671e7c1bc4.png)

另一个运行正常的集群：
![image](https://user-images.githubusercontent.com/61258341/230265655-30a00349-4e58-4680-913e-4a22eabe4143.png)

想请问一下，这些表是在什么时候创建的？挂了之后要怎么在不重新部署整个集群的情况下恢复？

**Comment by yyf1986** [comment]
这个里面是分2个库的，一个是eggroll的 一个是fatelfow的。初始话的时候eggroll就初始化了。fateflow的库是在python的容器在启动的时候创建的。（python的orm框架peewee）
