### ISSUE TITLE
HeteroNN 中的  Interactive layer 得到的结果是无损的吗? 无损的Za 会不会有隐私泄露的风险?

### ISSUE THREAD

**Issue by yixing5** [FederatedAI/FATE#4756]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by talkingwallace** [comment]
interactive_layer得到的结果，具体是指的哪部分呢
