### ISSUE TITLE
请问有没有什么好的办法可以直接将tensorflow模型转为fate中使用的模型？或者有没有什么方法在fate中构造tensorflow模型

### ISSUE THREAD

**Issue by Buyi0514** [FederatedAI/FATE#4761]
请问有没有什么好的办法可以直接将tensorflow模型转为fate中使用的模型？或者有没有什么方法在fate中构造tensorflow模型。
谢谢！

**Comment by Timo9Madrid7** [comment]
Afte you build your model, you can use `model.to_json()` to generate `nn_define:`.
