### ISSUE TITLE
 TypeError: bad operand type for abs(): 'str'

### ISSUE THREAD

**Issue by dxy0202** [FederatedAI/FATE#4764]
**Describe the bug**
数据集中有一些特征是str类型的，我在上传数据的时候用exclusive_data_type说明了，但是我在训练的时候出现了TypeError: bad operand type for abs(): 'str'
![image](https://user-images.githubusercontent.com/92411690/230762633-29542613-b439-43f8-bf3e-66826075dca7.png)
此时我应该怎么做才能让它正常训练呢？

**Comment by talkingwallace** [comment]
Str类型没办法在线性模型使用的

**Comment by dxy0202** [comment]
> Str型未办法在线模型使用的

谢谢您的回复，有没有什么文档或者说明可以看一下的？
