### ISSUE TITLE
能否从上一次保存的 pkl 文件开始继续训练？

### ISSUE THREAD

**Issue by DongRuiHust** [FederatedAI/FATE#4766]
我用数据 A 训练了一个纵向联邦学习模型，并且保存了 pkl 文件。
现在我又有了新的数据 B，我可以在经过数据 A 训练后的 pkl 文件上继续训练吗？

**Comment by mgqa34** [comment]
这里说的pkl指的是pipeline训练后保存的文件？ 如果是的话，当前是不支持的。可以通过model_loader组件加载之前训练好的的模型，然后拉多一个新的训练组件出来去接收新数据并持续训练

**Comment by DongRuiHust** [comment]
> 这里说的pkl指的是pipeline训练后保存的文件？ 如果是的话，当前是不支持的。可以通过model_loader组件加载之前训练好的的模型，然后拉多一个新的训练组件出来去接收新数据并持续训练

@mgqa34 这个组件没有看到，请问能告知具体在哪吗？
