### ISSUE TITLE
提交训练任务报错 workmode.cluster:1

### ISSUE THREAD

**Issue by 0329-rosa** [FederatedAI/FATE#4767]
用fate1.4.4训练模型，提交训练任务时报错retcode100 the following arguments are required :work_mode=<WorkMode.Cluster:1> WorkMode.Standalone:0>
搜了一下也没发现解决方案，请问这是怎么回事呢？

**Comment by mgqa34** [comment]
可以在release_history里面找对应版本的配置教程，1.4.4的版本job_parameters是需要填写work_mode/backend的，而新的版本是不需要的，应该是不同版本的配置错位了
