### ISSUE TITLE
集群版 fate 中 tensorflow 环境是需要自己装吗？

### ISSUE THREAD

**Issue by DongRuiHust** [FederatedAI/FATE#4784]
如图所示，我安装的集群版 fatev1.10.0 中，没有 tensorflow 的环境。
请问是要自己 pip install tensorflow-cpu=2.9.3 吗？
![image](https://user-images.githubusercontent.com/50562511/231806829-478aa36a-d324-4505-8152-00e582a6d052.png)

**Comment by Newer2019** [comment]
allinone的安装包里面有tf，其余版本可能需要自己装吧

**Comment by yyf1986** [comment]
你进到venv里面去没？
