### ISSUE TITLE
单元测试出现错误：lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument

### ISSUE THREAD

**Issue by LinkWithMe** [FederatedAI/FATE#4789]
**Describe the bug**
单元测试出现错误：lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument

**To Reproduce**
1. 单机版安装1.11.0/1.10.0/1.9.2都出现了错误
2. 安装完毕后进行单元测试
3. 出现错误

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/57388780/232435666-35d569bb-6ac1-4f06-9e83-1ff36102e131.png)

**Desktop (please complete the following information):**
 - OS: CenetOS7,8核CPU，64GB内存

**Comment by LinkWithMe** [comment]
已解决，发现是根据安装包陪环境的问题，若通过docker则无该问题产生

**Comment by Junyi-99** [comment]
I am also facing this problem when using Docker.

**Comment by amyseoj1** [comment]
Hi, has anyone resolved this issue ?
