### ISSUE TITLE
libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by pmpleader** [FederatedAI/FATE#4790]
fate v1.10 on spark 3.3.1:
==========================================

[ERROR] [2023-04-17 17:31:11,603] [202304171712454149180] [2089985:70373398965264] - [task_executor._run_] [line:265]: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
2
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 25.0 failed 4 times, most recent failure: Lost task 2.3 in stage 25.0 (TID 66) (enode-0001 executor 1): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
3
  File "/root/compile/venv/venv-py3.8/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 48, in <module>
4
    from ._check_build import check_build  # noqa
5
ImportError: /root/compile/venv/venv-py3.8/lib/python3.8/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

=========================================
>>> import sklearn; sklearn.show_versions()

System:
    python: 3.8.11 (default, Apr 12 2023, 12:00:53)  [GCC 9.1.0]
executable: /usr/local/bin/python3
   machine: Linux-4.19.90-24.4.v2101.ky10.aarch64-aarch64-with-glibc2.17

Python dependencies:
      sklearn: 1.2.2
          pip: 23.1
   setuptools: 50.3.2
        numpy: 1.23.1
        scipy: 1.10.1
       Cython: None
       pandas: 1.1.5
   matplotlib: None
       joblib: 1.2.0
threadpoolctl: 3.1.0

Built with OpenMP: True

threadpoolctl info:
       user_api: openmp
   internal_api: openmp
         prefix: libgomp
       filepath: /usr/lib64/libgomp.so.1.0.0
        version: None
    num_threads: 16

       user_api: openmp
   internal_api: openmp
         prefix: libgomp
       filepath: /usr/local/lib/python3.8/site-packages/scikit_learn.libs/libgomp-d22c30c5.so.1.0.0
        version: None
    num_threads: 16

       user_api: blas
   internal_api: openblas
         prefix: libopenblas
       filepath: /usr/local/lib/python3.8/site-packages/numpy.libs/libopenblas64_p-r0-9c1f2efe.3.20.so
        version: 0.3.20
threading_layer: pthreads
   architecture: armv8
    num_threads: 16

       user_api: blas
   internal_api: openblas
         prefix: libopenblas
       filepath: /usr/local/lib/python3.8/site-packages/scipy.libs/libopenblasp-r0-dff490c2.3.18.so
        version: 0.3.18
threading_layer: pthreads
   architecture: armv8
    num_threads: 16

**Comment by langkcc** [comment]
请问问题解决了吗？我也遇到了一样的问题。

**Comment by langkcc** [comment]
let me off this issue. 
My env is fate on eggroll.
add environment: export LD_PRELOAD="/usr/local/python3/lib/python3.8/site-packages/scikit_learn.libs/libgomp-d22c30c5.so.1.0.0"
on fateflow and nodemanager.

**Comment by pmpleader** [comment]
此类问题，配置正确的环境变量就可以解决；export LD_PRELOAD=
放到正确的配置文件中；
