### ISSUE TITLE
关于hetero_nn模块的host方数量问题

### ISSUE THREAD

**Issue by AwinChen** [FederatedAI/FATE#4791]
您好，请问目前纵向联邦神经网络模块的host方可以支持多少client？看到heteroNN的框架图介绍好像只看到支持1个host端和1个guest端的

**Comment by AwinChen** [comment]
如果支持多方host，具体的操作有哪些参考的教程吗？（目前使用的是FATE1.9版本）

**Comment by talkingwallace** [comment]
多个host的话得到1.10版本才能支持了

**Comment by AwinChen** [comment]
> 多个host的话得到1.10版本才能支持了

我重新安装了1.10版本，面对多个host方的Hetero_NN的场景部署教程有可以参考的吗？非常感谢回复

**Comment by DingDante** [comment]
> > 多个host的话得到1.10版本才能支持了
> 
> 我重新安装了1.10版本，面对多个host方的Hetero_NN的场景部署教程有可以参考的吗？非常感谢回复

hetero_NN 有多host方conf配置文件

**Comment by Newer2019** [comment]
> > > 多个host的话得到1.10版本才能支持了
> > 
> > 
> > 我重新安装了1.10版本，面对多个host方的Hetero_NN的场景部署教程有可以参考的吗？非常感谢回复
> 
> hetero_NN 有多host方conf配置文件

哪个是，没找到哇
