### ISSUE TITLE
安装包过大怎么破？

### ISSUE THREAD

**Issue by Newer2019** [FederatedAI/FATE#4797]
集群版本，安装后大概6GB，看了一下目录结构

里面python各种包占了3GB，torch和tensorflow就占了1.5GB
mysql的文件夹 占了 1.8GB，其中两个文件 mysqld 和 mysqld-debug 各占500MB

如何能够精简一下空间占用？

**Comment by zhihuiwan** [comment]
请问下是哪个版本？

**Comment by Newer2019** [comment]
1.10

**Comment by yyf1986** [comment]
安装包大，可以保证离线安装成功。或者你可以自己安装python的环境，下载python的依赖。用自有的mysql也是可以的。

**Comment by sagewe** [comment]
这些都是该版本的必要依赖，如果不使用某些功能确实可以进行一定程度的精简。
很抱歉我们无法同时维护太多版本的安装包，如果有特殊需求，可以考虑自己进行打包或者精简。
如果你觉得你的需求足够广泛，请详细描述你的场景和需求的必要性，我们可以做进一步的考虑！
