### ISSUE TITLE
安装allinone集群版一定要设置无密登录吗？

### ISSUE THREAD

**Issue by Newer2019** [FederatedAI/FATE#4798]
guest-host 两方部署为例
我是否可以分别下载安装guest和host，再配置下另一方的ip？

无密登录在运行时还需要吗？

**Comment by mgqa34** [comment]
可以的，改allInOne的setup配置，让它只部署自己一方，guest\host分别执行下，部署完成后，双方手工在eggroll/conf/route_table.json下面加对方的ip就行

**Comment by yyf1986** [comment]
使用allinone的话方便点。后期可以自己重写安装的。
