### ISSUE TITLE
ModuleNotFoundError: No module named 'pipeline'

### ISSUE THREAD

**Issue by 1170300814** [FederatedAI/FATE#4816]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 1
----> 1 from pipeline.component.nn import save_to_fate

ModuleNotFoundError: No module named 'pipeline'

sunddenly it can't run it

**Comment by mgqa34** [comment]
Please may sure package "fate-client" has been installed

**Comment by 1170300814** [comment]
> Please make sure package "fate-client" has been installed

i am sure i have installed it
