### ISSUE TITLE
训练过程设置验证频率，fateboard  log      eval summary  is  { iteration_ },  这里的iteration_应该为epoch_吧，具体为eval summary is {'iteration_79': {'train': {'auc': /1.10.0版本

### ISSUE THREAD

**Issue by DingDante** [FederatedAI/FATE#4818]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mgqa34** [comment]
跑的是哪个算法呢？ BTW: iteration可以理解为等价于epoch，只是命名风格的问题，为了对齐所有算法的展示，fate在fateboard上用iteration来统一风格
