### ISSUE TITLE
v1.11.1standalone中没有FATE-LLM吗？

### ISSUE THREAD

**Issue by donkeynextdoor** [FederatedAI/FATE#4820]
必须安装集群版才可以吗

**Comment by mgqa34** [comment]
集群版和单机版的代码都是一样的，可以参考教程:
https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_llm/README.md

**Comment by donkeynextdoor** [comment]
> 集群版和单机版的代码都是一样的，可以参考教程: https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_llm/README.md

可是单机版无法使用pipeline啊，不是只有安装集群吧才能使用jupyter notebook么

**Comment by mgqa34** [comment]
> > 集群版和单机版的代码都是一样的，可以参考教程: https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_llm/README.md
> 
> 可是单机版无法使用pipeline啊，不是只有安装集群吧才能使用jupyter notebook么

单机版也有pipeline的哦，你意思是使用jupyter notebook吗？这个直接pip install jupyter装一下就行
