### ISSUE TITLE
v1.11 FATE-LLM的硬件需求是什么？

### ISSUE THREAD

**Issue by donkeynextdoor** [FederatedAI/FATE#4821]
之前看到介绍说一个节点使用了两台V100，是否可以尽快更新一下最新的部署说明，谢谢

**Comment by mgqa34** [comment]
如果希望使用GPU资源，只要部署后的环境可以访问GPU卡即可，可以参考链接中"Training with CUDA"和"Training with multiple GPUs"一节
https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_llm/GPT2-example.ipynb

**Comment by donkeynextdoor** [comment]
> 如果希望使用GPU资源，只要部署后的环境可以访问GPU卡即可，可以参考链接中"Training with CUDA"和"Training with multiple GPUs" https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/fate_llm/GPT2-example.ipynb

那么请问有推荐的硬件资源列表么

**Comment by dylan-fan** [comment]
可以考虑用v100
