### ISSUE TITLE
纵向联邦训练场景，由于数据只训练一个 epoch，如何设置每训练 n 个 batch_size 后输出当前的 AUC 指标？

### ISSUE THREAD

**Issue by DongRuiHust** [FederatedAI/FATE#4825]
纵向联邦学习训练场景，数据只需训练一个 epoch
请问如何设置在训练过程中，每经过 n（假设为 100） 个batch_size 便输出当前 batch 的 auc 指标？

**Comment by talkingwallace** [comment]
目前暂时不支持这样的输出的 只能一个epoch输出

**Comment by DongRuiHust** [comment]
> 目前暂时不支持这样的输出的 只能一个epoch输出

感谢解答~
