### ISSUE TITLE
The uploaded file is incomplete

### ISSUE THREAD

**Issue by ado-cs** [FederatedAI/FATE#4826]
I tried both pipeline and DSL to upload csv files. As a result, the uploaded files on server were incomplete with success job status.

I uploaded two csv files, each file has 31315 rows of data. Then I checked the fate board, one file had 23904 rows of data file and the other one only got 2 rows of data remain.
The column seperator of my csv files was ',' and the row seperator was '\n'.

There was one warning in logs:
[WARNING] [2023-04-24 00:03:53,132] [202304240003504005100] [89:140651782690624] - [job_default_config.load] [line:61]: job default config not supported upload_max_bytes

Configuration:
{
  "file": "data/train_guest.csv",
  "table_name": "train_guest",
  "namespace": "telecom_fraud",
  "head": 1,
  "partition": 4
}

Fate version: 1.10.0-release
Serving version: 2.1.6-release
Docker version: 23.0.4
Docker-Compose version: 1.27.4

Runtime config:
```
{
	"job_parameters":{
		"common":{
			"job_type":"train",
			"model_version":"202304240118424183300",
			"pulsar_run":{},
			"auto_retries":0,
			"computing_engine":"EGGROLL",
			"model_id":"local-0#model",
			"task_parallelism":1,
			"rabbitmq_run":{},
			"engines_address":{},
			"computing_partitions":4,
			"federated_status_collect_type":"PUSH",
			"inheritance_info":{},
			"auto_retry_delay":1,
			"adaptation_parameters":{
				"request_task_cores":4,
				"task_cores_per_node":4,
				"task_nodes":1,
				"if_initiator_baseline":true,
				"task_memory_per_node":0
			},
			"eggroll_run":{},
			"spark_run":{},
			"federated_mode":"SINGLE"
		}
	},
	"component_parameters":{
		"role":{
			"local":{
				"0":{
					"upload_0":{
						"head":1,
						"file":"/data/projects/fate/fateflow/jobs/202304240118424183300/fate_upload_tmp/9ffaad54e27811ed955f0242c0a70064",
						"partition":4,
						"name":"train_guest",
						"namespace":"telecom_fraud",
						"destroy":true
					}
				}
			}
		}
	},
	"dsl_version":2,
	"role":{
		"local":[
			0
		]
	},
	"initiator":{
		"role":"local",
		"party_id":0
	}
}
```

**Comment by mgqa34** [comment]
Please have a check to see if data has duplicated keys(first column) or not.

**Comment by ado-cs** [comment]
Well, I see. I found nothing about the format requirements for the data on Fate documentation.
Thx!
