### ISSUE TITLE
请教，hetero_NN 中的predicting问题

### ISSUE THREAD

**Issue by DingDante** [FederatedAI/FATE#4827]
604 [INFO] [2023-04-24 16:30:40,072] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: get encrypted dense output of host model of epoch 0 batch 0
605 [INFO] [2023-04-24 16:30:40,820] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: start to get interactive layer's activation output of epoch 0 batch 0
605 [INFO] [2023-04-24 16:30:40,820] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: start to get interactive layer's activation output of epoch 0 batch 0
606 [INFO] [2023-04-24 16:30:45,174] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:529]: get encrypted weight gradient of epoch 0 batch 0
606 [INFO] [2023-04-24 16:30:45,174] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:529]: get encrypted weight gradient of epoch 0 batch 0
607 [INFO] [2023-04-24 16:30:45,320] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:548]: get decrypted weight graident of epoch 0 batch 0
607 [INFO] [2023-04-24 16:30:45,320] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:548]: get decrypted weight graident of epoch 0 batch 0
608 [INFO] [2023-04-24 16:30:45,744] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: interactive layer running forward propagation epoch 0 batch 1
608 [INFO] [2023-04-24 16:30:45,744] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: interactive layer running forward propagation epoch 0 batch 1
609 [INFO] [2023-04-24 16:30:46,365] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: get encrypted dense output of host model of epoch 0 batch 1
610 [INFO] [2023-04-24 16:30:46,947] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: start to get interactive layer's activation output of epoch 0 batch 1
611 [INFO] [2023-04-24 16:30:46,990] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:529]: get encrypted weight gradient of epoch 0 batch 1
612 [INFO] [2023-04-24 16:30:47,138] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:548]: get decrypted weight graident of epoch 0 batch 1
613 [INFO] [2023-04-24 16:30:47,569] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: interactive layer running forward propagation epoch 0 batch 2
614 [INFO] [2023-04-24 16:30:48,300] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: get encrypted dense output of host model of epoch 0 batch 2
615 [INFO] [2023-04-24 16:30:48,987] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: start to get interactive layer's activation output of epoch 0 batch 2
616 [INFO] [2023-04-24 16:30:49,136] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:529]: get encrypted weight gradient of epoch 0 batch 2
617 [INFO] [2023-04-24 16:30:49,298] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:548]: get decrypted weight graident of epoch 0 batch 2
618 [INFO] [2023-04-24 16:30:49,737] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: interactive layer running forward propagation epoch 0 batch 3
619 [INFO] [2023-04-24 16:30:50,155] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: get encrypted dense output of host model of epoch 0 batch 3
620 [INFO] [2023-04-24 16:30:50,568] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:354]: start to get interactive layer's activation output of epoch 0 batch 3
621 [INFO] [2023-04-24 16:30:50,673] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:529]: get encrypted weight gradient of epoch 0 batch 3
622 [INFO] [2023-04-24 16:30:50,768] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.backward_interactive] [line:548]: get decrypted weight graident of epoch 0 batch 3
623 [INFO] [2023-04-24 16:30:51,123] [202304241630082167620] [130358:139627842791232] - [tracker_client.log_metric_data_common] [line:69]: Request save job 202304241630082167620 task 202304241630082167620_hetero_nn_0 0 on guest 9999 metric train loss data
624 [INFO] [2023-04-24 16:30:51,166] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, interactive layer running forward propagation pred iteration 0 batch 0
625 [INFO] [2023-04-24 16:30:51,686] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, get encrypted dense output of host model of pred iteration 0 batch 0
626 [INFO] [2023-04-24 16:30:52,309] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, start to get interactive layer's activation output of pred iteration 0 batch 0
627 [INFO] [2023-04-24 16:30:52,461] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, interactive layer running forward propagation pred iteration 1 batch 0
628 
629 [INFO] [2023-04-24 16:30:53,400] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, start to get interactive layer's activation output of pred iteration 1 batch 0
631 [INFO] [2023-04-24 16:30:53,865] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, get encrypted dense output of host model of pred iteration 2 batch 0
633 [INFO] [2023-04-24 16:30:54,538] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, interactive layer running forward propagation pred iteration 3 batch 0
635 [INFO] [2023-04-24 16:30:55,091] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, start to get interactive layer's activation output of pred iteration 3 batch 0
640 [INFO] [2023-04-24 16:30:56,249] [202304241630082167620] [130358:139627842791232] - [he_interactive_layer.print_log] [line:357]: predicting, get encrypted dense output of host model of pred iteration 5 batch 0
==================================================================================
在hetero_NN中训练过程设置验证频率=10，batch_num=4。而在fateboard实际显示中，每个epoch都会有predicting, predicting的作用是什么，并且对iteration 0  到 iteration 5存在疑惑

**Comment by talkingwallace** [comment]
这个应该是传输的时候复用了变量，或者是log有错误 我们这边检查一下
