### ISSUE TITLE
What pipeline.component.HomoNN's `epoch` paramester really mean?

### ISSUE THREAD

**Issue by jiengup** [FederatedAI/FATE#4835]
Hi there
I have a question about `pipeline.component.HomoNN`'s fedavg training behavior.
Is it's paramester `epoch` mean **communication round**(aggregation round) or **local training round**?
As I notice 'pipeline.component.HeteroFTL` class has an attribute `local_round`(although I don't find where it is used) 
I guess if I set the pipeline(1 host, 1 guest, epoch=50) as below:
```python
pipeline = PipeLine().set_initiator(role='guest', party_id=GUEST).set_roles(guest=GUEST,
                                                                                                                               host=HOST,
                                                                                                                               arbiter=ARBITER)
nn_component = HomoNN(name='nn',
                          model=model,
                          loss=t.nn.BCELoss(),
                          dataset = dataset_param,
                          optimizer=t.optim.Adam(model.parameters(), lr=5e-4),
                          trainer=TrainerParam(trainer_name='fedavg_trainer',
                                               epochs=50,
                                               batch_size=32),
                          torch_seed=100)
pipeline.add_component(reader_0)
```
then the training process will consist of 50 rounds aggregation(communication between all participants)
and during each communication round each participant will train their local model with their own dataset **exactly once**(update local model once). Or each participant will train their local model 50 rounds and then aggregate?

**Comment by jiengup** [comment]
> 1. epoch parameter in the HomoNN is the local training round AND the aggregation round. By default, HomoNN will aggregate the model after finishing training an epoch
> 2. The local round in FTL is for communication efficient function.
>    :D

Thanks for your reply
So if I set epoch=50 then we will have 50 aggregation rounds and during each aggregation round each participant will train their local model 50 epoch right?

**Comment by talkingwallace** [comment]
Yes, you are right
