### ISSUE TITLE
官网案例信用卡欺诈任务提交失败

### ISSUE THREAD

**Issue by 0329-rosa** [FederatedAI/FATE#4837]
在训练官网记分卡案例时上传完数据后提交训练任务test_scorecard _job_conf.json 和dsl文件时报错信息为retcode 103，请问该如何解决？

**Comment by 0329-rosa** [comment]
报错信息如图
![Uploading 667DCB2B-160A-47DB-B1E2-3BAE97607908.png…]()

**Comment by 0329-rosa** [comment]
<img width="1267" alt="9BF6D32A-43D3-40F7-ABE7-78C5FC01D633" src="https://github.com/FederatedAI/FATE/assets/59122032/f30bbca8-fc0a-4263-8817-88d3e821d698">

**Comment by 0329-rosa** [comment]
> <img alt="9BF6D32A-43D3-40F7-ABE7-78C5FC01D633" width="1267" src="https://user-images.githubusercontent.com/59122032/237569073-f30bbca8-fc0a-4263-8817-88d3e821d698.png">

报错信息如图

**Comment by mgqa34** [comment]
Make sure arbiter's party_id != guest's party_id

**Comment by 0329-rosa** [comment]
> Make sure arbiter's party_id != guest's party_id
it worked!!thx a lot! I
