### ISSUE TITLE
运行Hadoop 数据存放过程中，发现在subprocess 会有无法连接的情况

### ISSUE THREAD

**Issue by xxl4** [FederatedAI/FATE#4838]
**Describe the bug**
我们使用hadoop做为数据第三方数据提供的时候，基于JOB做两方数据求交过程中，当程序运行到subprocess 过程中发现 CLASSPATH被None的情况，从而无法完成Hadoop的数据读取

![image](https://github.com/FederatedAI/FATE/assets/34465153/9cb1a156-8d29-467a-9759-520dbc0e827b)

在HDFS的 程序中无法连接到 Hadoop的数据内容

![image](https://github.com/FederatedAI/FATE/assets/34465153/bd5d6e20-a584-4b38-9a52-f7140e5154ef)

我们使用的是 fate 1.10 的版本。

帮忙看看，前面是基于什么考虑需要把CLASSPATH 配置为空的情况，在基于pyarrow 连接 Hadoop的时候，是会使用到这个变量。

后面我们取消这行代码后，就可以正常的跑JOB了。

![image](https://github.com/FederatedAI/FATE/assets/34465153/f114084f-c758-4310-97d3-cc830023cd7d)

**Screenshots**
![image](https://github.com/FederatedAI/FATE/assets/34465153/bd5d6e20-a584-4b38-9a52-f7140e5154ef)

**Comment by zhihuiwan** [comment]
您是指上传数据没问题但是读取失败了吗？

**Comment by zhihuiwan** [comment]
去掉了 CLASSPATH是因为在某些环境下CLASSPATH很长，甚至超出了subprocess参数的上限。我们测试发现pyarrow并不是强依赖CLASSPATH，之前也未出现类似的问题，怀疑可能和hadoop部署、环境、版本等内容相关，这个问题我们也会持续跟进，感谢您的反馈。
