### ISSUE TITLE
纵向联邦特征工程中的问题

### ISSUE THREAD

**Issue by dxy0202** [FederatedAI/FATE#4840]
请问：
1.特征插补的时候，分类的特征如何选择众数、中位数插补方法？
2.在特定的特征进行onehot编码前，如何将特征的数据类型转换为int或者str？

**Comment by mgqa34** [comment]
1. 特征插补指的是feature_imputation组件？该组件应该不支持众数、中位数
2. 可以在data_transform组件里面使用exclusive_data_type去指定onehot的列，设置相关类型为int/str

**Comment by dxy0202** [comment]
> 1. 特征插补指标的是feature_imputation组？该组应不支持人数、中位数
> 2. 可以在data_transform组里使用exclusive_data_type去指定onehot的列表，设置相关类型为int/str

感谢您的解答。
1.feature_imputation组件不支持众数、中位数的话，那对于分类特征的缺失值FATE中有没有组件可以进行填充（不是指定值的那种）？
2.根据您说的将相关类型设置为int/str的话是否可以将其他类型的类型转换为int/str类型？
