### ISSUE TITLE
fate_proxy在授权鉴权方面，怎么对联邦计算的数据获取，算法使用，使用时机，调用次数等进行授权，这部分的详细代码在哪里

### ISSUE THREAD

**Issue by YuChangF** [FederatedAI/FATE#4841]
比如host接收到了一个guest发送的job新增的请求，怎么鉴定这个job新增计算请求是合法的，是否是这个gust发送的，是否能进行这次联邦计算（也就是联邦计算逻辑是否被授权允许），是否能获取计算时所需要的数据。 这部分的详细代码在哪里

fate版本是1.10

**Comment by zhihuiwan** [comment]
在fate flow中有提供钩子，可以实现自定义钩子函数。
钩子入口在这里：https://github.com/FederatedAI/FATE-Flow/blob/v1.10.0/python/fate_flow/scheduling_apps/party_app.py#L30
默认钩子：
https://github.com/FederatedAI/FATE/blob/v1.10.0/conf/service_conf.yaml#L11
