### ISSUE TITLE
[WIP]implement algorithm volepsi

### ISSUE THREAD

**Issue by daydayuphere** [FederatedAI/FATE#4844]
https://github.com/Visa-Research/volepsi
类似的c++代码，如何移植到FATE算法组件里
有没有直接用c++代码的方法，因为里面还涉及很多三方库也是c代码，如果用python重写，代价有点大
麻烦老师指导下，谢谢

**Comment by talkingwallace** [comment]
可以考虑下用Python调用C++的办法
