### ISSUE TITLE
当我运行pipeline_tutorial_hetero_sbt时，报出此错误

### ISSUE THREAD

**Issue by zzwtop1** [FederatedAI/FATE#4845]
File /data/projects/fate/fate/python/fate_client/pipeline/utils/invoker/job_submitter.py:145, in JobInvoker.query_job(self, job_id, role, party_id)
    143     ret_code = result["retcode"]
    144     ret_msg = result["retmsg"]
--> 145     data = result["data"][0]
    146     return ret_code, ret_msg, data
    147 except ValueError:

IndexError: list index out of range

**Comment by talkingwallace** [comment]
这个应该是party id 配置上的问题

**Comment by zzwtop1** [comment]
是的，我试着更换初始化的ip和partyid，可以使用了
