### ISSUE TITLE
横向联邦推送到KF-Serving，需要自己写模型的预处理步骤吗？

### ISSUE THREAD

**Issue by FFinchR** [FederatedAI/FATE#4853]
我之前尝试过将横向的模型homo-convert到本地，然后发现需要完成如data_transform，scale等预处理步骤后，才能输入本地的模型，预测出正确结果。

![image](https://github.com/FederatedAI/FATE/assets/61258341/9a68ed5f-1fab-4bcc-bc87-a70e83c8c52f)

那么推送到KF-Serving的模型，是否也需要自己完成模型的预处理步骤？

**Comment by mgqa34** [comment]
当前支持的是训练模型的inference，如果用了特征工程组件的话，是需要自己完成入模前的预处理步骤的
