### ISSUE TITLE
预测任务failed

### ISSUE THREAD

**Issue by 0329-rosa** [FederatedAI/FATE#4855]
跑官网的信用卡案例，提交预测任务成功但fateboard显示任务失败，任务outputs里显示错误出现在hetero_lr_0这里，查看log输出也没搞懂是哪里不对？

**Comment by 0329-rosa** [comment]
![21D69908-FA41-4F76-BC27-BEB3143B974C](https://github.com/FederatedAI/FATE/assets/59122032/c78623d1-3e06-49a2-a259-60163014cbfa)
![98081EA7-F056-40F8-9859-8DB69106A26E](https://github.com/FederatedAI/FATE/assets/59122032/6c9286b1-a997-46d7-a415-4a97452d8d95)

**Comment by 0329-rosa** [comment]
![DDBA593B-A6C8-46AA-AD2A-7ABEAC4C2B6B](https://github.com/FederatedAI/FATE/assets/59122032/311645f3-c5c0-4927-af5c-8fca8900aa38)

**Comment by talkingwallace** [comment]
这个报错看不太清楚

**Comment by 0329-rosa** [comment]
> 这个报错看不太清楚
![12E80EBE-C8A7-47E6-B9F5-06B19B383890](https://github.com/FederatedAI/FATE/assets/59122032/bee9ee3a-32c1-4b87-98e8-f977b0167f4c)
