### ISSUE TITLE
hetero-nn模型自定义

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#4858]
1.请问是只有1.10版本支持hetero-nn里面layer的自定义吗？
2.目前1.10版本是否支持集群版本上，对hetero-nn layer自定义？看https://github.com/FederatedAI/FATE/blob/feature-1.10-nn-upgrade/%E6%95%99%E7%A8%8B/%E5%AE%89%E8%A3%85%E4%B8%8E%E6%95%B4%E4%BD%93%E4%BB%8B%E7%BB%8D.ipynb这个文档说的是只支持单机版

**Comment by talkingwallace** [comment]
支持的 文档是单机版是为了演示方便
