### ISSUE TITLE
关于 FATE-LLM 训练

### ISSUE THREAD

**Issue by pxyfxun** [FederatedAI/FATE#4863]
请问在进行 FATE-LLM 大模型训练时，对机器要求的最低配置有吗？比如要求CPU或者GPU最低多少G?

**Comment by talkingwallace** [comment]
这个要具体看运行模型的大小 如果是example的例子 一般有8g显存, 16G内存应该就可以本地跑起来

**Comment by pxyfxun** [comment]
> 这个要具体看运行模型的大小 如果是example的例子 一般有8g显存, 16G内存应该就可以本地跑起来

多谢解答
