### ISSUE TITLE
关于协调者的问题

### ISSUE THREAD

**Issue by LemonGitMin** [FederatedAI/FATE#4877]
请问fate联邦学习的算法组件中，有没有不需要协调者进行模型聚合和密钥分发的

**Comment by DingDante** [comment]
纵向联邦中的hetero_nn,  hetero_sshe_linr,  hetero_sshe_lr,是没有arbiter参与的

**Comment by talkingwallace** [comment]
HeteroSBT也是不需要的

**Comment by dyx0001** [comment]
@DingDante  涉及同态加密的算法中，arbiter是只向host发送同态加密的公钥么？
![paillier_cipher](https://github.com/FederatedAI/FATE/assets/132547242/d9f8ba33-f49c-4fe3-abaf-8f1276f60ec5)

**Comment by DingDante** [comment]
Arbiter公开公钥，私钥自身保存用于后续解密操作，host方获得公钥可以之间用加法或乘法同态性质在密文域计算，最后上传解密



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FederatedAI/FATE] 关于协调者的问题 (Issue #4877)




 
@DingDante  涉及同态加密的算法中，arbiter是只向host发送同态加密的公钥么？
 paillier_cipher.png (view on web)
