### ISSUE TITLE
如何加入或者脱离FATE

### ISSUE THREAD

**Issue by yang-shuaijun** [FederatedAI/FATE#4885]
**Describe the solution you'd like**
假设合作伙伴已经部署好了FATE，这个合作伙伴如何加入某公司已经部署好的FATE，在合作期满后，合作伙伴如何从公司的FATE环境剥离？

**Describe alternatives you've considered**

**Additional context**

**Comment by mgqa34** [comment]
从路由表中加入或者修改即可

**Comment by yang-shuaijun** [comment]
感谢抽出时间回复。
