### ISSUE TITLE
运行纵向xgb，千万样本量级，运行七个多小时的时候，出现通信错误

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#4886]
**运行纵向xgb，千万样本量级，运行七个多小时的时候，出现通信错误，请问是机器性能跟不上的原因吗？**

**报错如下：**
debug_error_string = "{"created":"@1685540881.228935796","description":"Error received from peer ipv4:xxx.xxx.xxx.xxx:37773","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Exception calling application: \n\n==== detail start, at 20230531.134801.185 ====\nTraceback (most recent call last):\n  File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 303, in run_task\n    self._run_unary(map_partitions_wrapper, task, shuffle=shuffle, reduce_op=reduce_op)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 119, in _run_unary\n    scatter_results = scatter_future.result()\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n    return list(f.result() for f in self._futures)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n    return list(f.result() for f in self._futures)\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result\n    return self.__get_result()\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\n  File "/data/projects/fate/eggroll/python/eggroll/core/datastructure/threadpool.py", line 51, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 154, in do_send_all\n    return CompositeFuture(send_all_futs).result()\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n    return list(f.result() for f in self._futures)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n    return list(f.result() for f in self._futures)\n  File "/opt/app-root/lib/python3.6/site-packages/grpc/_channel.py", line 303, in result\n    raise self\ngrpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1685539164.339567317","description":"Error received from peer ipv4:xxx.xxx.xxx.xxx:42819","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Socket closed","grpc_status":14}"\n>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_service.py", line 33, in call\n    kwargs=getattr(command_request, '_kwargs'))\n  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 94, in dispatch\n    raise e\n  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 91, in dispatch\n    call_result = _method(_instance, *deserialized_args)\n  File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 194, in wrapper\n    raise RuntimeError(msg)\nRuntimeError: \n\n==== detail start, at 20230531.134801.002 ====\nTraceback (most recent call last):\n  File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper\n    return func(*args, **kw)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 303, in run_task\n    self._run_unary(map_partitions_wrapper, task, shuffle=shuffle, reduce_op=reduce_op)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 119, in _run_unary\n    scatter_results = scatter_future.result()\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n    return list(f.result() for f in self._futures)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n    return list(f.result() for f in self._futures)\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result\n    return self.__get_result()\n  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result\n    raise self._exception\n  File "/data/projects/fate/eggroll/python/eggroll/core/datastructure/threadpool.py", line 51, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 154, in do_send_all\n    return CompositeFuture(send_all_futs).result()\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n    return list(f.result() for f in self._futures)\n  File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n    return list(f.result() for f in self._futures)\n  File "/opt/app-root/lib/python3.6/site-packages/grpc/_channel.py", line 303, in result\n    raise self\ngrpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1685539164.339567317","description":"Error received from peer ipv4:xxx.xxx.xxx.xxx:42819","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Socket closed","grpc_status":14}"\n>\n\n==== detail end ====\n\n\n\n==== detail end ====\n\n","grpc_status":2}"
325
>)

**Comment by qixiaoye** [comment]
同时出现的还有这个错误：
ValueError: query job result is {'data': "Can't connect to MySQL server on 'mysql' ([Errno -2] Name or service not known)", 'retcode': 100, 'retmsg': '2003'}, can not parse useful info

**Comment by talkingwallace** [comment]
请问这样的问题是稳定复现的吗

**Comment by qixiaoye** [comment]
是的，机器配置是16c32g
