### ISSUE TITLE
测试packing-unpacking有误

### ISSUE THREAD

**Issue by relinda2019** [FederatedAI/FATE#4887]
**Describe the bug**
测试 standalone_fate_install_1.10.0_release/python/federatedml/ensemble/test/gh_packing_compressing_test.py 文件时， 当h取负值，  cls.max_sample_num = 10,  方法 run_gh_accumulate_test（）中decrypt & unpacking后的h_sum_ 与理论值h_sum不相等。
如下所示，想问下packing  unpacking的针对h二阶梯度是负值的情况如何支持呢？感谢！

![image](https://github.com/FederatedAI/FATE/assets/39260479/c976218a-1b46-44e3-af69-f44d48d64197)

**To Reproduce**
1. Go to 'standalone_fate_install_1.10.0_release/python/federatedml/ensemble/test/gh_packing_compressing_test.py'
2. modify max_sample_number=10 and -h, 如下
![image](https://github.com/FederatedAI/FATE/assets/39260479/d6f9a9c6-6fef-4dfb-9be6-f93f2f61b41c)
3. 运行该unitest
8. See error9. 

![image](https://github.com/FederatedAI/FATE/assets/39260479/c976218a-1b46-44e3-af69-f44d48d64197)

**Expected behavior**
h_sum_理论值应该为h_sum = -3.1018895537282893
 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by talkingwallace** [comment]
hi，我们现有的损失函数中，我们的损失函数二阶导数都不会是负数的，因此不会考虑这种情况，packing是没问题的。
如果要考虑负数的情况，建议可以对h做一下offset到正数
