### ISSUE TITLE
千万级样本训练纵向nn如何提升速度

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#4890]
我们在千万级样本上训练nn，发现训练耗时过长，bottom model用了三层linear，top model用了两层linear，隐层神经元个数为4，batch size设置成12000,每个batch训练耗时大概一分半，一轮跑完需要七个小时，请问有什么方法或者设置哪些参数可以加速模型训练？

**Comment by DingDante** [comment]
我使用mnist数据集也遇到了同样的问题，跑完一个epoch，时间太长

**Comment by qixiaoye** [comment]
请问更小的模型是指减少层数还是减少每层神经元的个数呢？根据Hetero-nn实现来看，传到interactive layer的神经元个数不能太大，其他层的结构也会对速度有很大影响吗

**Comment by talkingwallace** [comment]
主要在于Interactive 层的大小, bottom model 和 top model的影响会小一些

**Comment by qixiaoye** [comment]
请问selective backward有相关文档吗，只在代码里看到默认参数relative，没有找到原理和参数说明文档
