### ISSUE TITLE
隐私求交模块能否支持指定列的求交？

### ISSUE THREAD

**Issue by enidastronomical** [FederatedAI/FATE#4891]
假设有两个输入表格A和B，各自有3列。能否在每次求交的时候指定用哪一列作为求交主键？
例如：
指定用A的第一列和B的第二列求交

如果能够支持这种功能，请问应该如何使用？还想问一下实现这部分功能的源码在哪里呢？如果不支持的话，应该从哪部分代码入手进行改造呢？

万分感谢！

**Comment by mgqa34** [comment]
可以参考下面的[tutorial](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_multiple_id_columns.ipynb)，需要用到match_id的相关概念和配置

**Comment by chenyouPomelo** [comment]
> 可以参考下面的[tutorial](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_multiple_id_columns.ipynb)，需要用到match_id的相关概念和配置

感谢，但是在运行过程中遇到了这个问题，请问是哪里发生了错误呀

[ERROR] [2023-06-05 16:20:03,343] [202306051619536516900] [28111:139948615706432] - [task_executor._run_] [line:265]: module 'federatedml' has no attribute 'None'
2
Traceback (most recent call last):
3
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
4
    cpn_output = run_object.run(cpn_input)
5
  File "/data/projects/fate/fateflow/python/fate_flow/components/_base.py", line 156, in run
6
    self._run(cpn_input=cpn_input)
7
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 238, in _run
8
    data_table_count = self.save_data_table(job_id, name, namespace, head)
9
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 273, in save_data_table
10
    metas_info.update({"schema": self.generate_anonymous_schema()})
11
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 352, in generate_anonymous_schema
12
    schema.update(AnonymousGenerator.generate_header(computing_table, schema))
13
  File "/data/projects/fate/fateflow/python/fate_flow/manager/data_manager.py", line 97, in generate_header
14
    obj = env_utils.get_class_object("data_format")
15
  File "/data/projects/fate/fateflow/python/fate_flow/component_env_utils/env_utils.py", line 53, in get_class_object
16
    class_obj = get_provider_class_object(provider, class_name)
17
  File "/data/projects/fate/fateflow/python/fate_flow/component_env_utils/provider_utils.py", line 43, in get_provider_class_object
18
    return getattr(importlib.import_module(".".join(class_path[:-1])), class_path[-1])
19
AttributeError: module 'federatedml' has no attribute 'None'

**Comment by mgqa34** [comment]
请问下部署方式是什么呢？ 另外版本号是哪个?

**Comment by chenyouPomelo** [comment]
> 请问下部署方式是什么呢？ 另外版本号是哪个?

版本号是1.9.1
部署方式：单机版本

**Comment by mgqa34** [comment]
> > 请问下部署方式是什么呢？ 另外版本号是哪个?
> 
> 版本号是1.9.1 部署方式：单机版本

这里的单机版指的是哪个包的链接呢？standalone-host还是standalone-docker还是分布式的单机版？

**Comment by chenyouPomelo** [comment]
> 是kube-fate docker 


> > > 请问下部署方式是什么呢？ 另外版本号是哪个?
> > 
> > 
> > 版本号是1.9.1 部署方式：单机版本
> 
> 这里的单机版指的是哪个包呢？standalone-host还是standalone-docker还是分布式的单机版？可以给下更具体的包名信息

**Comment by chenyouPomelo** [comment]
> > > 请问下部署方式是什么呢？ 另外版本号是哪个?
> > 
> > 
> > 版本号是1.9.1 部署方式：单机版本
> 
> 这里的单机版指的是哪个包呢？standalone-host还是standalone-docker还是分布式的单机版？可以给下更具体的包名信息

是kube-fate docker

**Comment by chenyouPomelo** [comment]
> > > > > 请问下部署方式是什么呢？ 另外版本号是哪个?
> > > > 
> > > > 
> > > > 版本号是1.9.1 部署方式：单机版本
> > > 
> > > 
> > > 这里的单机版指的是哪个包呢？standalone-host还是standalone-docker还是分布式的单机版？可以给下更具体的包名信息
> > 
> > 
> > 是kube-fate docker
> 
> [FederatedAI/KubeFATE#871](https://github.com/FederatedAI/KubeFATE/issues/871) 可以看下这个issue哈，可能也是有配置没更新

好的，谢谢。我看一下～

**Comment by Joe12-24** [comment]
> > > > > > 请问下部署方式是什么呢？ 另外版本号是哪个?
> > > > > 
> > > > > 
> > > > > 版本号是1.9.1 部署方式：单机版本
> > > > 
> > > > 
> > > > 这里的单机版指的是哪个包呢？standalone-host还是standalone-docker还是分布式的单机版？可以给下更具体的包名信息
> > > 
> > > 
> > > 是kube-fate docker
> > 
> > 
> > [FederatedAI/KubeFATE#871](https://github.com/FederatedAI/KubeFATE/issues/871) 可以看下这个issue哈，可能也是有配置没更新
> 
> 好的，谢谢。我看一下～

你好这部分做的怎么样了, 方便加个联系方式吗
