### ISSUE TITLE
model loader目前支持load哪些FATE组件？

### ISSUE THREAD

**Issue by ArtiPyHeart** [FederatedAI/FATE#4893]
目前在example/dsl/v2里，看到model loader仅仅有重新加载hetero_feature_binning组件一个例子，想问一下model loader是否支持其他组件（如各种联邦模型）的加载？以及，该组件是否仅能用于hetero纵向组件，无法用于homo横向组件？盼回复，谢谢！

**Comment by talkingwallace** [comment]
所有算法组件都是可以的
