### ISSUE TITLE
hetero_pearson raise an error when input both validate_data and train_data

### ISSUE THREAD

**Issue by scnjlnj** [FederatedAI/FATE#4894]
**Describe the bug**
hetero_pearson raise an error when input both validate_data and train_data
fate version v1.10

DSL as follow
"hetero_pearson_0":{
			"output":{
				"model":[
					"model"
				]
			},
			"input":{
				"data":{
					"validate_data":[
						"hetero_data_split_0.validate_data"
					],
					"test_data":[],
					"train_data":[
						"hetero_data_split_0.train_data"
					]
				}
			},
			"module":"HeteroPearson"
		}

![image](https://github.com/FederatedAI/FATE/assets/37607092/379c2e3a-40d0-4518-b01f-01f00b3e4b49)

error

![image](https://github.com/FederatedAI/FATE/assets/37607092/b15025ad-43c1-4e9f-be23-f42e24498f83)
![image](https://github.com/FederatedAI/FATE/assets/37607092/03c4456a-a33e-474e-bdc7-e501e1fbe923)
![image](https://github.com/FederatedAI/FATE/assets/37607092/c8248dae-957c-44e5-828d-580652187f30)

**Comment by mgqa34** [comment]
Pearson component does not support validate data.
