### ISSUE TITLE
表绑定存储引擎为HDFS支持的文件格式

### ISSUE THREAD

**Issue by iceicei** [FederatedAI/FATE#4895]
你好，我想请问一下表绑定中存储引擎为HDFS时，支持的数据格式是否不支持parquet格式，我在FATE-FLOW官方文档看到/fate_flow_data_access/#3文档中，表绑定mete信息中参数input_format只支持数据格式(dense、svmlight、tag:value)，以及hdfs的官方样例，据我目前了解的信息，hdfs目前支持.csv文件格式，而考虑大数据集的存储和读取性能，在计算引擎为Spark、存储引擎为hdfs的情况，是否应该支持parquet格式

**Comment by zhihuiwan** [comment]
fate暂不支持parquet格式的hdfs存储，不过这确实是个好的点，后续版本我们也会逐渐支持引入更多的格式的数据类型，非常感谢您提供的建议。

**Comment by iceicei** [comment]
> fate暂不支持parquet格式的hdfs存储，不过这确实是个好的点，后续版本我们也会逐渐支持引入更多的格式的数据类型，非常感谢您提供的建议。

你好，我还有一个问题，表绑定外部存储为HDFS时，当前是否不支持Kerberos鉴权？我在看fate flow关于table bind的文档时没有看到相关的案例以及参数呢。

**Comment by zhihuiwan** [comment]
不支持
