### ISSUE TITLE
云存储支持

### ISSUE THREAD

**Issue by yang-shuaijun** [FederatedAI/FATE#4897]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
目前FATE支持那些云厂商的对象存储？
本地存储如果存储大量数据，成本还是比较高的。

**Additional context**

**Comment by zhihuiwan** [comment]
目前只有模型支持腾讯云cos存储，后续在数据存储这块也会考虑引入云存储，非常感谢你的建议。

**Comment by yang-shuaijun** [comment]
非常感谢您抽出时间回答。
