### ISSUE TITLE
请问当前版本的hetero-nn是否支持多输出,是否支持自定义损失，请问有参考文档吗？

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#4898]
请问当前版本的hetero-nn是否支持多输出,是否支持自定义损失，请问有参考文档吗？

**Comment by talkingwallace** [comment]
https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/nn_tutorial/README.md
参考这个文档

HeteroNN 可以多输出，但是需要注意的是，多输出可能和FATE Board等组件的适配就会存在问题，如果使用上有任何问题
欢迎提issue，我可以及时回复
