### ISSUE TITLE
纵向nn  No module named 'federatedml.nn.model_zoo.bottom_net'

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#4901]
全程按照https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/nn_tutorial/Hetero-NN-Customize-Model.ipynb替换成自己自定义的模型，但一直报错No module named 'federatedml.nn.model_zoo.bottom_net'

**Comment by mgqa34** [comment]
确认save_to_fate已经有bottom_net，简单的方法是看下python/federatedml/nn/model_zoo下是否有这个文件
