### ISSUE TITLE
hetero nn加了验证集，每一轮(334个batch)训练结束之后验证集预测从iter 0 batch0一直到iter 333 batch0,请问这个什么意思？

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#4903]
hetero nn加了验证集，每一轮(334个batch)训练结束之后验证集预测从iter 0 batch0一直到iter 333 batch0，第二轮会从上面iter继续增加，请问这个是啥意思？验证集预测为什么batch一直为0,iter一直累加？
![image](https://github.com/FederatedAI/FATE/assets/37823459/82b58c18-382a-4c6d-809b-22a89bbb1641)

**Comment by talkingwallace** [comment]
Hi, 这个是日志的问题，在一些部分train/predict 共用了相同的传输变量，无视它们即可

**Comment by qixiaoye** [comment]
好的，我发现验证集预测时间和训练集训练时间差不多，比如一轮数据训练完需要5小时，验证集每一轮预测也需要五小时左右，这个正常吗？

**Comment by talkingwallace** [comment]
这个得看看您的数据量是怎么样的，理论上，验证集验证一次，也要经过一系列加密操作，开销较大

**Comment by qixiaoye** [comment]
请问验证集预测的时候，iter轮数变成了训练batch数的两倍，是什么原因？
如下图所示，第一轮batch数为0-122，但预测的iter数为0-243
![image](https://github.com/FederatedAI/FATE/assets/37823459/b8d3de6c-30ea-4993-b1ba-d280a12ebb91)
