### ISSUE TITLE
ansible deploy时使用虚拟环境的ansible部署时报错

### ISSUE THREAD

**Issue by iceicei** [FederatedAI/FATE#4907]
由于生产环境不能直接安装ansible，所以使用ansible [core 2.14.3]通过虚拟环境启动，但是在使用命令"/bin/bash deploy/deploy.sh ping"进行Ping测试时，出现问题。
当/data/projects/AnsibleFATE_1.11.0_release_offline/environments/prod/hosts文件，不填写ansible_ssh_host时（默认生成的，不包含红色框中内容），可以通过ping测试
![image](https://github.com/FederatedAI/FATE/assets/33820976/b28702f3-2907-4eb2-8f5b-ecebb2f43e81)
但是在bash deploy/deploy.sh deploy部署时，会出现以下错误：
![6e5fbc611049e6852c2b00e2c525ad8](https://github.com/FederatedAI/FATE/assets/33820976/a1a39fe9-797c-43e0-9682-de217ffbdc0d)
当我在hosts文件中将host和guest的ip都填写为ansible_ssh_host时，可以通过ping测试，但是部署时报错：
![27c44ad3afa00e92c2c47fea33df687](https://github.com/FederatedAI/FATE/assets/33820976/7f386f34-d9dc-4361-a798-aa036f4ad259)
而且部署的日志也有异常，正常host只会打印一个ip，但是这里把host和guest的ip都打印了：
![4b2c4590125257441ec5ff25504a01f](https://github.com/FederatedAI/FATE/assets/33820976/cfd7aa28-043a-4247-80c1-ebf16f82f3bb)
当我尝试只在hosts文件中添加host的ip，如上图1，把ip为xxx.65的注释时，ping测试报错：
![13728486db0b05f63e3f8f0afe4d8c3](https://github.com/FederatedAI/FATE/assets/33820976/e60b0729-03bf-4c7f-bacd-0cc67090b1f2)

**Comment by iceicei** [comment]
补充一下，我是使用命令"bash deploy/deploy.sh init -h="10000:55.14.7.67" -g="9999:55.14.7.65" -k="host|guest"生成的初始化部署配置文件，请问最终实际生成的hosts文件在哪能见到吗，或者我需要怎么改hosts文件才能成功部署呢？

**Comment by paulbaogang** [comment]
1、确认下ansible的版本，需要2.9.x及以上版本。

**Comment by paulbaogang** [comment]
1、environments/prod/hosts文件生成后不用修改，一般是ssh端口不对的时候再修改下
