### ISSUE TITLE
there are 1 failed test

### ISSUE THREAD

**Issue by SJTUHGX** [FederatedAI/FATE#4908]
**Describe the bug**
FAIL: test_compute_hess (__main__.TestSoftmaxCrossEntropyLoss)

**To Reproduce**
1. When running unit tests using the standalone version. fate_test unittest federatedml --yes

**Expected behavior**
Is there something wrong with the algorithm itself during the writing process?

**Screenshots**
![Uploading image.png…]()

**Comment by talkingwallace** [comment]
Hi, we update the Hess computation in the latest version, and this causes the test error. Just ignore it.
