### ISSUE TITLE
Homo Feature Selection ?

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4909]
Hello, 

I am wondering if there is a way to perform Homo Feature Selection on Horizontal Learning models. 
I am currently working on "epsilon_5k" homo data, and I want to filter out less meaningful features.

**Comment by talkingwallace** [comment]
Feature Selection support local filtering :D

**Comment by amyseoj1** [comment]
> Feature Selection support local filtering :D

Hello @talkingwallace, 

Do you mean by using Hetero Feature Selection and set "select_federated":False  in the selection parameter ?
