### ISSUE TITLE
训练好模型后, 如何脱离fate-serving的环境使用?

### ISSUE THREAD

**Issue by jhuser02** [FederatedAI/FATE#4912]
fate 已训练部署好的模型, 如何在脱离 fate-serving 的环境下进行API调用 (预测) ?
比如, 有没办法用python简单加载fate的模型来调用?
(由于业务上的限制, 我这无法部署fate-serving.)

**Comment by talkingwallace** [comment]
如果是纵向模型，可能暂时没办法，如果是横向模型，可以导出完整模型使用

**Comment by zzy484** [comment]
> 如果是横向模型，可以导出完整模型使用

如何导出完整的横向模型呢？
