### ISSUE TITLE
部署后单元测试 fate_test unittest federatedml --yes报错

### ISSUE THREAD

**Issue by mystery-abby** [FederatedAI/FATE#4914]
FAIL: test_compute_hess (__main__.TestSoftmaxCrossEntropyLoss)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/standalone_fate_install_1.11.2_release/fate/python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/test/cross_entropy_test.py", line 100, in test_compute_hess
    self.assertTrue(np.fabs(hess - softmaxloss_hess).all() < consts.FLOAT_ZERO)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 8 tests in 1.452s

FAILED (failures=1)

**Comment by talkingwallace** [comment]
Hi，这个是因为我们上个版本修复了一个梯度计算的bug，忘记更新单元测试了，无视这个错误就行，不会影响正确性的，我们尽快修复单元测试

**Comment by mystery-abby** [comment]
> Hi，这个是因为我们上个版本修复了一个梯度计算的bug，忘记更新单元测试了，无视这个错误就行，不会影响正确性的，我们尽快修复单元测试

感觉解答
