### ISSUE TITLE
树模型训练过程中会出现通信中断错误，非必现

### ISSUE THREAD

**Issue by qixiaoye** [FederatedAI/FATE#4926]
如下面所示，模型训练过程中会出现socket closed通信中断

debug_error_string = "{"created":"@1686742993.453500502","description":"Error received from peer ipv4:xxx.xxx.xxx.xxx:37538","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Exception calling application: \n\n==== detail start, at 20230614.194313.452 ====\nTraceback (most recent call last):\n File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper\n return func(*args, **kw)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 303, in run_task\n self._run_unary(map_partitions_wrapper, task, shuffle=shuffle, reduce_op=reduce_op)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 119, in _run_unary\n scatter_results = scatter_future.result()\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n return list(f.result() for f in self._futures)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n return list(f.result() for f in self._futures)\n File "/opt/python3/lib/python3.8/concurrent/futures/_base.py", line 444, in result\n return self.__get_result()\n File "/opt/python3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result\n raise self._exception\n File "/data/projects/fate/eggroll/python/eggroll/core/datastructure/threadpool.py", line 51, in run\n result = self.fn(*self.args, **self.kwargs)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 154, in do_send_all\n return CompositeFuture(send_all_futs).result()\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n return list(f.result() for f in self._futures)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n return list(f.result() for f in self._futures)\n File "/data/projects/python/venv/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result\n raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1686742351.089020278","description":"Error received from peer ipv4:xxx.xxx.xxx.xxx:36879","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Socket closed","grpc_status":14}"\n>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper\n return func(*args, **kw)\n File "/data/projects/fate/eggroll/python/eggroll/core/command/command_service.py", line 30, in call\n call_result = CommandRouter.get_instance() \\n File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 94, in dispatch\n raise e\n File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 91, in dispatch\n call_result = _method(_instance, *deserialized_args)\n File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 194, in wrapper\n raise RuntimeError(msg)\nRuntimeError: \n\n==== detail start, at 20230614.194313.434 ====\nTraceback (most recent call last):\n File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 187, in wrapper\n return func(*args, **kw)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 303, in run_task\n self._run_unary(map_partitions_wrapper, task, shuffle=shuffle, reduce_op=reduce_op)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 119, in _run_unary\n scatter_results = scatter_future.result()\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n return list(f.result() for f in self._futures)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n return list(f.result() for f in self._futures)\n File "/opt/python3/lib/python3.8/concurrent/futures/_base.py", line 444, in result\n return self.__get_result()\n File "/opt/python3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result\n raise self._exception\n File "/data/projects/fate/eggroll/python/eggroll/core/datastructure/threadpool.py", line 51, in run\n result = self.fn(*self.args, **self.kwargs)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 154, in do_send_all\n return CompositeFuture(send_all_futs).result()\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in result\n return list(f.result() for f in self._futures)\n File "/data/projects/fate/eggroll/python/eggroll/roll_pair/transfer_pair.py", line 48, in <genexpr>\n return list(f.result() for f in self._futures)\n File "/data/projects/python/venv/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result\n raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Socket closed"\n\tdebug_error_string = "{"created":"@1686742351.089020278","description":"Error received from peer ipv4:xxx.xxx.xxx.xxx:36879","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Socket closed","grpc_status":14}"\n>\n\n==== detail end ====\n\n\n\n==== detail end ====\n\n","grpc_status":2}"

**Comment by talkingwallace** [comment]
这个可能还是和网络环境波动有关系吧，如果不是必现的
