### ISSUE TITLE
Federated schedule error, Please check rollSite and fateflow network connectivityrpc

### ISSUE THREAD

**Issue by tigflanker** [FederatedAI/FATE#4928]
**Describe the bug**
通过Ansible安装好FATE后，提交任务经常会遇到“Federated schedule error, Please check rollSite and fateflow network connectivityrpc”

**To Reproduce**
1. 通过Ansible 1.8.1 安装好FATE
2. 无论通过Client或者pipeline执行基本的纵向LR
3. 出现如上问题
4. 日志报错关键句：
a. 'retmsg': 'Federated schedule error, Please check rollSite and fateflow network connectivityrpc request error: <_Rendezvous of RPC that terminated with: status = StatusCode.UNAVAILABLE
b. File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py\", line 133, in submit\n    raise Exception(\"create job failed\", response)\nException: ('create job failed',

**Screenshots**
请参见附件

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Version: Ansible 1.8.1
![微信截图_20230615165515](https://github.com/FederatedAI/FATE/assets/22868157/06ac4c6d-b794-4d37-8c16-565966faa174)
[log.log](https://github.com/FederatedAI/FATE/files/11755278/log.log)

**Comment by paulbaogang** [comment]
toy测试可以跑通么？另外机器是什么配置？如果低于2C4G容易出问题

**Comment by tigflanker** [comment]
@paulbaogang 又测试了一下，toy和min test都能跑通，双边模式，但是自己数据跑不通。。
机器是基于本地电脑的两台虚拟机，都是4C7G，但是run的时候确实本机内存占用到15G
我把数据（只有几百条）、conf和dsl、还有执行步骤和log都传上来，能否帮核验下呢，非参感谢
[测试样例纵向LR建模.zip](https://github.com/FederatedAI/FATE/files/11798469/LR.zip)

**Comment by paulbaogang** [comment]
跑任务的时候磁盘是否有满？机器负载怎么样？好像是跑任务的时候环境异常了，应该是哪里资源不足，导致临时进程没启动或者异常了。最好还是找两台服务器做测试。

**Comment by paulbaogang** [comment]
跑任务的时候磁盘是否有满？机器负载怎么样？好像是跑任务的时候环境异常了，应该是哪里资源不足，导致临时进程没启动或者异常了。

**Comment by tigflanker** [comment]
@paulbaogang 感谢回复，最终发现是conf文件里 “initiator”和“role” 的端口号写反了；终于找到了问题点
