### ISSUE TITLE
请问FATE在横向聚合的时候，安全层面的保证，是只使用了同态加密Paillier吗？

### ISSUE THREAD

**Issue by pxyfxun** [FederatedAI/FATE#4931]
如题，是否只使用了同态加密？客户端给服务端上传梯度时，有没有加可抵消的噪音？

**Comment by dylan-fan** [comment]
用的是SeccureAgg

**Comment by pxyfxun** [comment]
> 用的是SeccureAgg

谢谢。

另外，请教一下，这个具体代码大概在什么位置，我没找到~

**Comment by talkingwallace** [comment]
在framework/homo/aggregator下

**Comment by pxyfxun** [comment]
> 在framework/homo/aggregator下

谢谢大佬。

我看了这块，以及引用了“SecureAggregatorClient ”的python/federatedml/nn/homo/trainer/fedavg_trainer.py

但是有个疑问：使用了DH密钥交换技术，得到共享秘钥。但是最后增加可抵消参数时，两方之间没有约定这个可抵消的参数self._amplify_factor？这个是初始化时，定死的1？
