### ISSUE TITLE
关于fate-raw和fate-rsa求交算法的随机性

### ISSUE THREAD

**Issue by enidastronomical** [FederatedAI/FATE#4933]
我们测试了fate-raw和fate-rsa1024求交算法在数据量分别为500万vs500万，1000万vs500万，2000万vs500万下占用的网络带宽，理论上来说应该网络带宽峰值应该是一个递增的趋势。
但是测试出来的网络带宽峰值具有很强的随机性，1000万vs500万下的带宽峰值反而会小于500万vs500万下的带宽峰值，想请问一下这个可能是什么原因所导致的呀？

**Comment by chenyouPomelo** [comment]
> 从峰值角度考虑的话，感觉有一个可能的原因，500w vs 500w的时候，可能guest\host同时计算完一些步骤，然后互相发送，而数据量区别比较大的时候则不存在这种情况，所以500w vs 500w的峰值高是同时收发导致的，可以加一些日志确认下。 不过从理论上看2000w数据应该是占用更大的带宽的，eggroll不随着数据量增大而增大峰值应用，这个背后的原因需要再排查下

好的，非常感谢！
