### ISSUE TITLE
standalone_fate的docker部署问题

### ISSUE THREAD

**Issue by lyquid617** [FederatedAI/FATE#4934]
按照FATE/deploy/standalone-deploy中的步骤2.1，2.2进行部署，会报错：
Error response from daemon: manifest for federatedai/standalone_fate:1.11.2 not found: manifest unknown: manifest unknown

查看docker hub后发现docker hub中仅有1.10.0之前版本的镜像。缺少对后续版本的支持。

**Comment by dylan-fan** [comment]
这个最近会支持
