### ISSUE TITLE
hetero_sbt运行效率问题

### ISSUE THREAD

**Issue by huyz1117** [FederatedAI/FATE#4939]
单机模式下，两方运行hetero_sbt算法，数据求交后共有11w+，其中guest方拥有13个特征，host方30个特征，设置`num_trees=400`、树最大深度为4、加密方法为paillier，运行时间为27个小时，请问这个训练时间正常吗

**Comment by talkingwallace** [comment]
我这里测试一下

**Comment by talkingwallace** [comment]
请问你的配置是如何的，我在我自己的机器（16核，64G内存），用11W 13+30特征的数据集，最大深度为4，一棵树的时间大约在一分钟左右，如果400个树，约合7小时
![image](https://github.com/FederatedAI/FATE/assets/10768970/c3fb192c-e33a-4c27-aa78-418a5285062a)

**Comment by huyz1117** [comment]
12核，32G内存

**Comment by talkingwallace** [comment]
不是很清楚你这边具体的机器性能，不过如果觉得太慢了，可以考虑看下run_goss参数，看看能不能在样本的采样的情况下加速训练，采样可能会有一些性能损失
