### ISSUE TITLE
Bug: Hetero-NN-Mix-Task.ipynb does not run on FATE 1.11.2

### ISSUE THREAD

**Issue by PaulKMandal** [FederatedAI/FATE#4941]
**Describe the bug**
Because a few of the libraries have been renamed and removed (e.g. python/federatedml/nn/dataset/nlp_tokenizer.py), the Hetero-NN-Mix-Task is unable to run properly without adding some of the libraries from fate 1.10

**To Reproduce**
Run the Hetero-NN-Mix-Task.ipynb on FATE 1.11.2.

**Comment by talkingwallace** [comment]
Thanks for the feedback, I'll check the problem and get it fix in the next version :D

**Comment by talkingwallace** [comment]
https://github.com/FederatedAI/FATE-LLM/blob/main/python/fate_llm/dataset/nlp_tokenizer.py

The nlp_tokenizer is now in the llm repo, you can copy the codes and put it in the dataset folder
