### ISSUE TITLE
GPT2-large模型序列化的 protobuf 消息的大小超过了 protobuf 库所允许的最大值（2GB）(fate-v1.11.1)

### ISSUE THREAD

**Issue by kingruning** [FederatedAI/FATE#4944]
![image](https://github.com/FederatedAI/FATE/assets/103890285/75deec90-7a09-4aa2-9170-4d9f47195d50)

ValueError: Message com.webank.ai.fate.core.mlmodel.buffer.HomoNNParam exceeds maximum protobuf size of 2GB: 2804291367

**Comment by talkingwallace** [comment]
Hi 这个问题修复了，使用fedavgtrainer, TrainerParam里加上save_to_local_dir=True就可以了

**Comment by kingruning** [comment]
> Hi 这个问题修复了，使用fedavgtrainer， TrainerParam里加上save_to_local_dir=True就可以了

是的，确实可以的，谢谢
