### ISSUE TITLE
mnist数据集直接使用图片绑定的方式，1.9.0版本运行提示错误。另外1.11.2版本中为啥删除了绑定相关的示例？

### ISSUE THREAD

**Issue by liuyichen2013** [FederatedAI/FATE#4948]
**Describe the bug**
按照代码中的示例操作，1.9.0版本运行提示错误。另外1.11.2版本中为啥删除了mnist数据集绑定相关的示例？

![image](https://github.com/FederatedAI/FATE/assets/88218731/e0175a18-eabc-4201-81a8-9ce03d7eac49)

![image](https://github.com/FederatedAI/FATE/assets/88218731/e6e9c84a-82fb-4956-bda1-ac5b1156c0d7)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by liuyanfeng1981** [comment]
图片目录格式如下，应该没啥问题
![image](https://github.com/FederatedAI/FATE/assets/88218731/350fe889-0a6d-47a6-ae9a-89557d8e5492)

**Comment by talkingwallace** [comment]
Hi, 这种方式已经不支持了，可以考虑使用最新的版本以及参考最新文档

**Comment by liuyanfeng1981** [comment]
文档中没找到相关说明，对于这种数据集直接使用图片的情况，新版本如何解决的？还是已经不支持直接使用图片了？谢谢

**Comment by talkingwallace** [comment]
https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/nn_tutorial/README.md
这个，请参考下首页的NN文档哈

**Comment by liuyanfeng1981** [comment]
> https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/nn_tutorial/README.md 这个，请参考下首页的NN文档哈

![image](https://github.com/FederatedAI/FATE/assets/88218731/cf609ac0-a213-4861-9b0c-0177468d3853)
请教一下，这种直接使用图片上传数据集的方式有flow client命令行吗？文档中没找到，谢谢
