### ISSUE TITLE
【model deploy】Only deployed models could be used to execute process of loading. Please deploy model before loading.

### ISSUE THREAD

**Issue by tigflanker** [FederatedAI/FATE#4953]
**Describe the bug**
是在模型部署阶段，一个模型已经训练完成的情况下，部署卡壳

**To Reproduce**
![1](https://github.com/FederatedAI/FATE/assets/22868157/3f1ab6bf-b3e2-49e1-a1a4-d61496f4e7df)
先进行了一次模型load
flow model load -c /data/projects/fate/examples/gf_test/publish_load_model.json
报错模型需要先deploy

![2](https://github.com/FederatedAI/FATE/assets/22868157/8c27b6c1-30f9-4724-b67c-5a6190523b0d)
然后进行了一次deploy，成功了

![3](https://github.com/FederatedAI/FATE/assets/22868157/605e6fe3-1ed1-481f-a145-4b1b0a89b972)
再运行模型load，还是不成

另外想咨询下这个情况应该在哪儿看日志呢？
我在 /data/projects/fate/serving/server/logs/fate-serving-server.log
和 /data/projects/fate/fateflow/logs/info.log
貌似没看到端倪。。

**Desktop (please complete the following information):**
 - OS: CentOS 7（两台虚拟机VMWare)
 - Version Ansible 1.8.1

感谢大佬

**Comment by zhihuiwan** [comment]
需要使用deploy时生成的model_id && model version

**Comment by tigflanker** [comment]
@zhihuiwan 感谢感谢，是这样的，问题解决了
