### ISSUE TITLE
请问FATE横向联邦，关于安全聚合，client向server提交模型参数时，可抵掩码数是如何约定的？

### ISSUE THREAD

**Issue by pxyfxun** [FederatedAI/FATE#4957]
请问大佬，看了一下“SecureAggregatorClient ”的python/federatedml/nn/homo/trainer/fedavg_trainer.py
训练的代码，发现，虽然通过DH协议得到了共享密钥，但是，可抵消的掩码的值，是通过初始化默认的1来确定的？而不是某一方给出一个随机值，然后通过共享密钥加密通知给另一方？

那么：
1.通过DH协商出来的share_secret，是用来干啥的？
2.如果直接用默认值1来作为可抵消的掩码，那不是没有安全性？

**Comment by talkingwallace** [comment]
1. DH协商后，是用来生成随机种子
2. 这个不可能是1的，掩码一定是随机生成的随机数，然后相互之间是可以抵消的

**Comment by pxyfxun** [comment]
> 1. DH协商后，是用来生成随机种子
> 2. 这个不可能是1的，掩码一定是随机生成的随机数，然后相互之间是可以抵消的

谢谢
