### ISSUE TITLE
how to debug error runs of "flow model deploy"

### ISSUE THREAD

**Issue by kaiwang0112006** [FederatedAI/FATE#4962]
我们的fate版本是1.8.0，不同的域内各有一个节点，guest id是21000，host id是62020，通过rollsite联通。

已经完成纵向lr的训练过程，

![image](https://github.com/FederatedAI/FATE/assets/5267718/8c25cf82-b122-4448-821f-6ca0b23e6b22)

现在需要deploy模型：

`flow model deploy --model-id arbiter-62020#guest-21000#host-62020#model --model-version 202306210813377284140 --cpn-list "reader_0, data_transform_0, intersection_0, feature_scale_0, hetero_feature_binning_0, hetero_feature_selection_0, hetero_lr_0"`

但是在一方节点没有部署成功：

![image](https://github.com/FederatedAI/FATE/assets/5267718/77a38251-5689-4e37-9113-efc5858372f7)

请问如何获取详细的报错信息，因为不是提交的训练任务，在fateboard上看不到。如何定位部署失败的错误？

**Comment by mgqa34** [comment]
fate_flow/logs/fate_flow/ERROR.log有错误日志吗？

**Comment by kaiwang0112006** [comment]
> fate_flow/logs/fate_flow/ERROR.log有错误日志吗？

Hi, 我看了一下

`docker exec -it d794968a9ae3 /bin/bash # 进入federatedai/python:1.8.0-release的container
tail fateflow/logs/fate_flow/ERROR.log
`

有报错：

Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/apps/model_app.py", line 677, in deploy
    federated_mode=FederatedMode.MULTIPLE if not IS_STANDALONE else FederatedMode.SINGLE)
  File "/data/projects/fate/fateflow/python/fate_flow/utils/api_utils.py", line 78, in federated_api
    dest_party_id=dest_party_id, json_body=json_body, api_version=api_version, overall_timeout=overall_timeout)
  File "/data/projects/fate/fateflow/python/fate_flow/utils/api_utils.py", line 185, in federated_coordination_on_grpc
    raise Exception('{}rpc request error: {}'.format(tips, exception))
Exception: Please check rollSite and fateflow network connectivityrpc request error: <_Rendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1688438906.097301681","description":"Error received from peer ipv4:192.167.0.4:9370","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Deadline Exceeded","grpc_status":4}"

这个需要检查什么呢
