### ISSUE TITLE
❗BUG❗：model loader进行prediction报错ValueError: cpn HomoNN#sanet predict has redundant parameters

### ISSUE THREAD

**Issue by Yonggie** [FederatedAI/FATE#4968]
**Describe the bug**
使用model loader进行prediction报错

**To Reproduce**
FATE1.11.2，进行自定义模型部署后，再次使用model loader加载模型。
```py


param = {
        "model_id":"arbiter-3#guest-2#host-1#model",
        "model_version": "202306281649336445640",
        "component_name": "sanet",
        }
sanet_deployed = ModelLoader(name="sanet", **param)
from pipeline.component import HomoNN
sanet_predict=HomoNN(name='sanet_predict')
predict_pipeline.add_component(sanet_deployed)
predict_pipeline.add_component(sanet_predict,\
                               data=Data(test_data=test_reader.output.data),\
                               model=Model(model=sanet_deployed.output.model))
        
predict_pipeline.compile()
predict_pipeline.fit()
```
就会出现``cpn HomoNN#sanet predict has redundant parameters``.

FATEboard显示：
![图片](https://github.com/FederatedAI/FATE/assets/31330044/4f48c934-4f81-4ef4-917c-0e31463e341e)

**Expected behavior**
解决bug

**Screenshots**
![图片](https://github.com/FederatedAI/FATE/assets/31330044/80dd647c-6a01-494b-9b6f-561b71378806)

![图片](https://github.com/FederatedAI/FATE/assets/31330044/ff76f564-8c71-4b94-9075-980d5e402335)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by mgqa34** [comment]
尝试去复现，没复现问题，可以给出完整的训练的代码以及报错的代码，可以用breast_homo数据去替换。
按照你的配置，我这边的报错是ValueError: Trainer is not specified, please specify your trainer，这个报错是因为homo_nn没配置相关参数导致的，我看上面的例子也是没有配任何参数

**Comment by Yonggie** [comment]
> 尝试去复现，没复现问题，可以给出完整的训练的代码以及报错的代码，可以用breast_homo数据去替换。 按照你的配置，我这边的报错是ValueError: Trainer is not specified, please specify your trainer，这个报错是因为homo_nn没配置相关参数导致的，我看上面的例子也是没有配任何参数

上面的params是使用model loader加载一个已经部署了的模型。

被部署的模型是自定义的``homo_nn``。

上述代码不是在train，而是在predict。

所以：
1. 先**部署**一个模型
2. 用**model loader加载**此模型
3. 新开pipeline进行“预测”

请问您的复现代码是否是这样的？

**Comment by mgqa34** [comment]
是的呢，报错信息是dsl_parser解析参数报错，还在参数解析阶段，我这边是进入到了homo_nn的client里面的报错了，参数解析完成了，所以比较奇怪。

**Comment by Yonggie** [comment]
我重新尝试了mnist数据，上述代码的报错也是``ValueError: Trainer is not specified, please specify your trainer``。总之二种情况，都不能先model load进来然后做model predict。可否给一个例子使用deploy后的模型做预测？
