### ISSUE TITLE
❗BUG❗optimizer在FATE的自定义trainer中被改变

### ISSUE THREAD

**Issue by Yonggie** [FederatedAI/FATE#4969]
**Describe the bug**
使用torch的optimizer添加了2组parameter，传参进入trainer后，optimizer被改变，且FATE框架无提示。

**To Reproduce**
```py
# optimizer中加入2组优化参数（param）
optimizer = torch.optim.SGD([{'params':base, 'lr':0.1*train_args['lr']},\
                              {'params':head, 'lr':train_args['lr']}])


nn_component = HomoNN(name='sanet',
                      model=model, # model
                      loss=loss,
                      optimizer=optimizer, # 传入trainer后
                      dataset=dataset_param,  # dataset
                      trainer=TrainerParam(trainer_name='sa_trainer', cuda=True, checkpoint_save_freqs=1, **params),
                      torch_seed=100, # random seed
                      
                      )

# optimizer的param_group在trainer中就只变成1组了，其他的不见了。
```

**Expected behavior**
解决此BUG

**Screenshots**
train code：
![图片](https://github.com/FederatedAI/FATE/assets/31330044/0e9a2728-878c-4d16-990c-0116db52d3f7)

自定义trainer中打印信息:
![图片](https://github.com/FederatedAI/FATE/assets/31330044/1b4e38e3-cc74-409f-a40b-4f1e7ac610c0)

log信息：
![图片](https://github.com/FederatedAI/FATE/assets/31330044/46379778-8b50-4ebc-a486-d9b4f27fdbf4)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by talkingwallace** [comment]
Hi, optimizer 只支持单组参数的传递的（即全部model），如果希望使用多组参数，可以考虑在自定义trainer里加入

**Comment by Yonggie** [comment]
> 

可以给一个伪代码 或者 例子 或者 思路流程 吗？自定义trainer如何加入？

**Comment by talkingwallace** [comment]
比方说:
class Trainer():
     def __init__(opt_name='sgd'):
           xxxx
     def train():
           self.optimizer = make_optimizer(self.model, self.opt_name)
           
 可以在trainer中自己实现，提交任务时不提供optimizer参数即可

**Comment by Yonggie** [comment]
> 比方说: class Trainer(): def **init**(opt_name='sgd'): xxxx def train(): self.optimizer = make_optimizer(self.model, self.opt_name)
> 
> 可以在trainer中自己实现，提交任务时不提供optimizer参数即可

懂了，谢谢。
