### ISSUE TITLE
Secure Information Retrieval获取数据显示unretrieved

### ISSUE THREAD

**Issue by desertfoxfj** [FederatedAI/FATE#4970]
FATE集群1.11.2
使用官方secure_information_retrieval的test_secure_information_retrieval_conf.json  test_secure_information_retrieval_dsl.json测试该功能
guest和host相交ID的target_cols，显示为unretrieved

修改conf中的"raw_retrieval": 为true后可以显示target_cols的值

后续测试guest只上传包含部分id且只有id这一列的数据集，进行secure_information_retrieval，"raw_retrieval": 为true的前提下，相交ID的target_cols，依然显示为unretrieved

**Comment by nemirorox** [comment]
您好，请根据bug report issue格式提供以下信息以方便排查：

1. 环境信息：FATE/FATE-Flow/Python//FATE-Client（如使用）版本号；运行系统及部署方法；环境中是否存在多个FATE版本或曾经直接替换不同版本代码
3. 可复现描述问题的完整任务配置（用户配置以及来自jobs文件夹的配置）、提交方法及所使用数据（包括数据上传配置）
4. 结果截图或输出数据样例

多谢！

**Comment by desertfoxfj** [comment]
FATE版本1.11.2    集群模式   操作系统ubuntu18.04   没有多版本FATE也没有替代过版本
调用方式http接口   http://192.168.113.147:9380/v1/job/submit  dsl和conf使用的是官方是示例
[test_secure_information_retrieval_dsl.txt](https://github.com/FederatedAI/FATE/files/11963031/test_secure_information_retrieval_dsl.txt)
[test_secure_information_retrieval_conf.txt](https://github.com/FederatedAI/FATE/files/11963032/test_secure_information_retrieval_conf.txt)
查询结果如下:
![image](https://github.com/FederatedAI/FATE/assets/30258495/febfb1d1-5ed8-475b-8165-f554b1197d4e)
尝试修改
"raw_retrieval": 为true后再运行该任务能取到所需的数据列了
![image](https://github.com/FederatedAI/FATE/assets/30258495/9b464aa2-e262-428c-b341-8758d58259c6)

后续测试guest的数据集只包含部分id列去查询host的数据，依然是unretrieved
guest的数据集只有两个ID
![image](https://github.com/FederatedAI/FATE/assets/30258495/4300642f-7a9f-4b64-88f8-97bb88c9fd37)
host还是原来完整breast_hetero_guest.csv
结果查询结果还是unretrieved
![image](https://github.com/FederatedAI/FATE/assets/30258495/e2705436-a4e0-461d-81ba-c440f311093c)

请帮忙确认如何配置才能根据双方匹配的ID查询出对方对应字段的数字，而不是返回unretrieved

**Comment by mgqa34** [comment]
使用哪种部署方式呢， 可以给出具体链接。我们直接用allInOne部署在centos系统上，连续跑10次任务，用的examples/dsl/v2下的配置（应该和你那个一致），是没问题的
