### ISSUE TITLE
数据求交阶段python报错

### ISSUE THREAD

**Issue by tigflanker** [FederatedAI/FATE#4972]
**Describe the bug**
在一个只有两方数据求交过程报了个python错误

数据：guest方、host方
guest方只有两列数据、host方只有一列数据

guest方数据样例：
id,y
fa5e65eca6521c48af507ed9782aecfa,1
ac9e9e171172f7d62c569b992f89ab59,1

host方数据样例：
id
8e01ed12e9e918cb8a201d73910f3d87

数据上传是成功的，训练阶段只有一个两方数据求交
conf：
`{
    "dsl_version":2,
    "initiator":{
        "role":"guest",
        "party_id":9999
    },
    "role":{
        "arbiter":[
            10000
        ],
        "host":[
            10000
        ],
        "guest":[
            9999
        ]
    },
    "job_parameters":{
        "common":{
            "job_type":"train"
        }
    },
    "component_parameters":{
        "role":{
            "host":{
                "0":{
                    "data_transform_0":{
                        "with_label":false
                    },
                    "reader_0":{
                        "table":{
                            "name":"fate_actv_host_id",
                            "namespace":"actv_model_host"
                        }
                    }
                }
            },
            "guest":{
                "0":{
                    "data_transform_0":{
                        "with_label":true
                    },
                    "reader_0":{
                        "table":{
                            "name":"fate_actv_guest_id",
                            "namespace":"actv_model_guest"
                        }
                    }
                }
            }
        }
    }
}`

dsl：
vi fate_actv_is_dsl.json
`{
    "components":{
        "reader_0":{
            "module":"Reader",
            "output":{
                "data":[
                    "org_data"
                ]
            }
        },
        "data_transform_0":{
            "module":"DataTransform",
            "input":{
                "data":{
                    "data":[
                        "reader_0.org_data"
                    ]
                }
            },
            "output":{
                "data":[
                    "obj_data"
                ],
                "model":[
                    "model"
                ]
            }
        },
        "intersection_0":{
            "module":"Intersection",
            "input":{
                "data":{
                    "data":[
                        "data_transform_0.obj_data"
                    ]
                }
            },
            "output":{
                "data":[
                    "intersection_data"
                ]
            }
        }
    }
}`

报错是：
(venv) [root@vm_0_2_centos 202307051655408917260]# cat fate_flow_schedule.log 
[INFO] [2023-07-05 16:55:40,892] [202307051655408917260] [5422:140660109670144] - [dag_scheduler.submit] [line:51]: submit job, body {'dsl': {'components': {'reader_0': {'module': 'Reader', 'output': {'data': ['org_data']}}, 'data_transform_0': {'module': 'DataTransform', 'input': {'data': {'data': ['reader_0.org_data']}}, 'output': {'data': ['obj_data'], 'model': ['model']}}, 'intersection_0': {'module': 'Intersection', 'input': {'data': {'data': ['data_transform_0.obj_data']}}, 'output': {'data': ['intersection_data']}}}}, 'runtime_conf': {'dsl_version': 2, 'initiator': {'role': 'guest', 'party_id': 9999}, 'role': {'arbiter': [10000], 'host': [10000], 'guest': [9999]}, 'job_parameters': {'common': {'job_type': 'train'}}, 'component_parameters': {'role': {'host': {'0': {'data_transform_0': {'with_label': False}, 'reader_0': {'table': {'name': 'fate_actv_host_id', 'namespace': 'actv_model_host'}}}}, 'guest': {'0': {'data_transform_0': {'with_label': True}, 'reader_0': {'table': {'name': 'fate_actv_guest_id', 'namespace': 'actv_model_guest'}}}}, 'common': {'secure_information_retrieval_0': {'security_level': 0.5, 'oblivious_transfer_protocol': 'OT_Hauck', 'commutative_encryption': 'CommutativeEncryptionPohligHellman', 'non_committing_encryption': 'aes', 'dh_params': {'key_length': 1024}, 'raw_retrieval': False, 'target_cols': ['id']}}}}, 'config': '/data/projects/fate/projects/actv_model/fate_actv_is_conf.json', 'dsl': 'fate_actv_is_dsl.json', 'function': 'submit_job'}}
[ERROR] [2023-07-05 16:55:40,911] [202307051655408917260] [5422:140660109670144] - [dag_scheduler.submit] [line:179]: 'common'
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py", line 114, in submit
    train_runtime_conf=job.f_train_runtime_conf)
  File "/data/projects/fate/fateflow/python/fate_flow/utils/schedule_utils.py", line 54, in get_job_dsl_parser
    mode=job_type)
  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py", line 1109, in run
    components=self._get_reader_components())
  File "/data/projects/fate/fateflow/python/fate_flow/utils/runtime_conf_parse_util.py", line 27, in get_input_parameters
    return RuntimeConfParserV2.get_input_parameters(submit_dict, components=components)
  File "/data/projects/fate/fateflow/python/fate_flow/utils/runtime_conf_parse_util.py", line 412, in get_input_parameters
    input_parameters[role] = [copy.deepcopy(cpn_dict)] * len(submit_dict["role"][role])
KeyError: 'common'

个人感觉有可能是两个地方出错：
1. 有没有可能我guest有两列、host只有一列，这样不行？
2. 有没有可能我的key（id）是string类型，应该需要int型？

**Comment by mgqa34** [comment]
这是哪个版本？报错信息的行没有涉及到 common，报了KeyError common有些奇怪

**Comment by tigflanker** [comment]
@mgqa34 是Ansible安装的1.8.1版本，系统是CentOS 7；因为之前的toy还有min test都是成功的，我打算再对比下数据，看看是不是哪里少写了啥参数

**Comment by tigflanker** [comment]
暂时解决了。
看起来是我后面的SecureInformationRetrieval函数有地方写错，整个删掉后，前面的求交能跑。
