### ISSUE TITLE
请问fate目前支持国产化的服务器和操作系统吗。

### ISSUE THREAD

**Issue by a-b-c-3-2-1** [FederatedAI/FATE#4973]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by talkingwallace** [comment]
这个目前还没有测试过的

**Comment by Yonggie** [comment]
@a-b-c-3-2-1 你测试一下

**Comment by yyf1986** [comment]
海光的服务器，欧拉的操作系统是可以的。
