### ISSUE TITLE
纵向secureboost计算加密直方图之前使用了数据分箱吗？

### ISSUE THREAD

**Issue by guo623** [FederatedAI/FATE#4977]
XGBoost论文中在聚合G、H前会先计算出分位点，以h为权重。但secure boost中h是加密的，那么是如何计算的分位点呢，是对数据进行了分箱吗，具体是哪种分箱方法呢？

**Comment by talkingwallace** [comment]
Secureboost中的特征处理是使用Lightgbm的模式，是分好桶的，具体的说是使用了quantile分箱。

**Comment by guo623** [comment]
也就是secureboost还是只使用了特征值来寻找分位点，而不是使用二阶导数h做权重

**Comment by talkingwallace** [comment]
这个是有的，host将每个分裂点对应的g, h 计算好，返还到guest解密，再计算gain
