### ISSUE TITLE
A question in fate1.11.2

### ISSUE THREAD

**Issue by jhjiang10** [FederatedAI/FATE#4987]
Exception: retcode: 100, retmsg: required parameter values: work_mode=(<WorkMode.CLUSTER: 1>, <WorkMode.STANDALONE: 0>)
这是我使用的json文件
{
    "roles": {
        "guest": [9999],
        "host": [10000],
        "arbiter": [10000]
    },
    "data": {
        "guest": {
            "9999": {
                "name": "breast_hetero_guest",
                "namespace": "experiment"
            } 
        },
        "host": {
            "10000": {
                "name": "breast_hetero_guest",
                "namespace": "experiment"
            }
        }
    },
    "components": {
        "reader_0": {
            "id": "READER"
        },
        "column_expand_0": {
            "id": "COLUMN_EXPAND",
            "params": {
                "METHOD": "manual",
                "APPEND_HEADER": ["x_0", "x_1", "x_2", "x_3"],
                "FILL_VALUE": [0, 0.2, 0.5, 1]
            },
            "upstream": {
                "DATA": ["reader_0.DATA"]
            }
        }
    }
}

**Comment by talkingwallace** [comment]
看样子是没有指定work mode， 可以尝试用一下Pipeline？

**Comment by jhjiang10** [comment]
> 看样子是没有指定work mode， 可以尝试用一下Pipeline？
新版本不是奴需要指定这两个参数了嘛？

**Comment by mgqa34** [comment]
这个报错应该是底层部署的fate版本比较旧，而使用的examples为较新的版本，请使用对应版本的examples。
