### ISSUE TITLE
把FATE的各个组件分机器部署，需要如何修改设置

### ISSUE THREAD

**Issue by hust-suwb** [FederatedAI/FATE#4997]
如题，如果想把FATE的fate_flow、fateboard、clustermanager、nodemanager、rollsite、mysql各个组件分机器部署（假设这么多机器均在同一个网络联通的内网环境中），是否可行，应该如何设置才能让各个组件能正常访问到其所依赖的其他组件？
按我的理解，这些组件应该都是通过ip+端口通信的，如果是的话是否仅需要修改ip设置即可？可能需要修改的ip设置有哪些？有哪里能看到这个全集吗？
另外，这是否会带来其他问题，比如之前各个组件间是通过同一个物理存储地址来共享数据的，改为多机后，这些共享数据无法访问了之类的？
希望能有一个这样的最佳实践可供参考。

**Comment by yyf1986** [comment]
在服务器上直接部署是可以的。分组件部署也可以的。你可以先用allinone的部署方式熟悉了各个组件的关系就可以了。
数据问题也很简单，首先数据是保存在nodemanage里面的，通过eggroll的数据库来维护的映射关系。
