### ISSUE TITLE
训练好的模型可以保存后使用新的数据集继续训练吗

### ISSUE THREAD

**Issue by zzy484** [FederatedAI/FATE#5003]
已经训练好的横向联邦学习的模型，可以用loader model加载后，使用新的数据集继续进行训练吗？

**Comment by talkingwallace** [comment]
可以的 不过新的数据集的维度需要保持不变

**Comment by zzy484** [comment]
> 
那已经训练好的模型使用loader model加载之前，需要存储在哪里吗？

**Comment by talkingwallace** [comment]
不需要的 fate flow会帮你保存好的 你需要找到保存的模型吗？

**Comment by zzy484** [comment]
> 不需要的 fate flow会帮你保存好的 你需要找到保存的模型吗？
是不需要的，谢谢您。那如果我想把训练好的模型迁移到另一台机器上面训练，fate可以实现这个功能嘛？需要另一台机器也同样安装fate的环境嘛？
