### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#5011]
Hello, 

Is bootstrap sampling supported ?
Would it be possible to use custom sampling method ?

Thank you.

**Comment by talkingwallace** [comment]
Currently Bootstrapping is not supported

**Comment by amyseoj1** [comment]
Hello, 
I am using hetero-NN, hetero-logistic Reg, hetero-secure boost.

**Comment by talkingwallace** [comment]
Hi! SBT & LR currently not support Boostraping, but for hetero-nn, you can realize the bootstrapping mechanism in a custom dataset(make sure that the guest and host samples are aligned after sampling)
