### ISSUE TITLE
诸位大佬，该在哪种场景选择哪种部署方式？

### ISSUE THREAD

**Issue by Yonggie** [FederatedAI/FATE#5014]
有这么多部署方式，请问我们该在哪种场景选择哪种部署方式？
![图片](https://github.com/FederatedAI/FATE/assets/31330044/38cd5cc3-854c-49d9-9867-6e952d9e94c1)

**Comment by talkingwallace** [comment]
一般来说 本地实验，测试，开发 用单机版即可
集群版用于生产，可以跑数量级较大的数据，可以根据自己生产环境选择部署方法
