### ISSUE TITLE
Fate server loading model error: model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct

### ISSUE THREAD

**Issue by 2294930685** [FederatedAI/FATE#5019]
Execute: flow model load - c fateflow/examples/model/publish_ Load_ Model.json

result：
{
    "data": {
        "detail": {
            "guest": {
                "9999": {
                    "retcode": 123,
                    "retmsg": "model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct. "
                }
            },
            "host": {
                "10000": {
                    "retcode": 123,
                    "retmsg": "model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct. "
                }
            }
        },
        "guest": {
            "9999": 123
        },
        "host": {
            "10000": 123
        }
    },
    "jobId": "202307281055493641370",
    "retcode": 101,
    "retmsg": "failed"
}

**Comment by amyseoj1** [comment]
I have same issue since yesterday;

ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

**Comment by mgqa34** [comment]
> I have issue with fate flow since yesterday;
> 
> ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

Two things need to be confirmed:
1. flow init --ip ${fate_flow_service_ip} --port ${fate_flow_service_port}, check again the ip and port
2. if ip and port are correct, make sure fate_flow_server.py is still running.

**Comment by mgqa34** [comment]
> Execute: flow model load - c fateflow/examples/model/publish_ Load_ Model.json
> 
> result： { "data": { "detail": { "guest": { "9999": { "retcode": 123, "retmsg": "model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct. " } }, "host": { "10000": { "retcode": 123, "retmsg": "model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct. " } } }, "guest": { "9999": 123 }, "host": { "10000": 123 } }, "jobId": "202307281055493641370", "retcode": 101, "retmsg": "failed" }

Check again if the model_id/version is right.

**Comment by 2294930685** [comment]
@mgqa34 May I ask if I have any good solutions for this problem?

**Comment by 2294930685** [comment]
@mgqa34 I checked my model_ The ID is correct, and all steps before running were successful!

**Comment by zhihuiwan** [comment]
Code “123” means that fate serving cannot get the current model, it may be that the model has not been generated, or there may be a problem with the configuration
1. was the training job successful? The job status can be obtained through the query cli:  flow job query -j $job_id
2. is the fate serving configuration correct? please check "fate/conf/service_conf.yaml"

**Comment by 2294930685** [comment]
@zhihuiwan flow job query -j $job_id 报错Error: -j option requires an argument
