### ISSUE TITLE
fate环境里面如何使用gpu呢

### ISSUE THREAD

**Issue by zzy484** [FederatedAI/FATE#5034]

**Comment by talkingwallace** [comment]
是使用Homo-NN吗？还是什么算法呢

**Comment by zzy484** [comment]
> 是使用Homo-NN吗？还是什么算法呢

是使用homo-nn

**Comment by talkingwallace** [comment]
在trainer_param里设置cuda就可以了，https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py#L42

**Comment by zzy484** [comment]
> 在trainer_param里设置cuda就可以了，https://github.com/FederatedAI/FATE/blob/master/python/federatedml/nn/homo/trainer/fedavg_trainer.py#L42

![image](https://github.com/FederatedAI/FATE/assets/67353365/cebcb5f6-2c21-4b10-80e0-e7069e5e5574)
我这样添加之后，显示错误：ValueError: Cuda is not available on this machine
但是机器上面有设备号为0的GPU
![image](https://github.com/FederatedAI/FATE/assets/67353365/14ac74ed-c93a-43bb-8531-28ad26538566)
这是什么原因呢

**Comment by talkingwallace** [comment]
torch版本问题 看一下torch是否为cpu版本 如果是的话可以卸载重装
