### ISSUE TITLE
FATE有无和风控法务相关的文档说明？

### ISSUE THREAD

**Issue by tigflanker** [FederatedAI/FATE#5056]
首先感激FATE社区各个大佬打造并开源的FATE体系，以及多次帮助我们解决问题，
造福小公司能在遵循《个信法》的前提下，方便和其他公司展开联合建模。

求助一下FATE社区的法务大佬：
假如我想拿着FATE系统去和某家地方银行展开纵向联邦学习建模，不知道FATE有没有相关 “风控法务” 的规范文档？
在我给对方介绍FATE平台的框架和功能时，也能方便给对方法务做一些说明或者证明对方数据的安全性？

**Comment by dylan-fan** [comment]
目前社区没有这样公开文档，之前社区用户贡献的一份安全白皮书（https://github.com/FederatedAI/FATE/pull/4623）。你们可以看看是否对你们有所帮助。
此外，使用FATE软件，请关注FATE社区License（https://github.com/FederatedAI/FATE/blob/master/LICENSE） 和免责说明（https://github.com/FederatedAI/FATE/blob/master/DISCLAIMER）

**Comment by tigflanker** [comment]
@dylan-fan 感谢大佬
