### ISSUE TITLE
[Help] Key error when trying to use custom module when submitting to fateflow

### ISSUE THREAD

**Issue by PaulKMandal** [FederatedAI/FATE#5061]
Hello, everyone.

I'm trying to implement Reinforcement Learning for Fate. The main issue right now that I am having are key issues with fateflow. I guess I don't know where fateflow pulls the names of valid classes from.

Steps taken:
1. I created a file called `homo_RL.py`. Right now this is just a copy of `homo_nn.py` with the name of the class changed to `HomoRL`. I also modified the `__init__.py` in component to add my new module.

2. I ran
```
cp -f /data/projects/fate/fate/python/fate_client/pipeline/component/__init__.py /data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.11.2-py3.8.egg/pipeline/component/
cp -f /data/projects/fate/fate/python/fate_client/pipeline/component/homo_RL.py /data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.11.2-py3.8.egg/pipeline/component/
```

3. In the Homo-NN-Customize-Model.ipynb I changed 
`from pipeline.component import HomoNN` to `from pipeline.component import HomoRL`, `from pipeline.component.homo_nn import DatasetParam, TrainerParam` to from `pipeline.component.homo_RL import DatasetParam, TrainerParam`, and all instances of HomoNN to HomoRL.

4. Run Pipeline.fit and receive the following error
`ValueError: job submit failed, err msg: {'jobId': '202308211056038640280', 'retcode': 103, 'retmsg': 'Traceback (most recent call last):\n  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py", line 144, in submit\n    raise Exception("create job failed", response)\nException: (\'create job failed\', {\'guest\': {9999: {\'retcode\': 100, \'retmsg\': "KeyError(\'HomoRL\')"}}, \'host\': {10000: {\'retcode\': 100, \'retmsg\': "KeyError(\'HomoRL\')"}}, \'arbiter\': {10000: {\'retcode\': 100, \'retmsg\': "KeyError(\'HomoRL\')"}}})\n'}`

5. Cry at my desk and ponder where my life went wrong (okay, not really, but you get the idea).

Anyways, your help would be much appreciated. I'll probably need even more help if I need to modify PipeLine so that it doesn't require a dataset. Changing the train in FedAvg to implement REINFORCE won't be too difficult, so it's mainly the other library stuff that I'll likely need help with. Thanks!

**Comment by PaulKMandal** [comment]
I would very much appreciate help on this. I've been digging through fate-flow files for most of yesterday and part of today. I think it could have something to do with db_models.py or base_models.py but still can't figure it out.

@talkingwallace I see you make contributions quite often, would you happen to know the issue?

Thanks!

**Comment by PaulKMandal** [comment]
I tried adding a definition to `fate/python/federatedml/components/homo_RL.py`, but this did not work.

I saw this issue: https://github.com/FederatedAI/FATE/issues/5015#issuecomment-1660128583
but am a bit confused about what the FATE component is.

**Comment by talkingwallace** [comment]
Hi! There are several things you need to do in order to submit a pipeline job using a customized component:
1. Develop a FATE component in the federatedml, you can see how homo-nn work, your component need to subclassing ModelBase
2. Add the component define in the component folder under federatedml, see homo-nn.py as a reference
3. Develop the pipeline interface in fate_client/pipeline/component
4. After these are done, re-install fate_client( pip install -e ./fate_client) and restart fateflow, re-initialize pipeline&fateflow

Then you can submit a job which uses your component, @ me if you have any problem

**Comment by PaulKMandal** [comment]
Can you remind me what the command is for restarting fateflow and re-initializing pipeline and fateflow? Thanks!

**Comment by talkingwallace** [comment]
go to the fate project root dir:
cd fateflow
bash bin/service restart
flow init --ip xxx(your ip) --port 9380
pipeline init --ip xxx(your ip) --port 9380

**Comment by PaulKMandal** [comment]
I followed along with your steps. When I run bash bin/service.sh restart, I will get an error saying `service start failed, please check /data/projects/fate/fateflow/logs/error.log and /data/projects/fate/fateflow/logs/console.log ` I am attaching the error.log for your review. The console.log is empty. [error.log](https://github.com/FederatedAI/FATE/files/12415112/error.log)

When I attempt to run my custom module, bind table is refused connection although this should be no surprise given that the service isn't running.

Finally, I have uploaded my files [here](https://github.com/PaulKMandal/FateReinforced) if you wish to take a look.

Anyways, it's quite late here so I'm going to head off for the night, but I will be back on to review your guidance.

I appreciate all of your help!

**Comment by talkingwallace** [comment]
> @talkingwallace When you talk about the federated component, you're talking about here, right? `/fate/python/federatedml/components/`

yes

**Comment by PaulKMandal** [comment]
Hey, I got it working on a fresh standalone! I'm closing this issue for now, but I may need to create a bug report for the logs I posted above when trying to restart fateflow on the other standalone.

I'm closing this issue for now, I might need help with the homo_nn params in the federatedml/components later on.

Thanks for all of the help!
