### ISSUE TITLE
【help】flow table bind 表绑定问题

### ISSUE THREAD

**Issue by fang-zhiyou** [FederatedAI/FATE#5078]
想请教一下各位大佬：

FATE采用Eggroll架构时，table bind 能绑定 mysql，当 FATE采用Spark架构时，table bind 能绑定 hdfs吗？
FATE eggroll架构 只能 绑定mysql？
FATE spark 架构 只能 绑定hdfs吗？

这里的绑定，指的是通过 flow table bind 命令进行表绑定。谢谢各位大佬

**Comment by zhihuiwan** [comment]
是可以的， FATE spark 架构 可以绑定mysql和hdfs。
