### ISSUE TITLE
Cannot start fate flow service

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#5079]
Hello, 

I keep getting error saying "retmsg": "Connection refused, Please check if the fate flow service is started" 
even after running 

cd /data/projects/fate/python/fate_flow
sh service.sh restart

I cannot get it to start working. This problem occurs frequently.

**Comment by talkingwallace** [comment]
if starting fails, it will give you the location of the error logs, you can check the error log, or post log here so that I can see what happened
