### ISSUE TITLE
通过yarn和cluster模式提交任务到spark

### ISSUE THREAD

**Issue by iceicei** [FederatedAI/FATE#5119]
当前底层计算引擎为Spark的使用模式不够解耦，希望能支持通过yarn和cluster模式提交任务到spark

**Comment by iceicei** [comment]
我看到FATE-Flow v1.10.0时有类似排期但是在v1.10和v1.11的版本更新说明中都没有提到

**Comment by dylan-fan** [comment]
可以使用fate 2.x
