### ISSUE TITLE
How to clean the data cache, and use own data

### ISSUE THREAD

**Issue by xiaopengu** [FederatedAI/FATE#513]
**Describe the bug**
1. When I use my own data to run the secureboost algorithm with quick_run.py, I revise the upload_data.json and corresponding variable in quick_run.py and configure .json of secureboost, however, dataIO failed. So I just replace the given data with my own data.
2. When I replace the datasets in the examples/data with my own data and use the same data file name as the replaced one. However, after running the examples with quick_run.py, the data output shows that I still use the original given data.  Is it because the uploaded the data cache in the previous trials. So I wonder how to clear the upload data cache.

**Comment by mgqa34** [comment]
Can you paste "upload_data.json" and the error log of dataio？
