### ISSUE TITLE
用FATE上传数据了A，然后想往A中添加一部分数据B，这A跟B能merge吗？

### ISSUE THREAD

**Issue by Yonggie** [FederatedAI/FATE#5209]
同一用户id，用pipeline上传数据了A，然后想往A中添加一部分数据B，这A跟B能merge吗，还是只能用其他的namespace和table了？

如果能，请问下怎么操作？
如果不能，能在train的时候pipeline中一个id能bind多个table吗，还是一个用户id只能绑定一个数据table？

**Comment by mgqa34** [comment]
> 同一用户id，用pipeline上传数据了A，然后想往A中添加一部分数据B，这A跟B能merge吗，还是只能用其他的namespace和table了？
> 
> 如果能，请问下怎么操作？ 如果不能，能在train的时候pipeline中一个id能bind多个table吗，还是一个用户id只能绑定一个数据table？

1. 这里的用户id的概念是怎样的呢？
2. 使用同一张表，然后将drop参数设置为0，使用的是append的模式，会增加B这部分数据。
3. "能在train的时候pipeline中一个id能bind多个table吗"，这句话具体操作指的是？一个用户可以上传任意个table的，这里是否想说的是算法组件接受多table输入呢？

**Comment by Yonggie** [comment]
你好，谢谢。
1. 用户id就是guest_id，就是同一个人的意思。id不一样上传到同个namespace+table的话应该会报错吧。
2. 想问下如果是自定义的dataset，drop=0也起作用吗？
3. 在submit新task的时候reader要读取绑定table，意思是一个角色是否能绑定多个table？比如A角色read ``a,b,c``三个table，B角色read ``d``table，然后A、B共同参与训练。A之所以要绑定三个，是因为A上传了3次，不能append，所以bind 3个。

如果drop=0对自定义的数据也有效，那这个问题就解决了，谢谢！
