### ISSUE TITLE
Sample Project on VFL

### ISSUE THREAD

**Issue by anaclumos** [FederatedAI/FATE#5210]
Hi,

[Can FATE Work in Vertical Federated Learning Scenario? · Issue #2785 · FederatedAI/FATE](https://github.com/FederatedAI/FATE/issues/2785) mentions that https://github.com/FederatedAI/FATE/tree/master/python/federatedml folder has the hetero algorithms. However, I am having difficulty finding VFL samples in the folder. Can anyone help?

**Comment by anaclumos** [comment]
https://github.com/FederatedAI/FATE/blob/v2.0.0-beta/doc/2.0/fate/ml/hetero_secureboost_tutorial.ipynb

**Comment by mgqa34** [comment]
> Hi,
> 
> [Can FATE Work in Vertical Federated Learning Scenario? · Issue #2785 · FederatedAI/FATE](https://github.com/FederatedAI/FATE/issues/2785) mentions that https://github.com/FederatedAI/FATE/tree/master/python/federatedml folder has the hetero algorithms. However, I am having difficulty finding VFL samples in the folder. Can anyone help?

All components are listing in this [readme](https://github.com/FederatedAI/FATE/blob/master/doc/federatedml_component/README.md)，search keyword "Hetero" in this tutorial will help.

**Comment by anaclumos** [comment]
Thank you so much!
