### ISSUE TITLE
使用fate_standalone 测试线性归回时，data_transform组件报错

### ISSUE THREAD

**Issue by stupidhhh** [FederatedAI/FATE#5212]
fate-board错误信息如下:
![image](https://github.com/FederatedAI/FATE/assets/93757135/373a4e1d-ab52-4a24-8007-c29384aa24f1)
测试数据如下：
![image](https://github.com/FederatedAI/FATE/assets/93757135/2da859ec-2d9c-4def-8e48-741a83323def)
![image](https://github.com/FederatedAI/FATE/assets/93757135/1a8a1d5d-99f5-483a-a302-c8dccb002275)
代码如下：
![image](https://github.com/FederatedAI/FATE/assets/93757135/5c327ea4-8138-4b2d-bbc4-c136217aaac9)

**Comment by mgqa34** [comment]
从报错来看，(namespace=guest_train, name=house_price_guest)这份数据并没有"y"列，可以flow table info -t "house_price_guest" -n "guest_train"查询下header是否有问题，看下上传是否有误，或者直接下载下来确认下。

**Comment by stupidhhh** [comment]
> 从报错来看，(namespace=guest_train, name=house_price_guest)这份数据并没有"y"列，可以flow table info -t "house_price_guest" -n "guest_train"查询下header是否有问题，看下上传是否有误，或者直接下载下来确认下。

我把服务重新安装了一下  代码和数据都没改 跑起来报了别的错
![image](https://github.com/FederatedAI/FATE/assets/93757135/e70918be-f889-405f-8314-3ca6309c5395)
flow table info -t "house_price_guest" -n "guest_train" 这条命令执行后看到header里有y了
![image](https://github.com/FederatedAI/FATE/assets/93757135/4100d6b4-e438-4364-932f-06674567317e)

**Comment by stupidhhh** [comment]
> > > 从报错来看，(namespace=guest_train, name=house_price_guest)这份数据并没有"y"列，可以flow table info -t "house_price_guest" -n "guest_train"查询下header是否有问题，看下上传是否有误，或者直接下载下来确认下。
> > 
> > 
> > 我把服务重新安装了一下 代码和数据都没改 跑起来报了别的错 ![image](https://user-images.githubusercontent.com/93757135/270907014-e70918be-f889-405f-8314-3ca6309c5395.png) flow table info -t "house_price_guest" -n "guest_train" 这条命令执行后看到header里有y了 ![image](https://user-images.githubusercontent.com/93757135/270907315-4100d6b4-e438-4364-932f-06674567317e.png)
> 
> label_type设置为"float “，从图片看，是用的浮点数 data_transform_0_guest_party_instance.component_param(with_label=True, label_type="float", output_format="dense")

加上 label_type="float" 后又报了Count of data_instance is 0
![image](https://github.com/FederatedAI/FATE/assets/93757135/76716a28-5190-4ca9-b61a-9406b99d29ea)
