### ISSUE TITLE
评分卡流程中横向特征分箱问题

### ISSUE THREAD

**Issue by iceicei** [FederatedAI/FATE#5219]
通常评分卡（逻辑回归）的入模特征为woe转换特征，但是目前在横向特征分箱中设置transform_param的transform_type为"woe"时会报异常。
![横向分箱woe](https://github.com/FederatedAI/FATE/assets/33820976/86badbd8-1c68-4f9c-8608-23719b0e3514)

**Comment by mgqa34** [comment]
横向特征分箱不支持woe/iv值的计算，仅做分箱功能

**Comment by iceicei** [comment]
> 横向特征分箱不支持woe/iv值的计算，仅做分箱功能

现有的使用homo lr的评分卡流程不支持分箱以及计算woe/iv值，对于特征多的数据无法进行特征筛选，导入很多无效/冗余特征入模，这个后续有相关的计划吗。还有评分卡在金融领域也是用的比较多的，横向特征分箱不支持woe/iv计算的话，对于评分卡的效果（稳定性等）来说是大打折扣的，无法查看分箱的具体信息以及每箱的具体分数，目前的评分卡无法查看单个样本每个特征的单独评分，这样的话，对于要求可解释的场景下是不适用的，而且评分卡目前使用的场景基本都对可解释性有一定的要求。
