### ISSUE TITLE
sh run.sh guest fast ${host_table} ${host_namespace} failed

### ISSUE THREAD

**Issue by caolin12** [FederatedAI/FATE#522]
Hello!
When I run:
sh run.sh guest fast host_table_name_1567432160_7370  host_table_namespace_1567432160_7370
then something occured below,and there is no errors in logs;
....
[Intersect] Start intersect job status checker, status counter: 56, jobid:201909022152082643742
[Intersect] cur job status:running, wait_time: 583.2567648887634
[Intersect] Start intersect job status checker, status counter: 57, jobid:201909022152082643742
[Intersect] cur job status:running, wait_time: 593.5020263195038
[Intersect] Start intersect job status checker, status counter: 58, jobid:201909022152082643742
[Intersect] cur job status:running, wait_time: 603.73965716362
[Intersect] reach max intersect time:{}, intersect task may be failed, and exit now
Traceback (most recent call last):
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 500, in <module>
    raise ValueError("intersect task is failed")
ValueError: intersect task is failed
*********************
*******finish!*******

**Comment by zhuchangjiang** [comment]
i meet this problem，can you tell me hwo do you slove it!

**Comment by chenj133** [comment]
i meet this problem too，can you tell me hwo do you slove it!
