### ISSUE TITLE
homo_sbt 报错。

### ISSUE THREAD

**Issue by summerghw** [FederatedAI/FATE#5221]
![image](https://github.com/FederatedAI/FATE/assets/39901746/860228c0-4f1e-458b-ab08-452d85d8f153)
是否因为homo_sbt只接受x0，x1命名的feature？

**Comment by mgqa34** [comment]
标签列需要从0开始的连续整数，如果不是的话，可以用label_transform组件做一个转换或者自己清洗数据

**Comment by summerghw** [comment]
@mgqa34 谢谢。
通过将结局变量调整为0，1，2的分类型变量可以正常运行。
现在遇到了另一个问题。我将我的测试总结为下图。
![image](https://github.com/FederatedAI/FATE/assets/39901746/03027236-82af-40d5-880d-d51e0349f27d)
得出多分类型不支持评估的依据是：
1.说明文档中的这个参数的解释。
![image](https://github.com/FederatedAI/FATE/assets/39901746/5aec4797-5543-421d-87c1-c821784817ec)
2.一个多分类的评估结果中只有二元分类的结果：
![image](https://github.com/FederatedAI/FATE/assets/39901746/7e5e0906-a6df-4ad9-8efc-649013225c7e)
请问，这个结论是正确的吗？

**Comment by talkingwallace** [comment]
多分类评估是支持的，填multi即可

**Comment by summerghw** [comment]
@talkingwallace thx，multi可以的。
另外我发现reader中的id是升序，datatransform中则为乱序，请问这是为什么呢？
![image](https://github.com/FederatedAI/FATE/assets/39901746/3827ae5c-ea59-46f1-8640-e32bf95f7579)

**Comment by mgqa34** [comment]
> @talkingwallace thx，multi可以的。 另外我发现reader中的id是升序，datatransform中则为乱序，请问这是为什么呢？ ![image](https://private-user-images.githubusercontent.com/39901746/276073098-3827ae5c-ea59-46f1-8640-e32bf95f7579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDE0MTksIm5iZiI6MTcyMDYwMTExOSwicGF0aCI6Ii8zOTkwMTc0Ni8yNzYwNzMwOTgtMzgyN2FlNWMtZWE1OS00NmYxLTg2NDAtZTMyYmY5NWY3NTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA4NDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNTg1OGI2NGZmNDNmNGZlOWNjNDNhMTljZmY1M2E4OTYwYmM0ODU4N2U2OGY2ZWEwNzgxZWEwZGNhNWJjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aCQbeK1V2P9R6lLd1YFb8BKIXCUYxHKmgpNSakOC1BI)

data_transform的输出不能假设有序，它是一个分布式的数据表，fateboard选择输出100条，这100条不一定有序的
