### ISSUE TITLE
heterosbt现在能直接支持类别特征的输入吗?

### ISSUE THREAD

**Issue by harmony0303** [FederatedAI/FATE#5231]
heterosbt现在能直接支持类别特征的输入吗?此外就是将数据拼接起来使用lightgbm效果差异大吗

**Comment by talkingwallace** [comment]
目前使用不了categorical特征的，需要做one-hot处理

**Comment by harmony0303** [comment]
> 目前使用不了categorical特征的，需要做one-hot处理

谢谢您!另外我看现在sbt基本基于是lightgbm的方法,有没有和集中式lightgbm的效果对比文档或论文呢?

**Comment by talkingwallace** [comment]
examples 下的 benchmark quality 有与Sklearn GDBT的对比的程序文档，实际使用中SBT和xgb，lgb效果是基本接近的

**Comment by harmony0303** [comment]
> examples 下的 benchmark quality 有与Sklearn GDBT的对比的程序文档，实际使用中SBT和xgb，lgb效果是基本接近的

再次请问一下您，我这边有特征比较稀疏的数据集（如Criteo），做one-hot会导致特征维度很大，这样SBT和lgb效果也会接近吗？
