### ISSUE TITLE
使用docker训练HeteroSecureBoost pipeline.fit()报错

### ISSUE THREAD

**Issue by Worshipper6** [FederatedAI/FATE#5237]
**ValueError: Job is failed, please check out job 202310281308283488000 by fate board or fate_flow cli**
Traceback (most recent call last):
  File "share_mac/pipeline_hetero_sbt.py", line 43, in <module>
    pipeline.fit()
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/loguru/_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.11.3-py3.8.egg/pipeline/backend/pipeline.py", line 585, in fit
    self._fit_status = self._job_invoker.monitor_job_status(self._train_job_id,
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-1.11.3-py3.8.egg/pipeline/utils/invoker/job_submitter.py", line 94, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")

**fateflow/logs**
error.log
E1028 13:08:29.075821459     761 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
E1028 13:08:55.277860138     886 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
E1028 13:08:55.315456972     891 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
E1028 13:09:18.137453885     986 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
E1028 13:09:24.305093054    1012 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
E1028 13:09:30.131427585    1022 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
E1028 13:09:35.703897004    1029 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers

**WARNING log**
[WARNING] [2023-10-28 13:08:39,344] [Server] [70:276736354048] - [evaluation_param.check] [line:135]: use default metric ['auc', 'ks', 'lift', 'gain', 'accuracy', 'precision', 'recall', 'roc', 'confusion_mat', 'psi', 'f1_score', 'quantile_pr'] for eval type binary
[WARNING] [2023-10-28 13:08:39,775] [Server] [70:276736354048] - [evaluation_param.check] [line:135]: use default metric ['auc', 'ks', 'lift', 'gain', 'accuracy', 'precision', 'recall', 'roc', 'confusion_mat', 'psi', 'f1_score', 'quantile_pr'] for eval type binary
[WARNING] [2023-10-28 13:09:01,121] [Server] [70:278257219328] - [process_utils.get_process_instance] [line:231]: no such process 797
[WARNING] [2023-10-28 13:09:01,174] [Server] [70:276736354048] - [process_utils.get_process_instance] [line:231]: no such process 787
[WARNING] [2023-10-28 13:09:01,850] [Server] [70:278551095040] - [process_utils.get_process_instance] [line:231]: no such process 787
[WARNING] [2023-10-28 13:09:07,327] [Server] [70:278551095040] - [process_utils.get_process_instance] [line:231]: no such

**Comment by mgqa34** [comment]
查询日志的位置应该是fateflow/logs/${job_id}下的，需要查下所有方的日志确认到底哪一方抛出的错误
