### ISSUE TITLE
Try to setup standalone docker

### ISSUE THREAD

**Issue by ZiyueXu77** [FederatedAI/FATE#5247]
**Describe the bug**
Cannot get access to standalone docker, temporary docker unavailability?

**To Reproduce**
upon running
sudo docker pull federatedai/standalone_fate:1.11.3
or 
sudo docker pull ccr.ccs.tencentyun.com/federatedai/standalone_fate:1.11.3

Got error
Error response from daemon: manifest for federatedai/standalone_fate:1.11.3 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for ccr.ccs.tencentyun.com/federatedai/standalone_fate:1.11.3 not found: manifest unknown: manifest unknown

and the link cannot be reached
https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/fate/1.11.3/release/standalone_fate_install_1.11.3_release.tar.gz

**Expected behavior**
successful docker pull

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhihuiwan** [comment]
Thank you very much for your feedback; it has already been fixed.

**Comment by ZiyueXu77** [comment]
Thanks! it works now
