### ISSUE TITLE
Docker单机部署的FATE问题

### ISSUE THREAD

**Issue by harmony0303** [FederatedAI/FATE#5250]
跟着文档安装了单机版的docker后，之后文档太多有点看晕了。主要请问一下两个问题：
1、可以使用Pycharm直接连接docker里的FATE吗，我查询了一下没有查询到，有相应的文档吗？
2、对我自己的数据集想要进行联邦下的训练，我是需要先传入docker容器里，再根据pipeline文档里的.ipynb文件，重写一个自己的python文件再进行执行吗？
十分感谢您的回答。

**Comment by harmony0303** [comment]
> 跟着文档安装了单机版的docker后，之后文档太多有点看晕了。主要请问一下两个问题： 1、可以使用Pycharm直接连接docker里的FATE吗，我查询了一下没有查询到，有相应的文档吗？ 2、对我自己的数据集想要进行联邦下的训练，我是需要先传入docker容器里，再根据pipeline文档里的.ipynb文件，重写一个自己的python文件再进行执行吗？ 十分感谢您的回答。

直接在docker容器里安装jupyter notebook，pycharm链接可通过ssh，已解决这两个问题

**Comment by SJTUHGX** [comment]
> > 跟着文档安装了单机版的docker后，之后文档太多有点看晕了。主要请问一下两个问题： 1、可以使用Pycharm直接连接docker里的FATE吗，我查询了一下没有查询到，有相应的文档吗？ 2、对我自己的数据集想要进行联邦下的训练，我是需要先传入docker容器里，再根据pipeline文档里的.ipynb文件，重写一个自己的python文件再进行执行吗？ 十分感谢您的回答。
> 
> 直接在docker容器里安装jupyter notebook，pycharm链接可通过ssh，已解决这两个问题

想问下，在单机版容器里面安装jupyter notebook后，具体的需要修改哪些配置，才可以在容器外面，通过web端访问到jupyter界面。

**Comment by harmony0303** [comment]
> > > 跟着文档安装了单机版的docker后，之后文档太多有点看晕了。主要请问一下两个问题： 1、可以使用Pycharm直接连接docker里的FATE吗，我查询了一下没有查询到，有相应的文档吗？ 2、对我自己的数据集想要进行联邦下的训练，我是需要先传入docker容器里，再根据pipeline文档里的.ipynb文件，重写一个自己的python文件再进行执行吗？ 十分感谢您的回答。
> > 
> > 
> > 直接在docker容器里安装jupyter notebook，pycharm链接可通过ssh，已解决这两个问题
> 
> 想问下，在单机版容器里面安装jupyter notebook后，具体的需要修改哪些配置，才可以在容器外面，通过web端访问到jupyter界面。

将docker容器的jupyter端口映射到宿主机，是在容器启动的时候进行的
