### ISSUE TITLE
求交算法rsa，数据量达到千万级，亿级会卡住

### ISSUE THREAD

**Issue by zzgls** [FederatedAI/FATE#5254]
A，B_1000w都为1000万级数据，已经已经运行了17个小时没有结果，也没有任何的报错，如果数据降为100w则十几分钟可以计算完毕！！！

![微信图片_20231109142116](https://github.com/FederatedAI/FATE/assets/32196288/a067b39d-eb9a-4a74-8548-103c9c7bddeb)

![微信图片_20231109142132](https://github.com/FederatedAI/FATE/assets/32196288/5eee4f4e-e16e-4490-b2ac-b4d43760f989)

**Comment by Joe12-24** [comment]
你这个是数据求交吗, 想问下是如何部署的, 几个节点, 有中心服务器吗, 怎么没找到求交这块的部署文档

**Comment by sabakioukenasai** [comment]
FATE框架中rsa_intersect算法效率确实比较低，可以考虑替换为dh_intersect，会稍微好一点。

**Comment by dylan-fan** [comment]
可以考虑用ECDH算法，这个比较快
