### ISSUE TITLE
Provide an "estimated time cost" for example cases

### ISSUE THREAD

**Issue by ZiyueXu77** [FederatedAI/FATE#5256]
**Is your feature request related to a problem? Please describe.**
I am running a testing example with standalone docker 1.11.3: "https://github.com/FederatedAI/FATE/blob/master/examples/benchmark_quality/hetero_sbt/fate-sbt.py" with basic binary setting "https://github.com/FederatedAI/FATE/blob/master/examples/benchmark_quality/hetero_sbt/fate_sbt_binary.yaml".

The training time is about 11 min.
I am not sure if such time cost is expected / reasonable, or if I made any mistakes during my experiment setting up. This is mainly because if I perform centralized xgboost training, the training will finish within seconds.

**Describe the solution you'd like**
I hope an "expected running time" can be added to each of the examples (under certain hardware/system configurations), so that users will roughly know what to expect for training time.

**Describe alternatives you've considered**
Some instructions on the common time consumption for different computations and tricks that can be added for speed improvement

**Additional context**

**Comment by talkingwallace** [comment]
Hi! The training time of the example case on your machine is in expectation. Federated sbt training requires Paillier cipher computations which cost much time than centralized plaintext computing.

**Comment by talkingwallace** [comment]
You can refer to this paper: https://arxiv.org/abs/2110.10927, to have a general sense of training time cost.

**Comment by ZiyueXu77** [comment]
The default is without encryption right?

**Comment by talkingwallace** [comment]
> The default (not providing "Paillier" to encrypt_param) is without performing any encryption right?

yes, default is Paillier

**Comment by ZiyueXu77** [comment]
ah I see, so there is no option to "turn-off" the encryption (just to check the "base" time cost)?
