### ISSUE TITLE
添加合作方后可以不用重启rollsite容器就能实现多方之间的通讯吗?

### ISSUE THREAD

**Issue by 123fei1** [FederatedAI/FATE#5258]
**Is your feature request related to a problem? Please describe.**
目前我添加合作方后需要重启容器两方才能正常通讯, 否则就会报"Federated schedule error".     我用的fate是1.9.0版本一套源代码

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mgqa34** [comment]
只需要在conf/route_table.json下增删就行，这个是自动生效的，无需重启

**Comment by 123fei1** [comment]
> 只需要在conf/route_table.json下增减就行，这个是自动生效的，重启即可

我希望是在不重启的情况下就能与新添加的合作方发起通讯,  因为如果重启的话会出现我已经在运行的作业中间有五分钟会处于等待状态(不做功)五分钟后才继续执行,我就是想看看有没有在不重启的情况下还能与新添加的合作方做任务

**Comment by 123fei1** [comment]
> 只需要在conf/route_table.json下增删就行，这个是自动生效的，无需重启
问下您用到代理了吗,我是加了一个代理,是不是因为这个代理引起的我必须要重启
