### ISSUE TITLE
请问关于hetero_nn的交互层数据输入shape 的问题

### ISSUE THREAD

**Issue by AwinChen** [FederatedAI/FATE#5261]
关于hetero_nn的交互层interactive_layer的输入的数据形状可以是多维的吗，按教程上所讲的，纵向联邦学习框架的交互层输入通常是一个shape为（batsize_size, dim）的数据，想问下这个交互层的输入的tensor可以支持多维的吗？最近我想自定义一个VFL神经网络，目前还不能跑通（加密交互层的矩阵相乘出现了问题），十分感谢与期待您的回复~

**Comment by talkingwallace** [comment]
多维指的是 3个dim以上么？

**Comment by AwinChen** [comment]
是的 请教下，交互层可以实现3个dim以上的数据吗

**Comment by talkingwallace** [comment]
加密层目前是没办法的，只能进行2D的运算的 如果修改代码为明文的linear 层 那应该是OK的

**Comment by AwinChen** [comment]
> 加密层目前是没办法的，只能进行2D的运算的 如果修改代码为明文的linear 层 那应该是OK的

十分感谢您的答复~我看了源码发现有interactive_layer.py和he_interactive_layer.py两个交互层文件，您说的 ‘’修改为明文的linear层‘’ 是指把he_interactive_layer.py替换成interactive_layer.py使用吗，还是直接在he_interactive_layer.py里面的相关函数方法上做改动？具体该怎么修改呢？

**Comment by talkingwallace** [comment]
这里面应该有个参数可以直接改为明文的，请问你现在问题解决了么？
