### ISSUE TITLE
删除SessionRecord导致eggroll资源无法回收

### ISSUE THREAD

**Issue by zchunhai** [FederatedAI/FATE#5262]
当系统负载较高时，fateflow可能暂时性的访问不通eggroll
这里捕获到Exception时，直接删除SessionRecord，可能导致eggroll对应的egg_pair进程无法退出。
是否可以增加重试机制呢？

https://github.com/FederatedAI/FATE/blob/87dd4f63869b995b6bef3d49b1b7d1cb346806ec/python/fate_arch/session/_session.py#L408

@zhihuiwan

**Comment by zhihuiwan** [comment]
此问题已经在最新版本修复， 感谢您的反馈！
