### ISSUE TITLE
Saving Cross-Validation Model 

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#5264]
Hello, 
I was wondering if there is any way to save cross-validation models trained on different folds of the data. 
I need to apply each of the cross-validation model to new incoming data and evaluate. 
Is there any way to achieve this ?

**Comment by mgqa34** [comment]
Fate does not save models in CV mode, you may modify the code to achieve this.
Take a look this [link](https://github.com/FederatedAI/FATE/blob/master/python/federatedml/callbacks/callback_list.py), use checkpoints to save every fold's model, also refer to how the training algorithm using "callback_list" attribute to save model checkpoints.  You should also integrate this into [CV process](https://github.com/FederatedAI/FATE/blob/master/python/federatedml/model_selection/k_fold.py#L162). Finally, use model loader to load checkpoint and evaludate new data.
