### ISSUE TITLE
Feature Scaling in Cross Validation 

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#5265]
Hello, 

When I do cross-validation, I want to do feature scaling on the training data and apply the same transformation to the validation data in each fold. Is there a way to do this in FATE ? 

Thank you !

**Comment by mgqa34** [comment]
If you need to do scaling again on each fold, it means that every fold's training and validate dataset can be totally different (maybe not from same distribution as data scales at each fold). Why don't you split the datasets in local scripts and upload them to fate, then run different jobs?

**Comment by mgqa34** [comment]
> If you need to do scaling again on each fold, it means that every fold's training and validate dataset can be totally different (maybe not from same distribution as data scales at each fold). Why don't you split the datasets in local scripts and upload them to fate, then run different jobs?

By this way, #5264 can also be solved without code developing.

**Comment by amyseoj1** [comment]
Oh okay. I guess I can't avoid manual work :( 
Thank you for your insight !
