### ISSUE TITLE
请问有关于HeteroNN训练中Interactive Layer的噪声问题

### ISSUE THREAD

**Issue by ATowerz** [FederatedAI/FATE#5280]
1.请问一下这个梯度下降时的噪声有参数进行控制吗？

2.我看了一下RandomNumberGenerator文件，这个噪声的生成的随机值范围是在[-1024,1024]区间，我记得在预测的时候interactive_layer的输出值和self.acc_noise累计噪声是相关的，累计噪声的数值波动大不会使host方的预测大幅度失真而导致heteroNN效果不佳吗？

**Comment by talkingwallace** [comment]
hi 噪声在训练&预测的时候都会抵消的，不会影响到预测结果，这个目前没有相关控制参数

**Comment by ATowerz** [comment]
> hi 噪声在训练&预测的时候都会抵消的，不会影响到预测结果，这个目前没有相关控制参数

您好，我还是有点疑惑，在https://github.com/FederatedAI/FATE/blob/master/doc/federatedml_component/hetero_nn.md中，interactive layer在激活前的输出值为z = z_A + epsilon_acc * alpha_A + z_B(if exists)，这部分epsilon_acc* alpha_A是没有影响的吗？然后梯度下降时A方生成的随机值范围是在[-1024,1024]区间，累加后是epsilon_acc，epsilon_acc的噪声太大不会导致预测失真吗，这里我是哪里理解错误了呢

**Comment by talkingwallace** [comment]
Hi! https://arxiv.org/pdf/2007.06849.pdf 可以参考这篇文章的，噪声在整个训练过程中是会抵消的
