### ISSUE TITLE
API /data/download下载计算后的数据无输出

### ISSUE THREAD

**Issue by liyuu127** [FederatedAI/FATE#5296]
我运行官网给出的PIR计算过程，Job返回成功，dashboard上也可以看到输出的数据。
API /job/submit任务返回：
{"data":{"board_url":"http://fateboard:8080/index.html#/dashboard?job_id=202311281941010398530&role=guest&party_id=10000","code":0,"dsl_path":"/data/projects/fate/fateflow/jobs/202311281941010398530/job_dsl.json","job_id":"202311281941010398530","logs_directory":"/data/projects/fate/fateflow/logs/202311281941010398530","message":"success","model_info":{"model_id":"guest-10000#host-9999#model","model_version":"202311281941010398530"},"pipeline_dsl_path":"/data/projects/fate/fateflow/jobs/202311281941010398530/pipeline_dsl.json","runtime_conf_on_party_path":"/data/projects/fate/fateflow/jobs/202311281941010398530/guest/10000/job_runtime_on_party_conf.json","runtime_conf_path":"/data/projects/fate/fateflow/jobs/202311281941010398530/job_runtime_conf.json","train_runtime_conf_path":"/data/projects/fate/fateflow/jobs/202311281941010398530/train_runtime_conf.json"},"jobId":"202311281941010398530","retcode":0,"retmsg":"success"}
dashboard job：
<img width="1169" alt="截屏2023-11-29 09 28 38" src="https://github.com/FederatedAI/FATE/assets/48463783/05792e6c-0089-415a-8922-305e9e2e32b8">
<img width="1409" alt="截屏2023-11-29 09 27 59" src="https://github.com/FederatedAI/FATE/assets/48463783/e46b44e5-e043-40c1-87c0-86fa94a458a5">

我想要使用API下载输出的数据，于是使用/table/list先查询了这次job的数据列表：
{"data":{"data_transform_0":{"input":{"reader_0.data":{"name":"05ea41a48de311eeb2cf0242c0a70064","namespace":"output_data_202311281941010398530_reader_0_0"}},"output":{"data":{"name":"0d1ed8908de311ee941b0242c0a70064","namespace":"output_data_202311281941010398530_data_transform_0_0"}}},"reader_0":{"input":{"table":{"name":"breast_hetero_host","namespace":"experiment"}},"output":{"data":{"name":"05ea41a48de311eeb2cf0242c0a70064","namespace":"output_data_202311281941010398530_reader_0_0"}}},"secure_information_retrieval_0":{"input":{"data_transform_0.data":{"name":"0d1ed8908de311ee941b0242c0a70064","namespace":"output_data_202311281941010398530_data_transform_0_0"}},"output":{"data":{"name":"32f7cc2a8de311ee96cd0242c0a70064","namespace":"output_data_202311281941010398530_secure_information_retrieval_0_0"}}}},"retcode":0,"retmsg":"success"}

后面选择我需要的地址和数据调用data/download进行下载
download(base_url_10000, '/Users/liyu/workplace/project/gitlab/dmp/FATE-example-python/examples/fate_flow/pir/data/breast_hetero_host_pir.csv', "output_data_202311281941010398530_secure_information_retrieval_0_0", "32f7cc2a8de311ee96cd0242c0a70064")
输出响应：
{"data":{"board_url":"http://fateboard:8080/index.html#/dashboard?job_id=202311282006298852370&role=local&party_id=0","code":0,"dsl_path":"/data/projects/fate/fateflow/jobs/202311282006298852370/job_dsl.json","job_id":"202311282006298852370","logs_directory":"/data/projects/fate/fateflow/logs/202311282006298852370","message":"success","model_info":{"model_id":"local-0#model","model_version":"202311282006298852370"},"pipeline_dsl_path":"/data/projects/fate/fateflow/jobs/202311282006298852370/pipeline_dsl.json","runtime_conf_on_party_path":"/data/projects/fate/fateflow/jobs/202311282006298852370/local/0/job_runtime_on_party_conf.json","runtime_conf_path":"/data/projects/fate/fateflow/jobs/202311282006298852370/job_runtime_conf.json","train_runtime_conf_path":"/data/projects/fate/fateflow/jobs/202311282006298852370/train_runtime_conf.json"},"jobId":"202311282006298852370","retcode":0,"retmsg":"success"}
下载接口显示成功并且控制台日志输出也正常：
[INFO] [2023-11-28 20:06:40,805] [202311282006298852370] [11832:140548080904000] - [download._run] [line:75]: ===== export 569 lines totally =====
200
[INFO] [2023-11-28 20:06:40,806] [202311282006298852370] [11832:140548080904000] - [download._run] [line:76]: ===== export data finish =====
201
[INFO] [2023-11-28 20:06:40,806] [202311282006298852370] [11832:140548080904000] - [download._run] [line:77]: ===== export data file path:/Users/liyu/workplace/project/gitlab/dmp/FATE-example-python/examples/fate_flow/pir/data/breast_hetero_host_pir.csv =====

但是实际上我并没有在本地发现这个文件，请问是哪一步配置有误么。

**Comment by zhihuiwan** [comment]
请问下client和fateflow server不在一台机器吗？这个download的路径是在服务器上的

**Comment by zhihuiwan** [comment]
你可以使用pipeline调用component.output_data_table接口将组件的输出数据拉回到客户端
