### ISSUE TITLE
socket timeout报错，如何设置run_ip

### ISSUE THREAD

**Issue by LGDchampion** [FederatedAI/FATE#5299]
我使用pipeline构建神经网络，横向联邦学习任务。
自定义模型和数据问题解决，使用pipeline构建任务，可以运行pipeline.fit开始训练，可以看见日志显示任务训练了设定的epoch，但是训练完毕后报错socket.timeout，我猜测是run_ip显示为'run_ip': 'xxx.xxx.xxx.xxx'导致。

日志显示的参数如下
{'job_id': '202311290103155381610', 'component_name': 'reader_0', 'task_id': '202311290103155381610_reader_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': 'xxx.xxx.xxx.xxx', 'run_pid': 467154, 'run_port': '9380', 'party_status': 'running'}

**Comment by zhihuiwan** [comment]
run_ip是由系统设置的，为fate-flow的服务ip
socket.timeout有没有详细的报错信息？
