### ISSUE TITLE
Support for secret sharing scheme

### ISSUE THREAD

**Issue by yankang18** [FederatedAI/FATE#53]
**Is your feature request related to a problem? Please describe.**
Secret sharing Scheme is a must-have for FATE project. 

**Describe the solution you'd like**
Do R&D on implementing secret sharing operations, such as:
1. Create beaver triple
2. Add, Multiply, Division, Compare, and others

Having secret sharing operations been created, then
1. Implement secret sharing based LR
2. Implement secret sharing based FTL

These works do not need to be full-fledged for industrial applications. However, they should be able to help us create various secure federated learning algorithms/prototypes.

**Comment by dylan-fan** [comment]
This is an important feature. Secret sharing based LR(hetero & homo) can work with mingchao & hartin.  They also focus on this in the next version and some work will be reused.
Also some numeric operator on secret-share will be implemented in secureprotol module.

**Comment by dylan-fan** [comment]
Beaver triples maybe not a better solution which needs a trusted third party. 
We can implement multiplication triplets by offline on HE, which don't need a trusted third party.

**Comment by chenjinhua1993** [comment]
so , secret sharing feature now is not implemented?
