### ISSUE TITLE
bin/service.sh: line 75: lsof: command not found service not running

### ISSUE THREAD

**Issue by zziliang** [FederatedAI/FATE#5306]
I had a problem installing FATE. in the "FATE Standalone Deployment Guide", instead of using docker, I use "Install FATE in the host (using the compiled installer)", Run "`bash bin/init.sh Init` "after I met"`/private/standalone_fate_install_1. 11.4 _release/env/python/venv/lib/python3.8 / site - packages/setuptools / _distut ilscationWarning: setup.py install is deprecated`.", see the screenshot below for details. Then, I run "`bash bin/init.sh status`", the system will appear "`bin/service.sh: line 75: lsof: command not found service not running`", see the screenshot below for details.

**Screenshots**
![1701916183980](https://github.com/FederatedAI/FATE/assets/87296854/e99f8f1f-6a9f-4e7d-85cd-cc4ca6f2ebbc)

![1701916311587](https://github.com/FederatedAI/FATE/assets/87296854/ca9bdeb0-34dc-4cb4-8435-d628b3455b83)

 - OS: ubuntu20.04

**Comment by LeoLiding** [comment]
how do you solve this problem?
