### ISSUE TITLE
HeteroNN的使用问题

### ISSUE THREAD

**Issue by harmony0303** [FederatedAI/FATE#5362]
1. 好像HomoNN可以设置Cuda进行加速，HeteroNN参数列表好像没有这个参数？docker版的FATE好像也是cpu版本。

2. 对于我的HeteroNN训练的比较慢，目前需要的是在FATE下验证其性能，暂时不需要考虑隐私保护，有什么办法可以禁用其隐私保护方式，如将同态加密的密文使用明文计算，来提升训练速度的此类方式吗

谢谢您的解答！

**Comment by dylan-fan** [comment]
实验的话，可以考虑手动魔改代码，关掉加密。https://github.com/FederatedAI/FATE/blob/ea550db8c1000b89a53084d2c3a41cee476c832e/python/federatedml/secureprotol/encrypt.py#L204C17-L204C21。

**Comment by dylan-fan** [comment]
如果不着急的话，可以等我们2.0发布，我们2.0 这块有个配置，使用很灵活

**Comment by dylan-fan** [comment]
2.0 下周就会发布。提前预览可以看 https://github.com/FederatedAI/FATE/tree/dev-2.0.0-rc 分支，支持pip安装

**Comment by harmony0303** [comment]
> 实验的话，可以考虑手动魔改代码，关掉加密。[https://github.com/FederatedAI/FATE/blob/ea550db8c1000b89a53084d2c3a41cee476c832e/python/federatedml/secureprotol/encrypt.py#L204C17-L204C21。](https://github.com/FederatedAI/FATE/blob/ea550db8c1000b89a53084d2c3a41cee476c832e/python/federatedml/secureprotol/encrypt.py#L204C17-L204C21%E3%80%82)

您好，谢谢您的解答！我刚浏览源码的时候发现he_interactive_layer.py这块有一个PLAINTEXT = False的属性，我直接在源码里改成True还需要魔改您给出的这部分吗?

**Comment by harmony0303** [comment]
> > 实验的话，可以考虑手动魔改代码，关掉加密。[https://github.com/FederatedAI/FATE/blob/ea550db8c1000b89a53084d2c3a41cee476c832e/python/federatedml/secureprotol/encrypt.py#L204C17-L204C21。](https://github.com/FederatedAI/FATE/blob/ea550db8c1000b89a53084d2c3a41cee476c832e/python/federatedml/secureprotol/encrypt.py#L204C17-L204C21%E3%80%82)
> 
> 您好，谢谢您的解答！我刚浏览源码的时候发现he_interactive_layer.py这块有一个PLAINTEXT = False的属性，我直接在源码里改成True还需要魔改您给出的这部分吗?

刚刚重新试了一下，把PLAINTEXT直接赋值True就是HeteroNN以明文进行训练，不需要耗时在加密解密上了，非常感谢！
