### ISSUE TITLE
Error reported when running "Resnet example" example

### ISSUE THREAD

**Issue by magic-hya** [FederatedAI/FATE#5375]
**Describe the bug**
Error reported when running "Resnet example" example.

Other issuses also raised questions #5213

**To Reproduce**
1. Go to doc/tutorial/pipeline/nn_tutorial/Resnet-example.ipynb
2. Run

**Expected behavior**

**Screenshots**
![image](https://github.com/FederatedAI/FATE/assets/85269941/e1329b84-162f-4c80-a3c3-7ea7a28acdd9)

![image](https://github.com/FederatedAI/FATE/assets/85269941/395231f4-2486-465c-b274-cb889b599e40)

`RuntimeError: can not found table name: cifar10 namespace: experiment`

**Desktop (please complete the following information):**
kubefate 1.11.2

**Comment by talkingwallace** [comment]
The fateflow is not running, make sure that you start the fateflow service

**Comment by magic-hya** [comment]
The service in the "fateflow" image was started, but now I have also started the service in the "client" image, and it is still the same error. Normal tasks can load data, which is the same error as "pipeline. bind_table".

**Comment by talkingwallace** [comment]
Hi, did you bind the path of your cifar dataset before running?

**Comment by magic-hya** [comment]
> Hi, did you bind the path of your cifar dataset before running?

I used the Notebook example for code binding, and I am not sure if there are any other operations outside of the Notebook code.

```
pipeline = PipeLine().set_initiator(role='guest', party_id=guest).set_roles(guest=guest, host=host,
                                                                            arbiter=host)
data_0 = {"name": "cifar10", "namespace": "experiment"}
data_path = fate_project_path + '/examples/data/cifar10/train'
pipeline.bind_table(name=data_0['name'], namespace=data_0['namespace'], path=data_path)
pipeline.bind_table(name=data_0['name'], namespace=data_0['namespace'], path=data_path)
reader_0 = Reader(name="reader_0")
reader_0.get_party_instance(role='guest', party_id=guest).component_param(table=data_0)
reader_0.get_party_instance(role='host', party_id=host).component_param(table=data_0)
```
