### ISSUE TITLE
2.0.0的docker 镜像无法下载

### ISSUE THREAD

**Issue by zzy484** [FederatedAI/FATE#5435]
通过
https://webank-ai-1251170195.cos.apguangzhou.myqcloud.com/fate/2.0.0/release/standalone_fate_docker_image_2.0.0_release.tar.gz
这个网址下载镜像显示ERROR 404: Not Found.

**Comment by dylan-fan** [comment]
稍等，这几天就会上传好

**Comment by SJTUHGX** [comment]
想问下，还有几天上传好。

**Comment by dylan-fan** [comment]
https://github.com/FederatedAI/FATE/wiki/Download

**Comment by dylan-fan** [comment]
已经上传了
