### ISSUE TITLE
是否支持差分隐私DP，如果没有支持的话，是否有计划在未来版本中添加相关特性

### ISSUE THREAD

**Issue by wildfire8966** [FederatedAI/FATE#5436]
请问现存版本中是否有实现DP差分隐私相关的功能？

【背景】
因为项目中要求必须有差分隐私这个功能点，所以调研后希望将opacus这个谷歌开源的差分隐私的包集成到FATE框架中
但是在集成过程中，opacus需要包装装饰optimizer、model和data_loader，但是FATE得data_loader属于不能定制化的，因此没有办法集成。

【关键问题】
1. 现有版本是否可以集成opacus？
2. 未来是否有FATE框架内部实现的DP？

**Comment by franklin520520** [comment]
同问

**Comment by dylan-fan** [comment]
我们后面会在2.0上支持dp，至于集成opacus，还是自己从0实现，需要再评估下

**Comment by dylan-fan** [comment]
也非常环境大家给FATE社区提供建议和贡献
