### ISSUE TITLE
v1.x的版本还会继续演进嘛

### ISSUE THREAD

**Issue by Meet-guguguo** [FederatedAI/FATE#5441]
最新v2.0的版本发布了，那么v1.x还会继续演进吗，还是以后重点都在v2.0上了呀

**Comment by harmony0303** [comment]
同问，我看heteroNN之前的interactive_layer好像直接被弃用了啊

**Comment by dylan-fan** [comment]
我们会在1.11的基础上对1.11进行bug fix，大的功能迭代可能不会在1.x中迭代。后续请请关注2.0

**Comment by Meet-guguguo** [comment]
> 我们会在1.11的基础上对1.11进行bug fix，大的功能迭代可能不会在1.x中迭代。后续请请关注2.0

好的，谢谢
