### ISSUE TITLE
docker_standalone-fate1.4.0 vs docker_standalone-fate 1.3.0 

### ISSUE THREAD

**Issue by xiaoToby** [FederatedAI/FATE#5442]
I want to know, the function is only run on version 1.3？ Becauese I tried it on version 1.4.0, there is an error on DataIO，it shows "lmdb.Error: Attempt to operate on closed/deleted/dropped object." . The reason that I want to try rec on version 1.4.0, I think the fateboard is more friendly on showing the predict results,it will show a chart. And I want to konw which version can be used that I can try federeated algorithm expect version 1.3
@zhihuiwan 
@dylan-fan

**Comment by dylan-fan** [comment]
please use v1.11

**Comment by xiaoToby** [comment]
> please use v1.11

You mean "wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/docker_standalone-fate-1.4.0.tar.gz"?

Thanks for your reply
Looking forward for your reply soon
