### ISSUE TITLE
fate的数据库设计信息在哪里可以看到呢

### ISSUE THREAD

**Issue by zzy484** [FederatedAI/FATE#5443]
# New Algorithm

- Name:
- Category:

## WIP

- [ ] Main Code
  - [ ] sub task 1
  - [ ] sub task 2
  - [ ] ...

- [ ] Docs
  - [Algorithm READMD.md](https://github.com/FederatedAI/FATE/fix_this_link)
  - Add entry to `federatedml/READMD`

- [ ] Pipeline
  - [ ] code
    - [ ] param
    - [ ] component
  - [ ] doc for new component

- [ ] Example
  - [ ] pipeline
  - [ ] dsl
  - [ ] benchmark_quality

## Check and Acceptance 

- [ ] PR
  - [ ] add reviewer: @mgqa34 @dylan-fan 
  - [ ] add assigner
  - [ ] add labels
  - [ ] link projects
  - [ ] link this issue

- [ ] Confirm `Params` consistent between `federatedml` and `pipeline`
- [ ] Examples tested

**Comment by zhihuiwan** [comment]
2.x版本fate-flow数据表可以参考：https://github.com/FederatedAI/FATE-Flow/tree/main/python/fate_flow/db里面
1.x版本fate-flow数据表可以参考： 
- https://github.com/FederatedAI/FATE-Flow/blob/main-1.x/python/fate_flow/db/db_models.py
https://github.com/FederatedAI/FATE/blob/main-1.x/python/fate_arch/metastore/db_models.py

**Comment by sealofyou** [comment]
如果是没执行导致数据库里没表，可以重启fate_flow。fateflow会自己再建一遍。
