### ISSUE TITLE
能不能写一份比较详细的介绍eggroll的文档，介绍一下eggroll的模块、原理、接口和代码结构等，万分感谢。

### ISSUE THREAD

**Issue by GreyJeremyji** [FederatedAI/FATE#5446]
eggroll的文档太少了，阅读源码的成本太高了。

**Comment by dylan-fan** [comment]
https://github.com/FederatedAI/eggroll/tree/main/doc
看看这里能不能帮助你理解

**Comment by sagewe** [comment]
@GreyJeremyji 可以分享下你主要想了解哪部分的代码以及目的是啥吗，我们可以根据情况补充一些文档资料

**Comment by GreyJeremyji** [comment]
> @GreyJeremyji 可以分享下你主要想了解哪部分的代码以及目的是啥吗，我们可以根据情况补充一些文档资料

好的  我整理一下
