### ISSUE TITLE
FATE 并行任务支持疑问（form 工行）

### ISSUE THREAD

**Issue by GreyJeremyji** [FederatedAI/FATE#5447]
FATE目前是不是不支持并行任务的运行？当前由于业务需求大，同一时间可能需要跟多个合作方同时进行任务运行，做了个如下方案（from 工行），麻烦能不能帮忙看看可不可行，具体需要哪些改造才能达到方案效果呢。 方案有如下考虑（以PSI任务为例）： 1、各个任务间互不影响。通过容器隔离，不同任务完全运行在不同容器内。  2、节省资源。启动任务时，申请资源，启动容器，任务运行完，容器停止，释放资源。 3、网络灵活，多个任务，只需要一个入口（9370）。生产环境，频繁开通网络流程较长。

![yuque_diagram (7)](https://github.com/FederatedAI/FATE/assets/26345478/69148dd4-94c0-4fe3-b8a1-ce4beb15d6fb)

**Comment by dylan-fan** [comment]
FATE支持多任务并行
