### ISSUE TITLE
Problem with standalone-deploy readme

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/FATE#5450]
https://github.com/FederatedAI/FATE/blob/bb6de879de7d0c1f4a5a2d0d2905caf48b0861e7/deploy/standalone-deploy/README.zh.md?plain=1#L44

the command should be `pipeline init --ip 127.0.0.1 --port 9380`

**Comment by mgqa34** [comment]
Thanks,  can you make a 'Pull Request' to fix it ?

**Comment by asdfsx** [comment]
Sure, I just create pr https://github.com/FederatedAI/FATE/pull/5452 to fix it

**Comment by mgqa34** [comment]
> Sure, I just create pr #5452 to fix it

To Merge this pr,  it should pass the DCO checking.
