### ISSUE TITLE
problem with guest_data&host_data in `examples/lanchers/run.sh`

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/FATE#5453]
https://github.com/FederatedAI/FATE/blob/cd699d7aee6f6ac7c026119ce801b488afe5079b/examples/launchers/run.sh#L3

guest_data should be `../data/breast_hetero_guest.csv`
host_data should be `../data/breast_hetero_host.csv`

**Comment by dylan-fan** [comment]
Thanks for your feedback. The above is mainly aligned with doc (https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/ml/run_launchers.md)
