### ISSUE TITLE
Too many <defunct> process after upload data to eggroll 3.0

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/FATE#5461]
I build a test environment with fate-flow 2.0 + eggroll 3.0
According to [doc/2.0/fate/quick_start.md](https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/quick_start.md), I upload some data to eggroll. The upload task succeeded but left lots of defunct process.
![image](https://github.com/FederatedAI/FATE/assets/2292716/3f6ad648-e88b-44c7-93fc-439c9278710d)

**Comment by asdfsx** [comment]
It seems the problem is caused by the eggroll_boot.sh. I use the following cmd to create egg_pair
```
/bin/bash bin/eggroll_boot.sh start "bin/roll_pair/egg_pair_bootstrap.sh --config /data/projects/fate/eggroll/./conf/eggroll.properties   --session-id 202401180328232914780_toy_example_0_0_guest_10000 --server-node-id 2 --processor-id 103" egg_pair-103 &
```

And got defunct progress 

![image](https://github.com/FederatedAI/FATE/assets/2292716/b914f03e-c67d-4969-9c2b-a721e8bdb6df)
process haven't become defunct
![image](https://github.com/FederatedAI/FATE/assets/2292716/b3a842e0-e173-4b29-bbf6-652956e9861a)
process have become defunct

**Comment by asdfsx** [comment]
It seems the better solution is to use `setsid` to put the process into background, but not `&`

**Comment by mgqa34** [comment]
How do you deploy the environment , it seems you are using the standalone quick start guide? We need more messages to reproduce the problem: 
1. Cluster or Standalone packages. the link of packages
2 your OS version (Centos/Ubuntu/others...)
3. the way to upload data

**Comment by asdfsx** [comment]
I deploy all component into docker container, I think that's why I got so many defunct process

**Comment by asdfsx** [comment]
I solve the problem by using `tini` as the `PID 1`
