### ISSUE TITLE
the range of integer and float

### ISSUE THREAD

**Issue by ttsdmmn** [FederatedAI/FATE#5469]
I'd like to know how many bits  fate uses to represent an integer or float. When I execute
 a mpc program,such as addition,if I can know whether an overflow happens or not.

**Comment by sagewe** [comment]
64bit for now but would be extended in future

**Comment by ttsdmmn** [comment]
Thanks.And I'd also like to know how many bits of precision are supported for floating point numbers?

**Comment by ttsdmmn** [comment]
> 64bit for now but would be extended in future

Thanks.And I'd also like to know how many bits of precision are supported for floating point numbers

**Comment by sagewe** [comment]
> > 64bit for now but would be extended in future
> 
> Thanks.And I'd also like to know how many bits of precision are supported for floating point numbers
configurable:
https://github.com/FederatedAI/FATE/blob/master/python/fate/arch/config/default.yaml
