### ISSUE TITLE
FATE2.0组件参数命名不一致

### ISSUE THREAD

**Issue by amenkim** [FederatedAI/FATE#5470]
版本：FATE 2.0.0

对于组件的输入（dataframe_input），有些组件用的参数名是input_data（像psi、statistics、sample、datasplit等），有些用的是train_data（binning、scale、各建模算法）。
对于组件的输出（dataframe_output），nn和secureboost组件用的是train_data_output，其他组件用的都是train_output_data。

请问是否有考虑过对参数的命名进行统一呢，虽然组件输入的命名不同还好理解，但组件输出这个感觉很容易搞错……

**Comment by mgqa34** [comment]
> 版本：FATE 2.0.0
> 
> 对于组件的输入（dataframe_input），有些组件用的参数名是input_data（像psi、statistics、sample、datasplit等），有些用的是train_data（binning、scale、各建模算法）。 对于组件的输出（dataframe_output），nn和secureboost组件用的是train_data_output，其他组件用的都是train_output_data。
> 
> 请问是否有考虑过对参数的命名进行统一呢，虽然组件输入的命名不同还好理解，但组件输出这个感觉很容易搞错……

https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/components/README.md#algorithm-list
这里有对组件的输入输出做一个说明，对于输出的规范，我们下一个版本会进行统一，2.0在解析运行时，dag-parser对连线端口规定不再那么严格，所以开发过程中会更加自由，但在Component组件层来说确实统一会更好的。

**Comment by amenkim** [comment]
好的，谢谢解答~

**Comment by amenkim** [comment]
我这边跑了几个模型，还踩了几个坑…

1、homo_lr 和 hetero_feature_selection 输出的模型是 train_output_model，README里面写的是 output_model；
2、homo_nn 输出的模型是 train_model_output，输出的预测数据是 predict_data_output，README里面写的是 output_model 和 test_output_data；
3、hetero_secureboost 输出的预测数据是 test_output_data，README里面写的是 test_data_output。

**Comment by mgqa34** [comment]
> test_data_output

好的，感谢指出～ 如果您这边方便的话，可以提一个pr哈（commit的时候注意加上DCO签名)

**Comment by dylan-fan** [comment]
2.1 版本已经修复，谢谢反馈。
