### ISSUE TITLE
关于FATE2.0.0 自定义算法实现

### ISSUE THREAD

**Issue by BoastDown** [FederatedAI/FATE#5478]
您好！感谢阅读！
1. 目前打算实现一个自定义算法，我的思路有以下两种方式，针对FATE-2.0.0版本我看到有本地算法和容器算法两种方式，没有找到对应的指引，请问方便提供吗？

2.  针对本地算法实现，我参考https://fate.readthedocs.io/en/latest/zh/develop/develop_guide/#meta 开发指引，只找到对应的 model（算法模型实现）和 Component（算法组件的定义），像param、mate、 protobuf以及fate_client中定义Pipeline感觉和现阶段的版本差异很大，有些还没找到，方便说明一下吗？

3. 我目前翻看FATE的源码，看FATE2.0.0 版本的样例使用的都是yaml + py 文件提供，现阶段还支持flow_client  dsl + config 的方式提交任务吗？

4. FATE 有官方的技术讨论群吗？方便提供一下吗？

再次感谢您看完！谢谢！

**Comment by dylan-fan** [comment]
针对本地算法实现，我参考https://fate.readthedocs.io/en/latest/zh/develop/develop_guide/#meta 开发指引，只找到对应的 model（算法模型实现）和 Component（算法组件的定义），像param、mate、 protobuf以及fate_client中定义Pipeline感觉和现阶段的版本差异很大，有些还没找到，方便说明一下吗？ 
这个是应该是1.x的模式。

**Comment by dylan-fan** [comment]
https://github.com/FederatedAI/FATE/blob/master/python/fate/ml/glm/hetero/coordinated_lr/guest.py
你可以参考lr实现代码实现。
后面我们会把2.0 开发文档丰富下

**Comment by BoastDown** [comment]
@dylan-fan 好的！感谢指导，那再摸索一下，请问有官方的社区群吗？

**Comment by RayWang99** [comment]
> https://github.com/FederatedAI/FATE/blob/master/python/fate/ml/glm/hetero/coordinated_lr/guest.py 你可以参考lr实现代码实现。 后面我们会把2.0 开发文档丰富下

请问现在2.0以上的版本的开发文档有了吗？感谢
