### ISSUE TITLE
想问一下：FATE部署结束后，安装账号的权限是否可收回？

### ISSUE THREAD

**Issue by tigflanker** [FederatedAI/FATE#5480]
安装和使用过程中有个疑问，咨询一下FATE大佬

我们在安装过程中（比方说只有host和guest两方，我站在host端帮助guest端进行部署），我们需要建一个名叫fate的user，然后配备一个 host -> guest 的免密登录

安装完成后（使用阶段）我好像依然可以用这个账号免密登录对方电脑
那么我们应该对这个安装账号如何处理呢？删除免密登录密钥并修改登录密码？还是说这个账号可以直接删除呢？

（预祝路过的fater新年快乐！）

**Comment by mgqa34** [comment]
直接在免密登陆授权那里删掉对方主机授权应该就可以了
