### ISSUE TITLE
FATE2.0版本对FATE-Serving在线预测的支持情况

### ISSUE THREAD

**Issue by xkf4806** [FederatedAI/FATE#5481]
FATE2.0 Client命令行目前支持的model子命令包含：
![image](https://github.com/FederatedAI/FATE/assets/7620676/0578d6f1-5fc8-43a7-806e-617db3988bda)
没有支持deploy、load、bind等子命令，不知道怎样和FATE-Serving集成进行在线预测。

请问后续会对【在线预测】部分有相关规划吗？

**Comment by dylan-fan** [comment]
这块在后续会支持，目前不支持
