### ISSUE TITLE
请问FATE 1.x 版本支持一方基于Eggroll另一方基于Spark的异构计算吗

### ISSUE THREAD

**Issue by hust-suwb** [FederatedAI/FATE#5487]
请问FATE 1.x 版本支持一方基于Eggroll另一方基于Spark的异构计算吗。
如果支持的话，请问是从哪个版本开始支持的呢，我翻了下release note，好像没看到。
如果不支持的话，那在FATE 2.0里通过互联互通的方式，FATE on eggroll 和 FATE on Spark 这两个异构引擎都基于FATE2.0 我理解肯定是可以支持的，这个理解对吗。

**Comment by dylan-fan** [comment]
2.x都是支持的。建议使用2.x
