### ISSUE TITLE
When a participant sends the same content more than once,an error will be reported。

### ISSUE THREAD

**Issue by zgy970814** [FederatedAI/FATE#5489]
When a participant sends the same content more than once, the following error will be reported:

File"/standalone_fate_install_1.10.0_release/fate/python/fate_arch/federation/standalone/_federation.py", line 58, in remote
 raise ValueError(f"remote to {parties} with duplicate tag: {name}.{tag}")
ValueError: remote to [Party(role=guest, party_id=9999)] with duplicate tag:hash.c073cdca070dc28f152e.host_missing_idx.fit

So what are the next steps to solve this problem？

**Comment by zgy970814** [comment]
原来可以发中文的啊，这里用中文重复一遍：
当同一个参与方发送多次相同的变量便会报错，请问有什么解决办法？报错信息如下：
File"/standalone_fate_install_1.10.0_release/fate/python/fate_arch/federation/standalone/_federation.py", line 58, in remote
raise ValueError(f"remote to {parties} with duplicate tag: {name}.{tag}")
ValueError: remote to [Party(role=guest, party_id=9999)] with duplicate tag:hash.c073cdca070dc28f152e.host_missing_idx.fit

**Comment by mgqa34** [comment]
> 原来可以发中文的啊，这里用中文重复一遍： 当同一个参与方发送多次相同的变量便会报错，请问有什么解决办法？报错信息如下： File"/standalone_fate_install_1.10.0_release/fate/python/fate_arch/federation/standalone/_federation.py", line 58, in remote raise ValueError(f"remote to {parties} with duplicate tag: {name}.{tag}") ValueError: remote to [Party(role=guest, party_id=9999)] with duplicate tag:hash.c073cdca070dc28f152e.host_missing_idx.fit

不支持发同样的tag，可以根据需要自增后缀

**Comment by zgy970814** [comment]
> 不支持发同样的tag，可以根据需要自增后缀

添加一定数量的后缀后有如下报错：

 best_splitinfo_table = splitinfo_guest_host_table.mapValues(find_split_func)
21   File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/common/profile.py", line 415, in _fn
22     rtn = func(*args, **kwargs)#fate_arch/computing/standalone/_table.py
23   File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/computing/standalone/_table.py", line 120, in mapValues
24     return Table(self._table.mapValues(func))
25   File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/_standalone.py", line 186, in mapValues
26     return self._unary(func, _do_map_values)
27   File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/_standalone.py", line 295, in _unary
28     results = self._session._submit_unary(
29   File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/_standalone.py", line 548, in _submit_unary
30     function_bytes=f_pickle.dumps(func),
31   File "/usr/local/lib/python3.8/dist-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
32     cp.dump(obj)
33   File "/usr/local/lib/python3.8/dist-packages/cloudpickle/cloudpickle_fast.py", line 633, in dump
34     return Pickler.dump(self, obj)
35 TypeError: cannot pickle 'google.protobuf.pyext._message.MessageDescriptor' object

关于这个报错请问有什么解决办法吗？

**Comment by mgqa34** [comment]
> > 不支持发同样的tag，可以根据需要自增后缀
> 
> 添加一定数量的后缀后有如下报错：
> 
> best_splitinfo_table = splitinfo_guest_host_table.mapValues(find_split_func) 21 File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/common/profile.py", line 415, in _fn 22 rtn = func(*args, **kwargs)#fate_arch/computing/standalone/_table.py 23 File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/computing/standalone/_table.py", line 120, in mapValues 24 return Table(self._table.mapValues(func)) 25 File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/_standalone.py", line 186, in mapValues 26 return self._unary(func, _do_map_values) 27 File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/_standalone.py", line 295, in _unary 28 results = self._session._submit_unary( 29 File "/standalone_fate_install_1.10.0_release/fate/python/fate_arch/_standalone.py", line 548, in _submit_unary 30 function_bytes=f_pickle.dumps(func), 31 File "/usr/local/lib/python3.8/dist-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps 32 cp.dump(obj) 33 File "/usr/local/lib/python3.8/dist-packages/cloudpickle/cloudpickle_fast.py", line 633, in dump 34 return Pickler.dump(self, obj) 35 TypeError: cannot pickle 'google.protobuf.pyext._message.MessageDescriptor' object
> 
> 关于这个报错请问有什么解决办法吗？

参数有protobuf类型，这个是没法pickle的，可以看下是传递给函数的变量有这个问题还是self.xxx里面的属性xxx有这个问题
