### ISSUE TITLE
Prediction Score Output Format

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#5494]
Hello, 

I wonder if there is any way to export the prediction scores in the column-based format. 
For example, 
FATE data output gives me {'0': 0.01108020544052124, '1': 0.9889197945594788}, but is there any way to extract the scores in two separate columns?

Thank you!

**Comment by mgqa34** [comment]
Which version of fate in your enviroment ? Actually in newly version of fate, it's a json string instead of dict object

**Comment by amyseoj1** [comment]
Hello, 
Thank you for your reply ! 
I currently use V1.11.2
