### ISSUE TITLE
请问下模型部署阶段，model serving在host端是如何取到数据的？

### ISSUE THREAD

**Issue by tigflanker** [FederatedAI/FATE#5498]
请问下，在模型已经训练好的情况下（也已经依次完成了：部署、加载、绑定，3步）

我想要利用 curl -X POST 的方式做数据实时预测。

`curl -X POST -H 'Content-Type: application/json' -i 'http://xx.xx.xx.guest:8059/federation/v1/inference' --data '{
  "head": {
    "serviceId": "boost_model"
  },
  "body": {
    "featureData": {
        "g2": 1.88669
    },
    "sendToRemoteFeatureData": {
        "id": "00151788df5fc50f0d6be8bd709a7eca"
    }
  }
}'`

这里sendToRemoteFeatureData的id，会不会需要在host端，挂载一个大数据集，否则的话应该咋查询这个id的相关信息呢？

另外我直接调用上述代码的时候，返回是
`{"retcode":0,"retmsg":"","data":{"score":0.7038398080525485,"modelId":"guest#9999#arbiter-10000#guest-9999#host-9998_10000#model","modelVersion":"202402221632287164860","timestamp":1708590887081},"flag":0}`

这里是否应该有个标识？指出本次查询没有正确在host1或者host2通过id取到特征（这里retcode为0），否则下游直接拿着用了，感觉有些风险

**Comment by tigflanker** [comment]
背景是KubeFATE 1.11.1，三方纵向secure boost模型部署，guest和两个host都有特征入模，guest发起查询

**Comment by mgqa34** [comment]
模型推理阶段host方需要实现自己的adapter，可以参考下serving的[教程](https://fate-serving.readthedocs.io/en/latest/service/adapter/ )
