### ISSUE TITLE
How to deploy multi host请问怎么部署多个host方

### ISSUE THREAD

**Issue by Defu-csh** [FederatedAI/FATE#5520]
请问怎么部署多个host方，有无相关文档详细说明，只看到有多个host的使用，但是没有相关部署方案

**Comment by mgqa34** [comment]
fate-v1.x还是fate-v2.0？fate-v1.x在eggroll的conf/route_table.json下面添加的party_id/ip等信息就可以了，2.0的类似，在osx/conf下面的路由表进行配置

**Comment by hztBUAA** [comment]
> 请问怎么部署多个host方，有无相关文档详细说明，只看到有多个host的使用，但是没有相关部署方案

有本地运行多个host的使用教程吗 尝试进行三方（两个host 一个guest）的训练，会错误，在教程上找不到多host训练的例子
Duplicate of #

**Comment by Defu-csh** [comment]
> > 请问怎么部署多个host方，有无相关文档详细说明，只看到有多个host的使用，但是没有相关部署方案
> 
> 有本地运行多个host的使用教程吗 尝试进行三方（两个host 一个guest）的训练，会错误，在教程上找不到多host训练的例子 Duplicate of #

可以放一下你进行三方训练的配置看一下
