### ISSUE TITLE
OSX特性中:"支持作为exchange中心节点部署 ，支持FATE1.X 、FATE2.X 接入"这句话怎么理解呢

### ISSUE THREAD

**Issue by 123fei1** [FederatedAI/FATE#5530]
OSX特性中:"支持作为exchange中心节点部署 ，支持FATE1.X 、FATE2.X 接入"这句话怎么理解呢? 
 支持FATE1.X 、FATE2.X 接入 是接入什么?

**Comment by zhihuiwan** [comment]
调度命令、通信通道两个层面接入
