### ISSUE TITLE
FATE2.1.0怎么部署呢

### ISSUE THREAD

**Issue by mathieulin** [FederatedAI/FATE#5538]
wget2.1.0版本的安装包好像get不到

**Comment by mgqa34** [comment]
当前standalone & allInOne部署包已经上传，可以wget进行部署了，pip包install的方式(从pypi直接安装）会在本周晚些时候推送

**Comment by mathieulin** [comment]
> 当前standalone & allInOne部署包已经上传，可以wget进行部署了，pip包install的方式(从pypi直接安装）会在本周晚些时候推送

好的好的，谢谢

**Comment by Balincourt** [comment]
> 当前standalone & allInOne部署包已经上传，可以wget进行部署了，pip包install的方式(从pypi直接安装）会在本周晚些时候推送

@mgqa34 请问一下，上周是没有推送吗？

python -m pip install fate_client[fate,fate_flow]==2.1.0 报错如下：

ERROR: Could not find a version that satisfies the requirement fate_client==2.1.0 (from versions: 0.1.dev1, 0.1.dev2, 0.1rc1, 0.1, 0.1.post1, 0.2, 0.2.1, 0.2.1.post1, 0.2.2, 0.2.2.post1, 0.3.0, 0.3.0.post1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.7.1.1, 1.7.2, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.11.2, 1.11.3, 1.11.3.post1, 2.0.0a0, 2.0.0b0, 2.0.0)
ERROR: No matching distribution found for fate_client==2.1.0
