### ISSUE TITLE
cryptography is required for sha256_password or caching_sha2_password

### ISSUE THREAD

**Issue by pengluhyd** [FederatedAI/FATE#554]
When I run :
`python fate_flow_server.py `  
I got this:
`RuntimeError: cryptography is required for sha256_password or caching_sha2_password`

I didn't find cryptography in the requirements.
Have you forgotten to add it, or did you deliberately do this?

**Comment by zengjice** [comment]
Hello, if you use mysql as database for FATE-Flow, please check the DATABASE configuration in the fate_flow/settings.py.
