### ISSUE TITLE
OSX   通过http修改路由表的地址是什么

### ISSUE THREAD

**Issue by 123fei1** [FederatedAI/FATE#5540]
我没有找见通过http的方式修改路由表,请问这个具体的访问地址和传参方式是什么样的?

**Comment by Xiong-Li-github** [comment]
/v1/inner/router/set    {"data":"路由表json"}

具体逻辑在 org.fedai.osx.broker.router.RouterTableSetService

**Comment by 123fei1** [comment]
好的 谢谢  有比较全的API接口说明文档吗,  我看https://federatedai.github.io/FATE-Flow/latest/zh/swagger/  这个2.0.0的api接口不怎么全

**Comment by YCamelot** [comment]
你好，这个接口请求路径和参数是什么样子的啊，我在测试的时候接口都不通
