### ISSUE TITLE
fedpass算法实现相关问题

### ISSUE THREAD

**Issue by 123bazhahei** [FederatedAI/FATE#5543]
请问 python/fate/ml/nn/test/test_fedpass_lenet.py 是否是论文 FedPass: Privacy-Preserving Vertical Federated Deep Learning
with Adaptive Obfuscation 中的算法实现？
![image](https://github.com/FederatedAI/FATE/assets/162691077/5de1b9f7-1752-44f7-a008-e3f007685a47)
如果是的话，有下面几个问题：
1. test_fedpass_lenet.py 似乎没有 passive party 对 feature 的 obfuscation
2. fedpass 实现在 agg_layer 中，是在 host（passive方）经过 bottom_model 之后执行，按上图不应该是在 guest（activate方）执行嘛

**Comment by talkingwallace** [comment]
hi，这个是按照论文开发的
混淆的逻辑在agglayer里，可以参考下agglayer里的代码

**Comment by talkingwallace** [comment]
具体代码在model_zoo 下的agg layer

**Comment by 123bazhahei** [comment]
看到 agg_layer 了，混淆逻辑没问题，只是看论文里的用法：在 passive party feature 上使用，active party top_model 之前使用
和单测中的用法不一样，所以单测只是为了测试混淆逻辑，还是说单测还原了论文的实验？

**Comment by talkingwallace** [comment]
是会不一点点样的 但是这个代码使用的是原论文的代码方法。单侧（passive party)的用法也是和原论文一致，还原了效果的

**Comment by 123bazhahei** [comment]
好奇问一点，feature 的混淆逻辑为啥不做呢？
我理解论文中的做法：passive party feature 混淆 保护 feature，active party 混淆 保护 label；按照单侧的做法 passive party 在 agg_layer 混淆 embedding（论文中这个混淆在 active party），active party 因为没有自己的 feature 只是把 embedding 做聚合+top model，这么做似乎不能保护 label

**Comment by 123bazhahei** [comment]
还有一个问题：predict 的时候 这个 passport 还是需要过的对吧

**Comment by talkingwallace** [comment]
1. 没太明白您的意思，passive party的feature 混淆要用到passport，不会在active party 进行的？
2. passport会跟随模型保存的，预测需要passport

**Comment by talkingwallace** [comment]
guest(acitve) & host(passive) 都有这个agglayer，但是host的agglayer会执行passport相关的逻辑，而guest的是负责从host接受数据&反向传播，详细的可以看agglayer下fedpass 在host方的代码(你想要了解的图片里的红框部分）

**Comment by 123bazhahei** [comment]
你还没明白我的问题，我的问题是论文的图上画的 host feature 需要执行 passport，但代码里 host feature 并没有执行passport 呀
![image](https://github.com/FederatedAI/FATE/assets/162691077/d94cab26-c875-495f-b81b-475951e7b635)
![image](https://github.com/FederatedAI/FATE/assets/162691077/2dd05c00-0bf2-4dcf-a68f-248db57a751d)
请问 bottom model 在哪里执行了 passport

**Comment by talkingwallace** [comment]
![image](https://github.com/FederatedAI/FATE/assets/10768970/fb6f41f8-fc89-4f0a-bfea-9f4cacc91053)
passport相关的逻辑在这里

下面的这个过程
![image](https://github.com/FederatedAI/FATE/assets/10768970/bb0d7ec6-37b8-4f39-83e4-0cd3182754d5)
就是在 feature -> bottom_model -> agg_layer这个过程里完成的

**Comment by 123bazhahei** [comment]
![image](https://github.com/FederatedAI/FATE/assets/162691077/d56e0d32-718a-4536-8d78-7ee48063c9dc)
这里 g_theta 是 passport 呀，G_theta 是 bottom_model，应该是 feature -> passport -> bottom_model，代码里 feature -> bottom_model -> passport 不是和论文里不一样吗

**Comment by talkingwallace** [comment]
Hi, 你可以把这部分理解为一个完整的过程。这里实现的时候也是以论文代码为准的，论文代码里，比如说Lenet model，也是遵顼一个feature-> bottom_model -> passport的顺序的：
![image](https://github.com/FederatedAI/FATE/assets/10768970/91ac9d8a-c75f-454d-a61a-78e9a0064bab)

**Comment by 123bazhahei** [comment]
请问论文代码有开源吗，看上去和论文的图是反着的...
![image](https://github.com/FederatedAI/FATE/assets/162691077/540c9161-ef35-41b6-a0c6-eb471935e9ba)

**Comment by talkingwallace** [comment]
Hi~ 你可以发邮件问一下作者的，我不知道作者是否允许把代码分享其他人

**Comment by 123bazhahei** [comment]
好的，谢谢
