### ISSUE TITLE
模型训练出现“TypeError: a bytes-like object is required, not 'NoneType'”

### ISSUE THREAD

**Issue by cgyzfjm** [FederatedAI/FATE#5546]
运行一个住房预测的案例，在训练模型的时候出现not 'NoneType'”。具体的过程如下

总共有4个文件分别是**housing_1_eval、housing_1_train、housing_2_eval、housing_2_train**

然后使用upload_host.json文件把housing_1_eval和housing_1_train上传到host方容器。具体的文件内容如下
![image](https://github.com/FederatedAI/FATE/assets/25324817/0ab79515-545b-4ec9-9c71-b38c5dc00330)
![image](https://github.com/FederatedAI/FATE/assets/25324817/cbe4da63-6f18-4cf6-b0e3-8d6be1b6b031)
![image](https://github.com/FederatedAI/FATE/assets/25324817/35284984-6c81-494b-a7b7-f35d14228016)
![image](https://github.com/FederatedAI/FATE/assets/25324817/90386e84-e93f-45cc-910c-e3bb464dfc4d)

然后使用upload_guest.json文件把housing_2_eval和housing_2_train上传至guest方容器。具体的文件内容如下
![image](https://github.com/FederatedAI/FATE/assets/25324817/dfbd98a9-866a-444a-aa1d-e0cb8007ddbb)
![image](https://github.com/FederatedAI/FATE/assets/25324817/eb995354-45d6-4910-8c3a-2913c9efe69a)
![image](https://github.com/FederatedAI/FATE/assets/25324817/08f41bc5-11d0-45a7-a285-76b20923d4e8)
![image](https://github.com/FederatedAI/FATE/assets/25324817/e6c55f03-3f77-4311-bf6b-a971bd12b80f)

然后在host中的容器提交任务，

> dag:
  parties:
  - party_id:
    - '9999'
    role: guest
  - party_id:
    - '10000'
    role: host
  - party_id:
    - '10000'
    role: arbiter
  party_tasks:
    guest_9999:
      parties:
      - party_id:
        - '9999'
        role: guest
      tasks:
        reader_0:
          parameters:
            name: housing_train_guest
            namespace: experiment
    host_10000:
      parties:
      - party_id:
        - '10000'
        role: host
      tasks:
        reader_0:
          parameters:
            name: housing_train_host
            namespace: experiment
  stage: train
  tasks:
    reader_0:
      component_ref: reader
      parties:
        - party_id:
            - '9999'
          role: guest
        - party_id:
            - '10000'
          role: host
      stage: default
    binning_0:
      component_ref: hetero_feature_binning
      dependent_tasks:
      - scale_0
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: scale_0
        model: {}
      parameters:
adjustment_factor: 0.5
        bin_col: null
        bin_idx: null
        category_col: null
        category_idx: null
        local_only: false
        method: quantile
        n_bins: 10
        relative_error: 1.0e-06
        skip_metrics: false
        split_pt_dict: null
        transform_method: null
        use_anonymous: false
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        role: host
    evaluation_0:
      component_ref: evaluation
      dependent_tasks:
      - lr_0
      inputs:
        data:
          input_data:
            task_output_artifact:
              - output_artifact_key: train_output_data
                producer_task: lr_0
                parties:
                - party_id:
                  - '9999'
                  role: guest
      parameters:
        default_eval_setting: binary
        label_column_name: null
        metrics: null
        predict_column_name: null
      parties:
      - party_id:
        - '9999'
        role: guest
      stage: default
    lr_0:
      component_ref: coordinated_lr
      dependent_tasks:
      - selection_0
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: selection_0
              parties:
                - party_id:
                -  - '9999'
                  role: guest
                - party_id:
                    - '10000'
                  role: host
        model: {}
      parameters:
        batch_size: null
        early_stop: diff
        epochs: 10
        floating_point_precision: 23
        output_cv_data: true
        threshold: 0.5
        tol: 0.0001
    psi_0:
      component_ref: psi
      inputs:
        data:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: reader_0
      parameters: {}
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        role: host
      stage: default
    scale_0:
      component_ref: feature_scale
      dependent_tasks:
      - psi_0
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: psi_0
        model: {}
      parameters:
        feature_range: null
        method: standard
        scale_col: null
        scale_idx: null
        strict_range: true
        use_anonymous: false
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
- '10000'
        role: host
    selection_0:
      component_ref: hetero_feature_selection
      dependent_tasks:
      - binning_0
      - scale_0
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: scale_0
        model:
          input_models:
            task_output_artifact:
            - output_artifact_key: output_model
              producer_task: binning_0
      parameters:
        iv_param:
          filter_type: threshold
          metrics: iv
          threshold: 0.1
        keep_one: true
        manual_param: null
        method:
        - iv
        select_col: null
        statistic_param: null
        use_anonymous: false
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        role: host
schema_version: 2.0.0
 

然后在host容器中提交任务

> [root@976cf52cd022 fate_flow]# flow job submit -c examples/lr/train_lr.yaml
{
    "code": 0,
    "data": {
        "model_id": "202403122047397316310",
        "model_version": "0"
    },
    "job_id": "202403122047397316310",
    "message": "success"
}

在host（192.168.0.132）的Borad中没有错误输出，在guest（192.168.0.133）的Borad中出现“TypeError: a bytes-like object is required, not 'NoneType'”报错
![image](https://github.com/FederatedAI/FATE/assets/25324817/7b12d0ba-7a81-41cb-9edc-ec09b2a81191)

![image](https://github.com/FederatedAI/FATE/assets/25324817/eded6312-b3bd-4d2f-89cb-625181981beb)

**Comment by cgyzfjm** [comment]
> 运行到哪个算法组件的报错？

我不知道从哪里看是哪个组件报错，是这个吗

![image](https://github.com/FederatedAI/FATE/assets/25324817/4678f466-7b2f-4f98-a36e-df40e43afe11)

**Comment by talkingwallace** [comment]
对 各方都看看有没有具体的报错
