### ISSUE TITLE
上传后fateboard报错：[error]/home/neo/standalone_fate_install_1.11.2_release/fateflow/jobs/202403141624134098400/fate_upload_tmp/... is an empty file

### ISSUE THREAD

**Issue by NeoBateman** [FederatedAI/FATE#5547]
版本是fate1.11.2，使用主机安装方式安装，在对照教程“从零实现横向逻辑回归”，上传后fateboard报错如上，上传时的返回消息是：
(venv) [root@Centos777 data]# python /home/neo/standalone_fate_install_1.11.2_release/fateflow/python/fate_flow/fate_flow_client.py -f upload -c upload_data.json
{
    "data": {
        "board_url": "http://127.0.0.1:8080/index.html#/dashboard?job_id=202403142023375867770&role=local&party_id=0",
        "code": 0,
        "dsl_path": "/home/neo/standalone_fate_install_1.11.2_release/fateflow/jobs/202403142023375867770/job_dsl.json",
        "job_id": "202403142023375867770",
        "logs_directory": "/home/neo/standalone_fate_install_1.11.2_release/fateflow/logs/202403142023375867770",
        "message": "success",
        "model_info": {
            "model_id": "local-0#model",
            "model_version": "202403142023375867770"
        },
        "namespace": "homo_host_breast_train",
        "pipeline_dsl_path": "/home/neo/standalone_fate_install_1.11.2_release/fateflow/jobs/202403142023375867770/pipeline_dsl.json",
        "runtime_conf_on_party_path": "/home/neo/standalone_fate_install_1.11.2_release/fateflow/jobs/202403142023375867770/local/0/job_runtime_on_party_conf.json",
        "runtime_conf_path": "/home/neo/standalone_fate_install_1.11.2_release/fateflow/jobs/202403142023375867770/job_runtime_conf.json",
        "table_name": "homo_breast_1_train",
        "train_runtime_conf_path": "/home/neo/standalone_fate_install_1.11.2_release/fateflow/jobs/202403142023375867770/train_runtime_conf.json"
    },
    "jobId": "202403142023375867770",
    "retcode": 0,
    "retmsg": "success"
}

**Comment by zhihuiwan** [comment]
看报错是上传的文件是空文件， 可以检查下upload_data.json配置是否正确
