### ISSUE TITLE
打开FateBoard之后是一片空白，查看控制台的报错如下

### ISSUE THREAD

**Issue by 0814wdwd** [FederatedAI/FATE#5549]
安装好fate之后，打开FateBoard，界面如下
![image](https://github.com/FederatedAI/FATE/assets/118539178/06962db5-6a39-40c1-bc26-81fd3efb5e2d)
查看控制台的报错如下：
![image](https://github.com/FederatedAI/FATE/assets/118539178/ed4ef3db-c252-4559-8a04-d823b50f46a9)
应该如何去解决

**Comment by mgqa34** [comment]
是哪个版本？

**Comment by 0814wdwd** [comment]
2.0.0



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月16日 22:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) |

是哪个版本？

**Comment by 0814wdwd** [comment]
您有什么解决的办法吗，这个困扰了我好久了（鞠躬）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月16日 22:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) |

是哪个版本？

**Comment by mgqa34** [comment]
> 2.0.0
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年03月16日 22:50 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 是哪个版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

这个版本的board，可能某些情况下会导致这个问题，建议升级到2.1

**Comment by 0814wdwd** [comment]
好哒好哒，谢谢你，我先部署一些东西之后，尝试完再去升级叭，或者有什么办法可以保留现在的数据去升级呢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月17日 00:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) |

2.0.0
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月16日 22:50 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 是哪个版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

这个版本的board，可能某些情况下会导致这个问题，建议升级到2.1

**Comment by mgqa34** [comment]
> 好哒好哒，谢谢你，我先部署一些东西之后，尝试完再去升级叭，或者有什么办法可以保留现在的数据去升级呢
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年03月17日 00:45 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 2.0.0 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月16日 22:50 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 是哪个版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 这个版本的board，可能某些情况下会导致这个问题，建议升级到2.1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

需要保留的话，建议单独更新fateboard到v2.0.1，这样只影响到了fateboard的jar包的更新

**Comment by 0814wdwd** [comment]
还有一个问题想请教一下您，我想部署一个全连接神经网络的模型到 fate，有没有什么参考的模型配置文档和.yaml 文档呢，（万分感谢您回复我的提问）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月17日 00:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) |

2.0.0
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月16日 22:50 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 是哪个版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

这个版本的board，可能某些情况下会导致这个问题，建议升级到2.1

**Comment by 0814wdwd** [comment]
好喔，谢谢您，我明天去试着更新一下它



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月17日 00:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) |

好哒好哒，谢谢你，我先部署一些东西之后，尝试完再去升级叭，或者有什么办法可以保留现在的数据去升级呢
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月17日 00:45 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 2.0.0 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月16日 22:50 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 是哪个版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> 这个版本的board，可能某些情况下会导致这个问题，建议升级到2.1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

需要保留的话，建议单独更新fateboard到v2.0.1，这样只影响到了fateboard的jar包的更新

**Comment by mgqa34** [comment]
> 还有一个问题想请教一下您，我想部署一个全连接神经网络的模型到 fate，有没有什么参考的模型配置文档和.yaml 文档呢，（万分感谢您回复我的提问）
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年03月17日 00:45 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 2.0.0 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月16日 22:50 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 是哪个版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 这个版本的board，可能某些情况下会导致这个问题，建议升级到2.1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

麻烦 @talkingwallace 解答下

**Comment by 0814wdwd** [comment]
谢谢您，我会等待这位大牛的回复的（再次感谢）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月17日 00:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) |

还有一个问题想请教一下您，我想部署一个全连接神经网络的模型到 fate，有没有什么参考的模型配置文档和.yaml 文档呢，（万分感谢您回复我的提问）
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月17日 00:45 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 2.0.0 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年03月16日 22:50 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [FederatedAI/FATE] 打开FateBoard之后是一片空白，查看控制台的报错如下 (Issue #5549) | 是哪个版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> 这个版本的board，可能某些情况下会导致这个问题，建议升级到2.1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

麻烦 @talkingwallace 解答下

**Comment by lxs724** [comment]
解决了吗，我下载的2.1.0，也是这个问题

**Comment by zouzou6321** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
