### ISSUE TITLE
关于部分同态加密PHE的密钥生成

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5551]
![QQ图片20240318180341](https://github.com/FederatedAI/FATE/assets/127292082/2b5f8677-92fb-4f28-9635-1484d0a1ef62)

目前这个keygen这个方法，如果默认的长度1024会直接报错Illegal instruction (core dumped)，改到10也会相同的错误。
直接降到2，不会报错，但是CPU 满载100%20分钟都没算出结果。
不知道是哪里配置有问题，或者环境有什么问题。

环境是32G内存，CPU无GPU。
有没有哪位大神可以赐教的，万分感谢

**Comment by sagewe** [comment]
@RayWang99 方便提供下详细的系统环境吗 cpu架构/系统版本等

另外你可以尝试手动编译下fate_utils

激活虚拟环境后进入rust/fate_utils目录 执行maturin build —release

你需要预先安装好maturin和rust环境

**Comment by RayWang99** [comment]
> @RayWang99 方便提供下详细的系统环境吗 cpu架构/系统版本等
> 
> 另外你可以尝试手动编译下fate_utils
> 
> 激活虚拟环境后进入rust/fate_utils目录 执行maturin build —release
> 
> 你需要预先安装好maturin和rust环境

CPU ： Intel(R) Xeon(R) CPU E7- 4820  @ 2.00GHz
内存： 32GB
系统 ：NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

好的，我先尝试试试手动编译

**Comment by RayWang99** [comment]
> @RayWang99 方便提供下详细的系统环境吗 cpu架构/系统版本等
> 
> 另外你可以尝试手动编译下fate_utils
> 
> 激活虚拟环境后进入rust/fate_utils目录 执行maturin build —release
> 
> 你需要预先安装好maturin和rust环境

因为安装的是release包，未找到rust的toml，所以尝试手动编译develope版的，编译报错如下：

 Compiling fixedpoint v0.1.0 (/home/app/rust_temp/fate_utils/crates/fixedpoint)
   Compiling fate_utils v0.1.0 (/home/app/rust_temp/fate_utils/crates/fate_utils)
error: multiple input filenames provided (first two filenames are `crates/fate_utils/src/lib.rs` and `—release`)

error: could not compile `fate_utils` (lib) due to 1 previous error
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.8-64bit" PYO3_PYTHON="/home/app/projects/fate/common/python/venv/bin/python" PYTHON_SYS_EXECUTABLE="/home/app/projects/fate/common/python/venv/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/app/rust_temp/fate_utils/crates/fate_utils/Cargo.toml" "--lib" "--crate-type" "cdylib" "--" "\xe2\x80\x94release" "-C" "link-arg=-s"`

**Comment by RayWang99** [comment]
> @RayWang99 方便提供下详细的系统环境吗 cpu架构/系统版本等
> 
> 另外你可以尝试手动编译下fate_utils
> 
> 激活虚拟环境后进入rust/fate_utils目录 执行maturin build —release
> 
> 你需要预先安装好maturin和rust环境
去掉—release
maturin build 可以执行，产生whl文件，fate_utils-0.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
不过用pip 强制重装之后，原有的报错没有发生改变

**Comment by RayWang99** [comment]
> @RayWang99 方便提供下详细的系统环境吗 cpu架构/系统版本等
> 
> 另外你可以尝试手动编译下fate_utils
> 
> 激活虚拟环境后进入rust/fate_utils目录 执行maturin build —release
> 
> 你需要预先安装好maturin和rust环境

去掉—release
maturin build 可以执行，产生whl文件，fate_utils-0.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
不过用pip 强制重装之后，原有的报错没有发生改变

**Comment by RayWang99** [comment]
> @RayWang99 方便提供下详细的系统环境吗 cpu架构/系统版本等
> 
> 另外你可以尝试手动编译下fate_utils
> 
> 激活虚拟环境后进入rust/fate_utils目录 执行maturin build —release
> 
> 你需要预先安装好maturin和rust环境

重新编译后，重新安装fate_utils可以，非常感谢
