### ISSUE TITLE
关于新增接口

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5553]
![QQ图片20240321102030](https://github.com/FederatedAI/FATE/assets/127292082/e9e390b7-d19f-4b6c-ae3e-03fa90cbe584)

我在scheduler_app里新加了一个接口，在启动服务的情况下无法用页面访问，也无法用postman访问。
事实上我发现页面或者postman无法访问任何接口
用页面的话，会弹到404页面
用postman会出现405
用curl，返回的字符串里可以看到“等待系统加载”之类的字样。

请问是有什么权限控制吗，新加一个接口应该是在什么位置，什么流程（我看到是否是apps/__init__.py里注册“_app.py”的文件）。
无论是接口还是新接口，如何比较便利的测试其是否生效（能通过postman最好）？
（我测试用的路由是 xxx.yyy.zz.uu/v2/job/test，不确定路由是否正确）
另外，如果不能新增或者修改原项目的话，是否意味着是应该新建一套系统与fate通信。

万分感谢

**Comment by amenkim** [comment]
路由应该是 /v2/scheduler/job/test，要加上对应的page_name

**Comment by RayWang99** [comment]
> 路由应该是 /v2/scheduler/job/test，要加上对应的page_name

这个我刚才也尝试过，一样的现象，postman就是405，登录页面后访问就是404。
这个地址/v2/job/test我是仿照'https://federatedai.github.io/v2/job/rerun'来写的，因为
我写的test方法和rerun在一起，所以理论上路由应该是一致的
