### ISSUE TITLE
Which communication protocol and serialization method is supported?

### ISSUE THREAD

**Issue by Rene36** [FederatedAI/FATE#5554]
Dear FATE Team,

I am currently writing a survey paper on Federated Computing. One part of it describes existing FL frameworks. Could you please let me know which communication protocol (e.g., gRPC, WebSocket, HTTP, GLOO) and serialization method (e.g., Pickle, JSON, Protobuf, FOBS) FATE supports? I already saw in your documentation that you support gRPC, but maybe there is more.

Any help is highly appreciated.

**Comment by dylan-fan** [comment]
grpc

**Comment by dylan-fan** [comment]
pickle，protobuf
