### ISSUE TITLE
关于某些算法的参数配置

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5558]
类似文件/components/components/nn/runner/hetero_default_runner.py里DefaultRunner，初始化的参数里有
        bottom_model_conf: Optional[Dict] = None,
        top_model_conf: Optional[Dict] = None,
        agglayer_arg_conf: Optional[Dict] = None,
        top_model_strategy_arg_conf: Optional[Dict] = None,
        dataset_conf: Optional[Dict] = None,
        optimizer_conf: Optional[Dict] = None,
        training_args_conf: Optional[Dict] = None,
        loss_conf: Optional[Dict] = None,
        data_collator_conf: Optional[Dict] = None,
        tokenizer_conf: Optional[Dict] = None,
        task_type: Literal["binary", "multi", "regression", "others"] = "binary",
        threshold: float = 0.5

像这种每个算法具体有什么参数，进行什么设置，有没有说明对应文档什么的，或者这一大堆
_conf的字典里具体是什么样的值，有没有举例子？
homo_default_runner也是类似的道理。
方便开发人员知道怎么调用

**Comment by talkingwallace** [comment]
目前这块还没有具体文档说明，我们后续会补充上
可以看一下homonn的pipeline example和runner内部的代码，这些conf（dict）的主要作用就是传递参数，让runner可以初始化各种模型、优化器等等

如果是自己做实验的话，推荐直接在ml层面使用https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/ml/homo_nn_tutorial.md
用起来很直观
