### ISSUE TITLE
项目的DataFrame，是在pandas的基础上扩展的DataFrame，还是自定义的

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5559]
由于无法找到可以打断点的方法，所以只能用打日志的方式进行调试。
![image](https://github.com/FederatedAI/FATE/assets/127292082/b27b2caf-38c5-43c8-8bef-fe490cc13dc2)
问题在于这个DataFrame的对象里，没有info。
'DataFrame' object has no attribute 'info'
所以这个DataFrame主要什么方法属性？

**Comment by talkingwallace** [comment]
DataFrame是自行开发的，底层不一样
