### ISSUE TITLE
联邦学习发起方角色是否固定

### ISSUE THREAD

**Issue by dyx0001** [FederatedAI/FATE#5567]
联邦学习中必须由guest发起联合计算任务么？是否可以由第三方发起？

**Comment by dylan-fan** [comment]
FATE目前是guest发起任务

**Comment by dyx0001** [comment]
好吧，本来想着让中心节点发起联邦学习任务，看来目前是无法实现了。还有一个问题是横向联邦学习的各个参与方，是否可以通过某种策略，最终各自训练出个性化模型，分别适配自身数据？

**Comment by dylan-fan** [comment]
这个可以自己实现个性化联邦学习算法
