### ISSUE TITLE
如果我想对框架自定义的Dataframe的元素进行操作，该如何进行

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5568]
![image](https://github.com/FederatedAI/FATE/assets/127292082/3711494d-6d02-4325-a579-713485a681de)
这里的apply_row输入的是行，我想实现类似df = df.apply(lambda x: sm2_crypt.encrypt(x))或者df = df.applymap(lambda x: x**2)
这类的针对元素级的操作效果。
但是目前自定义的框架没有支持相关操作，如果使用as_pd_df转换为传统Dataframe操作，如何转换回来又是一个问题。
由于目前框架不支持SM2算法，所以想进一切操作想要实现，如果切入和对接就成了一个严重的问题，望请赐教，感谢

**Comment by mgqa34** [comment]
apply_row给的是每行的带schema数据（pd.Series)，理论上通过这个是可以完成对元素级的操作？这里没看懂为什么会觉得没法完成这种操作，sm2和ecdh应该是类似的逻辑
