### ISSUE TITLE
求教关于改动源代码

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5570]
修改的文件代码位于“fate\python\fate\arch\protocol\psi\ecdh\_run.py”，目的是为了在Curve25519之外新增一种方法，多种尝试之后遇到一些困难
```
    import sys
    sys.path.append('/home/app/projects/fate/fate/python/fate/arch/protocol/psi/ecdh/')
    import curve_util as utils
    logger.info(f"else逻辑1")
    curve = utils.Curve()
    private_key = randint(1, curve.n - 1)
    logger.info(f"else逻辑2")
    match_id = df.match_id.block_table
    logger.info(f"match_id：{match_id}")
    # guest_first_sign_match_id=_encrypt_bytes_sm2(match_id, curve=curve, private_key=private_key)
    encrypt_func = functools.partial(_encrypt_bytes_sm2, curve=curve, private_key=private_key)
    guest_first_sign_match_id = match_id.mapValues(encrypt_func)
    logger.info(f"guest_first_sign_match_id：{guest_first_sign_match_id}")
```
这部分部分是我模仿原有代码写的一段代码，其中_encrypt_bytes_sm2是我自定义的一个方法，curve=curve, private_key=private_key都是在前文自行初始化的参数对象。
这样运行的时候
==== detail start, at 2024-04-11 14:09:09 426908 ====
Traceback (most recent call last):
  File "/home/app/projects/fate/eggroll/python/eggroll/trace/_exception_logger.py", line 8, in wrapper
    return func(*args, **kw)
  File "/home/app/projects/fate/eggroll/python/eggroll/core/command/command_service.py", line 29, in call
    call_result = CommandRouter.get_instance().dispatch(
  File "/home/app/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 131, in dispatch
    raise e
  File "/home/app/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 126, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/home/app/projects/fate/eggroll/python/eggroll/computing/tasks/__init__.py", line 65, in exec
    result = handler.run(self.env_options, task.job, task)
  File "/home/app/projects/fate/eggroll/python/eggroll/computing/tasks/impl/_map_partitions_with_index.py", line 31, in run
    map_op = job.first_functor.func
  File "/home/app/projects/fate/eggroll/python/eggroll/core/meta_model/_core_model.py", line 394, in func
    return cloudpickle.loads(self._body)
ModuleNotFoundError: No module named 'curve_util'
每一行都会有这个错误。日志中“else逻辑2”字样正常输出，也就是说对于curve_util的引用应该是没有报错的。curve_util是我自定义写一个文件，是否是有需要进行组件注册之类的操作。
如果我换成  被注释掉的写法guest_first_sign_match_id=_encrypt_bytes_sm2(match_id, curve=curve, private_key=private_key)，直接调用该方法。
```
        logger.info(f"_encrypt_bytes_sm2：1")
        # id_list = [bytes(_id, "utf8") for _id in values[0]]
        id_list = values[0]
        id_list = [_id for _id in values[0]]
        logger.info(f"_encrypt_bytes_sm2：2")
```
日志中“else逻辑2”字样正常输出，“_encrypt_bytes_sm2：1”字样正常输出，但是无论这个id_list用哪种写法，均报错'Table' object is not subscriptable。

**Comment by mgqa34** [comment]
eggroll/conf/eggroll.properties下面需要配置pythonpath，默认加的是fate的部署目录和eggroll/python，可以确认下curve_util是否在这两个pythonpath下，不在的话，需要加进去

**Comment by RayWang99** [comment]
> eggroll/conf/eggroll.properties下面需要配置pythonpath，默认加的是fate的部署目录和eggroll/python，可以确认下curve_util是否在这两个pythonpath下，不在的话，需要加进去

就是说我自己写的工具类是要指定放在某个固定的目录下才行吗？然后目前默认的目录是原生设计未经修改的目录是/home/app/projects/fate/common/python/venv/bin/   以及 /home/app/projects/fate/eggroll/python/
将相关自定义类的放到这下面，有固定的命名规则之类的吗

**Comment by mgqa34** [comment]
如果是eggroll引擎的话，要在它的pythonpath里面能导入，如果不在的话，要增加pythonpath
