### ISSUE TITLE
import PipeLine,ModuleNotFoundError: No module named 'pipeline.backend'

### ISSUE THREAD

**Issue by LeoLiding** [FederatedAI/FATE#5572]
**Describe the bug**
from pipeline.backend.pipeline import PipeLine

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pipeline.backend.pipeline import PipeLine

ModuleNotFoundError: No module named 'pipeline.backend'

我已经装好了pipeline、fate2.1.0，fate flow和fate client，但是仍然报错，

**Comment by mgqa34** [comment]
安装2.1.0的pipeline的话，请使用2.0+的examples，"from pipeline.backend.pipeline import PipeLine"的语法应该是fate-1.x的
