### ISSUE TITLE
求教，关于集群代码的修改

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5573]
比如现在有一个guest 9999和一个host 10000。
我目前在9999修改PSI的代码（run_on_guest）模式，是否系统同步把修改的内容也改到其他的host上（现在只有1一个guest和一个host，假设后期host多起来，会不会也需要都修改）？
谢谢

**Comment by mgqa34** [comment]
系统不会同步代码，需要各自的party手工同步。
