### ISSUE TITLE
使用fate api提交任务异常

### ISSUE THREAD

**Issue by icutool** [FederatedAI/FATE#5576]
fate环境：docker单机版fate
版本号：1.11.3
前置条件：我在fate容器里将9380使用0.0.0.0：9380暴漏出去了，在外部进行接口调用
错误：我在使用/v1/data/upload进行上传数据集之后，返回的结果都是success，然后使用/v1/job/submit进行提交训练，提交返回接口也是success，但是使用fateborder进行查看训练任务，任务进度在0%就会报错，显示can not found table name:breast_homo_guest namespace:expriment,但是在fateborder能看到数据是提交成功的，如果在docker容器里面使用fate-client是没问题的
![任务列表](https://github.com/FederatedAI/FATE/assets/58366347/9958e1d8-fe08-425c-bea9-61e263b24508)
![报错信息](https://github.com/FederatedAI/FATE/assets/58366347/87b34e50-e9a1-484e-b7b4-8b6aa0ec68fe)

**Comment by mgqa34** [comment]
有没有可能是上传任务的name\namespace不匹配？再确认一下
