### ISSUE TITLE
线性回归模型使用Evaluation处，传递几个参数，但实际显示只有rmse，请问这是什么原因

### ISSUE THREAD

**Issue by Defu-csh** [FederatedAI/FATE#5578]
![image](https://github.com/FederatedAI/FATE/assets/74239663/fd3befd1-09b0-4d3c-8e37-b4dbe4ca7fec)
![image](https://github.com/FederatedAI/FATE/assets/74239663/dfae8b91-00d4-457f-b95c-946a7ca18c3b)

**Comment by mgqa34** [comment]
这个应该是fateboard展示有问题，可以通过flow cli先进行查询，我们后续会修复这个问题
