### ISSUE TITLE
关于内置的DataFrame

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5580]
guest_df = DataFrame.from_flatten_data(ctx, intersect_guest_data, df.data_manager, key_type="block_id")。
对于这样一个内置的DataFrame对象，我有办法通过自己生成的普通dataframe，或者list，dict之类的对象进行初始化吗？

在使用_table内置的_take(num)放取出数据list并进行相应操作后，有相应的方法再次使用变更后的数据list初始化_table，或者变更原_table里的数据吗

**Comment by mgqa34** [comment]
可以参考下这里：https://github.com/FederatedAI/FATE/blob/master/python/fate/ml/utils/predict_tools.py#L56
调用的案例：https://github.com/FederatedAI/FATE/blob/master/python/fate/components/components/nn/nn_runner.py#L232

**Comment by RayWang99** [comment]
> 可以参考下这里：https://github.com/FederatedAI/FATE/blob/master/python/fate/ml/utils/predict_tools.py#L56 调用的案例：https://github.com/FederatedAI/FATE/blob/master/python/fate/components/components/nn/nn_runner.py#L232

_table类型呢，是否也有类似的例子，万分感谢

**Comment by mgqa34** [comment]
> > 可以参考下这里：https://github.com/FederatedAI/FATE/blob/master/python/fate/ml/utils/predict_tools.py#L56 调用的案例：https://github.com/FederatedAI/FATE/blob/master/python/fate/components/components/nn/nn_runner.py#L232
> 
> _table类型呢，是否也有类似的例子，万分感谢

https://github.com/FederatedAI/FATE/blob/master/python/fate/arch/dataframe/ops/_dimension_scaling.py#L229
使用ctx.computing.parallelize接口就行，include_key=True的格式是[(k, v)...](迭代器，内容是(k, v), include_key=False的格式是[v1,v2...](迭代器，内容只有v，这个时候k会从0到len - 1)
