### ISSUE TITLE
我在单机版中试图调试PSI，目前遇到问题。

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5581]
pycharm远程运行examples\pipeline\psi\test_psi.py ，测试PSI功能。

在例子里是使用pipeline的方式运行reader，PSI。加入任务之后会进行task形式的运行。
请问有没有办法可以构造出相同的上下文，数据读取，传入PSI之类的，以普通方法调用的方式运行psi，这样远程断点可以进入，可以看到相关的一些变量的类型什么的

**Comment by dylan-fan** [comment]
可以参考 https://github.com/FederatedAI/FATE/tree/master/examples/launchers 这种模式

**Comment by RayWang99** [comment]
> 可以参考 https://github.com/FederatedAI/FATE/tree/master/examples/launchers 这种模式

非常感谢，很有帮助，我会尝试的这个思路的
