### ISSUE TITLE
FATE2.0 中如何使用 torch_geometric 中提供的 Dataset

### ISSUE THREAD

**Issue by ldq3** [FederatedAI/FATE#5582]
我想用 FATE2.0 框架来进行图数据集上的联邦学习，但似乎没有很好的 tutorial。我该怎样做？或者有没有好的教程？

**Comment by talkingwallace** [comment]
https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/ml/homo_nn_tutorial.md 你看看这个能不能帮到你？我理解你可以在ml层面直接跑代码

**Comment by ldq3** [comment]
> https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/ml/homo_nn_tutorial.md 你看看这个能不能帮到你？我理解你可以在ml层面直接跑代码

感谢！但事实上我已经看过这个 tutorial 了，我发现它里面用到的接口只针对 tabular dataset，令我感到无助的是我不知道应该怎么在图数据集上进行联邦学习。另外，我发现有 FATE 1.10 的相关的 tutorial （https://fate.readthedocs.io/en/latest/tutorial/pipeline/nn_tutorial/Homo-Graph/），所以我觉得应该是存在解决方法的，但是 FATE 2.0 的代码时（https://github.com/FederatedAI/FATE/tree/master/python/fate/ml/nn/dataset）发现似乎只有 table dataset。

**Comment by ldq3** [comment]
> https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/ml/homo_nn_tutorial.md 你看看这个能不能帮到你？我理解你可以在ml层面直接跑代码

感谢！但事实上我已经看过这个 tutorial 了，我发现它里面用到的接口只针对 tabular dataset，令我感到无助的是我不知道应该怎么在图数据集上进行联邦学习。另外，我发现有 FATE 1.10 的相关的 tutorial （[https://fate.readthedocs.io/en/latest/tutorial/pipeline/nn_tutorial/Homo-Graph），所以我觉得应该是存在解决方法的，但是当我查看 FATE 2.0 的代码时（https://github.com/FederatedAI/FATE/tree/master/python/fate/ml/nn/dataset）发现似乎只有对 table dataset 的支持。

**Comment by talkingwallace** [comment]
如果使用2.0版本的话 就不用参考1.10的教程了哈    2.0 ml模式下按照torch的使用习惯编写模型和数据集就行了
