### ISSUE TITLE
关于_table类型的一个内置方法的问题

### ISSUE THREAD

**Issue by RayWang99** [FederatedAI/FATE#5584]
关于_table类型内置方法mapValues，这个方法引用的是_map_reduce_partitions_with_index。在mapValues的x里把index传入，请问是否存在方法不会把index传入的？
我也不是很想用mapValues这个方法，但是由于我不知道如何初始化list为table类型，所以只能用传入的table类型反复的使用mapValues保持table类型

**Comment by Madoka-Zhang** [comment]
您好，请问您最后知道如何初始化list为table类型了吗？我也需要用到这个操作，但不知道怎么弄。。
