### ISSUE TITLE
multi-host 使用iv-filter来进行federated feature selection，但是报错Host metrics not found in provided model,请问应该这么解决，配置跟报错如下

### ISSUE THREAD

**Issue by Defu-csh** [FederatedAI/FATE#5587]
![image](https://github.com/FederatedAI/FATE/assets/74239663/12f000ce-131e-4ad4-890d-a989a1d58b9c)
binning_0:
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: psi_0
              parties:
              - role: guest
                party_id:
                - '9999'
              - role: host
                party_id:
                - '10001'
                - '10000'
        model: {}
      component_ref: hetero_feature_binning
      dependent_tasks:
      - psi_0
      parameters:
        n_bins: 10
        local_only: true
        transform_method: bin_idx
        method: bucket
        adjustment_factor: 0.5
        use_anonymous: false
        relative_error: 1.0E-6
        skip_metrics: false
selection_0:
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: psi_0
              parties:
              - role: guest
                party_id:
                - '9999'
              - role: host
                party_id:
                - '10001'
                - '10000'
        model:
          input_models:
            task_output_artifact:
            - output_artifact_key: output_model
              producer_task: binning_0
              parties:
              - role: guest
                party_id:
                - '9999'
              - role: host
                party_id:
                - '10001'
                - '10000'
      component_ref: hetero_feature_selection
      dependent_tasks:
      - psi_0
      - binning_0
      parameters:
        manual_param:
          keep_col:
          - x0
          - x1
        iv_param:
          filter_type:
          - threshold
          select_federated: true
          threshold:
          - 1.0
          metrics:
          - iv
          host_filter_type:
          - threshold
          host_take_high:
          - true
          host_threshold:
          - 1.0
          take_high:
          - true
        method:
        - iv
        statistic_param:
          filter_type: top_k
          threshold: 5
          metrics:
          - max
          - mean
        use_anonymous: false
        keep_one: true

**Comment by nemirorox** [comment]
如需使用iv filter，上游binning需关闭local only，同时在selection组件注明接入模型和对应filter，可参考此样例配置：https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/hetero_feature_selection/test_feature_selection_multi_host.py

**Comment by Defu-csh** [comment]
![image](https://github.com/FederatedAI/FATE/assets/74239663/0b9b4b89-ef89-4c2d-9399-be1a29553b7f)
binning_0组件把参数local only改成false之后，跑三方还是报错

**Comment by Defu-csh** [comment]
@nemirorox
