### ISSUE TITLE
Fate on spark，toy 单边测试 Federated schedule error

### ISSUE THREAD

**Issue by BoyangWei** [FederatedAI/FATE#5591]
**Describe the bug**
在部署完成fate on spark并启动fateflow,fateboard等组件后执行 `flow test toy -gid 10000 -hid 10000`报错

**To Reproduce**
1. source /pathtofate/bin/init_env.sh
2. flow test toy -gid 10000 -hid 10000
3. See error

**Screenshots**
![image](https://github.com/FederatedAI/FATE/assets/38055163/e9371377-1871-43f2-98a3-3765c68f3715)

**Additional context**
版本1.11.2，部署过程参考https://fate.readthedocs.io/en/latest/zh/deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide/#633-sparkspark.

**Comment by dylan-fan** [comment]
fate on spark测试话，建议用fate 2.1版本

**Comment by BoyangWei** [comment]
> fate on spark测试话，建议用fate 2.1版本

我这里环境是ARM，换版本做适配比较麻烦。有别的解决办法吗？

**Comment by BoyangWei** [comment]
问题出在nginx没有将请求转发到fate flow端，需要重新配置nginx
