### ISSUE TITLE
请问“hetero_nn”中的“runner_conf”参数应该都写啥呢

### ISSUE THREAD

**Issue by 123fei1** [FederatedAI/FATE#5595]
您好：我发现有些算子参数是dict类型的，但没有说明具体的填充值是哪些？应该填什么值? 就好比“hetero_nn”中的“runner_conf”参数，请问有具体的说明文档吗？

**Comment by 123fei1** [comment]
我执行了一个”hetero_nn“的任务，报错如下，但我不知道如何正确的配置参数
![1715410834331](https://github.com/FederatedAI/FATE/assets/107091149/83b0c15e-babf-44ea-8729-8fabc60aa9e1)

**Comment by talkingwallace** [comment]
如果只是本地运行的话，建议在ml层面使用，可以参考这个文档 https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/ml/hetero_nn_tutorial.md
使用会直观很多
