### ISSUE TITLE
SecureInformationRetrieval组件使用报错问题

### ISSUE THREAD

**Issue by ShaoYULi12** [FederatedAI/FATE#5598]
使用pir组建的时候报这个错误：
`"Traceback (most recent call last):\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py\", line 144, in submit\n    raise Exception(\"create job failed\", response)\nException: ('create job failed', {'host': {9999: {'retcode': 100, 'retmsg': 'ValueError(\"component secure_information_retrieval_0, module SecureInformationRetrieval\\'s provider does not exist\")'}}, 'guest': {10000: {'retcode': 100, 'retmsg': 'ValueError(\"component secure_information_retrieval_0, module SecureInformationRetrieval\\'s provider does not exist\")'}}})\n"`
我的conf和dsl如下：
`
    "job_runtime_conf": {
        "dsl_version": 2,
        "initiator": {
            "role": "guest",
            "party_id": 10000
        },
        "role": {
            "host": [
                9999
            ],
            "guest": [
                10000
            ]
        },
        "component_parameters": {
            "role": {
                "guest": {
                    "0": {
                        "reader_0": {
                            "table": {
                                "name": "breast_hetero_host",
                                "namespace": "experiment"
                            }
                        },
                        "data_transform_0": {
                            "with_label": false
                        }
                    }
                },
                "host": {
                    "0": {
                        "reader_0": {
                            "table": {
                                "name": "breast_hetero_guest",
                                "namespace": "experiment"
                            }
                        },
                        "data_transform_0": {
                            "with_label": true
                        }
                    }
                }
            },
            "common": {
                "secure_information_retrieval_0": {
                    "security_level": 0.5,
                    "oblivious_transfer_protocol": "OT_Hauck",
                    "commutative_encryption": "CommutativeEncryptionPohligHellman",
                    "non_committing_encryption": "aes",
                    "dh_params": {
                        "key_length": 1024
                    },
                    "raw_retrieval": false,
                    "target_cols": [
                        "x0",
                        "x3"
                    ]
                }
            }
        }
    },
    "job_dsl": {
        "components": {
            "reader_0": {
                "module": "Reader",
                "output": {
                    "data": [
                        "data"
                    ]
                }
            },
            "data_transform_0": {
                "module": "DataTransform",
                "input": {
                    "data": {
                        "data": [
                            "reader_0.data"
                        ]
                    }
                },
                "output": {
                    "data": [
                        "data"
                    ],
                    "model": [
                        "model"
                    ]
                }
            },
            "secure_information_retrieval_0": {
                "module": "SecureInformationRetrieval",
                "input": {
                    "data": {
                        "data": [
                            "data_transform_0.data"
                        ]
                    }
                },
                "output": {
                    "data": [
                        "data"
                    ],
                    "model": [
                        "model"
                    ]
                }
            }
        }
    }
`

**Comment by mgqa34** [comment]
SecureInformationRetrieval默认不支持组件级别的调用，如果需要组件调用，可以在python/federatedml/components目录下进行注册
