### ISSUE TITLE
fate on spark 任务执行失败，找不到./python_env/bin/python

### ISSUE THREAD

**Issue by BoyangWei** [FederatedAI/FATE#5599]
## 版本与部署环境
fate on spark v1.11.2

## 错误截图
![image](https://github.com/FederatedAI/FATE/assets/38055163/21581664-da83-4383-a99d-13ce8536be49)

## 复现方式
(venv) ``flow test toy -gid 10000 -hid 10000``

### SPARK 任务提交脚本
在日志中找到了提交脚本 `` /home/wby/jydata/local/spark-3.1.2/bin/spark-submit --name=202405131701189946420_secure_add_example_0#guest --num-executors=2 --executor-cores=1 --archives hdfs://tg01:9010/fate_dependence/1.11.2/fate.zip#fate_code,hdfs://tg01:9010/fate_dependence/1.11.2/python_env.tar.gz#python_env --conf spark.pyspark.python=./python_env/bin/python --conf spark.executorEnv.PYTHONPATH=./fate_code/fate/python:$PYTHONPATH --conf spark.pyspark.driver.python=/home/wby/fate/common/python/venv/bin/python /home/wby/fate/fateflow/python/fate_flow/worker/task_executor.py --job_id 202405131701189946420 --component_name secure_add_example_0 --task_id 202405131701189946420_secure_add_example_0 --task_version 0 --role guest --party_id 10000 --config /home/wby/fate/fateflow/jobs/202405131701189946420/guest/10000/secure_add_example_0/202405131701189946420_secure_add_example_0/0/task_executor/5db926aa110711efa7b28c2a8e87b876/config.json --result /home/wby/fate/fateflow/jobs/202405131701189946420/guest/10000/secure_add_example_0/202405131701189946420_secure_add_example_0/0/task_executor/5db926aa110711efa7b28c2a8e87b876/result.json --log_dir /home/wby/fate/fateflow/logs/202405131701189946420/guest/10000/secure_add_example_0 --parent_log_dir /home/wby/fate/fateflow/logs/202405131701189946420/guest/10000 --worker_id 5db926aa110711efa7b28c2a8e87b876 --run_ip tg01 --run_port 9380 --job_server tg01:9380 --session_id 202405131701189946420_secure_add_example_0_0_guest_10000 --federation_session_id 202405131701189946420_secure_add_example_0_0 ``

 可以看到是``-conf spark.pyspark.python=./python_env/bin/python`` 参数被设置成了 ``./python_env/bin/python``。 但是我在spark-env.sh中配置了``export PYSPARK_PYTHON=/home/wby/fate/common/python/venv/bin/python``, 不清楚为什么没有生效。
 
### 在mysql中的依赖信息截图
![image](https://github.com/FederatedAI/FATE/assets/38055163/4d0fede1-95df-4682-bd19-378eb4355d26)

### HDFS中分发的依赖
![image](https://github.com/FederatedAI/FATE/assets/38055163/f934b437-0b14-4592-af9c-c4f7d0913bea)
不知道是不是因为分发的依赖没有下载导致的问题。python_env.tar.gz的结构如下：
![image](https://github.com/FederatedAI/FATE/assets/38055163/a8c1d6b7-009c-475a-b249-2e408e9648e6)

**Comment by dylan-fan** [comment]
fate on spark，建议使用2.1.0版本

**Comment by BoyangWei** [comment]
2.1.0 on spark 部署方式和[ v1.11.2 on spark 部署方式]( https://fate.readthedocs.io/en/latest/zh/deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide)一样吗？
