### ISSUE TITLE
fate支持不同版本的联合建模吗？

### ISSUE THREAD

**Issue by didadida321** [FederatedAI/FATE#5600]
不同版本之间，fate支持联合建模吗？比如1.7和1.8之间可以吗？

**Comment by mgqa34** [comment]
不支持跨大版本（前两位版本号有差异）的联合建模

**Comment by didadida321** [comment]
好的多谢，那1.7.0和1.7.2之间通么？我这边测试好像也不通

**Comment by mgqa34** [comment]
不涉及release.md里面新增/bug-fix的内容应该是可以通的，报错是什么呢？
