### ISSUE TITLE
multi-host任务失败

### ISSUE THREAD

**Issue by Defu-csh** [FederatedAI/FATE#5601]
![image](https://github.com/FederatedAI/FATE/assets/74239663/634bc19f-5f91-44e7-abc5-5a37d197a1b7)
binning_0组件把参数local only改成false之后，跑三方还是报错，请问这种怎么解决
binning_0组件参数如下：
binning_0:
inputs:
data:
train_data:
task_output_artifact:
output_artifact_key: train_output_data
producer_task: feature_scale_0
model: {}
parties:
- role: guest
party_id:
- '9999'
- role: host
party_id:
- '10000'
- '10001'
component_ref: hetero_feature_binning
dependent_tasks:
- feature_scale_0
parameters:
n_bins: 10
method: quantile
use_anonymous: false
local_only: false
adjustment_factor: 0.5
relative_error: 1.0E-6
skip_metrics: false

**Comment by Defu-csh** [comment]
binning_0组件参数如下：
binning_0:
      inputs:
        data:
          train_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: feature_scale_0
        model: {}
      parties:
      - role: guest
        party_id:
        - '9999'
      - role: host
        party_id:
        - '10000'
        - '10001'
      component_ref: hetero_feature_binning
      dependent_tasks:
      - feature_scale_0
      parameters:
        n_bins: 10
        method: quantile
        use_anonymous: false
        local_only: false
        adjustment_factor: 0.5
        relative_error: 1.0E-6
        skip_metrics: false

**Comment by mgqa34** [comment]
每一方都是这个错误吗？

**Comment by Defu-csh** [comment]
只有一个host方会报这种错误

**Comment by Defu-csh** [comment]
然后我把多方改成两方之后这个host也还是报这个错误，请问这种会是什么原因导致的呢，这个host是ubuntu系统
