### ISSUE TITLE
FATE1.10.0集群版，我想自定义一个图像类的算法集成上去，但是自定义的图像数据集怎么上传呢？DSL和pipeline方式都不行吗？

### ISSUE THREAD

**Issue by Dopaine999** [FederatedAI/FATE#5603]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dopaine999** [comment]
conf文件里的"role": {
            "host": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "breast_homo_host",
                            "namespace": "experiment"
                        }
                    },
                    "data_transform_0": {
                        "with_label": true
                    }
                }
            },
            "guest": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "breast_homo_guest",
                            "namespace": "experiment"
                        }
                    },

**Comment by Dopaine999** [comment]
请问conf文件里的两方角色的name&namespace是通过什么接口进行读取绑定的呢？
"role": {
            "host": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "breast_homo_host",
                            "namespace": "experiment"
                        }
                    },
                    "data_transform_0": {
                        "with_label": true
                    }
                }
            },
            "guest": {
                "0": {
                    "reader_0": {
                        "table": {
                            "name": "breast_homo_guest",
                            "namespace": "experiment"
                        }
                    },

**Comment by mgqa34** [comment]
图像数据集只能通过table_bind进行绑定

**Comment by Dopaine999** [comment]
> 图像数据集只能通过table_bind进行绑定

感谢您的回答。我还想请问table_bind目前是只有nn模块支持吗？如果要自己自定义图像类算法开发的话，有相应的开发文档吗？谢谢！
