### ISSUE TITLE
hetero_nn多个host训练

### ISSUE THREAD

**Issue by Defu-csh** [FederatedAI/FATE#5605]
请问hetero_nn多个host的配置文件应该怎么写，根据两方的改成多host的任务报错（新增的一个host方报错，其他两方不报错）显示错误如下
![image](https://github.com/FederatedAI/FATE/assets/74239663/b2fe6fe8-6047-4b67-b22e-5c620bf95bce)
请问这种应该怎么解决

**Comment by talkingwallace** [comment]
基于SSHE的 hetero-nn暂时不支持多host哦

**Comment by Defu-csh** [comment]
那请问支持通过FedPass来进行多host训练吗，还是说只要是hetero-nn都不支持多host




只愿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月21日(星期二) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] hetero_nn多个host训练 (Issue #5605)





 
基于SSHE的 hetero-nn暂时不支持多host哦
