### ISSUE TITLE
fate建模如何避免提前终止？

### ISSUE THREAD

**Issue by didadida321** [FederatedAI/FATE#5607]
通过fate跑xgb算法，树的棵树为100颗，但是当tol较小时，会提前终止建模，可能只有50颗树，如何避免提前终止呢？除了将tol设置极小，有什么开关参数吗？

**Comment by mgqa34** [comment]
要看下具体是什么算法，如果是secure_boost的话，有个n_iter_no_change设置为False就行，如果是其他算法，要将tol设置得比较小
