### ISSUE TITLE
横向联邦逻辑回归是否支持多host方式，支持的话是否可以提供一个简单事例？

### ISSUE THREAD

**Issue by dyx0001** [FederatedAI/FATE#5611]
横向联邦逻辑回归是否支持多host方式，支持的话是否可以提供一个简单事例？

**Comment by mgqa34** [comment]
多host是支持的，这里说的提供案例，需要的是fate-1.x还是fate-2.x的用例？

**Comment by dyx0001** [comment]
需要的是fate-1.11.4版本的案例
