### ISSUE TITLE
Where is HomoSecureBoost? 横向安全提升树算法在哪里？

### ISSUE THREAD

**Issue by Concinnity-P** [FederatedAI/FATE#5615]
**Describe the bug**
I can't find the HomoSecureBoost. I want to implement this algo with FATE as it is mentioned in the officical documentation.

The algorithm should have been implemented previously by FATE. There are already some users posted issues related to it. But I could not find the algo anywhere. Please kindly suggest where I could find the algo or kindly provide any tutorial about the implementation.

根据官方文档，横向安全提升树已经被实现，但我并没有在FATE中找到相关的class，请问有相关的教程和实现方法嘛？

**Comment by mgqa34** [comment]
需要的话可以看fate-1.x版本，fate-2.1还没迁移

**Comment by dylan-fan** [comment]
我们也非常欢迎你能在FATE 2.x的基础上贡献HomoSecureBoost实现。
