### ISSUE TITLE
请问下 1.7 版本提交 SIR 任务，支持设置不输出未匹配到的 id 吗？

### ISSUE THREAD

**Issue by naruto2902git** [FederatedAI/FATE#5616]
https://fate.readthedocs.io/en/v1.7.2/federatedml_component/sir/

**Comment by mgqa34** [comment]
不支持，可以download数据后自己做过滤?

**Comment by naruto2902git** [comment]
> 不支持，可以download数据后自己做过滤?

再请教下，高版本中有支持这个功能的吗？

**Comment by dylan-fan** [comment]
目前也不支持。
