### ISSUE TITLE
FATE1.10集群版，nn模块下开发的dateset读取图像数据集的类，可以用于自定义算法模块读取自定义数据集吗？

### ISSUE THREAD

**Issue by Dopaine999** [FederatedAI/FATE#5622]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mgqa34** [comment]
可以的，图像是通过table bind本地路径之后，使用时直接透传绑定的路径，用类似的方法去处理自己的数据就好

**Comment by sagewe** [comment]
由于传递的是路径，你可以做任何你想要的操作，你可以从这里开始 https://github.com/FederatedAI/FATE/blob/0e36edc936394331dbefa868eec236808fadbd62/python/fate/components/components/homo_nn.py#L51
