### ISSUE TITLE
请问能fate-serving 2.0.0模型发布、绑定是怎么做的？能给个文档吗？

### ISSUE THREAD

**Issue by cloud66881314** [FederatedAI/FATE#5624]
请问能fate-serving 2.0.0模型发布、绑定是怎么做的？能给个文档吗？
我找遍了全网没有找到，fate-serving是怎么操作的，都是1版本的文档，2版本的文档一个也没有，这让我们如果学习呀？起码给个示例呀，怎么在线预测？请给个文档，谢谢。

**Comment by dylan-fan** [comment]
你说的是FATE Serving2.0 还是FATE 2.0。
目前FATE-Serivng 最新版本是2.1，支持的FATE 1.x 系列模型在线推理。
目前FATE-Serving 还不支持 FATE  2.0

**Comment by cloud66881314** [comment]
我使用 FATE2.0 时，按照例子训练完模型后，不清楚后续怎么使用了，例如，怎么保存模型，导入模型，怎么进行预测，将模型发布到fate-serving进行在线预测。我查看了github上的所有文档，都没有说，有的只是FATE1.0版本的文档。例如 https://github.com/FederatedAI/FATE-Serving/blob/master/document/docs/model/load.md 上面只说了模型发布、模型绑定的配置，具体怎么操作没说，这根本没法玩哦。
建议你们发布新版本，请将用例也更新下哦，不然我们使用的根本不知道如何入手，很快大家会放弃的，那只能以后你们自己玩了。
还有加你们的微信助手一直也加不了，一个沟通群也没有，微信、钉钉都可以呀，有问题找不到人，这样下去我看你们还是闭源自己玩的好。

**Comment by dylan-fan** [comment]
目前FATE 2.0还不支持在线推理（FATE-Serving）。可以支持离线预测。

**Comment by cloud66881314** [comment]
请问离线预测怎么操作呢？有没有相关的文档，谢谢

**Comment by mgqa34** [comment]
> 请问离线预测怎么操作呢？有没有相关的文档，谢谢

如果使用的是dag.yaml的格式去提交，可以参考下：https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/dag.md作为修改
我们更建议的方式是使用pipeline去建模，可以参考下：https://github.com/FederatedAI/FATE-Client/blob/main/doc/pipeline.md#deploy-components，这里可以做一个步骤分离，就是训练完成之后，pickle.dumps(pipeline)，然后再使用pickle.loads()去加载回来。当前pickle.loads可能会碰到问题，可以参考issue #5613，我们会在月底版本进行修复

**Comment by cloud66881314** [comment]
谢谢耐心回复，我研究下，不懂再请教您

**Comment by cloud66881314** [comment]
给个小建议，感觉您给写文档是给专业人士或内部人士使用的，就像是随笔，太乱了。我想很多新手，希望的是有一篇能够跑到底的示例文章，例如从数据获取、特征处理、模型训练、保存、加载、预测……，这一个流程能够走通的文档，但很遗憾的是没有，东找一下西找一下，还不一定能跑通，太累人了。如果您能够写好文档，我相信start会涨很多的

**Comment by mgqa34** [comment]
感谢您的提议，现在确实是文档比较孤立，我们后续会持续地完善，如果您有其他建议也可以继续提出，也可以贡献文档哈～

**Comment by dylan-fan** [comment]
quick start 可以参考这个： https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/quick_start.md

**Comment by dylan-fan** [comment]
感谢你的建议，这里补充说明下FATE-Serving 和 FATE的版本关系。 https://github.com/FederatedAI/FATE-Serving/wiki

**Comment by kongshijie** [comment]
fate-serving 后续有计划支持 fate2.x吗？
