### ISSUE TITLE
1.10.0版本能否支持OSX

### ISSUE THREAD

**Issue by aoaos111** [FederatedAI/FATE#5625]
1.10.0版本能否支持OSX,需要在代码里面2次开发吗

**Comment by dylan-fan** [comment]
默认不支持，如果想用osx，可以参考 FATE 2.x 改下 fate 1.x 里面federation代码，适配osx

**Comment by dylan-fan** [comment]
或者考虑切到eggroll 3.1，这个可以适配osx，用类似之前rollsite的流式模式

**Comment by dylan-fan** [comment]
FATE 2.1 的 release 内容  “OSX：Compatible with eggroll-v2.x”

**Comment by yx0090sh** [comment]
@aoaos111  1.10是可以支持osx 的， 具体方法就是 需要stop fate-rollsite 的服务， 启动osx服务
osx 需要更改一下配置  
文件osx/conf/broker/broker.properties
grpc.port= 9370
self.party=9999
# the IP  of the cluster manager component of eggroll
eggroll.cluster.manager.ip = 192.168.0.1
# the port of the cluster manager component of eggroll
eggroll.cluster.manager.port = 4670
eggroll.version=2.5.x

路由表和之前差不多，注意osx路由表最后有个 self_party

**Comment by aoaos111** [comment]
> FATE 2.1 的发布内容“OSX：兼容 eggroll-v2.x”

好的多谢

**Comment by aoaos111** [comment]
> @aoaos111 1.10是可以支持osx的，具体方法是需要stop fortune-rollsite 服务，启动osx服务 osx需要更改一下配置 文件osx/conf/broker/broker.properties grpc.port= 9370 self.party=9999 eggroll.cluster.manager.ip = 192.168.0.1 eggroll.cluster.manager.port = 4670 eggroll.version=2.5.x
> 
> 路由表和之前差不多，注意osx路由表最后有个self_party

好的感谢
