### ISSUE TITLE
横向、纵向联邦的离线预测问题

### ISSUE THREAD

**Issue by cloud66881314** [FederatedAI/FATE#5627]
请问当服务器重启后，怎样使用已经训练好的保存过的模型进行预测？
能不能分别给出横向、纵向联邦的离线预测示例？目前我只找到纵向预测示例，但我感觉重启后就不能用了，谢谢

from fate_client.pipeline.components.fate import HomoLR, Evaluation, Reader, Union
from fate_client.pipeline import FateFlowPipeline
from fate_client.pipeline.utils import test_utils
import pickle

guest = '9999'
host = '10000'
arbiter = '10000'
pipeline = FateFlowPipeline().set_parties(guest=guest, host=host, arbiter=arbiter)

reader_0 = Reader("reader_0", runtime_parties=dict(guest=guest, host=host))
reader_0.guest.task_parameters(
namespace=f"db",
name="homo_cancer_guest"
)
reader_0.hosts[0].task_parameters(
namespace=f"db",
name="homo_cancer_host"
)

homo_lr_0 = HomoLR(
"homo_lr_0",
epochs=10,
batch_size=16,
train_data=reader_0.outputs["output_data"]
)

evaluation_0 = Evaluation(
'eval_0',
metrics=['auc'],
input_data=[homo_lr_0.outputs['train_output_data']]
)

pipeline.add_tasks([reader_0, homo_lr_0, evaluation_0])
pipeline.compile()
pipeline.fit()

预测出现问题，使用的数据是原来训练的，并没有使用新数据，但deploy函数不加 reader_0 又报错
请问横向联邦怎么预测新数据呢
为什么需要语句：pipeline.deploy([reader_0, homo_lr_0])，如果下次重启服务器后，这个语句还能执行吗？
pipeline.deploy([reader_0, homo_lr_0])
pipeline.dump_model("pipeline.pkl")
predict_pipeline = FateFlowPipeline.load_model("pipeline.pkl")
reader_1 = Reader("reader_1", runtime_parties=dict(guest=guest, host=host))
reader_1.guest.task_parameters(
namespace=f"db",
name="homo_cancer_test_guest"
)
reader_1.hosts[0].task_parameters(
namespace=f"db",
name="homo_cancer_test_host"
)

请问为什么要加 语句：pipeline.get_deployed_pipeline，如果下次重启服务器后，这个语句还能执行吗？
deployed_pipeline = pipeline.get_deployed_pipeline()
deployed_pipeline.input_data = reader_1.outputs["output_data"]

predict_pipeline.add_tasks([reader_1, deployed_pipeline])
predict_pipeline.compile()
print(predict_pipeline.compile().get_dag())
predict_pipeline.predict()

**Comment by mgqa34** [comment]
"为什么需要语句：pipeline.deploy([reader_0, homo_lr_0])，如果下次重启服务器后，这个语句还能执行吗？"
"请问为什么要加 语句：pipeline.get_deployed_pipeline，如果下次重启服务器后，这个语句还能执行吗？"

可以无数次执行的，设计这句话的原因是在特定场景下，如果dag特别复杂，可能用户有用不同分支预测的需求，deploy的作用是推导预测的工作流，并且修改组件状态

**Comment by mgqa34** [comment]
预测出现问题，使用的数据是原来训练的，并没有使用新数据，但deploy函数不加 reader_0 又报错

请问是什么错误呢？ reader_0不应该被deploy，而是在预测时，加上新的reader_1用来设置新数据集

**Comment by cloud66881314** [comment]
请问能不能给2个简单示例给我呢？横向、纵向联邦的模型训练、保存、加载、离线预测新数据。网上找不到相关资料，谢谢。

**Comment by mgqa34** [comment]
https://github.com/FederatedAI/FATE/blob/feature-2.1.0-update_quick_start/doc/2.0/fate/quick_start.md
纵向可以参考下这个文档，横向我们会稍后补充

**Comment by FancyXun** [comment]
> https://github.com/FederatedAI/FATE/blob/feature-2.1.0-update_quick_start/doc/2.0/fate/quick_start.md 纵向可以参考下这个文档，横向我们会稍后补充

请问这个横向预测的例子有吗？
