### ISSUE TITLE
尊敬的开发者团队您好！请问一下对于secureboost过程相关的源代码在哪里

### ISSUE THREAD

**Issue by songyichun-1** [FederatedAI/FATE#5629]
对于secureboost建模过程，我想寻找一些源代码，希望能得到您的回答

1.在隐私约束下对数据进行对齐的（PSI）算法代码和通信过程，包括发送公钥，加密数据的代码

2.主动方在发送给被动方之前会加密梯度和海森矩阵。计算梯度，海森矩阵的代码以及通信时完成加密操作的代码

3.每个被动方使用[梯度]和[海森]计算加密的特征直方图，然后对（特征，分裂桶值）进行编码，并构建（特征，分裂桶值）查找表；然后将编码的（特征，分裂桶值）及特征直方图发送给主动方。计算特征直方图等行为和通信时的代码

4.主动方接收到被动方的特征直方图后，解密它们并找出最佳增益。如果最佳增益特征属于被动方，主动方将编码的（特征，分裂桶值）发回给所有者方。计算最佳增益的代码，以及通信的代码

以及：上述过程fate是否将例如发送公钥，发送加密数据包的动作记录到日志中呢？

期待您的回复
非常感谢！

**Comment by talkingwallace** [comment]
您好 你使用的是哪个版本呢？

**Comment by songyichun-1** [comment]
@talkingwallace 您好，我目前使用的是fate2.0版本

**Comment by talkingwallace** [comment]
您好，对于2，3，4 这里建议可以从secureboost的https://github.com/FederatedAI/FATE/blob/master/python/fate/ml/ensemble/algo/secureboost/hetero/guest.py guest方代码开始看起，在代码里对于2，3，4点通过代码引用找到对应的部分
对于 点1，对齐属于一个单独的功能，它没有ml部分的源码，属于fate基础代码的一部分，它的源码在这里：
https://github.com/FederatedAI/FATE/blob/master/python/fate/arch/protocol/psi/_psi_run.py
