### ISSUE TITLE
导出数据报错

### ISSUE THREAD

**Issue by tiatiayang** [FederatedAI/FATE#5636]
k8s 环境，fate pipline 任务正常执行，但是想把数据导出报错。
`flow output download-data -j 202406250224446234810 -r guest -p 8888 -tn lr_0 -o .

{
    "code": 6000,
    "message": "CommandCallError('Failed to call command: CommandURI(_uri=v1/eggs-pair/runTask) to endpoint: nodemanager:40161, caused by: ', <_InactiveRpcErr
or of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.42.153.110:
40161: Failed to connect to remote host: FD Shutdown\"\n\tdebug_error_string = \"UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.42.1
53.110:40161: Failed to connect to remote host: FD Shutdown {grpc_status:14, created_time:\"2024-06-25T10:01:47.93880071+00:00\"}\"\n>)"
}`

**Comment by zhihuiwan** [comment]
看起来像是eggroll服务挂了，可以检查下eggroll的服务看看

**Comment by tiatiayang** [comment]
有可能是网络问题，我增加了重试次数，可以拿到训练的数据。
