### ISSUE TITLE
尊敬的开发者团队您好，我对于eggroll组件有一些问题想咨询

### ISSUE THREAD

**Issue by songyichun-1** [FederatedAI/FATE#5650]
尊敬的开发者团队，您好！
目前我使用的fate版本为1.6.1的集群模式
对于eggroll，我现在想寻找其实现：
1.执行PSI算法步骤，例如发送公钥的实现代码
2.执行secureboost算法的步骤，例如发送加密的梯度和海森矩阵的代码
3.我想自己将这些步骤的记录（就是eggroll发送对应步骤数据包的记录）保存到eggroll的日志中，该如何操作
对于上述代码（例如sbt的计算梯度，加密梯度和发送梯度），我已经找到了fate在其他组件中如何实现的python代码，只是对于通信的部分还没找到，例如sbt在https://github.com/FederatedAI/FATE/blob/v1.6.1/python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py
此外，我想询问一下，1.6.1版本的fate集群模式，host和guest之间通信使用的是那种协议呢？以及他们之间进行通信的数据包，能否被常用的抓包软件抓取并分析。例如想对基于RSA的PSI算法的第一步（发送公钥）的步骤，如何抓包来进行分析
期待您的回复
谢谢！

**Comment by sagewe** [comment]
eggroll的通信模块为rollsite，客户端在https://github.com/FederatedAI/eggroll/blob/v2.5.3/python/eggroll/roll_site/roll_site.py
基于grpc通信的
节点直接使用java的模块通信
https://github.com/FederatedAI/eggroll/tree/v2.5.3/jvm/roll_site
也是基于grpc的

算法相关的代码都在FATE的python部分，公钥发送应该就是简单的remote/get，请参考相关的文档说明跟代码

另外，1.6.1版本以及非常老了，建议更新到新的版本以获得更好的算法性能和技术更新
