### ISSUE TITLE
HomoDecisionTree

### ISSUE THREAD

**Issue by linper1995** [FederatedAI/FATE#5651]
请问fate2.*版本的横向树模型的是不再支持了嘛？还是占时没有更新？如果有的话能否提供一下示例代码

**Comment by dylan-fan** [comment]
暂时还没来得及实现， 你们可以参考2.0框架和1.x 代码实现。

**Comment by linper1995** [comment]
> 暂时还没来得及实现， 你们可以参考2.0框架和1.x 代码实现。

是否有示例可以参考？如果有的话，麻烦您提供一下

**Comment by talkingwallace** [comment]
可以看下1.x版本federatedml ensemble下的相关代码的
