### ISSUE TITLE
PSI结果展示给哪一方是否可配置

### ISSUE THREAD

**Issue by dyx0001** [FederatedAI/FATE#5652]
我运行了官方事例中的pipeline-intersect-rsa.py，求交的结果总是guset方可见，无论是哪方发起的，如下图。请问这个结果向谁可见是否可配置？
![image](https://github.com/FederatedAI/FATE/assets/132547242/8d421332-e7d5-4a2c-9367-27c2f01f46ee)
![image](https://github.com/FederatedAI/FATE/assets/132547242/0a7f7138-6e61-4da4-9cfe-c552fcb36dd6)

**Comment by talkingwallace** [comment]
这个应该只有单方展示的
