### ISSUE TITLE
Sometimes misreporting occurs, ValueError: job running time exceed, please check federation or eggroll log

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/FATE#566]
when I run :
`python run_toy_example.py 10000 10000 1`
I got this:
```
...
job status is running
job status is running
Traceback (most recent call last):
  File "run_toy_example.py", line 197, in <module>
    exec_toy_example(runtime_config)
  File "run_toy_example.py", line 179, in exec_toy_example
    raise ValueError("job running time exceed, please check federation or eggroll log")
ValueError: job running time exceed, please check federation or eggroll log
```

I checked run_toy_example.py and found `MAX_TIME = 10`
This value may be too small. It should be changed to 20.

**Comment by mgqa34** [comment]
In ToyExample' default runtime conf , data size is 1000, and partition num is 10, there are only several kilobytes network transmission, so we think 10 seconds are enough.  By the way, after changed to 20s, do your job finish successfully ?

**Comment by slelove** [comment]
If it is 10, it will fail for the first time. If it changes to 20, it will always succeed.

**Comment by mgqa34** [comment]
We will take this issue into consideration. Thanks for your feedback!

**Comment by mgqa34** [comment]
We  change MAX_TIME = 10 to MAX_TIME = 100 since FATE-1.1, hope this will help.
