### ISSUE TITLE
Fate launchers与Fate-Flow的区别

### ISSUE THREAD

**Issue by DuanYuFi** [FederatedAI/FATE#5697]
您好，
我在学习使用FATE框架编写分布式多方的联邦学习场景代码，我看到Fate中存在两种书写代码的方式：[Training Demo with Only FATE Installed From Pypi](https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/ml)和[Training Demo with Both FATE AND FATE-Flow Installed From Pypi](https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/quick_start.md)。我想请教这两者除了在书写代码风格上有区别之外，是否在功能、性能上有区别？例如是否Fate-Flow更快？是否某一个方法所支持的功能更多？
期待回复，感谢！

**Comment by mgqa34** [comment]
FATE-2.0以后引入了两个解耦的概念：ML以及Component
ML: 比较自由的模式，用户可以把ML的代码直接当成一个算法库来进行调用、或者快速开发调试，对内容形式不做任何要求。
Component: 组件封装，是为了方便调度引擎等的调用，这个时候是在ML上进行进一步封装调用，在component里面需要实现ML的参数传递、流程调用、结果保存等操作
因此：
Launcher：调用的是ML代码，为了快速实验和验证一些idea，更多用在实验环境
FATE-Flow: 调用的是Component代码，根据用户提供的联邦任务工作流（DAG)按顺序进行调用，更多用于成熟组件的使用，以及用于生产环境

**Comment by DuanYuFi** [comment]
好的，十分感谢！
