### ISSUE TITLE
Practical application case

### ISSUE THREAD

**Issue by zouyip** [FederatedAI/FATE#5712]
Good project！ Is there any practical application case? Currently, the news on the official website is only updated until 2021.

**Comment by dylan-fan** [comment]
http://www.hbbill.com/uploadFiles/-16/548/058/54/%E8%81%94%E9%82%A6%E5%AD%A6%E4%B9%A0%E6%8A%80%E6%9C%AF%E9%87%91%E8%9E%8D%E5%BA%94%E7%94%A8%E7%99%BD%E7%9A%AE%E4%B9%A6.pdf

**Comment by zouyip** [comment]
Thanks a lot
