### ISSUE TITLE
使用pipeline时更换模型

### ISSUE THREAD

**Issue by youhl** [FederatedAI/FATE#5723]
使用pipeline训练时，能否更换初始模型，有相关教程或文档吗

**Comment by mgqa34** [comment]
更换初始模型是什么意思呢

**Comment by youhl** [comment]
比如test_nn_multi.py中导入了初始模型multi_model，能否导入本地其他的模型用以训练

**Comment by youhl** [comment]
比如test_nn_multi.py中导入了初始模型multi_model，能否导入本地其他的模型用以训练

**Comment by youhl** [comment]
> 更换初始模型是什么意思呢

比如test_nn_multi.py中导入了初始模型multi_model，能否导入本地其他的模型用以训练
