### ISSUE TITLE
使用KubeFate docker-deploy方法部署失败

### ISSUE THREAD

**Issue by DuanYuFi** [FederatedAI/FATE#5731]
**Describe the bug**

您好，

我使用KubeFate [docker-compose-release](https://github.com/FederatedAI/KubeFATE/releases/download/v2.0.0/kubefate-docker-compose-v2.0.0.tar.gz) 中的方法在三个机器上部署Fate training和serving，但是docker container一直重试。

![image](https://github.com/user-attachments/assets/a138d935-2d2c-4237-ae8c-63da3e4c2cde)

别的模块都可以启动，这是怎么回事？

附：各image tag如下：
![image](https://github.com/user-attachments/assets/c2a5688a-3a43-4e31-9678-6123d740671e)

谢谢！

**Comment by dylan-fan** [comment]
你们的镜像看起来不是最新的，很多怎么都是16个月以前的？

**Comment by DuanYuFi** [comment]
我更新后可以起来环境了：
![image](https://github.com/user-attachments/assets/9cd810d6-34ab-4e8a-b721-d307c02b552b)

不过不知道为什么测试不通过。
![image](https://github.com/user-attachments/assets/b284c948-f65e-47cd-879e-6e35f472fe09)

我的配置文件如下：
```
#!/bin/bash

user=root
dir=/data/projects/fate
party_list=(0 1 2)
party_ip_list=(172.26.232.247 172.26.232.248 172.26.232.249)
serving_ip_list=(172.26.232.247 172.26.232.248 172.26.232.249)

# Engines:
# Computing : Eggroll, Spark, Spark_local
computing=Eggroll
# Federation: OSX(computing: Eggroll/Spark/Spark_local), Pulsar/RabbitMQ(computing: Spark/Spark_local)
federation=Eggroll
# Storage: Eggroll(computing: Eggroll), HDFS(computing: Spark), LocalFS(computing: Spark_local)
storage=Eggroll
# Algorithm: Basic, NN, ALL
algorithm=Basic
# Device: CPU, IPCL, GPU
device=CPU

# spark and eggroll 
compute_core=8

# You only need to configure this parameter when you want to use the GPU, the default value is 1
gpu_count=1

# default
exchangeip=

# modify if you are going to use an external db
mysql_ip=mysql
mysql_user=fate
mysql_password=fate_dev
mysql_db=fate_flow
serverTimezone=UTC

name_node=hdfs://namenode:9000

# Define fateboard login information
fateboard_username=admin
fateboard_password=admin

# Define serving admin login information
serving_admin_username=admin
serving_admin_password=admin

# Define notebook login information
notebook_hashed_password=
```

另外，fate board的用户名密码也不对：
![image](https://github.com/user-attachments/assets/3771552b-d5ab-4425-945e-1bed2c9b0947)

**Comment by yx0090sh** [comment]
docker-compose 部署文档 https://github.com/FederatedAI/KubeFATE/blob/dev-2.2.0/docker-deploy/README_zh.md
fateboard的密码是正确的， 这种情况只需要刷新一下，再次登录即可，具体原因在于新服务覆盖了旧的，清理下缓存，或者刷新下再次登录就可以了

**Comment by DuanYuFi** [comment]
抱歉没有注意别的branch，我再试试，感谢！

**Comment by DuanYuFi** [comment]
:(
![image](https://github.com/user-attachments/assets/d3053492-3805-42e2-a9b3-695ca1c4dd23)

另外，fateboard清空缓存硬刷新仍然不work，密码错误:(，换浏览器也不行

**Comment by yx0090sh** [comment]
这是另一个错误了， fate_flow服务没有启动，需要看一下为什么flow没有启动，或者是没有启动需要 start一下

**Comment by DuanYuFi** [comment]
我认为是路由方面的问题，我该如何查看路由的配置？
![image](https://github.com/user-attachments/assets/46bf8fb9-c1a0-4f89-8756-4813f6932e96)
![image](https://github.com/user-attachments/assets/10c1a53f-2904-43da-9897-5ee755ee7d5f)

**Comment by DuanYuFi** [comment]
![image](https://github.com/user-attachments/assets/c1a0e022-e516-4b55-9cb9-018f9aaf64d4)
看起来是，fateflow的服务不能通过127.0.0.1的方式访问，而flow server info走的API是localhost的所以造成了这个问题。

请问这里是我部署的问题吗（部署完全按照教程），还是我机器的问题？现在我是应该更改路由表，让fateflow client走192.167的路径，还是应该排查为什么localhost访问不到服务的问题？

**Comment by yx0090sh** [comment]
建议不要用127.0.0.1

**Comment by DuanYuFi** [comment]
我没有手动指定127.0.0.1，这是部署后默认的。请问我该在哪里修改？

**Comment by yx0090sh** [comment]
具体部署参考
https://github.com/FederatedAI/KubeFATE/blob/dev-2.2.0/docker-deploy/README_zh.md

**Comment by maomaomiaomiao1234** [comment]
> 我没有手动指定127.0.0.1，这是部署后默认的。请问我该在哪里修改？

请问问题解决了吗，我现在也是一模一样的错误。
![image](https://github.com/user-attachments/assets/de35d62b-a768-4959-96d2-d05212b23646)

**Comment by DuanYuFi** [comment]
> 
> 请问问题解决了吗，我现在也是一模一样的错误。 

没有😂挣扎了一下放弃研究了

**Comment by maomaomiaomiao1234** [comment]
> > 请问问题解决了吗，我现在也是一模一样的错误。
> 
> 没有😂挣扎了一下放弃研究了

我也想放弃了，这个问题卡了好几天了 ：）。那老哥还有在部署FATE的集群版吗？

**Comment by DuanYuFi** [comment]
> 我也想放弃了，这个问题卡了好几天了 ：）。那老哥还有在部署FATE的集群版吗？

也没有，后来没有研究过FATE（

**Comment by maomaomiaomiao1234** [comment]
> > 我也想放弃了，这个问题卡了好几天了 ：）。那老哥还有在部署FATE的集群版吗？
> 
> 也没有，后来没有研究过FATE（

好的好的，谢谢了！
