### ISSUE TITLE
fate2.1.0 on arm 有相关部署文档吗？

### ISSUE THREAD

**Issue by jiejielu-0309** [FederatedAI/FATE#5751]
参照官网fate-builder/docs/arm/fate_run_on_arm.md文档，文档中示例是fate1.9.2版本。目前自己本地x86服务器是allinone方式部署的fate2.1.0版本。在arm服务器依照部署开始安装依赖、jdk、配置环境变量等操作，最终在arm服务器部署的fate2.1.0所有组件通过bash都能正常启动（mysql、fate_flow、eggroll、fateboard、osx），但是在flow test toy测试时报错：

<img width="692" alt="微信图片_20241211114959" src="https://github.com/user-attachments/assets/2d666377-8ae5-4333-a5dc-b0515fd0fd6f">

有什么解决办法吗？

**Comment by ShaoYULi12** [comment]
我们也遇到了同样的问题，请问你们是如何解决的呢
