### ISSUE TITLE
How to change the default selected evaluation scores?

### ISSUE THREAD

**Issue by ZhiyuanDang** [FederatedAI/FATE#583]
I use the docker version of FATE over Standalone. And I run the experiment about the hetero_secure_boost algorithm with my data by quick_run.py.

In the evaluation_0 module of the FATE board,  I found the default selected evaluation scores are AUC and K-S. 

If I want to use the accuracy with thresholds and the auc, what should I do?

**Comment by ZhiyuanDang** [comment]
Another question: what is the meaning of party id in quick_run.py? If I adopt a different dataset, should I modify its value?

**Comment by zazd** [comment]
please check the figure of evaluation in board， it should has accuracy， roc .... if not, check the log of evaluation to find if something error or warning.

**Comment by zazd** [comment]
the party id is the ID of role, for example, guest:9999, host:10000. It is nothing to do with what dataset you use

**Comment by ZhiyuanDang** [comment]
![image](https://user-images.githubusercontent.com/17498125/65022169-0b889180-d963-11e9-9bf2-ed0d225ce662.png)
I mean in this figure, how to change the auc and ks to auc and acc?

**Comment by ZhiyuanDang** [comment]
I could obtain these curves. But I want to display the above table with different items. In here,  they are auc and ks. But if I want to use auc and acc, what should I do?

**Comment by zazd** [comment]
You can not do this only if you change the code of evaluation. FATE's evaluation now support fixed format of evaluate output.

**Comment by ZhiyuanDang** [comment]
> You can not do this only if you change the code of evaluation. FATE's evaluation now support fixed format of evaluate output.

Fine, thanks your help.
