### ISSUE TITLE
when uploaded data with dimension 2.5 million * 150, it came up with "_end_unary_response_blocking" error

### ISSUE THREAD

**Issue by pandeBJ** [FederatedAI/FATE#625]
**Describe the bug**
Hi :
      when tried to upload data whose dimension is 2.5 million * 150, it came up with error logs in fate/python/jobs/*job_id*/std.log.

**logs**
 File "/data/projects/fate/venv/lib/python3.6/site-packages/grpc/_channel.py", line 625, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/projects/fate/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"

This situation didn't appearance when upload small data set. I doubt whether it was caused by the data set is large. And what's the proper way to upload large data set.
![image](https://user-images.githubusercontent.com/46129889/65652763-645ec680-e002-11e9-920b-6322e36fd8df.png)

**Comment by zengjice** [comment]
Please provide a log of the roll at the time, thank you.

**Comment by pandeBJ** [comment]
@zengjice sorry, i had delete the related logs. And after i change to another machine with bigger disk space to upload data, the issue was disappeared. I will attach the logs if encounter this issue in the future. thank you all the same.
