### ISSUE TITLE
where is the detail code after the post requests

### ISSUE THREAD

**Issue by chenj133** [FederatedAI/FATE#634]
**Is your feature request related to a problem? Please describe.**
when we run:
sh run.sh guest fast host_table_name_1569570831_8389 host_table_namespace_1569570831_8389
we get error with:
job running time exceed

we follow the py code and see the finally submit is:
requests.post('http://172.16.1.122:9380/v1/job/submit',json=post_data)
How can we known the program code running after the post requests on port 9380

**Comment by zengjice** [comment]
Hi,
FATE has the FATE-Flow system for task management and scheduling. The FATE-Flow contains the server and client, where the client provides the [CLI](https://github.com/FederatedAI/FATE/tree/master/fate_flow/doc). The run script calls the client through the subprocess, and the client will post data to the server. You can follow this line of thought to view the data stream.
