### ISSUE TITLE
Cluster Host&Guest cannot receive pallier public key when running Hetero Logistic Regression training

### ISSUE THREAD

**Issue by hi-hi-there** [FederatedAI/FATE#640]
The Guest and Hosts are waiting to get the keys but the Arbiter has already remote it. How do I go about debugging this?  Thank you
I suspect that the transferStatus is not updated, hence the Host/Guest keep waiting for the status to change from 0 to 3.

**Debug log from Guest (party id 10000), same for the Host as well(party id 90000)**
"2019-10-03 05:24:55,693 - task_executor.py[line:111] - INFO: {'data': {'data': ['intersection_0.train']}}"
"2019-10-03 05:24:55,694 - encrypt_param.py[line:65] - DEBUG: Finish encrypt parameter check!"
"2019-10-03 05:24:55,694 - model_base.py[line:61] - DEBUG: need_run: True, need_cv: False"
"2019-10-03 05:24:55,695 - model_base.py[line:223] - DEBUG: set flowid to transfer_variable, flowid: 201910030524353448356_hetero_lr_0.fit"
"2019-10-03 05:24:55,695 - hetero_lr_guest.py[line:102] - INFO: Enter hetero_lr_guest fit"
"2019-10-03 05:24:55,855 - federation.py[line:205] - DEBUG: [GET] guest 10000 :getting remote object HeteroLRTransferVariable.paillier_pubkey.201910030524353448356_hetero_lr_0.fit from arbiter [90000]"

**Debug log from Arbiter(party id 90000)**
"2019-10-03 05:22:00,112 - hetero_lr_arbiter.py[line:83] - INFO: Enter hetero_lr_arbiter fit"
"2019-10-03 05:22:00,120 - hetero_lr_arbiter.py[line:94] - INFO: public_key:<PaillierPublicKey ce341411cf>"
"2019-10-03 05:22:00,130 - eggroll.py[line:246] - DEBUG: created table: storage_type: LMDB, namespace: 201910030524353448356_hetero_lr_0, name: __federation__, partitions: 10, in_place_computing: False"
"2019-10-03 05:22:00,184 - federation.py[line:177] - DEBUG: [REMOTE] Sending 201910030524353448356_hetero_lr_0-HeteroLRTransferVariable.paillier_pubkey-HeteroLRTransferVariable.paillier_pubkey.201910030524353448356_hetero_lr_0.train-arbiter-90000-host-90000"
"2019-10-03 05:22:00,191 - federation.py[line:183] - DEBUG: [REMOTE] Sent HeteroLRTransferVariable.paillier_pubkey for job jobId: "201910030524353448356_hetero_lr_0"
"2019-10-03 05:22:00,191 - hetero_lr_arbiter.py[line:100] - INFO: remote public_key to host"
"2019-10-03 05:22:00,206 - eggroll.py[line:246] - DEBUG: created table: storage_type: LMDB, namespace: 201910030524353448356_hetero_lr_0, name: __federation__, partitions: 10, in_place_computing: False"
"2019-10-03 05:22:00,266 - federation.py[line:177] - DEBUG: [REMOTE] Sending 201910030524353448356_hetero_lr_0-HeteroLRTransferVariable.paillier_pubkey-HeteroLRTransferVariable.paillier_pubkey.201910030524353448356_hetero_lr_0.train-arbiter-90000-guest-10000"
"2019-10-03 05:22:00,268 - federation.py[line:183] - DEBUG: [REMOTE] Sent HeteroLRTransferVariable.paillier_pubkey for job jobId: "201910030524353448356_hetero_lr_0"
"2019-10-03 05:22:00,268 - hetero_lr_arbiter.py[line:107] - INFO: remote public_key to guest"

**Comment by zengjice** [comment]
Please check the deployment configuration, focusing on the Federation service.
