### ISSUE TITLE
Too many temporary data save to lmdb_temporary lead to disk full when training secureboost

### ISSUE THREAD

**Issue by pandeBJ** [FederatedAI/FATE#648]
when fit a certain depth of a tree during training secureboost model,  a lot of data will be used and stored to lmdb_temporary, such as data_bin_with_node_dispatch, data_bin_with_node_dispathc_join_grad_hess and so on. But when the fit end, the data won't be deleted. 
when fit next depth, the similar data also will be saved to lmdb_temporary...
After several iterations, more and more data will be stored in lmdb_temporary and the disk will be filled.

Is there any solution for this issue? thanks.

**Comment by matricer** [comment]
Suffer the same problem...
Too much temp data is cached which costs huge amount of disk space.
Is there anything we can do to clean up the cache?

**Comment by mgqa34** [comment]
In later version of FATE (FATE 1.1 or later)，eggroll will upgrade and temporary data generated each iteration will be automatically cleaned

**Comment by pandeBJ** [comment]
@mgqa34 The "iteration" used in my words above refers to fit every depth of a tree, not training every tree. Is the same meaning of yours?

**Comment by matricer** [comment]
@mgqa34 , Nice, this will significantly improve the practicability of FATE. 
BTW, as the @pandeBJ pointed out, does the "each iteration" refer to "each tree" or "each layer of the tree"?

**Comment by mgqa34** [comment]
@pandeBJ Yes, it will be every depth of the tree.

**Comment by pandeBJ** [comment]
@mgqa34 it's clear now. Thanks for your explanation and look forward to your changes.

**Comment by mgqa34** [comment]
FATE-1.1 support cleaning  temporary data  and this issue was closed
