### ISSUE TITLE
wrong comments on function aggregate_forward() in hetero_lr_guest.py

### ISSUE THREAD

**Issue by pandeBJ** [FederatedAI/FATE#679]
i doubt whether the comment on function aggregate_forward() in hetero_lr_guest.py is correct.
![image](https://user-images.githubusercontent.com/46129889/66902627-7c69aa80-eff0-11e9-838b-a6e2e075057c.png)

i think the context with red rectangle in above screenshot should be 
 [[ (wx_g + wx_h)^2 ]] = [[ wx_g^2 ]] + [[ wx_h^2 ]] + 2 * wx_g* [[ wx_h ]]

looking forward to your reply.

**Comment by tanmc123** [comment]
Here, we use "en_" prefix to represent Paillier encryption. Therefore, the above formula is actually the same as yours. However, it is a good suggestion to replace them by [[ ]] symbol. Thank you for pointing out this problem.
