### ISSUE TITLE
Unreasonable time consumption, in an epoch of the hetero LR.

### ISSUE THREAD

**Issue by EmilyMu** [FederatedAI/FATE#685]
My input data size is 350,000, there are 6 features on the guest side, 6 features on the host side, running hetero LR on this data, it takes about 1 minute to run an epoch, we think the time is too long, not reasonable.

From the log, we counted the time consumption of each step:
（1）Guest compute the compute_forward (computation time): 15s （Is the “join” in compute_forward function consumes too long time?）
（2）Guest get host_forward from host (Communication time)：8s 
（3）Guest compute fore_gradient (computation time): 6s
（4）Host get fore_gradient from guest (Communication time)：16s
（5）Guest compute guest_gradient and loss (computation time)：13s
（6）Arbiter get guest_gradient (Communication time)：< 1s
（7）Guest get optim_guest_gradient from arbiter（Communication time）：< 1s

is the time consumption reasonable ,on the current data size? 

the dsl file : 
[test_hetero_lr_train_job_dsl.txt](https://github.com/FederatedAI/FATE/files/3743074/test_hetero_lr_train_job_dsl.txt)
the conf file ：
[test_hetero_lr_train_job_conf.txt](https://github.com/FederatedAI/FATE/files/3743086/test_hetero_lr_train_job_conf.txt)

the guest log ：
![image](https://user-images.githubusercontent.com/5690422/67081135-30259280-f1c9-11e9-97e9-a021963e09f5.png)
the host log ：
![image](https://user-images.githubusercontent.com/5690422/67081181-403d7200-f1c9-11e9-8bc1-2ca88a33a43d.png)
the arbiter log ：
![image](https://user-images.githubusercontent.com/5690422/67081220-51867e80-f1c9-11e9-96e0-b3922f7b0825.png)

**Comment by matricer** [comment]
@tanmc123 It seems that fake encryption is applied which costs no time
      "encrypt_param": {
         "method": "Fake",
         "key_length": 1024
      },
Both computation and communication takes more time than expected. Does the join op in computation cost much? It takes 8 seconds for the guest to receive 350k*3*4=4.2MB info. from the host. Here, 3 is for tuple3 and 4 for bytes of float.
