### ISSUE TITLE
I don't quite understand the specific meaning of hetero and homo. Very eager to get directions, thanks.

### ISSUE THREAD

**Issue by Slun12** [FederatedAI/FATE#738]
I don't quite understand the specific meaning of **hetero** and **homo**. Very eager to get directions, thanks.

**Comment by tanmc123** [comment]
@Slun12 hetero and homo is two kinds of federated learning scenario. For hetero scenario, the parties involved have same sample ids but different features. That means the structure of data set of each party is different, or we call "heterogeneous", short for "hetero". 

As for homo, the parties involved have different samples but the feature structures are same. We call it "homogeneous" short for "homo". 

Hope that is useful for you. Thank you.

**Comment by Slun12** [comment]
Thank you very much, your reply is quite useful.@tanmc123
