### ISSUE TITLE
What the PartyA and PartyB means?

### ISSUE THREAD

**Issue by Daniells8910** [FederatedAI/FATE#752]
Hi,
    1、how should i understand the role of  "partya" and "partyb" in the project?
    2、i want to change the "deploy_dir" to my own path,is it ok?
         besides ,where other place i should change ? 
   thanks very much.

**Comment by paulbaogang** [comment]
1.Federal study requires at least two parties to participate in the study, the two parties are partya and partyb, the actual application can be two companies, two departments, etc.
2.Can use a custom directory.

**Comment by KAndHisC** [comment]
Instead, try installing KubeFATE, which is easier to install and customize! 

KubeteFATE provides tools to deploy FATE using Docker Compose and Kubernetes.
https://github.com/FederatedAI/KubeFATE
