### ISSUE TITLE
storage-service-cxx start failed

### ISSUE THREAD

**Issue by dockerzhang** [FederatedAI/FATE#753]
all modules are started except storage-service-cxx, error output:
storage-service-cxx/storage-service: error while loading shared libraries: libgrpc++.so.1: cannot open shared object file: No such file or directory

os: centos 7.2

there is different error:
Illegal instruction
after **export LD_LIBRARY_PATH=/data/projects/fate/eggroll/storage-service-cxx/third_party/lib/**

**Comment by ad51392627** [comment]
we have the same problem now
u have any soluations now?

**Comment by JJusti** [comment]
try reinstall storage-service-cxx module

```
cd FATE/cluster-deploy/scripts
bash deploy_cluster_multinode.sh binary storage-service-cxx
```

**Comment by xuexianju** [comment]
> try reinstall storage-service-cxx module
> 
> ```
> cd FATE/cluster-deploy/scripts
> bash deploy_cluster_multinode.sh binary storage-service-cxx
> ```
I met the exactly same error After reinstalling remains the issue.

After export the necessary enviroment path, I take the code snippet from the deploy shell code from 
/data/projects/fate/eggroll/service.sh 

cd /data/projects/fate/eggroll/storage-service-cxx
./storage-service-1.1  -p 7778 -d /data/projects/fate/eggroll/data-dir

the result is : Illegal instruction

PS : everthing needed is installed.

**Comment by paulbaogang** [comment]
Excute commands:

wget https://webank-ai-1251170195.cos.ap-guangzhou.myqcloud.com/third_party_source.tar.gz

tar -xzf third_party_source.tar.gz

cd third_party/rocksdb

PORTABLE=1 make shared_lib

cp librocksdb.so.6.1.2 /data/projects/fate/eggroll/storage-service-cxx/third_party/rocksdb/librocksdb.so.6.1.2

Then，restart  storage-service-cxx  service.
