### ISSUE TITLE
what n_g (or n_h*) means in image in  Homogeneous Neural Networks?

### ISSUE THREAD

**Issue by Joeyqcy** [FederatedAI/FATE#754]
The image in [doc](https://github.com/FederatedAI/FATE/tree/master/federatedml/nn/homo_nn) shows the process of Secure Aggregation. I don't understand the n_g (or n_h*) in each client's model update round. How should I understand this value?

**Comment by weiwee** [comment]
They're weights used in model aggregation, and are commonly equal to the num of samples that has comsumed in local model fitting this round.
Notice that h refer to host and g refer to guest.

**Comment by Joeyqcy** [comment]
Thank you for your answer , i have got it. @weiwee
