### ISSUE TITLE
fate_flow start failed

### ISSUE THREAD

**Issue by Daniells8910** [FederatedAI/FATE#755]
I start fate_flow service failed on cluster mode 
"fate_flow_stat.log" shows only "init mysql database on cluster mode successfully".
how should i do ？

ps : I connect fate to my own mysql installed earlier,but i found no table created after starting  fate_flow.

**Comment by zhihuiwan** [comment]
Check the logs/error.log for error messages and check if the DATABASE configuration is correct under fate_flow/settings.py

**Comment by Daniells8910** [comment]
the error message is
peewee.OperationalError:(1045,"Access denied for user 'root'@xxx(using password:YES)")

and the DATABASE configuration is correct under settings.py
