### ISSUE TITLE
Secureboost example Task failed 

### ISSUE THREAD

**Issue by vivianwky** [FederatedAI/FATE#759]
Hello:
 I was trying to run the secureboost example in examples/federatedml-1.0-examples/hetero_secureboost and the task failed. However I have already successfully run the lr example in examples/federatedml-1.0-examples/hetero_logistic_regression.

I followed the README files and used the quick_run.py. 
I have compared the test_hetero_lr_train_job_dsl.json and the test_secureboost_train_dsl.json. However, these files are so different and I cannot locate the problem. I wonder whether you can help.

quick_run.py : please see attachments
[quick_run.txt](https://github.com/FederatedAI/FATE/files/3818826/quick_run.txt)

quick_run.py prints:

Upload data config json: {'file': 'examples/data/breast_b.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'breast_b', 'namespace': 'breast_b_guest'}
stdout:{
    "data": {
        "board_url": "http://172.18.0.2:8080/index.html#/dashboard?job_id=201911070927083549974&role=local&party_id=0",
        "job_dsl_path": "/fate/jobs/201911070927083549974/job_dsl.json",
        "job_runtime_conf_path": "/fate/jobs/201911070927083549974/job_runtime_conf.json",
        "logs_directory": "/fate/logs/201911070927083549974",
        "namespace": "breast_b_guest",
        "table_name": "breast_b"
    },
    "jobId": "201911070927083549974",
    "retcode": 0,
    "retmsg": "success"
}

Upload data config json: {'file': 'examples/data/breast_a.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'breast_a', 'namespace': 'breast_a_host'}
stdout:{
    "data": {
        "board_url": "http://172.18.0.2:8080/index.html#/dashboard?job_id=201911070927115508105&role=local&party_id=0",
        "job_dsl_path": "/fate/jobs/201911070927115508105/job_dsl.json",
        "job_runtime_conf_path": "/fate/jobs/201911070927115508105/job_runtime_conf.json",
        "logs_directory": "/fate/logs/201911070927115508105",
        "namespace": "breast_a_host",
        "table_name": "breast_a"
    },
    "jobId": "201911070927115508105",
    "retcode": 0,
    "retmsg": "success"
}

dsl_path: /fate/examples/federatedml-1.x-examples/user_config/train_dsl.config_1573118834_3952, conf_path: /fate/examples/federatedml-1.x-examples/user_config/train_conf.config_1573118834_7281
stdout:{
    "data": {
        "board_url": "http://172.18.0.2:8080/index.html#/dashboard?job_id=201911070927147496896&role=guest&party_id=10000",
        "job_dsl_path": "/fate/jobs/201911070927147496896/job_dsl.json",
        "job_runtime_conf_path": "/fate/jobs/201911070927147496896/job_runtime_conf.json",
        "logs_directory": "/fate/logs/201911070927147496896",
        "model_info": {
            "model_id": "arbiter-10000#guest-10000#host-10000#model",
            "model_version": "201911070927147496896"
        }
    },
    "jobId": "201911070927147496896",
    "retcode": 0,
    "retmsg": "success"
}

Please check your task in fate-board, url is : http://172.18.0.2:8080/index.html#/dashboard?job_id=201911070927147496896&role=guest&party_id=10000
The log info is located in /fate/examples/federatedml-1.x-examples/../../logs/201911070927147496896
Task is running, wait time: 10.178555965423584
Task is running, wait time: 20.705707788467407
Task Failed

the logs are 
root@63106b5aa462:/fate/logs/201911070927147496896/host/10000/dataio_1# cat fate_flow_schedule.log 
"2019-11-07 09:27:28,410 - task_executor.py[line:115] - INFO: run 201911070927147496896 dataio_1 201911070927147496896_dataio_1 host 10000 task"
"2019-11-07 09:27:28,410 - task_executor.py[line:116] - INFO: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': False, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '201911070927147496896'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/user_config/train_conf.config_1573118834_7281', 'dsl': '/fate/examples/federatedml-1.x-examples/user_config/train_dsl.config_1573118834_3952', 'function': 'submit_job', 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}"
"2019-11-07 09:27:28,410 - task_executor.py[line:117] - INFO: {'data': {'data': ['args.eval_data']}, 'model': ['dataio_0.dataio']}"
"2019-11-07 09:27:28,415 - task_executor.py[line:127] - ERROR: Count of data_instance is 0"
Traceback (most recent call last):
  File "/fate/fate_flow/driver/task_executor.py", line 118, in run_task
    run_object.run(parameters, task_run_args)
  File "/fate/federatedml/model_base.py", line 157, in run
    self._run_data(args["data"], stage)
  File "/fate/federatedml/model_base.py", line 134, in _run_data
    self.data_output = self.transform(data)
  File "/fate/federatedml/util/data_io.py", line 738, in transform
    return self.reader.read_data(data_inst, "transform")
  File "/fate/federatedml/util/data_io.py", line 115, in read_data
    abnormal_detection.empty_table_detection(input_data)
  File "/fate/federatedml/util/abnormal_detection.py", line 25, in empty_table_detection
    raise ValueError("Count of data_instance is 0")
ValueError: Count of data_instance is 0
"2019-11-07 09:27:28,467 - task_executor.py[line:146] - INFO: finish 201911070927147496896 dataio_1 201911070927147496896_dataio_1 host 10000 failed task"

**Comment by mgqa34** [comment]
If you run the examples of secureboost directly，you should upload the data firstly.  The (table_name, namespace) of each example may be different, the error above means that the data doesn't upload successfully.

**Comment by youzp** [comment]
@mgqa34 目前v1.3.0版本的很多example还是存在这个问题，例如hetero_secureboost和hetero_pearson，但是hetero_logistic_regression这个例子又可以执行成功，这就非常奇怪。在quick_run.py这个执行代码中是存在upload_data()上传数据这个步骤的，但上传数据还是会失败。能帮忙解释一下吗？
