### ISSUE TITLE
Can not find eggroll.api.standalone package in master

### ISSUE THREAD

**Issue by qiuyujiang** [FederatedAI/FATE#763]
I can not find eggroll.api.standalone package in master. I saw this package was used in /arch/api/table/eggroll.py, at line 38. code like below:
from eggroll.api.standalone.eggroll import Standalone
But I can't find this file. Is this package open-source?

**Comment by qiuyujiang** [comment]
The issue file a said above is [https://github.com/FederatedAI/FATE/blob/master/arch/api/table/eggroll_util.py](url)

**Comment by qiuyujiang** [comment]
The issue file a said above is [here](https://github.com/FederatedAI/FATE/blob/master/arch/api/table/eggroll_util.py)

**Comment by dylan-fan** [comment]
you can see .gitmodules file.  
https://github.com/WeBankFinTech/eggroll.git

**Comment by dylan-fan** [comment]
Also, you can use: 
git clone --recursive git@github.com:FederatedAI/FATE.git

**Comment by qiuyujiang** [comment]
> you can see .gitmodules file.
> https://github.com/WeBankFinTech/eggroll.git

Thank you
