### ISSUE TITLE
homo_nn running failed

### ISSUE THREAD

**Issue by codergan** [FederatedAI/FATE#777]
**Describe the bug**
The dataIO is got, but the homo_nn failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/44254161/68741272-25271c00-0628-11ea-93b4-5c21c01d0542.png)

Log:
"2019-11-13 06:57:10,201 - api_utils.py[line:80] - INFO: local api request: http://172.19.0.2:9380/v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status"
2
"2019-11-13 06:57:10,201 - api_utils.py[line:80] - INFO: local api request: http://172.19.0.2:9380/v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status"
3
"2019-11-13 06:57:10,302 - api_utils.py[line:83] - INFO: {"retcode":0,"retmsg":"success"}
4
"
5
"2019-11-13 06:57:10,302 - api_utils.py[line:83] - INFO: {"retcode":0,"retmsg":"success"}
6
"
7
"2019-11-13 06:57:10,302 - api_utils.py[line:85] - INFO: local api response: /v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status {'retcode': 0, 'retmsg': 'success'}"
8
"2019-11-13 06:57:10,302 - api_utils.py[line:85] - INFO: local api response: /v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status {'retcode': 0, 'retmsg': 'success'}"
9
"2019-11-13 06:57:10,303 - task_executor.py[line:115] - INFO: run 201911130656552137699 homo_nn_0 201911130656552137699_homo_nn_0 guest 10000 task"
10
"2019-11-13 06:57:10,303 - task_executor.py[line:115] - INFO: run 201911130656552137699 homo_nn_0 201911130656552137699_homo_nn_0 guest 10000 task"
11
"2019-11-13 06:57:10,304 - task_executor.py[line:116] - INFO: {'HomoNNParam': {'secure_aggregate': True, 'aggregate_every_n_epoch': 1, 'config_type': 'nn', 'nn_define': [{'layer': 'Dense', 'units': 3, 'use_bias': False, 'activation': 'relu'}, {'layer': 'Dense', 'units': 2, 'activation': 'selu'}, {'layer': 'Dense', 'units': 1, 'activation': 'sigmoid'}], 'batch_size': -1, 'max_iter': 10, 'early_stop': {'early_stop': 'diff', 'eps': 0.0001}, 'metrics': ['accuracy', 'AUC', 'Hinge'], 'optimizer': {'optimizer': 'Adadelta', 'learning_rate': 0.05, 'rho': 0.95}, 'loss': 'binary_crossentropy', 'predict_param': {'threshold': 0.5}, 'cv_param': {'n_splits': 5, 'mode': 'hetero', 'role': 'guest', 'shuffle': True, 'random_seed': 1, 'need_cv': False}}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '201911130656552137699'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/homo_nn/test_homo_dnn_multi_layer.json', 'dsl': 'examples/federatedml-1.x-examples/homo_nn/test_homo_nn_train_then_predict.dsl', 'function': 'submit_job', 'local': {'role': 'guest', 'party_id': 10000}, 'CodePath': 'federatedml/nn/homo_nn/enter_point.py/HomoNNGuest', 'module': 'HomoNN'}"
12
"2019-11-13 06:57:10,304 - task_executor.py[line:116] - INFO: {'HomoNNParam': {'secure_aggregate': True, 'aggregate_every_n_epoch': 1, 'config_type': 'nn', 'nn_define': [{'layer': 'Dense', 'units': 3, 'use_bias': False, 'activation': 'relu'}, {'layer': 'Dense', 'units': 2, 'activation': 'selu'}, {'layer': 'Dense', 'units': 1, 'activation': 'sigmoid'}], 'batch_size': -1, 'max_iter': 10, 'early_stop': {'early_stop': 'diff', 'eps': 0.0001}, 'metrics': ['accuracy', 'AUC', 'Hinge'], 'optimizer': {'optimizer': 'Adadelta', 'learning_rate': 0.05, 'rho': 0.95}, 'loss': 'binary_crossentropy', 'predict_param': {'threshold': 0.5}, 'cv_param': {'n_splits': 5, 'mode': 'hetero', 'role': 'guest', 'shuffle': True, 'random_seed': 1, 'need_cv': False}}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '201911130656552137699'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/homo_nn/test_homo_dnn_multi_layer.json', 'dsl': 'examples/federatedml-1.x-examples/homo_nn/test_homo_nn_train_then_predict.dsl', 'function': 'submit_job', 'local': {'role': 'guest', 'party_id': 10000}, 'CodePath': 'federatedml/nn/homo_nn/enter_point.py/HomoNNGuest', 'module': 'HomoNN'}"
13
"2019-11-13 06:57:10,306 - task_executor.py[line:117] - INFO: {'data': {'train_data': ['dataio_0.train']}}"
14
"2019-11-13 06:57:10,306 - task_executor.py[line:117] - INFO: {'data': {'train_data': ['dataio_0.train']}}"
15
"2019-11-13 06:57:10,307 - random_padding_cipher.py[line:59] - INFO: synchronizing uuid"
16
"2019-11-13 06:57:10,307 - random_padding_cipher.py[line:59] - INFO: synchronizing uuid"
17
"2019-11-13 06:57:11,249 - random_padding_cipher.py[line:61] - INFO: local uuid=d043f7e8-05e2-11ea-a958-0242ac130002"
18
"2019-11-13 06:57:11,249 - random_padding_cipher.py[line:61] - INFO: local uuid=d043f7e8-05e2-11ea-a958-0242ac130002"
19
"2019-11-13 06:57:11,251 - random_padding_cipher.py[line:63] - INFO: Diffie-Hellman keys exchanging"
20
"2019-11-13 06:57:11,251 - random_padding_cipher.py[line:63] - INFO: Diffie-Hellman keys exchanging"
21
"2019-11-13 06:57:11,518 - random_padding_cipher.py[line:65] - INFO: Diffie-Hellman exchanged keys {UUID('d0767452-05e2-11ea-81ea-0242ac130002'): mpz(43050761789211103074012414491935670190873937671344350864488469987501248411593968086665275227175744745675186101408107064462459944809639534889860496004791823226501632472603050470479029436011999398580844231368665449208919456101657714250502356902046714048087896213426489321167869548761094399216119470948586090681)}"
22
"2019-11-13 06:57:11,518 - random_padding_cipher.py[line:65] - INFO: Diffie-Hellman exchanged keys {UUID('d0767452-05e2-11ea-81ea-0242ac130002'): mpz(43050761789211103074012414491935670190873937671344350864488469987501248411593968086665275227175744745675186101408107064462459944809639534889860496004791823226501632472603050470479029436011999398580844231368665449208919456101657714250502356902046714048087896213426489321167869548761094399216119470948586090681)}"
23
"2019-11-13 06:57:19,620 - deprecation.py[line:506] - WARNING: From /usr/local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
24
Instructions for updating:
25
Call initializer instance with the dtype argument instead of passing it to the constructor"
26
"2019-11-13 06:57:19,838 - deprecation.py[line:323] - WARNING: From /usr/local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4075: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
27
Instructions for updating:
28
Use tf.where in 2.0, which has the same broadcast rule as np.where"
29
"2019-11-13 06:57:19,973 - deprecation_wrapper.py[line:119] - WARNING: From /fate/federatedml/nn/homo_nn/backend/tf_keras/nn_model.py:59: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
30
"
31
"2019-11-13 06:57:20,012 - deprecation_wrapper.py[line:119] - WARNING: From /fate/federatedml/nn/homo_nn/backend/tf_keras/nn_model.py:60: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.
32
"
33
"2019-11-13 06:57:20,834 - enter_point.py[line:161] - INFO: start 0_th aggregation"
34
"2019-11-13 06:57:21,485 - task_executor.py[line:127] - ERROR: A target array with shape (846, 4) was passed for an output of shape (None, 1) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output."
35
Traceback (most recent call last):
36
File "/fate/fate_flow/driver/task_executor.py", line 118, in run_task
37
run_object.run(parameters, task_run_args)
38
File "/fate/federatedml/model_base.py", line 157, in run
39
self._run_data(args["data"], stage)
40
File "/fate/federatedml/model_base.py", line 98, in _run_data
41
self.fit(train_data, eval_data)
42
File "/fate/federatedml/nn/homo_nn/enter_point.py", line 164, in fit
43
self.nn_model.train(data, aggregate_every_n_epoch=self.aggregate_every_n_epoch)
44
File "/fate/federatedml/nn/homo_nn/backend/tf_keras/nn_model.py", line 118, in train
45
self._model.fit(x=data, epochs=epochs, verbose=1, shuffle=True, **left_kwargs)
46
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 673, in fit
47
initial_epoch=initial_epoch)
48
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
49
steps_name='steps_per_epoch')
50
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
51
batch_outs = batch_function(*batch_data)
52
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1153, in train_on_batch
53
extract_tensors_from_dataset=True)
54
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2692, in _standardize_user_data
55
y, self._feed_loss_fns, feed_output_shapes)
56
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 549, in check_loss_and_target_compatibility
57
' while using as loss `' + loss_name + '`. '
58
ValueError: A target array with shape (846, 4) was passed for an output of shape (None, 1) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output.
59
"2019-11-13 06:57:21,485 - task_executor.py[line:127] - ERROR: A target array with shape (846, 4) was passed for an output of shape (None, 1) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output."
60
Traceback (most recent call last):
61
File "/fate/fate_flow/driver/task_executor.py", line 118, in run_task
62
run_object.run(parameters, task_run_args)
63
File "/fate/federatedml/model_base.py", line 157, in run
64
self._run_data(args["data"], stage)
65
File "/fate/federatedml/model_base.py", line 98, in _run_data
66
self.fit(train_data, eval_data)
67
File "/fate/federatedml/nn/homo_nn/enter_point.py", line 164, in fit
68
self.nn_model.train(data, aggregate_every_n_epoch=self.aggregate_every_n_epoch)
69
File "/fate/federatedml/nn/homo_nn/backend/tf_keras/nn_model.py", line 118, in train
70
self._model.fit(x=data, epochs=epochs, verbose=1, shuffle=True, **left_kwargs)
71
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 673, in fit
72
initial_epoch=initial_epoch)
73
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
74
steps_name='steps_per_epoch')
75
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
76
batch_outs = batch_function(*batch_data)
77
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1153, in train_on_batch
78
extract_tensors_from_dataset=True)
79
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2692, in _standardize_user_data
80
y, self._feed_loss_fns, feed_output_shapes)
81
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 549, in check_loss_and_target_compatibility
82
' while using as loss `' + loss_name + '`. '
83
ValueError: A target array with shape (846, 4) was passed for an output of shape (None, 1) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output.
84
"2019-11-13 06:57:21,491 - api_utils.py[line:80] - INFO: local api request: http://172.19.0.2:9380/v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status"
85
"2019-11-13 06:57:21,491 - api_utils.py[line:80] - INFO: local api request: http://172.19.0.2:9380/v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status"
86
"2019-11-13 06:57:21,615 - api_utils.py[line:83] - INFO: {"retcode":0,"retmsg":"success"}
87
"
88
"2019-11-13 06:57:21,615 - api_utils.py[line:83] - INFO: {"retcode":0,"retmsg":"success"}
89
"
90
"2019-11-13 06:57:21,616 - api_utils.py[line:85] - INFO: local api response: /v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status {'retcode': 0, 'retmsg': 'success'}"
91
"2019-11-13 06:57:21,616 - api_utils.py[line:85] - INFO: local api response: /v1/schedule/201911130656552137699/homo_nn_0/201911130656552137699_homo_nn_0/guest/10000/status {'retcode': 0, 'retmsg': 'success'}"
92
"2019-11-13 06:57:21,617 - task_executor.py[line:146] - INFO: finish 201911130656552137699 homo_nn_0 201911130656552137699_homo_nn_0 guest 10000 failed task"
93
"2019-11-13 06:57:21,617 - task_executor.py[line:146] - INFO: finish 201911130656552137699 homo_nn_0 201911130656552137699_homo_nn_0 guest 10000 failed task"

**Comment by codergan** [comment]
Btw, a typo under /fate/federatedml/nn/homo_nn/backend/tf_keras/layers, it should be basic.py if I am not wrong

**Comment by weiwee** [comment]
as log `ValueError: A target array with shape (846, 4) was passed for an output of shape (None, 1) while using as loss binary_crossentropy. This loss expects targets to have the same shape as the output.` suggests,  binary_crossentropy accept output shape (None, 1), while you the data you provided has shape (846, 4). In other words, binary_crossentropy loss used for binary classification only, try ` categorical_crossentropy' for multi-class datas.

**Comment by weiwee** [comment]
> Btw, a typo under /fate/federatedml/nn/homo_nn/backend/tf_keras/layers, it should be basic.py if I am not wrong

to be fixed in next version, thanks for comment.

**Comment by codergan** [comment]
Thank you for the rapid response, but I still failed. I changed the dataset into breast and try categorical_crossentropy, but the error is below:
self._run_data(args["data"], stage)
22
File "/fate/federatedml/model_base.py", line 98, in _run_data
23
self.fit(train_data, eval_data)
24
File "/fate/federatedml/nn/homo_nn/enter_point.py", line 155, in fit
25
data = self.data_converter.convert(data_inst, batch_size=self.batch_size)
26
File "/fate/federatedml/nn/homo_nn/backend/tf_keras/nn_model.py", line 236, in convert
27
return KerasSequenceData(data, *args, **kwargs)
28
File "/fate/federatedml/nn/homo_nn/backend/tf_keras/nn_model.py", line 201, in __init__
29
self.x[index] = inst.features
30
ValueError: could not broadcast input array from shape (18) into shape (30)

**Comment by codergan** [comment]
The old dataset error:
File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 549, in check_loss_and_target_compatibility
49
' while using as loss `' + loss_name + '`. '
50
ValueError: A target array with shape (413, 4) was passed for an output of shape (None, 1) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.
