### ISSUE TITLE
Cluster-version: The Program runs too slowly when I use hetero_logistic_regression

### ISSUE THREAD

**Issue by lichaoliang1** [FederatedAI/FATE#778]
data：breast_a.csv  and breast_b.csv  ,Their size is about 570
algorithm ：hetero_logistic_regression
other part：default
running time ( just train )：**about 5 min**
**Is it normal?**

**Comment by tanmc123** [comment]
@lichaoliang1 

Could you please show us your machine configuration and parameters setting for lr. And is it running on a standalone version or cluster version?

We have test this data set in our 16 cores machine working with 10 partitions in standalone version, and it takes about 1.4s per iteration. As for cluster version, it takes about 8.3s per iteration. 

See if this is helpful or not.

**Comment by lichaoliang1** [comment]
I have test this data set in my 1 core machine in cluster version, and  I use the default parameters in hetero_logistic_regression , it takes about 16 s per iteration. Is it normal?

**Comment by tanmc123** [comment]
@lichaoliang1 Yes, it is normal
