### ISSUE TITLE
min_test_task failed on cluster version

### ISSUE THREAD

**Issue by vivianwky** [FederatedAI/FATE#787]
Hello:
I have built the cluster version fate and already passed the Stand-alone Test and oy_example Deployment Verification Test. However, the Minimization testing failed. 
I got the values of "host_table" and "host_namespace" from test results, and passed them with the correct command.  I haved tried different ways to solve this problem but it still exists.

I really wonder if anyone can help!!!!!

The printed messages are as follows:
(venv) sh-4.2$ sh run.sh guest fast host_table_name_1574402535_1069 host_table_namespace_1574402535_1069
role is guest
task is fast
Start Upload Data
Upload data config json: {'file': '/data/projects/fate/python/examples/min_test_task/../data/breast_b.csv', 'head': 1, 'partition': 10, 'work_mode': 1, 'table_name': 'guest_table_name_1574406070_6325', 'namespace': 'guest_table_namespace_1574406070_6325'}
stdout:{
    "data": {
        "board_url": "http://192.168.0.2:8080/index.html#/dashboard?job_id=201911221501107342736&role=local&party_id=0",
        "job_dsl_path": "/data/projects/fate/python/jobs/201911221501107342736/job_dsl.json",
        "job_runtime_conf_path": "/data/projects/fate/python/jobs/201911221501107342736/job_runtime_conf.json",
        "logs_directory": "/data/projects/fate/python/logs/201911221501107342736",
        "namespace": "guest_table_namespace_1574406070_6325",
        "table_name": "guest_table_name_1574406070_6325"
    },
    "jobId": "201911221501107342736",
    "retcode": 0,
    "retmsg": "success"
}

Upload output is {'data': {'board_url': 'http://192.168.0.2:8080/index.html#/dashboard?job_id=201911221501107342736&role=local&party_id=0', 'job_dsl_path': '/data/projects/fate/python/jobs/201911221501107342736/job_dsl.json', 'job_runtime_conf_path': '/data/projects/fate/python/jobs/201911221501107342736/job_runtime_conf.json', 'logs_directory': '/data/projects/fate/python/logs/201911221501107342736', 'namespace': 'guest_table_namespace_1574406070_6325', 'table_name': 'guest_table_name_1574406070_6325'}, 'jobId': '201911221501107342736', 'retcode': 0, 'retmsg': 'success'}
table_name:guest_table_name_1574406070_6325
namespace:guest_table_namespace_1574406070_6325
Data uploaded, expected table count: 569
process 125181 thread 140343626307392 run __init__ init table name:__gc_e1307ae4-0cf5-11ea-9a03-000c29cc7fc9, namespace:e1307ae4-0cf5-11ea-9a03-000c29cc7fc9
created table: storage_type: LMDB, namespace: e1307ae4-0cf5-11ea-9a03-000c29cc7fc9, name: __gc_e1307ae4-0cf5-11ea-9a03-000c29cc7fc9, partitions: 1, in_place_computing: False
process 125181 thread 140343626307392 run __init__ init table name:guest_table_name_1574406070_6325, namespace:guest_table_namespace_1574406070_6325
created table: storage_type: LMDB, namespace: guest_table_namespace_1574406070_6325, name: guest_table_name_1574406070_6325, partitions: 10, in_place_computing: False
table count:569
Test upload task success, upload count match DTable count
[Intersect] Start intersect task
stdout:{
    "data": {
        "board_url": "http://192.168.0.2:8080/index.html#/dashboard?job_id=201911221501177901047&role=guest&party_id=9999",
        "job_dsl_path": "/data/projects/fate/python/jobs/201911221501177901047/job_dsl.json",
        "job_runtime_conf_path": "/data/projects/fate/python/jobs/201911221501177901047/job_runtime_conf.json",
        "logs_directory": "/data/projects/fate/python/logs/201911221501177901047",
        "model_info": {
            "model_id": "guest-9999#host-10000#model",
            "model_version": "201911221501177901047"
        }
    },
    "jobId": "201911221501177901047",
    "retcode": 0,
    "retmsg": "success"
}

[Intersect] Start intersect job status checker, status counter: 0, jobid:201911221501177901047
[Intersect] cur job status:running, wait_time: 13.63308835029602
[Intersect] Start intersect job status checker, status counter: 1, jobid:201911221501177901047
[Intersect] cur job status:running, wait_time: 23.917373180389404
[Intersect] Start intersect job status checker, status counter: 2, jobid:201911221501177901047
.............
[Intersect] reach max intersect time:{}, intersect task may be failed, and exit now
Traceback (most recent call last):
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 500, in <module>
    raise ValueError("intersect task is failed")
ValueError: intersect task is failed
*********************
*******finish!*******
I downloaded the error.log and debug.log and you can see them in the attachments.
[debug_log.txt](https://github.com/FederatedAI/FATE/files/3878708/debug_log.txt)
[error.log](https://github.com/FederatedAI/FATE/files/3878712/error.log)

**Comment by 4Details** [comment]
please check your fate_flow server and the port (9360/9380), may be the server shut down.

**Comment by vivianwky** [comment]
> please check your fate_flow server and the port (9360/9380), may be the server shut down.

I am sure that the fate_flow  server and the port were on when I first posted this issue. 
However when I rebooted my computer , I cannot start the fate_flow sever, It always show that fail to start the service .
There is no error.log and the fate_flow_stat.log just showed "init mysql database on cluster mode successfully" . 
I wonder whether there is something I should do before I simply open the computer and use the command "sh services.sh all start"  to start all the service ???
