### ISSUE TITLE
ERROR.log was not found on the guest side

### ISSUE THREAD

**Issue by jiahaoc1993** [FederatedAI/FATE#788]
**Describe the bug**
On FATE v1.1, while running the toy example on the guest side, The fate flow server would report the `ERROR.log` was not found some time.

**Expected behavior**
Unknown, maybe it should not print this message.

**Screenshots**
The details of the error.
```
job status is running
Traceback (most recent call last):
  File "run_toy_example.py", line 196, in <module>
    exec_toy_example(runtime_config)
  File "run_toy_example.py", line 171, in exec_toy_example
    show_log(jobid, "error")
  File "run_toy_example.py", line 149, in show_log
    with open(error_log, "r") as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/data/projects/fate/python/examples/toy_example/19112203250928712616_log/guest/10000/secure_add_example_0/ERROR.log'
```

**Comment by zhihuiwan** [comment]
Thanks for your feedback: our tips will be more friendly in the future.
You can go to the corresponding job under fate_flow_schedule.log to see if there is an error log.

**Comment by jiahaoc1993** [comment]
Thank you for your reply, close now.
