### ISSUE TITLE
fail to run toy_example  test in Allinone mode

### ISSUE THREAD

**Issue by yongrl** [FederatedAI/FATE#794]
I rewrite the allinone_cluster_configurations.sh file as below:

#!/bin/bash
user=app
deploy_dir=/data/projects/fate
party_list=(10000 9999)
node_list=(192.168.0.1)
db_auth=(fate_dev fate_dev)
redis_password=fate_dev
cxx_compile_flag=false

then build the project , all services started and succeed to  run  run_test.sh, but when I tested toy_example by command: 
python run_toy_example.py 9999 10000 1
I got en error!

console output like this:
![image](https://user-images.githubusercontent.com/13956966/69608631-d2efed00-1062-11ea-8320-af0b7ca57658.png)
![image](https://user-images.githubusercontent.com/13956966/69608661-e1d69f80-1062-11ea-93a1-63c67b04da51.png)

and the proxy logs is :
![image](https://user-images.githubusercontent.com/13956966/69608752-0af73000-1063-11ea-917c-5e0809dff119.png)

It seems 10000 party failed to start, how should I solve this problem ?

**Comment by paulbaogang** [comment]
It is currently not possible to deploy two parties on one machine. It is recommended to prepare two hosts, one for each host.
