### ISSUE TITLE
What's the difference between eggroll and spark

### ISSUE THREAD

**Issue by WenqianZhao** [FederatedAI/FATE#795]
Hi, I'm a developer new to FATE and EGGROLL. I saw that FATE supported EGGROLL and SPARK as two options of backend engine. Since I have used SPARK before, I know that SPARK is a distributed computation system which offers variaties of easily used APIs for basic computation, SQL and ML. So what is EGGROLL designed for? What's the difference, or we could say the advantage of EGGROLL over SPARK? Could I just use SPARK to do all kinds of operations in FATE, including computation and storage?

**Comment by weiwee** [comment]
The feature using spark as backend engine is newly introduced in version 1.1, and much work remains to be done to make it more stable and efficient.

> What's the difference, or we could say the advantage of EGGROLL over SPARK? 
Spark's apis are build on the top of eggroll, which has unneglectable  overhead. So, use EGGROLL may be much more efficient over SPARK in current version. 

>Could I just use SPARK to do all kinds of operations in FATE, including computation and storage?
Not today.  FATE has heavily dependent on EGGROLL, one can only use eggroll as storage and federation in current version.

**Comment by WenqianZhao** [comment]
> Spark's apis are build on the top of eggroll, which has unneglectable overhead.
Could you please explain more about the "unneglectable overhead"? It seems that SPARK and EGGROLL are two independent routes, as both of the RDDTable and DTable are inherited from class Table. 
> FATE has heavily dependent on EGGROLL, one can only use eggroll as storage and federation in current version.
Do you guys have any plan to decouple EGGROLL's code from such heavy dependency, or also support SPARK as one option of both storage and federation?

**Comment by weiwee** [comment]
> > Spark's apis are build on the top of eggroll, which has unneglectable overhead.
> 
> Could you please explain more about the "unneglectable overhead"? It seems that SPARK and EGGROLL are two independent routes, as both of the RDDTable and DTable are inherited from class Table.
> 
> > FATE has heavily dependent on EGGROLL, one can only use eggroll as storage and federation in current version.
> 
> Do you guys have any plan to decouple EGGROLL's code from such heavy dependency, or also support SPARK as one option of both storage and federation?

1. the federation reason 
2. yes, and is in progress
