### ISSUE TITLE
启动服务异常

### ISSUE THREAD

**Issue by albus01** [FederatedAI/FATE#797]
背景：
操作系统：macos
docker：环境检测ok。
按照“使用Docker镜像安装FATE（推荐）” 进行安装。
执行部署：bash install_standalone_docker.sh
![image](https://user-images.githubusercontent.com/12758136/69597493-1fc2cc00-1041-11ea-96cd-04a13b97a065.png)

nohup日志报错：
[SQLITE_ERROR] SQL error or missing database (no such table: t_job)

SQL: select                   'true' as QUERYID,               f_job_id, f_role, f_party_id, f_name, f_tag, f_initiator_party_id, f_status, f_cu
rrent_steps,      f_current_tasks, f_progress, f_create_time, f_update_time, f_start_time, f_end_time,      f_elapsed, f_run_ip             ,               f_description, f_roles
, f_dsl, f_runtime_conf             from t_job                                  WHERE (  f_end_time between ? and ? )
Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: t_job); uncategorized SQLException for SQL []; SQL state [null]; error code [1]; [SQLITE_ERROR] SQL error or missing database (no such table: t_job); nested exception is org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: t_job)

**Comment by KathyKing** [comment]
No database ignored in docker design

**Comment by albus01** [comment]
Sorry, I do not understand your answer. I just follow your doc to install it with docker. But it do not work. How can I fix this? @KathyKing

**Comment by KathyKing** [comment]
t_job This table will be created automatically. Please check if there is any problem with your docker
