### ISSUE TITLE
Question about FATE Deployment Guide, What's the difference

### ISSUE THREAD

**Issue by HelloLadsAndGents** [FederatedAI/FATE#800]
Hello,could you please tell me the differences between the Four deployment methods :
1.Install Cluster
2.Build Cluster from Source
3.Install AllinOne
4.Build AllinOne from Source
especially the difference between 1 and 2 AND 1 and 3

Thank you

**Comment by KathyKing** [comment]
Install is an installation version, no compilation is required            
Build needs to be compiled            
You can use the AllInOne mode            
AllInOne mode is that all components are installed on one machine or virtual machine

**Comment by HelloLadsAndGents** [comment]
thank you for answering my questions
