### ISSUE TITLE
SBT CV模型运行中一方early stop成功 另一方继续执行 导致任务卡死

### ISSUE THREAD

**Issue by sookieqin** [FederatedAI/FATE#805]
**Describe the bug**
背景：该bug理论上仅会出现在cv模式第2折及之后的训练/预测过程中。进行CV SBT建模时可能会出现任务卡死但是不报错，直到48小时超时的问题。

**To Reproduce**
假设： GUEST方在fold=2， round=8时达到early stop的条件，主动发起early stop
正常情况：HOST方根据生成规则生成本轮训练中获取stop_flag的key来获取获取到这个stop_flag 然后也中断后续执行过程。

问题复现：然而由于双方环境独立且不一致以及网络延迟，host方运行到get_stop_flag这一步骤时，guest发出的这个消息可能还到达，但是由于stop_flag的key的生成规则不包含折数这一变量，所以每一折中每轮训练的stop_flag的key完全一样，同时每折训练完成后中间变量应该没有被删除，这样一来host获取到的其实是前一折中guest发送的stop_flag, 导致两边状态不同步，出现任务卡死的问题。

**Comment by mgqa34** [comment]
If use cv，cv module will reset flowid every fold (like train.0\train.1)，so the tag will be new for every fold as its prefix is flowid. If you have more questions, please post below, thanks very much.

**Comment by sookieqin** [comment]
> If use cv，cv module will reset flowid every fold (like train.0\train.1)，so the tag will be new for every fold as its prefix is flowid. If you have more questions, please post below, thanks very much.

Thank you for the reply. But I reviewed the relevant code and found that flowid wasn't used to generate tag, so every flow stayed the same.
![image](https://user-images.githubusercontent.com/52624066/69790099-cdc6a580-11fc-11ea-9006-6fc457bc125f.png)

There is a cv log as below, and we can see that the tag of stop_flag  remains same in each round of  
 every flow.
![image](https://user-images.githubusercontent.com/52624066/69790009-98ba5300-11fc-11ea-988b-fc330e44fd6b.png)
![image](https://user-images.githubusercontent.com/52624066/69790040-a7a10580-11fc-11ea-9046-a5fdbab5a898.png)
If I make mistakes in understanding and expressing， please point it out. Thanks again.

**Comment by mgqa34** [comment]
transfer_variable.remote api source code :
https://github.com/FederatedAI/FATE/blob/master/federatedml/transfer_variable/transfer_class/base_transfer_variable.py#L31

>>> tag=self._transfer_variable.generate_transferid(self, *suffix)

https://github.com/FederatedAI/FATE/blob/master/federatedml/transfer_variable/transfer_class/base_transfer_variable.py#L87
>>> transferid = transfer_var.name + "." + str(self.flowid)
        if suffix:
            transferid += "." + ".".join(map(str, suffix))

We can see that flowid is used.

**Comment by mgqa34** [comment]
@sookieqin We check the code and find out that because  secureboost's transfer_variable' name is 'transfer_inst' instead of 'transfer_variable', whose flowid  remain's zero forever, as it will not be change by modelbase' set_flowid method, and it will only influence stop_tag transfer.  
https://github.com/FederatedAI/FATE/blob/master/federatedml/model_base.py#L193

Thanks very much for pointing out this bug, it will be fixed in next version soon.
