### ISSUE TITLE
What's the detailed differences between standalone mode and cluster mode?

### ISSUE THREAD

**Issue by yongrl** [FederatedAI/FATE#812]
I can't understand the standalone mode and cluster mode , Can anybody explain it more detailed?

**Comment by HelloLadsAndGents** [comment]
standalone mode means you have only one server which your guest service and host service runs on 
cluster mode means you have several servers and you can run services on different servers
just my opinion

**Comment by yongrl** [comment]
@HelloLadsAndGents , thank you for your apply, but it confused me that the differences between allinone mode and standalone mode? Does standalone mode  host and guest must in one machine?

**Comment by weiwee** [comment]
> 

1. differences between allinone mode and standalone mode?
same in runtime, different in deploy

2. does standalone mode host and guest must in one machine?
yes, standalone mainly design for test and development
