### ISSUE TITLE
fateboard system error

### ISSUE THREAD

**Issue by ZhiyuanDang** [FederatedAI/FATE#822]
之前用的1.0.2，build_standalone_docker.sh 方式安装的，看到出了新版本1.1，所以换成了最新版。但是在跑一些大规模或者是高维数据集的时候老是failed，卡在dataio那里，错误信息大概是security pool abruptly kill when the future什么什么的，忘了保存了。除此之外还会有一个错误，就是evaluation那里又只有train的结果，一直是有这俩个错误，也没找到其他解决办法。只能换回1.0.2，现在是container都激活了，python quick_run.py也能运行，但是fateboard(127.0.0.1:8080)一直是新版的界面，提示system error，重试了好几次都一样，现在是要改什么东西吗？

**Comment by happycooperxu** [comment]
你好， 请问你切换不同版本的时候，docker容器和镜像是否清理干净？ 既然fateboard还是新版的界面，说明他还是用新版的容器和镜像启动的

**Comment by happycooperxu** [comment]
> 之前用的1.0.2，build_standalone_docker.sh 方式安装的，看到出了新版本1.1，所以换成了最新版。但是在跑一些大规模或者是高维数据集的时候老是failed，卡在dataio那里，错误信息大概是security pool abruptly kill when the future什么什么的，忘了保存了。除此之外还会有一个错误，就是evaluation那里又只有train的结果，一直是有这俩个错误，也没找到其他解决办法。只能换回1.0.2，现在是container都激活了，python quick_run.py也能运行，但是fateboard(127.0.0.1:8080)一直是新版的界面，提示system error，重试了好几次都一样，现在是要改什么东西吗？

你好， 请问你切换不同版本的时候，docker容器和镜像是否清理干净？ 既然fateboard还是新版的界面，说明他还是用新版的容器和镜像启动的

**Comment by ZhiyuanDang** [comment]
> > 之前用的1.0.2，build_standalone_docker.sh 方式安装的，看到出了新版本1.1，所以换成了最新版。但是在跑一些大规模或者是高维数据集的时候老是failed，卡在dataio那里，错误信息大概是security pool abruptly kill when the future什么什么的，忘了保存了。除此之外还会有一个错误，就是evaluation那里又只有train的结果，一直是有这俩个错误，也没找到其他解决办法。只能换回1.0.2，现在是container都激活了，python quick_run.py也能运行，但是fateboard(127.0.0.1:8080)一直是新版的界面，提示system error，重试了好几次都一样，现在是要改什么东西吗？
> 
> 你好， 请问你切换不同版本的时候，docker容器和镜像是否清理干净？ 既然fateboard还是新版的界面，说明他还是用新版的容器和镜像启动的

是清理干净的，docker 镜像 用的rmi命令删除的，container用的docker container prune删除的。fate_fateboard没法看修改日期，fate_python确实是9月24号的更新。

**Comment by ZhiyuanDang** [comment]
![image](https://user-images.githubusercontent.com/17498125/70257552-73fa4880-17c5-11ea-8650-512239fa1912.png)
docker container logs fate_fateboard一直报这个错误。这次是又重新装了一次。

> > 之前用的1.0.2，build_standalone_docker.sh 方式安装的，看到出了新版本1.1，所以换成了最新版。但是在跑一些大规模或者是高维数据集的时候老是failed，卡在dataio那里，错误信息大概是security pool abruptly kill when the future什么什么的，忘了保存了。除此之外还会有一个错误，就是evaluation那里又只有train的结果，一直是有这俩个错误，也没找到其他解决办法。只能换回1.0.2，现在是container都激活了，python quick_run.py也能运行，但是fateboard(127.0.0.1:8080)一直是新版的界面，提示system error，重试了好几次都一样，现在是要改什么东西吗？
> 
> 你好， 请问你切换不同版本的时候，docker容器和镜像是否清理干净？ 既然fateboard还是新版的界面，说明他还是用新版的容器和镜像启动的

**Comment by weiwee** [comment]
feel free to reopen if issue still persist
