### ISSUE TITLE
what happen when upload different csv with the same table_name, namespace

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE#823]
1) May I know if we re-use the same table_name and namespace when uploading a CSV files. Will the latest upload replace the old file when we train a model?
For example,
first time upload, CSV looks like.  x1,x2,y
second time upload, CSV looks like, x1,x2,x3,x4,y

2) Does the egg service has any versioning system?

3) Is it possible to integrate egg service with Azure Blobstore so that the egg service will not get out of disk space? 

4) Anyway to archieve old data (csv) in egg service to external backup system  (external hard disk) and load back into egg service when require in the future?

**Comment by maxwong** [comment]
1. dtable is kv based. Currently no duplicate key is allowed. If you upload data with same namespace and name, and if the keys are the same (or keys in new table are a superset on the old table), old values will be overridden; If the keys or some of the keys are not the same, old data will still in the dtable.

2. The storage service is based on LMDB. LMDB has a MVCC (Multi-Version Concurrency Control) mechanism which solves concurrent access in runtime. We suggest users maintain their application data for specific needs.

3. Maybe networking overhead is quite high? 

4. Storage system in Eggroll is file based. If a dtable is properly closed, you can directly backup the data file. But as for future use, you may need to reconstruct the metadata (i.e. a eggroll.table call).
