### ISSUE TITLE
 About calculation of bounding box coordinates in object detection

### ISSUE THREAD

**Issue by ssdyue** [FederatedAI/FATE#825]
research/federated_object_detection_benchmark/data/generate_task_json.py
```
def convert(size, box):
    dw = 1. / (size[0])
    dh = 1. / (size[1])
    x = (box[0] + box[1]) / 2.0 - 1
    y = (box[2] + box[3]) / 2.0 - 1
    w = box[1] - box[0]
    h = box[3] - box[2]
    x = x * dw
    w = w * dw
    y = y * dh
    h = h * dh
    return x, y, w, h
```
Why the x and y calculations here are subtracted by 1 ?

**Comment by jiahuanluo** [comment]
@ssdyue This is a question of zero-based or one-based of coordinates.
We assume the coordinates of the bounding box are one-based. 
Refer to the same [question](https://github.com/pjreddie/darknet/issues/341) in darknet.

**Comment by ssdyue** [comment]
@jiahuanluo thanks, I got it.
