### ISSUE TITLE
Can't check task in fate-board

### ISSUE THREAD

**Issue by JustcallmeTuner** [FederatedAI/FATE#826]
I want to check my task in fate-board after I execute python quick_run.py(docker_standalone) and task finished. But I find 404 when I use the fate-board url .  Can anyone tell me what should I do next?  
ubuntu 18.04
docker version 18.06.3-ce
docker-compose version 1.24.0

**Comment by KathyKing** [comment]
http://{fateboard-ip}:8080

**Comment by JustcallmeTuner** [comment]
@KathyKing 

> http://{fateboard-ip}:8080
Thanks a lot. 
There is "Please check your task in fate-board, url is : http://172.18.0.2:8080/index.html#/dashboard?job_id=201912060818188813183&role=guest&party_id=10000" in the terminal. 
what is {fateboard-ip}? Is "http://172.18.0.2" or "http://172.18.0.2:8080/index.html#/dashboard?job_id=201912060818188813183&role=guest&party_id=10000 "? I try it again, but not work.

**Comment by ZhiyuanDang** [comment]
if you build the FATE with standalone settings, you could check the fateboard at 127.0.0.1:8080.

**Comment by JustcallmeTuner** [comment]
@ZhiyuanDang  Thank you very much. It ｗorked!
