### ISSUE TITLE
query for all tables

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE#827]
Can party_id = A (fate_flow_client) query party_id= B to get a list of all table name and namespace uploaded successfully?

can this https://github.com/FederatedAI/FATE/blob/9d1d9010cbad9943a7657eed248069f0ed6160ee/fate_flow/doc/fate_flow_rest_api.md  be used to query another party's information. 

I have a scenario where as a party A, I would like to know table,namespace uploaded by party B. What is your advice?

**Comment by zhihuiwan** [comment]
At present, there is no interface for querying the list of successfully uploaded table names and namespaces. Version 1.2 only provides an interface for querying the list of table names and namespaces uploaded by itself. For the query of other parties, it does not currently provide an interface.

**Comment by dylan-fan** [comment]
This is an unsafe operation which party A  can query info<name, namespace> in party B.
