### ISSUE TITLE
prediction

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE#829]
**Test Scenario 1**
--------
**trainning:**
guest 10000
host 10000
arbiter 9997 (submit job)

**predict (no issue)**
guest 10000
host 10000
arbiter 9997  (submit job)

**predict (has issue)**
guest 10000
host 9999 (fateboard show: party id 9999 is unknown, can not extract component dependency); `I cannot find the jod-id directory inside /logs  `
arbiter 9997  (submit job)

**Test Scenario 2**
--------
**trainning:**
guest 10000
host 99999
arbiter 9997  (submit job)

**predict (has issue)**
guest 10000
host 10000 (fateboard show: party id 10000 is unknown, can not extract component dependency)
arbiter 9997  (submit job)

**predict (no issue)**
guest 10000
host 9999
arbiter 9997  (submit job)

Is party_id during training must be the same during predict ?

**Comment by mgqa34** [comment]
partyid should be same now in both training and predicting process
