### ISSUE TITLE
Can't start modeling task.

### ISSUE THREAD

**Issue by JustcallmeTuner** [FederatedAI/FATE#843]
1.I have uploaded data (Firstly  python ../fate_flow_client.py -f upload -c upload_data.json(guest) ;Then python ../fate_flow_client.py -f upload -c upload_data.json(host) ).  And the status is success in fate_board.
2. I started my modeling task, but failed.(python ../fate_flow_client.py -f Submit_job -d hetero_logistic_regression / test_hetero_lr_train_job_dsl.json -c hetero_logistic_regression / test_hetero_lr_train_job_conf.json) The retmsg is success in terminal, however the status is failed in fate_board. 
I checked the guest task's log, ERROR: Count of data_instance is 0" 
In addition, when I run the "python quick_run.py "  the status is success in fate_board. 
Can anyone help me ???
FATE:standalone
task:hetero_logistic_regression
ubuntu 18.04
docker version 18.06.3-ce
docker-compose version 1.24.0

**Comment by KathyKing** [comment]
If the "count of data" instance is 0 "appears in the log, it means that the role side has not imported data, or there is a problem with data configuration

**Comment by JustcallmeTuner** [comment]
@KathyKing Thanks very much.  I checked my data configuration and found no problem. Can you tell me the correct steps to achieve the hetero_lr task without quick_run.py?

**Comment by JustcallmeTuner** [comment]
@KathyKing  I finally solved the problem. The reason is that table_name and space_name are inconsistent with the config setting. Thanks again ~
