### ISSUE TITLE
input data's schema for fit and transform should be same

### ISSUE THREAD

**Issue by JustcallmeTuner** [FederatedAI/FATE#857]
hetero_lr_task.
guest_tarin_data: breast_b((id:0-499) total:500) host_train_data:breast_a((id:0-499) total:500)
guest_eval_data: breast_b((id:500-568) total:69) host_eval_data:breast_a((id:500-568) total:69)
My Step:
1. upload_guest_train_data
2. upload_host_train_data
3. start modeling (I add the 'need_deploy'=[true] to the xxx_dsl.json)
4. upload_guest_eval_data
5. upload_host_eval_data
6. predict 

step 1-5 is success in fate_board.
I checked the the error log of 'step6.predict' and found there is an error about "input data's schema for fit and transform should be same".
Can anybody help me to solve this problem?

**Comment by tanmc123** [comment]
@JustcallmeTuner  Please have a check about whether the dimension of features are matched between the train and test set.  This info can be shown on fateboard directly. Check the data output of the upstream component of the errored component. This might provide you some cues. 

If that still not work, please show us your dsl and conf files. Let's see if we can find something.

Hope that is useful for you.

**Comment by JustcallmeTuner** [comment]
Tanks, it still not work, are you in the weichat group? How can I send you my data and conf.json?

**Comment by JustcallmeTuner** [comment]
Here are data and config files. 链接: https://pan.baidu.com/s/138eq7yhkonFbBWs2U_DwrQ 提取码: 413h
