### ISSUE TITLE
FATE Stand-alone Deployment  using Docker Fialed

### ISSUE THREAD

**Issue by MakingL** [FederatedAI/FATE#859]
**Describe the bug**
我按照 “Install FATE using Docker Chinese guide” 中的操作部署 Fate，但是并没有部署成功，查看日志发现有关于数据库连接的错误。

I deployed Fate according to the instructions in the "Install FATE using Docker Chinese guide", but the deployment was not successful. I checked the logs and found that there are errors about the database connection.

**To Reproduce**
1. 获取安装包
2. `cd docker_standalone-fate-1.1.1`
3. `bash install_standalone_docker.sh`

**Screenshots**
![TIM截图20191217144147](https://user-images.githubusercontent.com/31580426/70972039-67d38c80-20dd-11ea-8536-fddb3de15bdb.png)

![TIM截图20191217144236](https://user-images.githubusercontent.com/31580426/70972043-6ace7d00-20dd-11ea-9962-94896bfbb9b5.png)

![TIM截图20191217144419](https://user-images.githubusercontent.com/31580426/70972048-6d30d700-20dd-11ea-8380-568f5143fcc3.png)

![TIM截图20191217144454](https://user-images.githubusercontent.com/31580426/70972013-5b4f3400-20dd-11ea-9499-05f406f073c6.png)

![TIM截图20191217150003](https://user-images.githubusercontent.com/31580426/70972264-f2b48700-20dd-11ea-9110-c0059a82da8b.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser:  chrome

**Additional context**

![TIM截图20191217145903](https://user-images.githubusercontent.com/31580426/70972202-cbf65080-20dd-11ea-9688-ea797d57eb00.png)

**Comment by KathyKing** [comment]
It is recommended to redeploy，Sqlitedb not created

**Comment by MakingL** [comment]
部署失败后，我尝试过重新运行 `bash install_standalone_docker.sh` ，但还是部署失败。我应该清除哪些环境后再重新部署呢？重装操作系统还是只需要删除相关的 Docker Image 即可？
   由于我的操作系统是虚拟机中新建的主机，除了 Docker 和 Docker-Compose和一些必要的工具软件，没有安装其他的软件，是不是有其他的软件我需要提前安装的呢？

After the deployment failed, I tried to run `bash install_standalone_docker.sh` again, but the deployment still failed. What system environments should I clear before redeploying? Reinstall the operating system or just delete the related Docker Image?
Since my operating system is a newly created host in the virtual machine, except for Docker and Docker-Compose and some necessary tool software, no other software is pre-installed. Is there any other software I need to pre-install?

**Comment by brucesunxi** [comment]
我也遇到了这个问题，不知道如何处理
