### ISSUE TITLE
task always waiting in fate board

### ISSUE THREAD

**Issue by Chenfengldw** [FederatedAI/FATE#866]
**Describe the bug**
Run python quick_run.py in fate_python container,  and successfully submited with retcode=0; Then go to check the fate board, there are 5 tasks always waiting.

**To Reproduce**
```
1. Go into fate_python container
2. cd to examples/federatedml-1.x-examples
3. run  python quick_run.py
```

**Expected behavior**

**Screenshots**
pload data config json: {'file': 'examples/data/breast_b.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'breast_b', 'namespace': 'breast_b_guest'}
stdout:{
    "data": {
        "board_url": "http://172.19.0.2:8080/index.html#/dashboard?job_id=2019121902313029842018&role=local&party_id=0",
        "job_dsl_path": "/fate/jobs/2019121902313029842018/job_dsl.json",
        "job_runtime_conf_path": "/fate/jobs/2019121902313029842018/job_runtime_conf.json",
        "logs_directory": "/fate/logs/2019121902313029842018",
        "namespace": "breast_b_guest",
        "table_name": "breast_b"
    },
    "jobId": "2019121902313029842018",
    "retcode": 0,
    "retmsg": "success"
}

Upload data config json: {'file': 'examples/data/breast_a.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'breast_a', 'namespace': 'breast_a_host'}
stdout:{
    "data": {
        "board_url": "http://172.19.0.2:8080/index.html#/dashboard?job_id=2019121902313356609719&role=local&party_id=0",
        "job_dsl_path": "/fate/jobs/2019121902313356609719/job_dsl.json",
        "job_runtime_conf_path": "/fate/jobs/2019121902313356609719/job_runtime_conf.json",
        "logs_directory": "/fate/logs/2019121902313356609719",
        "namespace": "breast_a_host",
        "table_name": "breast_a"
    },
    "jobId": "2019121902313356609719",
    "retcode": 0,
    "retmsg": "success"
}

dsl_path: /fate/examples/federatedml-1.x-examples/user_config/train_dsl.config_1576722696_7233, conf_path: /fate/examples/federatedml-1.x-examples/user_config/train_conf.config_1576722696_4370
stdout:{
    "data": {
        "board_url": "http://172.19.0.2:8080/index.html#/dashboard?job_id=2019121902313674034120&role=guest&party_id=10000",
        "job_dsl_path": "/fate/jobs/2019121902313674034120/job_dsl.json",
        "job_runtime_conf_path": "/fate/jobs/2019121902313674034120/job_runtime_conf.json",
        "logs_directory": "/fate/logs/2019121902313674034120",
        "model_info": {
            "model_id": "arbiter-10000#guest-10000#host-10000#model",
            "model_version": "2019121902313674034120"
        }
    },
    "jobId": "2019121902313674034120",
    "retcode": 0,
    "retmsg": "success"
}
![Screen Shot 2019-12-19 at 10 41 33 AM](https://user-images.githubusercontent.com/12796718/71140461-42b15c00-224c-11ea-8331-c7be1b2a35c7.png)

**Comment by zhihuiwan** [comment]
Hello, please check the logs/fate_flow/ERROR.log error message, this situation is usually caused by redis exception

**Comment by VincyChen96** [comment]
Have you fixed it? I also met the same problem.
