### ISSUE TITLE
[hetero linear regression] The host sends its "forwards" and "loss_regular" directly without encryption

### ISSUE THREAD

**Issue by SamuelGong** [FederatedAI/FATE#869]
**Describe the bug**
Have a look at [Line 131](https://github.com/FederatedAI/FATE/blob/efae2b1add20d9f98ac05a669298e36369f91497/federatedml/optim/gradient/hetero_linr_gradient_and_loss.py#L131) of File [hetero_linr_gradient_and_loss](https://github.com/FederatedAI/FATE/blob/master/federatedml/optim/gradient/hetero_linr_gradient_and_loss.py). This is where the Host compute part of the loss (in your word, loss intermediate). Note that **"forwards" is plain text**, and hence the result "self_wx_square" is also plain text. As a result, the guest will know the intermediate loss of the host.

Similar also happen at [Line 134](https://github.com/FederatedAI/FATE/blob/efae2b1add20d9f98ac05a669298e36369f91497/federatedml/optim/gradient/hetero_linr_gradient_and_loss.py#L134) of the same file. Note that **"loss_regular" is plain text as well**.

**To Reproduce**
One can simply add a line following [Line 131](https://github.com/FederatedAI/FATE/blob/efae2b1add20d9f98ac05a669298e36369f91497/federatedml/optim/gradient/hetero_linr_gradient_and_loss.py#L131) to print the type of the variable `self_wx_square`. According to my test, it is `numpy.float64`. The same thing happens with the variable `loss_regular` when I added a line following [Line 134](https://github.com/FederatedAI/FATE/blob/efae2b1add20d9f98ac05a669298e36369f91497/federatedml/optim/gradient/hetero_linr_gradient_and_loss.py#L134) to check its type.

**Expected behavior**
We should **encrypt "self_wx_square" and "loss_regular" before sending it to the guest**. In other words, the type of `self_wx_square` and `loss_regular` are both expected to be `Federatedml.secureprotol.fate_paillier.PaillierEncryptedNumber` (or something like that depending on the encryption method we use).

**Additional context**
You may not notice the problem before, as these bugs **do not harm the precision of the loss**. This is because the intermediate loss of the host, though not encrypted at the host, will be encrypted at the guest before producing the final encrypted loss.

**Comment by tanmc123** [comment]
@SamuelGong Thanks for you feedback. We have checked this bug report and find that the "self_wx_square" and "loss_regular" are not encrypted indeed. These two values are two statistical intermediate variables which leak few data information. 

However, it still makes more sense to encrypt them before transmission. We will fix this problem in next version. Thank you again for pointing out this problem for us.

**Comment by nemirorox** [comment]
Fixed in FATE-1.2 357af97
