### ISSUE TITLE
Can't execute the predict task

### ISSUE THREAD

**Issue by JustcallmeTuner** [FederatedAI/FATE#887]
hetero_lr_task.
guest_tarin_data: breast_b((id:0-499) total:500) host_train_data:breast_a((id:0-499) total:500)
guest_eval_data: breast_b((id:500-568) total:69) host_eval_data:breast_a((id:500-568) total:69)
My Step:

upload_guest_train_data
upload_host_train_data
start modeling (I add the 'need_deploy'=[true] to the xxx_dsl.json)
upload_guest_eval_data
upload_host_eval_data
predict
step 1-5 is success in fate_board.
I checked the the error log of 'step6.predict' and found there is an error about "input data's schema for fit and transform should be same".
Can anybody help me to solve this problem?
Here are data and config files. 链接: https://pan.baidu.com/s/138eq7yhkonFbBWs2U_DwrQ 提取码: 413h

**Comment by tanmc123** [comment]
Same with #925
