### ISSUE TITLE
[logistic_regression_param] Make it More Elegant

### ISSUE THREAD

**Issue by SamuelGong** [FederatedAI/FATE#928]
**Is your feature request related to a problem? Please describe.**
Just a subtle engineering problem.
Have a look at [Line 111](https://github.com/FederatedAI/FATE/blob/master/federatedml/param/logistic_regression_param.py#L111) of the file `federatedml/param/logistic_regression_param`. You have defined a prefix, however, you have not used it at most of the rest of the code. Instead, you would rather code "logistic_param's ..." in the exception raise clause. Like [Line 117](https://github.com/FederatedAI/FATE/blob/master/federatedml/param/logistic_regression_param.py#L117) of the same file, and so as most of them.

**Describe the solution you'd like**
Clearly just substitude those `"logistic_param's` with `descr + "`. If you like, also do the same thing for the class `HomoLogisticParam` which follows the definition of `LogisticParam`, though the appearances of `logistic_param's` are not too many.

**Additional context**
Thanks for the attention.

**Comment by tanmc123** [comment]
@SamuelGong OK, good suggestion, thanks.
