### ISSUE TITLE
push job into queue failed

### ISSUE THREAD

**Issue by newne** [FederatedAI/FATE#930]
**Describe the bug**
when I upload guest data, it returns "push job into queue failed" and no error logs . My commond is :
python fate_flow/fate_flow_client.py -f upload -c examples/federatedml-1.x-examples/upload_guest.json
I have checked all service status is up.

**Comment by KathyKing** [comment]
plaese check, whether redis is started

**Comment by newne** [comment]
All process are successful, but I found guest node can't connect redis-server .  The problem was solved  through redeployment.
