### ISSUE TITLE
How to use one-vs-rest in "Logistic Regression" algorithm?

### ISSUE THREAD

**Issue by lynnprosper** [FederatedAI/FATE#934]
First thank you for your focus.
It is said LR algorithm supports one-vs-rest multi-classification in the doc.
But I am confused for how to use this function or where to add the parameter.
Could you tell me something more?

Best wishes.
2020.1.11

**Comment by tanmc123** [comment]
@lynnprosper Here is an example of using one-vs-rest in LR: https://github.com/FederatedAI/FATE/blob/master/examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_one_vs_rest_job_conf.json#L81

Actually, LR will recoginize whether your data have more than 2 classes. If so, it will start one-vs-rest automatically.
