### ISSUE TITLE
SPARK_HOME not found

### ISSUE THREAD

**Issue by linjieccc** [FederatedAI/FATE#938]
Hi, I deployed FATE 1.2 using docker deploy. When I test the spark backend it raise an error:

Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/driver/task_scheduler.py", line 318, in start_task
    raise EnvironmentError("SPARK_HOME not found")
OSError: SPARK_HOME not found

Dose it mean that I should deploy spark+hadoop manually to use the spark backend?
Thanks!

**Comment by linjieccc** [comment]
If Yes, should I deploy spark+hadoop in the containers of "federatedai/python:1.2.0-release" in both guest and host devices, or other containers?

**Comment by weiwee** [comment]
@linjieccc you should deploy spark manually, both for guest and  and host devices.

**Comment by weiwee** [comment]
no further response, close this issue
