### ISSUE TITLE
如何进行多方计算的部署？比如说有 a、b、c 三个节点，应该怎么部署FATE环境？

### ISSUE THREAD

**Issue by lichaoliang1** [FederatedAI/FATE#944]
请问，如何进行多方计算的环境部署？
看当前部署教程是以两个节点举例的，那比如说有 a、b、c 三个节点，应该怎么部署FATE环境？有相关教程吗？
谢谢

**Comment by KathyKing** [comment]
没有多方部署，以两方扩展

**Comment by lichaoliang1** [comment]
> 没有多方部署，以两方扩展

以两方扩展是什么意思？能大概说明一下多节点（假如3个）的部署流程和使用方法吗？
