### ISSUE TITLE
ModuleNotFoundError: No module named 'eggroll.api'; 'eggroll' is not a package

### ISSUE THREAD

**Issue by Pysion-lin** [FederatedAI/FATE#945]
when i try to start cluster mode,the fate_flow's status is stop and fate_flow server can't run.(sh /data/projects/fate/services.sh all start)
under  /data/projects/fate/python/logs/error.log ,the issues is ModuleNotFoundError: No module named 'eggroll.api'; 'eggroll' is not a package.so I think it missing eggroll package or /data/projects/fage/python/arch/api/eggroll is incomplete.

**Comment by itboyljm** [comment]
> when i try to start cluster mode,the fate_flow's status is stop and fate_flow server can't run.(sh /data/projects/fate/services.sh all start)
> under /data/projects/fate/python/logs/error.log ,the issues is ModuleNotFoundError: No module named 'eggroll.api'; 'eggroll' is not a package.so I think it missing eggroll package or /data/projects/fage/python/arch/api/eggroll is incomplete.

Hello, the problem says you are missing the package eggroll.api, that is, you need to deploy eggroll. Check if there is a directory: $FATE_DIR/eggroll and then check your pythonpath. Pythonpath needs both eggroll and fate path.

**Comment by Pysion-lin** [comment]
I have detected the Pythonpath and confirmed that there is no such path. Even if I manually add the path, the error will be reported.$FATE_DIR/eggroll is empty.
