### ISSUE TITLE
Support HeteroFM Algorithm

### ISSUE THREAD

**Issue by peiyong86** [FederatedAI/FATE#958]
**Is your feature request related to a problem? Please describe.**
In fate' version >= 1.3, Hetero FM will be support.

**Comment by xiaoToby** [comment]
I want to know, the function is only run on version 1.3？ Becauese I tried it on version 1.4.0, there is an error on DataIO，it shows "lmdb.Error: Attempt to operate on closed/deleted/dropped object." . The reason that I want to try rec on version 1.4.0, I think the fateboard is more friendly on showing the results of predict function,it will show a chart. And I want to which version can be used that I can try federeated algorithm expect version 1.3
