### ISSUE TITLE
How to eliminate the noise effect of Party A in Hetero-NN? BTW, the reference 2 cannot be found.

### ISSUE THREAD

**Issue by zhanyueluoxuanwan** [FederatedAI/FATE#969]
Hetero-NN related.

How to eliminate the noise effect of Part A in the interaction layer, i.e. epsilon_acc * alpha_A? Could it be added in the readme?

By the way, the reference 2: "Deep Neural Network for Collaborative Machine Learning with Additively Homomorphic Encryption" cannot be found. Could you offer a valid link?

Thank you.

**Comment by mgqa34** [comment]
W' = W - epsilon_acc(W' is the weight mixed with noise, W is the true weight). In forward process,  W' * alpha_A = (W - epsilon_acc) * alpha_A = W * alpha_A - epsilon_acc * alpha_A， so we add 'epsiion_acc * alpha_A' after party B sending this result and its decyption

**Comment by zhanyueluoxuanwan** [comment]
Got it. But it seems a mistake in the readme and figure for this part.

By the way, how to get this final equation?  W_A -= eta * (delta_act * W_A + epsilon_B + epsilon_A / eta) - epsilon_B = eta * delta_act * W_A - epsilon_B = W_TRUE - epsilon_acc. It is not easy to get this.

**Comment by zhanyueluoxuanwan** [comment]
By the way, I also find a curious part: Step 3 in forward propagation seems useless because A can directly sends epsilon_acc * alpha_A to B. It doesn't need z_A + epsilon_B instead. Is there something missing?

**Comment by zhanyueluoxuanwan** [comment]
By the way, W_A -= eta * (delta_act * W_A + epsilon_B + epsilon_A / eta) - epsilon_B = eta * delta_act * W_A - epsilon_B = W_TRUE - epsilon_acc. This equation also differs from the figure.
