### ISSUE TITLE
How to do a task with the result of another task?

### ISSUE THREAD

**Issue by czzmmc** [FederatedAI/FATE#970]
I am wondering a scenario about Fate. Like, I already have done the intersection of two sets coming from host and guest, but I do not add train into that work flow, and now I want to do the training based on that intersection result. Is there some way? I'v already seen that if I want to make a model, I need to write the whole work flow at the very beginning. What if I don't? I just want to reuse some data I already created. Hope someone gives me help.

**Comment by mgqa34** [comment]
In Fate 1.2 or earlier，the task can't reuse the result of another task. So you may write a script to collect the interaction results and make training data yourself, then submit another training job. But in Fate 1.3, the result of some component can be reused as the data' (name, namespace) can be obtained from fate_flow' cli.
