### ISSUE TITLE
How to split data into training and testing data before training?

### ISSUE THREAD

**Issue by czzmmc** [FederatedAI/FATE#972]
I want to train and test model using FATE. From the FATE doc, I don't find the way about how to split data into training and testing data by conf file. Does that mean I could only upload another data set as testing data? Or is there some easy way that I can upload the data once and use it as training and testing data?

**Comment by mgqa34** [comment]
FATE does not support split data during training process, so you should upload another data and run another task.  We will enhance this function in later version of FATE, thanks for your using.
