### ISSUE TITLE
error when running quick_run.py

### ISSUE THREAD

**Issue by Mantj** [FederatedAI/FATE#985]
**Describe the bug**
Hi, I am new to FATE, and I'm trying to follow Guide. I install FATE in Host successfully, but when I execute `python standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/quick_run.py`, I first get some output:
> Upload data config json: {'file': 'examples/data/default_credit_homo_guest.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'default_credit_homo_guest', 'namespace': 'default_credit_homo_guest_guest'}

But then I get an error:
> stdout:Traceback (most recent call last):
  File "/home/rong/standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/../../fate_flow/fate_flow_client.py", line 27, in <module>
    from arch.api.utils import file_utils
ModuleNotFoundError: No module named 'arch.api'

But I had install arch model and it's version is 4.13, I don't know what happen. Please help~~

**To Reproduce**
1. Go to 'standalone-fate-master-1.2.0/examples/federatedml-1.x-examples/'
2. Click on 'python quick.py'
3. See error

**Expected behavior**
I want to have some suggestion!

**Desktop (please complete the following information):**
 - OS: Linux [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
 - Version python3.6.0

**Comment by dylan-fan** [comment]
please check your pythonpath

**Comment by Mantj** [comment]
> please check your pythonpath

I had doublecheck my pythonpath. 
I find that I can import arch in python environment, but I **cannot** from arch.api.utils import file_utils, it also error:
`No module named 'arch.api'`

I wonder if I installed wrong version of model arch? I use `pip install arch` to install model arch, is that correct?

**Comment by Mantj** [comment]
I think the **arch model** I had installed is : https://github.com/bashtage/arch
is it right?

**Comment by mgqa34** [comment]
@Mantj  execute "echo $PYTHONPATH" , and check if this includes the parent directory of arch(where you put your code of FATE projects". Hope this will be helpful.

**Comment by Mantj** [comment]
@mgqa34 it's helpful, thanks a lot!
